### ISSUE TITLE
"Dotnet restore" references 1.0.0-rc3-002832

### ISSUE THREAD

**Issue by CarlosTorrecillas** [dotnet/cli#3224] opened 2016-05-24 19:57 UTC
## Steps to reproduce

On Mac OS:

- Get the SDK from GitHub (https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-dev-osx-x64.latest.pkg)
- Follow the steps to create a new app: https://www.microsoft.com/net/core#macosx
- You can either try to debug using VS Code or run it through the console you get the following message:

error NU1001: The dependency Microsoft.NETCore.App >= 1.0.0-rc3-002832 could not be resolved.

## Expected  behavior

I would expect the program to compile and print "Hello World!"

## Actual behavior

error NU1001: The dependency Microsoft.NETCore.App >= 1.0.0-rc3-002832 could not be resolved.

Note that if I change the version in the project.json to "version": "1.0.0-rc2-3002702":

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

Which is the latest version I can find of the Microsoft.NETCore.App package: https://www.nuget.org/packages/Microsoft.NETCore.App/  and then I run again "dotnet restore" then I'm able to run the application successfully.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002832)

Product Information:
 Version:            1.0.0-preview2-002832
 Commit SHA-1 hash:  7f26270354

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by ellismg** [comment] 2016-05-25 04:47
This is by design.  The daily builds of CLI (which is what's present at https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-dev-osx-x64.latest.pkg reference the latest version of the Microsoft.NETCore.app package (which is the version that will eventually become 1.0 RTM).

https://github.com/dotnet/cli/blob/9155fbfbdbcb03877fc7b6e8a880b911c2e90449/Documentation/known-issues.md#on-dev-builds-of-the-tools-restoring-default-project-from-dotnet-new-fails explains how you can use a NuGet.config to work around this issue (by pointing NuGet at our dev feed that has these packages)

**Comment by blackdwarf** [comment] 2016-05-25 15:41
@CarlosTorrecillas since this is a by design behavior and @ellismg has pointed to the documentation that explains what needs to be done here, I will close this issue.

**Closed by blackdwarf** 2016-05-25 15:41 UTC
