### ISSUE TITLE
Improve Error Message when using backslashes in Global.json

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1035] opened 2016-01-26 01:20 UTC
Tested this out on Windows 10 with this path in global.json:

`C:\Users\brthor\code\cli_args\artifacts\tests\..\..\src`

Only error message is this, very misleading:

`Invalid charactor escape syntax. Unexpected \85.`

I imagine, depending on the character following the first `\`, this error would change

Why don't we support backslashes on Windows?

cc @anurse @davidfowl

**Comment by anurse** [comment] 2016-01-26 17:22
The problem is that JSON string literals use `\` as a string escaping syntax. So you have to double it up. This is why we try to allow most of our path properties to support `/`. This isn't an issue in our code, it's a limitation of using JSON as the serialization format.

**Comment by brthor** [comment] 2016-01-26 19:01
:+1: Thanks for the quick and clear explanation!
Makes sense now.

**Comment by anurse** [comment] 2016-01-26 19:10
There may be a place for improving the error messaging though, and making it clear that the error is a JSON error while parsing the global.json file.

**Comment by brthor** [comment] 2016-01-26 19:14
Agreed, I'd like to leave this open on the backlog so we can look at it when we have the time.

**Comment by anurse** [comment] 2016-01-26 19:15
:+1:

**Comment by piotrpMSFT** [comment] 2016-07-27 23:00
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

**Closed by piotrpMSFT** 2016-07-27 23:01 UTC
Labels: enhancement
