### ISSUE TITLE
Re-introduce DNX's --debug flag

### ISSUE THREAD

**Issue by couven92** [dotnet/cli#4199] opened 2016-09-18 22:39 UTC
Previously, in DNX, you could run the runtime with the `--debug` flag which prompted the runtime to wait until a debugger attached **BEFORE** it started exeucting the application entry point.

I realize the ``dotnet run` command implements the `-v` flag which outputs the process ID and this does indeed make it easy to attach the debugger to the running process.

Currently the only alternative left is to implement the main function like this:

``` csharp
public static class Program
{
    public static void Main(string[] args)
    {
        System.Console.WriteLine($"Process ID: {System.Diagnostics.Process.GetCurrentProcess().Id}");
        while (!System.Diagnostics.Debugger.IsAttached) ;

        // Really execute application
    }
}
```

There are several potential problems I see for this alternative:
- It is not possible to debug static constructors for the `Program` class as well as any other code that somehow is exeucted before the call to `Main(string[])` without also including the above code in said constructor.
- If above code is placed inside a static construtor, it is difficult to obtain the arguments and thus difficult to conditionally wait for the debugger depending on a command-line argument
- It is annoying having to write the above code each time one wnats to quickly debug an application without creating an entire Visual Studio project / or declaring a VS Code `launch.json` with the appropiate paths.
- In cases where minimal dependency standalone publishing is an issue, the above code **ALWAYS** creates unnecessary dependencies on the `System.Diagnostics.Debug` and `System.Diagnostics.Process` packages. This is even true, if one wraps the above code in an `#if DEBUG` preprocessor as the `project.json` project system does not support configuration-specifc dependencies.

I propose that the `dotnet run` command should have a `--debug` flag that executes something very similar to the code written above **BEFORE** the entry point is called. Secondly, I suggest that the `dotnet <filename>` command should have a similar option.

**Comment by eerhardt** [comment] 2016-09-19 15:01
Looks like a duplicate of https://github.com/dotnet/core-setup/issues/198.  

/cc @gkhanna79 @schellap @blackdwarf

**Comment by piotrpMSFT** [comment] 2016-11-01 07:01
Let's track this in the core-setup repo per @eerhardt's link above. If this is to be implemented it will need to happen at the host level, which comes from core-setup.

**Closed by piotrpMSFT** 2016-11-01 07:01 UTC
