### ISSUE TITLE
Loading dll with AssemblyLoadContext fails with dotnet cli

### ISSUE THREAD

**Issue by joepeer** [dotnet/cli#490] opened 2015-12-14 03:31 UTC
I'm trying to figure out how without the dotnet cli to dynamically load dll.  I would need to be able to load some kind of a plugin.  Something like [Issue 2095](https://github.com/dotnet/coreclr/issues/2095) is talking about.

With dnx I was able to subclass System.Runtime.Loader.AssemblyLoadContext and make things work.
But when I'm simply running my test app with the dotnet run, I end up with

>Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at dnxtest.Program.Main(String[] args)
Access to the path 'testpluginload.dll' is denied.

Here is my project.json
>            "dependencies": {
    					"System.Collections": "4.0.11-beta-23516",
						"System.Console": "4.0.0-beta-23516",
						"System.Linq": " 4.0.1-beta-23516",
						"System.Threading": " 4.0.11-beta-23516",
						"System.Net.Sockets": "4.1.0-beta-23516",
						"System.Runtime.Loader": "4.0.0-beta-23516",
						"System.Net.Primitives": "4.0.11-beta-23516"	
            },

I'm kinda of confused why its giving me this error only with the cli.

Will this type of usage get covered by the cli or should I just stick up with dnx?

**Comment by davidfowl** [comment] 2015-12-14 18:20
I'm seeing this too, the TPA list seems to ruin everything :smile:. 

/cc @gkhanna79

**Comment by gkhanna79** [comment] 2015-12-14 18:34
Is there a repro? If an ALC is instantiated and LoadFromPath attempted against it, it will attempt to return assembly only from the ALC instance.

**Comment by davidfowl** [comment] 2015-12-14 18:47
I don't see any calls to my ALC, so it looks like the TPA is taking over (or something). How do I get tracing for this thing? 

Here's my sample: 

https://github.com/davidfowl/dotnetcli-aspnet5/tree/davidfowl/hot-reload/dynamic-reload

**Comment by gkhanna79** [comment] 2015-12-14 19:14
@davidfowl LoadFromAssemblyName is implemented to call into the custom Load implementation provided by you. there is no TPA coming into the picture yet. You dont see Console.WriteLine in your Load implementation?

**Comment by gkhanna79** [comment] 2015-12-14 23:16
@davidfowl Please share a repro for this.

**Comment by joepeer** [comment] 2015-12-14 23:56
I think I found out what was causing my error.  I think it has to do with this dependency 
>"Microsoft.NETCore.Runtime": "1.0.1-beta-*",

As soon as I add it to my project.json it now works.  

Can't even figure from which repo this dependency is from...  I'm kinda lost.

This dependency is now mandatory?

Will subclassing AssemblyLoadContext will allow me to load native image by calling LoadFromNativeImagePath?

**Comment by gkhanna79** [comment] 2015-12-14 23:59
That will pull in CoreCLR - it always was required except DNX used to pull it in behind the scenes.

@davidfowl can comment on details.

**Comment by davidfowl** [comment] 2015-12-15 07:52
@gkhanna79 I'm seeing everything fail to load when I call Load on my custom load context. I get a single call and return a file:

https://github.com/davidfowl/dotnetcli-aspnet5/blob/davidfowl/hot-reload/dynamic-reload/DynamicLoadContext.cs#L58

Then it just says this:

```
Load(System.Runtime, Culture=neutral, PublicKeyToken=null)
LoadFromAssemblyPath(/Users/dfowler/.dnx/packages/System.Runtime/4.0.21-rc2-23611/lib/DNXCore50/System.Runtime.dll)

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at DynamicReloader.DynamicLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at DynamicReloader.Program.Main(String[] args)
Abort trap: 6
```

**Comment by andschwa** [comment] 2015-12-16 20:11
I've also recently had issues with `LoadFromPath`, which fails with a similar exception you see @davidfowl, and `LoadFromAssemblyName` simply seg-faults. This is using a custom `AssemblyLoadContext` with the latest `dotnet-core` MyGet feed packages (yesterday) on Ubuntu 14.04.

What's more, I have a custom native host as well, which might help to rule out some potential causes.

**Comment by gkhanna79** [comment] 2016-01-04 23:07
@davidfowl is this still a problem? If so, are you able to repro this on Windows?

**Comment by gkhanna79** [comment] 2016-01-14 00:34
@davidfowl @andschwa Let me know if this is still an issue. Keep in mind that LoadFromAssemblyPath needs to specify assemblies that are *not* on TPA list. Otherwise, their load is blocked by design.

**Comment by gkhanna79** [comment] 2016-01-14 16:33
Here is the repro I constructed, which compiled and executed successfully with CLI:

https://gist.github.com/gkhanna79/271d90f49b74d1336fc1

**Comment by andschwa** [comment] 2016-01-14 17:46
@gkhanna79 Ah, that would be what I saw then. Since it's a `dotnet-cli` published app, all the assemblies at start are in the TPA. The app then *reloads* them (by path!) to cache the types in the assemblies. I'll see if I can fix the logic so that it doesn't use the path to load them.

Thanks for the information.

**Comment by davidfowl** [comment] 2016-01-14 17:47
@gkhanna79 We need to make the TPA list unspecial

**Comment by gkhanna79** [comment] 2016-01-15 07:43
@davidfowl That approach makes is very easy for folks to run into the issue of loading the same FX assembly (e.g. System.runtime.dll or system.Collections.dll) into two LoadContexts and run into type mismatch issues.

It is a simpler model, and invariant, that any assembly that needs to be loaded from path/ni should not be in the app-base (since that set is semantically loaded in default context).

**Comment by davidfowl** [comment] 2016-01-15 10:14
@gkhanna79 with great power comes great responsibility. That constraint makes it nearly impossible properly implement a child load context where you don't want to unify certain types.

**Comment by gkhanna79** [comment] 2016-01-15 18:32
@davidfowl The implication of only unifying mscorlib (which is required by design) is that for any custom ALC instance, everytime a static assemblyref needs to be resolved for an assembly being loaded via Load from path/ni/stream, we would need to call into custom ALC's Load method where the ALC implementation would need to know where to load the assembly from. 

From what you propose, this will be required for FX assemblies as well (e.g. system.runtime.dll). Not only will this impact performance of the load triggered but there are scenarios (e.g. dotnet run) where the FX assemblies are not applocal and the custom ALC would have no idea where to load it from.

And just to clarify, everything that is coming from CoreFX (including system.runtime and like FX assemblies) is no different from an app assembly now.

Thus, I am not sure how this will work if we were to go this route.

**Comment by gkhanna79** [comment] 2016-01-21 01:26
I am closing this issue.

**Closed by gkhanna79** 2016-01-21 01:26 UTC
Labels: bug

**Comment by andschwa** [comment] 2016-03-24 20:45
@gkhanna79 Thanks for the information :smile: I'm trying to fix this whole mess the *right* way.
