### ISSUE TITLE
dotnet does not generate fsproj.metaproj file, but build process seems to require it

### ISSUE THREAD

**Issue by colinbowern** [dotnet/cli#7000] opened 2017-06-25 20:45 UTC
## Steps to reproduce
1. Install .NET Core on WSL Bash per the [.NET Core Step-by-Step instructions](https://www.microsoft.com/net/core#linuxubuntu)
2. Run through steps to get started with F# on the CLI through to completing "Writing a Class Library" on the [Get started with F# with the .NET CLI](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/getting-started/getting-started-command-line) documentation
3. Run "dotnet build" 

## Expected  behavior
Class library compiles

## Actual behavior
Failed with error MSB4025: The project file could not be loaded. Could not find file '/mnt/c/Users/colinb/Projects/TestProject/src/Library/Library.fsproj.metaproj

No tooling along the way creates a metaproj file. This file does not exist.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64
>  Base Path:   /usr/share/dotnet/sdk/1.0.4

**Comment by dmbarbour** [comment] 2017-06-29 16:16
I'm seeing the same problem with any attempt to create a solution. Steps to reproduce:

    mkdir tmp; cd tmp
    mkdir A; cd A; dotnet new classlib -lang f#; cd ..
    dotnet new sln
    dotnet sln add A/A.fsproj
    dotnet build

Error at this point is: `/tmp/A/A.fsproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/tmp/A/A.fsproj.metaproj'`. Same dotnet version as @colinbowern, above.

**Comment by dmbarbour** [comment] 2017-06-29 23:29
I have a workaround: I'm just using a toplevel project instead of a toplevel solution.

**Comment by livarcocc** [comment] 2017-07-10 21:23
@rainersigwald Is this something else that msbuild needs to address? Why would it fail to generate the metaproj for a solution with fsprojs? Are we setting the wrong project type, maybe?

**Comment by rainersigwald** [comment] 2017-07-10 21:27
This issue was moved to Microsoft/msbuild#2275

**Comment by rainersigwald** [comment] 2017-07-10 21:27
The sln metaproj will point to (memory-only) project metaproj files in some circumstances that I don't recall offhand. We should debug why that's happening here.

**Comment by livarcocc** [comment] 2017-07-10 21:33
Closing this one for now then. Re-activate if this turns out as a problem in the CLI/SDK.

**Closed by livarcocc** 2017-07-10 21:33 UTC
