### ISSUE TITLE
EntityFramework Core 1.1 support for Spatial.

### ISSUE THREAD

**Issue by muhsohail** [dotnet/cli#7401] opened 2017-08-09 08:41 UTC
Hi,

I have question around System.Data.Spatial.

We have been using System.Data.Spatial in .NetFramework4.5 a lot.
Do we have alternative in DotNetCoreApp 1.1. 
I did not find.

## Environment data
`dotnet --info` output:
DotNetCoreApp 1.1.

**Comment by livarcocc** [comment] 2017-08-09 16:13
@bricelam Is this something that you can help with?

**Comment by bricelam** [comment] 2017-08-09 17:05
@divega

**Comment by bricelam** [comment] 2017-08-09 17:08
ARAIK, `System.Data.Spatial` was created by the OData team. @divega might know if there are any plans for .NET Core...

**Comment by bricelam** [comment] 2017-08-09 17:12
Oh wait, I may be getting confused with `Microsoft.Spatial`.

All I know is that we have aspnet/EntityFramework#1100 for figuring out how to light up spatial data types in EF Core.

**Comment by bricelam** [comment] 2017-08-09 17:15
Duplicate of dotnet/corefx#12034?

**Comment by littleKing82** [comment] 2017-08-12 06:38
Thanks you for your replies. I shall have a look. This can be closed.

**Comment by divega** [comment] 2017-08-12 06:53
Thanks @bricelam for reminding me of this thread. I think it is fair to say that this can be a duplicate of both the corefx and the EF Core issues. 

For future reference, System.Data.Spatial was actually a namespace we used in the EF implementation :smile:, e.g. DbGeography. The work the OData team did lives on in Microsoft.Spatial.

@littleKing82 I don't know of any specific short term plans, but very detailed customer feedback, e.g. on what spatial functionality you use can help a lot.

**Comment by littleKing82** [comment] 2017-08-22 19:15
@divega thanks for your comments. Mean we should start finding alternate for System.Data.Entity.Spatial.

**Closed** 2018-05-11 22:46 UTC
Labels: question
