### ISSUE TITLE
Unable to publish with 2.0.0-preview2-006098

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/cli#6649] opened 2017-05-20 13:24 UTC
## Steps to reproduce
```
Create new AspCore WebApp app
Upgrade package to 2.0.0-preview2-25108
dotnet publish -c Debug
```

## Expected  behavior

> publish

## Actual behavior

```
  WebApplication1 -> D:\temp\TestCore\WebApplication1\WebApplication1\bin\debug\netcoreapp2.0\WebApplication1.dll
  Razor view compilation for WebApplication1 -> obj\debug\netcoreapp2.0\WebApplication1.PrecompiledViews.dll
C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(252,5): error MSB4018: The "ResolvePublishAssemblies" task failed unexpectedly.\r [D:\temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]
C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(252,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\vrith\.nuget\packages\microsoft.aspnetcore.all\2.0.0-preview2-25108\build\manifest.win7-x64.xml'.\r [D:\temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]
C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(252,5): error MSB4018: File name: 'C:\Users\vrith\.nuget\packages\microsoft.aspnetcore.all\2.0.0-preview2-25108\build\manifest.win7-x64.xml'\r [D:\temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]
C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(252,5): error MSB4018:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)\r [D:\temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]

```
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006098)

Product Information:
 Version:            2.0.0-preview2-006098
 Commit SHA-1 hash:  8c1dacbe23

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006098\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f

**Comment by livarcocc** [comment] 2017-05-20 16:48
If you changed the package, you need to run restore and then you can publish. We will have implicit restore by RTW, but not yet.

**Comment by vRITHNER** [comment] 2017-05-20 17:05
I have cleaned and  restored but no changes

**Comment by vRITHNER** [comment] 2017-05-20 17:09
Bye the way, I just git undo of my entire solution to come back to 2.0.0-preview1-final
then cleaned, restored and published but I get same issue.

**Comment by livarcocc** [comment] 2017-05-20 17:29
Which package did you upgrade to 2.0.0-preview2-25108? Can you share your csproj?

@Eilon @muratg @JunTaoLuo since this is the asp.net manifest that seems to be missing.

**Comment by vRITHNER** [comment] 2017-05-20 19:15
You can find the sample here: [https://1drv.ms/u/s!AqPUReudKR8t8OIQQz2ni2DFaCFuNg](https://1drv.ms/u/s!AqPUReudKR8t8OIQQz2ni2DFaCFuNg)

It's really a VS2017 enterprise preview aspnetcore 2.0 web mvc web app with auth identity 
Then update to 2.0.0-preview2-25108

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
    <UserSecretsId>aspnet-WebApplication1-2E1BF476-B586-41B3-A53F-9A2451A31681</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-25108" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0-preview2-25108" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview1-final" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview1-final" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <None Update="urlRewrite.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

**Comment by livarcocc** [comment] 2017-05-20 21:29
@vRITHNER I am not sure how restore is working for you. I just tried the project you posted and I can restore, which makes sense, since that version of the asp.net hasn't made back into the CLI yet.

This is expected, given that.

This is what I see, by the way, when running dotnet restore in the command using CLI 2.0.0-preview2-006098.
```
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.AspNetCore.All (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.EntityFrameworkCore.Tools (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.VisualStudio.Web.CodeGeneration.Design (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.VisualStudio.Web.CodeGeneration.Tools (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.EntityFrameworkCore.Tools.DotNet (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.Extensions.SecretManager.Tools (>= 2.0.0-preview2-25108)' for '.NETCoreApp,Version=v2.0'. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Value cannot be null. [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
/sdk/2.0.0-preview2-006098/NuGet.targets(98,5): error : Parameter name: path [/Users/livarcocc/Downloads/WebApplication1/WebApplication1.csproj]
```

**Comment by vRITHNER** [comment] 2017-05-20 23:42
Restore is working in my environment because I set a nuget.config similar to the one in Danroth27 build sample

Sent from my Windows 10 phone

**Comment by vRITHNER** [comment] 2017-05-21 08:32
[https://1drv.ms/u/s!AqPUReudKR8t8ON_7dnybO-i_Ak14Q](url)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
        
    <add key="AspNetCore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="AspNetCoreTools" value="https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="aspnet-release" value="https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json" />     

  </packageSources>
</configuration>
```

**Comment by JunTaoLuo** [comment] 2017-05-22 19:19
I am not able to reproduce the error and am able to restore and publish using 2.0.0-preview2-006098. 

I checked our Microsoft.AspNetCore.All package and it contains the correct set of manifests so I'm not sure what is causing that error. Can you clear your caches and try clean/restore/publish again? `You can clear you caches with dotnet nuget locals all --clear`.

**Comment by vRITHNER** [comment] 2017-05-23 05:58
I executed the command and then try to restore 

The result is:

```
D:\Temp\TestCore\WebApplication1\WebApplication1>dotnet nuget locals all --clear
info : Clearing NuGet HTTP cache: C:\Users\vrith\AppData\Local\NuGet\v3-cache
info : Clearing NuGet global packages cache: C:\Users\vrith\.nuget\packages\
info : Clearing NuGet Temp cache: D:\Users\vrith\AppData\Local\Temp\NuGetScratch
info : Local resources cleared.

D:\Temp\TestCore\WebApplication1\WebApplication1>dotnet restore
  Restoring packages for D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj...
  Restoring packages for D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj...
  Restoring packages for D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj...
  Restoring packages for D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj...
C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\NuGet.targets(98,5): warning : Dependency specified was Microsoft.EntityFrameworkCore.Tools.DotNet (>= 2.0.0-preview2-006098) but ended up with Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0-preview2-24770. [D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]
  Restore completed in 13.43 sec for D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj.
C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\NuGet.targets(98,5): warning : Dependency specified was Microsoft.Extensions.SecretManager.Tools (>= 2.0.0-preview2-006098) but ended up with Microsoft.Extensions.SecretManager.Tools 2.0.0-preview2-24770. [D:\Temp\TestCore\WebApplication1\WebApplication1\WebApplication1.csproj]
```

I then right clicked in VS "Manage Nuget Package" and I saw "v2.0.0-preview2-25159"
-I run "dotnet nuget locals all --clear"
- `dotnet restore` -> No errors 
- `dotnet build` -c debug -> No errors
- `dotnet publish -c debug` -> No errors
- cd bin\Debug\netcoreapp2.0\publish
- dotnet  WebApplication1.dll ->

> Error: assembly specified in the dependencies manifest was not found probably due to missing runtime store associated with manifest.win7-x64.xml;manifest.win7-x86.xml;manifest.osx-x64.xml;manifest.linux-x64.xml -- package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.0-preview2-25159', path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'

- `cd ..\..\..\..`
- `dotnet run -c debug`
- run `https://127.0.0.1:44356` in chrome -> 

> An unhandled exception occurred while processing the request.
> 
> ArgumentException: Options.ClientId must be provided
> Parameter name: ClientId
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
> 
> Stack Query Cookies Headers
> ArgumentException: Options.ClientId must be provided
>  Parameter name: ClientId

Txs

**Comment by JunTaoLuo** [comment] 2017-05-23 07:11
Seems like we are making progress as publish was at least successful. It seems that the problem now is that the aspnetcore runtime store is not installed. I'm not sure if the preview2 sdk installer includes our preview2 runtime store. @livarcocc ?

If the store is installed, your dotnet home directory should contain 
```
root
\_ additionalDeps\
\_ host\
\_ sdk\
\_ shared\
\_ store\
\_ dotnet.exe
...
```

If not the fallback is to manually instal the store:
1. download the Build.RS package with the corresponding version number: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Build.RS 
2. unzip Build.RS.{platform}-preview2-{build number}.{zip/tar.gz} to the dotnet home directory

**Comment by vRITHNER** [comment] 2017-05-23 10:25
I just try without any change

**Comment by livarcocc** [comment] 2017-05-23 17:16
Preview2 is carrying a store.

**Comment by JunTaoLuo** [comment] 2017-05-23 17:43
Seems like the store that is carried is 2.0.0-preview1-final, not the preview2 stores that we are producing. This misalignment means the binaries cannot be loaded at runtime which is producing the error observed.

**Comment by livarcocc** [comment] 2017-05-23 17:47
I believe @mlorbetske has a PR updating the store version.

**Comment by eerhardt** [comment] 2017-06-08 19:13
Is this issue now solved?  I'm removing the 'store' label, since this isn't an issue with the `dotnet store` command.  Instead, it has morphed into an issue with how we are packaging the asp.net runtime store in the SDK.

**Comment by livarcocc** [comment] 2017-06-13 22:25
I believe we have this fixed now. If this is still an issue, please, re-activate.

**Closed by livarcocc** 2017-06-13 22:25 UTC
