### ISSUE TITLE
Escape characters in error messages

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2590] opened 2016-04-19 22:26 UTC
## Steps to reproduce

```
PS C:\Users\\Documents\Visual Studio 2015\Projects\dotnet-scratch> dotnet my-tool
[1m[31mNo executable found matching command "dotnet-my-tool"[39m[22m
```
## Expected  behavior

No `[39m[22m` like sequences in the error message
## Actual behavior

```
[1m[31mNo executable found matching command "dotnet-my-tool"[39m[22m
```
## Environment data

`dotnet --info` output:

```
dotnet --version
1.0.0-rc2-002426
```

**Comment by brthor** [comment] 2016-04-19 22:34
what platform

**Comment by moozzyk** [comment] 2016-04-19 22:56
win10

**Comment by mikeharder** [comment] 2016-04-21 21:50
I was also seeing this on Windows Server 2012 R2.  See #2609.

**Comment by piotrpMSFT** [comment] 2016-04-22 01:15
Folks, we're not successfully finding a repro for this issue. I've only seen the ANSI color code characters show up when i redirect console output to a text file and then open that file in notepad. We've tried this on multiple win10 machines. Can you help us find a good repro?

**Comment by mikeharder** [comment] 2016-04-22 01:42
**Repro Steps**
1. Create a VM in Azure running Windows Server 2012 R2 Datacenter
2. Install "Windows x64 .NET Core SDK Installer" version 1.0.0-rc2-002470.
3. Open command prompt (cmd.exe)
4. Run `dotnet foo`

**Output**
```
C:\Windows\system32>dotnet foo
←[1m←[31mNo executable found matching command "dotnet-foo"←[39m←[22m
```

**Comment by moozzyk** [comment] 2016-04-22 16:13
I don't see it happening anymore with 1.0.0-rc2-002476

**Comment by mikeharder** [comment] 2016-04-22 19:34
Still repros on Windows Server 2012 R2 with 1.0.0-rc2-002476.

**Comment by xied75** [comment] 2016-04-30 22:45
Just saw this on Ubuntu 14.04 running inside docker:

![image](https://cloud.githubusercontent.com/assets/1682456/14938907/a19e78f2-0f2b-11e6-8c59-ced62f60e0e0.png)

(sorry about the huge size, apparently it's the OneNote screen clipping not handling HiDPI correctly)

It's not really unicode, it's just an plain old ascii 0x1b, as proved like this:

```
root@c488baa8e6b9:~/test# dotnet run | hd
00000000  43 6f 6d 70 69 6c 69 6e  67 20 1b 74 65 73 74 1b  |Compiling .test.|
00000010  20 66 6f 72 20 1b 44 4e  58 43 6f 72 65 2c 56 65  | for .DNXCore,Ve|
00000020  72 73 69 6f 6e 3d 76 35  2e 30 1b 0a 0a 1b 43 6f  |rsion=v5.0....Co|
00000030  6d 70 69 6c 61 74 69 6f  6e 20 73 75 63 63 65 65  |mpilation succee|
00000040  64 65 64 2e 1b 0a 20 20  20 20 30 20 57 61 72 6e  |ded...    0 Warn|
00000050  69 6e 67 28 73 29 0a 20  20 20 20 30 20 45 72 72  |ing(s).    0 Err|
00000060  6f 72 28 73 29 0a 0a 54  69 6d 65 20 65 6c 61 70  |or(s)..Time elap|
00000070  73 65 64 20 30 30 3a 30  30 3a 30 31 2e 34 38 34  |sed 00:00:01.484|
00000080  35 31 34 38 0a 20 0a 0a  48 65 6c 6c 6f 20 57 6f  |5148. ..Hello Wo|
00000090  72 6c 64 21 0a                                    |rld!.|
```

**Comment by moozzyk** [comment] 2016-05-04 17:44
For whatever reason I did not see this with 1.0.0-rc2-002476 but it is actually still happening on Win10 and 1.0.0-rc2-002655:
```
PS C:\temp\publishout> dotnet pu
[1m[31mNo executable found matching command "dotnet-pu"[39m[22m
```

**Comment by jasonwilliams200OK** [comment] 2016-08-06 07:37
I can't reproduce it with 1.0.0-preview2-003121 on Windows 10 and OSX 10.11.

**Comment by xied75** [comment] 2016-09-16 15:31
Running on Linux container works fine now. Maybe can close.

**Comment by blackdwarf** [comment] 2017-01-15 16:20
OK, since it seems the issue has resolved with newer versions, closing. Please reopen if it repros again with latest.

**Closed by blackdwarf** 2017-01-15 16:20 UTC
Labels: Investigate
