### ISSUE TITLE
error NETSDK1053: Pack as tool does not support self contained seems restrictive with no purpose

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#10609] opened 2019-01-15 17:03 UTC
## Steps to reproduce
publish a tool marked as `<PackAsTool>true</PackAsTool>` as a self-contained application (`dotnet publish -c release -f netcoreapp2.1 -r ubuntu.14.04-x64`)

## Expected  behavior
publish should succeed, just like it did in 2.1

## Actual behavior
Fails with:
```
/usr/share/dotnet/sdk/2.2.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.PackTool.targets(71,5): error NETSDK1053: Pack as tool does not support self contained.
```

This is a regression as far as I'm concerned, since previously there was nothing "wrong", neither in concept or in practice (in the netcoreapp2.1 SDK era) with publishing a self contained application which is ALSO packaged as a dotnet global tool.

This is currently forbidden as of the new .NET Core SDK, and its hard to figure out what the reasoning is.

When the condition on `/usr/share/dotnet/sdk/2.2.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.PackTool.targets`/line 71 is commented out, the 2.1 behavior works as expected.

I think it would make sense to relax this limitation, esp. since it's not so clear what purpose it serves...

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.502 [/usr/share/dotnet/sdk]
  2.2.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2019-01-15 18:58
Duplicate of https://github.com/dotnet/cli/issues/10607.

**Closed by livarcocc** 2019-01-15 18:58 UTC
