### ISSUE TITLE
Unable to start process "dotnet-projectmodel-server" while starting VS2015

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#4621] opened 2016-11-04 18:48 UTC
## Steps to reproduce
Install dotnet cli sdk 1.0.0-preview3-004050
Open an xproj based solution (I opened the [nuget.core](https://github.com/NuGet/NuGet.Client) solution, Not sure if this is an issue with all xproj solutions.)

## Expected  behavior
Solution should load without error

## Actual behavior

Get an error - 

![2016-11-04](https://cloud.githubusercontent.com/assets/10507120/20018227/26ccc3ee-a284-11e6-82ab-113cfeb523b8.png)

## Environment data
`dotnet --info` output:

```
E:\nuget\NuGet.Client [dev ≡]> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

```

## Extra

Not sure if dev14 is suppose to play nice with preview3. Raising a bug for visibility.

**Comment by piotrpMSFT** [comment] 2016-11-09 06:54
This looks like a dupe of https://github.com/dotnet/cli/issues/4248

Try the options documented here:
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md

**Closed** 2016-11-10 00:19 UTC

**Comment by ZoolWay** [comment] 2016-12-19 13:46
If someone comes here maybe after installing VS 2017 RC which also comes with newer toolings than preview 2, take a look here: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md#how-do-i-work-with-projectjson-and-csproj-on-the-same-machine

You can setup your `global.json` to use preview2 tooling in old projects which are not migrated (back) to `.csproj`.
