### ISSUE TITLE
Build won't finish

### ISSUE THREAD

**Issue by maririos** [dotnet/cli#8478] opened 2018-01-25 21:28 UTC
@MeikelLP commented on [Tue Jan 23 2018](https://github.com/dotnet/buildtools/issues/1874)

My project wont build at all using `dotnet build`. Using the `-v diag` switch I can see that the problem seems to be the "Copy" Task. And after canceling it via Ctrl+C messages keep appearing in my terminal:

```
22:08:00.854  2:10>/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB4220: Waiting for the currently executing task "Copy" to cancel. [/Volumes/Speicher/projekte/Gitlab/MeikelLP/DataVisualizer/Core/Core.csproj]
/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB4220: Waiting for the currently executing task "Copy" to cancel. [/Volumes/Speicher/projekte/Gitlab/MeikelLP/DataVisualizer/Core/Core.csproj]
```

This is the last output from the command:
```
22:03:32.868  1:10>Target "CopyFilesToOutputDirectory: (TargetId:107)" in file "/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets" from project "/Volumes/Speicher/projekte/Gitlab/MeikelLP/DataVisualizer/Core/Core.csproj" (target "PrepareForRun" depends on it):
                   Set Property: CreateHardLinksForCopyFilesToOutputDirectoryIfPossible=false
                   Set Property: CreateSymbolicLinksForCopyFilesToOutputDirectoryIfPossible=false
                   Set Property: CopyBuildOutputToOutputDirectory=true
                   Set Property: CopyOutputSymbolsToOutputDirectory=true
                   Using "Copy" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Copy" (TaskId:66)
                     Task Parameter:SourceFiles=obj/Debug/netstandard2.0/DataVisualizer.Core.dll (TaskId:66)
                     Task Parameter:DestinationFolder=bin/Debug/netstandard2.0/ (TaskId:66)
                     Task Parameter:SkipUnchangedFiles=True (TaskId:66)
                     Task Parameter:OverwriteReadOnlyFiles=False (TaskId:66)
                     Task Parameter:UseHardlinksIfPossible=False (TaskId:66)
                     Task Parameter:UseSymboliclinksIfPossible=False (TaskId:66)
                     Copying file from "obj/Debug/netstandard2.0/DataVisualizer.Core.dll" to "bin/Debug/netstandard2.0/DataVisualizer.Core.dll". (TaskId:66)
```

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DataVisualizer.Core</AssemblyName>
    <RootNamespace>DataVisualizer.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
</Project>
```

System:
* MacOS 10.13.2
* .NET Core SDK 2.1.4

---

@MeikelLP commented on [Tue Jan 23 2018](https://github.com/dotnet/buildtools/issues/1874#issuecomment-359934392)

I edited the .csproj (removed AssemblyName & RootNamespace) saved and ran `dotnet build`-> worked.
I changed my edit back to the submitted version and ran `dotnet build`-> worked.
Why? That's super strange...

**Comment by livarcocc** [comment] 2018-01-25 22:00
I don't see much that we can do here without a repro or logs.

It may have been so many things in your system causing the task to hang.

Still, cc @rainersigwald in case he has seen anything like this in the past. Otherwise, we will need at least logs.

**Comment by rainersigwald** [comment] 2018-01-25 22:09
I don't recall anything causing a hang in Copy on macOS. I'd be very interested in a repro (or an `strace`/`dtruss` of the failure on your machine), but I agree that without one this is unlikely to get chased down.

**Comment by MeikelLP** [comment] 2018-01-25 22:44
The machine is newly setup so no fancy tools installed.
Cannot reproduce this anymore (sadly). I would like to know which could have caused this as well...

**Comment by livarcocc** [comment] 2018-02-16 01:04
Given that we don't have a repro and the issue seem to have gone away, I am going to close this issue.

**Closed by livarcocc** 2018-02-16 01:04 UTC
