### ISSUE TITLE
Ensure that corehost works on Nano Server

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#468] opened 2015-12-10 17:56 UTC
We had some issues with building `dnx` on Nano Server. We need to verify that `corehost` will work fine on Nano Server (which only supports the OneCore APIs).

**Comment by anurse** [comment] 2016-01-14 18:02
I think @schellap and @gkhanna79 own this now, right? This is definitely important for RTM since we expect ASP.NET applications to run on Nano Server. @moozzyk may have some insight from our own porting efforts for DNX.

/cc @piotrpMSFT

**Comment by gkhanna79** [comment] 2016-01-14 19:33
Yes, @schellap owns it. However, I am not sure if this can make RC2 but can be done for RTM. I will move this to RTM - let me know if anyone feels otherwise.

CC @leecow

**Comment by GuardRex** [comment] 2016-01-15 08:19
@anurse @Rick-Anderson @shirhatti Curious ... Does the .NET 5 on Nano doc also need to stay under-the-covers until RTM? https://github.com/aspnet/Docs/pull/894

**Comment by anurse** [comment] 2016-01-15 18:09
My only concern with waiting for RTM is that DNX RC1 ran on Nano Server, so this would be a temporary regression of behavior since an ASP.NET app compiled with dotnet cli would not be guaranteed to run on Nano Server.

@DamianEdwards, @danroth27, @davidfowl and @glennc should probably be aware of that :)

/cc @victorhurdugaci @muratg @Eilon

**Comment by DamianEdwards** [comment] 2016-01-15 18:16
We have customers running on Nano now so this would indeed be a regression for RC2. What is the hold up?

**Comment by anurse** [comment] 2016-01-15 18:36
It's mostly just that we have a new host now (`corehost` rather than `dnx`) and we need to to ensure that it runs on Nano server.

**Comment by gkhanna79** [comment] 2016-01-15 23:22
This would require building the host against apisets so that it can work on Nano server. And since it will be linked against them, we need to have the right forwarder binaries in place.

The work is to ensure all of this works - especially on downlevel OS. It would have been awesome to see this issue earlier but it came our way just yesterday. We will see what can be done for RC2.

CC @Petermarcu

**Comment by moozzyk** [comment] 2016-01-15 23:25
At the moment ASP.NET requires reverse forwarders to be installed on Nano.

**Comment by gkhanna79** [comment] 2016-01-15 23:28
If reverse forwarders are installed, then the host should work (since R-Forwarders are going to resolve Kernel32->API-*). Has someone on ASP.NET or Nano server tried using the host?

**Comment by GuardRex** [comment] 2016-01-15 23:29
Yes ... It's working with the Forwarders package. Which is what we have in the tutorial on this. I can rapidly respond to changes for the doc to match any changes teams make, and I can add a note at the head of the doc saying "works for RC1 only" if RC2 is a concern.

**Comment by GuardRex** [comment] 2016-01-15 23:30
... btw ... my test middleware app is RC2 current packages and runtime ... and it did work just this morning.

**Comment by GuardRex** [comment] 2016-01-15 23:31
... dotnet CLI changes ... no idea on that one ... which I think is what @anurse is referring to here.

**Comment by anurse** [comment] 2016-01-15 23:51
Requiring the reverse forwarders is probably just fine, so if we need to do that, that's fine. 

@moozzyk, @victorhurdugaci You guys have done nano server work before. Do you still have a VM set up using nano? My VM host doesn't use Hyper-V (because Docker) so I can't easily set one up. We just need someone to try running a `dotnet-publish`ed app on Nano Server and see if it works :)

**Comment by victorhurdugaci** [comment] 2016-01-16 00:22
When we convert MusicStore it will test Nano server too. We have a Nano CI agent for it

**Comment by gkhanna79** [comment] 2016-01-16 01:16
If reverse forwarders (and not APISet forwarders) are always going to be present on Nano server, then please try the test @anurse suggested above. It should just work without requiring any changes to the host. In that case, this issue is a no-op and can be closed (once confirmation comes through).

**Comment by moozzyk** [comment] 2016-01-16 01:29
The requirement of having reverse loaders on Nano for ASP.NET 5 comes from http platform handler and libuv. I could imagine that in the future http plafrom handler will no longer require forwarders. Similarly libuv can be fixed (there are ~20 APIs that are not available in one core - most of which have  *Ex counterparts that are present in onecore) - especially if http platform handler is fixed.

Also, not sure how much of a scenario it is but cli apps will likely won't work... 

I would say leave this open to fix for post RTM.

**Comment by GuardRex** [comment] 2016-01-16 01:39
> Also, not sure how much of a scenario it is but cli apps will likely won't work...

@moozzyk Curious why it will/might break for dotnet cli? ... just because if true, it blocks the release of the ".NET 5 on Nano Server" doc for quite a while.

**Comment by GuardRex** [comment] 2016-01-16 04:15
@moozzyk Nevermind. I'm off that doc now. Someone else is going to handle it.

**Comment by moozzyk** [comment] 2016-01-16 04:26
@GuardRex In general native apps not against onecore.lib don't work without reverse forwarders and reverse forwarders are not installed on Nano by default (as opposed to win10).

**Comment by GuardRex** [comment] 2016-01-16 04:26
@moozzyk thx

**Comment by Eilon** [comment] 2016-01-21 19:00
@gkhanna79 I can get someone on my team to test this. However, we're doing our big rename right now so the test won't happen until at least next week.

**Comment by GuardRex** [comment] 2016-01-21 19:06
@Eilon I'm trying to do a "non-team" test now. `dotnet cli` is fighting me a little bit, but I'll see if/when I get my `dotnet cli` cook'in if I can get my test proj running on Nano by the end of the day.

**Comment by anurse** [comment] 2016-01-21 19:14
Cool. At this point a simple console app test would be enough I think. We already know that the ASP.NET managed code works on Nano, it's just the native host we're concerned about :)

**Comment by GuardRex** [comment] 2016-01-21 19:23
@anurse It's :dog:'in me a little on package sources, but I'll play with it when I get back. I'm actually going to try to get this meaty MVC app running, but I'll make a console app, too. I'm going out for a skate, but if you have a tip on these package sources not working, I'm all :ear: :ear: :ear:'s ... 

![capture](https://cloud.githubusercontent.com/assets/1622880/12491638/0715cf5e-c031-11e5-8aaa-0ae410fba7ff.PNG)

Does that 
```
https://www.myget.org/F/dotnet-core/api/v3
```
... need to be in my NuGet.Config? or in VS NuGet package sources?

**Comment by victorhurdugaci** [comment] 2016-01-21 19:37
Are you running restore on nano?

**Comment by GuardRex** [comment] 2016-01-21 19:38
No ... locally .. my win10 dev machine

**Comment by Eilon** [comment] 2016-01-21 20:29
CC @ryanbrandenburg who will try this out as well.

**Comment by gkhanna79** [comment] 2016-01-23 16:25
@Eilon Do you have a tentative timeframe to get this validated?

**Comment by GuardRex** [comment] 2016-01-23 20:49
Here is some good Nano news this morning. I have the console app running on Nano. There are few rough edges, but it worked out ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12532600/ee08c49c-c1cc-11e5-8c59-a433ade1478e.PNG)

#### Setup
* Used `dotnew new` to provide the console app, which was kept in a folder at `c:\newproj` locally.
* Nano Server TP4 configured with Reverse Forwarders and IIS packages
* Folder layout on the Nano: `c:\testsite\wwwroot\web.config`; `c:\testsite\newproj\` for the app payload, which included the `.exe` file and all of the DLL's; and `c:\testsite\logs` to hold the `HttpPlatformHandler` logs and show if the console app is triggered properly (i.e., receive the console output)
* `web.config` and `project.json` are below.
* After getting the bits in the right spots on Nano and configuring IIS for the app at port 8000, I hit the site at the VM's IIS endpoint: `http://<nano_DNS_address>.westus.cloudapp.azure.com:8000`. There's no response in the browser, of course, but the console app tosses the `Hello Log!` output properly into the `HttpPlatformHandler` log as you can see above. :+1:
```xml
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" 
          resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\newproj\newproj.exe" arguments="" stdoutLogEnabled="true" 
        stdoutLogFile="..\logs\httpplatform" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```
```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-*"
  },
  "frameworks": {
      "dnxcore50": { }
  }
}
```
#### Pain Points
* Had to use `dnu restore` via VS to get packages, which ended up in DNX packages and had to manually moved to the `.nuget` folder. Trying `dotnet restore` from the CL constantly throws `NotFound` 404's for package sources (e.g., `NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json`).
* `dotnet compile --native` throws a "The system cannot find the file specified", but `dotnet publish` does produce all of the outputs needed. I would love to get it all down to a single `.exe`.
* Minor issue when I copied a new project payload to the Nano (I changed "Hello World!" to "Hello Log!") without stopping the AppPool first: It broke responsiveness (i.e., writing to the log); however, it didn't crash the AppPool. I had to stop the AppPool and restart it to get the new "Hello Log!" version of the app responsive. This isn't all that surprising really. Not stopping the AppPool when making app changes is a huge no-no when dealing with IIS.

@anurse Is this along the lines of what you're looking for? ... or are you asking here if the app can be manually run (outside of IIS/HttpPlatformHandler) on a Nano **without** the Reverse Forwarders packages? If you'd like that test, I'll give it a go. If so, let me know if there are package (or package sources) changes over what I just did.

**Comment by anurse** [comment] 2016-01-23 20:54
This is fantastic! It sounds like the core issue (i.e. `corehost`, pun intended of course) is not going to be a big worry.

I would suggest we keep this issue open though, since ideally we should not require the reverse forwarders for `corehost`. That is not as high a priority for us though since we already needed the Reverse Forwarders to run Kestrel (since libuv is not built against the OneCore surface)

**Comment by GuardRex** [comment] 2016-01-23 21:03
@anurse ... Right. That's kind'a what I thought. I am sort of personally curious though if it will run without the Reverse Forwarders packages on there (just the console app ... not via IIS ... not via HttpPlatformHandler of course with libuv's requirement for Reverse Forwarders right now). I think I will do that test when I get back from errands today.

My next big one is going back to the MVC6 testing I was doing the other day. I nearly choked to death :skull: on package problems; however, just the work you cats did in the last few days has helped a lot.

Let me see if I can get a full IIS/HttpPlatformHandler MVC6 app working this evening. I have 17 bottles of cheap beer :beers: and several hours to kill, so it should be fun to see what happens ... and yes ... I'll prob be posting random YouTube music videos on JabbR while I work on this. Apologies in advance to @benaadams for that! Please don't BAN me Ben. :smile: I'll report back ...

**Comment by DamianEdwards** [comment] 2016-01-23 21:47
I thought we built libuv against OneCore specifically for Kestrel? @moozzyk

**Comment by GuardRex** [comment] 2016-01-23 21:49
https://github.com/aspnet/Hosting/issues/539#issuecomment-167709309

**Comment by moozzyk** [comment] 2016-01-23 22:44
@DamianEdwards @GuardRex 
No, libuv is not linked against OneCore - until libuv code is updated to not use APIs that are not part of OneCore it can't be done. I briefly looked at what needs to be changed to fix this and it looked like in most cases it should be easy but some would require more thought and I have not had a chance to spend more time on it.

In the libuv-build repo we built libuv differently than it is built in the libuv repo to avoid introducing another tool chain (gyp (which requires python) and/or autotools) and because the toolchain they use did not support ARM and OneCore (this is not a big deal at the moment - as I said above the code cannot be linked agains OneCore at the moment). I briefly looked 

Also note that currently http platform handler currently requires reverse forwarders as well (though I heard they would like to lift this requirement eventually)

**Comment by GuardRex** [comment] 2016-01-24 02:46
@anurse Well, that didn't work out (bone stock Nano ... no Reverse Forwarders) ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12534161/20e4965a-c201-11e5-883c-d8baa3224aa6.PNG)

There's nothing showing in Event Viewer when trying to execute the app. It crashes Hard, Fast, and Clean ... I think I have the title of my autobiography there! :smile:

**Comment by anurse** [comment] 2016-01-24 04:47
I'd expect that. Even if you only use APIs available on Nano, you still have to link your app specially to work with the "OneCore" API set libraries in order to work on Nano without Forwarders. We don't do that (yet).

**Comment by GuardRex** [comment] 2016-01-24 04:51
@anurse Ok, that's cool.

I've gone back to trying to get the MVC6 test app running on Nano. So far, it's going as well as last time ... package issues ... like getting the `AppContext` package now. We'll see. I'm on JabbR "Rubber Duck" programming along and posting random '80's music videos and drinking a lot of cheap :beer:. We'll see how far I get this time with it.

**Comment by GuardRex** [comment] 2016-01-24 06:54
@anurse Not happenig bro. Package issues out the wazoo. I even dropped back to @davidfowl `HelloMvc` and it's choking on package references big time. I fix one ... then go headlong right into another one. I'll try again in a few days. Until then, the :beer: and the :cherries: are quite good!

![cherries](https://cloud.githubusercontent.com/assets/1622880/12534934/11bcb8e2-c224-11e5-8ab5-6abacd0e3d48.jpg)

**Comment by GuardRex** [comment] 2016-01-24 07:25
@anurse 

> I would suggest we keep this issue open though, since ideally we should not require the reverse forwarders for corehost.

I kept the Nano without Reverse Forwarders ... deallocated in Azure but ready to go. Let me know when it should work, and I'll bring that puppy back online and call for a full spread of photon torpedoes. :rocket:

**Comment by gkhanna79** [comment] 2016-01-24 16:21
Nano is built on OneCore and until all native components (libuv, corehost, etc) are built for OneCore, reverse forwarders will be required.

BTW, this maybe bigger than just CoreHost. To make CLI work on any OneCore based SKU, all native components used in CLI toolchain need to be identified and fixed. Next, CLI toolchain will need to carry APISet forwarders to allow it to run on downlevel OS.

I have filed https://github.com/dotnet/cli/issues/1008 to @piotrpMSFT  to drive that, instead of this one which appears to have served its purpose to validate that corehost works on Nano with reverse forwarders. Once https://github.com/dotnet/cli/issues/1008 is addressed, reverse forwarders dependency for CLI can be removed.

Is there any other validation required on this issue aside validating corehost or can we close this issue?

**Comment by anurse** [comment] 2016-01-25 05:39
At the moment, AFAIK, the only native component we use is the CoreCLR itself which is already compiled against APISets and includes the APISet forwarders on Windows.

Now that we have the other issue, I think we can close this one.

**Comment by moozzyk** [comment] 2016-01-25 05:56
@anurse @gkhanna79 - if I have a native dll and I compiled it against OneCore should the package containing the dll also contain the api sets needed by this dll or should it rely on the ones that are shipped with CoreClr?

**Comment by gkhanna79** [comment] 2016-01-25 16:02
CoreCLR carries api-set forwarders for what it requires. A native binary, not associated with CoreCLR, may consume other APIs that CoreCLR does not and thus, cannot rely on CoreCLR to carry APISet forwarders for it.

I believe the path ahead should be to package all APISets forwarders in a package that satisfy CLI native dependencies's requirements. This package could be a superset of APISets package for CoreCLR or a different intersection altogether.

**Comment by moozzyk** [comment] 2016-01-25 18:36
@gkhanna79 - yeah, packaging api sets should be fine. Otherwise if a package containing a dll would contain api sets that are used by CoreClr then during publish they would stomp on each other. Not sure if this is a big problem but having api sets in a package(s) could solve it.

**Comment by gkhanna79** [comment] 2016-01-25 18:48
Closing this based upon the discussion above.

**Closed by gkhanna79** 2016-01-25 18:48 UTC
Labels: enhancement, infrastructure

**Comment by ryanbrandenburg** [comment] 2016-01-25 22:52
Just to pile on the confirmation here, I was able to get @davidfowl 's HelloMvc app running on the Threshold2 release of Nano server (with reverse forwarders). I just ran "dotnet publish" on my local box (version 1.0.0 of dotnet) then copied that over and ran the exe. Once the server was running I made successful requests against it and got the expected results.

**Comment by ryanbrandenburg** [comment] 2016-01-25 23:29
Just to pile on the confirmation, I was also able to get @davidfowl 's HelloMvc project running by doing "dotnet publish" (dotnet version 1.0.0) on my local machine, copying that to the Nano server and running the exe. The server responded with a 200 and the expected content.

**Comment by GuardRex** [comment] 2016-01-26 07:48
Cross ref (`ViewBag` bug on Nano): https://github.com/aspnet/Mvc/issues/3991

**Comment by schellap** [comment] 2016-05-04 00:19
Cc @pakrym

**Comment by victorhurdugaci** [comment] 2016-05-04 01:08
What's are the few rough edges? :)

**Comment by GuardRex** [comment] 2016-05-04 01:56
@victorhurdugaci @schellap If you're asking about .NET Core on Nano: The only reported delta between TP4 and TP5 is that in TP4 a packages folder was included with the preview that contained the Reverse Forwarders and IIS packages but the packages folder is not present in the TP5 distro. A dev reported to me that he had to obtain the packages manually. I have yet to confirm this, and I'm planning on running both of my test apps (portable and self-contained) on Nano later this week. I can ping you back here with the result if you like.

**Comment by gkhanna79** [comment] 2016-05-04 14:24
@GuardRex Please do share the results when you get them.

**Comment by GuardRex** [comment] 2016-05-04 14:26
@gkhanna79 Sure thing. I'll get to this no later than Sunday and ping back the result.

**Comment by refaati** [comment] 2016-05-06 01:10
@GuardRex , the packages folder *is* available on the ISO media, but not available in the Nano Server IaaS image on Azure, nor in the downloadable developer VHD.  Instead, people should use the Find-NanoServerPackage and Install-NanoServerPackage cmdlet to acquire and install the required packages from the cloud repository.
Please consult the Nano Server [documentation](https://technet.microsoft.com/en-us/library/mt126167.aspx), under "Installing packages on Nano Server online"
Thanks
ref@
Refaat Issa [MSFT]

**Comment by GuardRex** [comment] 2016-05-06 01:14
@refaati Ah! ... thank you. That will definitely speed me up this weekend.

**Comment by GuardRex** [comment] 2016-05-09 23:22
@gkhanna79 So much for getting to this by Sunday! My schedule got a little backed up. We see this now: https://github.com/dotnet/cli/issues/2967 ... which doesn't bode well for portable apps on Nano.

I only tested the self-contained application model previously. I still have a To-Do item to run tests for both app types in the coming days. I'll report back here soon.
