### ISSUE TITLE
dotnet build error

### ISSUE THREAD

**Issue by Varorbc** [dotnet/cli#11020] opened 2019-03-26 01:38 UTC
### 1.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>

```

```csharp
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            if (GetT<Program>() is null)
            {
                Console.WriteLine("null");
            }
        }

        public static T GetT<T>() where T : new()
        {
            var t = new T();
            if (t is null)
            {
                throw new Exception();
            }

            return t;
        }
    }
}

```

## Expected  behavior

dotnet build success

## Actual behavior

dotnet build error

Program.cs(19,22): error CS0403: 无法将 null 转换为类型参数“T”，因为它可能是不可以为 null 的值类型。请考虑改用“default(T)”

## Environment data
`dotnet --info` output:

.NET Core SDK（反映任何 global.json）:
 Version:   2.2.105
 Commit:    7cecb35b92

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment] 2019-03-26 02:05
I would expect the need for a `class` constraint on the generic parameter `T` for `Get<T>` to get past the `CS0403` error.

However, with a 3.0 SDK, I can't seem to get it to error regardless of the `LangVersion` I use (7.0+ since this example uses a pattern).

@jaredpar is this some subtle behavior difference between the compilers that ship with 2.2 and 3.0?

**Comment by jaredpar** [comment] 2019-03-26 02:57
@cston can confirm but believe this is a deliberate change between C# 7.3 and C# 8.0 (the latter allows the code now).

**Comment by Varorbc** [comment] 2019-03-26 03:54
@jaredpar I set the language version to 7.0 in vs 2019 and still compiled successfully.

**Comment by Varorbc** [comment] 2019-03-26 03:55
@jaredpar I set the language version to 7.0 in vs 2019 and still compiled successfully.

**Comment by jaredpar** [comment] 2019-03-26 03:55
@Varorbc I noticed that as well and that appears to be a bug. If you actually use a 7.0 compiler though you'll see it doesn't compile.

**Comment by Varorbc** [comment] 2019-03-26 04:02
@jaredpar Yes, I don't know exactly what version is used in the project system.@davkean Can you tell us?

**Comment by cston** [comment] 2019-03-26 04:27
Adding @gafter for the compiler change since `t is null` is bound as an `is` pattern now.

**Comment by jcouv** [comment] 2019-03-26 04:43
I think the change is deliberate and comes from https://github.com/dotnet/roslyn/pull/25995 ("recursive-patterns(18): Permit a constant pattern to be used with an open type as input")

**Comment by peterhuene** [comment] 2019-03-26 05:00
@jcouv Thanks for the info! However, should `-langversion:7` with a Dev16 compiler emit `CS0403` for the code above or not?

If the answer is "no", then I think we can close this by design.  If the answer is "yes", then we should transfer this to issue to Roslyn (with some changes, since this is expected behavior with a .NET Core 2.2 SDK, but it should be possible to get the error with a `LangVersion` set to 7 with a 3.0 SDK).

**Comment by peterhuene** [comment] 2019-03-29 18:44
Ping @jcouv for follow-up question above.

**Comment by jcouv** [comment] 2019-04-02 17:24
I checked with @gafter who said this was a new feature (as opposed to a bug fix). That means that `t is null` should produce a diagnostic when LangVersion is < 8. That diagnostic should indicate that upgrading the LangVersion would make the code compile.

**Comment by jcouv** [comment] 2019-04-02 17:27
Moving the issue over to Roslyn repo: https://github.com/dotnet/roslyn/issues/34678

**Closed by jcouv** 2019-04-02 17:27 UTC
