### ISSUE TITLE
Publish for RID specific shared runtime

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#5553] opened 2017-02-02 03:25 UTC
http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/ explains publish will generate a **standalone app** when given an RID.
```
dotnet publish --framework netcoreapp1.0 /p:RuntimeIdentifier=osx.10.11-x64
```

There should be a way to specify an RID and still use a **shared runtime**.

**Comment by blackdwarf** [comment] 2017-02-03 01:20
@tmds what is the scenario you are aiming for?

**Comment by tmds** [comment] 2017-02-03 09:03
> @tmds what is the scenario you are aiming for?

For example, publish for a shared runtime container like [1.0.3-runtime](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/runtime/Dockerfile). This is `debian.8-x64`. The publish folder should not contain the runtime or native bits for other platforms.

**Comment by tmds** [comment] 2017-02-09 10:09
@blackdwarf does the scenario make sense?

**Comment by blackdwarf** [comment] 2017-02-09 14:55
@tmds you are talking about a shared app that has any native dependencies constrained to just the runtime specified via the RID, correct?

**Comment by tmds** [comment] 2017-02-10 08:13
> @tmds you are talking about a shared app that has any native dependencies constrained to just the runtime specified via the RID, correct?

Exactly.

**Comment by davidfowl** [comment] 2017-02-10 08:14
> @tmds you are talking about a shared app that has any native dependencies constrained to just the runtime specified via the RID, correct?

Low-fat apps.

**Comment by blackdwarf** [comment] 2017-02-10 08:19
@tmds thanks for the clarification.

@davidfowl we should seriously consider other names, today I got (again) confused on the % of fat in all kinds of apps. 😄

**Comment by eerhardt** [comment] 2017-03-27 14:58
This is a duplicate of #4704.

**Closed by eerhardt** 2017-03-27 14:58 UTC
