### ISSUE TITLE
Unable to restore packages after dotnet migrate

### ISSUE THREAD

**Issue by dpaquette** [dotnet/cli#4663] opened 2016-11-09 19:11 UTC
## Steps to reproduce

- Clone https://github.com/AspNetMonsters/AlpineSkiHouse/
- Go to /src/AlpineSkiHouse.Web
- run `dotnet migrate` 
- run `dotnet restore` 

## Expected  behavior
Packages should restore.

## Actual behavior

```
Restore failed in 643.5607ms for /home/ux1/AlpineSkiHouse/src/AlpineSkiHouse.Web/AlpineSkiHouse.Web.csproj.

Errors in /home/ux1/AlpineSkiHouse/src/AlpineSkiHouse.Web/AlpineSkiHouse.Web.csproj
    Unable to resolve 'Microsoft.NET.Sdk.Web (>= 1.0.0-alpha-20161104-2)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.VisualStudio.Web.CodeGeneration.Design (>= 1.0.0-msbuild1-final)' for '.NETCoreApp,Version=v1.0'.

Errors in /home/ux1/AlpineSkiHouse/src/AlpineSkiHouse.Web/AlpineSkiHouse.Web.csproj
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Errors in /home/ux1/AlpineSkiHouse/src/AlpineSkiHouse.Web/AlpineSkiHouse.Web.csproj
    Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-ne
5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

NuGet Config files used:
    /home/ux1/AlpineSkiHouse/src/nuget.config
    /home/ux1/.nuget/NuGet/NuGet.Config

Feeds used:
    https://www.myget.org/F/imageprocessor/api/v3/index.json
    https://api.nuget.org/v3/index.json

Installed:
    149 package(s) to /home/ux1/AlpineSkiHouse/src/AlpineSkiHouse.Web/AlpineSkiHouse.Web.csproj
```
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by piotrpMSFT** [comment] 2016-11-10 00:43
@livarcocc tracked down this issue after we chatted. The root cause is that the ASP.NET packages referenced after migration are not yet on NuGet and other package versions are being picked up. This should be fixed once the next wave of NuGet packages gets pushed to NuGet.org.

**Closed by piotrpMSFT** 2016-11-10 00:43 UTC
