### ISSUE TITLE
[Preview 2] - dotnet cli not finding tool located in solution dir

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#3802] opened 2016-07-07 13:16 UTC
## Steps to reproduce
Create a solution, with a project A and a project B.

Project A is a tool similar to: https://github.com/aspnet/IISIntegration with an output name: dotnet-gluon-tool

Project B is an application that uses the tool. Add a reference to the tool project to Project B. Project B's project.json should end up having these entries:

```
"dependencies": {
 "Gluon.Tool": "1.0.0-*"
},

"tools": {
 "Gluon.Tool": {
      "version": "1.0.0-*",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
}
```

Now cd into Project B's project directory and run `dotnet gluon-tool`:

## Expected  behavior

`dotnet` finds the tool project in my solution's directory and runs it.

## Actual behavior

`dotnet` doesn't find the tool within the solution, and throws an exception saying it can't find it in my nuget packages directory:

![image](https://cloud.githubusercontent.com/assets/3176632/16652614/970b4080-4443-11e6-8e3f-75c033538a17.png)

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/3176632/16654373/6282b15e-444d-11e6-8b9a-5b10910be90f.png)

**Comment by victorhurdugaci** [comment] 2016-07-07 15:37
This is a known issue: https://github.com/dotnet/cli/issues/1215

**Comment by blackdwarf** [comment] 2016-07-21 16:58
Closing this one as a duplicate of #1215. For now, as of Preview 2, tools need to be nuget packages that are restored using `dotnet restore`.

**Closed by blackdwarf** 2016-07-21 16:58 UTC
