### ISSUE TITLE
Dotnet publish output parameter doesn't work

### ISSUE THREAD

**Issue by libsamek** [dotnet/cli#6700] opened 2017-05-26 12:54 UTC
## Steps to reproduce
```
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> dotnet publish .\Sandbox.sln -c Release -o .\output\
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\docker-compose.dcproj : error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.Docker.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Sandbox.Web -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1\Sandbox.Web.dll
  Sandbox.Api -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1\Sandbox.Api.dll
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> ls -l .\output\
```

Files are available in `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1` and `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1`, which is not what I need. `output` folder remains empty.

## Expected  behavior
Compiled dlls in output folder, in the above example in `.\output`. I would expect dlls in output folder as specified by output argument.

## Actual behavior
There is no actual difference running with or without -o parameter.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

I get the same behavior in container from image `aspnetcore:1.1.2-jessie`.

**Comment by varsis** [comment] 2017-07-14 08:28
I am having the same issue here:
`.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
`

**Comment by dasMulli** [comment] 2017-07-14 08:41
The problem is that the parameter is interpreted **relative to the project**, not to the working directory you call this command from. same goes for `pack`.

This has been reported many times.. @livarcocc @piotrpMSFT since would be a breaking, would it be possible to still do this for 2.0?

**Comment by varsis** [comment] 2017-07-14 12:25
@dasMulli I am calling it like so `dotnet publish -c Release -o out` It still ends up in `bin/Release`

**Comment by dasMulli** [comment] 2017-07-14 12:29
@varsis are you sure there isn't an `out` subdirectory created in each project's directory? (there will still be assemblies in `bin/Release`)

**Comment by JSONVoorhees** [comment] 2018-01-29 08:09
I suspect my issue is related to this one. 

```
$ dotnet publish --self-contained -o './Deploy/server/' -c 'Release' -r 'ubuntu.16.04-x64'
$ find Deploy/ -type d
Deploy/
Deploy/server
Deploy/server/it
Deploy/server/es
Deploy/server/ja
Deploy/server/refs
Deploy/server/ru
Deploy/server/ko
Deploy/server/zh-Hans
Deploy/server/zh-Hant
Deploy/server/fr
Deploy/server/de
```
But then on re-running:

```
$ dotnet publish --self-contained -o './Deploy/server/' -c 'Release' -r 'ubuntu.16.04-x64'
$ find Deploy/ -type d
Deploy/
Deploy/server
Deploy/server/it
Deploy/server/es
Deploy/server/Deploy
Deploy/server/Deploy/server
Deploy/server/ja
Deploy/server/refs
Deploy/server/ru
Deploy/server/ko
Deploy/server/zh-Hans
Deploy/server/zh-Hant
Deploy/server/fr
Deploy/server/de
```
It will continue to nest like this with each call.

**Comment by dasMulli** [comment] 2018-01-29 08:12
@JSONVoorhees your issue is that all files inside the directory where the csproj is is considered part of the project.

So when you publish again, the publish output from the previous call is now considered part of the project and also copied to the publish output directory.

**Comment by JSONVoorhees** [comment] 2018-01-29 08:16
Ah, I see. Not ideal, I'll adjust things around to avoid that. Thank you!

**Comment by livarcocc** [comment] 2018-01-29 18:22
We missed the train on this one for the 2.0 release. Moving it to the backlog to be picked up in 3.0.

**Closed** 2018-09-10 18:01 UTC
Labels: breaking-change
