### ISSUE TITLE
Unexpected result for dotnet publish when publishing the second time

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/cli#9541] opened 2018-06-22 08:21 UTC
## Steps to reproduce
1. dotnet new web
2. Run command "dotnet publish --output ./publish --configuration Release"
3. Run command "dotnet publish --output ./publish --configuration Release" again
## Expected  behavior
Step 3 will override the files created in Step 2.

## Actual behavior
Step 3 will create new "publish" Folder in publish folder

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.201)

Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

![command](https://user-images.githubusercontent.com/16079555/41765958-3acad712-7638-11e8-9081-bbf72b956865.PNG)
![result](https://user-images.githubusercontent.com/16079555/41765969-3ea82a24-7638-11e8-8162-8de90d802f33.PNG)

**Comment by dasMulli** [comment] 2018-06-22 12:03
when you publish inside the project folder, the publish output of the first call will become part of the project. if you have VS open, it will show the files as part of the project. so `publish\Test.dll` will be part of the project at the time you publish the second time and thus copied to `publish\publish\Test.dll`.

if you call `dotnet publish ..\publish-output`, you won't have this problem since you don't create files and folders next to the csproj file.

**Comment by livarcocc** [comment] 2018-06-22 17:56
Yes. This is the current behavior and globing is working as designed.

**Closed by livarcocc** 2018-06-22 17:56 UTC
