### ISSUE TITLE
dotnet publish self-contained app give weird executable name

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/cli#6996] opened 2017-06-23 21:11 UTC
## Steps to reproduce

```
dotnet --version
2.0.0-preview2-006502
```

My console app is called `agent.listener` and `agent.worker`
after `dotnet publush --runtime linux-x64`,
i got following under bin:
`agent.listener.dll`, 
`agent.listener.listener`,
`agent.worker.dll`, 
`agent.worker.worker` 

## Expected  behavior

i suppose to get `agent.listener` and `agent.worker`

**Comment by livarcocc** [comment] 2017-06-26 17:11
Duplicate of https://github.com/dotnet/cli/issues/6397.

**Closed by livarcocc** 2017-06-26 17:11 UTC
