### ISSUE TITLE
Debugging native/ c code in vs2015 .Net core RC2 .

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/cli#4002] opened 2016-08-05 06:30 UTC
## Steps to reproduce
Create a  .Net Core Console Application which should refer to a .Net Core package say for ex: corepack1 . corepack1 is depended on nativecode which for ex say nativecode.dll .

## Expected  behavior
When i launch the console app using vs2015 update 2, i am able to debug into corepack1 which is the .Net Core package, but i am not able to step into nativecode.dll which is c based dll. I have the pdb for native code  and still i am not able to step into the native code.

## Actual behavior
Step into the native code.

Tried different ways , few are  attaching the code opening in other project, put a breakpoint into the native source code  .

I got a suggestion of using command line and use "dnx --debug run . args" , but when i use the option with dotnet i do not see --debug .

So is --debug option supported ? if yes, will i be able to step into native code ?

I am using VS2015 tooling preview 1. 

## Environment data
c:\Users\IBM_ADMIN\Desktop\db2core\samp>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

Please help me out in debugging the native code.

Thanks and Regards,
Prashanth.

**Comment by svick** [comment] 2016-08-05 11:41
This seems to be the same issue as https://github.com/dotnet/corefx/issues/10524.

Also, I don't know if it's going to solve your issue, but you should upgrade to the latest .Net Core SDK/VS Tools (preview 2).

**Comment by blackdwarf** [comment] 2016-08-07 14:26
Closing this one as a dupe of dotnet/corefx#10524.

**Closed by blackdwarf** 2016-08-07 14:26 UTC
