### ISSUE TITLE
Support nuget's "fallback package target" feature in DependencyContext

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#3569] opened 2016-06-14 20:15 UTC
NuGet now supports a secondary package target to improve `dotnet restore` performance. The idea is to populate the secondary folder for Azure Web Sites to improve kudu restore performance.

This WI is to complete the work and add the support for this secondary package folder in DependencyContext as well. This would fix the `dotnet run` scenario for MVC runtime view compilation as well as `dotnet test` scenarios. 

This can be done for CLI preview3. We have punted the work from CLI preview2 in the core war today.

cc @piotrpMSFT @Petermarcu  @Eilon @davidfowl

**Comment by eerhardt** [comment] 2016-06-15 13:48
Seems like a dupe of #3372

**Comment by muratg** [comment] 2016-06-15 15:47
@eerhardt My understanding was there was code duplication, but perhaps I'm wrong. @davidfowl Thoughts?

**Comment by eerhardt** [comment] 2016-06-15 16:49
> My understanding was there was code duplication

Code duplication between where?

FYI - I have this feature supported in this PR #3554, which doesn't have the official NuGet support yet and wasn't approved for preview2 (as you noted above).

**Comment by muratg** [comment] 2016-06-15 17:05
@pakrym ?

**Comment by pakrym** [comment] 2016-06-15 17:10
@eerhardt DependencyContext is separate library that does not depend on nuget or projectmodel and used for runtime dynamic compilation.

**Comment by eerhardt** [comment] 2016-06-15 17:15
So what about `DependencyModel` needs to support nuget fallback sources if it doesn't depend on nuget?

**Comment by pakrym** [comment] 2016-06-15 17:16
Does not depend on nuget libraries, so it needs to duplicate logic.

**Comment by piotrpMSFT** [comment] 2016-11-10 07:49
Moved to core-setup

**Closed by piotrpMSFT** 2016-11-10 07:49 UTC
