### ISSUE TITLE
Removing "testrunner": "xunit" from TestLibraryLesser test asset causes binding redirect generation to fail.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2570] opened 2016-04-18 19:24 UTC
Removing "testrunner": "xunit" from TestLibraryLesser test asset causes binding redirect generation to fail.

I ran into this in #2450, for now I've just added back the node in project.json but this is pretty weird.

This is the file:
https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/TestProjects/TestBindingRedirectGeneration/TestLibraryLesser/project.json

cc @pakrym @anurse @Sridhar-MS @piotrpMSFT

**Comment by anurse** [comment] 2016-04-18 21:44
This was originally by design. Binding Redirects are only generated for executables (including Unit Tests) so you need either `emitEntryPoint` or `testRunner`. I do agree that it may not be the ideal behavior though. We should consider just emitting them for every assembly (as long as we don't copy them around, because that's going to be a lot of `.dll.config` files :))

**Comment by Sridhar-MS** [comment] 2016-04-18 21:52
Why do we need to emit binding redirects for dlls? It makes sense only in the context of the app. Am I missing something here?

**Comment by anurse** [comment] 2016-04-18 23:02
In the case of a test runner, when the runner loads the DLL we need it to honor the binding redirects for that DLL (and it does, in fact, do that when there is a dll.config next to it)

**Comment by piotrpMSFT** [comment] 2017-01-19 09:36
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.

**Closed by piotrpMSFT** 2017-01-19 09:36 UTC
Labels: bug, fit-n-finish
