### ISSUE TITLE
[ARM32 SDK] Debugging on ARM

### ISSUE THREAD

**Issue by raffaeler** [dotnet/cli#8872] opened 2018-03-22 19:20 UTC
Please provide a better developer experience on ARM devices for both local and remote debugging.

- provide the libsosplugin.so in the sdk (could not find it in the preview bits)
- ability to use device SOS when debugging remotely from VS
- provide a way to get crash dumps from a remote machine and debug them from VS
- provide the ability to step into (F11) the system libraries using the netcore sources (I don't know if there are specific requirements for the described scenario, that is remote debugging and ARM platform)

**Comment by Petermarcu** [comment] 2018-03-22 21:00
@gregg-miskelly @mikem8361 I think these fall into one of your camps. Can you help with guidance and what might be planned as far as a roadmap?

**Comment by gregg-miskelly** [comment] 2018-03-22 21:27
@raffaeler 

For "provide a way to get crash dumps from a remote machine and debug them from VS" would you mind opening either a item on https://visualstudio.uservoice.com/forums/121579-visual-studio-ide?

For "provide the ability to step into (F11) the system libraries", are you talking about .NET Framework managed system libraries? If so, this is in flight for .NET Core 2.1. VS Code support is available now (see [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Debugging-into-the-.NET-Framework-itself)) and VS support is in flight and expected to ship with Visual Studio 2017 version 15.7.

**Comment by gregg-miskelly** [comment] 2018-03-22 21:34
Missed one. 

For "ability to use device SOS when debugging remotely from VS" you are certainly welcome to open a uservoice item for this. But to be frank, not enough users understand/appreciate sos level debugging for it to be all that likely that the VS team will fund this work. Though if you get lots of votes, maybe this could change. I will say that it probably possible to fork the (MIEngine)[https://github.com/Microsoft/MIEngine] and build an lldb-mi to make something like this possible if you are really interested in this and are willing to do work on it yourself.

**Comment by raffaeler** [comment] 2018-03-22 22:00
@gregg-miskelly here is the [thread on UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33722614-get-crash-dumps-from-a-remote-machine-and-debug-th)

F11. Yes, that is what I mean. Great, I will deep dive in the provided link, thank you.

SOS. I understand that SOS is hard, but it is also the only way to understand certain problems. So let me insist that this is a primary requirement for any company willing to invest in NetCore and going in production on platform different than Windows.
I am already doing it with lldb, but it is even hard to find the correct libsosplugin.so (when not deploying in SCD) or the lldb version itself.

**Comment by mikem8361** [comment] 2018-03-22 22:06
We are working toward making our libsosplugin.so story better and making versions of the plugin easily available for more lldb versions and platforms (arm32). I don't have a firm schedule right now.

**Comment by gregg-miskelly** [comment] 2018-03-22 22:07
RE: Crash dumps - Thanks for opening the user voice item. CC @caslan

**Comment by raffaeler** [comment] 2018-03-22 22:08
BTW can somebody tell me if the mixed debugging is something that is going to happen? (I mean both on Windows and xplat).

**Comment by gregg-miskelly** [comment] 2018-03-22 22:46
Windows x86/x64 .NET Core mixed mode works today.
We don't have any plans to do mixed mode on Linux/OSX, or Windows arm/arm64.

**Comment by livarcocc** [comment] 2018-03-23 00:21
Given that there does not seem to be an action item on the CLI for this, I am going to close this issue.

**Closed by livarcocc** 2018-03-23 00:21 UTC

**Comment by Petermarcu** [comment] 2018-03-23 00:57
Looks like there was one item in here that we should make sure is tracked so people can follow along. @mikem8361 is there an issue someone tracking the libsoplugin work? https://github.com/dotnet/cli/issues/8872#issuecomment-375473243

**Comment by raffaeler** [comment] 2018-03-23 09:33
Are all the proposed items tracked elsewhere?
I would like either to follow them or create the issue if needed. (I am currently travelling, so it may take few days)

**Comment by noahfalk** [comment] 2018-04-09 23:59
@raffaeler - I've opened new tracking issues that I think cover 1 and 4 above. You also opened the VS user voice issue which I think was intended to cover 2 and 3. Let me know if you still think there are gaps in the requests and we'll get it sorted out.

Also a question on your user voice request - right now there are some non-trivial technical issues making our library that inspects dumps operate on a different OS or bitness machine than the one which created the dump. You could imagine a VS dump debugging scenario that leveraged a remote Linux machine, similar to remove live debugging, that would avoid needing to solve those technical issues and thus be much cheaper to implement. I suspect its not what you had in mind, but it would be great feedback to know how worthwhile the $$ feature is vs. the $$$$$ feature ; )

Thanks!
