### ISSUE TITLE
dotnet migrate of project reference produces broken build

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#4337] opened 2016-10-06 18:26 UTC
## Steps to reproduce

1. Create a simple project-to-project reference between two project.json projects. I have an example here which has "project1" referencing "project2": [p2pmigrate.zip](https://github.com/dotnet/cli/files/514475/p2pmigrate.zip).
1. `cd` to the project containing the project reference
1. `dotnet migrate`
1. `dotnet restore3`
1. `dotnet build3`

## Expected  behavior

The build should succeed (building both projects).

## Actual behavior

The build fails:

```
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/6/2016 11:24:28 AM.
Project "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" on node 1 (Build target(s)).
Project "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (1) is building "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (1:2) on node 1 (Build target(s)).
Project "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (1:2) is building "C:\Users\jver\Desktop\p2pmigrate\project2\project2.csproj" (2) on node 1 (GetTargetFrameworkProperties target(s)).
C:\Users\jver\Desktop\p2pmigrate\project2\project2.csproj : error MSB4057: The target "GetTargetFrameworkProperties" does not exist in the project.
Done Building Project "C:\Users\jver\Desktop\p2pmigrate\project2\project2.csproj" (GetTargetFrameworkProperties target(s)) -- FAILED.

Done Building Project "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (Build target(s)) -- FAILED.

Done Building Project "C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (Build target(s)) -- FAILED.


Build FAILED.

"C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (Build target) (1) ->
"C:\Users\jver\Desktop\p2pmigrate\project1\project1.csproj" (Build target) (1:2) ->
"C:\Users\jver\Desktop\p2pmigrate\project2\project2.csproj" (GetTargetFrameworkProperties target) (2) ->
  C:\Users\jver\Desktop\p2pmigrate\project2\project2.csproj : error MSB4057: The target "GetTargetFrameworkProperties" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.41
```

Additionally, it looks like the package references and project references are getting different conditions. 
Project:
`'$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0'`
Package:
`'$(TargetFramework)' == 'netcoreapp1.0'`

Because of this, restore fails to include `project2.csproj` in the assets file,.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003770)

Product Information:
 Version:            1.0.0-preview3-003770
 Commit SHA-1 hash:  09e8877bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by joelverhagen** [comment] 2016-10-06 18:53
Here are the .csproj files for each of the two migrated projects:

project1.csproj (which references project2):
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
    <DebugType>portable</DebugType>
    <AssemblyName>project1</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoUnify>true</AutoUnify>
    <DesignTimeAutoUnify>true</DesignTimeAutoUnify>
    <ProjectLockFile>$(MSBuildProjectDirectory)/project.lock.json</ProjectLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <ProjectReference Include="..\project2\project2.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <DefineConstants>$(DefineConstants);NETCOREAPP1_0</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE;TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

project2.csproj
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <DebugType>portable</DebugType>
    <AssemblyName>project1</AssemblyName>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoUnify>true</AutoUnify>
    <DesignTimeAutoUnify>true</DesignTimeAutoUnify>
    <ProjectLockFile>$(MSBuildProjectDirectory)/project.lock.json</ProjectLockFile>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <ProjectReference Include="..\project2\project2.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <DefineConstants>$(DefineConstants);NETCOREAPP1_0</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE;TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
    <DebugType>portable</DebugType>
    <AssemblyName>project2</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoUnify>true</AutoUnify>
    <DesignTimeAutoUnify>true</DesignTimeAutoUnify>
    <ProjectLockFile>$(MSBuildProjectDirectory)/project.lock.json</ProjectLockFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <DefineConstants>$(DefineConstants);NETCOREAPP1_0</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE;TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by joelverhagen** [comment] 2016-10-06 19:02
The duplicate metadata shown in project2.csproj above is fixed with https://github.com/dotnet/cli/issues/4305 but the same build3 failure still occurs.

**Comment by brthor** [comment] 2016-10-06 20:44
Looking into this.

**Comment by brthor** [comment] 2016-10-06 21:01
The issue here doesn't appear to be in migrate. It appears to be that in order to `dotnet build3` a project with a project reference, all of the projects it references must be restored so the sdk target is brought into that project. 

This seems strange and broken that you'd need to restore all of our dependency projects just to run your top level one and is a gap from the project.json experience. 

@eerhardt @nguerrera @natidea 

Can you comment on if this is an expected behavior or is a bug?

**Comment by eerhardt** [comment] 2016-10-06 21:08
This is a duplicate of https://github.com/NuGet/Home/issues/3577, right?

**Comment by joelverhagen** [comment] 2016-10-06 21:11
Yup, that would fix this problem, I think.

However, the error message provided by build3 should be better if the restore (for whatever reason) has not occurred on those reference projects. Tooling in preview2 said:
```
Project project2 does not have a lock file. Please run "dotnet restore" to generate a new lock file.
Project project2 does not have a lock file. Please run "dotnet restore" to generate a new lock file.
```

(not sure why it was displayed twice but the error is much more actionable by the user)

**Comment by eerhardt** [comment] 2016-10-06 21:13
A better error message would be ideal.  But that would be https://github.com/dotnet/sdk 's repsonsibility.  The CLI is no longer enforcing rules, or doing these types of checks.

Please log an issue in the dotnet/sdk repo to get a better error message when the project is not restored.

**Comment by brthor** [comment] 2016-10-06 22:39
I'm going to close this one out guys. I think we've resolved at least that this isn't a migration issue, just some unexpected behavior and need for a better error message.

**Closed by brthor** 2016-10-06 22:39 UTC
