### ISSUE TITLE
Localization work for the CLI

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6114] opened 2017-03-22 20:28 UTC
- [x] Produce CLI's satellite assemblies (PR #6800)
- [x] Carry CLI dependencies' satellite assemblies (#5007)
- [x] Pay-for-play (#6877)

Blocking partner issues:
- [x] https://github.com/Microsoft/msbuild/issues/2187 (In PR)
- [x] https://github.com/Microsoft/msbuild/issues/2203 (In PR)
- [ ] https://github.com/NuGet/Home/issues/5382

**Comment by rainersigwald** [comment] 2017-06-20 19:07
Can you track https://github.com/Microsoft/msbuild/issues/2187 instead of  Microsoft/msbuild#2201 please? I closed the latter as a duplicate of the former.

**Comment by rainersigwald** [comment] 2017-06-20 19:08
MSBuild PRs out for

- [ ] Microsoft/msbuild#2187
- [ ] https://github.com/Microsoft/msbuild/issues/2203

**Comment by nguerrera** [comment] 2017-06-20 20:57
> Can you track Microsoft/msbuild#2187 instead of Microsoft/msbuild#2201 please?
Fixed.

**Comment by shaggygi** [comment] 2017-10-21 11:31
Any reason this is still open?  Only issue left to close milestone?

**Comment by livarcocc** [comment] 2017-10-21 16:29
We still don't have NuGet satellites.

**Comment by nguerrera** [comment] 2018-01-25 23:04
Let's use #8471 to track nuget satellites.

**Closed by nguerrera** 2018-01-25 23:04 UTC
Labels: Task
