### ISSUE TITLE
Migrated project fails to restore

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4604] opened 2016-11-03 21:51 UTC
**Repro steps**
unzip \scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip to your local machine
from VSMigrationDemo folder run  "dotnet migrate"
![image](https://cloud.githubusercontent.com/assets/12449387/19986686/ebc77dde-a1d4-11e6-9a78-96f3739156da.png)

run dotnet restore

![image](https://cloud.githubusercontent.com/assets/12449387/19986702/fa70dc0e-a1d4-11e6-9805-8792be100f6c.png)

## Environment data
d15rel/15.0.25902.2
1.0.0-preview3-004040

**Comment by livarcocc** [comment] 2016-11-03 22:00
This is happening because restore is picking up this metaproj file to run the restore for.

Can you try running dotnet restore <your_file>.csproj?

**Comment by jinujoseph** [comment] 2016-11-03 22:11
@livarcocc  , going to individual project directory and restoring works

**Comment by livarcocc** [comment] 2016-11-04 17:23
@jinujoseph dotnet restore does not support restoring a folder. It supports restoring an individual project, a solution file or a chain of projects. If you run dotnet restore on projectA and projectA depends on ProjectB. ProjectB will also be restored.

**Comment by jinujoseph** [comment] 2016-11-07 08:12
![image](https://cloud.githubusercontent.com/assets/12449387/20050557/d2e93f44-a47e-11e6-8562-e21417bcdb5e.png)

The folder does contain solution file.

**Comment by livarcocc** [comment] 2016-11-10 20:46
Does this work if you invoke dotnet restore VSMigrationDemo.sln?

**Comment by piotrpMSFT** [comment] 2016-11-10 21:14
Once we get @jinujoseph unblocked, we need an issue for `dotnet restore` in NuGet/Home to fix the UX here.

**Comment by piotrpMSFT** [comment] 2016-11-11 10:07
This ends up being a dupe of https://github.com/dotnet/cli/issues/4687. The sln file fails to restore 'cause it is referencing non-existant csproj files.

**Closed by piotrpMSFT** 2016-11-11 10:07 UTC

**Comment by jinujoseph** [comment] 2016-11-14 18:01
@livarcocc , just to answer your question.
![image](https://cloud.githubusercontent.com/assets/12449387/20276494/51422d74-aa51-11e6-920b-d3a46d7f7caf.png)

**Comment by piotrpMSFT** [comment] 2016-11-15 19:49
@jinujoseph you should be able to fix up the sln to point to the post-migrated file instead.

**Comment by fubar-coder** [comment] 2016-12-25 11:50
@piotrpMSFT This bug isn't fixed in 1.0.0-preview5-004275. The solution file is points indeed to an existing csproj file, but the problem still exists. Please stop closing issues that aren't fixed yet.

**Comment by fubar-coder** [comment] 2016-12-25 11:56
The same error message occurs when a project references something that doesn't exist any more.
