### ISSUE TITLE
Configure.PS1 fails installing .NET CLI

### ISSUE THREAD

**Issue by jainaashish** [dotnet/cli#7867] opened 2017-10-18 21:35 UTC
Copied from https://github.com/NuGet/Home/issues/6049 

After cloning the NuGet.Client repo and following the instructions to configure for a build. Configure.PS1 fails when attempting to download the .NET CLI. The output from the Powershell console is below:

`PS D:\Reference Source\Microsoft\nuget\nuget.client> .\configure.ps1
[17:10:09 +0] Configuring NuGet.Client build environment
[17:10:09 +0] [BEGIN] Configuring git repo
[17:10:09 +0] [DONE +00:00:00] Configuring git repo
[17:10:09 +0] [BEGIN] Installing NuGet.exe
NuGet Version: 4.0.0.2283
http-cache: C:\Users\spmys\AppData\Local\NuGet\v3-cache
global-packages: C:\Users\spmys.nuget\packages
temp: C:\Users\spmys\AppData\Local\Temp\NuGetScratch
[17:10:09 +0] [DONE +00:00:00] Installing NuGet.exe
[17:10:09 +0] [BEGIN] Installing .NET CLI
.NET Command Line Tools (1.0.1)

Product Information:
Version: 1.0.1
Commit SHA-1 hash: 005db40cd1

Runtime Environment:
OS Name: Windows
OS Version: 6.1.7601
OS Platform: Windows
RID: win7-x64
Base Path: D:\Reference Source\Microsoft\nuget\nuget.client\cli1.0.4\sdk\1.0.1
[17:10:10 +0] Downloading .NET CLI
Error-Log : [17:10:13 +3] [FAILED +00:00:03] Installing .NET CLI
At D:\Reference Source\Microsoft\nuget\nuget.client\build\common.ps1:142 char:17

... Error-Log "[FAILED +$(Format-ElapsedTime $sw.Elapsed)] $B ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Error-Log
Exception calling "Invoke" with "0" argument(s): "Failed to download
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version."
At D:\Reference Source\Microsoft\nuget\nuget.client\cli\dotnet-install.ps1:106 char:20

        return $ScriptBlock.Invoke()
               ~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [], ParentContainsErrorRecordException
FullyQualifiedErrorId : RuntimeException
PS D:\Reference Source\Microsoft\nuget\nuget.client>`

Any thoughts on what the issue is and how to resolve it?

**Comment by livarcocc** [comment] 2017-10-18 22:05
@mhsimkin is this 100% reproducible for you? Have you tried invoking the install script separately? These would be super useful information for us.

The script should work in win7 and we haven't had reports of failures of this nature on it so far. So, I am wondering if there is a chance for flakiness here or for some network problem.

**Comment by livarcocc** [comment] 2017-10-18 22:06
@johnbeisner can you please try this out in a win7 box?

**Comment by mhsimkin** [comment] 2017-10-18 22:37
@livarcocc I tried it a couple of time.  I rebooted in between each attempt.

I went to the the [DotNet Core archive page](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) to download the SDK to install it, just to make sure there where no issues.

Can you please elaborate on how you would like me to invoke the install script separately.

I wouldn't be surprised if it is a firewall issue at the place I work.  I never know what is blocked (and there seems to be no rhythm or reason).  Is the install script trying to use a download source that is not download.microsoft.com or github.com?

FYI, if it is a firewall issue, it might be a good enhancement to provide instructions on how to download the required files manually, and then pass the disk location via a parameter to the script.

-marc

**Comment by livarcocc** [comment] 2017-10-18 22:54
It is trying to download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version right now and failing. So, not download.microsoft.com nor github.com. Can you download the file above from a browser?

**Comment by mhsimkin** [comment] 2017-10-19 14:35
@livarcocc My corporate firewall is blocking the request to the secure site[https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version) but not to insecure site[http://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version](http://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version).

As an enhancement maybe a command line parameter could be added that will allow the use of HTTP instead of HTTPS.

-marc

**Comment by johnbeisner** [comment] 2017-10-19 17:08
I cannot reproduce this error on Windows 7. 
Is this behavior a recent change? Could it be that your corporate firewall has changed it's policies recently?

**Comment by livarcocc** [comment] 2017-10-19 17:21
@johnbeisner this is happening because @mhsimkin company is blocking the URL. Nothing wrong with our scripts.

@mhsimkin I am not sure enabling a http URL option is the right approach here. Can't you just ask to have that URL enabled for https?

**Comment by livarcocc** [comment] 2017-10-19 18:00
This is really up to the NuGet build script. You can get a CLI manually and put it where their build script expects it to be and then just locally comment out the install script invocation.

**Comment by mhsimkin** [comment] 2017-10-19 18:06
ok.  Please consider this resolved.

Thanks

-marc

**Comment by johnbeisner** [comment] 2017-10-19 18:12
closing...

**Closed by johnbeisner** 2017-10-19 18:12 UTC
Labels: Install-Script
