### ISSUE TITLE
Cross-platform standalone publish produces not working executables

### ISSUE THREAD

**Issue by MartinJohns** [dotnet/cli#2394] opened 2016-04-10 19:36 UTC
## Steps to reproduce
1. Be on Windows.
2. Create a new project.
3. Have the runtime `ubuntu.14.10-x64` in your project.json file.
4. Deploy with the target runtime: `dotnet publish --runtime ubuntu.14.04-x64`

The other way around has the same issue, be on Ubuntu and try to create binaries for Windows.

## Expected  behavior
I end up with a directory containing a version that I can deploy to and run on Ubuntu 14.04.

## Actual behavior
The publish directory contains a `project.exe` file, which can't be executed on Ubuntu.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002339)

Product Information:
 Version:     1.0.0-rc2-002339
 Commit Sha:  2be5e84f87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by MartinJohns** [comment] 2016-04-11 04:39
Likely related: https://github.com/dotnet/cli/pull/2220 - [donotmerge] Enable Cross Platform Publishing and add tests

**Comment by Sridhar-MS** [comment] 2016-04-11 16:40
cc @brthor

**Comment by brthor** [comment] 2016-04-11 17:38
This is a dupe of #2141 

Working on #2220  now

**Closed by brthor** 2016-04-11 17:38 UTC
