### ISSUE TITLE
compile error: `dotnet new` should create folder

### ISSUE THREAD

**Issue by benaadams** [dotnet/cli#686] opened 2016-01-03 09:09 UTC
Opening a command window takes you to user folder root (e.g. `C:\Users\Ben>`)

If you follow the instructions there e.g.
```
dotnet new
dotnet restore
dotnet run
```
The last step takes a very long time then fails with
> C:\Users\Ben>dotnet run
Access to the path 'C:\Users\Ben\AppData\Local\ElevatedDiagnostics' is denied.

If you run as admin in same place it then fails with
> C:\Users\Ben>dotnet run
Access to the path 'C:\Users\Ben\AppData\Local\Microsoft\Windows\INetCache\Content.IE5' is denied.

Trying other combinations leads to similar errors
> C:\Users\Ben>dotnet -v run
Running C:\Program Files\dotnet\bin\dotnet-build.exe --output "C:\Users\Ben\bin\.dotnetrun\8e28922490d74855874fb198488ac959" --temp-output "C:\Users\Ben\bin\.dotnetrun\8e28922490d74855874fb198488ac959" --framework "DNXCore,Version=v5.0" --configuration "Debug" C:\Users\Ben
Process ID: 7812
Running C:\Program Files\dotnet\bin\dotnet-compile.exe --framework DNXCore,Version=v5.0 --configuration Debug --output "C:\Users\Ben\bin\.dotnetrun\8e28922490d74855874fb198488ac959" --temp-output "C:\Users\Ben\bin\.dotnetrun\8e28922490d74855874fb198488ac959" "C:\Users\Ben"
Process ID: 13232
Compiling Ben for DNXCore,Version=v5.0
Access to the path 'C:\Users\Ben\AppData\Local\ElevatedDiagnostics' is denied.

and
> C:\Users\Ben>dotnet build
Compiling Ben for DNXCore,Version=v5.0
Access to the path 'C:\Users\Ben\AppData\Local\ElevatedDiagnostics' is denied.

Creating a new directory and running it there, all is good

**Comment by blackdwarf** [comment] 2016-01-06 18:28
@benaadams this is now tracked in #655 as well.

**Comment by piotrpMSFT** [comment] 2016-05-11 01:07
Dupe of #655

**Closed by piotrpMSFT** 2016-05-11 01:07 UTC
Labels: bug
