### ISSUE TITLE
Target ProjectModel.Loader and ProjectModel.Workspaces for net 451 

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#1540] opened 2016-02-23 19:54 UTC
#876 was closed after addressing only the ProjectModel project. 
So opening a new one to track the Loader and Workspaces projects.

**Comment by prafullbhosale** [comment] 2016-02-23 19:54
cc @pranavkm @pakrym @sayedihashimi

**Comment by sayedihashimi** [comment] 2016-02-25 17:06
I've marked this as `blocking-partner`. I assume that the EF team also needs Workspaces (and maybe loader) supported on .net451 as well.

cc @rowanmiller @bricelam

**Comment by bricelam** [comment] 2016-02-25 19:27
`AssemblyLoadContext` doesn't exist on `net451`, so I don't think ProjectModel.Loader *can* `target net451`. On EF, we'll probably use an AppDomain-based strategy there similar to how our NuGet PowerShell commands work.

**Comment by davidfowl** [comment] 2016-03-08 07:37
Workspaces should be easy. Loader needs some thought.

**Comment by danroth27** [comment] 2016-04-08 17:18
Both of these packages now target netstandard1.5, which should work on .NET 4.6.2. @prafullbhosale @sayedihashimi Is this sufficient? If yes, then please close.

**Comment by NTaylorMullen** [comment] 2016-04-11 19:51
@danroth27 @Eilon @DamianEdwards @muratg @anurse  this means that `dotnet-razor-tooling`, `ef`, `scaffolding` tools etc (anything that must load a users project) will not be able to work on user projects that target anything less than net 4.6.2.

I assume since Razor targets net451 that our expectations are mismatched. All that are CC'd is this OK?

This blocks with the assumption that net 4.6.2 isn't low enough :smile: 
- https://github.com/aspnet/RazorTooling/issues/55
- https://github.com/aspnet/EntityFramework/issues/4577

**Comment by NTaylorMullen** [comment] 2016-04-11 19:58
Hmm actually, in the form of command line arguments and ifdefs we may be able to work around the limitation. Aka, scavenge all the information needed about a users project in the netstandard process prior to dispatching to the net45 variation of the same tool.

Seems like a poor tool authoring experience, but doable. Consider my question above rephrased to be: Should we do the workaround work or is the net 4.6.2 limitation acceptable?

**Comment by anurse** [comment] 2016-04-11 20:42
`ProjectModel.Loader` is certainly only designed for use in .NET Core apps, so it doesn't make sense to have a desktop version since there's no such thing as a Load Context on desktop. Working around it seems like the best option right now.

**Comment by muratg** [comment] 2016-04-11 21:16
cc @divega @natemcmaster @bricelam

**Comment by Eilon** [comment] 2016-04-11 23:36
From my understanding, this does not sound acceptable to me. These need to work on .NET 4.5.1.

@DamianEdwards can you comment?

**Comment by Eilon** [comment] 2016-04-11 23:48
Is there anything preventing ProjectModel from targeting a much, much lower `netstandard` version? Like 1.0 even?

**Comment by anurse** [comment] 2016-04-12 16:52
ProjectModel and ProjectModel.Workspace can definitely either cross-target or target a lower `netstandard`. The problem is the Loader is based on `AssemblyLoadContext` which is a CoreCLR thing. Desktop apps need to use an AppDomain. The Loader is a tiny part of the API though, so it's pretty easy to re-implement using AppDomains

**Comment by danroth27** [comment] 2016-04-13 20:36
@muratg Is @anurse available to look at this?

**Comment by piotrpMSFT** [comment] 2016-04-13 23:04
Assigning @muratg for the time being. We need someone familiar with project model [@anurse, @pakrym] to take this on.

**Comment by anurse** [comment] 2016-04-13 23:13
I can take a look at this now

**Comment by anurse** [comment] 2016-04-13 23:14
Ok, first glance, it looks like NuGet is going to be the first problem. It targets `netstandard1.5`, so everything of ours that references it has to as well.

/cc @emgarten

**Comment by anurse** [comment] 2016-04-13 23:16
https://github.com/NuGet/Home/issues/2538 will block this.

**Comment by anurse** [comment] 2016-04-13 23:24
Also, it appears System.CommandLine only targets `netstandard1.3` which will block `ProjectModel.Workspaces` from cross-targeting `net451`. I can drop it to `netstandard1.3` (which correlates with .NET 4.6)

The others already cross-target `net451`, with the exception of `ProjectModel.Loader` because it depends on CoreCLR/.NET 4.6.2 features (Load Contexts). On .NET <4.6.2 AppDomains should be used to emulate that functionality (Razor tooling, for example, would need to set that up itself).

Does this sound right @Eilon @NTaylorMullen ?

**Comment by NTaylorMullen** [comment] 2016-04-13 23:35
@anurse how would I replicate the `CreateLoadContext` functionality from `ProjectContext`? Just duplicate the code manually?

**Comment by anurse** [comment] 2016-04-14 00:27
In that case yes, and I could see the value in adding some API to ProjectContext to get the same data. @natemcmaster has an updated version of the LoadContext that we'll be taking post RC2 so we can do it in that.

**Comment by natemcmaster** [comment] 2016-04-14 00:54
> @natemcmaster has an updated version of the LoadContext that we'll be taking post RC2 so we can do it in that.

For anyone looking for that, it is in [aspnet/EntityFramework/src/dotnet-ef/Loader/](https://github.com/aspnet/EntityFramework/tree/72af85c13f09654dea9e8cc91a8a70d71c7f1451/src/dotnet-ef/Loader)

**Comment by Eilon** [comment] 2016-04-14 07:30
@anurse thanks - who owns CommandLine? That seems like it could easily target netstandard1.0 as well, at least conceptually. Pretty sure that string parsing is supported all the way back to .NET 1.0 😄

**Comment by anurse** [comment] 2016-04-14 16:07
It's in dotnet/corefxlab , not sure exactly who owns it. Might be @piotrpMSFT

**Comment by Eilon** [comment] 2016-04-15 00:59
@anurse can you log a bug there with the necessary info? I want to make sure we don't lose track of this.

**Comment by anurse** [comment] 2016-04-15 16:26
https://github.com/dotnet/corefxlab/issues/655

**Comment by piotrpMSFT** [comment] 2016-04-21 23:06
System.CommandLine is no longer a dependency of CLI. #2594 addressed this. @anurse, when do you expect this issue to get closed?

**Comment by anurse** [comment] 2016-04-22 02:19
I'll change ProjectModel.Workspace to target net451 tomorrow morning, which should resolve this issue. There's also a similar problem in NuGet, and we'll need to take a new NuGet to fix that. I'm not sure the status of that.

**Comment by danroth27** [comment] 2016-04-22 05:00
[DocFx](https://github.com/dotnet/docfx) is taking a dependency on ProjectModel.Workspace and having net451 support would allow them to run on Mono for their initial xplat story. Long term they will move to .NET Core, but they are blocked on a bunch of 3rd party dependencies.

**Comment by anurse** [comment] 2016-04-25 21:06
We've added a net451 target to ProjectModel.Workspace. As far as I know that should resolve this issue. Let me know if there's anything else that needs to be updated!

**Closed by anurse** 2016-04-25 21:06 UTC
Labels: aspnet, blocking-partner
