### ISSUE TITLE
dotnet test failure on OS X 10.11.2

### ISSUE THREAD

**Issue by devigned** [dotnet/cli#680] opened 2015-12-31 20:18 UTC
project.json:
```json
{
  "version": "1.4.2-preview",
  "summary": "ClientRuntime Tests.",
  "authors": [ "Microsoft" ],
  "tags": [ "Microsoft AutoRest ClientRuntime REST" ],
  "projectUrl": "https://github.com/Azure/AutoRest",
  "licenseUrl": "https://raw.githubusercontent.com/Microsoft/dotnet/master/LICENSE",
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "System.Diagnostics.Tools": "4.0.0",
        "System.Net.Http": "4.0.0",
        "System.Threading.Tasks": "4.0.11-beta-23516",
        "System.Xml.ReaderWriter": "4.0.10",
        "Microsoft.CSharp": "4.0.0"
      }
    }
  },

  "dependencies": {
    "Microsoft.Rest.ClientRuntime": "",
    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*"
  }
}
```

```
$ dotnet build
Compiling Microsoft.Rest.ClientRuntime for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.1812561Compiling Microsoft.Rest.ClientRuntime.Tests for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3977259 (The compilation time can be improved. Run "dotnet build --profile" for more information)
```

```
$ dotnet test
dotnet-test Error: 0 : System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Test.Program.RunConsole(ProjectContext projectContext, CommandLineApplication app, String testRunner)
   at Microsoft.DotNet.Tools.Test.Program.<>c__DisplayClass0_0.<Main>b__0()
```

Thoughts?

**Comment by devigned** [comment] 2015-12-31 20:49
This might be related to: https://github.com/dotnet/cli/issues/407

**Comment by muratg** [comment] 2015-12-31 22:25
cc @piotrpMSFT

**Comment by piotrpMSFT** [comment] 2016-01-12 08:54
@devigned the error message should be improved now :) The issue is that we don't have an xunit runner  package quite ready yet. Now back to work on dotnet-test-xunit

**Comment by piotrpMSFT** [comment] 2016-01-15 20:27
@devigned since the CLI-side issues here are done, I'm closing this issue. We're just waiting on the xunit runner now.

**Closed by piotrpMSFT** 2016-01-15 20:27 UTC
Labels: bug

**Comment by muratg** [comment] 2016-01-15 21:50
@piotrpMSFT How long till we get the xunit runner?  We're blocked on getting rid of DNX in our repos due to this.

**Comment by piotrpMSFT** [comment] 2016-01-15 22:21
I can give you a working prototype offline. Working with xunit to get real bits.

**Comment by devigned** [comment] 2016-01-15 22:43
@piotrpMSFT thank you for the update! Looking forward to the xunit bits.

**Comment by zach-folwick** [comment] 2016-01-18 22:24
@piotrpMSFT - I would be very interested in a prototype test runner.  We've already adopted dotnet-cli and have been missing xunit tests.
