### ISSUE TITLE
Error occurred when min-code is specific.

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/cli#10686] opened 2019-02-01 07:42 UTC
## Steps to reproduce
1. Create a new console app in VS
2. Modify the csproj with the following: `<Project Sdk="Microsoft.NET.Sdk/min=9999">
`
It shows as below:
![image](https://user-images.githubusercontent.com/46206739/52108865-6cfb2a80-2636-11e9-88c8-87afa1fa1c84.png)

3. Reload the project,
## Expected  behavior
There's a error in error list window:
`"The current .NET SDK does not support targeting .NET Core 3.0. Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0."`

## Actual behavior:
Reload the project, it shows the error:
![image](https://user-images.githubusercontent.com/46206739/52108943-bcd9f180-2636-11e9-8c08-3579436e74df.png)

## Environment data
`dotnet --info` output:
```
C:\Users\e2euser>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010197
 Commit:    f80481ad2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010197\

Host (useful for support):
  Version: 3.0.0-preview-27330-4
  Commit:  373df9c049

.NET Core SDKs installed:
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010197 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19080-0484 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27330-4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27330-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by nguerrera** [comment] 2019-02-01 19:03
The expected behavior here was due to another bug in the way of the ultimate experience. Now that that is fixed, we're hitting https://github.com/dotnet/project-system/issues/2467.

I will update the test expectation accordingly.

**Comment by nguerrera** [comment] 2019-02-01 19:03
Duplicate of dotnet/project-system#2467

**Comment by livarcocc** [comment] 2019-02-01 20:55
Closing as a dup of the project system bug @nguerrera linked above.

**Closed by livarcocc** 2019-02-01 20:55 UTC

**Comment by yuki233** [comment] 2019-06-21 10:14
Repro on CLI/SDK: 2.1.605(runtime- 2.1.12), not repro on CLI/SDK: 2.1.508(runtime- 2.1.12)

**Comment by nguerrera** [comment] 2019-06-21 12:46
@yuki233 can you open a new bug and re-document the steps taken since the instructions were changed when this was last reported?
