### ISSUE TITLE
Trying to execute tool that doesn't properly reference Microsoft.NETCore.App leads to bad error.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2448] opened 2016-04-12 23:42 UTC
## Overview

Ran into this guy when developing the Razor tooling. Essentially, I had temporarily removed the `"type": "platform",` portion from my `Microsoft.NETCore.App` inclusion in order to get it to work with Visual Studio and forgot I had done that. Got the misleading error mentioned below which sent me on a wild goose chase for a while. Could forsee other users trying to build their own tools and not getting it right the first time. Minor bug at best :smile:  
## Steps to reproduce
- Change the `Microsoft.NETCore.App` reference in a tool to not have the `"type": "platform",` entry.
- Package the tool
- Reference the tool in a user project
- Restore in the user project.
- Try to execute the tool
## Expected  behavior

Any of the below:  
1. Appropriate failure stating the tool is not valid when trying to restore it in the user project.
2. Smarter error stating that the tool cannot be properly executed since it wasn't built correctly.
## Actual behavior

You get the following error:

```
Policy library either not found in deps [C:\Users\nimullen\.nuget\packages\.tools\dotnet-razor-tooling\1.0.0\netstandardapp1.5\dotnet-razor-tooling.deps.json] or not found in 1 probe paths.
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:                      
 Version:     1.0.0-rc2-002349            
 Commit Sha:  ed9309b90b                  

Runtime Environment:                      
 OS Name:     Windows                     
 OS Version:  10.0.10586                  
 OS Platform: Windows                     
 RID:         win10-x64                   
```

**Comment by krwq** [comment] 2016-04-13 00:10
Could you try updating and retrying? I believe this was fixed today with https://github.com/dotnet/cli/commit/aed81d43db0337623fc708ead37216133b82da8b

**Comment by natemcmaster** [comment] 2016-04-13 00:35
I ran into the same error. 1.0.0-rc2-002357

**Comment by brthor** [comment] 2016-04-13 00:37
The fact that an error is thrown here is by design, since tools must be portable.

We could definitely do a better job of detecting this and throwing before trying to execute the tool though.

**Comment by livarcocc** [comment] 2019-08-17 04:41
Going to close this issue since we are moving away from project tools towards global/local tools.

**Closed by livarcocc** 2019-08-17 04:41 UTC
Labels: fit-n-finish
