### ISSUE TITLE
dotnet build rebuilds every time when the project contains a pre/post-compile script and incremental build gets disabled

### ISSUE THREAD

**Issue by prochan2** [dotnet/cli#4342] opened 2016-10-07 08:51 UTC
## Steps to reproduce
1. Create a new console (or any other) .NET Core app. (`dotnet new`)
2. Add any postcompile script to project.json.
3. Run `dotnet build` twice.
## Expected  behavior
1. First run of `dotnet build` builds the project.
2. Second run of `dotnet build` says `Project {project name} was previously compiled. Skipping compilation.
## Actual behavior

Both runs of `dotnet build` rebuild the whole project.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
## Notes

Let's say that the post-compile script does not do any change which would affect the incremental build. Wouldn't it be better to allow adding a flag to the script telling that the script is "incremental build friendly"?

**Comment by blackdwarf** [comment] 2016-10-31 20:59
This was by design in Preview 2 I believe. https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build has all of the details.

In the MSBuild world, this is not applicable since MSBuild has a different way of providing post-target extensibility. With that, I will close this issue.

**Closed by blackdwarf** 2016-10-31 20:59 UTC
Labels: msbuild-notapplicable
