### ISSUE TITLE
dotnet commands fail with just core installed

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#2879] opened 2016-05-04 20:39 UTC
## Steps to reproduce
1. Download the .NET Core Installer (x64 and x86)
2. Run ```dotnet --help``` (as specified by the output of running just ```dotnet```)

## Expected  behavior
A help text is displayed

## Actual behavior
"Did not find a suitable dotnet SDK at '<install path>'. Install dotnet SDK from <github path>"

## Environment data
`dotnet --info` output:

Same error as above

**Comment by brthor** [comment] 2016-05-04 20:41
#2697

**Comment by sokket** [comment] 2016-05-04 20:42
dotnet info doesn't work either :(

**Comment by sokket** [comment] 2016-05-04 20:42
ie. dotnet --version or dotnet --info

**Comment by brthor** [comment] 2016-05-04 20:49
I don't know how these things can work without an SDK installed.

**Comment by sokket** [comment] 2016-05-04 20:57
The help text should describe what the ```dotnet``` command is and how to run it (like ```man dotnet```) would. Once the SDK is installed, that can be expanded to include the SDK help.

Version should always be available to output the version of whatever is installed; if no SDK is installed the it should show the runner version. Once the SDK is installed, show the runner and SDK version. Same with info

**Comment by brthor** [comment] 2016-05-04 22:27
I think having --help also output `dotnet app.dll` like it does if you type `dotnet` alone is reasonable, but for `--version`, it's current beauty is that you get a string you can easily pipe to other commands, or easily use in a build.

Perhaps a `--host-version` would satisfy the need while preserving this scenario?

**Comment by sokket** [comment] 2016-05-04 22:28
> for --version, it's current beauty is that you get a string you can easily pipe to other commands, or easily use in a build.

What use cases do we see in this area? If anything, this seems like a developer-centric scenario that would not be involved if just core were installed...

**Comment by brthor** [comment] 2016-05-04 22:56
> What use cases do we see in this area? If anything, this seems like a developer-centric scenario that would not be involved if just core were installed...

There was some conversation here https://github.com/dotnet/cli/issues/1607#issuecomment-189930471

I see the use cases as primarily being around automation when verification needs to be done, or decisions made based on the current version of the cli being used.

With just core installed, the scenarios are likely different which is why I think a different option makes sense.

**Comment by piotrpMSFT** [comment] 2016-05-04 23:23
This is a duplicate of #2697

**Closed by piotrpMSFT** 2016-05-04 23:23 UTC
