### ISSUE TITLE
dotnet restore on debian 9 dotnet sdk 2.0.3 fails to download any packages

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8203] opened 2017-12-11 03:34 UTC
@dvogel commented on [Sun Dec 10 2017](https://github.com/dotnet/core/issues/1146)

I downloaded the [minimal install of debian 9](https://gemmei.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-9.3.0-amd64-netinst.iso) and installed it using defaults.

Then I followed [the directions for installing dotnet sdk](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x). I ran:

```
export PATH=$PATH:$HOME/dotnet
mkdir test0
cd test0
dotnet new mvc
dotnet restore
```

The restore command printed out:

```
  Restoring packages for /home/dvogel/test0/test0.csproj...
  Restore completed in 39.83 ms for /home/dvogel/test0/test0.csproj.
  Restore completed in 60.96 ms for /home/dvogel/test0/test0.csproj.
```

That output looked successful at first but a subsequent `dotnet build` will fail due to missing packages. The `$HOME/.nuget/packages` directory is empty.

Here's an OVA exported from virtualbox: http://acfa3ee7d7a82c5cc99c3982b6dab6ab.s3.amazonaws.com/dotnet-devel1.ova (password is "microsoft" for both the root and dvogel accounts).

The `PATH` change seems suspect because nothing is actually installed into `$HOME/dotnet` and the `dotnet` commands don't seem to create any files in that directory.

**Comment by livarcocc** [comment] 2017-12-11 18:20
I could not repro this. I just downloaded your VM, fired it up in VirtualBox and ran the commands above, including dotnet run and it all work for me. No errors.

Also, notice that your `$HOME/.nuget/packages` is empty because you are only using the packages from a regular mvc project, that are all present in your fallback folder. NuGet does not copy packages from the fallback folder to the nuget cache.

**Comment by dvogel** [comment] 2017-12-12 03:22
You're right. The issue doesn't repro in that VM. My debugging process led be to misinterpret the results I saw.

I had this issue on a different install of debian on my main development machine. In order to find an extreme counter-point to that experience, I decided to test it in a CentOS 7 VM. In that VM the `dotnet restore` command placed many files in `~/.nuget/packages` and `dotnet run` worked. In order to bisect the problem, I decided to repeat the same steps in a new debian 9 VM. When I didn't see the packages installed into the same place I skipped the `dotnet run` step and assumed there was a problem. Evidently, I misunderstood the baseline expectations and inappropriately assumed that the sdk packages would work the same across different linux distros.

I tried to use a fresh VM because my initial attempts to use the sdk ran into this issue with package references. Perhaps you could help me determine a better debugging path to determine why I see the following when trying to add a package reference to my csproj file?

```
dvogel@lukahn:~/devel> mkdir test0
dvogel@lukahn:~/devel> cd test0
dvogel@lukahn:~/devel/test0> dotnet new mvc
Getting ready...
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/template-3pn for details.

Processing post-creation actions...
Running 'dotnet restore' on /home/dvogel/devel/test0/test0.csproj...
  Restoring packages for /home/dvogel/devel/test0/test0.csproj...
  Restoring packages for /home/dvogel/devel/test0/test0.csproj...
  Restore completed in 1.33 sec for /home/dvogel/devel/test0/test0.csproj.
  Generating MSBuild file /home/dvogel/devel/test0/obj/test0.csproj.nuget.g.props.
  Generating MSBuild file /home/dvogel/devel/test0/obj/test0.csproj.nuget.g.targets.
  Restore completed in 1.43 sec for /home/dvogel/devel/test0/test0.csproj.


Restore succeeded.

dvogel@lukahn:~/devel/test0> dotnet restore
  Restore completed in 50.04 ms for /home/dvogel/devel/test0/test0.csproj.
  Restore completed in 28.62 ms for /home/dvogel/devel/test0/test0.csproj.
dvogel@lukahn:~/devel/test0> dotnet --version
2.0.3
dvogel@lukahn:~/devel/test0> dotnet run
Hosting environment: Production
Content root path: /home/dvogel/devel/test0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
```

So the base app runs OK. Now I add this to my csproj file:

```
  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="2.4.4" />
    <PackageReference Include="MongoDB.Driver" Version="2.4.4" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.4.4" />
  </ItemGroup>
```

And then the `dotnet restore` command seems to succeed but the subsequent `dotnet run` command fails, despite the build actually succeeding:

```
dvogel@lukahn:~/devel/test0> dotnet restore
  Restoring packages for /home/dvogel/devel/test0/test0.csproj...
  Restore completed in 46.11 ms for /home/dvogel/devel/test0/test0.csproj.
dvogel@lukahn:~/devel/test0> dotnet run

The build failed. Please fix the build errors and run again.
dvogel@lukahn:~/devel/test0> dotnet msbuild
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  test0 -> /home/dvogel/devel/test0/bin/Debug/netcoreapp2.0/test0.dll
dvogel@lukahn:~/devel/test0> dotnet run

The build failed. Please fix the build errors and run again.
```

**Comment by livarcocc** [comment] 2017-12-12 03:27
Have you tried just running a `dotnet build` to try to get logs for the build failure. If possible, run dotnet build /bl, which will generate a binlog file that you can then share with us. Please, be careful if you have passwords or things like that in your build, because they will appear on the binlog.

**Comment by dvogel** [comment] 2017-12-12 04:01
When I try `dotnet build` I get no errors but the `dotnet run` command continues to error out unless I use the `--no-restore` option:

```
dvogel@lukahn:~/devel/test0> dotnet clean
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

dvogel@lukahn:~/devel/test0> dotnet build
dvogel@lukahn:~/devel/test0> dotnet run

The build failed. Please fix the build errors and run again.
dvogel@lukahn:~/devel/test0> dotnet build --no-incremental
dvogel@lukahn:~/devel/test0> dotnet run

The build failed. Please fix the build errors and run again.
dvogel@lukahn:~/devel/test0> dotnet build --no-incremental --no-restore
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  test0 -> /home/dvogel/devel/test0/bin/Debug/netcoreapp2.0/test0.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.71
dvogel@lukahn:~/devel/test0> dotnet run

The build failed. Please fix the build errors and run again.
dvogel@lukahn:~/devel/test0> dotnet run --no-restore
Hosting environment: Production
Content root path: /home/dvogel/devel/test0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
```

Here's the zip file that was created by `dotnet build /bl`: [msbuild.ProjectImports.zip](https://github.com/dotnet/cli/files/1550207/msbuild.ProjectImports.zip)

**Comment by livarcocc** [comment] 2017-12-12 04:28
I can't open the zip you put above.

Is this still just a regular MVC app or are you doing any customization to it? I can't find a way to repro it. Also, bl should generate a `.binlog` file. Did you rename it? I also tried renaming your zip and opening it in the structured view logger, but it also failed.

**Comment by dvogel** [comment] 2017-12-12 05:16
It looks like I mistakenly chose `msbuild.ProjectImports.zip` instead of `msbuild.binlog` because github's file extension support excludes that file type. I'm not really sure what the `msbuild.ProjectImports.zip` file is but here's a different zip file containing the `msbuild.binlog` file: 
[issue8203.zip](https://github.com/dotnet/cli/files/1550345/issue8203.zip)

The project is just a regular MVC app with the MongoDB drivers added as `PackageReference`s in the csproj file.

**Comment by dvogel** [comment] 2017-12-13 05:35
I used `strace -e trace=file` on the restore command and got this output: 
[restore-trace.txt](https://github.com/dotnet/cli/files/1554213/restore-trace.txt)

The suspicious part, toward the end:

```
26325 open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 92
26325 open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 92
26325 lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
26325 lstat("/usr/share", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
26325 lstat("/usr/share/dotnet", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
26325 lstat("/usr/share/dotnet/shared", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
26325 lstat("/usr/share/dotnet/shared/Microsoft.NETCore.App", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
26325 lstat("/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.3", {st_mode=S_IFDIR|0755, st_size=16384, ...}) = 0
26325 stat("/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.3/System.Security.Cryptography.X509Certificates.dll", {st_mode=S_IFREG|0644, st_size=435712, ...}) = 0
26325 open("/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.3/System.Security.Cryptography.X509Certificates.dll", O_RDONLY) = 92
26325 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
26325 unlink("/tmp/clr-debug-pipe-26294-9671987-in") = 0
26325 unlink("/tmp/clr-debug-pipe-26294-9671987-out") = 0
26325 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
26302 <... open resumed>)               = ?
26316 +++ killed by SIGSEGV +++
26315 +++ killed by SIGSEGV +++
26313 +++ killed by SIGSEGV +++
26312 +++ killed by SIGSEGV +++
26311 +++ killed by SIGSEGV +++
26310 +++ killed by SIGSEGV +++
26309 +++ killed by SIGSEGV +++
26308 +++ killed by SIGSEGV +++
26307 +++ killed by SIGSEGV +++
26305 +++ killed by SIGSEGV +++
26304 +++ killed by SIGSEGV +++
26303 +++ killed by SIGSEGV +++
26302 +++ killed by SIGSEGV +++
26301 +++ killed by SIGSEGV +++
26300 +++ killed by SIGSEGV +++
26299 +++ killed by SIGSEGV +++
26325 +++ killed by SIGSEGV +++
26294 +++ killed by SIGSEGV +++
```

**Comment by dvogel** [comment] 2017-12-13 05:55
After running `sudo apt remove libssl1.0.0` it now works. Looks to be [a duplicate of another issue](https://github.com/dotnet/corefx/issues/8951).

**Comment by livarcocc** [comment] 2017-12-13 17:33
I see. That makes some sense. I am going to close this one then, if that's ok with you and I would suggest commenting on that one in case you have something to add there.

Let me know if something comes up and you want me to re-activate this one.

**Closed by livarcocc** 2017-12-13 17:33 UTC
