### ISSUE TITLE
ProjectLoadContext fails to resolve strong-named assemblies

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#955] opened 2016-01-22 00:09 UTC
This is noted in [a comment in the code](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel.Loader/LoaderProjectContextExtensions.cs#L23-L24), but I just hit it so I thought I'd file an issue.

In my particular example, the loader is trying to resolve the assembly `EntityFramework.Sqlite, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`, but the `ProjectLoadContext` fails to resolve it because the lookup dictionary contains `EntityFramework.Sqlite, Culture=neutral, PublicKeyToken=null` for the key to that assembly.

**Comment by davidfowl** [comment] 2016-01-29 03:33
@NTaylorMullen added a custom assembly name comparer. Strong names shouldn't matter since there's only every one version at runtime.

**Comment by NTaylorMullen** [comment] 2016-01-29 03:59
I'll reference this issue as part of that PR.

**Comment by NTaylorMullen** [comment] 2016-01-29 04:07
duplicate of #1084

**Closed by NTaylorMullen** 2016-01-29 04:07 UTC
Labels: duplicate
