### ISSUE TITLE
Cannot run x86 project from x64 dotnet

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#3684] opened 2016-06-23 17:35 UTC
## Steps to reproduce
1. Create a project and set buildOptions->platform to x86
2. Try to `dotnet run` that project from an x64 version of dotnet
3. Observe the error `Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'BasicWebSite.dll'. An attempt was made to load a program with an incorrect format.`

## Expected  behavior
The project should launch.

## Actual behavior
The project crashes.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003098)

Product Information:
 Version:            1.0.0-preview2-003098
 Commit SHA-1 hash:  b2dadfa81c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

@pakrym said that one solution to this was to install both the x64 and x86 version of dotnet and use different ones depending on weather you want x86 or not, which seems like a pretty poor experience.

**Comment by blackdwarf** [comment] 2016-07-27 17:29
I believe this is by design. @schellap @gkhanna79 can you confirm?

**Comment by gkhanna79** [comment] 2016-07-27 17:33
Please see http://stackoverflow.com/questions/2265023/load-32bit-dll-library-in-64bit-application

**Comment by blackdwarf** [comment] 2016-07-28 06:27
According to the link @gkhanna79 shared, it seems that this behavior is by design. Closing.

**Closed by blackdwarf** 2016-07-28 06:27 UTC
