### ISSUE TITLE
dotnet tool install failed when home directory has non ASCII character with MSBuild Error

### ISSUE THREAD

**Issue by pherbel** [dotnet/cli#9413] opened 2018-06-04 09:39 UTC
## Steps to reproduce
dotnet tool install --global dotnet-outdated
Or
dotnet tool install --global dotnet-outdated --version 1.0.0

## Expected  behavior

dotnet tool is installed successfully

## Actual behavior
MSBUILD : error MSB1006: Property is not valid.

The tool package could not be restored.
Tool 'dotnet-outdated' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment] 2018-06-04 16:49
I can install this tool successfully.

@wli3 @peterhuene can you help investigate this issue?

**Comment by wli3** [comment] 2018-06-04 21:30
@pherbel I cannot repo it on my machine. Could I have a more detailed log from you? Could you run the following command and post it here or send to my email wul at microsoft.com

`dotnet -d tool install --global dotnet-outdated -v:n`

**Comment by pherbel** [comment] 2018-06-05 08:01
After this command I can see that the problem could be the accented character encoding in my name.

This is the cmd output:
```
Telemetry is: Enabled
Running C:\Program Files\dotnet\dotnet.exe restore C:\Users\PéterHerbel\AppData\Local\Temp\coflus1r.o2w\restore.csproj --runtime any -property:BaseIntermediateOutputPath=C:\Users\P&#233;terHerbel\.dotnet\tools\.store\.stage\aqfgbue5.kex -verbosity:n
Process ID: 5188
Telemetry is: Enabled
MSBUILD : error MSB1006: Property is not valid.
Switch: terHerbel\.dotnet\tools\.store\.stage\aqfgbue5.kex

For switch syntax, type "MSBuild /help"

The tool package could not be restored.
Tool 'dotnet-outdated' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

Thanks your help.

**Comment by peterhuene** [comment] 2018-06-05 17:12
Hi @pherbel.  That does indeed look like the case.

@wli3 It looks like this line is the problem: https://github.com/dotnet/cli/blob/release/2.1.3xx/src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs#L47.  My guess is that this moved from where it was written to the project file and we forgot to remove the XML escaping.  This should simply be quoted instead.

**Comment by wli3** [comment] 2018-06-05 17:23
@peterhuene no, that is a regression (this is the original from). But that might be fixed in 2.1.4xx already due to it is moved to temp project. Pass to msbuild via command line **should** be escaped by xml encoding. Problem is else where

**Comment by peterhuene** [comment] 2018-06-05 17:26
Ah, couldn't remember which direction it moved from (from or to the project file).  It absolutely should not be XML encoded on the command line.  Semicolon is the property delimiter, which is why MSBuild is not parsing it correctly.  If we're to pass it on the command line, it should be double quoted so that MSBuild will treat it as a literal value.

**Comment by wli3** [comment] 2018-06-05 17:37
I need to dig more. The xml encode is to fix the problem when `BaseIntermediateOutputPath` has a space in the middle. I looks fishy but I need to verify.

**Comment by wli3** [comment] 2018-06-05 17:40
Repo similar by `dotnet -d tool install --tool-path "C:/work/åä" dotnetsay`

**Comment by wli3** [comment] 2018-06-05 17:56
@peterhuene you are right xml encode is the problem. The bug means installation will fail when home directory has non ascii character. As well as --tool-path.

I need to 
1. find a workaround
2. verify 2.1.4xx is fixed
3. see if this bug need to do servicing @livarcocc

**Comment by peterhuene** [comment] 2018-06-05 17:58
I amended my workaround above to something that should work, albeit it is a bit clunky.

**Comment by wli3** [comment] 2018-06-05 17:59
Thanks, I think I cannot find a better workaround

**Comment by wli3** [comment] 2018-06-05 21:19
Talked to Livar, we need to try to target servicing. Let me add repo test and port the 2.1.4xx to see the change.

**Comment by wli3** [comment] 2018-06-05 21:22
@peterhuene do you think pass it via just double quote on command line or put it in temp project is better? In temp project we has several directory path passed by it already. I think that is more reliable. While command has different layer's command line parser in the middle. Simply just quote it might not be enough

**Comment by peterhuene** [comment] 2018-06-05 21:42
Passing it in via the project file would be best, I think.

**Comment by pherbel** [comment] 2018-06-06 07:36
Thanks @peterhuene 
Your workaround works for me.

Thanks guys the help and I hope you can fix it in the next patch release.

**Comment by wli3** [comment] 2018-06-06 23:19
`dotnet restore -p:BaseIntermediateOutputPath="å, ä"` will fail. but `msbuild /restore -p:BaseIntermediateOutputPath="å, ä"` is fine. I think there is CLI parser's problem as well. I may need to change to pass by temp project to avoid all this

**Comment by wli3** [comment] 2018-06-06 23:29
@rainersigwald do you know if there is a "loss-less" way to pass property to msbuild? Should I pass it by command line or pass it by xml (temp project).

I can create a folder like that in Windows 
![image](https://user-images.githubusercontent.com/6993335/41070268-b636dda4-69a6-11e8-9f29-b5ba97b86aef.png)

**Comment by peterhuene** [comment] 2018-06-07 00:56
Try `dotnet restore -p:BaseIntermediateOutputPath=\"å, ä\"` so that MSBuild receives the quotes.

If you use quotes for the property argument to `DotNetCommandFactory.Create` then our command line handling code should also escape them properly, allowing MSBuild to parse it correctly.

Let me know if that works.

**Comment by wli3** [comment] 2018-06-07 02:35
https://github.com/dotnet/cli/blob/release/2.1.3xx/src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs#L52

It is that today. I passed using quotes like https://github.com/wli3/cli/blob/fix-xmlescape/src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs#L47 it won't pass the repro test

**Comment by rainersigwald** [comment] 2018-06-07 03:00
Comma and semicolon are both special in command-line property specifications. To set a property that contains one of them, MSBuild needs to see quotes after the `propertyname=` part. On full framework, we rely on Windows behavior and parse the entire command line as a string ourselves, explaining why it works with `msbuild.exe` but not `dotnet`

For *nix I'd consider single-quoting the whole property argument `'-p:BaseIntermediateOutputPath="å, ä"'` so shell escaping doesn't eat it. For Windows I'm less sure of how .NET Core parses that into the argument array. It looks weird: I could get it to work with `dotnet msbuild test.proj "/p:P=\"å, ä\""` (but single quotes don't work).

But we shouldn't need entity escaping for non-ANSI characters. I think URL encoding it might be the right way to go--or we could maybe do so just for comma and semicolon.

**Comment by wli3** [comment] 2018-06-11 23:23
both Uri.EscapeDataString, and Uri.EscapeUriString cannot get the test pass.
EscapeUriString won't escape ";". And EscapeDataString get folder "ab á¹°ÌºÌºÌo;.ç°ä¸­ãã ,Ã¥Ã¤" created in the end.

**Comment by wli3** [comment] 2018-06-12 00:42
I realize there is not good way to make mix ascii char + control char to work, even when I put it in xml. 

However, I realize -o cannot work with the crazy string `dotnet build -o C:\Users\wul\Downloads\testescape\ab Ṱ̺̺̕o;.田中さん ,å` as well. However, considering there is no compile about it. I will choose the same code as dotnet build -o . It can handle non ascii, but not control char.

**Comment by wli3** [comment] 2018-06-12 21:14
Log more error case
Pass  `"ab ; semi . period , comma"` will error with 

Error Message:
 Microsoft.DotNet.ToolPackage.ToolPackageException : The tool package could not be restored.c:\work\cli\bin\2\win-x64\dotnet\sdk\2.1.301-preview-008906\15.0\Microsoft.Common.props(61,35): error MSB4115: The "HasTrailingSlash" function only accepts a scalar value, but its argument "$(MSBuildProjectExtensionsPath)" evaluates to "c:\work\cli\bin\2\win-x64\test\artifacts\ab ; semi . period , comma\f2oiwymg.yel\.stage\ctxxm3e0.fia" which is **not a scalar value**. [C:\Users\wul\AppData\Local\Temp\pkogc221.jgz\giwtguht.0ng.csproj]

; is not escaped

Pass `\"ab ; semi . period , comma\"` will error with

error MSB1006: Property is not valid.Switch:  semi . period For switch syntax, type "MSBuild /help"

comma kills it...

**Closed** 2018-08-03 19:11 UTC
Labels: tool
