### ISSUE TITLE
Null reference exception during compilation.

### ISSUE THREAD

**Issue by sirentek** [dotnet/cli#2807] opened 2016-05-02 11:19 UTC
## Steps to reproduce
Change directory to parent (or any directory) from terminal, execute "dotnet run".

## Expected  behavior
project.json not found or similar warning.

## Actual behavior
object reference not set to an instance of an object message appears and it doesn't compile.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment] 2016-05-02 20:07
This is a fit n' finish type scenario as if there is no project.json in your directory, I think it's fairly unsurprising that things don't work. 

bumping this out to rtm.

**Comment by sirentek** [comment] 2016-05-02 21:04
Ok, I am closing this for now then.

**Comment by mellinoe** [comment] 2016-05-02 23:59
I think we want to keep this issue open, at least for tracking since we eventually need to fix it.

I just hit this as well. To clarify, the scenario is "run `dotnet run` from any directory that doesn't have a project.json in it"

**Comment by brthor** [comment] 2016-05-03 00:01
Thanks for reopening @mellinoe 

@sirentek I didn't mean to imply that it wasn't important, just that this won't be able to make it into RC2 given the time and resources available 😄

**Comment by sirentek** [comment] 2016-05-05 11:43
@brthor :+1:

**Comment by Sridhar-MS** [comment] 2016-05-11 00:47
Closing it as a duplicate of https://github.com/dotnet/cli/issues/2965

**Closed by Sridhar-MS** 2016-05-11 00:47 UTC
Labels: duplicate, fit-n-finish
