### ISSUE TITLE
terminating `dotnet run` doesn't terminate child

### ISSUE THREAD

**Issue by mickaelistria** [dotnet/cli#7426] opened 2017-08-12 10:18 UTC
## Steps to reproduce

```
[Terminal 1]
$ dotnet new razor
$ dotnet run
Hosting environment: Production
Content root path: /home/mistria/runtime-EclipseApplication/tst
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
[Terminal 2]
$ ps aux | grep dotnet
mistria  24040  2.2  0.7 3296988 88604 pts/0   SLl+ 12:07   0:01 dotnet run
mistria  24143  1.1  0.5 21300684 71156 pts/0  SLl+ 12:07   0:00 dotnet exec /home/mistria/runtime-EclipseApplication/tst/bin/Debug/netcoreapp2.0/tst.dll
$ kill -15 24040 #SIGTERM on host
$ ps aux | grep dotnet
mistria  24143  1.1  0.5 21300684 71156 pts/0  SLl+ 12:07   0:00 dotnet exec /home/mistria/runtime-EclipseApplication/tst/bin/Debug/netcoreapp2.0/tst.dll
# child still there like a zombie
```

## Expected  behavior

Child process terminated

## Actual behavior

Child process is still there
This can be confusing for IDEs (like Eclipse IDE) which bind the "stop" button and other UI actions to the Terminate signal. In such case, the developer trying `dotnet run` from the IDE will face issues because of the zombi-ish processes

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.1-servicing-006924)

Product Information:
 Version:            2.0.1-servicing-006924
 Commit SHA-1 hash:  1ed6be56ca

Runtime Environment:
 OS Name:     fedora
 OS Version:  26
 OS Platform: Linux
 RID:         fedora.26-x64
 Base Path:   /home/mistria/apps/dotnet-2/sdk/2.0.1-servicing-006924/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by jonaskello** [comment] 2017-09-02 11:06
Maybe using [dumb-init](https://github.com/Yelp/dumb-init) could help with this?

**Comment by omajid** [comment] 2017-09-08 17:51
> Maybe using dumb-init could help with this?

Maybe for containers. This is just using a plain `dotnet` command on a normal OS.

**Comment by psmolkin** [comment] 2017-09-21 09:52
Same problem with `dotnet test`. While terminating main process  (eg timeout) all his childs stays and locks assemblies, takes up processors time etc.

**Comment by alexsandro-xpt** [comment] 2017-09-24 18:12
I'm tool, same problem.

**Comment by FanrayMedia** [comment] 2017-10-16 16:55
I'm struggling with this too, the only way to stop it is to restart my machine.

**Comment by livarcocc** [comment] 2017-11-23 06:45
on @mickaelistria's case, about dotnet razor, I don't think it is dotnet's job to terminate those processes. The CTRL+C message there is coming from asp.net itself and when you CTRL+C it is asp.net's responsibility to terminate any extra processes that it may have initiated when it gets terminated.

Also, I couldn't repro this right now when I tried.

As for dotnet test, @psmolkin would you happen to have a repro for it?

**Comment by psmolkin** [comment] 2017-11-23 07:35
@livarcocc I tried to reproduce it but as I think the problem was fixed. Now I have installed CLI version 2.0.3

**Comment by psmolkin** [comment] 2017-11-29 12:08
@livarcocc 
## Steps to reproduce:
* Create a project:
  * Ap.Ms.Test.csproj :
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
  </ItemGroup>

</Project>
```
  * UnitTest1.cs :
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace Ap.Ms.Test
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            while (true)
            {
                Assert.IsTrue(true);
            }
            Assert.IsTrue(true);
        }
    }
}
```
* run `dotnet test`
![image](https://user-images.githubusercontent.com/24776038/33373980-48f2358e-d515-11e7-9636-522272434054.png)
* run `procexp.exe` and find parent donet.exe
![image](https://user-images.githubusercontent.com/24776038/33374091-b46f2114-d515-11e7-894a-de2b75e46b8d.png)
* then kill parnet process (9864)
![image](https://user-images.githubusercontent.com/24776038/33374223-4c418928-d516-11e7-9f6a-39ffd4b5807c.png)

## Expected
* All child processes are stopped

## Actually
* Childs continue running and lock assemblies

**Comment by etinin** [comment] 2018-04-17 06:09
getting this with 2.1.0-preview2-26406-04, both on Linux and on Windows

**Comment by gjaryczewski** [comment] 2018-06-27 12:02
I have observed a similar beahoviour of not working Ctrl+C BUT only when using a hosted services. I used sample codes from https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples/, in time and scope variant, and this is repeatable and permanent behavior.

**Comment by gjaryczewski** [comment] 2018-06-27 12:12
And one observation more: when I press any key after Ctrl+C, than I see an error message, and the process is terminating. It applies to SDK 2.1.

**Comment by brthor** [comment] 2018-07-02 23:07
I hit this in @coherenceApi on linux recently.

I managed to work around it by using the method [here](https://azimi.me/2014/12/31/kill-child_process-node-js.html).

This is a `nodejs` specific solution, to kill the entire process group.

```javascript
var spawn = require('child_process').spawn;

var child = spawn('my-command', {detached: true});

process.kill(-child.pid);
```

IMO the cli should be terminating the entire process group @livarcocc , but there should be an api for that in corefx (no idea if there is one).

FYI @etinin @gjaryczewski @mickaelistria

**Comment by tskarman** [comment] 2018-07-23 16:14
I think it is reasonable to expect `dotnet run`/`dotnet watch`/etc to reliably shutdown its child processes.

Still:
* I've found that one indirect cause of this, is the inability of the actual running code to come to a halt.
In my case a third-party library was holding up the shutdown of the application. It looks like it manages its own thread pool and deadlocked in its clean-up logic.
Not sure why that could hold up the shutdown (the threads look to be background threads). It might be that something deadlocks the "exit" thread. 
* This happens for both console applications and Kestrel-type (i.e. `WebHost`) applications
* Make sure to dispose of your `ServiceProvider` instances
* And be careful around disposal of your injected instances. It looks like the `ServiceProvider` implementations are not guaranteed to run `.Dispose()` on objects implementing `IDisposable` (e.g. on types registered as singletons).

**Comment by martinbliss** [comment] 2018-10-23 16:36
Looks like this thread is still active but stale. It was originally open almost a year ago: do we have consensus that this is real and should be addressed somewhere and slotted for a future release?

**Comment by cole21771** [comment] 2018-10-29 13:42
I'd really like this to be fixed. I'm just getting into the dotnet platform and would really like to take advantage of the speed of linux over windows for our server, but in testing we keep running into this issue which putting us down a bit. 

## How I encountered the issue
### System
Ubuntu 18.04.1 LTS 1 cpu, 1gb ram (AWS EC2 free tier)

### Install dotnet-sdk-2.1
```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1
```

### Install Node.js
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

### Create Angular / .net project
`dotnet new angular -o angular-test-project`

### Start project
```
export ASPNETCORE_Environment=Development
dotnet build
dotnet 
```

Wait for the angular build to finish. After this, kill the project with Ctrl + C. Sometimes it successfully says `Application is shutting down` and then shuts down. Other times, it will just say `Application is shutting down` and then sit there forever meaning something is blocking in some way most likely (my best guess). If you Ctrl + C again after this, the memory will remain being used by this zombie process. You can see in the screenshot below I had to press Ctrl + C twice before it went back to bash.
![image](https://user-images.githubusercontent.com/14830521/47653381-6e5c1900-db56-11e8-9479-61d791e88e53.png)

If you look in htop, it seems to be a bunch of ng processes which is strange. So maybe it is just something as simple as the ng serve is stuck open. You can see htop below.
![image](https://user-images.githubusercontent.com/14830521/47653207-f988df00-db55-11e8-8b71-2b43a15def2d.png)

@omajid @livarcocc Hopefully this helps move this along in some way.

**Comment by livarcocc** [comment] 2018-10-29 15:11
If closing a asp.net app is not terminating the process, I believe this is an issue that should be investigated by the ASP.NET team. Please, file a new issue on aspnet/home.

Another possibility is that dotnet has three long running processes that stay around to help with inner loop performance: roslyn, msbuild and razor. You can terminate these processes by running `dotnet build-server shutdown`.

**Comment by sillyousu** [comment] 2018-10-29 15:29
@livarcocc 

quoting from asp.net issue tracker:

https://github.com/aspnet/Hosting/issues/960#issuecomment-321057786
>dotnet doesn't forward Ctrl-C to child processes, so we won't be able to fix this in Hosting itself. Closing per the triage team's decision.

**Comment by livarcocc** [comment] 2018-10-29 15:34
@jkotas do you know if this is a limitation of the host or the process APIs?

**Comment by sillyousu** [comment] 2018-10-29 16:19
I have a few questions:

1.0) what does `dotnet run` do when it receive a `control+c` on Linux?
1.1) Does it handle the SIGINT?
1.2) How does it terminate child process? Forwarding `SIGINT` to child process?
1.3)  Does it keep waiting until child process is fully terminated?

2.0) what does `dotnet run` do when it receive a `control+c` on Win?
2.1) Does it receive any king of event/signal?
2.2) Does it terminate child process somehow? How to?
2.3)  Does it keep waiting until child process is fully terminated?

@livarcocc

**Comment by sillyousu** [comment] 2018-10-29 16:54
@livarcocc 

>@jkotas do you know if this is a limitation of the host or the process APIs?

https://github.com/dotnet/corefx/issues/5339#issuecomment-171643049 @stephentoub  saied:

> \>is there an API to send Ctrl+C to a spawned process? 
>Not exposed in the framework. On Unix it can be achieved via a P/Invoke to kill, and on Windows via a P/Invoke to GenerateConsoleCtrlEvent I believe. There's an open issue requesting such a feature be added (#1838), but there's also no reason it needs to be in corefx itself and could easily be done as a 3rd-party library.

It seems like `dotnet run` does not handle SIGINT now.

**Comment by jkotas** [comment] 2018-10-29 17:03
> @jkotas do you know if this is a limitation of the host or the process APIs?

@livarcocc Killing parent process does not automatically kill child processes. It is standard behavior of process APIs in both .NET and elsewhere. For example, if you launch a child process using C/C++ [system](http://www.cplusplus.com/reference/cstdlib/system/) function, killing the parent process won't automatically kill the child process either.

You can do a best effort to kill child process in `dotnet run`. It will fix the common cases, but the bad cases where things go wrong will still leave orphaned processes behind.

A more reliable solution is to kill the process group in the first place. E.g. replace "kill -15 24040 #SIGTERM on host" in the repro above with "kill -15 -- -24040 #SIGTERM on host process group".

**Comment by Tomamais** [comment] 2018-11-30 05:11
Well, I've found a temporary solution to the problem. Again, it's TEMPORARY. It's wonky, but it works.

https://github.com/Tomamais/StartAndStopDotNetCoreApp

**Comment by peterhuene** [comment] 2019-01-04 22:21
I will be making a fix that (at best) partially addresses this issue.

On POSIX systems, `dotnet run` will now handle the `SIGTERM` signal (via `AppDomain.CurrentDomain.ProcessExit`) and forward it to the child process (via libc `kill`).  However, because there is currently no way in corefx to spawn a process in a new process group (see dotnet/corefx#17412), we cannot terminate the process tree starting at the child of `dotnet run`.  To do this in `dotnet` would require system calls between `fork` and `execve` and would require a lot of additional complexity that really belongs in corefx.  As a workaround, send `SIGTERM` to the process group of `dotnet run` using `kill -15 -- -$DOTNET_RUN_PID` instead.

On Windows, there is no way to send a graceful termination signal to a console process.  The closest analogous signal to `SIGTERM` would be [CTRL+CLOSE](https://docs.microsoft.com/en-us/windows/console/ctrl-close-signal), but that is only sent if you gracefully terminate the console itself and not `dotnet`.  Like the workaround above, I would recommend using `taskkill /t /pid %DOTNET_RUN_PID%` to terminate `dotnet` and its tree.

**Comment by herebebeasties** [comment] 2019-01-04 23:44
You can pick up CTRL+C on Windows (C# Console.CancelKeyPress, implemented behind the scenes via kernel32.dll's SetConsoleCtrlHandler on Windows).
Well-behaved consoles should send that, I'd have thought?

**Comment by peterhuene** [comment] 2019-01-04 23:57
Hi @herebebeasties.  Consistent `SIGINT`/Ctrl-C handling from `dotnet run` is a different issue and one I am also producing a fix for.  `SIGINT` is sent to the foreground process group in POSIX and, similarly, to all processes attached to the current console on Windows. Thus, the children see the signal and can respond to it appropriately; for example, this is why Ctrl-C of a ASP.NET Core application running from `dotnet run` prints the shutdown message).  The problem there is that the default handling of `SIGINT` from `dotnet run` causes a different exit status to the parent then it would have if the parent had spawned the child program directly.  It also causes an immediate return back to the waiting parent and the child program may still be writing to the terminal when handling the signal, resulting in inconsistent and undesirable output in an interactive shell session.

This issue is about sending `SIGTERM` or using task manager / taskkill to terminate the `dotnet run` process and having it reliably clean up the child processes.  Unlike `SIGINT`, sending `SIGTERM` is usually sent with the `kill` command and that, unless you manually tell it to send to a process group, will only go to the individual process specified.

`SIGINT` is sent automatically to all the processes in the group, so the children of `dotnet run` see it today.  The problem there is that `dotnet run` itself responds to the signal with the default handler, resulting in different exit status /

**Comment by Code-DJ** [comment] 2019-01-18 16:49
We are seeing similar behavior with Task Scheduler in Windows.

Scheduled run.bat which runs "dotnet foo.dll" in Task Scheduler with "Stop the task if it runs longer than: X".

Past the time, we see "Task stopping due to timeout reached" in the History of the task but "dotnet foo.dll" continues to run and can be seen in Task Manager Details tab.

Is this the same problem as this issue? Thanks!

**Comment by cchamberlain** [comment] 2019-02-01 03:45
@Code-DJ Task Scheduler has been unreliable for ages. I've had better luck creating services that do this programatically.

**Closed** 2019-02-08 02:09 UTC
