### ISSUE TITLE
dotnet build -v crashes

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5565] opened 2017-02-02 23:10 UTC
## Steps to reproduce
run "dotnet build -v"

Looks like a regression from https://github.com/dotnet/cli/pull/5206 

## Expected  behavior
Message saying it isn't a valid option

## Actual behavior

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.ParseOption(Boolean isLongOption, CommandLineApplication command, String[] args, Int32& index, CommandOption& option)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

Tried on the RC3 build.

**Comment by livarcocc** [comment] 2017-02-03 00:01
@jonsequitur Seems around the area that you have been playing with. Want to take a look?

**Comment by krwq** [comment] 2017-02-03 00:08
This is a duplicate of https://github.com/dotnet/cli/issues/5295

**Closed by krwq** 2017-02-03 00:08 UTC
