### ISSUE TITLE
NuGet Cache expansion even when I could already build in VS

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5420] opened 2017-01-21 05:17 UTC
## Steps to reproduce
Install VS 2017 RC3
Build your project in VS
Open the Developer command prompt for VS 2017.
dotnet build your project.

## Expected  behavior
It just builds

## Actual behavior
It spends about a minute extracting a nuget cache that wasn't necessary to build in VS. I didn't look at all the details but I worry the cache is duplicated and at the very least is taking up a minute that it shouldn't need to do.

## Environment data
`dotnet --info` output:
Whatever is in VS 2017 RC3 :)

**Comment by piotrpMSFT** [comment] 2017-01-21 08:18
Dupe of https://github.com/dotnet/cli/issues/5325. Sadly, this is blocked on https://github.com/NuGet/Home/issues/4343. Of course, we could do something hacky in the CLI, but we agreed with NuGet team to not inspect the packages directory directly after all of the troubles experienced with the PackagePath.ToLower() change some months back.

**Closed by piotrpMSFT** 2017-01-21 08:18 UTC

**Comment by Petermarcu** [comment] 2017-01-21 20:50
Ok :)
