### ISSUE TITLE
dotnet-migrate System.IO.IOException: Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5299] opened 2017-01-13 00:25 UTC
## Steps to reproduce
When migrating https://github.com/aspnet/EventNotification
following exception occurs:
```
Unhandled Exception: System.IO.IOException: Cannot create a file when that file already exists
   at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Microsoft.DotNet.ProjectJsonMigration.MigrationBackupPlan.PerformBackup()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.BackupProjects(MigrationReport migrationReport)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.MoveProjectJsonArtifactsToBackup(MigrationReport migrationReport)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass28_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Expected  behavior
migration successful or valid reason for failure

## Actual behavior
unhandled exception

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4)

Product Information:
 Version:            1.0.0-rc4
 Commit SHA-1 hash:  cf8fd7dd34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004506
```

cc: @livarcocc @piotrpMSFT - I'm pretty sure I saw similar issue before but can't find it, please let me know if you know which one is it

Unfortunatelly for some reason despite having pdbs it won't show me the line numbers - variable names would be nice too - I'll dig into that a little more to get something actionable

**Comment by livarcocc** [comment] 2017-01-13 00:32
Likely the same as this: https://github.com/dotnet/cli/issues/5224.

**Comment by krwq** [comment] 2017-01-13 00:33
@DustinCampbell could you confirm if this is the same and close this? If you pull the latest and cherry pick https://github.com/dotnet/cli/pull/5298/commits you should see the same stack trace in the other issue if this is the same.

**Comment by DustinCampbell** [comment] 2017-01-13 00:54
will do. It does look similar

**Comment by DustinCampbell** [comment] 2017-01-13 09:48
Yup. This is a dupe of #5224

**Closed by DustinCampbell** 2017-01-13 09:48 UTC
Labels: duplicate, migration
