### ISSUE TITLE
Cannot build an app after adding a framework due to an System.ArgumentException

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1775] opened 2016-03-09 19:01 UTC
I added the `dnx451` to my app like this: https://github.com/aspnet/cli-samples/compare/072933574a50240be5be9630bb912a891ae90724...pawelka/bug 
and now the application won't build due to: `An item with the same key has already been added. Key: System.Collections Unspecified`

## Steps to reproduce
clone https://github.com/aspnet/cli-samples repo
switch to pawelka/bug branch
dotnet restore 
dotnet run/build

## Expected  behavior
The application runs or gives an actionable error message

## Actual behavior
```
PS C:\Source\cli-samples\HelloMvc> dotnet run -f dnx451
An item with the same key has already been added. Key: System.Collections Unspecified
```
## Environment data
`dotnet --version` output:

```
PS C:\Source\cli-samples\HelloMvc> dotnet --version
.NET Command Line Tools (1.0.0-beta-001672)

Product Information:
 Version:     1.0.0-beta-001672
 Commit Sha:  12dd8d6112

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by Scarat** [comment] 2016-03-10 15:59
@moozzyk  I was experiencing this too and here is my [comment](https://github.com/dotnet/cli/issues/1098#issuecomment-186941106) on another issue. I was able to solve it by moving NETStandard.Library to dnxcore50 dependencies. Probably not the best solution but it could be a hint for where to start looking.

**Comment by moozzyk** [comment] 2016-03-10 17:23
@Scarat - I tried moving NETStandard.Library to dnxcore50 dependencies but it did not help too much:

```
Compiling HelloMvc for DNX,Version=v4.5.1
Can not add property System.Collections to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
```

**Comment by livarcocc** [comment] 2016-03-29 00:18
@moozzyk I don't see the repro branch available anymore. I saw a tool-test branch but not a bug branch. I am closing this issue for now. If you can still repro, could you give us me some details on how you are reproing it?

**Closed by livarcocc** 2016-03-29 00:18 UTC
Labels: blocking-partner

**Comment by moozzyk** [comment] 2016-03-29 00:23
The branch is still there https://github.com/aspnet/cli-samples/tree/pawelka/bug. I don't know if it reproes though.
