### ISSUE TITLE
Deploy pdb symbols for dependant assemblies from nuget packages (via PackageReference)

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#7690] opened 2017-09-21 17:32 UTC
## Steps to reproduce
`dotnet publish` in a project with nuget dependencies

## Expected  behavior
A folder with "published" version contains not only *.dll from nuget dependencies but *.pdb as well (they do exist in packages of cause).

## Actual behavior
No pdb's deployed for package dependencies. Symbols do deployed for application itself (current project and its dependent projects) but not for nuget dependencies. While symbols exist in packages.

## 
Actually it should not make deference what dependencies I'm publishing (project or package). If symbols exist they should be published as well.

Project1 
  -- ProjectReference --> Project2 - symbols deployed
  -- PackageReference --> Project3 - no symbols deployed

Also it would make sense to control symbols publishing for nuget dependencies via an option (for example `--include-symbols` or/and `--exclude-symbols`).

**Comment by wli3** [comment] 2017-09-25 21:28
might share the same root cause with
https://github.com/dotnet/sdk/issues/1458

**Comment by livarcocc** [comment] 2018-02-13 21:02
@nguerrera can you check if this is the same as dotnet/sdk#1458? If so, let's close this one. if not, what is different?

**Comment by nguerrera** [comment] 2018-02-13 21:04
Yes. Duplicate of dotnet/sdk#1458. I will add  a note there to verify publish behavior.

**Closed by nguerrera** 2018-02-13 21:04 UTC
Labels: bug
