### ISSUE TITLE
Install scripts likely need to be updated to support acquiring the asp.net shared framework.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8334] opened 2018-01-05 17:42 UTC
People are going to want to do something similar to this but get ASP.NET + the Core Shared runtime.

```
wget https://dot.net/v1/dotnet-install.sh
chmod 700 dotnet-install.sh
./dotnet-install.sh --channel 2.0 --install-dir "$netdir" --shared-runtime --no-path
```

**Comment by livarcocc** [comment] 2018-01-05 21:46
Duplicate of https://github.com/dotnet/cli/issues/8252

**Closed by livarcocc** 2018-01-05 21:46 UTC
