### ISSUE TITLE
"exec: \"dotnet\": executable file not found in $PATH" when running in Kubernetes cluster

### ISSUE THREAD

**Issue by iniside** [dotnet/cli#9443] opened 2018-06-08 17:31 UTC
## Steps to reproduce
It's going to be little hard, but basically:
1. I have create Kubernetes cluster on Google Cloud.
2. I have this test project: https://github.com/iniside/uSpark
It is composed from Client console app, frontend (Google Endpoints) and test backend app. 
There are two YAML files. grpc-greeter.yml will deploy public service + frontend app.
grpc-greeter-backend.yml will deploy service and simple backend app.

Now deployment of frontend is without issue. It works and it responds to test requests. 
When I try to run kubectl -f grpc-greeter-backend.yml it deploys but pod cannot run application and errors on:
"exec: \"dotnet\": executable file not found in $PATH"

I thought that my docker image is broken. But tested it locally and it works. Also images for both services are created exactly the same way.

## Expected  behavior

Command inside kubernetes cluster pod will run successfuly. 

## Actual behavior

Command is not found. 

## Environment data

Cannot provide. Cannot connect to remote pod, since it is terminating, just after failing to run command.

**Comment by peterhuene** [comment] 2018-06-08 17:41
Hi @iniside.  Thanks for reporting this.  I'll see if I can reproduce this locally with docker and minikube (or AKS).

**Comment by peterhuene** [comment] 2018-06-20 22:38
Hi @iniside.  I too have no problems from a container I build myself (I don't have access to your GCR to pull the same one).

I'll give it a shot on minikube and let you know if I can reproduce.  Thanks!

**Comment by peterhuene** [comment] 2018-06-20 22:47
Hi @iniside.  I also can't reproduce it on minikube:

```
$ kubectl logs grpc-greeter-backend-66c55cfd6d-7jc2n
Hello World!
Gretter server is linstening on port 29000
Press any key to stop server
```

For now I'm going to close this issue as unable to reproduce.  My suggestion would be to rebuild the image in question, but I'm sure you've already done that.  Please reopen this issue if you are still able to reproduce and have any suggestions for how I can do the same.

Thanks again for reporting this to us!

**Closed** 2018-06-20 22:47 UTC
