### ISSUE TITLE
2.1-preview1 dotnet restore fails with "Microsoft.NET.Sdk.Web/Sdk/Sdk.props could not be loaded."

### ISSUE THREAD

**Issue by pheuter** [dotnet/cli#8711] opened 2018-03-01 17:05 UTC
## Steps to reproduce

Inside of an ASP.NET Core 2.1 Preview 1 project run the following command:

```sh
$ docker run --rm -v $(pwd):/root/code microsoft/aspnetcore-build:2.1.300-preview1 dotnet restore
```

## Expected  behavior

This should spin up a `microsoft/aspnetcore-build` container with the latest `2.1-preview` .NET SDK and restore the current project's dependencies.

## Actual behavior

Container is created and an error is immediately thrown upon attempting to restore:

```
/root/code/App.csproj : error MSB4024: The imported project file "/usr/share/dotnet/sdk/2.1.300-preview1-008174/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.props" could not be loaded. Data at the root level is invalid. Line 1, position 1.
```

**It should be noted** that this same `$ dotnet restore` command works just fine on my local mac running the same version of the SDK. It is crucial for the same command to work inside Docker as we use containers for local dev as well as production deployments.

## Environment data

**Running:**

```sh
docker run --rm -v $(pwd):/root/code microsoft/aspnetcore-build:2.1.300-preview1 dotnet --info
```

**Produces:**

```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview1-008174/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by pheuter** [comment] 2018-03-01 17:24
### Update

It appears to be specific to the Debian Stretch container because the command completes successfully when I switch to the Ubuntu Bionic container.

**Comment by pheuter** [comment] 2018-03-01 18:24
## Update 2

Bizarre, now I'm starting to get a new error whenever I restore in the Bionic container:

```sh
$ docker run --rm -v $(pwd):/root/code microsoft/aspnetcore-build:2.1.300-preview1-bionic dotnet restore
```

```
  Restoring packages for /root/code/CareSwitch.csproj...
  Restoring packages for /root/code/CareSwitch.csproj...
  Restore completed in 309.91 ms for /root/code/CareSwitch.csproj.

/usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(114,5): error : An error occurred while retrieving package metadata for 'runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0' from source '/usr/share/dotnet/sdk/NuGetFallbackFolder'. [/root/code/CareSwitch.csproj]
/usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(114,5): error :   Data at the root level is invalid. Line 1, position 1. [/root/code/CareSwitch.csproj]
```

I'm not sure what caused this error to come up, I was able to restore just fine inside of Bionic earlier and I haven't made any dependency or project file changes. Is it possible that something funky is happening with the NuGet repository?

**Comment by peterhuene** [comment] 2018-03-01 18:43
Hi @pheuter:

Thanks for reporting this.  I'm unable to reproduce the problem locally:

```
$ docker run --rm -v $(pwd):/root/code --rm microsoft/aspnetcore-build:2.1.300-preview1 dotnet new web -o /root/code
The template "ASP.NET Core Empty" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/template-3pn for details.

Processing post-creation actions...
Running 'dotnet restore' on /root/code/code.csproj...
  Restoring packages for /root/code/code.csproj...
  Generating MSBuild file /root/code/obj/code.csproj.nuget.g.props.
  Generating MSBuild file /root/code/obj/code.csproj.nuget.g.targets.
  Restore completed in 1.01 sec for /root/code/code.csproj.

Restore succeeded.

$ docker run --rm -v $(pwd):/root/code --rm microsoft/aspnetcore-build:2.1.300-preview1 dotnet restore
  Restore completed in 73.03 ms for /root/code/code.csproj.

$ docker run --rm microsoft/aspnetcore-build:2.1.300-preview1 dotnet --info 
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview1-008174/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

$ docker --version
Docker version 18.02.0-ce, build fc4de447b5
```

I'm able to "see" the container's Web SDK install, so I'm not sure why the restore would be failing for you.

**Comment by pheuter** [comment] 2018-03-01 18:50
@peterhuene huh, that's weird. so i figured it must have something to do with Docker itself and now that command works once I reset my Docker virtual disk image.

**Comment by livarcocc** [comment] 2018-03-01 18:52
Ok. Given that this seems like a transient docker issue, I am closing this issue.

If some new development happens though, feel free to comment and we can re-activate.

**Closed by livarcocc** 2018-03-01 18:52 UTC
