### ISSUE TITLE
Installation from Daily servicing builds do not load dlls correctly

### ISSUE THREAD

**Issue by cbranch-bhg** [dotnet/cli#7996] opened 2017-11-10 22:46 UTC
This is an issue appeared when trying to resolve an issue in 2.0.0 related to C# finalizers causing issues with Test Coverage software. https://github.com/dotnet/coreclr/issues/14763
The problem was apparently fixed in 2.0.4-servicing-25831-01 release
However after installing the servicing release found here:
https://github.com/dotnet/core-setup/blob/release/2.0.0/README.md#officially-released-builds

Running dotnet would still be using version 2.0.0
There was a work around by renaming or copying the directory:
\dotnet\shared\Microsoft.NETCore.App\2.0.4-servicing-25831-01
to
\dotnet\shared\Microsoft.NETCore.App\2.0.4

Unfortunately this issue was very difficult to track down as the dotnet --info output did indicate that it was using 2.0.4. I have not tried to examine the behavior on non-Windows platforms.

## Steps to reproduce
Clean system.
Install SDK 2.0.0
Install 2.0.4-servicing...
Run dotnet program.
Attach debugger or other tool and look at what dlls are loaded

## Expected  behavior
Expected to see dlls loaded from \dotnet\shared\Microsoft.NETCore.App\2.0.4-servicing-25831-01 directory

## Actual behavior
See dlls loaded from  \dotnet\shared\Microsoft.NETCore.App\2.0.0

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4-servicing-25831-01
  Build    : 92cbf99da7b056cbf5145f6c91a0c7800ae7f834

**Comment by livarcocc** [comment] 2017-11-11 06:10
This is by design.

The host will not automatically roll you forward on a pre-release version, as this would make the servicing rules problematic.

We have an issue at core-setup tracking adding a flag or parameter that would enable this, but I don't see this behavior being enabled by default.

Closing this issue in favor of the core-setup one: https://github.com/dotnet/core-setup/issues/3227.

**Closed by livarcocc** 2017-11-11 06:10 UTC
