### ISSUE TITLE
dotnet restore will load NuGet.config but no other casing

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2324] opened 2016-04-06 22:51 UTC
## Steps to reproduce
On Linux
dotnet new
mv NuGet.config Nuget.config
dotnet restore

## Expected  behavior
Nuget.config will be loaded and used as the nuget feeds

My recommendation is since case sensitive file systems are supported, we should use the defacto default of all lower case to ensure it is loaded in all necessary cases.

## Actual behavior
Nuget.config is ignored since it is not the right casing

(Note: all lowercase nuget.config is found and loaded, just not other casings: eg Nuget.config)

## Environment data
`dotnet --info` output:
1.0.0-beta-002254

**Comment by akoeplinger** [comment] 2016-04-06 22:59
Related: https://github.com/NuGet/Home/issues/1427

I'd obviously :+1: to an all lowercase `nuget.config` by default.

**Comment by blackdwarf** [comment] 2016-07-21 15:22
Closing this as a duplicate of NuGet/Home#1427. The `dotnet restore` command uses NuGet to restore packages, so anything that NuGet does it does.

**Closed by blackdwarf** 2016-07-21 15:22 UTC
