### ISSUE TITLE
SDK 3.0.100-preview-010006 should merge runtime 3.0.0-preview-27219-3 rather than 3.0.0-preview-27218-01

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#10551] opened 2019-01-07 07:19 UTC
## Steps to reproduce
1. Install SDK 3.0.100-preview-010006 with .tar.gz installer and .deb/.rpm installer

## Expected  behavior
1. SDK installer works fine and CLI(dotnet new/restore/run) work fine too.

## Actual behavior
1. For .tar.gz installer, after decompressed, it shows that runtime **3.0.0-preview-27218-01** installed. But dotnet run for web app failed as runtime **3.0.0-preview-27219-3** was not found.
![image](https://user-images.githubusercontent.com/1578239/50754106-74295580-128f-11e9-812f-8374379ba5fc.png)

2. For .deb/.rpm installer, when try to install sdk, it prompt runtime **3.0.0-preview-27218-01** is needed
  ![image](https://user-images.githubusercontent.com/1578239/50753841-53accb80-128e-11e9-8c43-92bc9f44f52c.png)
But, after installed runtime **3.0.0-preview-27218-01** , it prompt runtime **3.0.0-preview-27219-3** is needed.
  ![image](https://user-images.githubusercontent.com/1578239/50753884-8a82e180-128e-11e9-9321-09170ebfa7d3.png)

## Environment data
`dotnet --info` output:
1) Donet --info on CentOS75 with .tar.gz installer
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010006
 Commit:    166534d9bf

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /home/nicole/mytest/sdk/3.0.100-preview-010006/

Host (useful for support):
  Version: 3.0.0-preview-27218-01
  Commit:  d40b87f29d

.NET Core SDKs installed:
  3.0.100-preview-010006 [/home/nicole/mytest/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-18630-0234 [/home/nicole/mytest/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27218-01 [/home/nicole/mytest/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

2) dotnet --info on Ubuntu16.04 with .deb installer
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010006
 Commit:    166534d9bf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview-010006/

Host (useful for support):
  Version: 3.0.0-preview-27219-3
  Commit:  6cd1c28ae3

.NET Core SDKs installed:
  3.0.100-preview-010006 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-18630-0234 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27219-3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment] 2019-01-07 20:38
Closing as a duplicate of https://github.com/dotnet/cli/issues/10551.

**Closed by livarcocc** 2019-01-07 20:38 UTC
