### ISSUE TITLE
Impersonation works when building for dnxcore50 doesn't with net46

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/cli#1365] opened 2016-02-11 18:07 UTC
_(not sure if this was the best place to file this, but I'll start here)_

I have discovered a bug when using dotnet cli to compile and run code using impersonation targeting two different frameworks:

``` csharp
using System;
using System.Linq;
using System.Security.Principal;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApplication {
    public class Program {
        public static void Main(string[] args) {
            Console.WriteLine("Hello World!");
            
            Action action = () => { WriteLine($"I am {WindowsIdentity.GetCurrent().Name}!"); };
            
            WindowsIdentity.RunImpersonated(WindowsIdentity.GetCurrent() as WindowsIdentity.AccessToken, action);
        }
    }
}
```

What happens:

``` batch
C:\tmp>dotnet build
Compiling tmp for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.5898345

Compiling tmp for .NETFramework,Version=v4.6

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.5765484

C:\tmp>dotnet run
Project tmp (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Hello World!
I am NTDEV\garretts!

C:\tmp>bin\Debug\net46\tmp.exe
Hello World!

Unhandled Exception: System.Security.SecurityException: Unable to retrieve security descriptor for this frame.
   at System.Security.Principal.WindowsIdentity.SafeImpersonate(SafeAccessTokenHandle userToken, WindowsIdentity wi, StackCrawlMark& stackMark)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at ConsoleApplication.Program.Main(String[] args) in C:\tmp\Program.cs:line 21

C:\tmp>
```

Works with DNXCORE50 but not NET46 .

I've created a git repo you can pull the whole thing from: https://github.com/fearthecowboy/RunImpersonatedBug

**Comment by fearthecowboy** [comment] 2016-02-11 19:58
FWIW; I recompiled something similar with C# 5, and it crashed the same.

It also turns out that the sample on the MSDN page (https://msdn.microsoft.com/en-us/library/dn906220(v=vs.110).aspx) fails in the same way. 

Which really means this is more likely a .NET 4.6 framework bug. (*$)$& !!!!

**Comment by terrajobst** [comment] 2016-02-12 02:33
It [looks like](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/security/principal/windowsidentity.cs#L735) this behavior is by design.

For now, you should be able to work this around by not using `GetCurrent()` inside of a delegate. Not ideal, but probably doable.

**Comment by terrajobst** [comment] 2016-02-12 02:33
@bartonjs

**Comment by fearthecowboy** [comment] 2016-02-12 17:15
>> It looks like this behavior is by design.

Except, the MSDN sample https://msdn.microsoft.com/en-us/library/dn906220(v=vs.110).aspx fails too. 

>> For now, you should be able to work this around by not using GetCurrent() inside of a delegate. Not ideal, but probably doable.

The delegate isn't the problem; I just made the repro as small as possible.

**Comment by davidfowl** [comment] 2016-02-16 03:58
@fearthecowboy Better to move this issue to corefx?

**Comment by bartonjs** [comment] 2016-02-16 18:47
@fearthecowboy I found this issue in the (internal) bug database for the full framework... (I can't decide if that's a smile (yay for internal finds) or a frown (boo for the bug existing)... emotive failure on my part!).

But, the good news is that we already know about it, so it should be fixed in a future version.

So, unfortunately, impersonation requires dual-compiling for full framework and CoreFX right now...  full-framework has to do the older Impersonate() form, and the CoreFX version has to use RunImpersonated().

Since there isn't an issue in dotnet/cli (or, even, really in dotnet/corefx) I'm going to go ahead and close this issue (because as far as I know that's the right thing to do).

**Closed by bartonjs** 2016-02-16 18:47 UTC
