### ISSUE TITLE
dotnet restore does not populate targets in project.assets.json on RHEL7.2

### ISSUE THREAD

**Issue by adiaaida** [dotnet/cli#8819] opened 2018-03-16 16:18 UTC
## Steps to reproduce
./dotnet-install.sh -sharedruntime -runtimeid linux-x64 -installdir .dotnet -channel master -architecture x64
source ./dotnet-install.sh -installdir .dotnet -channel master -architecture x64
dotnet new console

This happens on RHEL7.2

## Expected  behavior
Creates console hello world app, successfully restores, and is able to successfully build.

## Actual behavior

Build returns:
```
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(15,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(16,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,71): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,99): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,122): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(10,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(11,61): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(12,59): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(13,68): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(14,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(15,53): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(16,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(2,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(7,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(8,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
Program.cs(5,11): error CS0518: Predefined type 'System.Object' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(7,26): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(7,16): error CS0518: Predefined type 'System.Void' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
```

When inspected, project.assets.json has no content under 'targets':
```
{
  "version": 3,
  "targets": {
    ".NETCoreApp,Version=v2.0": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    ".NETCoreApp,Version=v2.0": [
      "Microsoft.NETCore.App >= 2.0.0"
    ]
  }
```

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008368
 Commit:    3f09a889d9

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/sdk/2.1.300-preview2-008368/

Host (useful for support):
  Version: 2.1.0-preview2-26314-02
  Commit:  8ac5f4fa22

.NET Core SDKs installed:
  2.1.300-preview2-008368 [/mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30331 [/mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30331 [/mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26313-01 [/mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26314-02 [/mnt/resource/j/w/Private/dotnet_optimization/master/CLRx64LINmasPGO/output/CLRx64LINmas/PGO/cli/x64/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by adiaaida** [comment] 2018-03-16 16:20
Note: This is blocking us from generating new PGO packages for Linux.

**Comment by livarcocc** [comment] 2018-03-16 17:11
If you are using a nightly build of the CLI from the master branch, this is expected. This happens because the version of the `Microsoft.NetCore.App` package being referenced by the default by the CLI is not available in nuget.org.

You need to add a nuget feed to your list of feeds to be able to download these packages. For instance, you can use this feed: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

On a separate note, why are you using a nightly build to generate this PGO packages for linux? Why not use a released version?

**Comment by adiaaida** [comment] 2018-03-16 17:17
We use the nightly build because we privately build, out of master, coreclr.dll, clrjit.dll and System.Private.Corelib.dll and drop them into the dotnet shared directory, because we are updating the coreclr master branch's pgo packages. Anytime SPC is updated, we need the corresponding changes in the framework, so we can't just use a released version (for example, any time Span is updated).

How would I add the nuget feed? In a file, in an environment variable? This didn't use to be a problem. It just started failing within the last 2 weeks or so.

**Comment by livarcocc** [comment] 2018-03-16 17:53
I am very surprise this was not happening before. This has always been the case. You need to add a NuGet.Config file somewhere above the folder structure from where the dotnet restore command is being run.

Note that this is the very reason why most of our repos all have a NuGet.Config with additional feeds that contain nightly packages.

**Comment by adiaaida** [comment] 2018-03-16 20:12
Ok, it looks like the reason we didn't see this before was because we DO write a Nuget.config file, but not for our Dotnet_FirstTimeXP scenario. I wonder if dotnet new console used to not perform a restore, but now it does. Thank you for your help.

**Comment by livarcocc** [comment] 2018-03-16 20:17
`dotnet new` has had implicit restore 2.0. I am glad the issue is now understood.

Going to close this issue. If there is still anything going on, just comment and we can re-activate.

**Comment by adiaaida** [comment] 2018-03-16 21:20
@livarcocc Ok, so there's a new issue now. When I try to build my hello world app generated by dotnet new console, I get this error:

```
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(15,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(16,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,71): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,99): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,122): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(10,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(11,61): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(12,59): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(13,68): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(14,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(15,53): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(16,55): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(2,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(7,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
obj/Debug/netcoreapp2.1/hello.AssemblyInfo.cs(8,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/home/dotnet-bot/hello/hello.csproj]
Program.cs(5,11): error CS0518: Predefined type 'System.Object' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(7,26): error CS0518: Predefined type 'System.String' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
Program.cs(7,16): error CS0518: Predefined type 'System.Void' is not defined or imported [/home/dotnet-bot/hello/hello.csproj]
```

Is there something else we are missing? This is without replacing coreclr/System.Private.CoreLib.

**Comment by livarcocc** [comment] 2018-03-16 22:13
cc @rohit21agrawal and @nkolev92 since this seems to be happening because the project.assets.json file is not being generated properly. It is missing dependencies in the targets portion of the file.

```
{
  "version": 3,
  "targets": {
    ".NETCoreApp,Version=v2.0": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    ".NETCoreApp,Version=v2.0": [
      "Microsoft.NETCore.App >= 2.0.0"
    ]
  }
```

**Comment by adiaaida** [comment] 2018-03-19 20:58
@nkolev92 I went to repro this again this morning to get a full log, but it looks like one of the changes fixed my issue and it is no longer reproing. I'm going to close the issue now.

**Comment by adiaaida** [comment] 2018-03-19 23:03
I spoke too soon. This is working on Ubuntu, but still fails on RHEL7.2.  I have attached a restore log.
[restore.log](https://github.com/dotnet/cli/files/1827275/restore.log)

**Comment by nkolev92** [comment] 2018-03-19 23:14
@adiaaida 
Does the assets file look like the above posted one? 

Logs seem to suggested the package and its dependencies were resolved correctly.

**Comment by adiaaida** [comment] 2018-03-19 23:21
Yes, the projects.assets.json is missing anything under "targets"

**Comment by nkolev92** [comment] 2018-03-19 23:23
//cc
@zhili1208 Can you please check if you can repro this?

**Comment by adiaaida** [comment] 2018-03-21 18:18
I have confirmed that if I restore on an Ubuntu machine and copy the targets section from the project.assets.json file generated there to the RHEL machine, I can build, but this is not really a good solution. Is it possible there were changes recently (in the last 16 days or so) that could have broken RHEL?

**Comment by nkolev92** [comment] 2018-03-21 18:27
@adiaaida 
There's been no changes affecting this that I am aware of. 

Is it consistently reproducible on RHEL?
//cc @rrelyea @zhili1208

**Comment by adiaaida** [comment] 2018-03-21 21:04
@nkolev92 yes, it is consistently reproduceable.

**Comment by zhili1208** [comment] 2018-03-23 21:38
No, it's not similar, I mentioned the lock file is incorrect in memory. This asset file is incorrect on disk.

**Comment by cdmihai** [comment] 2018-05-02 21:41
This issue might also be causing the msbuild repo to fail building on RHEL7.2. Here's a sample failure in our CI:https://ci2.dot.net/job/Microsoft_msbuild/job/vs15.7_sourcebuild/job/innerloop_RHEL7.2_CoreCLR_SourceBuild_prtest/11/ (you can also get a binlog from here)

The `*.csproj.nuget.g.targets` files do not contain the imports for `NETStandard.Library.targets`, which leads to the `Reference` item being empty and compilation missing with missing references.

 `project.assets.json` files for projects targetting netstandard:
```
     1  {
     2    "version": 3,
     3    "targets": {
     4      ".NETStandard,Version=v2.0": {}
     5    },
     6    "libraries": {},
     7    "projectFileDependencyGroups": {
     8      ".NETStandard,Version=v2.0": [
     9        "NETStandard.Library >= 2.0.1",
    10        "Nerdbank.GitVersioning >= 2.1.23",
...
```

Projects targeting netcoreapp on the other hand do have targets:
```
1  {
     2    "version": 3,
     3    "targets": {
     4      ".NETCoreApp,Version=v2.0": {
     5        "Microsoft.Build/15.1.0-dev": {
     6          "type": "project",
     7          "framework": ".NETStandard,Version=v2.0",
     8          "dependencies": {
     9            "Microsoft.Build.Framework": "15.1.0-dev",
    10            "System.Collections.Immutable": "1.3.1",
    11            "System.Diagnostics.TraceSource": "4.0.0",
    12            "System.IO.Compression": "4.3.0",
    13            "System.Reflection.Metadata": "1.3.0",
    14            "System.Reflection.TypeExtensions": "4.1.0",
    15            "System.Runtime.InteropServices.RuntimeInformation": "4.3.0",
    16            "System.Runtime.Loader": "4.0.0",
    17            "System.Text.Encoding.CodePages": "4.0.1",
    18            "System.Threading.Tasks.Dataflow": "4.6.0"
    19          },
    20          "compile": {
    21            "bin/placeholder/Microsoft.Build.dll": {}
    22          },
    23          "runtime": {
    24            "bin/placeholder/Microsoft.Build.dll": {}
    25          }
    26        },
    27        "Microsoft.Build.Framework/15.1.0-dev": {
    28          "type": "project",
    29          "framework": ".NETStandard,Version=v2.0",
    30          "dependencies": {
    31            "System.Runtime.Serialization.Primitives": "4.1.1",
    32            "System.Threading.Thread": "4.0.0"
    33          },
    34          "compile": {
    35            "bin/placeholder/Microsoft.Build.Framework.dll": {}
    36          },
    37          "runtime": {
    38            "bin/placeholder/Microsoft.Build.Framework.dll": {}
    39          }
    40        },

```

To repro, build the msbuild repo on RHEL7.2 with `./build.sh`

**Comment by cdmihai** [comment] 2018-05-02 21:57
@jainaashish says it is most likely cause by this problem https://github.com/dotnet/corefx/issues/29095

**Comment by livarcocc** [comment] 2018-10-11 01:34
@adiaaida is this still happening for you? with the latest .NET Core SDK 2.1.403?

**Comment by adiaaida** [comment] 2018-10-11 16:36
I have not noticed it recently, no.

**Comment by livarcocc** [comment] 2018-10-11 18:33
Ok, closing this issue for now then.

**Closed by livarcocc** 2018-10-11 18:33 UTC
