### ISSUE TITLE
Daily build links are broken

### ISSUE THREAD

**Issue by cocowalla** [dotnet/cli#9508] opened 2018-06-17 19:28 UTC
The daily build links in this repo's main readme.md file are all broken.

For example, [Windows x64 installer](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe) gives `ResourceNotFound`.

**Comment by dasMulli** [comment] 2018-06-17 20:39
Looks like other repos are affected as well, also tried core-setup and a few different branches.

**Comment by vRITHNER** [comment] 2018-06-18 07:36
```
<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:21fbb97e-b01e-0057-6bd7-064146000000 Time:2018-06-18T07:36:01.6087826Z
</Message>
</Error>
```

**Comment by eerhardt** [comment] 2018-06-18 14:23
It seems to be something wrong with the Azure Storage account.  I can't download any URL from the account:

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.exe
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-rhel.6-x64.tar.gz
etc

All return 404. But I am able to see all of the files and I can download them using Azure Storage Explorer (since I have permission to the account)

The checksum links appear to work: https://dotnetclichecksums.blob.core.windows.net/dotnet/Runtime/master/dotnet-host-latest-rhel.7-x64.rpm.sha512.

**Comment by akoeplinger** [comment] 2018-06-18 14:57
See https://github.com/dotnet/corefx/issues/30479 and https://github.com/dotnet/core-eng/issues/3700

**Comment by eerhardt** [comment] 2018-06-18 15:00
Closing as the issue is now resolved.  Thanks for reporting it.

From @dagood:

>This should be fixed for now.
The dotnet container in the dotnetcli account was marked private, rather than allowing public blob access. I changed it back and I’m looking into why this might have changed in the first place.

**Closed by eerhardt** 2018-06-18 15:00 UTC
