### ISSUE TITLE
Multi targetting with conditional references copies only one version to each output

### ISSUE THREAD

**Issue by Roemer** [dotnet/cli#7015] opened 2017-06-28 07:49 UTC
## Steps to reproduce
Create a multitargetting project which includes different versions of an assembly based on the target.
For example:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net40;net45</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net35'">
      <HintPath>..\libs\Interop\3.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net40' Or '$(TargetFramework)'=='net45'">
      <HintPath>..\libs\Interop\4.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

</Project>
```

## Expected  behavior
In each output folder is the correct referenced file.
In this example, net35 should have the 3.5 version of the Interop.UIAutomationClient.dll and net40 and net45 should have the 4.5 version of the Interop.UIAutomationClient.dll.

## Actual behavior
All three outputs contain the 3.5 version of the Interop.UIAutomationClient.dll.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.3.9600
>  OS Platform: Windows
>  RID:         win81-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## Other notes
I had to remove net35 in order to build with ```dotnet msbuild``` (and not with Visual Studio 2017) and just modified the file that the 3.5 version of the dll is referenced in net40 and the 4.5 version in net45 with the same result: both contain the 3.5 version.

**Comment by Roemer** [comment] 2017-06-28 13:45
The only workaround I could think of for now would be to not copy the dlls to the output and using post-build hooks to manually copy the files.

**Comment by livarcocc** [comment] 2017-06-28 17:29
@nguerrera can you take a look? @Roemer have you tried moving the condition into the ItemGroup and then having the 3.5 and 4.0/4.5 references inside these conditioned ItemGroups instead?

**Comment by nguerrera** [comment] 2017-06-28 19:57
@livarcocc The conditions are fine where they are.

@Roemer I cannot reproduce this issue. Here is my attempt showing the correct behavior:  [ct.zip](https://github.com/dotnet/cli/files/1110040/ct.zip)

Is it possible that an error has caused the 3.5 Interop.UIAutomationClient.dll to land in the .\libs\Interop\4.5\ folder? I ask because I had actually build authoring issue that caused this in my first attempt to make the output directories line up directly to what your reference hint paths expect.

**Comment by Roemer** [comment] 2017-06-28 20:52
Hmm I must say I cannot reproduce it with the pc I am currently. Will double-check tomorrow with the one where I found the issue.

**Comment by Roemer** [comment] 2017-06-29 09:32
The problem is actually something different. I Want to add those library files to the generated nuget assemblies as well. For that I use:
```xml
<ItemGroup Label="Additional nuget files">
  <None Include="..\libs\Interop\3.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net35" />
  <None Include="..\libs\Interop\4.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net40;lib\net45" />
</ItemGroup>
```
If I add the ```Condition```there as well it works.

To make it easier now, I thought about having a Interop\net35, Interop\net40 and Interop\net45 folder (where net40 and net45 have the same content) and just using the ```$(TargetFramework)``` variable in the path like:
```csharp
<ItemGroup Label="References">
  <Reference Include="Interop.UIAutomationClient">
    <HintPath>..\libs\Interop\$(TargetFramework)\Interop.UIAutomationClient.dll</HintPath>
    <EmbedInteropTypes>false</EmbedInteropTypes>
    <SpecificVersion>false</SpecificVersion>
  </Reference>
</ItemGroup>

<ItemGroup Label="Additional nuget files">
  <None Include="..\libs\Interop\$(TargetFramework)\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\$(TargetFramework)" />
</ItemGroup>
```
This works for the ```Reference Include``` but for some reason not for the ```None Include``` :(

**Comment by Roemer** [comment] 2017-06-29 10:31
I actually can't make this work with the csproj. Maybe someone of you got an idea. Otherwise I probably need to go back to nuspec or cake for building the nuget packages.

**Comment by Roemer** [comment] 2017-06-29 10:41
The problem seems to be that the files to include into the nuget are "added" to the project (with `None`) and according to [this](https://blogs.msdn.microsoft.com/manishagarwal/2005/09/28/resolving-file-references-in-team-build-part-2/) it first searches in the project files. That is probably why it is using the "wrong" file in the output.
The correct solution should be to find a way to add files to the nuget package without adding them to the project.

**Comment by livarcocc** [comment] 2017-07-01 00:00
Given that this is an issue with pack, I am moving this to NuGet. If there this turns out to require changes in the CLI/SDK, please, just move it back. We will be glad to help.

**Comment by livarcocc** [comment] 2017-07-01 00:00
This issue was moved to NuGet/Home#5520

**Closed by livarcocc** 2017-07-01 00:00 UTC
