### ISSUE TITLE
PCL bait and switch trick not working any more

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#3155] opened 2016-05-20 12:34 UTC
## Steps to reproduce

1. Create a `net45` app with `dotnet new`
2. Create a PCL library (profile 259)
3. Add `FubarCoder.RestSharp.Portable.HttpClient` (4.0.0-alpha1-5) as dependency to the `net45` project
4. Add `FubarCoder.RestSharp.Portable.Core` (4.0.0-alpha1-5) as dependency to the PCL project
5. Reference the PCL library from the `net45` project (project reference)
6. Use the PCL library from the `net45`
7. Start the `net45` application

Example application: [TestRestSharpPortable.zip](https://github.com/dotnet/cli/files/274534/TestRestSharpPortable.zip)

You have to run the example application with `dotnet run -f net45`.

## Expected  behavior

The application should run without problem.

## Actual behavior

The application crashes, because it doesn't find the `IWebProxy Proxy` property, because the `FubarCoder.RestSharp.Portable.Core` assembly in the output directory of the `net45` project is the one for the PCL, but it should've been the assembly for the `net45` framework.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by piotrpMSFT** [comment] 2016-05-26 07:38
dupe of #3211

**Closed by piotrpMSFT** 2016-05-26 07:38 UTC

**Comment by fubar-coder** [comment] 2016-05-26 07:44
Shouldn't the bait-and-switch trick work even when there's no `ref` assembly specified? At least until `ref` assembly packaging is supported?

**Comment by fubar-coder** [comment] 2016-07-06 14:15
@piotrpMSFT This issue is related to #3211, but it isn't a dupe (IMHO), see my comment above.
