### ISSUE TITLE
`dotnet publish` publishes all frameworks to one folder if -o specified

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#810] opened 2016-01-12 21:37 UTC
If the output folder is specified and the project.json contains multiple frameworks `dotnet publish` will publish everything into the folder specified by the user.
It would make sense to treat the output folder specified by the user as a root under which the entire structure of Configuration/Framework/Runtime is created - at least if project.json contains more than one framework. 

https://github.com/dotnet/cli/blob/0e4719ee95c05541ae4e32b589b9ea1e96269e25/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L86-L94

**Comment by piotrpMSFT** [comment] 2016-01-15 20:17
this is a duplicate of #760

**Closed by piotrpMSFT** 2016-01-15 20:17 UTC
