### ISSUE TITLE
dotnet run swallows empty lines

### ISSUE THREAD

**Issue by jskeet** [dotnet/cli#3186] opened 2016-05-22 14:41 UTC
## Steps to reproduce

Start with `dotnet new` - no `project.json` changes required.

`Program.cs`:

```csharp
using System;

class Test
{
    static void Main()
    {
        Console.Write("x\n");
        Console.Write("\n");
        Console.Write("y\n");
        Console.Write("a\n");
        Console.Write("\n\n");
        Console.Write("b\n");
    }
}
```

Build and run:

```sh
$ dotnet restore
$ dotnet run
```

## Expected  behavior

There should be one blank line between `x` and `y`, and two between `a` and `b`, i.e.

```text
x

y
a


b
```

## Actual behavior

The blank lines are missing:

```text
x
y
a
b
```

If instead you run it with `dotnet bin/Debug/netcoreapp1.0/bug.dll` then the output is as expected

## Environment data
`dotnet --info` output:

```text
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.10
 OS Platform: Linux
 RID:         ubuntu.15.10-x64
```

I initially thought this was Linux only, but I've now seen the exact same behaviour on my Windows box:

```text
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by jasonwilliams200OK** [comment] 2016-05-22 15:01
This is a duplicate of #2234.
#2235 and #2244 pull requests are fixing this problem. (@svick both PRs need a rebase)

**Comment by svick** [comment] 2016-05-25 22:50
@jasonwilliams200OK Thanks for letting me know, I have rebased #2244.

**Comment by piotrpMSFT** [comment] 2016-05-26 06:38
Closing since duplicate of #2234

**Closed by piotrpMSFT** 2016-05-26 06:38 UTC
