### ISSUE TITLE
Add support for dotnet test path_to_solution

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#5876] opened 2017-03-01 02:44 UTC
Currently we cannot do `dotnet test` for a solution. That feature would be great to have!

e.g. - `dotnet test NuGet.Sln`

//cc: @emgarten @piotrpMSFT @livarcocc

**Comment by livarcocc** [comment] 2017-03-01 06:06
Duplicate of https://github.com/Microsoft/vstest/issues/411.

**Closed by livarcocc** 2017-03-01 06:06 UTC
