### ISSUE TITLE
Wrong command name for dotnet restore --help

### ISSUE THREAD

**Issue by thecodejunkie** [dotnet/cli#2366] opened 2016-04-08 09:24 UTC
## Steps to reproduce
Run `dotnet restore --help`

## Expected  behavior
> Usage: dotnet restore [arguments] [options]

## Actual behavior
> Usage: nuget3 restore [arguments] [options]

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-002279)

Product Information:
 Version:     1.0.0-beta-002279
 Commit Sha:  76610c4cd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

**Comment by krwq** [comment] 2016-04-08 18:20
duplicate of https://github.com/dotnet/cli/issues/2348

**Closed** 2016-04-08 18:20 UTC
