### ISSUE TITLE
How to 'uninstall' a built CLI

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#259] opened 2015-11-19 15:38 UTC
I built the CLI. It worked. It's now in my path. Remind me how I remove it so that I can install a new version. I want to install the PKG version, so don't want the versions to conflict.

Can this be written down somewhere?

/cc @blackdwarf

**Comment by blackdwarf** [comment] 2015-11-19 15:42
If you built it from source, just remove the $PATH binding by editing the env variable. If you created symlinks, rm those. 

Will write it down for people, though these are not cli-specific but rather os-specific operations. :)

**Comment by richlander** [comment] 2015-11-19 15:49
/I/ didn't do anything. It's whatever the build script did.

Should I just rm /usr/local/bin/dotnet*

**Comment by blackdwarf** [comment] 2015-11-19 16:58
@anurse  Did we change the build script to now install stuff? 

@richlander yeah, in that case, you can do the following: 

1. Remove /usr/local/share/dotnet dir  (rm -r)
2. Remove all of the symlinks in /usr/local/bin that point to the above dir.

**Comment by anurse** [comment] 2015-11-19 17:09
The build script certainly shouldn't install the outputs of the build. Are you possibly hitting https://github.com/dotnet/cli/issues/200 (which has been fixed) and actually seeing the installed stage0?

Either way, running `where dotnet` should help you find the things to clean up.

**Comment by blackdwarf** [comment] 2015-11-19 17:13
@anurse yeah, that sounds about right, build just drops the artifacts locally, shouldn't be installing.

**Comment by blackdwarf** [comment] 2015-11-19 22:20
OK, I'm going to close this because it seems that we are already tracking it as #200 and the issue is not valid, since the behavior is abberant.

**Closed by blackdwarf** 2015-11-19 22:20 UTC
