### ISSUE TITLE
Telemetry Error

### ISSUE THREAD

**Issue by daholste** [dotnet/cli#11530] opened 2019-06-11 19:17 UTC
Hey Dotnet CLI,

To build the ML.NET CLI, we forked the telemetry portion of this repo. When @justinormont was executing this code on a Mac laptop, during one run, the following exception occurred:

```
Internal CLR error. (0x80131506)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at System.Net.NetworkInformation.BsdNetworkInterface.GetBsdNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

Out of four runs today (and many in the past) on the Mac of the same code, this only happened one time.

Any thoughts on what the issue could be?

**Comment by peterhuene** [comment] 2019-06-11 19:39
Hi @daholste:

It looks like #11531 was an accidental dupe of this one, which was now closed as a dupe of a CoreFX issue.  I am going to close this issue as well.  Please reopen if there's something I'm missing.  Thanks!

**Closed by peterhuene** 2019-06-11 19:39 UTC
