### ISSUE TITLE
Duplicate Targetframework attribute

### ISSUE THREAD

**Issue by kai-oswald** [dotnet/cli#9197] opened 2018-05-04 10:15 UTC
Not sure if this is an issue of the used template (since it's not an official template) or of dotnet.
I'm trying to run the application under Ubuntu 16.04 and am getting the following error when building the application the second time. I tried deleting the `obj` and `bin` folders, but the error persists.
When building and running the first time everything works fine. The error doesn't occur on my windows development machine, only on my ubuntu server

## Steps to reproduce
`dotnet new -i aspnetcore-vuejs`
`dotnet new vuejs`
`dotnet restore`
`npm install`
`npm run install`
`dotnet run`
`dotnet run` (second time)
## Expected  behavior
Successful build

## Actual behavior
Building will produce the following error:
```
/tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,12): error CS0579: `Duplicate attribute "global::System.Runtime.Versioning.TargetFrameworkAttribute". [/var/www/test2/test2.csproj]
```

## Environment data
`dotnet --info` output:
```
.NET-Befehlszeilentools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by peterhuene** [comment] 2018-06-20 22:23
Hi @kai-oswald.  I'm unable to reproduce this with the `2.1.300` version of the SDK.  The subsequent `dotnet run` command executes without error.

Would you mind trying a more recent SDK, such as 2.1.300 and see if that addresses your issue?

I'm going to close this issue for now.  If you are able to reproduce it with a later SDK, please re-open this issue and I will investigate.  Thanks for reporting this to us!

**Closed by peterhuene** 2018-06-20 22:23 UTC

**Comment by Adrug** [comment] 2018-09-29 17:03
I have too this problems. It started when i run ` npm install`.
npm packages  installation finished with error then `dotnet build` got error

```
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/root/betprofit-server/VFL.Web/VFL.Web.csproj]
```

My platform
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.2 [/usr/share/dotnet/sdk]
  2.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
