### ISSUE TITLE
Dotnet core 2.1 rc-1 won't load projects targeting net461

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#9241] opened 2018-05-09 15:31 UTC
@dloukola commented on [Wed May 09 2018](https://github.com/dotnet/core/issues/1525)

I have been working with dotnet core 2.1 preview 2 and earlier without issues. Installing the dotnet core 2.1 rc-1 SDK causes my webapi projects that are targeting 4.6.1 framework to fail to load.

It fails in the Startup at ConfigureServices when calling services.AddMvcCore().

The error message is: "the given key was not present in the dictionary"
It seems to error out in the stack trace at: "DefaultAssemblyPartDiscoveryProvider"

Uninstalling the 2.1 SDK makes everything work again, so it's definitely the issue.

I am targeting some aspnet core 1.* versions...maybe that is the issue?
Example:
Microsoft.AspNetCore.Authentication.JwtBearer (1.1.1)
Microsoft.AspNetCore.Diagnostics (1.1.1)
Microsoft.AspNetCore.Mvc (1.1.2)
Microsoft.AspNetCore.Routing (1.1.1)
Microsoft.AspNetCore.Server.IISIntegration (1.1.1)
Microsoft.AspNetCore..Server.Kestrel (1.1.1)

Any ideas?

---

@thyams commented on [Wed May 09 2018](https://github.com/dotnet/core/issues/1525#issuecomment-387761135)

Try replacing the AspNetCore 1.0 packages with AspNetCore.All (v2.0.8),

---

@dloukola commented on [Wed May 09 2018](https://github.com/dotnet/core/issues/1525#issuecomment-387762080)

@thyams  I have a plan to try that. However, I have no current intention to migrate that project to core 2.0. Installing a SDK shouldn't break older projects. I'm not referencing and 2.1-rc1 nuget packages in that project. 2.1 preview 2 didn't have this issue.

---

@thyams commented on [Wed May 09 2018](https://github.com/dotnet/core/issues/1525#issuecomment-387763401)

It might be the configuration / startup change. Try this change (without package updates):
![image](https://user-images.githubusercontent.com/1414138/39821275-d92eb102-5375-11e8-8360-22f10622f96a.png)

Thats kestrel running successfully running a brand new project utilizing everything NetCore 2.0 (so no old packages) but try with your setup.

AddMvcCore() is a little different then just utilizing AddMvc()

---

@dloukola commented on [Wed May 09 2018](https://github.com/dotnet/core/issues/1525#issuecomment-387779085)

I appreciate the thought of updating...but like I said previously, I think we need a workaround that will allow the 2.1 sdk installed without having to change apps that aren't using 2.1. 
I have tried adding global.json files all over the place to no avail.

**Comment by Petermarcu** [comment] 2018-05-09 15:32
@livarcocc can you have someone take a look? Installing 2.1.300 shouldn't break people's existing 4.6 webapi projects.

**Comment by livarcocc** [comment] 2018-05-09 17:13
I believe this issue should be looked at first by asp.net. Moving it there. If it is confirmed to be an SDK issue, this one can be re-activated.

**Comment by livarcocc** [comment] 2018-05-09 17:13
This issue was moved to aspnet/Home#3132

**Closed by livarcocc** 2018-05-09 17:13 UTC

**Comment by pspkshah** [comment] 2018-08-20 05:54
Hey Hey, I got the solution for the same issue, if any of your application targeting to .net Framework 4.6.1 and you wants to install, .net Core SDK (in my case I installed dotnet-sdk-2.1.302-win-x64.exe ).

Solution: just change your .net Framework to 4.7.1, and everything will work fine, without changing any of the code.

Cause: What I understood about the issue is, there is problem with .net Framework 4.6.x where its not able to find their assembly and getting conflict with .net core SDK.
since, .net framework 4.7.x has .core features in build, it differentiates and things gets managed.

Issue, which is mentioned at very beginning, @livarcocc , same issue I was getting.

Here, I was able to open, edit and commit all my changes, even I was able to build project as well, but when I start running my application from Host project (startup project / default project)

var host = new WebHostBuilder()
.UseKestrel()
.UseContentRoot(Directory.GetCurrentDirectory())
.UseIISIntegration()
.UseStartup()
.Build();

        host.Run();  --> Host is not able to initialising project, due wrong referencing
Applying above solution if anyone facing similar issue, comment on this, will resolve !!!
