### ISSUE TITLE
Improve instructions for running an installed global tool when the tool follows the dotnet-blah convention

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#8424] opened 2018-01-18 19:38 UTC
Repro steps:
- Install the SDK
- Add the https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json NuGet feed
- Run `dotnet install tool dotnet-dev-certs --version <whatever's latest>`

Actual output:

```
The installation succeeded. If there is no other instruction. You can type the following command in shell directly to invoke: dotnet-dev-certs
```

Expected output (a space between dotnet and dev-certs):

```
The installation succeeded. If there is no other instruction. You can type the following command in shell directly to invoke: dotnet dev-certs
```

**Comment by livarcocc** [comment] 2018-01-18 20:42
This is by design. For global tools, we display as the command to be run the command that was configured in the package.

We do not have plans to infer different instructions based the form of the command.

Now, once this becomes a native verb on the CLI, then it will be invoked with dotnet dev-certs. Right now, it works because when the you type dotnet verb and the CLI does not find a matching verb, it tries to invoke dotnet-verb from the path, and as a global tool, we have dotnet-dev-certs in the path.

**Closed by livarcocc** 2018-01-18 20:42 UTC
