### ISSUE TITLE
Could not find file _._ while trying to dotnet publish

### ISSUE THREAD

**Issue by mmalolepszy** [dotnet/cli#2250] opened 2016-04-04 11:09 UTC
## Steps to reproduce

- `dotnet new`
- Edit `project.json`:
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-23931"
    }
  },
  "frameworks": {
    "netstandardapp1.5": {}
  },
  "runtimes": {
    "win7-x64": {},
    "ubuntu.14.04-x64": {}
  }
}
```
- `dotnet restore`
- `dotnet publish`

## Expected  behavior

```
Published to C:\project\bin\Debug\netstandardapp1.5\win7-x64\publish
Published 1/1 projects successfully
```

## Actual behavior

`Could not find file 'C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.DotNetHost\1.0.0-rc2-00001\runtimes\win7-x64\native\_._'.`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

## Additional info
- Publish succeedes after creating `_._` files in 
```
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.DotNetHost\1.0.0-rc2-00001\runtimes\win7-x64\native
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.DotNetHostPolicy\1.0.0-rc2-00001\runtimes\win7-x64\native
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.DotNetHostResolver\1.0.0-rc2-00001\runtimes\win7-x64\native
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.2-rc2-23931\runtimes\win7-x64\native
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Windows.ApiSets\1.0.1-rc2-23931\runtimes\win7-x64\native
C:\Users\<my-user>\.nuget\packages\runtime.win7-x64.runtime.native.System.IO.Compression\4.0.1-rc2-23931\runtimes\win7-x64\native
```
- Similar behavior can be observed on Ubuntu 14.04. `dotnet --info`:
```
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by piotrpMSFT** [comment] 2016-04-05 04:23
@schellap looks like a host packaging issue

**Comment by schellap** [comment] 2016-04-06 19:24
@weshaggard any ideas here? I know this `_._` is a placeholder, but are these expected to be present in the package?

**Comment by weshaggard** [comment] 2016-04-06 19:36
cc @ericstj 

Yes placeholder files should be present in the package as they are used as markers by nuget to mean there is no asset.

**Comment by schellap** [comment] 2016-04-06 19:42
This happens for all native packages, coreclr, apisets, host sub packages... I will talk to @ericstj what this is about.

**Comment by gkhanna79** [comment] 2016-04-06 20:27
@Sridhar-MS Assigned to you since you are looking into this.

**Comment by weshaggard** [comment] 2016-04-06 20:27
@mmalolepszy can you please remove 

```
      "type": "platform",
```

Currently you cannot have that along with RID's specified. @anurse this error message needs to be fixed so we don't get into this situation or we need to teach publish to handle it correctly.

**Comment by ericstj** [comment] 2016-04-06 20:29
None of these actually require placeholders since they have actual content in that directory in the package.

**Comment by anurse** [comment] 2016-04-06 20:29
> Currently you cannot have that along with RID's specified.

You sure can. That enables the non-portable-but-shared-framework scenario. This error was caused by something else, and I think @pakrym fixed it. Does it still repro on the latest builds?

**Comment by anurse** [comment] 2016-04-06 20:29
Ah, I've seen this before. The file exists, but NuGet is dropping a placeholder in the lock file. This may be a NuGet bug.

**Comment by piotrpMSFT** [comment] 2016-04-06 20:30
@petermarcu hit this yesterday.

@krwq you're finishing up #2198 which repros the issue. Are you still seeing it?

**Comment by piotrpMSFT** [comment] 2016-04-06 20:31
@emgarten adding you in case this is a Nuget issue.

**Comment by anurse** [comment] 2016-04-06 20:38
To be clear, @pakrym 's change should remove the immediate error since he filters out `_._` files during publish. However, this is still a bug, since there should be a file in the lock file but we're getting a placeholder instead

**Comment by Sridhar-MS** [comment] 2016-04-06 20:43
I am not able to repro this with a later version `1.0.0-beta-002222`.

When did @pakrym changes go in?

**Comment by pakrym** [comment] 2016-04-06 20:45
https://github.com/dotnet/cli/commit/87ee62c282b9124ec2f63bbd7cb3963cbbd0c4b7

**Comment by schellap** [comment] 2016-04-06 21:03
Cc @brthor the errors you saw the other day (and Compilation Failed)...

**Comment by Sridhar-MS** [comment] 2016-04-06 23:30
The bug is no longer reproing with @pakrym 's fix - https://github.com/dotnet/cli/commit/87ee62c282b9124ec2f63bbd7cb3963cbbd0c4b7

I think there is still an underlying nuget restore bug. If a project.json contains `type: platform` and the `runtimes` node too, then restore drops the placeholder `_._` into the lock file even though files are present in the nuget package.

Example:

```
"runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc2-23931": {
        "type": "package",
        "compile": {
          "ref/netstandard1.0/_._": {}
        },
        "runtime": {
          "runtimes/win7-x64/lib/netstandard1.0/_._": {}
        },
        "native": {
          "runtimes/win7-x64/native/_._": {}
        }
      },
```

**Comment by emgarten** [comment] 2016-04-07 05:32
The placeholder ``_._`` is added to the lock file so that compatibility can be checked outside of NuGet. Looks like this has already been fixed, but it is expected that consumers of the lock file understand the ``_._`` convention.

**Comment by schellap** [comment] 2016-04-07 06:24
Are these useful in the deps file? I saw them show up there, and the host thinks it is an asset. If they don't serve any purpose don't put in the deps file.

**Comment by ericstj** [comment] 2016-04-07 14:48
They need to be there to replicate package structure.  For instance of a package includes a DLL on win7 but that DLL is part of the operating system on win8.  Host shouldn't try to load package copy.

**Comment by anurse** [comment] 2016-04-07 17:15
Yeah, the `_._` indicates that the host **should** match that section as an asset, but not load anything. It implies that the assembly/library is already going to be loadable (in Desktop, that means the GAC, on  Core that means the shared framework, or in the case of a native library, an OS-specific library search path).

**Comment by Sridhar-MS** [comment] 2016-04-07 21:38
I think there are two issues here

- Even though `Microsoft.NETCore.Runtime.CoreCLR` has an implementation for `win7-x64` why are placeholders being dropped for `runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR` instead of actual assemblies?

- Host is currently probing for `_._`. Even though it does not fail it or add it to the TPA, it can do better to completely ignore `_._` as an optimization. cc @schellap

**Comment by anurse** [comment] 2016-04-07 21:49
Ah, I've worked out why the placeholders are there. If you specify `type: platform` for a dependency, we add the `exclude: runtime, native` flags which mean that runtime/native assets are dropped from the lock file (intentionally) because those assets are available in the shared framework. So that's not actually a bug (as long as we have `type: platform` in this scenario)

**Comment by anurse** [comment] 2016-04-07 21:49
So @pakrym 's fix is sufficient for fixing the publish failure.

**Comment by Sridhar-MS** [comment] 2016-04-07 22:19
Ok. So there is no bug here except for 
> Host is currently probing for `_._`. Even though it does not fail it or add it to the TPA, it can do better to completely ignore `_._` as an optimization. cc @schellap

Filed #2351 to track this.

**Comment by Sridhar-MS** [comment] 2016-04-08 20:28
Closing this issue.

@mmalolepszy The issue is fixed. Reopen the issue of still facing it.

**Comment by Sridhar-MS** [comment] 2016-05-11 00:20
Actually closing this issue now.

**Closed by Sridhar-MS** 2016-05-11 00:20 UTC
Labels: bug
