### ISSUE TITLE
PublishRoslyn generates invalid runtimeconfig.json file

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#8613] opened 2018-02-14 19:53 UTC
See https://github.com/dotnet/roslyn/issues/24816

In Azure AppService ASP.NET Core ligthup scenario we bring additional deps and runtime store for 2.1-* runtime and set `DOTNET_ADDITIONAL_DEPS/ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` environment variables that affect all dotnet processes 

`csc.runtimeconfig.json` has TFM set to `netcoreapp2.0` but shared framework version `2.1.0-preview1-26116-04` which causes additional deps file to be resolved from `2.1.0-preview1-26116-04` hive while runtime store is resolved from `netcoreapp2.0` hive that doesn't even exists (we only care about 2.1). Corehost running csc.dll is unable to resolve libraries from additional deps and crashes.

# csc.runtimeconfig.json 
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0-preview1-26116-04"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

This afects preview1 of ASP.NET Core site extension

/cc @muratg @livarcocc @eerhardt

**Comment by eerhardt** [comment] 2018-02-14 20:10
@steveharter 

Thinking more about this, why does `csc` need those additional libraries?  It shouldn't be depending on anything in the store.  So is it the `dotnet.exe` host that is complaining and raising an error?

**Comment by pakrym** [comment] 2018-02-14 20:17
It doesn't, it just happens to pick up the same set of environment variables that are used by asp.net core site on AppServices (environment variables are set on w3wp hosting process level which then executes both customer site and `dotnet build -> dotnet csc`).

**Comment by livarcocc** [comment] 2018-02-14 21:29
@pakrym it is not clear to me what is your ask with this bug. Can you clarify that?

**Comment by pakrym** [comment] 2018-02-14 21:31
`runtimeconfig.json` file is invalid, it targets `netcoreapp2.0` but requires `2.1.0-preview1-26116-04` which breaks additional deps/runtime store scenarios.

We either need to decide that this is wrong and fix it or rethink how additional deps/runtime store  is discovered.

**Comment by livarcocc** [comment] 2018-02-14 21:53
There are a few different things that need to happen for us to make this change:

1. Roslyn needs to target netcoreapp2.1, which is what the CLI ships with.
2. We need the host to rollforward on minor version, so that we can keep Roslyn's M.NC.App version at 2.0.0 but running against 2.1.0-preview1 or whatever other version the CLI is currently targeting.

What are the scenarios that are breaking because of it targeting netcoreapp2.0 and specifying a 2.1 runtime? And we have been doing this for a while, so it sounds to me like some new scenarios are broken and that this is not a regression. Correct?

@steveharter do we have minor version roll-forward enabled and working?

**Comment by muratg** [comment] 2018-02-14 23:25
cc @glennc

**Comment by pakrym** [comment] 2018-02-14 23:34
>What are the scenarios that are breaking because of it targeting netcoreapp2.0 and specifying a 2.1 runtime? 

We bring `2.1-preview1-*` additional deps and `netcoreapp2.1` in one of our site extensions to enable light up on Azure functionality. 

Because of how environment variables are set in this scenario `dotnet  build` and subsequently `dotnet csc` happens to inherit `DOTNET_ADDITIONAL_DEPS/ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` environment variables. 

`corehost` correctly pickups `additionalDeps` because `csc` is running on `2.1-preview1-*` but when it tries to resolve dll locations for additional deps it doesn't pick up runtime store that is `netcoreapp2.1` only while `csc` has `netcoreapp2.0` in `runtimeconfig` causing compiler to crash.

**Comment by livarcocc** [comment] 2018-02-14 23:51
So, you would be ok if csc targeted netcoreapp2.0 with M.NC.App 2.0.0? This is more feasible, as it is a CLI only change, given that minor version roll forward is available.

Otherwise, you will need to get roslyn to change their TFM.

**Comment by pakrym** [comment] 2018-02-14 23:53
Yes, we would be totally fine with it,

**Comment by Petermarcu** [comment] 2018-02-14 23:55
@steveharter

**Comment by livarcocc** [comment] 2018-02-14 23:59
Also, want to confirm that this is not blocking for preview1 and can be fixed in preview2?

**Comment by pakrym** [comment] 2018-02-15 00:03
We are yet to try the possible workaround

**Comment by livarcocc** [comment] 2018-02-15 00:13
ok, we will handle it for preview2 for now and if necessary we can cherry-pick it back into preview1.

**Closed** 2018-02-16 18:40 UTC
