### ISSUE TITLE
Cannot run build.sh on Gentoo due to 404 error

### ISSUE THREAD

**Issue by svick** [dotnet/cli#1835] opened 2016-03-14 14:47 UTC
## Steps to reproduce
1. Clone the `cli` repo.
2. Execute `build.sh` on Linux (Gentoo) on branch `rel/1.0.0` or `master`.

## Expected  behavior
Build progresses successfully.

## Actual behavior
Build fails trying to download `dotnet.tar.gz`.

On `rel/1.0.0`:
```
dotnet_install: Preparing to install .NET Tools from 'beta' channel to '/redacted/dotnet/cli/scripts/../.dotnet_stage0/Linux'
ldconfig is not in PATH, trying /sbin/ldconfig.
dotnet_install: Downloading dotnet--x64.1.0.0.001665.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001665
######################################################################## 100.0%
HTTP Error 404 fetching the dotnet cli from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001665 
```

On `master`:
```
dotnet_install: Preparing to install .NET Tools from 'dev' channel to '/redacted/dotnet/cli/scripts/../.dotnet_stage0/Linux'
ldconfig is not in PATH, trying /sbin/ldconfig.
dotnet_install: Latest Version: Time:2016-03-14T14:44:39.5138665Z</Message></Error>
dotnet_install: Local Version: <none>
dotnet_install: Downloading dotnet--x64.latest.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest
######################################################################## 100.0%
HTTP Error 404 fetching the dotnet cli from https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest 
```

**Comment by branciat** [comment] 2016-03-14 19:48
Only the OS in the file scripts/obtain/install.sh are defined, it find centos, rehl, ubuntu and debian. But debian is not recognized and generate the same error, i replaced with ubuntu for a test. you can see the name  dotnet--x64.latest.tar.gz is malformed, between the dotnet and x64 must have the os name.

**Comment by SirCmpwn** [comment] 2016-06-27 22:06
What does that tarball have in it that's distro specific? I took a look and nothing in particular jumps out. What is it used for?

**Comment by blackdwarf** [comment] 2016-07-21 14:44
@svick does this still repro?

**Comment by svick** [comment] 2016-07-21 15:26
The errors are different now, but it still tries to download a file that does not exist and fails.

Maybe this should be closed in favor of a general "support building on unknown Linux distributions" issue? (#1532?)

The errors:

```
dotnet_install: Error: OS name could not be detected
dotnet_install: Error: Download failed
```

Full output:

```
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars
dotnet-install: Calling: get_azure_channel_from_channel rel-1.0.0
dotnet-install: azure_channel=rel-1.0.0
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture
dotnet-install: Calling: get_normalized_architecture_from_architecture x64
dotnet-install: normalized_architecture=x64
dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.blob.core.windows.net/dotnet rel-1.0.0 x64 Latest
dotnet-install: Calling: get_latest_version_info https://dotnetcli.blob.core.windows.net/dotnet rel-1.0.0 x64
dotnet-install: Calling: get_current_os_name
dotnet_install: Error: OS name could not be detected
dotnet-install: get_latest_version_info: latest url: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/latest.version
dotnet-install: Calling: download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/latest.version
dotnet-install: get_specific_version_from_version: version_info=76058bea60c0744a49574445c18999a592a2b91a
1.0.0-preview3-003208
dotnet-install: Calling: get_version_from_version_info
dotnet-install: specific_version=1.0.0-preview3-003208
dotnet-install: Calling: construct_download_link https://dotnetcli.blob.core.windows.net/dotnet rel-1.0.0 x64 1.0.0-preview3-003208
dotnet-install: Calling: get_current_os_name
dotnet_install: Error: OS name could not be detected
dotnet-install: download_link=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003208/dotnet-dev--x64.1.0.0-preview3-003208.tar.gz
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_share_path
dotnet-install: resolve_installation_path: share_path=/afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux
dotnet-install: install_root=/afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux
dotnet-install: Calling: check_pre_reqs
ldconfig is not in PATH, trying /sbin/ldconfig.
dotnet-install: Calling: install_dotnet
dotnet-install: Calling: is_dotnet_package_installed /afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux sdk 1.0.0-preview3-003208
dotnet-install: Calling: combine_paths /afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux sdk
dotnet-install: combine_paths: root_path=/afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux/sdk 1.0.0-preview3-003208
dotnet-install: combine_paths: root_path=/afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux/sdk
dotnet-install: combine_paths: child_path=1.0.0-preview3-003208
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/afs/ms.mff.cuni.cz/u/o/ondep7am/cli/build_projects/dotnet-cli-build/../../.dotnet_stage0/Linux/sdk/1.0.0-preview3-003208
dotnet-install: Zip path: /tmp/u/ondep7am/dotnet.Pekmw4md9
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003208/dotnet-dev--x64.1.0.0-preview3-003208.tar.gz
dotnet-install: Calling: download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003208/dotnet-dev--x64.1.0.0-preview3-003208.tar.gz /tmp/u/ondep7am/dotnet.Pekmw4md9
dotnet_install: Error: Download failed
```

**Comment by blackdwarf** [comment] 2016-07-22 06:48
@svick this is by design as far as the script behavior goes. I think you are right, we should close this in favor of the one that tracks overall Linux distro work you linked.

**Closed by blackdwarf** 2016-07-22 06:48 UTC
