### ISSUE TITLE
dotnet restore fails to resolve local dependencies with a DEFAULT folder strucutre

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/cli#5030] opened 2016-12-15 09:56 UTC
## Steps to reproduce
1) Start VS 2015 Update 3
2) Create ASP.Core App project (.NET Framework)
3) Create .NET Framework Class library
4) Reference Class Library project in Asp.Core project
5) run dotnet restore for ASP.Core App

## Expected  behavior
dotnet restore works

## Actual behavior
dotnet restore ends with error

```
log  : Restoring packages for D:\cot\Test\TestSolution\src\WebApplication1\project.json...
error: Unable to resolve 'ClassLibrary1' for '.NETFramework,Version=v4.5.2'.
log  : Restoring packages for tool 'BundlerMinifier.Core' in D:\cot\Test\TestSolution\src\WebApplication1\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in D:\cot\Test\TestSolution\src\WebApplication1\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in D:\cot\Test\TestSolution\src\WebApplication1\project.json...
log  : Writing lock file to disk. Path: D:\cot\Test\TestSolution\src\WebApplication1\project.lock.json
log  : D:\cot\Test\TestSolution\src\WebApplication1\project.json
log  : Restore failed in 2647ms.
dotnet : 
At line:1 char:1
+ dotnet restore
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Errors in D:\cot\Test\TestSolution\src\WebApplication1\project.json

    Unable to resolve 'ClassLibrary1' for '.NETFramework,Version=v4.5.2'.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

NOTES: I know about https://github.com/dotnet/cli/issues/3199  which says that after some magic you can push it working. 
But..
1) I use default structure! There VS propose folders location for me - this should work from the box.
2) I can't succeed with the proposed "solution". My global.json is in a solution folder and I have added some new entries to  ` "projects": [ "src", "test", "ClassLibrary1", ".","..","..","../ClassLibrary1" ],`  dotnet restore still doesn't work
3) Actually I do not want to use flat "structure" which was proposed where all projects "class libraries" and "services" are on the one level. The default structure with src folder for web app and other services is exactly what I need. But I can't understand from documentation is the flat structure obligated or not. 

![cli bug](https://cloud.githubusercontent.com/assets/11598038/21219228/8bf4249e-c2bc-11e6-8be3-3ac2e68e4be0.PNG)

![cli bug 2](https://cloud.githubusercontent.com/assets/11598038/21219334/0a0d536e-c2bd-11e6-8b75-e9a1378d30f9.PNG)

[TestSolution.zip](https://github.com/dotnet/cli/files/654288/TestSolution.zip)

**Comment by piotrpMSFT** [comment] 2016-12-17 09:59
Since this is a project.json issue and there is a workaround I'm closing the issue. If you decide to `dotnet migrate` the project and see problems atop csproj [CLI preview3+, VS2017 RC+] please do open a new issue and we'll take a look!

**Closed by piotrpMSFT** 2016-12-17 09:59 UTC

**Comment by rpokrovskij** [comment] 2016-12-17 12:18
@piotrpMSFT  I feel befooled by MS team. I can't understand how you can close issue related to VS 2015 pointing that there is solution for VS 2017 RC...  In any normal team issue will be accepted and left open. It seems like a cheating around open issues number.

**Comment by piotrpMSFT** [comment] 2016-12-17 12:40
@rpokrovskij I'm not clear on what this issue should track if open. The issue is addressing the folder structure that was imposed by project.json and a potential bug in preview2 tooling for project.json. The particular folder structure requirement was eliminated in preview3 and you are now able to provide arbitrary layouts to projects. It seems to me like the issue is fixed exactly as requested. If there is some aspect to it that is not addressed please do help me understand it so we can make a fix!

I do agree that the versions used in the past create some confusion. Though VS2015 is RTM and already has a few shipped updates, the .NET Core + project.json tooling for VS2015 was a preview. As was reported in the original issue, VS2015 uses the 1.0.0-preview2-* version of the dotnet tools. The team has been working hard since then and is already on 1.0.0-preview5 [latest in this repo]. Since the project model has shifted so significantly between preview2 and preview3, there is not any opportunity for us to address bugs in the preview2 tooling. It would be an investment in technology which is not moving forward. 

We do continue to invest time to ensure that workarounds are available for preview2/project.json issues whenever possible. We don't want folks to be stuck with bugs that shipped in this early release, but also need to focus on bugs that are preventing us from releasing the 1.0.0 version of .NET Core tooling [1.0.0 without a preview suffix :)].

If the workaround you identified is not working, let me know and I'll try to help find another workaround. If there is an issue that is still blocking/inconvenient in the preview5 tooling please help me understand it so it can be fixed. I didn't close this issue to cheat at numbers, but because I'm not sure what is left here to track.

**Comment by rpokrovskij** [comment] 2016-12-23 07:52
@piotrpMSFT I can't find in VS 2017 RC possibility to work with ASP.Core project and Standard Framework.  "Migration" was failed with default projects (configured to use .net 4.6.2). I even can't find ASP.Core project template in Templates C#/Web folder. 

I have no words to describe my disappointment.
