### ISSUE TITLE
Trying to run preview 3 commands on project.json projects could give clearer error

### ISSUE THREAD

**Issue by svick** [dotnet/cli#4826] opened 2016-11-23 17:18 UTC
## Steps to reproduce

1. Create a project.json-based project.
2. Run a preview 3 command like `dotnet restore`, `dotnet build` or `dotnet run` on it.

## Expected  behavior

Clear error message explaining that the project is not compatible and suggesting `dotnet migrate`.

## Actual behavior

```
>dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

>dotnet build
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

>dotnet run
Couldn't find a project to run. Ensure a project exists in E:\Users\Svick\git\core\samples\helloworld.
Or pass the path to the project using --project
```

This is confusing to users that don't know the difference between the various Preview versions or about the switch from project.json to msbuild, for example: https://github.com/dotnet/core/issues/363.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by vcsjones** [comment] 2016-11-29 19:56
+1.

I would propose:

1. If there is no csproj / sln, and there is a project.json or global.json, then print out a message about "dotnet migrate"
2. If there is no project.json, then the existing message is probably fine.
3. If there is a csproj and a project.json, the tooling should be happy to use whatever it wants to so users can have SxS tooling for a project, if they want.

**Comment by Petermarcu** [comment] 2017-01-06 03:14
This is a CLI request best tracked in the dotnet/cli repo.

**Comment by jgoshi** [comment] 2017-01-10 01:31
So this one appears to need loc. Does this mean we need to push it out to RTM?

**Comment by livarcocc** [comment] 2017-01-10 18:16
@nguerrera for comment on loc.

**Comment by blackdwarf** [comment] 2017-01-20 05:55
We are closed down for strings, unfortunately, so will have to move it to post v1.

**Comment by piotrpMSFT** [comment] 2017-01-21 04:53
@blackdwarf I want to try to get this one in. This feature will have no use post 1.0 and could be hugely helpful during that milestone...

**Comment by blackdwarf** [comment] 2017-01-21 05:06
@piotrpMSFT so what, just an English error then?

**Comment by livarcocc** [comment] 2017-01-23 05:27
This seems like a duplicate of https://github.com/dotnet/cli/issues/4628.

**Closed** 2017-01-23 05:27 UTC
