### ISSUE TITLE
Could not resolve coreclr path when invoking a dotnet tool 

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#2026] opened 2016-03-24 16:32 UTC
## Steps to reproduce
Create a web application 
Add a tool like dotnet-ef / dotnet-aspnet-codegenerator
Invoke the tool 
for eg:
```
dotnet aspnet-codegenerator -h
```

## Expected  behavior
It shows the help text (or does whatever the tool is expected to do)

## Actual behavior
```
Could not resolve coreclr path
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001943)

Product Information:
 Version:     1.0.0-beta-001943
 Commit Sha:  c06e1b7a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x86

```

`where dotnet` output:

```
C:\Program Files (x86)\dotnet\dotnet.exe
```

Attached trace 
[Full Trace for invoking tool.txt](https://github.com/dotnet/cli/files/188219/Full.Trace.for.invoking.tool.txt)

**Comment by brthor** [comment] 2016-03-24 18:21
Hey @prafullbhosale could you share a project.json and NuGet.config ?

**Comment by prafullbhosale** [comment] 2016-03-24 18:27
I just created a new web project using the latest WTE build. 

Nuget.config (global nuget.config. There isn't one for the project)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <activePackageSource>
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </activePackageSource>
</configuration>
```

Project.json
```
{
  "userSecretsId": "aspnet-WebApplication95-67bfb6d6-502b-4665-9964-ddfa7bcf2edc",
  "compilationOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.HttpOverrides": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Identity": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20254",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-20254",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-20254",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-20254",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-20254",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-20254",
    "NETStandard.Library": "1.0.0-rc2-23826"
  },

  "frameworks": {
    "netstandardapp1.5": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "tools": {
    "dotnet-aspnet-codegenerator":  "1.0.0-rc2-20254",
    "dotnet-ef": "1.0.0-rc2-20254",
    "dotnet-publish-iis": "1.0.0-rc2-20254",
    "dotnet-razor-tooling": "1.0.0-rc2-20254"
  },

  "content": [
    "wwwroot",
    "Views",
    "appsettings.json"
  ],

  "exclude": [
    "node_modules"
  ],

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath%" ]
  }
}
```

**Comment by brthor** [comment] 2016-03-24 18:49
Thanks!
Can you confirm these tools have been converted to Portable Apps as per #1970 ?

Regardless of that, I think there's an issue with the error message we're displaying.,

**Comment by prafullbhosale** [comment] 2016-03-24 21:57
No its not, its importing dnxcore50 and portable-net45+win8.
Will try to get rid of these and see if it works with that.

**Comment by brthor** [comment] 2016-03-25 17:17
@prafullbhosale I reproed this with `razor-tooling`

It is caused by the tools not yet having reacted to #1970 

I agree the error message here should be more obvious and not look like a bug though.

**Comment by brthor** [comment] 2016-04-18 21:38
Closing this out, as it was that tools were not yet portable.

**Closed by brthor** 2016-04-18 21:38 UTC
