### ISSUE TITLE
Publish from root folder breaks afterpublish scripts when setting an OutputFolder

### ISSUE THREAD

**Issue by WolfspiritM** [dotnet/cli#3679] opened 2016-06-22 21:02 UTC
Calling publish from the root (solution) Folder of an asp.net project and setting a relative output Folder to store the final Published project throws an exception in the IISIntegration Tool as it seems like it gets called from within the Project Directory causing it to resolve the outputFolder wrongly.

Also: The publish command will end with a green  `Published 1/1 projects successfully` even so the afterpublish script failed.

(Interestingly using a full path gave me a "Access is denied")
## Steps to reproduce

Directory Structure with simple Asp.net core App

```
- AspNetExample
| - src
| | - AspNetExample
| | | - ...
| | | - project.json (Includes IIS Integration Tool)
| | | - web.config
```

Calling from the root AspNetExample folder:
`dotnet publish src\AspNetExample -o output`
## Expected  behavior

Publishing and Configuring (IIS Tool) successfully.
Or at least no `Published 1/1 projects successfully` message if afterbuild script fails.
## Actual behavior

Publishing successfully but IISIntegration Tool throws an Exception:

```
Publishing AspNetExample for .NETCoreApp,Version=v1.0
Project AspNetExample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Configuring the following project for use with IIS: 'output'
No web.config found. Creating 'output\web.config'
Could not find a part of the path 'C:\projec\AspNetExample\src\AspNetExample\output\web.config'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\projec\AspNetExample\src\AspNetExample\output\web.config'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
publish: Published to output
Published 1/1 projects successfully
```
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by kirkone** [comment] 2016-06-28 10:00
Hello,

I want to add my experience with this.

The error you describe is only the result of an other problem.
When running `dotnet publish -o .\publish` with a relative path for the output is does not include any file specified under `publishOptions` in `project.json`.
This is the reason why it will fail with a `DirectoryNotFoundException` because there is no web.config.

If I use `dotnet publish -o w:\publish` the output is fine and all files and folders are there.

I can reproduce this with dotnet RC2 and dotnet 1.0

dotnet --info  output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by WolfspiritM** [comment] 2016-06-28 10:28
I'm pretty sure after trying that I verified that the web.config was in the correct path.

But as you can see it looks in the wrong path:
From C:\projec\AspNetExample I call the dotnet.exe with output path "output".
The Afterpublish script (IIS) however looks for the web.config in:
'C:\projec\AspNetExample\src\AspNetExample\output\web.config'
where the correct would be:
'C:\projec\AspNetExample\output\web.config'

That means it's using the wrong Execution Folder to look for when using a relative path and that's why I get the DirectoryNotFound Exception.

I wasn't able to test with 1.0 yet.

**Comment by kirkone** [comment] 2016-06-28 11:44
the web.config is there after the error occurred but it is not the one from your source. It will create an empty one when it can not be found.

Can you please try to use an absolute path for the output folder?
If this works we can narrow down the reason for the behavior.

Greetings, KirK

**Comment by kae** [comment] 2016-06-28 13:58
It looks like that cause of it is line

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Files/IncludeFilesResolver.cs#L43

Interestingly enough that condition was broken on Windows in rc2 and it doesn't broke anything at my usage.

So I don't understand what was initial thinking for guarding from '.' and '..' in output paths.

**Comment by kae** [comment] 2016-06-28 14:01
Also I can't understand why diagnostics argument is uncondionally null at 

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L190

So there isn't any to view diagnostics from processing of publishing copying.

**Comment by piotrpMSFT** [comment] 2016-11-12 21:07
dupe of #3745

**Closed by piotrpMSFT** 2016-11-12 21:07 UTC

**Comment by vineus** [comment] 2017-03-03 10:43
Hey there,

OutputDir works with `publish` on preview3+, but not with `publish-iss` apparently:

```
Configuring the following project for use with IIS: '%publish:OutputDir%'
No web.config found. Creating '%publish:OutputDir%\web.config'
The given path's format is not supported.
System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
```

using:

- `"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview4-final"`
- `"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview4-final"`

Am I doing something wrong ?

Thank you for your help
