### ISSUE TITLE
dotnet-resgen aborts on Windows 8.1 & 10

### ISSUE THREAD

**Issue by huangpf** [dotnet/cli#412] opened 2015-12-05 01:44 UTC
```dotnet publish $cmdletsDir -f dnxcore50 -r win7-x64 -o $packageSource```

==>

```
Running C:\Program Files\dotnet\bin\dotnet-resgen.exe "D:\git\a\ps-clu\src\CLU\Commands.Common.Authentication\Properties\Resources.resx" "obj\Deb
ug\dnxcore50\Commands.Common.Authentication.Properties.Resources.resources"
Process ID: 10276

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, Publi
cKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Except
ion from HRESULT: 0x80131040)
   at Microsoft.DotNet.Tools.Resgen.Program.WriteResourcesFileIfNotEmpty(String resxFilePath, String outputFile)
   at Microsoft.DotNet.Tools.Resgen.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Resgen.Program.Main(String[] args)
```

Win8.1 Info:
```
.NET Version Manager v1.0.0-rc2-15545
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-final   clr     x64          win
       1.0.0-rc1-final   clr     x86          win
       1.0.0-rc1-final   coreclr x64          win
       1.0.0-rc1-final   coreclr x86          win
       1.0.0-rc1-update1 clr     x64          win
       1.0.0-rc1-update1 clr     x86          win
  *    1.0.0-rc1-update1 coreclr x64          win             1.0.0-rc1-final, default
       1.0.0-rc1-update1 coreclr x86          win
```

Win10 Info:
```
.NET Version Manager v1.0.0-rc2-15545
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-beta5       clr     x64          win
       1.0.0-beta5       clr     x86          win
       1.0.0-beta5       coreclr x64          win
       1.0.0-beta5       coreclr x86          win
       1.0.0-rc1-final   clr     x64          win
       1.0.0-rc1-final   clr     x86          win
       1.0.0-rc1-final   coreclr x64          win
       1.0.0-rc1-final   coreclr x86          win
       1.0.0-rc1-update1 clr     x86          win
  *    1.0.0-rc1-update1 coreclr x64          win             default
```

Running ```dotnet-resgen.exe``` itself reproduces the problem as well, like described in #408.

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, Publi
cKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Except
ion from HRESULT: 0x80131040)
   at Microsoft.DotNet.Tools.Resgen.Program.WriteResourcesFileIfNotEmpty(String resxFilePath, String outputFile)
   at Microsoft.DotNet.Tools.Resgen.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Resgen.Program.Main(String[] args)
```

**Comment by huangpf** [comment] 2015-12-05 01:46
The ```.resx``` file can be accessed at: ```https://github.com/Azure/azure-powershell/blob/clu/src/CLU/Commands.Common.Authentication/Properties/Resources.resx```

**Comment by piotrpMSFT** [comment] 2015-12-07 18:59
This is a duplicate of #408

**Closed by piotrpMSFT** 2015-12-07 18:59 UTC
