### ISSUE TITLE
Publish for ubuntu.16.04-arm does not publish libuv.so

### ISSUE THREAD

**Issue by koenvanderlinden** [dotnet/cli#6072] opened 2017-03-19 10:06 UTC
## Steps to reproduce
`dotnet new webapi -n mywebapi`

**webapihello.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
	<RuntimeFrameworkVersion>2.0.0-beta-001791-00</RuntimeFrameworkVersion>
	<RuntimeIdentifiers>ubuntu.16.04-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
  </ItemGroup>
</Project>
```

Changed:
`<TargetFramework>netcoreapp1.0</TargetFramework>`
to
`<TargetFramework>netcoreapp2.0</TargetFramework>`

added:
```
<RuntimeFrameworkVersion>2.0.0-beta-001791-00</RuntimeFrameworkVersion>
<RuntimeIdentifiers>ubuntu.16.04-arm</RuntimeIdentifiers>
```
As 2.0.0-beta-001791-00 is the dotnet version that's installed on Raspberry Pi2.

Added the following keys to the nuget config:
add the keys:
```<add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
<add key="dotnet-corefxlab" value="https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json" />
<add key="aspnetcore-ci-dev" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />
```

`dotnet restore`

`dotnet publish -r ubuntu.16.04-arm`

## Expected  behavior
Publish output directory should contain libuv.so.

## Actual behavior
Publish output directory does not contain libuv.so.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005448)

Product Information:
 Version:            2.0.0-preview1-005448
 Commit SHA-1 hash:  f8c3c4a030

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005448\
```

**Additional Info**
When changing the project file to use runtime 2.0.0-beta-001663-00 it does publish the libuv.so file.
'<RuntimeFrameworkVersion>2.0.0-beta-001663-00</RuntimeFrameworkVersion>

'dotnet restore'
Nuget now downloads the runtime.ubuntu.16.04-arm.microsoft.netcore.app\2.0.0-beta-001663-00 package.
The .nuget\packages\runtime.ubuntu.16.04-arm.microsoft.netcore.app\2.0.0-beta-001663-00\runtimes\ubuntu.16.04-arm\native\ folder does contain the libuv.so.

\.nuget\packages\runtime.ubuntu.16.04-arm.microsoft.netcore.app\2.0.0-beta-001791-00\runtimes\ubuntu.16.04-arm\native\ folder is missing the libuv.so.

Maybe this is not a CLI problem, but more a packaging problem.

Copying the libuv.so file manually to a published output directory and running the webapi app on Raspberry Pi is working great.

Let me know how to prevent that manual step and how to make sure the libuv.so is published automatically.

**Comment by livarcocc** [comment] 2017-03-20 05:25
cc @gkhanna79 @Petermarcu

**Comment by gkhanna79** [comment] 2017-03-20 15:57
Libuv.so has been removed form SharedFX.

CC @eerhardt

**Comment by eerhardt** [comment] 2017-03-20 16:05
@gkhanna79 is correct.  See https://github.com/dotnet/core-setup/pull/1661.

ASP.NET hasn't been updated for .NET Core 2.0 yet, so it doesn't have the package reference itself yet.
/cc @davidfowl @pranavkm @Eilon 

You can workaround this by adding

```
<PackageReference Include="Libuv" Version="1.10.0-preview1-22036" />
```

to your project to get yourself unblocked.

Closing as this is "by design".  Libuv is no longer in the dependency graph, so it won't get published.

**Closed by eerhardt** 2017-03-20 16:05 UTC

**Comment by koenvanderlinden** [comment] 2017-03-23 13:05
@eerhardt thanks. The workaround solves the problem.
Created a [blogpost](https://kvdlinden.blogspot.nl/2017/03/getting-net-core-web-api-to-run-on.html) for other Raspberry Pi & .NET Core enthusiasts.
