### ISSUE TITLE
'dotnet pack' is not restoring right package dependencies when condition is used

### ISSUE THREAD

**Issue by ldubrois** [dotnet/cli#12480] opened 2019-09-04 15:14 UTC
## Steps to reproduce
I have a project in which I have created additional Configuration (Release_v3).

In the csproj of my project, I have added the following lines : 

```
  <PropertyGroup Condition="'$(Configuration)'=='Release_v3'">
    <PackageId>MyProject_v3</PackageId>
  </PropertyGroup>

  <ItemGroup Condition="''$(Configuration)'=='Release_v3'">
    <PackageReference Include="MyPackage" Version="3.0.19140.1527" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="MyPackage" Version="4.0.19157.2035" />
  </ItemGroup>
```

## Expected  behavior
When I run the ```dotnet pack``` command with the argument ```-c Release_v3``` the resulting package should include a dependency to MyPackage version 3

## Actual behavior
The package produced has the right name (which should indicate a right interpretation of the first condition) but the package has the version 4 of MyPackage as dependency.

Visual Studio, from the UI, produce the right packages dependencies

## Environment data
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2019-09-05 21:22
Can you share the project.assets.json file for when the dotnet pack runs and uses the wrong dependencies?

Are you sure restore is running when you pass the new configuration?

@nkolev92 is configuration an input for implicit restore?

**Comment by nkolev92** [comment] 2019-09-05 21:36
Nope. 
Restore by design won't use the configuration switch, because the assets file lives in root obj.
You need to pass it explicitly to every step or consider not using configuration as a pivot, but a custom property.

**Comment by ldubrois** [comment] 2019-09-06 07:19
Thanks for your feedback.

What is strange and disapointing is that Visual Studio does it well, but the command line does not.

I've seen on forum and issues many people has encountered the same issue.
@nkolev92  Is there somewhere some sample of how to perform it in the way you indicate it in your answer ?

thanks

**Comment by livarcocc** [comment] 2019-09-09 18:51
I am going to close this issue as for now the system is behaving as expected.

It is ok to continue talking here, but if you want some changes here, it seems nuget/home might be a better repo for this conversation.

**Closed by livarcocc** 2019-09-09 18:51 UTC
