### ISSUE TITLE
RC2 Tooling bits + latest dotnet cli, unable to do Ctrl-F5 or F5 with ASP.NET Core Web Application

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#2435] opened 2016-04-12 19:06 UTC
## Install Steps 
Dev14 U2 RTW
Install AspNetCoreTools RC2: \\aspnetci\drops\Setup-Bundle\release\54\x86\dvdQA\AspNetCoreTools.1.0.RC2.exe 
Install latest .NET CLI: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe 

![image](https://cloud.githubusercontent.com/assets/8246794/14472153/a98aad08-00a6-11e6-9754-9fe7a34c87d7.png)

## Steps to reproduce
1. New ASP.NET Core web app > Web Application
2. Ctrl - F5 or F5

## Expected  behavior
Ctrl-F5 and F5 work

## Actual behavior
F5, 
![image](https://cloud.githubusercontent.com/assets/8246794/14472183/daa75d6e-00a6-11e6-9d3b-d59da130e91c.png)

If I try to self-host, then I see the following error
![image](https://cloud.githubusercontent.com/assets/8246794/14472200/f11a3206-00a6-11e6-9a8a-8e84871d73fd.png)

## Environment data
`dotnet --info` output:

**Comment by piotrpMSFT** [comment] 2016-04-12 19:27
@barrytang can you have someone take a first look?

**Comment by piotrpMSFT** [comment] 2016-04-12 20:40
@balachir is working on a tool-less repro for CLI team to investigate.

**Comment by balachir** [comment] 2016-04-12 21:07
If I try to do 'dotnet run' on this empty web app from the command-line, I get 

![image](https://cloud.githubusercontent.com/assets/8246794/14475522/3b5b8896-00b7-11e6-92d2-f27d3c3c44c3.png)

I can also repro the above message on the command-line with "dotnet new"
![image](https://cloud.githubusercontent.com/assets/8246794/14475544/5c16ac32-00b7-11e6-9a8a-ab1d93b1708c.png)

Change the dependencies section in project.json to look like below. Version "1.0.0-rc2-23931" is what we get with the default template in our current tooling bits. 
```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-23931"
    }
  },
```
![image](https://cloud.githubusercontent.com/assets/8246794/14475599/a5779b84-00b7-11e6-994c-f4149e01bc79.png)

![image](https://cloud.githubusercontent.com/assets/8246794/14475617/bc0293a4-00b7-11e6-9f60-c655eb012d62.png)

**Comment by piotrpMSFT** [comment] 2016-04-12 21:13
@schellap, this is a host/fxr issue

**Comment by piotrpMSFT** [comment] 2016-04-12 21:15
Can you confirm this has to do with churn in the muxer and is something we should manually workaround by deleting old zip-installed CLI and start fresh?

**Comment by schellap** [comment] 2016-04-12 21:16
Could you please try:

```
copy "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-23931\hostfxr.dll" "C:\Program Files\dotnet\hostfxr.dll"
```

or better to Uninstall and start with a fresh installlation?

**Comment by balachir** [comment] 2016-04-12 21:31
@schellap, I tried copying over hostfxr.dll but I get the error in screenshot below now. 
![image](https://cloud.githubusercontent.com/assets/8246794/14476142/df4744f6-00ba-11e6-8d66-c6e672ad29de.png)

When you say "Uninstall and start with a fresh installation", do you mean I should try uninstalling the dotnet cli and installing latest from https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe ?

**Comment by schellap** [comment] 2016-04-12 21:33
Yes. Please use the latest installation from the link you have added. The latest bits should have the interface between hostfxr and hostpolicy stable.

**Comment by balachir** [comment] 2016-04-12 21:50
Hmm, I updated to the latest (1.0.0-rc2-002355) and I still see the same issue.

**Comment by piotrpMSFT** [comment] 2016-04-12 22:59
did you delete previous installs?

**Comment by balachir** [comment] 2016-04-12 23:22
I tried deleting the 1.0.0-beta-002275 folder from C:\Program Files\dotnet\sdk but that does not seem to help much either.

I talked offline with Senthil a little while ago. Apparently, there was a breaking change in hostfxr and the Microsoft.NETCore.App 1.0.0-rc2-23931 package which the default templates depend on currently is not compatible with the latest CLI version. So sounds like tooling needs to move to a newer set of compatible runtime packages to get this working again for VS tooling + latest CLI.

**Comment by barrytang** [comment] 2016-04-13 00:25
@Petermarcu, @Eilon, can you confirm tooling does need new packages to pick up a new CLI due to this breaking change? If yes, when can I expect the next Coherence-Signed? Thanks!

**Comment by schellap** [comment] 2016-04-13 00:37
1.0.0-rc2-23931 is quite an old CLI. We've made several changes (servicing related and bug fixes) to the host. These introduced new properties like patch roll forward and prerelease roll forward.

What is happening here is the newer host is used to load an older policy dll. The interface is now stabilized to be backwards compatible. So it is best to use the newer CLI, specifically, `hostfxr.dll` can load and execute all earlier `hostpolicy.dll` starting from `1.0.0-rc2-002349`.

**Comment by Eilon** [comment] 2016-04-13 01:27
ASP.NET is using CLI 1.0.0-rc2-002353 as of this afternoon.

**Comment by Eilon** [comment] 2016-04-13 01:27
However, there's some issues with ASP.NET full builds going through, so it might not be until tomorrow to get an ASP.NET build that is ready for Barry's team.

**Comment by barrytang** [comment] 2016-04-13 01:54
@Eilon, so you are saying I shouldn't pick up a new CLI until the next Coherence-Signed? And once I have done that, this issue will go away?

**Comment by Eilon** [comment] 2016-04-13 01:58
@barrytang I'm not sure what will happen if you take a CLI on your own. I think it depends on which CLI you have right now, but honestly I don't know all the intricacies.

**Comment by barrytang** [comment] 2016-04-13 02:16
With Bala's earlier comment, it seems to be the case.

> I talked offline with Senthil a little while ago. Apparently, there was a breaking change in hostfxr and the Microsoft.NETCore.App 1.0.0-rc2-23931 package which the default templates depend on currently is not compatible with the latest CLI version. So sounds like tooling needs to move to a newer set of compatible runtime packages to get this working again for VS tooling + latest CLI. 

I am going to assume my team is blocked picking up the next CLI until the next Coherence-Signed build unless someone tells me otherwise.

**Comment by gkhanna79** [comment] 2016-04-13 22:33
@piotrpMSFT How should we get a new build over to Barry's team?

**Comment by piotrpMSFT** [comment] 2016-04-15 00:07
My understanding of @barrytang's comment is that he's waiting for a new Coherence-Signed build from ASP.NET and is not blocked on CLI. If I'm missunderstanding help me grasp the gap.

**Comment by Eilon** [comment] 2016-04-15 00:57
We think @barrytang currently has everything he needs (perhaps minus some known issues), so I don't *think* he's particularly blocked right now. But he'd have to comment to confirm.

**Comment by barrytang** [comment] 2016-04-15 01:10
@piotrpMSFT, @Eilon, I did get the Coherence-Signed build from Eilon along with CLI 2374. My system is chugging along and should have a bundle build soon.@balachir will reply back to confirm whether the issue is fixed once we have a build.

**Comment by barrytang** [comment] 2016-04-15 03:19
Bad news... The issue is not fixed with the latest ASP.NET build + CLI. I will follow up with @schellap offline and provide a repro machine.

**Comment by gkhanna79** [comment] 2016-04-15 03:24
@barrytang What is the version of dotnet you are using?

**Comment by barrytang** [comment] 2016-04-15 03:28
2374

**Comment by gkhanna79** [comment] 2016-04-15 04:32
Examining the repro machine has confirmed (details shared offline) that the mismatch issue is resolved.

**Comment by gkhanna79** [comment] 2016-04-15 04:32
@barrytang @balachir Can you please close this once you have validated, at your end, the mismatch issue is addressed?

**Comment by barrytang** [comment] 2016-04-15 07:59
Will wait for @piotrpMSFT's ack that this is a CLI upgrade issue before we close this. Thanks for looking into this @gkhanna79!

**Comment by schellap** [comment] 2016-04-15 08:46
> So it is best to use the newer CLI, specifically, hostfxr.dll can load and execute all earlier hostpolicy.dll starting from 1.0.0-rc2-002349.

We should always be backwards compatible between hostfxr and hostpolicy. @piotrpMSFT we can close this one out once you copy.

**Comment by piotrpMSFT** [comment] 2016-04-15 20:34
@schellap do you believe there is an upgrade issue? Do we understand why installing a newer CLI did not get us back into a good state? Is this the expected "dotnet.exe + hostfxr.dll were in use during upgrade"?

**Comment by gkhanna79** [comment] 2016-04-15 20:52
The mismatch, I believe, was between the new hostfxr and the older hostpolicy that came from the older framework since both new and old pre-release FX were installed. If older is removed or renamed, everything works.

**Comment by schellap** [comment] 2016-04-15 21:29
The app still targets the old version. So the mismatch still exists. Starting from 2349, same situations install new with old with app targeting old will work fine.

**Comment by piotrpMSFT** [comment] 2016-04-15 23:04
Ok, closing.

**Closed by piotrpMSFT** 2016-04-15 23:04 UTC
Labels: blocking-partner
