### ISSUE TITLE
dotnet build .sln fails on multitargeted projects

### ISSUE THREAD

**Issue by Rurouni** [dotnet/cli#6312] opened 2017-04-13 16:51 UTC
Hi,
I have a solution that contains both netstandard1.6 projects and netcoreapp1.1. Some of netstandard project are multitargeting  `<TargetFrameworks>netstandard1.6;net20</TargetFrameworks>`
It builds perfectly in VS 2017 but not with dotnet build.

First I've tried  `dotnet build <path to sln>` and that gives errors about .Net Framework 2.0 not found for those project that have net20 target but I suppose that's expected 
but even trying `dotnet build <path to sln> -f netcoreapp1.1 ` or  `dotnet build <path to sln> -f netstandard1.6 ` output lots of errors about basic types not found and such.

The problem is only if trying to build with sln. because  dotnet build with individual projects works fine

## Steps to reproduce
`dotnet restore <path to sln> `
`dotnet build <path to sln> -f netcoreapp1.1`

## Expected  behavior
build succeeds 
## Actual behavior
lots and lots of errors  like  `error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)` or `error CS0518: Predefined type 'System.String' is not defined or imported`

## Environment data
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment] 2018-03-02 21:27
I believe this is a duplicate of https://github.com/dotnet/sdk/issues/826.

**Closed by livarcocc** 2018-03-02 21:27 UTC
