### ISSUE TITLE
Make dotnet build write errors to stderr

### ISSUE THREAD

**Issue by nothrow** [dotnet/cli#7114] opened 2017-07-10 11:09 UTC
Teamcity detects errors based on output to stderr. I believe (but I do not have older version installed anywhere) that `dotnet build` produced errors correctly, but now it does not.

## Steps to reproduce
```
using System;

namespace dotnet_errors
{
    public class Class1
    {
        uncompilable file
    }
}
```

`e:\tmp\dotnet_errors>dotnet build > stdout.txt 2> stderr.txt`

## Expected  behavior
`stderr.txt` to contain `Class1.cs(7,26): error CS1002: ; expected [e:\tmp\dotnet_errors\dotnet_errors.csproj]`

## Actual behavior
`stderr.txt` is empty, `stdout.txt` contents:

```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Class1.cs(7,26): error CS1002: ; expected [e:\tmp\dotnet_errors\dotnet_errors.csproj]

Build FAILED.

Class1.cs(7,26): error CS1002: ; expected [e:\tmp\dotnet_errors\dotnet_errors.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.85
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by jaredpar** [comment] 2017-07-10 17:23
This behavior is by design. The C# / VB compilers output their errors to stdout, never stderr. 

> Teamcity detects errors based on output to stderr.

Why do they not look at the exit code of the process? This is the standard way of checking for failed process execution.

**Comment by livarcocc** [comment] 2017-07-10 17:25
Since this is the default behavior of the compiler, I don't believe the CLI should attempt to change that. I am closing this issue.

**Closed by livarcocc** 2017-07-10 17:25 UTC
