### ISSUE TITLE
Dotnet 

### ISSUE THREAD

**Issue by Zudva** [dotnet/cli#11086] opened 2019-04-06 21:20 UTC
Hi!

I install virtualenv and virtualenvwrapper for work with OpenCV.

I write command: source ~/.bash_profile

And i have this report:
-bash: export: `Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/admin/Desktop/android:/Users/Master/.nexustools:/Users/admin/Desktop/android:/Users/Master/.nexustools': not a valid identifier

-bash: export: 

## OS X
`dotnet --info` output:
-bash: dotnet: command not found

I install  NET2.0 SDK and runtime.

**Comment by peterhuene** [comment] 2019-04-06 21:41
Hi @Zudva.

Can you show us the line it's erroring on from your `.bash_profile`?

`dotnet` should be on your PATH if you installed the SDK via the macOS installer.  Is that how you installed the .NET Core SDK?

**Comment by Zudva** [comment] 2019-04-07 17:28
> Can you show us the line it's erroring on from your .bash_profile?

`-bash: export: `Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/admin/Desktop/android:/Users/Master/.nexustools:/Users/admin/Desktop/android:/Users/Master/.nexustools': not a valid identifier
`

I install this file: dotnet-sdk-2.2.105-osx-gs-x64.pkg

**Comment by peterhuene** [comment] 2019-04-07 21:44
Hi @Zudva.  That seems to be the error from bash, but is there a corresponding line in your `.bash_profile`?

It seems like there's an export statement (I assume for `PATH`) in the file that is syntactically incorrect, but I'm not sure what the file contains.

If I had to guess, I think you have something like `export $PATH=...` instead of `export PATH=`.

**Comment by Zudva** [comment] 2019-04-07 23:16
> Hi @Zudva. That seems to be the error from bash, but is there a corresponding line in your `.bash_profile`?
> 
> It seems like there's an export statement (I assume for `PATH`) in the file that is syntactically incorrect, but I'm not sure what the file contains.
> 
> If I had to guess, I think you have something like `export $PATH=...` instead of `export PATH=...`.

Maybe i must write PATH for dotnet in ~/.bash_profile?

Now i have this:
source ~/.profile

export PATH=$PATH:~/.nexustools

export NVM_DIR="/Users/Master/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# Cuda lib
export DYLD_LIBRARY_PATH="/usr/local/cuda/lib":$DYLD_LIBRARY_PATH
export PATH="/usr/local/sbin:$PATH"

PATH=/usr/local/sbin:$PATH
# Homebrew
PATH=/usr/local/bin:$PATH
export PATH="/usr/local/opt/curl/bin:$PATH"
# Homebrew
export PATH=/usr/local/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/b$

**Comment by peterhuene** [comment] 2019-04-08 20:11
Hi @Zudva.

When you installed the .NET Core SDK via `dotnet-sdk-2.2.105-osx-gs-x64.pkg`, it should have created a file at `/etc/paths.d/dotnet` with the content `/usr/local/share/dotnet`.  This should automatically cause `/usr/local/share/dotnet` to be put on your `PATH`.

Is `/etc/paths.d/dotnet` present for you?

Given what you've pasted of your `.bash_profile`, I don't spot any inherent problems that might be the cause.  I'm able to source that content just fine.  To check, is the `b$` in the Python path intentional?  If so, it would be probably a good idea to escape the `$` with a backslash (i.e. `\$`) so that any additional characters added don't get treated as a variable.

**Comment by peterhuene** [comment] 2019-04-09 15:48
> How to delete this request?

I'm not sure I understand; which request are you referring to?

If `/usr/local/share/dotnet` is on your PATH already because the installer added it, you shouldn't need to export it again from your `.bash_profile`.

If uninstalling another piece of software corrupted your `.bash_profile` such that your PATH is no longer set correctly, you will need to repair your profile so that it does.  Unfortunately, unless that piece of software was the .NET Core SDK, we can only offer limited help.

**Comment by Zudva** [comment] 2019-04-09 17:47
after add: 
#Dotnet
export PATH="/usr/local/share/dotnet:$PATH"

command: "dotnet --info" work.

How to correct write this text to ~/.bash_profile? 

`~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands` 

Thank you!

**Comment by peterhuene** [comment] 2019-04-09 23:01
@Zudva I'm not sure I understand your question.  Your syntax for appending to the PATH for `dotnet` is correct (`export PATH=/usr/local/share/dotnet:$PATH`).  That should be all that is needed in your `.bash_profile`.

However, it shouldn't need to be added if `/usr/local/share/dotnet` is already on the PATH, which it should be if the installer modified the PATH and I believe you confirmed that to be the case.

What error are you running into?

**Comment by Zudva** [comment] 2019-04-10 08:08
This good.

`dotnet --info`
Yes, work now.

I have questions to this error in bash: `~/.dotnet/tools`

I want say, how to remove the error request to bash export?

Fussion.app delete now, but why does bash request this?

Thank you!

**Comment by peterhuene** [comment] 2019-04-10 17:09
@Zudva I'm glad `dotnet` is now working for you from the command line.

Regarding `~/.dotnet/tools` causing an error, can you paste the exact line you have that's causing the problem?

`export PATH=$PATH:~/.dotnet/tools` should work, however, the .NET Core SDK installer should also already be putting this on the PATH.

Regarding Fusion no longer being installed and still present on your PATH, perhaps it also puts a file in `/etc/paths.d`?  Unfortunately, I can't really help you with that.

**Comment by livarcocc** [comment] 2019-05-07 17:53
Closing this issue as this is now almost a month old without new activity.

**Closed by livarcocc** 2019-05-07 17:53 UTC
