### ISSUE TITLE
dotnet uses -? Sub commands use --help

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#1369] opened 2016-02-11 19:11 UTC
Should they be the same?

**Comment by blackdwarf** [comment] 2016-02-12 18:46
@Petermarcu yes.

**Comment by blackdwarf** [comment] 2016-02-23 14:55
@Petermarcu actually, this is by design. `dotnet -?` fails with "unknown option" which prompts it to display the usage info. This is true for any uknown option. Will close this, reopen if you think the behavior is not correct.

**Closed by blackdwarf** 2016-02-23 14:55 UTC
Labels: bug
