### ISSUE TITLE
--help: Document that the dotnet command can be used to run applications

### ISSUE THREAD

**Issue by dhasenan** [dotnet/cli#6330] opened 2017-04-16 01:24 UTC
## Steps to reproduce
`dotnet --help`

## Expected  behavior
The help message mentions the path-to-executable way of running `dotnet`, like when you just run `dotnet` without any arguments.

## Actual behavior
The help message does not mention that `dotnet` can run executables.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by svick** [comment] 2017-04-16 09:41
I think this is a duplicate of https://github.com/dotnet/cli/issues/6215.

**Comment by livarcocc** [comment] 2017-04-17 20:03
Correct. We are tracking an all out improvement to these messages.

**Closed by livarcocc** 2017-04-17 20:03 UTC
