### ISSUE TITLE
No dotnet-clean command

### ISSUE THREAD

**Issue by SeayXu** [dotnet/cli#3961] opened 2016-07-28 15:49 UTC
## Steps to reproduce
I want to clean built project.

## Expected  behavior
**Clean had been built project,for example,`bin` or `obj` directory**

## Actual behavior
no command,now

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment] 2016-07-28 18:11
Dupe of #3725

**Closed by blackdwarf** 2016-07-28 18:11 UTC
