### ISSUE TITLE
How to I use machine-wide prerelease CLI 2.0 side-by-side with 1.0?

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#5896] opened 2017-03-02 18:30 UTC
## Steps to reproduce
Start with a machine that has DotNET CLI 1.0.  I created a vm with base image Windows-10-VSWillow-d15rel-26228_00-Enterprise.

Install latest CLI from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe

From command prompt, run `dotnet --info`.

## Expected  behavior
It shows both of them along with instructions on how to choose which one?  Not sure best behavior here but I was confused that I couldn't use the thing I just installed.

## Actual behavior
Output only shows single version.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

If I examine the files on disk I see that the SDK and shared framework are both laid down in side-by-side version specific folders.  The host seems to have been a major upgrade where the new version is laid down in a version specific folder and the old version has been removed.

Relevant code appears to be here:
https://github.com/dotnet/core-setup/blob/a3aa7554141425971e82fb3e75d2431b3604a101/src/corehost/cli/fxr/fx_muxer.cpp#L566-L609

I set COREHOST_TRACE=1 and reran dotnet --version.  The relevant portion of the trace is as follows:
```
--- Resolving SDK version from SDK dir [C:\Program Files\dotnet\sdk]
Considering version... [.]
Considering version... [..]
Considering version... [1.0.0]
Considering version... [2.0.0-alpha-005156]
Checking if resolved SDK dir [C:\Program Files\dotnet\sdk\1.0.0] exists
Resolved SDK dir is [C:\Program Files\dotnet\sdk\1.0.0]
Found CLI SDK in: C:\Program Files\dotnet\sdk\1.0.0
Using dotnet SDK dll=[C:\Program Files\dotnet\sdk\1.0.0\dotnet.dll]
```

I found that the only way I could get the machine-wide dotnet.exe to pick up my new version was to create a global.json in a parent directory with the following:
```
{
    "sdk": {
        "version": "2.0.0-alpha-005156"
    }
}
```

After doing so I get the following from `dotnet --info`
```
.NET Command Line Tools (2.0.0-alpha-005156)

Product Information:
 Version:            2.0.0-alpha-005156
 Commit SHA-1 hash:  1cafd69f62

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-005156\
```

This may be desired behavior but we at least need to document how to choose the new SDK here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

Ideally there is also something a bit more intuitive in the tools that will lead you down the path of configuring your side-by-side SDK.

/cc @eerhardt @Petermarcu @gkhanna79 @piotrpMSFT

**Comment by livarcocc** [comment] 2017-03-02 18:36
@ericstj Given that all this logic lives in the host, I think we should move this bug to core-setup.

**Comment by ericstj** [comment] 2017-03-02 18:43
@livarcocc let's have the discussion here first since it applies to the CLI product.  If we decide on a specific change we can move this issue.

**Comment by blackdwarf** [comment] 2017-03-10 17:44
@ericstj this is by design, in a sense, I would say. We use `global.json` to specify a specific version of the tools to use. I understand that this is slightly confusing since the host prefers, IIUC, the released version over a higher preview version (1.0.0 over 2.0.0-*), but the configuration mechanism is still the same. 

This should be documented in the doc you mentioned, of course.

**Comment by gkhanna79** [comment] 2017-03-10 17:50
@blackdwarf Same as https://github.com/dotnet/core-setup/issues/1664

**Comment by livarcocc** [comment] 2019-05-14 17:25
I believe this has been fixed in the host.

**Closed by livarcocc** 2019-05-14 17:25 UTC
