### ISSUE TITLE
new web mvc project with v 2.0.0-preview1-final doesn't publish correctly out of the box

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/cli#6607] opened 2017-05-16 11:21 UTC
Hi, 
## Steps to reproduce
From VS2017 preview, create new dotnet web mvc -auth  Individual
```
Open command shell
dotnet publish -c debug
cd bin\Debug\netcoreapp2.0\publish
dotnet xxx.dll
```

## Expected  behavior
`Now listening on: http://127.0.0.1:50001`

## Actual behavior
`Unhandled Exception: System.IO.FileNotFoundException: Could not find file xxxxxbin\Debug\netcoreapp2.0\publish\urlRewrite.config'`

## Environment data
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

Thanks
-Vince

**Comment by livarcocc** [comment] 2017-05-16 18:03
@vijayrkn @mlorbetske can you guys take a look?

**Comment by livarcocc** [comment] 2017-05-16 20:13
Tagging @muratg here since he replied so quickly to the other issue I tagged him at 😄

**Comment by muratg** [comment] 2017-05-16 20:29
This is probably a template issue.  @mikaelm12, could you give it a try?

**Comment by mikaelm12** [comment] 2017-05-16 20:34
Yup. I'll take a look right now

**Comment by mikaelm12** [comment] 2017-05-16 21:12
Okay, so the issue is that the template uses the Url rewrite middleware and loads the enforce https rules from a urlRewrite config file. This config file isn't being copied into the publish output when the app is published. This is fixed by editing the properties of the urlRewrite.config file and changing the `Build Action` to `Content` and the `Copy to Output Directory Option` to `Copy always`.
This is a bug in the template.

We could also solve this by using code rules for the url rewrite middleware instead of the config file

**Comment by mlorbetske** [comment] 2017-05-16 21:18
@vijayrkn

**Comment by vijayrkn** [comment] 2017-05-16 21:22
Only the web.config is added to the Content glob.

https://github.com/aspnet/websdk/blob/dev/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L29

You can move this bug to websdk & we will include all *.config files to the content glob.

**Comment by vijayrkn** [comment] 2017-05-16 21:28
https://github.com/aspnet/websdk/pull/202

**Closed** 2017-05-16 23:03 UTC
