### ISSUE TITLE
dotnet build fails on Nano Server

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/cli#5081] opened 2016-12-19 11:17 UTC
## Steps to reproduce

- Install .NET Core on Windows Nano Server (I used the latest preview5 drops)
- Run the following commands:

```
dotnet new
dotnet restore
dotnet build
```

## Expected  behavior
- Build to complete successfully

## Actual behavior
```
C:\Program Files\dotnet\sdk\1.0.0-preview5-004275\Microsoft.Common.CurrentVersion.targets(1909,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. 

System.DllNotFoundException: Unable to load DLL 'mscoree.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

at Microsoft.Build.Tasks.NativeMethods.GetFileVersion(String szFullPath, StringBuilder szBuffer, Int32 cchBuffer, UInt32& dwLength)
at Microsoft.Build.Tasks.AssemblyInformation.GetRuntimeVersion(String path) 
at Microsoft.Build.Tasks.AssemblyInformation.IsWinMDFile(String fullPath, GetAssemblyRuntimeVersion getAssemblyRuntimeVersion, FileExists fileExists, String& imageRuntimeVersion, Boolean& isManagedWinmd) 
at Microsoft.Build.Tasks.Reference.set_FullPath(String value) 
at Microsoft.Build.Tasks.ReferenceTable.ResolveReference(AssemblyNameExtension assemblyName, String rawFileNameCandidate, Reference reference) 
at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName) at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryItems(ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, ArrayList exceptions) at Microsoft.Build.Tasks.ReferenceTable.ComputeClosure(DependentAssembly[] remappedAssembliesValue, ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, ArrayList exceptions) 
at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader) at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute() 
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() 
```

## Environment data
`dotnet --info` output:

```
[192.168.122.201]: PS C:\Program Files\dotnet> .\dotnet.exe --info
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

## Notes
- May be a duplicate of microsoft/msbuild#1233
- I tried to read the "Running .NET Core on Nano Server" section in the [readme](https://github.com/dotnet/core/blob/master/cli/known-issues.md#running-net-core-cli-on-nano-server), but apparently that section does not exist.

**Comment by jeffkl** [comment] 2016-12-19 16:08
Yes this is definitely a duplicate of Microsoft/msbuild#1233.  Unfortunately we hadn't tested on Nano server and we're discovering that we're making P/Invoke calls into functions that don't exist.  The solution has been to not use P/Invoke calls into Windows functions when running under .NET Core and instead using built-in .NET methods.  We hope to get Nano server squared away before Visual Studio 2017 ships but in the mean time feel free to sends us pull requests if you're able.

**Comment by qmfrederik** [comment] 2016-12-19 16:28
@jeffkl I can take a stab at a PR, I see there is already an alternative code path available (I assume that's used on Linux), if you can you let me know how to check for NanoServer in the codebase - do you already have a property for that? In that case, the PR would be trivial

**Comment by jeffkl** [comment] 2016-12-19 16:43
We generally introduce a feature flag and wrap the logic in a preprocessor block.  We build against "full framework" and .NET Core and would only add the constant for full framework which would have the related API.

You can use [this PR](https://github.com/Microsoft/msbuild/pull/1343/files) as a guide where were calling `RtlMemory` which wasn't available on Nano.  The code got further but then hit the code path you reported.  The big question is how many places we're calling something that isn't available on Nano server...

**Comment by qmfrederik** [comment] 2016-12-19 19:16
@jeffkl Thanks! Please have a look at Microsoft/msbuild#1495

**Comment by livarcocc** [comment] 2016-12-19 19:17
Given that this issue is in msbuild, should we close this one here in the CLI?

**Comment by qmfrederik** [comment] 2016-12-19 19:19
@livarcocc fine for me, if the PR is accepted in msbuild, anything that needs to be done to get dotnet/cli to use the latest version of msbuid? Or is that automatic?

**Comment by blackdwarf** [comment] 2016-12-20 07:45
@qmfrederik there is a process by which we would ingest a new version of MSBuild.

**Comment by qmfrederik** [comment] 2016-12-21 18:17
@blackdwarf Microsoft/msbuild#1495 was merged, what's required to get this fix in the cli packages? Something along the lines of #4889?

**Comment by livarcocc** [comment] 2016-12-21 18:29
Just find the right version of MSBuild and update it here: https://github.com/dotnet/cli/blob/rel/1.0.0/build/Microsoft.DotNet.Cli.DependencyVersions.props#L4

**Comment by piotrpMSFT** [comment] 2017-01-18 10:44
Fixed, so closing

**Closed by piotrpMSFT** 2017-01-18 10:44 UTC
