### ISSUE TITLE
Runtime configuration of .NET

### ISSUE THREAD

**Issue by UppaJung** [dotnet/cli#426] opened 2015-12-08 00:21 UTC
I need to be able to configuring the .NET runtime.  In my case I need to enable objects of size > 2GB, though presumably there are many other reasons one might one to do change runtime configuration parameters from their defaults.

Piotr (Peter Puszkiewicz <piotrp@microsoft.com>) explained that "we've not added runtime configuration to the host thus far" and asked me to file this issue.

**Comment by piotrpMSFT** [comment] 2015-12-14 23:49
This is a duplicate of #488. Let's track this there!

[yes, I know the other is a dupe, but since it has more traction let's still use it :)]

**Closed by piotrpMSFT** 2015-12-14 23:49 UTC
