### ISSUE TITLE
Ubuntu 16.04 Can't install dotnet

### ISSUE THREAD

**Issue by sabastiaan** [dotnet/cli#2962] opened 2016-05-09 19:44 UTC
~$ sudo apt-get install dotnet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.

This is the same issue that as posted in [`issue 308`](https://github.com/dotnet/cli/issues/308) however since ubuntu 16.04 is supposed to be supported I wonder what could be done to fix this?

**Comment by Sridhar-MS** [comment] 2016-05-09 19:48
Duplicate of https://github.com/dotnet/cli/issues/2957.
We are working on supporting the dotnet CLI on Ubuntu 16.04.

**Closed by Sridhar-MS** 2016-05-09 19:48 UTC
Labels: duplicate

**Comment by DasJott** [comment] 2016-05-31 06:42
You can download the missing lib from [here](http://packages.ubuntu.com/de/trusty/libicu52).

After installing you can apt-get install dotnet.
