### ISSUE TITLE
Remove "please" in error messages.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/cli#11336] opened 2019-05-14 19:47 UTC
Per the MS Style guide

Avoid please except in situations where the customer is asked to do something inconvenient or the application or site is to blame for the situation.

A search yields 864 lines with please. In almost every case, please should be removed.

Examples:

* ` <source>Found more than one project in `{0}`. Please specify which one to use.</source>`
*  `<source>Please specify at least one {0}.</source>`
* ` <value>Please specify one package reference to add.</value>`
*    Unable to generate a temporary file for project '{0}'. Cannot add package reference. **Please** clear the temp directory and try again.

I'd be  willing to help remove these.

**Comment by livarcocc** [comment] 2019-05-15 01:13
@Rick-Anderson We would gladly take a PR for this 😄.

cc @peterhuene

**Comment by peterhuene** [comment] 2019-05-15 04:25
Technically this is a dupe of https://github.com/dotnet/cli/issues/9203 which I never got around to scrubbing (I've been more monitoring new resource strings so we didn't add additional work).

**Comment by Rick-Anderson** [comment] 2019-05-15 04:51
I could probably PR this. Do I PR into master?

**Closed** 2019-05-17 21:02 UTC
Labels: good first issue, help wanted
