### ISSUE TITLE
dotnet tool install is not compliant with preview

### ISSUE THREAD

**Issue by tebeco** [dotnet/cli#9407] opened 2018-06-03 17:23 UTC
## Steps to reproduce
* push a `dotnet tool` as preview on nuget.org (no stable release)
* try to install it without specifying the version ... since version resolution should be done by nuget

## Expected  behavior
Install the latest pre-release if there's only pre release

## Actual behavior
The package is not even detected ....

## Environment data
`dotnet --info` output :
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17677
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

![image](https://user-images.githubusercontent.com/2266487/40889196-04efcfa0-6763-11e8-879f-ca453d6e7c66.png)

```
error NU1103: Unable to find a stable package fake-cli with version
error NU1103:   - Found 4 version(s) in nuget.org [ Nearest version: 5.0.0-rc015.196 ]
error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error NU1103:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder
error NU1103:   - Found 0 version(s) in CliFallbackFolder
The tool package could not be restored.
Tool 'fake-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

### ugly and broken workaround :
```
  dotnet tool install fake-cli ^
    --tool-path ./foobar ^
    --version 5.0.0-rc*
```

* Ugly, because : i have to deal with version when nuget should do that so if a v6 appear for ... reason, this will also break
* Broken, because : 
https://github.com/dotnet/cli/issues/9409
https://github.com/dotnet/cli/issues/9408

**Comment by livarcocc** [comment] 2018-06-04 17:35
I believe this is a duplicate of https://github.com/dotnet/cli/issues/8485, where we discuss supporting installing preview versions of packages.

**Closed by livarcocc** 2018-06-04 17:35 UTC

**Comment by tebeco** [comment] 2018-06-05 06:07
would be really great thx a lot for that info
