### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '/Users/liangjingtang/Documents/workspace/program/net./myApp/bin/Debug/netcoreapp2.0/myApp.dll'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by JingLMalan** [dotnet/cli#8007] opened 2017-11-14 03:21 UTC
## Steps to reproduce
I install dotnet platform, and it succeed.
`JingMalans-MacBook-Pro:myApp liangjingtang$ dotnet --version
2.0.2`
First step: I create a new project: 
`dotnet new console -o myApp
cd myApp`
It also restores succeeded.
Then: I build this test project.
`dotnet build`
It also tells me that Build succeeded.
At last: I run it.
`dotnet run`
message:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '/Users/liangjingtang/Documents/workspace/program/net./myApp/bin/Debug/netcoreapp2.0/myApp.dll'. The system cannot find the file specified.

What's the matter with it?
## Expected  behavior
Run
## Actual behavior
Unhandled Exception

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by dasMulli** [comment] 2017-11-14 04:05
Seems to be reproducible for every built application when any directory in the hierarchy ends with a dot.

```
$ dotnet exec /Users/martin/tmp/net/tmp./testcons/bin/Debug/netcoreapp2.0/testcons.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '/Users/martin/tmp/net/tmp./testcons/bin/Debug/netcoreapp2.0/testcons.dll'. The system cannot find the file specified.

Abort trap: 6
```

**Comment by livarcocc** [comment] 2017-11-14 17:47
Moving this to core-setup, as this seems like a host issue. @steveharter, please let us know if there is something here that we can do in the CLI/SDK.

**Comment by livarcocc** [comment] 2017-11-14 17:47
This issue was moved to dotnet/core-setup#3410

**Closed by livarcocc** 2017-11-14 17:47 UTC
