### ISSUE TITLE
'dotnet run' is slow

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#8178] opened 2017-12-07 04:27 UTC
_From @perlun on December 6, 2017 21:30_

Hi,

Even on a minimal console application, `dotnet run` takes about 4s on my MacBook Pro:

```
$ time dotnet run

real	0m4.670s
user	0m3.668s
sys	0m1.249s
```

If I run the `.dll` from my project instead, it's much faster:

```
$ time dotnet bin/Debug/netcoreapp2.0/electronsharp-poc.dll

real	0m0.070s
user	0m0.039s
sys	0m0.027s
```

Is this expected, or is there any way to make it faster? The `.csproj` file is for a blank project I just created, I'll include it here for reference:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

_Copied from original issue: dotnet/coreclr#15403_

**Comment by jkotas** [comment] 2017-12-07 04:27
_From @fiigii on December 6, 2017 23:14_

@perlun Could you try `dotnet run -c release`? AFAIK, `dotnet run` builds programs with `debug` mode by default.

**Comment by livarcocc** [comment] 2017-12-07 05:46
Duplicate of https://github.com/dotnet/cli/issues/7610.

However, `dotnet run` is not equivalent of dotnet <your_dll>.dll.

`dotnet run` is a development time tool that restores (if necessary), builds (if necessary) and the determines the command to run to invoke your under development app and then, finally, invokes your application. Which is why there is a time difference between the two. Having said that, we are investigating and making many perf improvements in the CLI for our next release, which will improve this scenario as well.

**Closed by livarcocc** 2017-12-07 05:46 UTC

**Comment by perlun** [comment] 2017-12-07 06:50
> Duplicate of #7610

Thanks! I searched briefly before posting the issue, but in the coreclr repo so I was looking at the wrong place...

> However, dotnet run is not equivalent of dotnet <your_dll>.dll.
> 
> dotnet run is a development time tool that restores (if necessary), builds (if necessary) and the determines the command to run to invoke your under development app and then, finally, invokes your application. Which is why there is a time difference between the two.

True, but the time difference is still a bit too high IMHO. I tried with `release` btw, it was still around 3 seconds. Anyhow, let's continue in #7610 if needed.

```shell
$ dotnet --version
2.0.0
```
