### ISSUE TITLE
I can not run any dotnet tool installed with --tool-path

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/cli#12072] opened 2019-07-29 22:27 UTC
I am trying to configure my build environment to download and run my tools in a local directory so I dont blow up anyone elses builds. I have tried all of the following:

```powershell
PS C:\Users\toryb\Desktop\build_server> dotnet tool install dotnetsay --tool-path tools
You can invoke the tool using the following command: dotnetsay
Tool 'dotnetsay' (version '2.1.4') was successfully installed.
PS C:\Users\toryb\Desktop\build_server> dotnetsay
dotnetsay : The term 'dotnetsay' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnetsay
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnetsay:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\toryb\Desktop\build_server> dotnet dotnetsay
No executable found matching command "dotnet-dotnetsay"
PS C:\Users\toryb\Desktop\build_server> dotnet .\tools\dotnetsay.exe
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\toryb\Desktop\build_server\tools\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\Users\toryb\Desktop\build_server\tools\dotnetsay.runtimeconfig.json file specifying the appropriate framework.
PS C:\Users\toryb\Desktop\build_server> # ... wtf
PS C:\Users\toryb\Desktop\build_server> $env:path = "${pwd}\tools;" + $env:path;
PS C:\Users\toryb\Desktop\build_server> dotnet dotnetsay
No executable found matching command "dotnet-dotnetsay"
PS C:\Users\toryb\Desktop\build_server>
```

You can see nothing I try works. This is with a fresh install of the latest core. I even try and set the `env:path`.

Should I be installing the tool differently in order to use it in my build environment?

**Comment by peterhuene** [comment] 2019-07-29 22:40
Hi @VictorioBerra.  Thank you for reporting this issue to us.

You can run the app with `.\tools\dotnetsay.exe` or after you add it to your path, simply `dotnetsay`.

As the tool is not prefixed with `dotnet-` (e.g. `dotnet-dotnetsay`), it can't be run as `dotnet dotnetsay`, only as `dotnetsay`.

I'm going to close this issue as by design.  If neither of the above solutions work for you, please reopen this issue and provide any additional information you feel might be relevant for reproducing the issue.  Thanks!



Ple

**Closed by peterhuene** 2019-07-29 22:40 UTC
