### ISSUE TITLE
Manually Uninstall .NET Core SDK 2.2.0-Preview and 15.5.0-Preview Nightly Builds

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#8652] opened 2018-02-21 02:11 UTC
# Manually Uninstall .NET Core SDK 2.2.0-Preview and 15.5.0-Preview Nightly Builds

[A change in the version number strategy for .NET Core SDK](https://github.com/dotnet/designs/pull/29) resulted in some nightly builds having a higher version number. This higher version number will block the installation of the correct .NET Core SDK.

If you have installed nightly builds of the .NET Core SDK that start with version number that begin with `2.2.0-preview1` or `15.5.0-preview`, you must manually uninstall these preview builds before later versions of the SDK with version numbers like 2.1.xxx will be available. This may have occurred by installing nightly builds of the .NET Core SDK or concurrent nightly builds of Visual Studio previews.

## Details

[We changed the version number strategy for .NET Core SDK](https://github.com/dotnet/designs/pull/29) as development was ongoing. Because of this, version numbers on the old scheme appeared in nightly builds. Unfortunately, these numbers are higher than the version numbers in the new scheme. All of the newer SDKs for .NET Core 2.1 will be ignored due to this higher version number; this includes newer nightly builds, public previews and eventual releases.

These older version numbers are similar to the following, with the last several different values in the last six digits:

```
2.2.0-preview1-008000
15.5.0-preview-007082
```

Since the newer versions are in the form:

```
2.1.300-preview1-008000
```

## Call to Action

If you have installed nightly builds, please uninstall any .NET SDK versions that start with `2.2.0-preview1` or `15.5.0-preview`.

**Comment by livarcocc** [comment] 2018-02-22 20:45
I thought we were going to put this in announcements.  In any case, is it OK to close the issue, since there are no changes to be made in the product?

**Comment by KathleenDollard** [comment] 2018-02-23 20:41
We put close comments in announcements and send people to the repo issue to discuss. 

So, I want to leave this open for now. 

Make sense?

**Comment by livarcocc** [comment] 2018-05-11 23:00
@KathleenDollard I think this has been time enough now, yes? I am going to close the issue. If you disagree let me know and I can re-activate.

**Closed by livarcocc** 2018-05-11 23:00 UTC

**Comment by juniwang** [comment] 2018-07-05 08:39
Finally I find the cause why I cannot install the latest 2.1.3 SDK. That's because I have `2.2.0-preview1-007840` installed. But can you tell me how to manually uninstall it please? I tried to run the downloaded MSI file, but it's still there.
