### ISSUE TITLE
dotnet corrutps paths which end with slash

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1216] opened 2016-02-04 00:56 UTC
I see process explorer that corehost is a child process of dotnet. dotnet is invoked like this:

`"dotnet"  "publish-iis" "--publish-folder" "C:\temp\HelloMvc\"`

but the corehost is invoked like this:

`"C:\Users\pawelka\AppData\Local\Microsoft\dotnet\cli\bin\corehost.exe" "C:\Users\pawelka\.nuget\packages\dotnet-publish-iis\1.0.0-t02\lib\dnxcore50\dotnet-publish-iis.dll" "--publish-folder" "C:\temp\HelloMvc\""`

notice that the publish-folder parameter ends now with two `"` which results in:

```
System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Microsoft.AspNetCore.Tools.PublishIIS.PublishIISCommand.Run()
   at Microsoft.AspNetCore.Tools.PublishIIS.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Tools.PublishIIS.Program.Main(String[] args)
```
down the road.

**Comment by moozzyk** [comment] 2016-02-04 01:22
I wonder if this can be related to this: https://github.com/dotnet/cli/blob/a7f438f85d5a68c8f4c61bb422c39bbf3c1e1822/src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs#L203

**Comment by moozzyk** [comment] 2016-02-04 01:23
```Console.WriteLine(ArgumentEscaper.EscapeAndConcatenateArgArrayForProcessStart(new[] {@"C:\temp\" }));```

results in: `"C:\temp\\"` which is not correct

**Comment by livarcocc** [comment] 2016-02-04 02:15
@moozzyk May be related to this as well: #2957. I remember me and @brthor tried this by calling a dotnet command directly with a path ending in \, we saw a wrong string coming in directly on the string[], so before we could do any processing to it.

**Comment by livarcocc** [comment] 2016-02-04 02:29
@moozzyk Actually, I just tried the issue above and couldn't repro anymore. This seems like separate problem.

**Comment by moozzyk** [comment] 2016-02-04 19:38
@livarcocc - I will investigate this today.

**Comment by moozzyk** [comment] 2016-02-09 03:29
The issue here is that if an exe is being executed via cmd the arguments needs to be escaped first for exe and then for cmd. In addition currently the code [always put quotes around args](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs#L203) (if they are not already escaped) which causes additional problems - e.g. this corrupts cmd arguments that already contain a quote but don't have whitespaces. 
Finally the ShouldSurroundArgument function is used for both cmd and Process Start escaping but the rules for escaping between the two are different - I guess returning always true was supposed to hid the difference but it actually breaks more things that it fixes (vide #1036).

**Comment by brthor** [comment] 2016-02-09 17:58
@moozzyk 
The intent of the code in ShouldSurroundArgument is not to put quotes around args which are already quoted.

There is also separate logic for escaping cmd and process.Start Args.
https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs#L85
https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs#L144

The tests for these two code paths are here:
https://github.com/dotnet/cli/blob/rel/1.0.0/test/ArgumentForwardingTests/ArgumentForwardingTests/ArgumentForwardingTests.cs

The tests mock the scenarios by starting processes and should be robust, but please point out any issues there :smile:

**Comment by brthor** [comment] 2016-02-09 20:43
@moozzyk 
```
Console.WriteLine(ArgumentEscaper.EscapeAndConcatenateArgArrayForProcessStart(new[] {@"C:\temp\" })); 

results in:  "C:\temp\\"  which is not correct
```

Can you point out why this is not correct?
This is accounting for rules here: 
https://msdn.microsoft.com/en-us/library/a1y7w461.aspx

This test case should cover this scenario:
https://github.com/dotnet/cli/blob/rel/1.0.0/test/ArgumentForwardingTests/ArgumentForwardingTests/ArgumentForwardingTests.cs#L66

Admittedly there should probably be a more direct test case here.

I think the issue is here:
`"dotnet" "publish-iis" "--publish-folder" "C:\temp\HelloMvc\"`
should be 
`"dotnet" "publish-iis" "--publish-folder" "C:\temp\HelloMvc\\"`
Otherwise the quote is treated as escaped and will be included in string[] args.

**Comment by brthor** [comment] 2016-02-10 01:10
@moozzyk 

I created a c++ test project to test how deep this issue goes:
```
#include <iostream> 
using namespace std;

int main(int argc, char* argv[]) {
	cout << "argc = " << argc << endl;
	for (int i = 0; i < argc; i++)
		cout << "argv[" << i << "] = " << argv[i] << endl;
	int i;
	cin >> i;
	return i;
}
```
The Output when supplied with arg string: `"C:\some\path\" something else`

```
argc = 2
argv[0] = c:\users\brthor\documents\visual studio 2015\Projects\Project1\Debug\Project1.exe
argv[1] = C:\some\path" something else
```

This is an issue deeper than the cli, which I think is rooted here:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx

**Comment by moozzyk** [comment] 2016-02-10 02:08
The rules for escaping for cmd are different from the rules for used by `CommandLineToArgvW`. Quotes are especially difficult. If you escape " by "" and then use this to pass to an exe you are corrupting the arguments. Another issue is that if you have an argument ending with '\' and we always escape it you first end up with: ^"^C^:^\^t^e^m^p^\^" then it will get collapsed by cmd to "C:\temp\" but then CommandLineToArgvW will interpret the trailing slash as an escape character for qoute so it will unescape it and you end up as `C:\temp"`. 
The issues with the current code (aside that this is a really hard problem) I found so far were: 
- for Process.Start we were always escaping if the arg was already in quotes 
- we always wanted to add quotes even if they were not necessary (e.g. for Process.Start you need quotes and escaping only if the argument contains specific characters)
- we were always escaping " with "" which breaks if you run exe via cmd (e.g. scripts)
- we were always adding quotes to the program name (but it is a separate issue - #1306)

I hacked a prototype (it's quite dirty and some comments are not correct) - it fixes many of the issues above. One thing it does is to check if exe is being run via cmd and if it is it escapes args for process start first and then it escapes parameters for cmd except for escaping " with "". Let's discuss it tomorrow. You can find it here: https://github.com/dotnet/cli/commit/83a32575bec7544bc43ebb795d1a0d9012572269
(all tests passed)

**Comment by brthor** [comment] 2016-02-10 18:27
I'll take a look.

This is a tough problem and I feel a simpler fix may be not to run .exe files through cmd /c when using the scriptexecutor. That whole scenario is admittedly not tested in the ArgumentEscaper because the general case is only to use cmd /c for .cmd files.

What do you think of this?

**Comment by moozzyk** [comment] 2016-02-10 19:14
I think escaping is hard :smile:

**Comment by brthor** [comment] 2016-02-10 19:36
After our chat here's a summary of the changes we discussed:

1. Don't always quote everything (bugfix)
2. Make corresponding escaping logic changes where necessary for things which aren't quoted
3. Don't always use cmd /c for the ScriptExecutor, only use it for built in commands and .cmd or .bat files

Let me know if I missed something. Thanks for the great feedback on all of this!

**Comment by moozzyk** [comment] 2016-02-10 19:55
I think there was one more - don't double escape quotes added by the cmd escaper to quote the arg.

**Comment by brthor** [comment] 2016-02-10 19:57
Ah yes, and just let unbalanced quotes fail right?

**Comment by moozzyk** [comment] 2016-02-10 20:14
I think so.

**Closed** 2016-02-12 20:38 UTC
Labels: in progress
