### ISSUE TITLE
dotnet publish failed for SCD : Unable to copy the project dlls and documentation files

### ISSUE THREAD

**Issue by ajopjo** [dotnet/cli#10310] opened 2018-11-09 18:27 UTC
# Issue 
dotnet publish from CLI fails with error message 

**error MSB3030: Could not copy the file "obj\Release\netcoreapp2.1\win-x64\Inventory.pdb"**
**error MSB3030: Could not copy the file "obj\Release\netcoreapp2.1\win-x64\Inventory.dll**
**error MSB3030: Could not copy the file "bin\Release\netcoreapp2.1\win-x64\Inventory.xml**

## Behavior from Visual studio publish
*VS publish copies the application files (pdb, dlls, xml...) at one level below $(PublishDir) and the SCD publish works as expected. 
![image](https://user-images.githubusercontent.com/15382196/48280082-2a9bc600-e418-11e8-8ff1-5ddc263b1d34.png)

## Hack for CLI publish
If I write a prepublish script and copy the dll, pdb and xml to onle level below $(PublishDir), the self contained publish will work from dotnet cli.

## Additional Data
dotnet --info 
 1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

**Step: 1**
dotnet build
Build succeeded.
    0 Warning(s)
    0 Error(s)

**Step 2:**
This command ran from the the folder where the *.csproj resides
**_dotnet publish -c Release -r win-x64 --self-contained -o D:\Test\Publish\inventoryService_**

**Error:**
C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(168,5): error MSB3030: Could not copy the file "obj\Release\netcoreapp2.1\win-x64\Inventory.pdb" because it was not found. [<<Removedpath>>\inventory\Inventory.csproj]
C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(168,5): error MSB3030: Could not copy the file "obj\Release\netcoreapp2.1\win-x64\Inventory.dll" because it was not found. [<<Removedpath>>\inventory\Inventory.csproj]
C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(168,5): error MSB3030: Could not copy the file "bin\Release\netcoreapp2.1\win-x64\Inventory.xml" because it was not found. [<<Removedpath>>\inventory\Inventory.csproj]

**csproj file settings (using shared assembly info) edited for clean look**

-  TargetFramework- netcoreapp2.1
-  AssemblyName Inventory
-   RootNamespace Inventory
-   GenerateAssemblyInfo>false
-   GeneratePackageOnBuild>true
-  GenerateAssemblyCompanyAttribute>false
-   GenerateAssemblyCopyrightAttribute>false
-   GenerateAssemblyFileVersionAttribute>false
- GenerateAssemblyInformationalVersionAttribute>false
-  GenerateAssemblyVersionAttribute>false

**Comment by livarcocc** [comment] 2018-11-09 18:29
Can you share a csproj with us? Or better yet, a repro repo. I don't quite follow why this would be failing.

**Comment by ajopjo** [comment] 2018-11-09 18:31
@livarcocc  Since its an enterprise project, I'm not able to upload in a public share. I'll create a clone using the same csproj settings and share

**Comment by ajopjo** [comment] 2018-11-09 20:58
@livarcocc please find the repo from https://github.com/ajopjo/dotnetpublishrepo.
I tried to remove most of the code and create a clone. 
Don't use Visual Studio Publish. I ran the below command from the location where csproj file resides
dotnet publish -c Release -r win-x64 --self-contained -f netcoreapp2.1

**Comment by samuelcadieux** [comment] 2019-03-05 16:12
Just leaving a note that we're seeing a similar issue on our end. Publishing from visual studio produce the expected result but not from the command line.
```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2019-03-11 23:55
I see you are setting `GeneratePackageOnBuild` to true. The issue here is that you are setting that property and trying to publish the application. When you set that property, you indicate that your app is a library and is being packaged, which is why it does not work.

If you really need that, then maybe condition on the presence of a RuntimeIdentifier, if that's the only publish case you need.

@peterhuene can you think of something else we could do here? Would your NoBuild error help diagnose this case?

**Comment by peterhuene** [comment] 2019-03-12 00:05
As @livarcocc noted, the problem is that `GeneratePackageOnBuild` will set `NoBuild` to `true` in the pack targets file, which causes the `Publish` target to not depend on the `Build` target, thus no build occurs and the publish cannot succeed unless the output is present from a previous build.

I've filed https://github.com/NuGet/Home/issues/7801 to track not doing it this way.

As a workaround, you should be able to pass `/p:NoBuild=false` to your `dotnet publish` command to prevent the pack targets from inadvertently disabling the build.

**Comment by livarcocc** [comment] 2019-03-12 00:10
@peterhuene can we close this one or is there some work on our side you want to track using this?

**Comment by peterhuene** [comment] 2019-03-12 00:11
I think we can close it, so I'll do so in favor of the NuGet issue.

Once that is resolved, you should be able to publish with `GeneratePackageOnBuild` set to `true`.

**Closed** 2019-03-12 00:11 UTC

**Comment by ajopjo** [comment] 2019-03-13 01:35
Thank you for the workaround and looking forward to fix this  behavior
