### ISSUE TITLE
`dotnet run` regressed in supporting multiple operands

### ISSUE THREAD

**Issue by dleeapho** [dotnet/cli#2643] opened 2016-04-22 16:29 UTC
## Steps to reproduce
Create a command-line app that accepts more than one argument (eg. "Hello" -p) try to a pass the arguments as operands the `run` command, ie your command-line app. 

## Expected  behavior
Previously, `dotnet run` syntax was:
```usage: dotnet [-f <arg>] [-c <arg>] [-p <arg>] [-h] [--] <args>...

    -f, --framework <arg>        Compile a specific framework
    -c, --configuration <arg>    Configuration under which to build
    -p, --project <arg>          The path to the project to run
                                 (defaults to the current directory).
                                 Can be a path to a project.json or a
                                 project directory
    -h, --help                   Help for compile native.
    <args>...                    Arguments to pass to the executable or
                                 script```
so the `--` served to separate the args to `run` from the operands to pass to the app.

## Actual behavior
```
dotnet run "Hello" -p
Specify --help for a list of available options and commands.
Missing value for option 'project'
```
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by eerhardt** [comment] 2016-04-22 19:32
This caused by removing System.CommandLine and using the DNX command line parser instead.  #2594.  I'll get a fix for this.

Also - we need a test.  :)

**Comment by eerhardt** [comment] 2016-04-26 20:06
@Petermarcu approved in email.

**Closed** 2016-04-27 04:01 UTC
Labels: --approved, in progress

**Comment by PinpointTownes** [comment] 2016-04-28 08:31
@eerhardt FYI, it's probably not the only regression, as this syntax no longer works:

```
dotnet run server.urls=http://localhost:53507/ --framework net451
```

This one does, though:

```
dotnet run --framework net451 server.urls=http://localhost:53507/
```

**Comment by eerhardt** [comment] 2016-04-28 14:32
@PinpointTownes - this behavior is by design.  The first syntax is incorrect according to:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02

> Guideline 9:
All options should precede operands on the command line.

It may have worked before, but it wasn't intended to work.

**Comment by PinpointTownes** [comment] 2016-04-28 15:12
Well, it's not really incorrect since specifying operands/arguments before options is just "recommended", not mandatory (it's a *should*, not a *must*). And IIRC, the command lines stack already goes beyond what POSIX requires (e.g double dash support).

The "old" syntax feels more natural (IMHO) and is supported by many programs like git or all the GNU utilities.

**Comment by eerhardt** [comment] 2016-04-28 15:20
Feel free to log a separate issue, as the scenario you are asking for is in direct conflict with this issue.

This issue says:

> Create a command-line app that accepts more than one argument (eg. "Hello" -p) try to a pass the arguments as operands the run command, ie your command-line app.

>Actual behavior
> dotnet run "Hello" -p
Specify --help for a list of available options and commands.
Missing value for option 'project'

You are asking to allow `-p` after "Hello". If that was allowed, failing for an empty `-p` argument would be the correct behavior.

**Comment by PinpointTownes** [comment] 2016-04-28 15:37
I created a separate ticket: https://github.com/dotnet/cli/issues/2728 :smile:

**Comment by smbecker** [comment] 2016-04-28 16:19
Will the fix here also apply to `dotnet test` because it would be nice to be able to send command line arguments into the test runner as well?

**Comment by eerhardt** [comment] 2016-04-28 18:10
> Will the fix here also apply to dotnet test because it would be nice to be able to send command line arguments into the test runner as well?

The fix of allowing `--` separator was only applied to `dotnet run`.

However, you were and still are able to pass command line arguments into the test runner through `dotnet test`, it's just `dotnet test --help` doesn't say you can (#1549).

For example, if you are using xunit you can say:

```
dotnet test -method Full.Method.Name
```

to just run a single method.
