### ISSUE TITLE
Error NETSDK1005 temporarily fires when switching TF

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#10989] opened 2019-03-18 17:00 UTC
## Steps to reproduce

1. Create a netcoreapp3.0 console application
1. Ensure the error list is visible 
1. Open the project file for editing 
1. Change the `TargetFramework` value to net472
1. Save All

## Expected  behavior
No errors

## Actual behavior
Briefly a NETSDK1005 error will appear in the error list. It seems to disappear as soon as auto-restore kicks in. 

This error is causing the Roslyn team issues as it breaks our integration tests. They are keyed to fail on any error and even this transient one is considered. There are work arounds but they end up causing us to more globally suppress NETSDK1005 which we'd like to avoid.

**Comment by livarcocc** [comment] 2019-03-18 17:52
I think this issue belongs in the project system actually. Do you want to move it or would you like me to?

**Comment by jaredpar** [comment] 2019-03-18 20:47
@nguerrera and I had chatted about this privately. He said he was going to take a quick look and re-route to project system if the issue was there.

**Comment by nguerrera** [comment] 2019-03-18 21:29
@jaredpar mentioned that this only started being observed after the move to 3.0 sdk, which leads me to think that the regression is in the SDK.

We have code that prevents errors in design-time builds when no assets file is present, but nothing to stop an out-of-date assets file with the wrong tfm from doing so. Logically, these should be handled equivalently. I am not seeing how this worked in 2.0. I suspect there has always been a race and something has changed the timing, but I need to look at it more carefully.

I think we need to fix this in the SDK.

**Comment by nguerrera** [comment] 2019-06-04 17:20
Duplicate of dotnet/sdk#2322

**Comment by nguerrera** [comment] 2019-06-04 17:20
This was fixed by dotnet/sdk#3268

**Closed by nguerrera** 2019-06-04 17:20 UTC
