### ISSUE TITLE
dotnet migrate doesn't delete project.lock.json

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#4816] opened 2016-11-22 23:05 UTC
## Steps to reproduce
Execute `dotnet migrate` on an xproj/`project.json` project.

## Expected  behavior
The `project.lock.json` file is either deleted or moved to the `backup` folder.

## Actual behavior
The `project.lock.json` file is left in place.

## Environment data
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment] 2016-11-23 00:44
Duplicate of https://github.com/dotnet/cli/issues/4753.

**Closed by livarcocc** 2016-11-23 00:44 UTC
