### ISSUE TITLE
dotnet publish -c Release -r ubuntu.14.04-x64 create invalid executable

### ISSUE THREAD

**Issue by fanoI** [dotnet/cli#8839] opened 2018-03-18 17:23 UTC
## Steps to reproduce
Follow the instructions here: https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli but change RuntimeIdentifiers in this way:

```xml
<RuntimeIdentifiers>win10-x64;osx.10.11-x64;ubuntu.14.04-x64</RuntimeIdentifiers>
```

## Expected  behavior
The SCD file created in bin\Release\netcoreapp2.0\ubuntu.14.04-x64 is a valid Linux ELF binary and it is correctly executed

## Actual behavior
Linux refuses to execute it:

>$ ./SCD
>bash: ./SCD: cannot execute binary file: Exec format error

## Environment data
`dotnet --info` output:

>Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

>Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

>Microsoft .NET Core Shared Framework Host

  >Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

Linux version:
>$ cat /etc/issue
Ubuntu 14.04 LTS \n \l

**Comment by svick** [comment] 2018-03-18 18:16
Are you sure you copied the right files and that the files weren't somehow damaged during the transfer? What does running `file SCD` say?

Also, when you want to copy an SCD app to another machine, you need to use the files in the `publish` directory (in your case, `bin\Release\netcoreapp2.0\ubuntu.14.04-x64\publish`). Though the error you're getting doesn't sound like it would be caused by this.

**Comment by fanoI** [comment] 2018-03-18 18:53
I've used a zip archive so yes the files have been correctly transferred.
Trying to execute the SCD in ubuntu.14.04-x64 or in publish directory gives the same error.

I find a little confusing that there are two SCD files by the way.

**Comment by dasMulli** [comment] 2018-03-18 22:37
@fanoI is the target system by any chance a 32bit ubuntu system? or even an ubuntu ARM version?

**Comment by fanoI** [comment] 2018-03-19 00:09
Effectively it is! x86 is not supported right?

**Comment by dasMulli** [comment] 2018-03-19 00:38
not for linux. and this is why running `*-x64` output won't ever work on x86

**Comment by fanoI** [comment] 2018-03-19 09:47
I was sure to be in a x64 Linux host :-(

It is working perfectly on a Cent OS 7 x64 indeed.
I need to find a x64 Ubuntu but I'm pretty sure it is working.

**Comment by livarcocc** [comment] 2018-03-19 18:03
Ok, given the above, I am going to close this issue.

**Closed by livarcocc** 2018-03-19 18:03 UTC
