### ISSUE TITLE
dotnet migrate command not installed on Mac 

### ISSUE THREAD

**Issue by thegame8714** [dotnet/cli#5392] opened 2017-01-19 13:40 UTC
## Steps to reproduce
I've downloaded the .NET Core SDK installer from this link https://www.microsoft.com/net/core#macos
and I've followed the process. All good, no error. 

## Expected  behavior
I'm expecting the dotnet migrate command to run normally

## Actual behavior
When I try to run the command ``dotnet migrate``  I receive the following error
``No executable found matching command "dotnet-migrate"``

## Environment data
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

```

**Comment by DustinCampbell** [comment] 2017-01-19 14:08
The problem is that the dotnet migrate command is only in more recent builds of recent builds of the .NET CLI. 'preview2' builds only support project.json and don't have the migrate command. If you want to try the latest and greatest, you can install a recent build from the front page of this repo (or directly from [here](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-osx-x64.latest.pkg)).

**Comment by thegame8714** [comment] 2017-01-19 14:50
Thank you very much, it did work fine

**Comment by blackdwarf** [comment] 2017-01-19 16:10
Since this is the solution, closing the issue.

**Closed by blackdwarf** 2017-01-19 16:11 UTC
