### ISSUE TITLE
`dotnet restore` doesn't work on a fresh osx install

### ISSUE THREAD

**Issue by ctide** [dotnet/cli#786] opened 2016-01-11 17:39 UTC
Under the 1.0.1-beta-23516 (I believe, `dotnet` says 1.0.0, but running dnu restore references this version in the project.lock.json file) version of the dotnet tools, dotnet restore doesn't work:

```
~  ᐅ dotnet restore
No executable found matching command "dotnet-restore"
```

There is a `dotnet-restore` executable located in `/usr/local/share/dotnet/bin` and other dotnet commands, such as `dotnet new`, do work. `dotnet run`, doesn't work either, saying it can't find the executable `csc`.

**Comment by spencerhakim** [comment] 2016-01-11 18:49
+1'ing this, although I get `﻿﻿﻿No executable found matching command "dotnet-dnx"` when running `dotnet restore`.

**Comment by brthor** [comment] 2016-01-11 19:14
Is this installed via the PKG? Also what version of OSX are you on?

**Comment by ctide** [comment] 2016-01-11 19:35
Via PKG, yes, both on El Capitan and on Yosemite.

**Comment by spencerhakim** [comment] 2016-01-11 20:42
Installed via the pkg linked on the dotnet.github.io, running El Capitan.

**Comment by brthor** [comment] 2016-01-11 20:57
@ctide Can you post the result of `ls /usr/local/share/dotnet/bin` and `ls -l /usr/local/bin | grep dotnet` (Not sure if OSX has grep by default, but I want to see what symlinks are there)

**Comment by ctide** [comment] 2016-01-11 20:59
I had to actually revert back to the older version, as I'm teaching a class
today on c#. If no one else posts it, I'll switch to the newer version
later tonight and can post the output of those.

**Comment by blackdwarf** [comment] 2016-01-11 23:28
Same here. The problem is in lacking symbolic link for dotnet-dnx binary in the postinstall step. Adding that symlink makes the thing work.

**Comment by jwhitmarsh** [comment] 2016-01-12 17:04
There's a symlink to csc missing too, fixed on my setup with:

```
ln -s /usr/local/share/dotnet/bin/dotnet-dnx /usr/local/bin/
ln -s /usr/local/share/dotnet/bin/csc /usr/local/bin/
```

Fresh install on OSX: 
```
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
```

**Comment by blackdwarf** [comment] 2016-01-12 17:41
@brthor when did we add a csc executable? I thought we only needed dotnet-compile-csc in the PATH for compile to work?

**Comment by stefanoric** [comment] 2016-01-13 12:47
+1

**Comment by kkoning** [comment] 2016-01-13 18:35
I still had problem after jwitmarsh's suggestion above.  I got the error message:

```
$ dotnet run
Could not find file '/usr/local/bin/libclihost.dylib'.
```

However, adding the following symlink allowed me to run the simple hello world sample.

```
$ ln -s /usr/local/share/dotnet/bin/libclihost.dylib /usr/local/bin
$ dotnet run
Hello World!
```

**Comment by blackdwarf** [comment] 2016-01-13 19:15
@kkoning yes, thewe are tracking that in #823.

**Closed** 2016-01-15 20:41 UTC
Labels: bug, in progress
