### ISSUE TITLE
[dotnet build] Can't replace MVC packages with sources

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2966] opened 2016-05-09 21:44 UTC
## Steps to reproduce

Part of this verification task: aspnet/Release#10

Steps:

1) Create web app project
 2) Clone https://github.com/aspnet/Mvc
 3) Add path to Mvc\src to global.json
 4) Restore (right-click project in Solution Explorer and click "Restore packages") so VS sees new source refs (related: #528)
 5) Build

Expected: my app should compile fine and I should be able to run it.

Actual:
Severity    Code    Description Project File    Line    Suppression State
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.ViewFeatures\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.ViewFeatures.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.TagHelpers\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.TagHelpers.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Razor.Host\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Razor.Host.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Razor.dll' could not be found   VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Localization\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Localization.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Formatters.Json\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Formatters.Json.dll' could not be found   VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.DataAnnotations\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.DataAnnotations.dll' could not be found   VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Cors\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Cors.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Core\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.Core.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.ApiExplorer\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.ApiExplorer.dll' could not be found   VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Abstractions\bin\Debug\netstandard1.3\Microsoft.AspNetCore.Mvc.Abstractions.dll' could not be found VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
Error       c:\users\cesars\documents\visual studio 2015\Projects\VerifyReplacePackagesWithSources\src\VerifyReplacePackagesWithSources\error CS0006: Metadata file 'D:\src\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc\bin\Debug\netstandard1.5\Microsoft.AspNetCore.Mvc.dll' could not be found   VerifyReplacePackagesWithSources    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 
## Expected  behavior

Find binaries in correct place.
## Actual behavior

It's looking for MVC binaries in the wrong places.
## Environment data

`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:     1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by abpiskunov** [comment] 2016-05-09 21:45
See related issue that was first opened for tooling: https://github.com/aspnet/Tooling-Internal/issues/530

**Comment by livarcocc** [comment] 2016-05-09 22:05
@abpiskunov The related issue link seems broken.

**Comment by abpiskunov** [comment] 2016-05-09 22:10
It has, same info i added to new issue, i just copy pasted it.

Thanks,
Anton

On May 9, 2016, at 6:06 PM, Livar <notifications@github.com<mailto:notifications@github.com>> wrote:


@abpiskunov<https://github.com/abpiskunov> The related issue link seems broken.

-

**Comment by livarcocc** [comment] 2016-05-09 22:21
@abpiskunov Can you give more details about your files layouts? Where is your web app in relation to the mvc src? Also, where is your global.json? Is the root for your "solution" D:\src\aspnet?

**Comment by abpiskunov** [comment] 2016-05-09 23:29
Please follow repro steps with default vs options and you will get all layouts for files.

Thanks,
Anton

On May 9, 2016, at 6:22 PM, Livar <notifications@github.com<mailto:notifications@github.com>> wrote:


@abpiskunov<https://github.com/abpiskunov> Can you give more details about your files layouts? Where is your web app in relation to the mvc src? Also, where is your global.json? Is the root for your "solution" D:\src\aspnet?

-

**Comment by piotrpMSFT** [comment] 2016-05-10 02:40
@abpiskunov can you make steps 2 & 3 more explicit? In what directory did you clone? what did you add to global.json and where [show full file]?

**Comment by abpiskunov** [comment] 2016-05-10 16:13
I am a bit surprised why that matters and why you don't "just try to do it".. I tried this repro steps as they were assigned to a bug for my team and was able to repro it within 5 mins, but extra questions in this issue postponed investigation for 1 extra day already. I am not trying to be a "smart ass", but really it is just a pattern I noticed for some cli issues... Below is my global.json and as you would see that you could just do same thing without me yesterday, there not many choices how to specify folder and it does not matter for actual problem in this issue ...

Here is my global.json:

{
  "projects": [ "src", "test", "D:\\git\\ms\\aspnet\\Mvc\\src" ]
}

**Comment by PinpointTownes** [comment] 2016-05-10 17:21
@abpiskunov have you tried to escape your absolute path?

`D:\\git\\ms\\aspnet\\Mvc\\src`

**Comment by abpiskunov** [comment] 2016-05-10 17:34
I did not and it does not matter, all projects are found just fine and are being restored, built etc. However see at where "dotnet build" tries to find their binaries under RID subfolders bin\Debug\netstandard1.5, but they actually being built under artifacts.

So it does not matter how they are specified in global.json.

**Comment by abpiskunov** [comment] 2016-05-10 17:35
1 sec - when I pasted GitHub changed \ symbols , I did have escaped ones

**Comment by kspearrin** [comment] 2016-05-26 19:42
I'm having this same problem now. I used to do this app the time with my rc1 aspnet app. Getting same errors as @abpiskunov now with RC2.

**Comment by SeeWhat** [comment] 2016-06-16 05:36
You can workaround the issue by modifying each of the sources projects .xproj by replace the line 

`<Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" Condition="'$(VSToolsPath)' != ''" />`
with
`<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Props" Condition="'$(VSToolsPath)' != ''" />`

**Comment by kspearrin** [comment] 2016-06-16 20:17
@SeeWhat That didn't change anything for me. I've always had my `.xproj` files updated for RC2 and still having the same problem.

**Comment by SeeWhat** [comment] 2016-06-16 22:23
@kspearrin Hi, Not your project files, but the project you want to debug against. So if you wanted to work debug/work with `Microsoft.AspNetCore.Mvc.Abstractions` then you'd modify it's `.xproj` file.

Not ideal, but a workaround.

**Comment by muratg** [comment] 2016-06-22 19:56
:eyes:

**Comment by dandy** [comment] 2016-07-02 15:53
I am having the same problem, can not build mvc from the sources. I have tried workaround mentioned by @SeeWhat, but didn't work for me.

**Comment by DarrenV79** [comment] 2016-07-17 19:52
@SeeWhat suggestion didn't work.  The issue is the output paths which (for Identity) say

<OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts\bin\</OutputPath>

but my projects are

<OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>

Changing the Identity XProj's to match my projects and rebuilding fixes the issue.

**Comment by frostymarvelous** [comment] 2016-09-09 10:22
@DarrenV79 gave the right solution for me

Changing 
    `<OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts\bin\</OutputPath>`
to
    `<OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>`

fixes it for me

**Comment by rendmath** [comment] 2016-09-21 11:40
Apparently, this has to be done for all cascading dependencies.

For example, when trying to step into Microsoft.AspNetCore.Diagnostics, I had to change the OutputPath inside Microsoft.AspNetCore.Diagnostics.Abstractions.xproj too.

**Comment by Sebazzz** [comment] 2016-10-27 17:15
For all who have it, I had this issue trying to debug MVC as part of my app. I resolved it by running `dotnet build -c Debug` in the `src/Microsoft.AspNetCore.Mvc` folder. This causes a build, after that I was able to successfully build my own project.

My guess is that Visual Studio doesn't recognize the "added projects" via global.json as candidates for a project build.

**Comment by livarcocc** [comment] 2017-05-09 22:11
We don't support this anymore. When using MSBuild, you need to be explicit about using a ProjectReference or a PackageReference. So, I am going to close this. If I misunderstood something, please, re-activate.

**Closed by livarcocc** 2017-05-09 22:11 UTC
