### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#586] opened 2015-12-18 16:27 UTC
_From @ErikSchierboom on April 26, 2015 7:10_

I'd love to see F# support, similar to how [VB support will be added](https://github.com/aspnet/dnx/issues/1706).

_Copied from original issue: aspnet/dnx#1714_

**Comment by muratg** [comment] 2015-12-18 16:27
_From @KodrAus on September 11, 2015 3:16_

+1 for F# support

**Comment by muratg** [comment] 2015-12-18 16:27
_From @spencerwi on September 14, 2015 15:49_

Another +1; F# is the whole reason that I'd try to do .NET work (as a Linux/OSX dev)

**Comment by muratg** [comment] 2015-12-18 16:27
_From @itajaja on September 14, 2015 15:50_

yay! +1

**Comment by muratg** [comment] 2015-12-18 16:27
Language support (including VB.NET) is not in scope for V1. Putting this one to Backlog as well.

**Comment by muratg** [comment] 2015-12-18 16:27
_From @jskulavik on September 14, 2015 18:59_

@davidfowl [pointed out how this could be achieved long ago](https://github.com/aspnet/dnx/issues/1706), @Alxandr already gave it a go, and we've now got beta 7+ to work with possibly using [this](https://github.com/davidfowl/vNextLanguageSupport) as a spring board.  Given that ASPNET5 is an OSS project, why shouldn't the 'community,' in this case the outstanding F# community, contribute?  The new MSFT is *give and take* folks, no longer just give, and we shouldn't just take, but give.  I'm personally +100 for the support of F#, but let's make it happen as a community rather than demand this already overloaded team just provide it like they did in the MSFT of old.

**Comment by muratg** [comment] 2015-12-18 16:27
_From @spencerwi on September 14, 2015 19:25_

@jskulavik As you pointed out, @Alxandr did already give it a go. This issue is, as I understand it, about *official* support for F# (a Microsoft language) on Microsoft's own .NET language runtime, using *stabilized* APIs, rather than *unofficial* support against *beta* APIs.

Trust me, I've tried quite a bit using and digging into Alxandr's YoloDev work, but the problem right now is that aspnet/vNext are in such a "move fast and break everything" phase right now that community support is far from stable.

**Comment by enricosada** [comment] 2015-12-24 13:11
@muratg i added compile fsc with pr #538.

I'll add others issues and link this issue to track commands who require specific f# support ( new, etc )

ref Microsoft/visualfsharp#834 too

**Comment by enricosada** [comment] 2015-12-24 13:23
`dotnet new` issue #647

**Comment by borgdylan** [comment] 2015-12-27 10:11
@enricosada In my mono port of the CLI, I adapted your work to work on mono.

**Comment by xperiandri** [comment] 2016-01-07 20:32
Could someone explain me how to run F# with DNX RC2?
https://github.com/fsprojects/fsharp-dnx/issues/26

**Comment by spencerwi** [comment] 2016-01-07 20:42
@xperiandri This issue is, I think, about using a different cli -- `dotnet` (not `dnx`) to run F#.

That being said, I'd also like to know how to run F# projects using the `dotnet` cli.

**Comment by enricosada** [comment] 2016-01-07 21:30
@spencerwi it's really the first steps, check tests. https://github.com/dotnet/cli/tree/master/test/FSharpTestProjects/TestAppWithArgs

it's like c#, but you need to add `"compilerName": "fsc"` in project json and source files inside `compileFiles`.

**Comment by xperiandri** [comment] 2016-01-07 21:54
Cool! As I understand, ASP.NET 5 RTM will run top of CLI, won't it?
However I cannot specify [<EntryPoint>] for DNX or run ASP.NET with CLI yet.

**Comment by enricosada** [comment] 2016-01-07 21:59
the dotnet/cli replace asp.net/dnx, and asp.net rtm is going to use cli. 
about current cli/dnx support, ask in aspnet, sry i am not in the loop

**Comment by muratg** [comment] 2016-01-08 19:03
@xperiandri Current plan is to ship ASP.NET 5 RC2 with dotnet CLI support and retire DNX.

**Comment by xperiandri** [comment] 2016-01-08 19:37
That is great. However I would like to start a project on MVC 6 with F# as soon as possible.

**Comment by muratg** [comment] 2016-01-08 21:08
Sure!  @davidfowl has some examples [here](https://github.com/davidfowl/dotnetcli-aspnet5).

**Comment by fsoikin** [comment] 2016-01-10 21:02
@enricosada I tried this just now, and it failed at `dotnet restore`, because dependency `Microsoft.FSharp.Core.netcore` is nowhere to be found.

Should I be using some special feed? Right now I'm using these:

```
https://www.myget.org/F/dotnet-coreclr/api/v3/flatcontainer/
https://api.nuget.org/v3-flatcontainer/
```

**Comment by enricosada** [comment] 2016-01-10 21:43
you need

```xml
    <add key="fsharp-daily" value="https://www.myget.org/F/fsharp-daily/api/v3/index.json" />
```

like [NuGet.Config#L15](https://github.com/dotnet/cli/blob/ecda2a810615dda9f280fd8a87d23be2e2fcae45/NuGet.Config#L15)

**Comment by fsoikin** [comment] 2016-01-22 19:38
Tried with that. Now it can find FSharp package, but fails to find `Microsoft.Netcore.Platforms >= 1.0.0-rc2-23616` (which is apparently referenced from FSharp).
Despite this, `dotnet restore` reports "complete" rather than "failed", but issuing `dotnet run` after that still leads to "unresolved dependency" errors.

**dotnet restore** output:
```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for D:\work\...\project.json...
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 690ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 595ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 643ms
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 444ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 509ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 575ms
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
info : Committing restore...
info : Restore completed in 9733ms.
```

**project.json** (taken from [here](https://github.com/dotnet/cli/blob/master/test/FSharpTestProjects/TestLibrary/project.json), with fixed up versions due to "downgrade warning")
```
{
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "commands": {
    "run": "run"
  },
  "frameworks": {
    "dnxcore50": { }
  },
  "compilerName": "fsc",
  "compile": [
      "program.fs"
  ],
  "dependencies": {
    "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-151221",
    "System.Runtime": "4.0.21-rc2-23616",
    "System.Console": "4.0.0-rc2-23616"
  }
}
```

**Local nuget.config** (taken from [here](https://github.com/dotnet/cli/blob/master/NuGet.Config))
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
  	<clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="nugetbuild" value="https://www.myget.org/F/nugetbuild/api/v3/index.json" />
    <add key="AspNetCIDev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="roslyn-nightly" value="https://www.myget.org/F/roslyn-nightly/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-corefxlab" value="https://www.myget.org/F/dotnet-corefxlab/api/v3/index.json" />
    <add key="corefxlab" value="https://www.myget.org/F/netcore-package-prototyping/api/v3/index.json" />
    <add key="corert" value="https://www.myget.org/F/dotnet/auth/3e4f1dbe-f43a-45a8-b029-3ad4d25605ac/api/v2" />
    <add key="dotnet-buildtools" value="https://www.myget.org/F/dotnet-buildtools/api/v3/index.json" />
    <add key="fsharp-daily" value="https://www.myget.org/F/fsharp-daily/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by enricosada** [comment] 2016-01-22 20:16
It's ok. You miss that dependency inside project.jsonCheck the TestInteger app in my pr ( under test/FsharpTestProjects ). It's your use example ( i added it as regression test )

Inviato da Mobile




On Fri, Jan 22, 2016 at 11:38 AM -0800, "Fyodor Soikin" <notifications@github.com> wrote:





Tried with that. Now it can find FSharp package, but fails to find `Microsoft.Netcore.Platforms >= 1.0.0-rc2-23616` (which is apparently referenced from FSharp).
Despite this, `dotnet restore` reports "complete" rather than "failed", but issuing `dotnet run` after that still leads to "unresolved dependency" errors.

**dotnet restore** output:
```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for D:\work\...\project.json...
info :   NotFound https://www.myget.org/F/nugetbuild/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 690ms
info :   NotFound https://www.myget.org/F/roslyn-nightly/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 595ms
info :   NotFound https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 643ms
info :   NotFound https://www.myget.org/F/netcore-package-prototyping/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 444ms
info :   NotFound https://www.myget.org/F/dotnet-buildtools/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 509ms
info :   NotFound https://www.myget.org/F/fsharp-daily/api/v3/flatcontainer/microsoft.netcore.platforms/index.json 575ms
info : All packages are compatible with DNXCore,Version=v5.0.
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
info : All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
info : Committing restore...
info : Restore completed in 9733ms.
```

**project.json** (taken from [here](https://github.com/dotnet/cli/blob/master/test/FSharpTestProjects/TestLibrary/project.json), with fixed up versions due to "downgrade warning")
```
{
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "commands": {
    "run": "run"
  },
  "frameworks": {
    "dnxcore50": { }
  },
  "compilerName": "fsc",
  "compile": [
      "program.fs"
  ],
  "dependencies": {
    "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-151221",
    "System.Runtime": "4.0.21-rc2-23616",
    "System.Console": "4.0.0-rc2-23616"
  }
}
```

**Local nuget.config** (taken from [here](https://github.com/dotnet/cli/blob/master/NuGet.Config))
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
        <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="nugetbuild" value="https://www.myget.org/F/nugetbuild/api/v3/index.json" />
    <add key="AspNetCIDev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="roslyn-nightly" value="https://www.myget.org/F/roslyn-nightly/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-corefxlab" value="https://www.myget.org/F/dotnet-corefxlab/api/v3/index.json" />
    <add key="corefxlab" value="https://www.myget.org/F/netcore-package-prototyping/api/v3/index.json" />
    <add key="corert" value="https://www.myget.org/F/dotnet/auth/3e4f1dbe-f43a-45a8-b029-3ad4d25605ac/api/v2" />
    <add key="dotnet-buildtools" value="https://www.myget.org/F/dotnet-buildtools/api/v3/index.json" />
    <add key="fsharp-daily" value="https://www.myget.org/F/fsharp-daily/api/v3/index.json" />
  </packageSources>
</configuration>
```

---

**Comment by fsoikin** [comment] 2016-01-22 20:34
@enricosada I don't quite understand: which dependency am I missing exactly?

**Comment by enricosada** [comment] 2016-01-22 21:01
See #894 the https://github.com/enricosada/cli/blob/10fbd54157afa2b61b37d0ded7237d49dda07769/test/FSharpTestProjects/TestAppWithInteger/project.json

Inviato da Mobile




On Fri, Jan 22, 2016 at 12:34 PM -0800, "Fyodor Soikin" <notifications@github.com> wrote:





@enricosada I don't quite understand: which dependency am I missing exactly?

---

**Comment by enricosada** [comment] 2016-02-25 15:31
i added some useful info in a wiki specific to F# and .NET CLI

- [Getting Started](https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki/Getting-Started)
- [Migrate fsproj to .NET CLI](https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki/Migrate-fsproj-To-.NET-CLI)

**Comment by blackdwarf** [comment] 2016-05-20 21:07
Closing this as there is a story with F# and the new tooling.

**Closed by blackdwarf** 2016-05-20 21:07 UTC
Labels: Move to DotNet CLI
