### ISSUE TITLE
dotnet run by default, is too verbose - Use --verbosity instead

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#3594] opened 2016-06-15 22:48 UTC
By default, a simple `dotnet run` should just run. No details at all.

Perhaps there's a -v1 or -v2? Basically verbose is great, but run should 
just run. THIS is not needed:

```
C:\Users\Scott\Desktop\foo>dotnet run
Project foo (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hello World!
```

So: 

| command | output |
| --- | --- |
| run | no output |
| run -v | current verbose output |
| run - **(need suggestions here)** | The current run behavior, basically "info level" output |

**Comment by plioi** [comment] 2016-06-16 13:34
Other dotnet commands have --verbosity as an option.  dotnet help shows that --verbose is a 'common' option.  For consistency, all commands could instead have --verbosity.

**Comment by herecydev** [comment] 2016-06-16 15:40
@plioi I would agree, as long as the default verbosity is lowered. I don't need to see `Project foo (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.` everytime, if ever.

**Comment by plioi** [comment] 2016-06-16 16:05
@herecydev Especially when I'm targeting a few frameworks, and my build script invokes dotnet build and dotnet test a couple times. Most of the script's output is "Skipping compilation".

**Comment by eerhardt** [comment] 2016-06-16 16:28
Looks like a dupe of #2174.

**Comment by blackdwarf** [comment] 2016-06-16 17:19
I agree that this is not optimal and is something we should do. 

@plioi your example is not using `dotnet run` though. I assume you are also referring to build having this passed to it?

**Comment by plioi** [comment] 2016-06-16 17:25
@blackdwarf Right. If the immediate request regarding 'dotnet run' is corrected, but in a different way than is already established on some other commands, we'll wind up with a funky CLI.  --verbose is insufficient,  --verbosity would be best across all the commands.

**Comment by blackdwarf** [comment] 2016-06-16 17:32
@plioi agreed, was just asking to make sure we're on the same page. 😄

**Comment by ljw1004** [comment] 2016-08-30 18:55
@glennc advises that `dotnet mydll.dll` is the way an end-user would run it, while `dotnet run` is intended only for use during development time. I guess that's why it's naturally more verbose...

**Comment by blackdwarf** [comment] 2016-08-30 21:43
@ljw1004 no, there is some work to do to figure out when `dotnet run` should output. Regardless of whether it is design time or not, it is too verbose and I'm working on a proposal on how to fix this.

**Comment by glennc** [comment] 2016-09-14 00:49
@blackdwarf you mean no to the implication that `dotnet run` should be verbose not no to it being a design time command. Right?

**Comment by blackdwarf** [comment] 2016-09-14 14:01
@glennc yes, "no, it is still too verbose, even though it is meant for dev-time scenarios" is what I meant. :)

**Comment by shanselman** [comment] 2016-10-31 21:20
It really feels like this needs to get done. I [blogged recently about doing "Auto testing"](http://www.hanselman.com/blog/CommentView.aspx?guid=9f30b83e-6a88-4174-a08c-f1fc06f6c1ec#commentstart) with dotnet watch test, and the verbose output is super annoying. I noticed it, and the comments noticed it.

**Comment by eerhardt** [comment] 2016-10-31 21:36
With the new MSBuild-enabled CLI, I was able to get "dotnet run" down to only printing out build warnings and errors.  It no longer prints out other build messages, like "skipping build", etc.

The reason it still prints out warnings and errors is because that is what the "quiet" mode of MSBuild does. I still felt build errors needed to be printed out, so you know why your app couldn't be executed.  And I felt they needed to be printed out in red text to catch your eye.

Try the latest builds using .csproj and let us know what you think.

**Comment by xferra** [comment] 2016-10-31 21:55
@eerhardt  It was really annoying behavior, thank you!

**Comment by blackdwarf** [comment] 2017-01-14 18:12
As @eerhardt said, in the latest tooling `dotnet run` will print out just the app output or warnings or errors if there are any. With this, I will close the issue as "fixed". Please reopen if needed. Thanks!

**Closed by blackdwarf** 2017-01-14 18:12 UTC
Labels: enhancement

**Comment by 0xced** [comment] 2017-01-14 19:40
@blackdwarf What's *the latest tooling* exactly? I just downloaded **dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg** a few seconds ago and it still has this issue.

**Comment by blackdwarf** [comment] 2017-01-15 00:53
@0xced the latest tooling is the latest from rel/1.0.0. Alternatively you can download the Preview 4 release. Links are in the README.

**Comment by perlun** [comment] 2018-02-17 19:11
Late to the party here, but... is there a way to get the verbose output back, if desired? I tried both with `dotnet run --verbose` and `dotnet run -v` but neither option gives me any more output than just `dotnet run`.

**Comment by livarcocc** [comment] 2018-02-17 21:59
We added a verbosity option in the 2.1.300 version of the CLI. Which is not available officially yet, only as nightlies, but we will have a preview of it officially available soon.
