### ISSUE TITLE
Latest portable Linux SDK fails in dotnet create console

### ISSUE THREAD

**Issue by janvorli** [dotnet/cli#6662] opened 2017-05-22 20:16 UTC
## Steps to reproduce
* Download dotnet sdk from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-linux-x64.latest.tar.gz (link is on the main page of this repo)
* Untar it into a folder
* cd into the folder where it was untared to
* mkdir test
* cd test
* ../dotnet create console

## Expected  behavior
It succeeds creating the new app and restores its dependencies

## Actual behavior
The restore phase fails with the following output:
```

Processing post-creation actions...
Running 'dotnet restore' on /home/janvorli/dotnet/test/test.csproj...
Restore failed.
Output from command:
  Restoring packages for /home/janvorli/dotnet/test/test.csproj...
/home/janvorli/dotnet/sdk/2.0.0-preview2-006125/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25319-02)' for '.NETCoreApp,Version=v2.0'. [/home/janvorli/dotnet/test/test.csproj]
  Generating MSBuild file /home/janvorli/dotnet/test/obj/test.csproj.nuget.g.props.
  Generating MSBuild file /home/janvorli/dotnet/test/obj/test.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /home/janvorli/dotnet/test/obj/project.assets.json
  Restore failed in 420.59 ms for /home/janvorli/dotnet/test/test.csproj.

  Errors in /home/janvorli/dotnet/test/test.csproj
      Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25319-02)' for '.NETCoreApp,Version=v2.0'.

  NuGet Config files used:
      /home/janvorli/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
      /home/janvorli/.dotnet/NuGetFallbackFolder






Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-006125)

Product Information:
 Version:            2.0.0-preview2-006125
 Commit SHA-1 hash:  059e29b600

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/janvorli/dotnet/sdk/2.0.0-preview2-006125/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d
```

**Comment by janvorli** [comment] 2017-05-22 20:17
cc: @gkhanna79, @livarcocc, @eerhardt

**Comment by livarcocc** [comment] 2017-05-22 20:26
Duplicate of https://github.com/dotnet/cli/issues/6619. This happens because the LZMA archive is out of sync with the runtime carried in the CLI.

**Closed by livarcocc** 2017-05-22 20:26 UTC
Labels: bug
