### ISSUE TITLE
Restore fails when a NuGet feed with Encrypted Credentials (default) is defined on the system

### ISSUE THREAD

**Issue by justinbailey** [dotnet/cli#3174] opened 2016-05-21 02:58 UTC
## Steps to reproduce
1. set nuget private feed with credentials as described [here](https://docs.nuget.org/consume/nuget-config-settings#credentials-for-package-source)
   `NuGet.exe Sources Add -Name <feedName> -Source <pathToPackageSource> -UserName xxx -Password <secret>`
2. validate that nuget works with the feed on a non-Core project
3. create new basic app using dotnet new
4. restore packages using dotnet restore
## Expected  behavior

log  : Restoring packages for D:_temp_net\project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   GET https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json 322ms
info :   OK https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver' 526ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
info :   GET https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost'
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json 150ms
info :   OK https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost' 230ms
log  : Installing Microsoft.NETCore.Windows.ApiSets 1.0.1-rc2-24027.
log  : ... <remaining entries omitted> ...
info : Committing restore...
log  : Writing lock file to disk. Path: D:_temp_net\project.lock.json
log  : D:_temp_net\project.json
log  : Restore completed in 29062ms.

NuGet Config files used:
    C:\Users\Justin\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    https://nuget.telerik.com/nuget
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    112 package(s) to D:_temp_net\project.json
## Actual behavior

`info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost''.
log  : Password decryption failed for source : 'https://nuget.telerik.com/nuget' is unsupported on this platform. A clear text password may be used instead.
log  :   Specified method is not supported.
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost''.
log  : Password decryption failed for source : 'https://nuget.telerik.com/nuget' is unsupported on this platform. A clear text password may be used instead.
log  :   Specified method is not supported.
error: Failed to retrieve information from remote source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost''.
error: Password decryption failed for source : 'https://nuget.telerik.com/nuget' is unsupported on this platform. A clear text password may be used instead.
error: Failed to retrieve information from remote source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost''.
error:   Password decryption failed for source : 'https://nuget.telerik.com/nuget' is unsupported on this platform. A clear text password may be used instead.
error:   Specified method is not supported.`
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
## Comment

Workaround is to store the credentials in PlainText using the `-StorePasswordInClearText` argument when adding the feed such as `NuGet.exe Sources Add -Name <feedName> -Source <pathToPackageSource> -UserName xxx -Password <secret> -StorePasswordInClearText` as described in the logged error message. 

However, corporate policy disallows storing any password in cleartext, so we are in trouble if this is not fixed for RTM.

And restore worked properly in RC1 when Nuget feed contained Encrypted credentials prior to the switch to RC2.

**Comment by blackdwarf** [comment] 2016-05-21 16:22
@yishaigalatzer @emgarten this seems like a NuGet issue.

**Comment by yishaigalatzer** [comment] 2016-05-21 16:29
This is currently by design as the error message clearly declares. There are no decryption APIs in .net core yet.

Another work around is to use nuget.exe restore instead (use 3.5 beta)

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, May 21, 2016 at 9:22 AM -0700, "Zlatko Knezevic" <notifications@github.com<mailto:notifications@github.com>> wrote:


@yishaigalatzer<https://github.com/yishaigalatzer> @emgarten<https://github.com/emgarten> this seems like a NuGet issue.

-

**Comment by thewilsons13** [comment] 2016-06-03 17:08
I have the same issue with a private Nuget feed I use in VS Team Services.  The nuget.exe 3.5 beta trick appears to work for a restore, but I'd prefer to have the normal restore features of dotnet CLI work so I don't have to remember this trick two years from now.  I work in an enterprise IT environment and I've always sighed when I have to work with projects that have all these dependency resolution problems you have to work through before you can get the project to work.

So... I hope that "There are no decryption APIs in .net core yet." is an indication that there will be...

**Comment by joshgerdes** [comment] 2016-06-17 19:31
I was not able to get the nuget.exe 3.5 beta trick to work on mac. Anybody have success with a workaround on mac?

###### Here's the output from running `mono --runtime=v4.0 ./nuget.exe restore`:
> TODO: unknown keyword platform


###### Environment information output from `dotnet --info`:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by emgarten** [comment] 2016-06-17 20:01
@joshgerdes that looks like an error that would come from an older version of nuget.exe. Make sure you have the latest 3.5.0-beta2 build from: https://dist.nuget.org/index.html

**Comment by joshgerdes** [comment] 2016-06-17 20:42
@emgarten Thanks for the catch, I had accidentally copied an older version.  I'm now using NuGet Version: 3.5.0.1284 but I am receiving the following error:

> Restoring packages for /Users/joshgerdes/test/project.json...
>   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
> Unable to load the service index for source https://test.pkgs.visualstudio.com/DefaultCollection/_packaging/test/nuget/v3/index.json.
>   Data unprotecting failed.
>   Invalid data.

A quick search lead me to some mono related issues.  So I am currently looking the possibility of mono being the source of the issue.  I'll post my findings.

###### Environment info:
- Mac OS X 10.11.5 (15F34)
- NuGet Version 3.5.0.1284
- Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)

**Comment by emgarten** [comment] 2016-06-18 05:13
I haven't seen this error before, you might try using basic auth instead of the visual studio online extensions for nuget.exe which normally bring up the full login experience for visual studio feeds. You can find sometimes find it by selecting the NuGet 2.8.x login option from Visual Studio online.

**Comment by joshgerdes** [comment] 2016-06-20 15:43
@mrward Yes, the password is encrypted. Taking your advice, I upgraded to the latest mono and did some more testing.

Using:
Mono JIT compiler version 4.4.0 (tarball Wed Jun 15 18:28:03 BST 2016)

I was able to add the source with an encrypted password running the following command:
`nuget.exe sources add -Source <sourceurl> -Name <key> -UserName<username> -Password <secret>`

And the `nuget.exe restore` command would run successfully.

But if I do not add the source from the command line and just have the source defined in the project's NuGet.config it fails with the same error as I posted before.

Is there some sort of trick to get the encrypted password to be read from the NuGet.config correctly?

**Comment by yishaigalatzer** [comment] 2016-06-20 21:03
Thanks @joshgerdes. 

nit: I was a bit confused by your edit :) It's better to avoid editing on top, because the notification email contains to original comment.

**Comment by smolesen** [comment] 2016-09-27 12:49
The NuGet.exe version running on VSTS is currently:

Detected NuGet version 3.3.0.212 / 3.3.0

Is there a way to get this to work when building on VSTS? Can I somehow use a different version of NuGet.exe?

**Comment by yishaigalatzer** [comment] 2016-09-27 15:45
Yes - You can bring your own version of nuget to VSTS 

CC @zjrunner for guidance

**Comment by zjrunner** [comment] 2016-09-28 16:04
In the task configuration in VSTS there is an 'Advanced' section that lets you choose a pre-release nuget 3.5, or your own custom version.  Once 3.5 rtm is released we'll be force upgrading this 3.5 pre-release build to the official 3.5 as part of the task update for people that have chosen that option.

**Comment by smolesen** [comment] 2016-09-29 05:38
The only thing I see in the advanced section is:

Verbosity
Path to NuGet.exe
Path to NuGet.exe is below version 3.2

I've made it use NuGet 3.5.0-RC1 by putting it in .nuget and then checkit in, plus setting Path to NuGet.exe to '.nuget/nuget.exe'

**Comment by zjrunner** [comment] 2016-09-29 15:41
I'm sorry, the update is still rolling out so seeing it will depend on which region your account resides.  You should see it light up within the next few days and you'll be able to continue using a custom version or just select the in-task version.  When it does roll out you will get a build warning that 3.3 is the selected default but we're continuing to use your custom version - that will be a good notification that the update has been applied and you can choose to either check our () 3.5 option (and clear the custom path) or the () custom option to make the warning disappear.

**Comment by MartinJohns** [comment] 2016-10-08 09:15
Could someone add a reference to the issue that tracks the missing encryption API that blocks this issue?

**Comment by yishaigalatzer** [comment] 2016-10-08 15:52
This is already fixed in the latest version of nuget @alpanov

**Comment by piotrpMSFT** [comment] 2016-11-10 08:41
Closing as this is fixed in the latest version of nuget. If there is a further issue here, please open in https://github.com/nuget/home.

**Closed by piotrpMSFT** 2016-11-10 08:41 UTC

**Comment by mountgellert** [comment] 2017-02-09 19:48
Would it be possible to have the version used by dotnet restore to be equivalent or bigger than the version mentioned here?

**Comment by wierzba3** [comment] 2017-02-28 19:07
I'm having this problem and using -StorePasswordInClearText caused the "password decryption not supported" error to go away, 

but now I get this:

```
2017-02-28T18:05:03.4345104Z error: Unable to load the service index for source https://mycompany.pkgs.visualstudio.com/_packaging/DLFeed/nuget/v3/index.json.
2017-02-28T18:05:03.4345104Z error:   Response status code does not indicate success: 401 (Unauthorized).
```

The feed with the same credentials work in a different build (normal .NET). So .net core must be the difference causing the 401.

What could be the problem?

**Comment by guidobouman** [comment] 2018-02-05 12:47
Did this ever get solved?

I'm running into this issue on macOS, `dotnet --info` gives me the following results:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Although I was able to run a restore the other day, I seem to be unable now. Is it possible that multiple versions of NuGet might be interfering with each other?

> ➜  which -a dotnet
/usr/local/share/dotnet/dotnet

> ➜  which -a nuget
/Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget
