### ISSUE TITLE
Template fails dotnet restore after updating to dotnet core 2 preview 2

### ISSUE THREAD

**Issue by mike-morr** [dotnet/cli#7078] opened 2017-07-05 18:01 UTC
## Steps to reproduce
[Install dotnet core](https://www.microsoft.com/net/core#windowscmd)
Install dotnet core 2 Preview 1
dotnet new -i Fable.Template
dotnet new fable -n TestProj
dotnet restore **(should work)**
[Install dotnet core 2 Preview 2](https://www.microsoft.com/net/core/preview#windowscmd)
dotnet new -i Fable.Template
dotnet new fable -n TestProj
dotnet restore

## Expected  behavior

dotnet restore succeeds the after installing Preview 2

## Actual behavior

An error message is thrown:

```bash
  '""' is not recognized as an internal or external command,
  operable program or batch file.
C:\code\TestProj\.paket\Paket.Restore.targets(18,5): error MSB3073: The command """ restore --project "C:\code\TestProj\TestProj.fsproj" --target-framework netstandard1.6" exited with code 9009. [C:\code\TestProj\TestProj.fsproj]
```

## Workaround

```./.paket/paket.exe install``` after this, dotnet restore works successfully.

## More Info
It appears like the paket restore targets are getting mangled somehow.  

The source for the template is located here:  https://github.com/fable-compiler/Fable/tree/master/src/templates/simple

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by livarcocc** [comment] 2017-07-05 18:52
I don't see how this belongs in the CLI repo. We do not own the Fable templates. Should you move this bug to the fable repo?

**Comment by forki** [comment] 2017-07-05 18:57
No the problem is that the template source is fine. The template update process is somehow broken. 
We have this behavior seen with multiple users.

**Comment by livarcocc** [comment] 2017-07-05 18:57
We do not own this Paket.Restore.targets target. We do not know what it does.

**Comment by livarcocc** [comment] 2017-07-05 18:59
I see this in the targets:

```
<PaketCommand Condition=" '$(OS)' == 'Windows_NT'">"$(PaketExePath)"</PaketCommand>
    <PaketCommand Condition=" '$(OS)' != 'Windows_NT' ">$(MonoPath) --runtime=v4.0.30319 "$(PaketExePath)"</PaketCommand>
```

It is up to the template owners to figure out why this is not being set properly anymore.

@KevinRansom I wonder if this is due to preview2 moving to the new F# SDK?

**Comment by forki** [comment] 2017-07-05 19:07
Yes we do understand that you don't own these files. As far as we already know these files are all correct in the template source. And this has nothing to do with F# sdk or paket. 
The problem is simply that after dotnet new we have a diff between the fresh project and the original template. 
Something is messing this up.

**Comment by KevinRansom** [comment] 2017-07-05 21:23
@forki 
Hey mate, I think your .targets may be slightly broken:

In the section bellow:

I believe PacketRootPath should be PacketToolsPath or vice-versa.

````
    <PaketToolsPath>$(MSBuildThisFileDirectory)</PaketToolsPath>
   <PaketExePath Condition=" '$(PaketExePath)' == '' AND Exists('$(PaketRootPath)paket.exe')">$(PaketRootPath)paket.exe</PaketExePath>

````

````
  <PropertyGroup>
    <!-- Mark that this target file has been loaded.  -->
    <IsPaketRestoreTargetsFileLoaded>true</IsPaketRestoreTargetsFileLoaded>
    <PaketToolsPath>$(MSBuildThisFileDirectory)</PaketToolsPath>
    <MonoPath Condition="'$(MonoPath)' == '' And Exists('/Library/Frameworks/Mono.framework/Commands/mono')">/Library/Frameworks/Mono.framework/Commands/mono</MonoPath>
    <MonoPath Condition="'$(MonoPath)' == ''">mono</MonoPath>
    <!-- Paket command -->
    <PaketExePath Condition=" '$(PaketExePath)' == '' AND Exists('$(PaketRootPath)paket.exe')">$(PaketRootPath)paket.exe</PaketExePath>
    <PaketCommand>"$(PaketExePath)"</PaketCommand>
    <PaketBootStrapperExePath Condition=" '$(PaketBootStrapperExePath)' == '' AND Exists('$(PaketRootPath)paket.bootstrapper.exe')">$(PaketRootPath)paket.bootstrapper.exe</PaketBootStrapperExePath>
    <PaketBootStrapperCommand>"$(PaketBootStrapperExePath)"</PaketBootStrapperCommand>
  </PropertyGroup>
````

```
C:\temp\a>set PaketExePath=C:\temp\a\.paket\paket.exe
C:\temp\a>dotnet restore
  Paket version 5.4.5
  packages folder is locked by paket.exe (PID = 16320). Waiting...
  packages folder is locked by paket.exe (PID = 16320). Waiting...
  packages folder is locked by paket.exe (PID = 16320). Waiting...
  Performance:
   - Disk IO: 244 milliseconds
   - Runtime: 21 seconds
  Restoring packages for C:\temp\a\a.fsproj...
  Restoring packages for C:\temp\a\a.fsproj...
  Installing FSharp.Compiler.Tools 4.1.17.
  Installing FSharp.NET.Sdk 1.0.5.
  Generating MSBuild file C:\temp\a\obj\a.fsproj.nuget.g.props.
  Generating MSBuild file C:\temp\a\obj\a.fsproj.nuget.g.targets.
  Restore completed in 4.53 sec for C:\temp\a\a.fsproj.
  Installing Microsoft.DiaSymReader.PortablePdb 1.2.0.
  Installing FSharp.Compiler.Service 13.0.0.
  Installing Newtonsoft.Json 10.0.3.
  Installing Fable.Compiler 1.1.7.
  Installing dotnet-fable 1.1.7.
  Restore completed in 6.07 sec for C:\temp\a\a.fsproj.

C:\temp\a>
````

**Comment by forki** [comment] 2017-07-06 06:32
@kevinransom root path and tool path are two different things. The problem is not if paket can be called or not (that is just the symptom). Our issue is that we see dotnet new creating a wrong file. 
We expect it to exactly create https://github.com/fable-compiler/Fable/blob/master/src/templates/simple/Content/.paket/Paket.restore.targets . For this issue here,  it doesn't matter if the file itself is actually bug free or not. It just matters that we don't get the the file as specified in the template. (I saw it with other files as well, but this was what reproed for multiple users) 

Again we think this has nothing to do with paket, f# or fable. It's just a matter of dotnet templating

**Comment by livarcocc** [comment] 2017-07-06 06:36
@mlorbetske can you take a look at this? have you heard about something like this before.

@forki, so, the Paket.Restore.targets is not being generated at all? Because from @mike-morr initial bug report, it seemed like it did, but a property was missing, like @KevinRansom suggested. Are we sure we are talking about one single issue here?

**Comment by forki** [comment] 2017-07-06 06:44
Yes @mike-morr and myself discussed on gitter before we raised it. It's been investigated over couple of weeks. And since didn't find a solution we raised it here. 
The file gets generated, but it has a diff to the uploaded version. Nobody knows why. That's the problem we see.

**Comment by forki** [comment] 2017-07-06 06:48
@kevinransom can please diff your local version with the online version? The fact that path is wrong for you is probably due to the fact that the template creation bug reproed on your machine.

**Comment by livarcocc** [comment] 2017-07-06 07:18
Has the version with the problem ever been published? Did it even exist in your repo during some point in time?

**Comment by forki** [comment] 2017-07-06 07:22
I think it does not. There are 2 versions of that file. And IIRC my file after dotnet new was a mix of both.

**Comment by livarcocc** [comment] 2017-07-06 07:24
Ok, given that this seems like an issue with templates, I will let @mlorbetske investigate. if you want, go ahead and move this issue to dotnet/templating.

**Comment by mlorbetske** [comment] 2017-07-06 07:29
This issue was moved to dotnet/templating#1021

**Closed by mlorbetske** 2017-07-06 07:29 UTC
