### ISSUE TITLE
dotnet restore: RuntimeIdentifiers does not tolerate spaces

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#4633] opened 2016-11-07 00:45 UTC
## Steps to reproduce

Create a new C# project using `dotnet new`. Add the following line to a PropertyGroup:

```xml
<RuntimeIdentifiers>win10-x64; osx-10.11-x64</RuntimeIdentifiers>
```

Note the space after the semicolon; it is important. Then run `dotnet restore`.

## Expected  behavior

`dotnet restore` should succeed.

## Actual behavior

`dotnet restore` fails with a number of errors like this:
> System.Threading.Timer 4.0.1 provides a compile-time reference assembly for System.Threading.Timer on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with  osx.10.11-x64.

Although you can't see it above, there are actually two spaces between 'compatible with' and 'osx.10.11-x64'. Removing the space after the semicolon allows `dotnet restore` to succeed.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004040)

Product Information:
 Version:            1.0.0-preview3-004040
 Commit SHA-1 hash:  de5da5870f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by jeffkl** [comment] 2016-11-07 16:11
FYI @emgarten, not sure a group contact to send this to.

This should be opened against NuGet.  The issue is the [Split](https://github.com/NuGet/NuGet.Client/blob/4f85794855737b27c009b2169c00b718c4af01df/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs#L398) function called [here](https://github.com/NuGet/NuGet.Client/blob/4f85794855737b27c009b2169c00b718c4af01df/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs#L245) does not trim whitespace and/or the [RuntimeDescription](https://github.com/NuGet/NuGet.Client/blob/4cccb13833ad29d6a0bcff055460d964f1b49cfe/src/NuGet.Core/NuGet.RuntimeModel/RuntimeDescription.cs#L34) constructor does not clean up the user specified value.  From the code, it looks like any MSBuild property that is a semi-colon delimited list like `RuntimeSupports` would have the same problem.

One solution would be to have `Split` trim each item:
``` C#
private static string[] Split(string s)
{
    if (!string.IsNullOrEmpty(s))
    {
        return s.Split(new char[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(i => i.Trim()).ToArray();
    }

    return new string[0];
}
```

Or update the `RuntimeDescription` constructor to call `Trim()` (and any other constructor that takes a value which was originally a semi-colon delimited list).

**Comment by emgarten** [comment] 2016-11-07 16:57
@jeffkl thanks for the code snippet, this tracked on the nuget side here https://github.com/NuGet/Home/issues/3819

**Comment by jeffkl** [comment] 2016-11-07 16:58
Thanks, I looked for an open issue but couldn't find one!

**Comment by piotrpMSFT** [comment] 2016-11-09 06:41
Closing CLI issue in favor of NuGet/Home#3819

**Closed by piotrpMSFT** 2016-11-09 06:41 UTC
