### ISSUE TITLE
Code coverage for .net core applications

### ISSUE THREAD

**Issue by srini1978** [dotnet/cli#6010] opened 2017-03-11 11:05 UTC
## Steps to reproduce

1. Run .net core application with VSTS
2. Choose Analyze test with code coverage

## Expected  behavior

Code coverage should come up for each of the dlls

## Actual behavior

Multiple resultssets show up skewing up code coverage. Some internal dlls report code coverage multiple times

## Environment data
`dotnet --info` output:

**Comment by ChristophB125** [comment] 2017-03-13 16:54
@srini1978  I am trying to get code coverage working at the moment as well. Can you please share how you invoke dotnet test and which NuGet package you use for code coverage (I assume Microsoft.CodeCoverage). 
Possible duplicate of #1995 ?

**Comment by shanselman** [comment] 2017-03-14 23:41
@piotrpMSFT Did this ship with 1.0 or is this not done?

**Comment by livarcocc** [comment] 2017-03-14 23:51
I don't think this was explicitly done.

@codito @Faizan2304 Will this work out of the box because of vstest?

**Comment by piotrpMSFT** [comment] 2017-03-16 22:29
This issue was moved to Microsoft/vstest#621

**Closed by piotrpMSFT** 2017-03-16 22:29 UTC
