### ISSUE TITLE
'dotnet new --info' crashes the CLI

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5385] opened 2017-01-19 00:02 UTC
## Steps to reproduce
```
dotnet new --info
```

## Expected  behavior
Prints error message and doesn't crash

## Actual behavior
Crashes.

```
Specify --help for a list of available options and commands.

Unhandled Exception: Microsoft.DotNet.Cli.CommandLine.CommandParsingException: Unrecognized option '--info'
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.ParseOption(Boolean isLongOption, CommandLineApplication command, String[] args, Int32& index, CommandOption& option)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.New.NewCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004530)

Product Information:
 Version:            1.0.0-rc4-004530
 Commit SHA-1 hash:  4f0b7bd58c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15007
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004530
```

**Comment by piotrpMSFT** [comment] 2017-01-19 00:16
@DustinCampbell for RTM we're replacing `new` with `new3`. I just validated that `new3` does not exhibit this failure [kudos, @mlorbetske!]

**Comment by DustinCampbell** [comment] 2017-01-19 00:19
Great! I didn't realize new3 hadn't moved over yet. Are there other commands that have not yet moved?

**Comment by piotrpMSFT** [comment] 2017-01-19 00:20
new3 is the last. Just opened #5387 to track!

**Comment by piotrpMSFT** [comment] 2017-01-19 00:21
I'm closing this as dupe of #5387.

**Closed by piotrpMSFT** 2017-01-19 00:21 UTC

**Comment by DustinCampbell** [comment] 2017-01-19 00:23
Cool -- thanks!
