### ISSUE TITLE
Cleaner file structure when publishing please

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8840] opened 2018-03-18 17:45 UTC
@njbrown09 commented on [Wed Jan 17 2018](https://github.com/dotnet/core/issues/1226)

Can we please get a way to put everything but the binary in a folder? Its so frustrating having 50 DLLs in the same folder as the binary

---

@DevSidious commented on [Sat Jan 20 2018](https://github.com/dotnet/core/issues/1226#issuecomment-359176571)

I second that.

---

@Petermarcu commented on [Sun Mar 18 2018](https://github.com/dotnet/core/issues/1226#issuecomment-374021939)

In 2.1, I believe all the runtime/host features are there to put them wherever they want to be. The work would be in the SDK to allow for more options.

**Comment by fanoI** [comment] 2018-03-19 09:48
I'm really confused by the directory structure there is a not working .exe in the parent folder of "publish" with one or two DLL but the real one is inside "publish"? Why?

**Comment by livarcocc** [comment] 2018-03-19 18:14
This is a duplicate of https://github.com/dotnet/cli/issues/8764.

**Closed by livarcocc** 2018-03-19 18:14 UTC
