### ISSUE TITLE
dotnet build needs to have --packages <dir> equivalent to work with custom dotnet restore --packages

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/cli#3406] opened 2016-06-06 21:02 UTC
Currently (only by symlinking) for dotnet build there is no way to set the packages folder and it errors out with unresolved package errors.

This is useful for build tools to be able to specify

**Comment by brthor** [comment] 2016-06-06 21:30
This is a dupe of #2712

**Closed by brthor** 2016-06-06 21:30 UTC
