### ISSUE TITLE
Dotnet CLI does not build linked resource file correctly (while VS 2017 Preview does)

### ISSUE THREAD

**Issue by atanasa** [dotnet/cli#7309] opened 2017-07-28 12:51 UTC
## Steps to reproduce
- Create a console project that uses the new csproj format and targets the net451 framework
- Add a resource file to the project
- Add a link to text file to the resource file
- Build using dotnet cli (restore+build)

Sample project: 
[ReproLinkedResource.zip](https://github.com/dotnet/cli/files/1183077/ReproLinkedResource.zip)

## Expected  behavior
Reading the resource string should give the string content of the file.
`hello world!!!`

## Actual behavior
Reading the resource string in the sample project gives 
`hello.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;Windows-1252`

**Note: Building using Visual Studio 2017 Preview produces the correct build and the resource string has the correct value. The issues is observed when build with dotnet cli (2.0.0 preview 1 and preview 2)**

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

---------------
Visual Studio version: 15.3.0 Preview 6.0

---------------
This is silently breaking project converted to dotnet cli

**Comment by livarcocc** [comment] 2017-07-28 20:59
@rainersigwald I believe this is an issue in msbuild core, can you confirm?

**Comment by rainersigwald** [comment] 2017-07-28 21:12
Yes, this is a duplicate of https://github.com/Microsoft/msbuild/issues/308.

**Closed** 2017-07-28 21:31 UTC
