### ISSUE TITLE
Error MB2014 Microsoft.PackageDependencyResolution

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#9526] opened 2018-06-21 02:15 UTC
@SeanErvinson commented on [Wed Jun 20 2018](https://github.com/dotnet/core/issues/1715)

Having trouble building or running on the latest version of dotnet.

```
asean@asean:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```
What I have done:
-Remove entire dotnet core
-Clean install of dotnet core on Ubuntu 18.04.
-dotnet new console
-both dotnet build and dotnet run resulted in this error

<a href="http://i.imgur.com/n1Vs4u5.png">
  <img src="http://imgur.com/n1Vs4u5l.png" />
</a>

- also tried with an ASP.Net Core app same result

**Comment by livarcocc** [comment] 2018-06-21 04:13
@nguerrera this seems related to the cache we added. Though, I believe we have seen something like this in the past and the issue was some underlying corefx bug.

**Comment by nguerrera** [comment] 2018-06-21 19:43
Looks like a duplicate of dotnet/sdk#2251 which was moved to https://github.com/dotnet/corefx/issues/29820

@SeanErvinson What timezone are you on?

@krwq @tarekgh Is that bug fix ported to .NET Core 2.1 servicing by chance.

We can consider adding a workaround to the sdk if it has not been addressed in framework servicing.

**Comment by tarekgh** [comment] 2018-06-21 19:57
> Is that bug fix ported to .NET Core 2.1 servicing by chance.

No, I don't think this is ported to the servicing. this should repro only on a specific TZ. @SeanErvinson what is TZ you have in your machine? changing the TZ temporary during the build will help avoid this problem.

**Comment by nguerrera** [comment] 2018-06-21 20:01
See also https://github.com/dotnet/corefx/issues/29820#issuecomment-390690353 for a workaround that doesn't involve changing timezones, but will slow down your builds.

**Comment by SeanErvinson** [comment] 2018-06-22 04:30
I'm on (GMT+8) Asia/Manila.

**Comment by SeanErvinson** [comment] 2018-06-22 04:34
I went ahead and changed the timezone to Asia/Taipei and surprisingly it works now

**Comment by nguerrera** [comment] 2018-06-22 15:44
Closing as duplicate of dotnet/corefx#29820.

**Closed by nguerrera** 2018-06-22 15:44 UTC
