### ISSUE TITLE
dotnet restore fails on linux when run as a different user

### ISSUE THREAD

**Issue by rajkumar42** [dotnet/cli#4211] opened 2016-09-20 20:14 UTC
## Steps to reproduce

Login as user1, run "dotnet new" and "dotnet restore". 
Login as user2, run "dotnet new" and "dotnet restore" 
## Expected  behavior

"dotnet restore" should succeed for user2.
## Actual behavior

fails with the following error message
"Failed to create prime the NuGet cache. restore failed with: 1" 
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by piotrpMSFT** [comment] 2016-11-03 08:24
@rajkumar42 did you install via apt-get? DEB download? tar.gz?

Is that the full failure message you saw?

**Comment by piotrpMSFT** [comment] 2016-11-16 03:30
https://github.com/NuGet/Home/issues/3229 is the root cause.

**Comment by rajkumar42** [comment] 2016-11-18 05:06
@piotrpMSFT  apologies, only got to see the message today. I did the usual apt-get as suggested in the getting started page. I suppose you have identified the root cause. Please let me know if you need more info.

**Comment by piotrpMSFT** [comment] 2016-11-18 07:13
Thanks @rajkumar42. We've identified the root cause and are waiting for NuGet/Home#3229 to be addressed.

**Comment by blackdwarf** [comment] 2017-01-14 15:39
I believe the issue has been fixed in Nuget. Closing this. If it repros again, please reopen. Thanks!

**Closed by blackdwarf** 2017-01-14 15:39 UTC
Labels: external, Investigate
