### ISSUE TITLE
Dotnet publish with -r ubuntu-x64 and --self-contained=false fails to find framework

### ISSUE THREAD

**Issue by tylerphelan** [dotnet/cli#10602] opened 2019-01-14 15:59 UTC
## Steps to reproduce
```
$ docker run -it ubuntu:18.04 bash
$ apt-get update
$ apt-get install liblttng-ust0 libcurl3 libssl1.0.0 libkrb5-3 zlib1g libicu60 -y
$ dotnet --version
> 2.2.101
$ dotnet --list-runtimes
> Microsoft.AspNetCore.All 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.NETCore.App]
$ dotnet new webapi
$ dotnet publish -r ubuntu-x64 --self-contained=false
$ cd bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
$ ./project --server.urls http://0.0.0.0:8080
> The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

## Expected  behavior

We are not sure if this is a valid workflow but we expected `Microsoft.AspNetCore.App` to be found.

## Actual behavior

The error seen above with missing framework.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    29ae5ac2c2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /tmp/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.101 [/tmp/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.NETCore.App]
```

This is using an SDK built from source against ubuntu 18.04 and everything else seems to be working: https://github.com/dotnet/cli/blob/master/Documentation/project-docs/developer-guide.md#buildingrunning

I don't see why the framework wouldn't be found. Should this workflow with `dotnet publish -r ubuntu-x64 --self-contained=false` be valid? I've found some other issues where the `-r` flag and `--self-contained=false` are used together. What should we expect to happen in this case? Is the app packaged with the specific runtime but not entirely self-contained?

Thanks for the help!

**Comment by livarcocc** [comment] 2019-01-14 17:35
You passed self-contained as false, that means the app is not self-contained, so it won't pack the framework with it. What this does though, it make an executable available while keeping it as a framework dependent app. That's the way we found to let you produce your app as a Framework Dependent App with an executable.

The app fails to run for you because it can't find a framework to run against, as your framework is not installed in the default location for the OS. I see it under /tmp/dotnet. If you want this to work, you should set DOTNET_ROOT and point it to that location.

Otherwise, if you actually want a self-contained app (with the runtime distributed with the app), then don't pass --self-contained false.

**Comment by tylerphelan** [comment] 2019-01-14 19:22
@livarcocc Thank you for the quick response!

After the steps above and adding the 2.2.0 frameworks just to be safe:
```
$ dotnet --list-runtimes
> Microsoft.AspNetCore.All 2.2.0 [/tmp/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.2.0 [/tmp/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.2.0 [/tmp/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.NETCore.App]
$ export DOTNET_ROOT=/tmp/dotnet
$ ./project --server.urls http://0.0.0.0:8080
> It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2019-01-14 21:34
Which steps exactly did you follow? That would be helpful to diagnose what is going on. When you use an executable with a framework dependent app, it has special logic to try to find the runtime that it can use. Differently from using dotnet <path_to_dll>, we can't use the runtimes next to dotnet itself, as you haven't invoked the app with it.

Instead, we rely on this DOTNET_ROOT variable if your runtime is not installed in the default location. I think I gave you wrong information above when I told you to point it to `/tmp/dotnet`. Can you try pointing it to `/tmp/dotnet/dotnet`? That is, if you want to use a FDD app with an executable. If you want a regular SCD, then don't set --self-contained.

**Comment by tylerphelan** [comment] 2019-01-14 22:59
@livarcocc I still can't get it to find the runtimes. The full workflow is:

```
docker run -it ubuntu:18.04 bash
$ apt-get update
$ apt-get install liblttng-ust0 libcurl3 libssl1.0.0 libkrb5-3 zlib1g libicu60 liburcu6 libllvm3.9 liblldb-3.9 git -y
$ git clone https://github.com/dotnet/cli
$ cd cli && git checkout v2.2.102+dependencies
$ TERM=linux DropSuffix=true ./build.sh /t:Compile
$ cp -r bin/2/linux-x64/dotnet /tmp/
$ export DOTNET_ROOT=/tmp/dotnet/dotnet (also tried /tmp/dotnet)
$ /tmp/dotnet/dotnet --version
> 2.2.101
$ /tmp/dotnet/dotnet --list-runtimes
> Microsoft.AspNetCore.All 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.2.1 [/tmp/dotnet/shared/Microsoft.NETCore.App]
$ mkdir /tmp/project && cd /tmp/project
$ /tmp/dotnet/dotnet new webapi
$ /tmp/dotnet/dotnet publish -r ubuntu-x64 --self-contained=false
$ cd bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
$ ./project --server.urls http://0.0.0.0:8080
> The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment] 2019-01-14 23:15
`DOTNET_ROOT` is expected to be a directory where `dotnet` resides, so should be `/tmp/dotnet` in this case (which you tried, but that is the expected value).

I would also only set it when running the application (the output exe from the publish operation):

```
DOTNET_ROOT=/tmp/dotnet ./project --server.urls http://0.0.0.0:8080
```

Could you try also running with `COREHOST_TRACE=1` and paste the output?  That will cause the runtime to output some probing path diagnostics:

```
COREHOST_TRACE=1 DOTNET_ROOT=/tmp/dotnet ./project --server.urls http://0.0.0.0:8080
```

I'll see if I can reproduce this myself to figure out the problem.

**Comment by peterhuene** [comment] 2019-01-14 23:50
It looks like `libhostfxr.so` and `libhostpolicy.so` are being copied to the publish directory for some reason despite `--self-contained=false`.  This is triggering a self-contained activation, which fails to find the self-contained runtime.

Note if you delete these two files it will activate in a framework-dependent way, but will fail to activate because the fallback folder only contains the `2.2.0` host policy and not `2.2.1`.

Investigating why that is.

**Comment by peterhuene** [comment] 2019-01-15 00:44
This is a legitimate 2.2 issue that reproduces with applications targeting `Microsoft.AspNetCore.App` preventing them from publishing correctly for framework-dependent deployments.

It has been fixed in 3.0 as a result of the "build/publishing unification changes" but I believe may warrant a servicing fix.

I'll have a detailed explanation soon.

**Comment by peterhuene** [comment] 2019-01-15 01:43
There has been a bug since 2.1 regarding framework-dependent publishing of ASP.NET Core applications.

In 2.1 for a framework-dependent publish of an ASP.NET Core application, we copy `apphost` (not customized and useless for activation) and the `libhost*` libraries to the publish output.  This is because of the `ResolvePublishAssemblies` task in the SDK and how it fails to properly traverse shared framework dependencies (i.e. `Microsoft.AspNetCore.App` -> `Microsoft.NETCore.App`) when resolving assets.  Thus when ASP.NET Core moved to a shared framework, the task was outputting a whole bunch of files for the publish operation to copy.  However, the publish conflict resolution suppresses most of them, leaving only the `apphost` and `libhost*` libraries actually copied.  This ultimately resulted in a few unneeded files in the publish output.

In 2.2, we added the customized framework-dependent apphost.  Because of this existing bug, the customized apphost attempts to activate in a self-contained fashion because it discovers the `libhost*` shared libraries in the publish output.  This results in a framework-dependent application that cannot activate via the apphost (it can still be activated with `dotnet` like in 2.1, however).

We have a test coverage hole here too: the automated test was using a `Microsoft.NETCore.App` targeted project to build and then run via the framework-dependent apphost, which succeeds because the `libhost*` libraries are **not** copied.  I need to review the test plan as I'm pretty sure there should have been ASP.NET Core coverage in the manual case.

**Comment by peterhuene** [comment] 2019-01-15 01:48
As noted, in my previous comment: this is no longer a bug in 3.0 because of the work done to unify the build and publish asset resolution for copy-local, which now uses `ResolvePackageAssets` which handled this case correctly.

**Comment by tylerphelan** [comment] 2019-01-15 14:41
@livarcocc @peterhuene  Thanks for looking into it! Here's the output from `COREHOST_TRACE=1 DOTNET_ROOT=/tmp/dotnet ./project --server.urls http://0.0.0.0:8080` if you still need it:
```
$ COREHOST_TRACE=1 DOTNET_ROOT=/tmp/dotnet ./project --server.urls http://0.0.0.0:8080
> Tracing enabled
--- Invoked apphost [version: 2.2.0, commit hash: 1249f08feda72b116c7e6e4e9a390671883c797d] main = {
./project
--server.urls
http://0.0.0.0:8080
}
The managed DLL bound to this executable is: 'project.dll'
Resolved fxr [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/libhostfxr.so]...
Invoking fx resolver [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/libhostfxr.so] v2
Host path: [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project]
Dotnet path: [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/]
App path: [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.dll]
Tracing enabled
--- Invoked hostfxr v2 [commit hash: 1249f08feda72b116c7e6e4e9a390671883c797d] main
Checking if CoreCLR path exists=[/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/libcoreclr.so]
--- Executing in a native executable mode...
Using dotnet root path [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/]
App runtimeconfig.json from [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.dll]
Runtime config is cfg=/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.runtimeconfig.json dev=/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.runtimeconfig.dev.json
Attempting to read runtime config: /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.runtimeconfig.json
Attempting to read dev runtime config: /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.runtimeconfig.dev.json
Runtime config [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/project.runtimeconfig.json] is valid=[1]
--- Resolving FX directory, name 'Microsoft.AspNetCore.App' version '2.2.0'
Searching FX directory in [/tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish]
Attempting FX roll forward starting from [2.2.0]
'Roll forward on no candidate fx' enabled with value [1]. Looking for the least production greater than or equal to [2.2.0]
No production greater than or equal to [2.2.0] found. Looking for the least preview greater than [2.2.0]
No preview greater than or equal to [2.2.0] found.
Applying patch roll forward from [2.2.0]
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /tmp/project/bin/Debug/netcoreapp2.2/ubuntu-x64/publish/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment] 2019-01-15 19:20
Note that you should be able to delete `libhost*.so` from the publish directory and have it activate as FDD.  However, this won't work in the Docker example above because the shared host is not present in the build output from building the CLI.  A .NET Core install, however, should have the shared host present and thus should activate correctly.

**Comment by peterhuene** [comment] 2019-01-15 21:24
Unfortunately my last statement was incorrect; the deps file will still list the apphost package and dependencies, which won't get resolved properly at runtime even with the `libhost*.so` files deleted.

I'm investigating a proper fix for this now.

**Comment by peterhuene** [comment] 2019-01-31 19:38
Hi @tylerphelan.  I wanted to thank you again for reporting this issue to us and helping us diagnose the problem.

A fix has been approved for a forthcoming servicing release of the .NET Core SDK.  I'll comment again on this issue once the fix has been merged and I can inform you which release it will be going into.

**Comment by tylerphelan** [comment] 2019-02-06 22:37
Great, thanks for the update! Sounds good!

**Comment by peterhuene** [comment] 2019-02-13 05:23
Hi @tylerphelan.  The fix for this has now been merged and should be in an upcoming release of the .NET Core SDK.

I'm going to close this issue.  Please reopen if you feel the issue hasn't been properly addressed.  Thanks!

**Closed by peterhuene** 2019-02-13 05:23 UTC
Labels: Servicing-approved, bug
