### ISSUE TITLE
newly installed dotnet cli not working on hello world

### ISSUE THREAD

**Issue by chuck-mitchell** [dotnet/cli#969] opened 2016-01-22 17:35 UTC
Just installed dotnet cli on Windows and simplest test case doesn't work:

C:\git\repos\DotNet\Projects\Hello>dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

C:\git\repos\DotNet\Projects\Hello>dotnet new
Created new project in C:\git\repos\DotNet\Projects\Hello.

C:\git\repos\DotNet\Projects\Hello>ls
    C:\git\repos\DotNet\Projects\Hello\*.*
NuGet.Config  Program.cs    project.json
    12288 (850) bytes in 3 files

C:\git\repos\DotNet\Projects\Hello>dotnet restore
Failed to initialize CoreCLR, HRESULT: 0x80070057

C:\git\repos\DotNet\Projects\Hello>

**Comment by brthor** [comment] 2016-01-22 20:38
How did you install @chuck-mitchell ? Also what version of windows are you on?

**Comment by chuck-mitchell** [comment] 2016-01-22 20:43
Windows(X64) 10.0.10586

I installed following directions for Windows on "http://dotnet.github.io/getting-started/"  

https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi

**Comment by bartw** [comment] 2016-01-22 20:44
I get the same error.
I installed the msi and Visual C++ Redistributable for Visual Studio 2015 found on http://dotnet.github.io/getting-started/,

**Comment by brthor** [comment] 2016-01-22 20:48
There is a known issue with the default install location of the msi this week. I'm not sure if this has the same root cause but you may try installing to the drive root (e.g. C:\dotnet ) as a workaround.

Fixes for that particular issue should be incoming today.

**Comment by Jeffiy** [comment] 2016-01-23 03:37
I get the same error. and fix it as @brthor say:
> installing to the drive root (e.g. C:\dotnet )

**Comment by bartw** [comment] 2016-01-23 06:20
The solution by @brthor fixed it for me too.

**Comment by piotrpMSFT** [comment] 2016-01-26 18:23
Folks, can you give this a shot with default install path? This was fixed by #525. If you still see a repro, please reopen this issue.

**Closed by piotrpMSFT** 2016-01-26 18:23 UTC

**Comment by brthor** [comment] 2016-01-26 19:22
Tested this out with the latest MSI and not hitting any issues. If anyone is still hitting this please share details!

![spaces_in_path](https://cloud.githubusercontent.com/assets/14280892/12591926/019e47e4-c41f-11e5-93b0-75b4d23164ee.PNG)
