### ISSUE TITLE
dotnet test fails: dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#4914] opened 2016-12-04 04:18 UTC
## Steps to reproduce

clone https://github.com/onovotny/bc-csharp and check out the `netstandard` branch.

use dotnet restore, dotnet build and then dotnet test
## Expected  behavior
tests should run

## Actual behavior
Test run for C:\dev\bc-sharp\crypto\test\bin\Debug\net462\crypto.test.dll(.NETFramework,Version=v4.6.2)
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

Test run for C:\dev\bc-sharp\crypto\test\bin\Debug\netcoreapp1.1\crypto.test.dll(.NETCoreApp,Version=v1.1)
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14965
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment] 2016-12-04 10:39
Dupe of #4744 [which is fixed :)]

**Closed by piotrpMSFT** 2016-12-04 10:39 UTC

**Comment by onovotny** [comment] 2016-12-04 13:27
Do you know if the preview4-series tooling works with the current VS 2017 RC? Trying not to break things terribly ;)

**Comment by piotrpMSFT** [comment] 2016-12-10 00:39
Towards the end they diverged due to the Sdk attribute.
