### ISSUE TITLE
dotnet executable included in standalone app publish directory

### ISSUE THREAD

**Issue by russellhadley** [dotnet/cli#2349] opened 2016-04-07 21:52 UTC
## Steps to reproduce

dotnet publish standAloneApp

## Expected  behavior

publish directory should not have 'dotnet' executable in it, just assemblies and target dependent host launcher exe.

## Actual behavior

'dotnet' executable is included

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-002184)

Product Information:
 Version:     1.0.0-beta-002184
 Commit Sha:  9f23b7adf5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by russellhadley** [comment] 2016-04-08 04:14
@blackdwarf This was the case I was seeing where the dotnet executable was put in the publish directory.

**Comment by GuardRex** [comment] 2016-04-08 04:17
![capture](https://cloud.githubusercontent.com/assets/1622880/14374044/ea36408a-fd16-11e5-998b-51bce498dbd1.PNG)

Yep! Here, too.

**Comment by blackdwarf** [comment] 2016-04-12 12:50
/cc @brthor @Sridhar-MS 

I don't think this is right. For self-contained app, the host should be the app's "exe" and we shouldn't need a "vanilla" dotnet.exe in there, right?

**Comment by GuardRex** [comment] 2016-04-12 14:47
Update: This is **not** repro'ing here any longer.

**Comment by piotrpMSFT** [comment] 2016-04-12 17:20
Closing since @GuardRex confirmed this no longer repros. Please reopen if you see this again.

**Closed by piotrpMSFT** 2016-04-12 17:20 UTC
Labels: bug

**Comment by davojc** [comment] 2016-07-07 10:23
This appears to be happening again with the latest version. Just a dll for netcoreapp1.0 and no executable.

**Comment by GuardRex** [comment] 2016-07-08 06:41
@davojc I'm not seeing it here (`1.0.0-preview3-003171`). Can you put up a repro?
