### ISSUE TITLE
Why not support install on  Win7 SP1 32bit system

### ISSUE THREAD

**Issue by csdanping** [dotnet/cli#1401] opened 2016-02-15 07:06 UTC
the download msi package can not install on win7 sp1 32bit system
I just want to test my runtime on my customer desktop pc

**Comment by MaherJendoubi** [comment] 2016-02-15 09:05
Hi there,
I have the same issue on windows 7 sp1 64-bit system. Here is the log:

[1888:19CC][2016-02-15T10:05:01]i001: Burn v3.10.0.2103, Windows v6.1 (Build 7601: Service Pack 1), path: C:\Users\M_Jendoubi\Downloads\dotnet-win-x64.latest.exe
[1888:19CC][2016-02-15T10:05:01]i000: Initializing string variable 'BuildType' to value 'Release'
[1888:19CC][2016-02-15T10:05:01]i000: Initializing string variable 'DisplayVersion' to value '1.0.0.001306'
[1888:19CC][2016-02-15T10:05:01]i000: Initializing string variable 'ReleaseSuffix' to value 'beta'
[1888:19CC][2016-02-15T10:05:01]i000: Initializing string variable 'DOTNETHOME' to value '[ProgramFiles6432Folder]dotnet'
[1888:19CC][2016-02-15T10:05:01]i009: Command Line: '-burn.unelevated BurnPipe.{5FDA24F9-057B-4C0B-95F1-4DE39CD972CF} {DFE79318-E276-4C70-A76D-6E6CF5A29F95} 8768'
[1888:19CC][2016-02-15T10:05:01]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\M_JEND~1\AppData\Local\Temp\Microsoft_Dotnet_CLI_for_Windows_(1.0.0.001306_beta)_20160215100501.log'
[1888:19CC][2016-02-15T10:05:01]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\M_Jendoubi\Downloads\dotnet-win-x64.latest.exe'
[1888:19CC][2016-02-15T10:05:01]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\M_Jendoubi\Downloads\'
[1888:19CC][2016-02-15T10:05:01]i000: Setting string variable 'WixBundleName' to value 'Microsoft Dotnet CLI for Windows (1.0.0.001306 beta)'
[1888:19CC][2016-02-15T10:05:01]i000: Setting string variable 'WixBundleManufacturer' to value 'Microsoft Corporation'
[1888:10DC][2016-02-15T10:05:01]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[1888:10DC][2016-02-15T10:05:01]i000: Setting version variable 'WixBundleFileVersion' to value '1.0.0.1306'
[1888:19CC][2016-02-15T10:05:02]i100: Detect begin, 1 packages
[1888:19CC][2016-02-15T10:05:02]i000: Registry key not found. Key = 'SOFTWARE\dotnet\Setup'
[1888:19CC][2016-02-15T10:05:02]i052: Condition 'PreviousInstallFolder' evaluates to false.
[1888:19CC][2016-02-15T10:05:02]e000: Error 0x8002000a: Failed to convert version: 1.0.16759.1448007803 to DWORD64 for ProductCode: {3221C7B4-0EC1-4B1E-8F1C-1B6321C1E6C2}
[1888:19CC][2016-02-15T10:05:02]e151: Detect failed for package: dotnet_win_x64.1.0.0.001306.msi, error: 0x8002000a
[1888:19CC][2016-02-15T10:05:02]i101: Detected package: dotnet_win_x64.1.0.0.001306.msi, state: Unknown, cached: None
[1888:19CC][2016-02-15T10:05:02]i199: Detect complete, result: 0x8002000a

Hope that helps!
Best

**Comment by robmen** [comment] 2016-02-15 10:09
@Sridhar-MS currently each "dotted-part" of a version supports values from 0-655365. `1448007803` from the version number `1.0.16759.1448007803` is a pretty extreme build number. Is that the correct value?

**Comment by Sridhar-MS** [comment] 2016-02-16 17:31
We stopped using this version number `1.0.16759.1448007803` a long time time back. Currently the version number uses this template - `"{Major}.{Minor}.{Patch}.{CommitCount}`. This is encoded as a 3 part MSI version in [here](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/Utils/BuildVersion.cs)

@MaherJendoubi How old is the installer that you are trying to use? Is there a previous version of CLI that has been installed in that machine?

**Comment by Sridhar-MS** [comment] 2016-02-16 17:33
@csdanping We currently do not produce 32bit version of the CLI. I am not very sure about the plans for the 32bit installer.

/cc: @piotrpMSFT @blackdwarf

**Comment by robmen** [comment] 2016-02-16 17:38
@Sridhar-MS the interesting thing is the log @MaherJendoubi provided is a Bundle log file. Which means it came from a fairly recent build. I think that the issue is there is a old MSI already on the machine with the "extreme version number" and we're having problems removing it.

@MaherJendoubi can you try removing the existing .NET Core from your Add/Remove Programs (er, Programs and Features) control panel then installing again?

**Comment by MaherJendoubi** [comment] 2016-02-16 21:07
@robmen I succeeded to uninstall AspNet5.ENU.RC1_Update1_KB3137909.exe but I still trying to uninstall AspNet5.ENU.RC1 Update1.

**Comment by MaherJendoubi** [comment] 2016-02-16 21:58
@robmen it works thanks a lot Sir :+1:

**Comment by blackdwarf** [comment] 2016-02-23 15:15
This issue is referencing two distinct things, one is an ask for a feature (32-bit installer) and another is a bug in the x64 installer that is resolved. I will close this one and @csdanping can you open another issue and cc me in it for the 32-bit installer?

**Closed by blackdwarf** 2016-02-23 15:15 UTC
