### ISSUE TITLE
Cannot find namespace

### ISSUE THREAD

**Issue by adrianveliz** [dotnet/cli#3788] opened 2016-07-06 00:05 UTC
## Steps to reproduce
Build and run a hello world app.

mkdir test
cd test
dotnet new
dotnet restore
dotnet run

Then replace Program.cs with a new program with the only change being that it creates an ArrayList.

`
using System;
using System.Collections;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
			ArrayList al = new ArrayList();
            Console.WriteLine("Hello World!");
        }
    }
}
`
Afterwards, perform: 
dotnet restore 
dotnet run

## Expected  behavior
Successful compilation and run with the output "Hello World"

This exact same program works fine with csc and dmcs.

## Actual behavior
Project test (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling test for .NETCoreApp,Version=v1.0
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\Adrian\test\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
C:\Users\Adrian\test\Program.cs(10,4): error CS0246: The type or namespace 'ArrayList' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\Adrian\test\Program.cs(10,23): error CS0246: The type or namespace 'ArrayList' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    2 Error(s)

Time elapsed 00:00:01.7122205

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment] 2016-07-27 18:17
@adrianveliz due to the factoring in .NET Core, ArrayList is not in the `System.Collections` namespace anymore. You need to add [`System.Collections.NonGeneric`](https://www.nuget.org/packages/System.Collections.NonGeneric/) to your `project.json` and restore. I've confirmed that this solves the problem you are having. 

Will close this. Please reopen if you are still running into problems. For any API questions you can open issues on dotnet/corefx repo. Thanks!

**Closed by blackdwarf** 2016-07-27 18:17 UTC
