### ISSUE TITLE
dotnet-resgen aborts on Ubuntu 14.04

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#408] opened 2015-12-03 23:32 UTC
## Versions
``` sh
$ uname -a
Linux magrathea 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/LinuxLinux magrathea 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ aptitude show dotnet
Package: dotnet                          
New: yes
State: installed
Automatically installed: no
Version: 1.0.16772.1449108444-1
```

## Error
This happens when called via `dotnet [run|compile|publish]` but reproduces most easily with just `dotnet-resgen`

```sh
$ dotnet-resgen file.resx file.resource
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dep
endencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)                                                            
   at Microsoft.DotNet.Tools.Resgen.Program.WriteResourcesFileIfNotEmpty(String resxFilePath, String outputFile)
   at Microsoft.DotNet.Tools.Resgen.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Resgen.Program.Main(String[] args)
```

Running the above under strace, the assembly it's trying to load is `/usr/share/dotnet/bin/System.Xml.XDocument.dll`; the version of which is incorrect.

```sh
$ monodis --assembly /usr/share/dotnet/bin/System.Xml.XDocument.dll 
Assembly Table
Name:          System.Xml.XDocument
Hash Algoritm: 0x00008004
Version:       4.0.10.0
Flags:         0x00000001
PublicKey:     BlobPtr (0x00000bdd)
        Dump:
0x00000000: 00 24 00 00 04 80 00 00 94 00 00 00 06 02 00 00 
0x00000010: 00 24 00 00 52 53 41 31 00 04 00 00 01 00 01 00 
0x00000020: 07 D1 FA 57 C4 AE D9 F0 A3 2E 84 AA 0F AE FD 0D 
0x00000030: E9 E8 FD 6A EC 8F 87 FB 03 76 6C 83 4C 99 92 1E 
0x00000040: B2 3B E7 9A D9 D5 DC C1 DD 9A D2 36 13 21 02 90 
0x00000050: 0B 72 3C F9 80 95 7F C4 E1 77 10 8F C6 07 77 4F 
0x00000060: 29 E8 32 0E 92 EA 05 EC E4 E8 21 C0 A5 EF E8 F1 
0x00000070: 64 5C 4C 0C 93 C1 AB 99 28 5D 62 2C AA 65 2C 1D 
0x00000080: FA D6 3D 74 5D 6F 2D E5 F1 7E 5E AF 0F C4 96 3D 
0x00000090: 26 1C 8A 12 43 65 18 20 6D C0 93 34 4D 5A D2 93
```

The included runtime has 4.0.10, but `dotnet-resgen` wants 4.0.11. By overwriting it with the `System.Xml.XDocument.dll` from `"System.Xml.XDocument": "4.0.11-beta-23516",` `dotnet-resgen` happily works.

**Comment by shahid-pk** [comment] 2015-12-04 00:02
dotnet-resgen is not intended to be used standalone as of yet. dotnet use it internally

**Comment by andschwa** [comment] 2015-12-04 00:12
@shahid-pk As noted above, when `dotnet-resgen` is used by the `dotnet` tool in any of the above subcommands (`[run|publish|compile]`), the same error is produced, and the cause is as noted.

**Comment by brthor** [comment] 2015-12-04 00:15
`dotnet resgen` has this dependency in project.json

`"System.Xml.XDocument": "4.0.11-beta-23504"` so it's clear why that dependency is needed.

It's not clear why it's getting stomped on by a different version of system.xml.xdocument though.

Any thoughts @krwq @anurse ?

**Comment by andschwa** [comment] 2015-12-04 00:43
@brthor how do you guys get and package the DLLs that end up in `$DOTNET_HOME/{bin,runtime/coreclr}`?

**Comment by piotrpMSFT** [comment] 2015-12-05 01:41
$DOTNET_HOME is something we're eliminating the need for. In cases where it's needed, the bits can get there in many ways:
- native installer
- zip package
- build output

**Comment by piotrpMSFT** [comment] 2015-12-05 01:48
@gkhanna79 FYI

**Comment by davidfowl** [comment] 2015-12-05 06:50
@anurse bug with corehost?

**Comment by gkhanna79** [comment] 2015-12-06 18:23
@ramarag CC

**Comment by anurse** [comment] 2015-12-07 17:41
Sounds more like one of the other projects in dotnet-cli is stomping on the System.Xml.XDocument version since we publish to one flat folder. `corehost` just loads everything from the app folder.

**Comment by victorhurdugaci** [comment] 2015-12-07 17:42
Duplicate: https://github.com/dotnet/cli/issues/419

This is blocking the ASP.NET build.

**Comment by andschwa** [comment] 2015-12-08 19:53
A new build was pushed and I upgraded, but this bug is still present.

**Comment by anurse** [comment] 2015-12-08 20:10
Looks like this is caused by NuGet.Packaging pulling in System.Xml.XDocument 4.0.10, which is stomping on the build resgen uses. I'm going to revert resgen to 4.0.10 and see if that fixes the issue.

**Comment by davidfowl** [comment] 2015-12-09 05:56
Should be fixed by https://github.com/dotnet/cli/commit/02217b695f7d4f8ec79e13c12f918b650973759a

**Closed by davidfowl** 2015-12-09 05:56 UTC
Labels: bug

**Comment by andschwa** [comment] 2015-12-09 17:33
Great to hear it :smile:

**Comment by andschwa** [comment] 2015-12-16 22:03
This is indeed fixed with the latest package.
