### ISSUE TITLE
Global tools fail with csproj and obj/project.assets.json in current path

### ISSUE THREAD

**Issue by chamons** [dotnet/cli#9748] opened 2018-07-27 17:33 UTC
## Steps to reproduce
- git clone https://github.com/chamons/filed-bug-test-cases/tree/master/dotnet-global-tool-args
- make (to build and install my echo global tool)
- dotnet doit 42
- note that it works
- cd project
- dotnet doit 42
- note that it fails

```
rm Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": /usr/local/share/dotnet/sdk/2.1.302/Sdks/Microsoft.NET.Sdk/targets/GenerateDeps/GenerateDeps.proj
```

Full failure - https://gist.github.com/chamons/221a3bbed4afefc2e88c9ba48bd95a13

- rm -r obj
- dotnet doit 42
- note that it works
- 🤔 

## Expected  behavior
The content of a directory shouldn't affect a global tool launching

## Actual behavior
It somehow does

## Environment data
`dotnet --info` output: https://gist.github.com/a33a67e1bcf02829f365f2306a5090ce

**Comment by chamons** [comment] 2018-07-27 17:59
Workaround: `dotnet-doit` works fine.

**Comment by wli3** [comment] 2018-07-27 18:15
dotnet-doit is calling global tool. and `dotnet doit` invoked project tool. Is there a way to not adding the project tool? (remove the packagereference of the tool in csproj)

**Comment by wli3** [comment] 2018-07-27 19:52
If the problem is to distinguish project tools and global tools -- this is a fundamental design of dotnet cli. The [resolver](https://github.com/dotnet/cli/blob/08f050c012cb80bb9433cd401d9be866307e4687/src/Microsoft.DotNet.Cli.Utils/CommandResolution/DefaultCommandResolverPolicy.cs#L46) is used to resolve different dll for a same command according to the policy. The alternative would require explicit "policy" from commandline. It reduces usability too much. Also, since the immediate problem is solved. I'll close it as won't fix for now. cc @KathleenDollard

**Closed by wli3** 2018-07-27 19:52 UTC

**Comment by chamons** [comment] 2018-07-27 20:00
So this issue was created because I had a local project tool with the same name from when I was trying to figure things out. The error message isn't ideal, but user error here mostly.

**Comment by KathleenDollard** [comment] 2018-07-27 21:07
Thank you for posting this!
