### ISSUE TITLE
dotnet pack -v crashes

### ISSUE THREAD

**Issue by yizhang82** [dotnet/cli#9042] opened 2018-04-10 18:41 UTC
## Steps to reproduce

dotnet pack -v

## Expected  behavior

Don't crash

## Actual behavior

Crashes with:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by yizhang82** [comment] 2018-04-10 18:44
I know the correct command is to /v:detail, etc. But crashing with such callstack isn't very helpful.

**Comment by omajid** [comment] 2018-04-10 18:44
https://github.com/dotnet/cli/issues/8160 was another variant of the same issue.

**Comment by nguerrera** [comment] 2018-04-10 20:37
Duplicate of #8160

**Closed by nguerrera** 2018-04-10 20:37 UTC
