### ISSUE TITLE
.NET Core SDK needs to have a "Linux" build

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5854] opened 2017-02-26 21:32 UTC
There should be one download that will support glibc based Linux distros based on the "Linux" assets being produced in core-setup.

https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-linux-x64.latest.tar.gz

This will require that the CLI start building in one place and then testing those builds on various distros. This is a tracking item for this work in the 2.0 timeframe.

**Comment by piotrpMSFT** [comment] 2017-02-27 04:11
@Petermarcu is this going to be the story for all apps that ship atop the unified Linux distro? Build once, test everywhere? Since this sort of scenario is not readily supported by CI's, is there some drawback to building & testing everywhere, but only shipping the output of one of those builds? This is how we handle e.g. NuGet packages today and have not seen any issues...

**Comment by Petermarcu** [comment] 2017-02-27 07:18
There are likely two things. One is building the way the distros build and the other will be building in a "portable" way. We're looking at changing our CI in core-setup to be able to fire off tests to different Helix queues to get cross testing even from Jenkins. The shared framework needs to do this so we have to work through the CI problem. 

This is the first time we're doing this on Linux so I'm not sure it would be prudent to assume there won't be bugs when using native assets built on one distro on a different one. Its not something the linux ecosystem guarantees. We should meet to talk it through. In the short term, just getting one more leg that is the "Linux" leg and testing it on one distro would be a good start.

**Comment by Petermarcu** [comment] 2017-02-27 08:03
I may have misread what you said. I think what you are proposing could work but doing it that way would likely mean two builds.

This "Linux" version of the CLI is not what will go into native installers for each distro. Those would just reference the deb or rpm packages they depend on the way it works today I believe. So you would need to build and test the one that runs on the distro specific binaries and one that runs on the distro agnostic binaries.

Make sense? Let's meet and discuss.

**Comment by tmds** [comment] 2017-02-27 08:34
Duplicate of https://github.com/dotnet/cli/issues/5811?

**Comment by piotrpMSFT** [comment] 2017-02-27 20:30
@tmds @Petermarcu do we have a listing of linux distros for which we want to test the `Linux` binaries?

**Comment by Petermarcu** [comment] 2017-02-27 20:43
Yes, Its the same as the support matrix. I have a proposed list in an email somewhere I will dig up.

**Comment by livarcocc** [comment] 2017-02-28 19:27
@jgoshi has started iterating on this work.

**Comment by jgoshi** [comment] 2017-02-28 21:17
@Petermarcu what is the correct shared framework version number for this? I'm assuming the RID is linux-x64?

**Comment by Petermarcu** [comment] 2017-02-28 21:36
Do the versions here help? https://github.com/dotnet/core-setup

Yes, linux-x64 is the rid. Let me know if there are other questions I can answer. Note that we will not have native package manager installers for this version. No MSI's, PKG's, DEB's, or RPMS.

**Comment by jgoshi** [comment] 2017-02-28 21:51
For the master branch it shows failed build. We currently use this one: 2.0.0-beta-001509-00

Will that work for the Linux-x64 RID?

**Comment by ellismg** [comment] 2017-03-01 00:27
> We currently use this one: 2.0.0-beta-001509-00

It should, the NuGet package for [Microsoft.NETCore.App exists](https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.linux-x64.Microsoft.NETCore.App/2.0.0-beta-001509-00).

**Comment by jgoshi** [comment] 2017-03-09 22:25
We have this up and running in both Jenkins CI and VSO. There is currently just one remaining issue, test support for 2.0.
https://github.com/Microsoft/vstest/issues/494

Once that becomes available, doing the following two things will enable tests to run for the Linux portable builds.

1. In netci.groovy remove the check (near the bottom) that stops this statement from running on Linux portable builds Utilities.addMSTestResults(newJob, '**/*.trx')

2. In run-build.sh remove this property /p:CLITargets=\"Prepare;Compile;Package;Publish\" from the CUSTOM_BUILD_ARGS property.

Completing those two steps will allow Linux portable builds to run and validate tests.

**Comment by livarcocc** [comment] 2017-04-18 17:18
This is done and tests are enabled for the linux x64 portable distro.

**Closed by livarcocc** 2017-04-18 17:18 UTC
