### ISSUE TITLE
Debian Testing dotnetcli Segmentation fault

### ISSUE THREAD

**Issue by Bhaal22** [dotnet/cli#3940] opened 2016-07-26 13:47 UTC
## Steps to reproduce
* mkdir project
* cd project
* dotnet init

## Expected  behavior
* No segmentation fault

## Actual behavior
* Segmentation Fault (cf strace file attached)
[dotnet_init.strace.txt](https://github.com/dotnet/cli/files/383933/dotnet_init.strace.txt)

## Environment data
```
root@roth:~# lsb_release -da

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```

* Downloaded from this url : https://go.microsoft.com/fwlink/?LinkID=809130
```
john@roth$ dotnet -v
Telemetry is: Disabled
.NET Command Line Tools (1.0.0-preview2-003121)
Usage: dotnet [host-options] [command] [arguments] [common-options]
```

`dotnet --info` output:

```
john@roth$ dotnet info

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2671 ms
Segmentation fault
```

From GDB:
```
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:183
#1  0x00007f3f3bcede52 in CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) ()
   from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#2  0x00007f3f3bcedb10 in CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) ()
   from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#3  0x00007f3f3bcf29c1 in CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int) ()
   from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#4  0x00007f3f3bcf2c22 in WaitForSingleObjectEx () from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#5  0x00007f3f3ba41c61 in CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*) ()
   from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#6  0x00007f3f3ba46493 in Thread::RareDisablePreemptiveGC() () from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#7  0x00007f3f3b9e2b87 in JIT_RareDisableHelperWorker () from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
#8  0x00007f3f3ba762d2 in JIT_RareDisableHelper () from /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.so
```

**Comment by Bhaal22** [comment] 2016-07-26 16:14
Same behavior noticed with preview3 while trying to build cli itself

```
john@roth$ /home/john/dev/git/microsoft/cli/.dotnet_stage0/Linux/dotnet --version
1.0.0-preview3-003215
```

**Comment by blackdwarf** [comment] 2016-07-27 03:42
Dupe of #3681 .

**Closed by blackdwarf** 2016-07-27 03:42 UTC
