### ISSUE TITLE
dotnet build NRE

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1069] opened 2016-01-27 18:37 UTC
I made a mistake in my project.json file and I believe it is pointing to non-existing package. I ran `dotnet restore` and it did not complain. Then I tried building and I got:

```
PS C:\source\dotnetcli-aspnetcore\HelloMvc> dotnet build

Project HelloMvc will be compiled because expected outputs are missing.

Compiling HelloMvc for DNXCore,Version=v5.0
Object reference not set to an instance of an object.
```

Repro: 
1) clone my of dotnetcli-aspnetcore and sync to https://github.com/moozzyk/dotnetcli-aspnetcore/commit/7e037055d44b9c9f2cc08809c90e7c36323093e3 
2) dotnet restore
3) dotnet build

The problem in the project.json file is in this line https://github.com/moozzyk/dotnetcli-aspnetcore/commit/7e037055d44b9c9f2cc08809c90e7c36323093e3#diff-f1127d17f7513174ff115b8ec8a911c3R15. There is no "Microsoft.AspNetCore.Mvc": "6.0.0-*" package. There is only "Microsoft.AspNetCore.Mvc": "1.0.0-*". Still I would expect to get an error message and not an NRE. (I also think restore should have failed).

**Comment by jskeet** [comment] 2016-05-18 19:10
I would expect the "fit-n-finish" label to be for things which are a bit ugly, but don't actually cause any pain.

Currenty, I'm receiving this error message and I have no idea why. The complete lack of clue about the cause (I'm *guessing* it's a bug in my project.json...) makes this a bug to fix urgently IMO.

**Comment by natemcmaster** [comment] 2016-07-05 18:19
I've encountered this many times too (preview2-3150). There is no discernable way to identify the cause of the error because there is no stack trace produced.

Although this may not always be the cause of the error, I've encountered this most when checking out a branch with a TFM change or a project reference that was renamed. Build throws the error trying to build with stale lock files. Cleaning stale lock files--especially any lock files left behind by in folders that used to contain a project--usually solves the issue.

**Comment by piotrpMSFT** [comment] 2016-07-27 23:02
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

**Closed by piotrpMSFT** 2016-07-27 23:02 UTC
Labels: bug, fit-n-finish
