### ISSUE TITLE
Restore packages does not preserve package name cases

### ISSUE THREAD

**Issue by fractus** [dotnet/cli#11085] opened 2019-04-06 17:26 UTC
## Steps to reproduce
- Create a new project
- Add `Deedle` package 
- Restore packages into packages directory
```shell
$ dotnet new classlib -n Lib
...
$ dotnet add Lib.csproj package Deedle
...
$ cat Lib.csproj
...
  <ItemGroup>
    <PackageReference Include="Deedle" Version="2.0.1" />
  </ItemGroup>
...

$ dotnet restore --packages packages
  Restore completed in 906.43 ms for /home/vpap/temp/p1/Lib/Lib.csproj.

$ ll packages/
total 0
drwxrwxrwx 0 vpap vpap 512 Apr  6 18:13 deedle/
```

## Expected  behavior
Folder under packages should be `Deedle`.

## Actual behavior
Instead it is always in small case; `deedle`.

## Environment data
_(This is in Win10 WSL)_
`dotnet --info` output:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.202/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.202 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment] 2019-04-07 05:59
Hi @fractus.  Thanks for reporting an issue with us.

This is by design as NuGet stores the packages based on a normalized (lower case) name.  cc @nkolev92 from the NuGet team to confirm that this is the expected behavior.

Are you running into any problems with the way NuGet is storing the package?

**Comment by fractus** [comment] 2019-04-07 12:10
@peterhuene Thanks for your response; I wasn't aware of this normalization.

The reason I raised this is because some F# packages have scripts with include paths to the package directory; for example, see [FsLab.fsx](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.fsx).

**Comment by peterhuene** [comment] 2019-04-07 21:01
Given that NuGet will always store the package with the normalized name, I think the best approach is for the scripts to match the normalized casing, thus ensuring compatibility with platforms that have case-sensitive file systems.

@nkolev92 have there been other requests around this area regarding interactive F#, since it seems quite common to explicitly reference a search path into the package directory?

**Comment by nkolev92** [comment] 2019-04-08 17:08
PackageIds are case insensitive in NuGet so to prevent ambiguity they are always installed in the global packages folder with lowercase names. 

The F# package with scripts assuming the package management style is packages.config, so not sure those can work without amending the package itself. 

In packages.config world, the paths to packages were one of 2: 

`<sln root>/packages/PackageID.PackageVersion/<content>`
`<sln root>/packages/PackageID/<content>`

In PackageReference they are always:

`<global packages folder root>/pacakges/packageid/packageversion/<content>`

I would say actively looking for the paths of dependent packages for which you don't know the resolved version is a bad practice. 
Consider using build targets to do custom logic like that. 
GeneratePathProperty might help too. https://github.com/NuGet/NuGet.Client/pull/2271. It stores the full path to a given package id in an msbuild variable and allows for customization.

**Comment by peterhuene** [comment] 2019-04-08 18:34
Hi @fractus.  Does the above information make sense?  Is there additional feedback or changes you would like to see for this issue?

**Comment by fractus** [comment] 2019-04-08 20:24
@peterhuene @nkolev92 Thanks for the explanation - this is enough information for me to try a more robust alternative way. I will keep you posted.

**Comment by peterhuene** [comment] 2019-04-08 20:25
Thanks @fractus.  I'm going to close this issue for now, but feel free to reopen if you run into any issues.

**Closed by peterhuene** 2019-04-08 20:25 UTC
