### ISSUE TITLE
dotnet run of subproject not getting commandline args

### ISSUE THREAD

**Issue by russellhadley** [dotnet/cli#2286] opened 2016-04-05 21:33 UTC
Assumes an app (I'm running standalone) that takes arguments, one of which is '--help'

## Steps to reproduce

dotnet publish .\src\subproj
dotnet run -p .\src\subproj --help

## Expected  behavior

'--help' argument passed to the commandline app being run.

## Actual behavior

'--help' is parsed and passed to dotnet itself.

## Environment data
`dotnet --info` output:

 14:32:26 > dotnet --info
.NET Command Line Tools (1.0.0-beta-002222)

Product Information:
 Version:     1.0.0-beta-002222
 Commit Sha:  8f7ab0e61c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by russellhadley** [comment] 2016-04-05 21:37
@blackdwarf Here's the issue I was seeing.

**Comment by dleeapho** [comment] 2016-04-05 22:17
Have you tried escaping the args to the app with a double dash '--' :
`dotnet run -p .\src\subproj -- --help`

**Comment by russellhadley** [comment] 2016-04-05 23:13
@dleeapho that worked. So I guess this is more a discoverability bug.  Quick search in the engine didn't turn it up either.  Where should I expect to see this documented?

**Comment by blackdwarf** [comment] 2016-04-05 23:25
@russellhadley that is a good question, even I didn't know about this. @dleeapho how did you discover this and what are the semantics?

**Comment by dleeapho** [comment] 2016-04-06 15:24
Somewhat ironically, `dotnet run --help`
```
usage: dotnet [-f <arg>] [-c <arg>] [-p <arg>] [-h] [--] <args>...

    -f, --framework <arg>        Compile a specific framework
    -c, --configuration <arg>    Configuration under which to build
    -p, --project <arg>          The path to the project to run
                                 (defaults to the current directory).
                                 Can be a path to a project.json or a
                                 project directory
    -h, --help                   Help for compile native.
    <args>...                    Arguments to pass to the executable or
                                 script
```

**Comment by blackdwarf** [comment] 2016-04-06 15:40
So we need to document this in the help as well as in the docs.

**Comment by russellhadley** [comment] 2016-04-06 16:58
@blackdwarf @dleeapho I saw the dotnet run --help but I was unclear as to the semantics of [--] since it didn't have an explanation in the usage splash screen. It might just be my ignorance but it wasn't super clear.  At the same time the docs get updated we should add a blurb to help to cover it for users like me.

**Comment by blackdwarf** [comment] 2016-04-06 17:26
@russellhadley yup. Working on that now.

**Comment by krwq** [comment] 2016-04-06 17:35
shouldn't we be forwarding everything after project name? IMO this is an annoying bug even if it was by design a while ago

**Comment by blackdwarf** [comment] 2016-04-06 20:01
@krwq we should, ideally, but there could be some reason we are not.

**Comment by dleeapho** [comment] 2016-04-22 16:18
@krwg problem is that the `run` command has its own args so you need to separate the command args from the operands. Using `--` fits convention: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

**Comment by dleeapho** [comment] 2016-04-22 16:31
This recently regressed, #2643

**Comment by blackdwarf** [comment] 2016-05-20 03:23
Seems the #2643 is closed and fixed. I've added the `--` to the docs on http://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-run.html. With this, will close this one. Reopen if all of this is not solving it.

**Closed by blackdwarf** 2016-05-20 03:23 UTC
Labels: documentation
