### ISSUE TITLE
In a command window, 'dotnet tool list --global' does not list any global tools

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#9127] opened 2018-04-24 13:39 UTC
## Steps to reproduce
1. Install CLI for .NET Core 2.1 (version 2.1.300-rc1-008662)
2. Open command window and run
`dotnet tool list --global`

## Expected  behavior
List all the global tools

## Actual behavior
No global tools are listed

![image](https://user-images.githubusercontent.com/8246794/39190822-445c13ea-478a-11e8-8b4d-4e6a72c517d7.png)

**Comment by livarcocc** [comment] 2018-04-24 16:54
@peterhuene can you take a look?

**Comment by wli3** [comment] 2018-04-24 17:28
@balachir what tool is installed that you expect to see? could you show us the content under c:\Users\fwtlaba\.dotnet\tools ?

Also the second command _dotnet tool list_ is not valid and the error is expected

**Comment by peterhuene** [comment] 2018-04-24 19:34
As @wli3 mentioned, the second error is expected since either of the two options specified are required.

Regarding the output of `dotnet tool list --global`, that is the expected output if no tools have been installed globally.  Is that the case?  Following Will's suggestion should help answer that.

**Comment by balachir** [comment] 2018-04-25 11:14
I don't have a ```c:\Users\fwtlaba\.dotnet\tools``` folder. Did something not get initialized correctly? I even tried running ```dotnet new console``` to make sure any initialization completed, but my folder still looks like below. 

![image](https://user-images.githubusercontent.com/8246794/39242193-15ccdfe6-483e-11e8-8462-baf3d4047ba5.png)

**Related question**: Is ```c:\Users\fwtlaba\.dotnet\tools``` the folder where the global tools like Microsoft.EntityFrameworkCore.Tools.DotNet and Microsoft.Extensions.SecretManager.Tools get installed?

/cc: @bricelam @natemcmaster

**Comment by natemcmaster** [comment] 2018-04-25 14:26
> Related question: Is c:\Users\fwtlaba\.dotnet\tools the folder where the global tools like Microsoft.EntityFrameworkCore.Tools.DotNet and Microsoft.Extensions.SecretManager.Tools get installed?

No. Those binaries are installed along with the rest of the sdk files in C:/Program Files/dotnet/sdk/$version

**Comment by wli3** [comment] 2018-04-25 17:27
@balachir all the that will show up in `dotnet tool list` requires explicit `dotnet tool install -g packageid`. If a tool does not require it. It might be a bundled tool, project tool, or custom configured packages like xunit runner.

**Comment by livarcocc** [comment] 2018-04-25 20:17
Closing this as not a bug.

The bundled SDK tools ship as native verbs on the CLI and should not appear as global tools, which is the current behavior.

If you happen to install a global tool (like dotnet-cowsay) and that is not listed, then comment or file a new issue and we can investigate.

**Closed by livarcocc** 2018-04-25 20:17 UTC
Labels: Blocking-RTM

**Comment by balachir** [comment] 2018-04-26 14:40
Thanks for the clarifications everyone!
