### ISSUE TITLE
Explicitly run first-time experience

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/cli#9233] opened 2018-05-09 03:52 UTC
Hi,

I'm automating the creation of virtual machines that will be used as build servers.

After installing the .NET Core SDK through the Visual Studio 2017 Installer, the first-time experience does not appear to be run. Thus, on the first build that happens on that server, that build includes the first-run experience.

Since my build process attempts to build multiple projects in parallel, various instances of `dotnet` choke over the first-use sentinel when attempting concurrent writes:

```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

My.DotNet.Project.dll (net47) ExitCode = 1
System.IO.IOException: The process cannot access the file 'C:\Users\BuildServerUser\.dotnet\2.1.104.dotnetFirstUseSentinel' because it is being used by another process.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.PrintFirstTimeUseNotice()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Is there a sensible way to kick off this process automatically at the time that the VM is created, rather than at the time of the first build? I'd rather do it eagerly than lazily.

Thanks.

**Comment by Kralizek** [comment] 2018-05-09 08:43
Not a contributor!

In the docker image, I see they do `dotnet new` with a comment about "first experience". I'd give it a try ;)

**Comment by yaakov-h** [comment] 2018-05-09 08:49
Hmm, looks like they use `dotnet help` [here](https://github.com/dotnet/dotnet-docker/blob/master/2.1/sdk/alpine3.7/amd64/Dockerfile#L30). That's a good idea... I saw something about `--version` skipping the first use setup, but I didn't think of help.

**Comment by bergmeister** [comment] 2018-05-09 11:30
@yaakov-h You can just an environment variable with name `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` to 1.
I do this in my builds as well using PowerShell:
```powershell
[Environment]::SetEnvironmentVariable("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", 1)
```

**Comment by yaakov-h** [comment] 2018-05-09 11:31
Does that still populate the NuGet Fallback folders, though?

**Comment by bergmeister** [comment] 2018-05-09 11:32
I think so but I don't know

**Comment by Kralizek** [comment] 2018-05-09 13:12
@bergmeister AFAIK, this will not fill in the fallback folder nor download the default global tools if needed.

**Comment by livarcocc** [comment] 2018-05-09 16:53
@bergmeister confirming that setting that environment variable to true will not do the cache population.

I would suggest using `dotnet new` to trigger the first run when setting up the VM.

**Comment by vcsjones** [comment] 2018-05-31 00:05
Seems like this is a dupe of  #4919.

**Comment by livarcocc** [comment] 2018-05-31 16:33
Agreed.

**Closed by livarcocc** 2018-05-31 16:33 UTC
