### ISSUE TITLE
Install global tool failed with error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'any'.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#11190] opened 2019-04-18 07:48 UTC
## Steps to reproduce
Require: machine also install netcoreapp2.1 runtime since "dotnetsay" is targeting 2.1. This should not be required when netcoreapp3.0 is released and dotnetsay is updated
1. Create empty directory
2. not yet implemented Run dotnet new tool-manifest
	a. In the meantime copy the following and create file called dotnet-tools.json
 
{
"version": 1,
"isRoot": true,
"tools": {}
}
3. cd to the directory with manifest file
4. run dotnet tool install dotnetsay
## Expected  behavior
Run dotnet tool install dotnetsay succeeded.

## Actual behavior
Run failed with error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'any'.
![image](https://user-images.githubusercontent.com/33921754/56344804-e72c5b80-61f0-11e9-9813-28f48c941a6d.png)

## Environment data
D16.0/28803.202(16.0.2) + CLI/SDK: 3.0.100-preview5-011354
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011354
 Commit:    3796a49205

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011354\

Host (useful for support):
  Version: 3.0.0-preview5-27617-04
  Commit:  f28abecf15

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011354 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19217-04 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27617-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27617-04 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by wli3** [comment] 2019-04-18 21:05
Root cause is this https://github.com/dotnet/sdk/issues/3135

**Comment by dsplaisted** [comment] 2019-04-18 21:35
This should be fixed by https://github.com/dotnet/cli/pull/11166 and https://github.com/dotnet/sdk/pull/3136.  I'll leave this open for now for validation.

**Closed** 2019-04-24 00:11 UTC
Labels: tool
