### ISSUE TITLE
dotnet restore and run do not work reliable

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8746] opened 2018-03-08 16:16 UTC
@ecwan commented on [Fri Mar 02 2018](https://github.com/dotnet/core/issues/1320)

General
```dotnet --version```
1.1.5
running on Windows 7 

steps to reproduce it on my system:

```cd myproject```

```dotnet restore```

 ...
  Restore completed in 20,87 sec for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.

-> everything looks fine

```dotnet run sample1```

CSC : error CS0006: Metadata file 'C:\myproject\Workflow.Awl\bin\Debug\netstandard1.3\Workflow.Awl.dll' could not be found [C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj]

The build failed. Please fix the build errors and run again.

```dotnet restore```

  Restore completed in 31,33 ms for C:\myproject\Workflow.Awl\Workflow.Awl.csproj.
  Restore completed in 42,67 ms for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.

```dotnet run sample1```

The application to execute does not exist: 'C:\myproject\AWLReaderAndProcessor\bin\Debug\netcoreapp1.1\AWLReaderAndProcessor.dll'

```dotnet run sample1```

-> now does it work

Question: Why do I have to repeat the restore and run commands until it works?

My expectation: Every command like restore and run should already work the first time or give a clear indication about the current status.

**Comment by livarcocc** [comment] 2018-03-08 18:25
Can you share your project or a small repro in a repo on github?

Also, what OS are you using? Lastly, does this repro if you install the latest SDK (2.1.4)?

**Comment by ecwan** [comment] 2018-03-08 19:37
Hi.
The issue does exist on Windows 7 and NOT on Ubuntu.
I will try the latest SDK as proposed by you.
The project should not be made public. I would share it only with a single person.
The other way round: I have no clue how to isolate the root cause of the problem. If I would be able to do that would I try to create a test case ...
Every hint is welcome.
Regards,
Andreas

________________________________________
Von: Livar <notifications@github.com>
Gesendet: Donnerstag, 8. März 2018 19:26:00
An: dotnet/cli
Cc: Weiss, Andreas; Mention
Betreff: Re: [dotnet/cli] dotnet restore and run do not work reliable (#8746)

Can you share your project or a small repro in a repo on github?

Also, what OS are you using? Lastly, does this repro if you install the latest SDK (2.1.4)?

**Comment by livarcocc** [comment] 2018-03-09 17:49
Did this repro with the latest SDK?

**Comment by kasper3** [comment] 2018-03-10 10:37
`dotnet run sample1`, should it be just `dotnet run` in the root of solution or project directory? You can also use `dotnet run -p  path/to/sample1`

**Comment by livarcocc** [comment] 2018-03-11 18:24
@kasper3 you are correct. I missed that.

**Comment by ecwan** [comment] 2018-03-13 16:55
> dotnet run sample1, should it be just dotnet run in the root of solution or project directory?
No. "sample1" is a commandline parameter for my app and not the name of the project.

> Did this repro with the latest SDK?
Not yet. -> I will do some more tests.

Keep this ticket/case open the next two weeks. I will do more tests.

Thank you for the support!

**Comment by livarcocc** [comment] 2018-03-13 17:06
How about we close it and if you can still repro it in your tests we re-open?

**Comment by ecwan** [comment] 2018-03-14 11:56
The issue still exists!
It seems to relate the way I'm handling the project.
steps to reproduce:
1. create and run the project on Ubuntu
2. zip the project folder on Ubuntu and copy it to the Windows machine
3. extract the zip file
4. "enjoy" the unreliability

What can I do to debug the issue?



dotnet run sample1

CSC : error CS0006: Metadata file 'C:\myproject\Workflow.Awl\bin\Debug\netstandard1.3\Workflow.Awl.dll' could not be found [C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj]



dotnet restore

Restore completed in  ms for C:\myproject\Workflow.Awl\Workflow.Awl.csproj.
Restore completed in  ms for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.


dotnet run sample1

The application to execute does not exist: 'C:\myproject\AWLReaderAndProcessor\bin\Debug\netcoreapp1.1\AWLReaderAndProcessor.dll'



dotnet restore

Restore completed in  ms for C:\myproject\Workflow.Awl\Workflow.Awl.csproj.
Restore completed in  ms for C:\myproject\AWLReaderAndProcessor\AWLReaderAndProcessor.csproj.

dotnet run sample1

-> now does it work

dotnet --version

2.1.4

**Comment by livarcocc** [comment] 2018-05-11 22:58
If you are restoring the project on one machine, copying everything to another and doing a dotnet run on a different machine, that is not supported and will not work.

Your project.assets.json contains path information inside of it that do not translate across machines.

In this case, I would suggest copying only the code (exclude bin/obj) and doing another restore on the second machine and then a run.

Can you try that?

**Comment by ecwan** [comment] 2018-05-13 16:33
I will run a test after my vacation and provide the feedback.

Von: Livar [mailto:notifications@github.com]
Gesendet: Samstag, 12. Mai 2018 00:59
An: dotnet/cli
Cc: Weiss, Andreas; Mention
Betreff: Re: [dotnet/cli] dotnet restore and run do not work reliable (#8746)


If you are restoring the project on one machine, copying everything to another and doing a dotnet run on a different machine, that is not supported and will not work.

Your project.assets.json contains path information inside of it that do not translate across machines.

In this case, I would suggest copying only the code (exclude bin/obj) and doing another restore on the second machine and then a run.

Can you try that?

**Comment by ecwan** [comment] 2018-06-25 15:50
Hi Livar,
thank you very much.
It works fine.
Please close this case/ticket.
Regards,
Andreas

Von: Livar [mailto:notifications@github.com]
Gesendet: Samstag, 12. Mai 2018 00:59
An: dotnet/cli
Cc: Weiss, Andreas; Mention
Betreff: Re: [dotnet/cli] dotnet restore and run do not work reliable (#8746)


If you are restoring the project on one machine, copying everything to another and doing a dotnet run on a different machine, that is not supported and will not work.

Your project.assets.json contains path information inside of it that do not translate across machines.

In this case, I would suggest copying only the code (exclude bin/obj) and doing another restore on the second machine and then a run.

Can you try that?

**Closed** 2018-06-25 20:09 UTC
