### ISSUE TITLE
"dotnet add reference" produce a csproj with mixed eol characters

### ISSUE THREAD

**Issue by csleead** [dotnet/cli#8147] opened 2017-12-01 14:48 UTC
## Steps to reproduce
Create 2 projects and add project a reference from one of them to another
For example,
dotnet new classlib -o lib1
dotnet new classlib -o lib2
dotnet add lib1 reference lib2\lib2.csproj

## Expected  behavior
EOL characters of the csproj file should be CRLF

## Actual behavior
Both LF and CRLF exists in the csproj file.

## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by livarcocc** [comment] 2017-12-01 18:17
@peterhuene want to take a look?

**Comment by peterhuene** [comment] 2017-12-11 02:54
Hi @csleead: thank you for bringing this to our attention.

I believe this may have been fixed with work in MSBuild to normalize line endings, but I will confirm on Windows when I get a chacne.  On OSX, at least, it normalizes the entire file to LF.

**Comment by peterhuene** [comment] 2018-03-19 22:24
I've reproduced this in master:

```
C:\Users\peterhuene\tmp\lib1>diff lib1.csproj.orig lib1.csproj | cat -A
1,7c1,11$
< <Project Sdk="Microsoft.NET.Sdk">^M$
< ^M$
<   <PropertyGroup>^M$
<     <TargetFramework>netstandard2.0</TargetFramework>^M$
<   </PropertyGroup>^M$
< ^M$
< </Project>^M$
---$
> <Project Sdk="Microsoft.NET.Sdk">$
> $
>   <ItemGroup>^M$
>     <ProjectReference Include="..\lib2\lib2.csproj" />^M$
>   </ItemGroup>$
> $
>   <PropertyGroup>$
>     <TargetFramework>netstandard2.0</TargetFramework>$
>   </PropertyGroup>$
> $
> </Project>$
```

All but two CRLF get changed to LF.

**Comment by peterhuene** [comment] 2018-03-19 22:28
This appears to be a known issue that has yet to be addressed in MSBuild: Microsoft/MSBuild#1401.

**Comment by livarcocc** [comment] 2018-03-27 19:38
@peterhuene is there an action for us on this issue or should we dup it to the msbuild one? Or are we blocked on it?

**Comment by peterhuene** [comment] 2018-03-27 20:30
I think we can dupe it to that one since there isn't a fix on the CLI side needed.

**Closed by peterhuene** 2018-03-27 20:30 UTC
