### ISSUE TITLE
Projects containing periods/ dots create incorrect output assembly file on linux-arm (Folder.Name becomes Folder.Name.Name)

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/cli#6590] opened 2017-05-13 13:17 UTC
## Steps to reproduce
(Windows to create):
mkdir Folder.With.Dots
cd Folder.With.Dots
dotnet new console

Modify Folder.With.Dots.csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.0</TargetFramework>
        <RuntimeIdentifiers>win10-x64;linux-arm</RuntimeIdentifiers>
      </PropertyGroup>
    </Project>

dotnet restore
dotnet build
dotnet publish . --output Publish --configuration Release --runtime linux-arm

## Expected  behavior
Along with all the included files, the output assembly (which would Folder.With.Dots.exe on Windows) should be called "Folder.With.Dots"
Running ./Folder.With.Dots executes the application.

## Actual behavior
The output assembly is named incorrectly "Folder.With.Dots.Dots" (the part after the last period is appended again to the name.
Running ./Folder.With.Dots.Dots fails with:
The managed DLL bound to this executable: 'Folder.With.Dots.dll', did not match own name 'Folder.With.Dots.Dots.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.

Workaround: remove the last .Dots from the output assembly and the application executes just fine.

## Environment data

    dotnet --info
    .NET Command Line Tools (2.0.0-preview1-005977)
    Product Information:
     Version:            2.0.0-preview1-005977
     Commit SHA-1 hash:  414cab8a0b
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.16193
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\
    Microsoft .NET Core Shared Framework Host
      Version  : 2.0.0-preview1-002111-00
      Build    : 1ff021936263d492539399688f46fd3827169983`

**Comment by mikkelbu** [comment] 2017-05-14 18:16
This looks like a duplicate of #6397

**Comment by livarcocc** [comment] 2017-05-15 17:11
Correct, this is a dup. Closing this one.

**Closed by livarcocc** 2017-05-15 17:11 UTC
