### ISSUE TITLE
Error when case does not match between dependencies

### ISSUE THREAD

**Issue by dmorrison42** [dotnet/cli#7995] opened 2017-11-10 19:59 UTC
Let me preface this by saying. I understand this may be a *wontfix*, because most operating systems use a case sensitive file system. However, it would be nice to have a custom error message for this, or at least this issue as a reference for anyone else who has this problem.

## Steps to reproduce

Attempt to `Rebuild` the solution.

## Expected  behavior

The solution builds.

## Actual behavior

Error Cannot find project info for 'PROJECT2.csproj'. This can indicate a missing project reference.	

## Solution

I had a dependency tree that looked like this:

UI => Project 1 => Project 2

Project 1 had a reference to `project2.csproj`.

Project 2's csproj file was named `PROJECT2.csproj` on the disk.

I just renamed `PROJECT2.csproj` to `~PROJECT2.csproj` then to `project2.csproj` and did a `git mv PROJECT2.csproj project2.csproj`.

I think the ideal solution would be to make the error message match the *expected* casing. This would allow the developer to identify the problem faster, while still meeting the cross platform requirements.

`Error Cannot find project info for 'project2.csproj'. This can indicate a missing project reference.`

## Environment data

```
$ dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by peterhuene** [comment] 2018-04-06 22:01
Hi @dmorrison42.  Thank you for reporting this issue to us!

#8048, which is actually a dupe of your issue (but I didn't see your issue until now, unfortunately), has been fixed with the merging of #2088.

As such, I'm closing this issue.  The fix should be available in the upcoming "preview 2" of .NET Core 2.1.

Please reopen this issue if you have any questions.  Thanks again!

**Closed by peterhuene** 2018-04-06 22:01 UTC
