### ISSUE TITLE
restore failed with Nuget.config is empty on Debian

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/cli#7082] opened 2017-07-06 09:49 UTC
## Steps to reproduce
Got the latest build is 2.1.0-preview1-006685 in page https://github.com/dotnet/cli/tree/master
1.download the package via wget -O ~/dotnet-sdk-latest-debian-x64.deb https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-debian-x64.deb
2.extract the package
3.add the extract path to PATH
4.dotnet --info to check the build number
5. dotnet new console
6.dotnet run

## Expected  behavior
print: Hello World

## Actual behavior
e2euser@e2e-d8-5:~/Ht0$ sudo dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/e2euser/Ht0/Ht0.csproj...
  Restoring packages for /home/e2euser/Ht0/Ht0.csproj...
/home/e2euser/Ht0/Ht0.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25511-03)
/home/e2euser/Ht0/Ht0.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 2.0.0-preview2-25407-01 ]
  Generating MSBuild file /home/e2euser/Ht0/obj/Ht0.csproj.nuget.g.props.
  Generating MSBuild file /home/e2euser/Ht0/obj/Ht0.csproj.nuget.g.targets.
  Restore failed in 401.91 ms for /home/e2euser/Ht0/Ht0.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

##Solution
add <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />  
to NuGet.Config.
but, vim ~/.nuget/NuGet/NuGet.Config
this NuGet.Config is empty.

## Environment data
e2euser@e2e-d8-5:~$ dotnet --info
.NET Command Line Tools (2.1.0-preview1-006685)

Product Information:
 Version:            2.1.0-preview1-006685
 Commit SHA-1 hash:  49dfa8e96b

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.0-preview1-006685/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25507-02
  Build    : 6e7dadfdaed031624319dfd61415b2ce3498aa51

**Comment by livarcocc** [comment] 2017-07-06 17:27
This is actually a separate issue. This is because the lzma and the runtime in the CLI are out of sync. Please, add a nuGet.Config with `<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` in it and this should work.

Re-activate if it still fails even with the NuGet.Config change.

**Comment by shimingsg** [comment] 2017-07-13 02:33
repro on build 2.0.0-preview3-006736, re-open it

**Comment by livarcocc** [comment] 2017-07-13 05:44
This happens because the shared runtime is not in sync between the CLI and ASP.NET. The last build we had in sync was 2.0.0-previre3-006692. Until the builds get in sync, you will be required to add the NuGet.Config with the feed I mentioned above. This is not a bug that we will be able to fix in 2.0, as that requires a re-engineering of how the product is composed. So, closing the issue again. If this still fails after the feed above is used during restore, then there may be something else going on here.

**Closed by livarcocc** 2017-07-13 05:44 UTC
