### ISSUE TITLE
dotnet pack produces confusing/wrong versions for dependencies in nuspec file

### ISSUE THREAD

**Issue by schwamster** [dotnet/cli#4806] opened 2016-11-22 08:00 UTC
dotnet pack creates nuget package with nuspec that only sets a minimum version even though project.json defines a specific version. Have a look at the examples in expected/actual

## Steps to reproduce
dotnet new

then add a dependency to project.json (for example Newtonsoft):

```JSON
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.*"
        },
        "Newtonsoft.Json": "9.0.1"
      },
      "imports": "dnxcore50"
    }
  }
}
```

then build the nuget package:
dotnet pack

## Expected  behavior
I get a nuget package with the following nuspec:

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>netcore</id>
    <version>1.0.0</version>
    <authors>netcore</authors>
    <owners>netcore</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>netcore</description>
    <tags></tags>
    <dependencies>
      <group targetFramework=".NETCoreApp1.1">
        <dependency id="Microsoft.NETCore.App" version="[1.1.0]" />
        <dependency id="Newtonsoft.Json" version="[9.0.1]" />
      </group>
    </dependencies>
  </metadata>
</package>
```

## Actual behavior
i get a nuget packages with the following nuspec file:

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>netcore</id>
    <version>1.0.0</version>
    <authors>netcore</authors>
    <owners>netcore</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>netcore</description>
    <tags></tags>
    <dependencies>
      <group targetFramework=".NETCoreApp1.1">
        <dependency id="Microsoft.NETCore.App" version="[1.1.0, )" />
        <dependency id="Newtonsoft.Json" version="[9.0.1, )" />
      </group>
    </dependencies>
  </metadata>
</package>
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by davidfowl** [comment] 2016-11-22 08:03
This is by design. You don't have an exact version, you have a minimum and that's what nuget packs. Using exact versions is an anti pattern and should *only* ever be used with dependencies you tightly control or when you absolutely know that higher versions are broken.

**Comment by piotrpMSFT** [comment] 2016-11-22 09:24
Since this gets into intent of NuGet, closing the CLI issue. Let's have this discussion on nuget/home repo if we want to dig in. I'm sure other NuGet user will have an easier time finding it there.

**Closed by piotrpMSFT** 2016-11-22 09:24 UTC

**Comment by schwamster** [comment] 2016-11-22 09:34
actually have to agree with davidfowl 
i looked at it from the wrong perspective
