### ISSUE TITLE
console app builded by vs2015 in win7-x64 cannot run in windows server2008

### ISSUE THREAD

**Issue by vincentshow** [dotnet/cli#3311] opened 2016-06-01 01:53 UTC
## Steps to reproduce
publish a self-contained console app named test.exe by vs2015 with project.json below
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "publishOptions": {
    "include": [
      "appsettings.json"
    ]
  },
  "runtimes": {
    "win7-x64": { }
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702"//,
      //"type": "platform"
    },
    ...
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net452+win81"
      ],
      "dependencies": {
        ...
      }
    }
  }
}
and then modify the project.json and publish a portable dll named test.dll.

## Expected  behavior

runs ok in both win7 and winserver2008

## Actual behavior

both of test.exe and test.dll ran ok in another win7, but cannot run in winserver2008 with output errors 
test.exe: Failed to load the dll from [hostfxr.dll], HRESULT: 0x80070057.
dotnet test.dll: No executable found matching command "dotnet-test.dll"

 i've installed DotNetCore.1.0.0.RC2-Runtime-x64.exe in win7-x64 while DotNetCore.1.0.0.RC2-WindowsHosting.exe in winserver2008. And i have tried dotnet new, dotnet restore and dotnet run in winserver2008, 'hello world' can be outputed in command window.

## Environment data
`dotnet --info` output:
sorry, the command cannot be executed in winserver2008 with error:Unknown option: --info,
but dotnet --version output:

.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

**Comment by vincentshow** [comment] 2016-06-01 02:34
curious!!!  dotnet cannot be uninstalled in winserver2008! i've uninstalled dotnet both in win7 and winserver2008, but dotnet still can be executed in winserver2008 without any error outputed

**Comment by vincentshow** [comment] 2016-06-06 01:18
can somebody give me any help? am i in a wrong room?

**Comment by piotrpMSFT** [comment] 2016-06-07 00:25
1.0.0-beta-001598 is a very old build. RC2/Preview1 shipped as 1.0.0-preview1-002702. Can you grab the installers from [here](https://www.microsoft.com/net/download) and give it a shot?

**Comment by schellap** [comment] 2016-06-08 08:36
Could you please check if you have https://support.microsoft.com/en-us/kb/2533623 on the server 2008?

See pre-requisites: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-prerequisites.md#windows-dependencies

`PS> get-hotfix | findstr KB2533623`

**Comment by vincentshow** [comment] 2016-06-12 09:21
@piotrpMSFT i‘ve checked the cli version by your url, it was same with my installed cli. With the solution given by @schellap,i have executed exe file successfully after installing kb2533623. however, the dll could not be executed by cli yet. i'll try again, thank you all

**Comment by vincentshow** [comment] 2016-06-13 05:49
it's my fault. i have installed dotnet-win-x64.1.0.0.001598 in April, when dotnet version was just rc1-update2 with a name microsoft dotnet cli which was different from microsoft .net core . unfortunately, i missed it both when uninstalling and installing new dotnet. anyway, it runs ok now after i uninstalling the old version and installing dotnet core rc2, and last but not least, follow the official docs in  https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-prerequisites.md#windows-dependencies

**Comment by KasunKoswattha** [comment] 2016-06-16 13:53
Hi, Im trying to migrate my RC1 project to RC2. I have installed preview 1 and then Preview 2. But the assemblies were not resolving in the project.json file. So what I did, I've uninstall everything (Preview 1 and 2)  then installed Preview 1 again. But now when I try to run dotnet --info, it gives the below error. 
`Failed to load the dll from [], HRESULT: 0x80070057`
I tried removing temp files but did not work. 
Can anyone help me with this?

**Comment by schellap** [comment] 2016-06-16 17:06
@KasunKoswattha could you pls. share the contents (screenshot or `tree` output) of your c:/program files/dotnet folder and the link you used to install dotnet?

**Comment by KasunKoswattha** [comment] 2016-06-16 17:45
@schellap I had to restore my PC. Now I have updated my VS 2015 to update 2 and trying to Uninstall Microsoft ASP.NET 5 RC1 Update 1 . But it gives 0x80070001- Incorrect function. Can you please help me with that?

**Comment by KasunKoswattha** [comment] 2016-06-16 19:22
@schellap I have managed to remove RC1 update 1 manually and installed RC2 from this link. [URL](https://www.microsoft.com/net/core#windows). Now when I do dotnet --info in getting the dotnet information. But I tried dotnet new and dotnet restore. the restore fails now. almost all the packages are failing. Error message says the dependency {Dependency name} does not support framework .NETCoreapp, version=v1.0.

Could you please help me with this?

**Comment by schellap** [comment] 2016-06-16 23:59
@KasunKoswattha it may be a dup of https://github.com/dotnet/cli/issues/3315

Try: `dotnet restore --source https://dotnet.myget.org/F/dotnet-core`

Cc @eerhardt

**Comment by KasunKoswattha** [comment] 2016-06-17 12:01
@schellap Thanks for the comment. But did not work. The simple hello world app is not restoring and building. I have created an issue yesterday. [https://github.com/dotnet/cli/issues/3618](#3618)

**Comment by dvdobrovolskiy** [comment] 2016-07-01 17:34
I have Failed to load the dll from [], HRESULT: 0x80070057
any where from opening project to just running dotnet in cmd

**Comment by schellap** [comment] 2016-07-03 03:07
@dvdobrovolskiy, could you share some more details as whether you are on server 2008 and you have the KB mentioned above and if you have the below DLL available in `%ProgramFiles%\dotnet\hostfxr.dll` or `%ProgramFiles%\dotnet\host\fxr\{version}\hostfxr.dll`

**Comment by dvdobrovolskiy** [comment] 2016-07-03 09:53
No, notebook with win10

**Comment by schellap** [comment] 2016-07-03 17:00
@dvdobrovolskiy, it sounds like the DLL is missing, could you confirm? If that's the case, reinstall .NET Core from https://dot.net. Also, could you share what steps you did that resulted in the missing DLL?

**Comment by blackdwarf** [comment] 2016-07-28 18:16
Closing this due to lack of activity. If the issue is still reproing, please reopen.

**Closed by blackdwarf** 2016-07-28 18:16 UTC
