### ISSUE TITLE
Unable to debug/run netcoreapp1.1 webapi project which has a reference to netstandard1.6 class library

### ISSUE THREAD

**Issue by thammadi** [dotnet/cli#6699] opened 2017-05-26 07:32 UTC
Using Visual Studio Code 1.12.2 on Windows 7 Pro

## Steps to reproduce
1) Create a webapi (dotnet new webapi) "TestWebApi"
2) Create a class library (dotnet new classlib) "TestClassLibrary"
3) Add Microsoft.AspNetCore.Mvc reference to "TestClassLibrary"
3) Change TargetFramework for "TestClassLibrary" to netstandard1.6 (in TestClassLibrary.csproj)
4) Cut and past Controller folder from "TestWebApi" to "TestClassLibrary"
5) Add "TestClassLibrary" reference to "TestWebApi" (dotnet add reference ..\TestClassLibrary\TestClassLibrary.csproj)
6) Modify ConfigureServices (Startup.cs) method in "TestWebApi" as
services.AddMvc()
                .AddApplicationPart(typeof(ValuesController).GetTypeInfo().Assembly)
                .AddControllersAsServices();
and also add appropriate using statement
7) Hit F5 to debug

## Expected  behavior
Web api to build and run without any issues and also able to access sample api method (api/values)

## Actual behavior
Build error:
System.DllNotFoundException: Unable to load DLL 'combase.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Win32.UnsafeNativeMethods.RoGetActivationFactory(String activatableClassId, Guid& iid, Object& factory)
   at System.Threading.Tasks.AsyncCausalityTracer..cctor()

Note: `dotnet build` on individual projects work fine
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by livarcocc** [comment] 2017-05-29 01:04
@DustinCampbell any idea on even how to direct this? I don't believe the exception above is coming from the CLI.

**Comment by DustinCampbell** [comment] 2017-05-30 20:11
This should be moved to C# for VS Code at https://github.com/OmniSharp/omnisharp-vscode.

**Comment by DustinCampbell** [comment] 2017-05-30 20:11
This issue was moved to OmniSharp/omnisharp-vscode#1529

**Comment by DustinCampbell** [comment] 2017-05-31 18:05
Pinging here as well. @livarcocc, this is clearly not a VS Code issue but looks like a CoreCLR problem. Please see https://github.com/OmniSharp/omnisharp-vscode/issues/1529#issuecomment-305004561.

**Comment by nicolaszawada** [comment] 2017-06-07 10:13
I'm having the same issue on a Windows 7 machine. Have you been able to resolve this?
Combase.dll is not present in the System32 folder.
```
System.DllNotFoundException: Unable to load DLL 'combase.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Win32.UnsafeNativeMethods.RoGetActivationFactory(String activatableClassId, Guid& iid, Object& factory)
   at System.Threading.Tasks.AsyncCausalityTracer..cctor()'dotnet.exe' (CoreCLR: clrhost):
```

**Comment by JamieKeeling** [comment] 2017-07-27 22:04
👍 

It'd be good to know what the resolution was so it can be recorded here.

Hopefully it's not install Windows 10 🔨

**Comment by DustinCampbell** [comment] 2017-07-28 13:44
@livarcocc: Is there somebody you could add in from the CoreCLR team? Is looks like the issue is right here:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/AsyncCausalityTracer.cs#L148

and 

https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/Microsoft/Win32/UnsafeNativeMethods.cs#L250-L256

**Comment by livarcocc** [comment] 2017-07-28 22:50
@Petermarcu can you help triage this?

**Comment by Petermarcu** [comment] 2017-08-04 15:07
@yizhang82 , Any ideas here?

**Comment by yizhang82** [comment] 2017-08-04 19:52
@AlfredoMS Looks like AsyncCausalityTrace should be properly hardened / skipped in Win7.

**Comment by AlfredoMS** [comment] 2017-08-04 20:32
@yizhang82 Causality Trace was a windows 8 feature, it was never meant to go downlevel, so it should definitely be skipped for win7.

**Comment by DustinCampbell** [comment] 2017-08-04 20:34
Yeah, that's what we realized over in https://github.com/OmniSharp/omnisharp-vscode/issues/1529#issuecomment-305004561.

**Comment by AlfredoMS** [comment] 2017-08-04 20:36
The code is around a try catch, so I'm not sure why the exception leaked

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/AsyncCausalityTracer.cs#L146

**Comment by DustinCampbell** [comment] 2017-08-04 20:53
Does CoreCLR try to load the P/Invoke before JIT'ing the method?

**Comment by yizhang82** [comment] 2017-08-04 21:27
@DustinCampbell No, it's loaded when you make the call. From the call stack, it's clear that it is actually calling the p/invoke. I suspect Environment.IsWinRTSupported either not working properly, or that code is thrown out for some reason (IL linker?)

**Comment by Petermarcu** [comment] 2017-08-04 21:32
@russellhadley

**Comment by yizhang82** [comment] 2017-08-04 22:23
![image](https://user-images.githubusercontent.com/6903744/28989213-cc44df48-7928-11e7-8c68-39c11472ee65.png)

**Comment by JamieKeeling** [comment] 2017-08-04 22:27
Is there anything I can provide from my machine that might help to reproduce / identify the issue?

**Comment by JamieKeeling** [comment] 2017-08-04 22:41
![image](https://user-images.githubusercontent.com/7165035/28989619-719852a0-796e-11e7-8dd4-0e7ce340a2de.png)

Some specifics on my machine.

**Comment by JamieKeeling** [comment] 2017-08-04 22:42
![image](https://user-images.githubusercontent.com/7165035/28989636-97567e2c-796e-11e7-8c1e-23d798c9eb54.png)

Complete call stack leading up to the runtime error

**Comment by yizhang82** [comment] 2017-08-04 22:54
Thanks. @JamieKeeling It'd be nice to capture a full heap dump at the point of the exception when it is thrown?

**Comment by JamieKeeling** [comment] 2017-08-04 23:06
Dump with heap attached (via VS 2017) as requested @yizhang82 .

[dotnet.zip](https://github.com/dotnet/cli/files/1201878/dotnet.zip)

**Comment by yizhang82** [comment] 2017-08-04 23:42
Thanks @JamieKeeling . This is super helpful. 

OK. I think this is a bug that IsWinRTSupported was #ifdefed incorrectly in CoreCLR version to return always return true:

https://github.com/dotnet/coreclr/blob/ad746a9b698c3cd5f603db8974a196dfcbc10267/src/mscorlib/src/System/Environment.cs#L416

This is probably a oversight at some point when we believe CoreCLR should always run on Win8+, which is no longer true. 

@rahku fixed this in his change https://github.com/dotnet/coreclr/commit/201c70cc49ff2027fb8ed0ba5e25f56534b04a96, so this should no longer repro in 2.0.0. 

I"m still investigating why this doesn't happen on my win7 box.

**Comment by yizhang82** [comment] 2017-08-05 00:02
@JamieKeeling Did you turn on first-chance exceptions? Do you see the process crash inside VS? I can see the exception getting thrown in my machine and then handled by try/catch.
The RoGetActivationFactory call wasn't supposed to be run (see my investigation earlier), and the exception shouldn't be thrown in the first place. But the try/catch should handle that gracefully.

**Comment by JamieKeeling** [comment] 2017-08-11 11:50
Thanks @yizhang82 - I should have thought about that beforehand. After playing with how my exceptions are handled / break within VS2017 I am able to load without issue - I never thought to press F5!

**Comment by livarcocc** [comment] 2017-10-03 17:17
Seems like this issue has been resolved. Closing.

**Closed by livarcocc** 2017-10-03 17:17 UTC
