### ISSUE TITLE
dotnet pack for global tools generates files with 0 permissions

### ISSUE THREAD

**Issue by bojanrajkovic** [dotnet/cli#9410] opened 2018-06-03 23:43 UTC
## Steps to reproduce

1. Install .NET Core 2.1
2. Install @natemcmaster's template package: `dotnet new --install McMaster.DotNet.GlobalTool.Templates`
3. `dotnet new global-tool -o bad-perms`
4. `cd bad-perms`
5. `dotnet pack`
6. `cd bin/Debug/netcoreapp2.1`
7. `unzip bad-perms.1.0.0.nupkg`
8. `stat -f "%p" tools/netcoreapp2.1/any/bad-perms.dll`

## Expected  behavior

Should output 100644, or something similar—a reasonable set of permissions for assemblies (644 being `rw-r--r--`).

## Actual behavior

Outputs 100000, indicating a file with no permissions at all. This is true for all files in the package, which makes the package totally unusable. The same also happens for `dotnet pack` on non-global-tool packages.

## Environment data

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by natemcmaster** [comment] 2018-06-04 03:31
+1. Can confirm this behavior on macOS when using `unzip`. It's probably caused by this: https://github.com/dotnet/corefx/issues/17342

@bojanrajkovic you can workaround this by using `tar xf myfile.nupkg` instead of `unzip`. It seems `tar` does a better job of extracting permissions on macOS.

**Comment by livarcocc** [comment] 2018-06-04 16:41
@wli3 @peterhuene anything we can do here?

**Comment by peterhuene** [comment] 2018-06-04 17:07
It isn't related to tool packages; sounds like a general problem of unzipping nuget packages.

**Comment by natemcmaster** [comment] 2018-06-04 17:09
I think the underlying issue is with System.IO.Compression.ZipArchive. I had to [workaround a similar issue](https://github.com/aspnet/BuildTools/blob/2af0e2e3d02329b4f0290061ab9bd8c7ca1aa26f/modules/BuildTools.Tasks/ZipArchive.cs#L93-L109) a while back in producing a .zip file in .NET Core. I don't think this was ever fixed in corefx.

**Comment by livarcocc** [comment] 2018-06-04 18:13
@peterhuene please, go ahead and close this issue and comment on the issue that @natemcmaster has linked to above for corefx.

**Comment by peterhuene** [comment] 2018-06-04 18:44
Closing as a duplicate of https://github.com/dotnet/corefx/issues/17342.

**Closed by peterhuene** 2018-06-04 18:44 UTC
Labels: tool
