### ISSUE TITLE
CLI master is not in-sync with core-setup master

### ISSUE THREAD

**Issue by shiftylogic** [dotnet/cli#7415] opened 2017-08-10 21:42 UTC
Filed with @ericstj 

/cc @livarcocc

**Comment by nguerrera** [comment] 2017-08-10 22:22
This is a duplicate of https://github.com/dotnet/cli/issues/7157

There's some issues with the managed packages out of core-setup getting a version bump. I started to work through them but was pre-empted by higher pri 2.0 work.

**Closed by nguerrera** 2017-08-10 22:22 UTC
