### ISSUE TITLE
A? (Installer wants to restart an app that does not exist or does not show what it is going to restart)

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2756] opened 2016-04-29 16:51 UTC
![image](https://cloud.githubusercontent.com/assets/1438884/14922943/39df1d8a-0def-11e6-8fb0-9a1572b1daf1.png)

```
PS C:\Source\RazorTooling> ps

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id  SI ProcessName
-------  ------    -----      ----- -----   ------     --  -- -----------
    629      28    22752      29880 ...26     3.56   7508   1 ApplicationFrameHost
    511      13    17732      15796 ...23 1,001.75  23516   0 audiodg
    376      18    11300      20036 ...79     0.86  10256   1 browser_broker
   3433      22    20572      25784   235     0.95  10752   1 BuildNotificationApp
    426      24    25440      40604   274     3.41  13764   1 Calculator
   1465      46    50536      69040   245           43820   0 CcmExec

...
```

**Comment by Sridhar-MS** [comment] 2016-04-29 16:52
Duplicate of #2678

**Closed by Sridhar-MS** 2016-04-29 16:52 UTC
