### ISSUE TITLE
Auto define for PCL profiles should be the profile number

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1412] opened 2016-02-16 02:42 UTC
Probably something like `PORTABLE_PROFILE{number}`.

``` C#

#if PORTABLE_PROFILE7
   // Something
#endif
```

**Comment by Pilchie** [comment] 2016-02-16 02:58
The only time there isn't a profile number is if the PCL is targeting `dotnet` or `netstandard`.

**Comment by scottdorman** [comment] 2016-02-16 03:00
This allows PCL profiles to follow the same behavior as the other targets and auto define a compiler define. Using the profile number is the simplest approach and stays fairly consistent with the other auto generated defines.

In the case of a PCL targeting `dotnet` or `netstandard`, could we do something like `PORTABLE_DOTNET` or `PORTABLE_NETSTANDARD`?

**Comment by onovotny** [comment] 2016-02-16 03:00
I think we can all agree that `dotnet` should die. For `netstandard` there's still a version, `NETSTANDARD1_2`, etc.

**Comment by davidfowl** [comment] 2016-02-16 03:00
@Pilchie or when people invent profiles by adding arbitrary platforms using +

**Comment by davidfowl** [comment] 2016-02-16 03:01
> In the case of a PCL targeting dotnet or netstandard, could we do something like PORTABLE_DOTNET or PORTABLE_NETSTANDARD?

I think no, the only reason I added the PORTABLE moniker is because PROFILE{number} seems less clear.

**Comment by Pilchie** [comment] 2016-02-16 03:02
Adding arbitrary platforms using + still resolves down to a profile number (or error) in the NuGet implementation.

**Comment by davidfowl** [comment] 2016-02-16 03:04
As long as you're sure about that. What profile is this:

`portable-net45+wp80+win8+wpa81+dnxcore50`

BTW @emgarten is there a way to get the profile number from a NuGetFramework?

**Comment by onovotny** [comment] 2016-02-16 03:06
NuGetFramework has a Profile property on it.

**Comment by emgarten** [comment] 2016-02-16 03:29
NuGetFramework will contain Profile<number> if it was matched. It automatically does this when creating the full .NET framework name. If it is a made up profile it will contain the original list of frameworks.

**Comment by davidfowl** [comment] 2016-02-16 03:31
> If it is a made up profile it will contain the original list of frameworks.

Right, so we'll need to re-parse as a framework name to know if it's real profile number or not right?

**Comment by onovotny** [comment] 2016-02-16 03:41
Couldn't you just check if Profile isn't null?

**Comment by scottdorman** [comment] 2016-02-16 03:41
@emgarten So if it's matched, then it ends up as something like `.NETPortable,Version=v4.0,Profile=Profile328`, but if it's not matched it would be `.NETPortable,Version=v4.0,Profile=net46+sl4+wpa81`?

@davidfowl Wouldn't that be enough? If it's a matched profile, it would always start with `Profile`.

(Note that I may be greatly oversimplifying things.)

**Comment by davidfowl** [comment] 2016-02-16 03:43
> Couldn't you just check if Profile isn't null?

It's not null.

> @davidfowl Wouldn't that be enough? If it's a matched profile, it would always start with Profile.

Sure, makes me feel dirty inside. We could also look for '+' :smile:

**Comment by davidfowl** [comment] 2016-02-16 03:47
I'd like to request an API change @emgarten to make this less dirty. Add a bool or something to `NuGetFramework`

**Comment by scottdorman** [comment] 2016-02-16 03:50
@davidfowl LOL. Yes, an `IsPCLProfile` flag on `NuGetFramework` is definitely better, although if we're going to do that, wouldn't it be better to either change this to be `IsValidPCLProfile` or include both? That way we can determine not just if it's a PCL profile but also that it's a valid profile that properly matches.

**Comment by onovotny** [comment] 2016-02-16 04:01
For properly matching, you'd also need to take all the optional frameworks into account...esp the Xamarin ones that people tack on to the end.

**Comment by scottdorman** [comment] 2016-02-16 04:05
@davidfowl If I'm looking in the right spot (https://github.com/dotnet/cli/blob/c881516abf4ee50ebea4e6d8fd065939248ec9e6/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L582), there already and `IsPCL` property. I think part of the problem is that the code in that method (`MakeDefaultTargetFrameworkDefine`) simply returns `null` if that property is `true`. It seems like that's the place where we'd want to add the logic of figuring out what the defined symbol should be.

**Comment by davidfowl** [comment] 2016-02-16 04:07
Yap that's it.

**Comment by scottdorman** [comment] 2016-02-16 04:17
So now I guess the question is: What is the behavior of the `IsPCL` property? Is it enough to simply query that property and create the appropriate define or do we still need something else that can tell us the either the profile number and/or if it's a validly defined PCL profile.

**Comment by scottdorman** [comment] 2016-02-16 04:38
Ok, `IsPCL` ([NuGetFramework.cs, line 258](https://github.com/NuGet/NuGet.Client/blob/4094086a0b6588dbc9c21dbd3ac8efecf93dac80/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs#L258)) effectively just looks to see if the TFM starts with `.NETPortable`. Based on what I'm seeing in `GetShortFolderName` [NuGetFramework.cs, line 171](https://github.com/NuGet/NuGet.Client/blob/4094086a0b6588dbc9c21dbd3ac8efecf93dac80/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs#L171), it does look like checking the combination of `if (targetFramework.IsPCL && !String.IsNullOrWhitespace(targetFramework.Profile))` in `ProjectReader.cs`, [line 582] (https://github.com/dotnet/cli/blob/c881516abf4ee50ebea4e6d8fd065939248ec9e6/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L582) might work.

**Comment by davidfowl** [comment] 2016-02-16 05:05
@scottdorman do you want to PR this?

**Comment by scottdorman** [comment] 2016-02-16 05:09
@davidfowl Sure, I can do that but probably won't get to it until sometime tomorrow afternoon.

**Comment by scottdorman** [comment] 2016-02-17 17:29
@davidfowl I think I have the code change completed. How do I test this (preferably inside Visual Studio) before checking in to my branch and submitting a pull request?

**Comment by davidfowl** [comment] 2016-02-17 18:45
There's no cli support for VS publicly available as yet. You can write a cli test and just do manual testing on the command line for now

**Comment by scottdorman** [comment] 2016-02-17 19:30
Ok. I'll do some manual command line testing then.

**Comment by blackdwarf** [comment] 2016-03-01 00:26
@scottdorman did you manage to make this work?

**Comment by piotrpMSFT** [comment] 2016-11-10 00:48
Closing, as ProjectModel is removed starting with preview3.

**Closed by piotrpMSFT** 2016-11-10 00:48 UTC
