### ISSUE TITLE
Resx files are not working for fsharp project

### ISSUE THREAD

**Issue by Lanayx** [dotnet/cli#8697] opened 2018-02-28 15:01 UTC
## Steps to reproduce
1. Create empty F# console project (.NET Core)
2. Add `type Test = Test of string`
3. Add Resources folder
4. Add Resource `Test.en.resx` to Resources folder
5. Build project

## Expected  behavior
VS build works
`dotnet build` works

## Actual behavior
VS build works
`dotnet build` doesn't work. 
resources.cs file with fsharp content is created and CS compiler errors are shown

## Environment data
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment] 2018-02-28 17:49
This is not currently supported in MSBuild core, but is supported in full MSBuild.

I believe this issue is a duplicate of https://github.com/Microsoft/msbuild/issues/2272.

**Comment by Lanayx** [comment] 2018-02-28 19:07
Looks like the issue is only with F#, if I do the same thing in C#, it works fine. The main problem is that MyProject.resources.cs file is generated for both cases and C# compiler is used for both cases, while .fs file and F# compiler should be used for F# project.

**Comment by livarcocc** [comment] 2018-02-28 19:38
@KevinRansom can you take a look?

@nguerrera just corrected me. We do support resx files. MSBuild just doesn't support non-string assets in it. But that does not look like the issue here.

**Comment by Lanayx** [comment] 2018-02-28 19:39
Just checked Visual Basic, it has exactly the same issue. Only C# version works fine.

**Comment by peterhuene** [comment] 2018-03-15 01:16
I see this working in master:

```
$ mkdir repro && cd repro
```
```
$ dotnet new console -lang f#
```
```
$ cat <<EOF > Program.fs
open System
open System.Resources

[<EntryPoint>]
let main argv =
    Console.WriteLine(ResourceManager("repro.Strings", System.Reflection.Assembly.GetCallingAssembly()).GetObject("HelloWorld"))
    0
EOF
```
```
$ cat <<EOF > Strings.resx
<?xml version="1.0" encoding="utf-8"?>
<root>
  <data name="HelloWorld" xml:space="preserve">
    <value>Hello World!</value>
  </data>
</root>
EOF
```
```
$ dotnet run
Hello World!
```

**Comment by Lanayx** [comment] 2018-03-15 03:55
It was supported when I created the issue if building from VS.

**Comment by livarcocc** [comment] 2018-03-15 04:10
@KevinRansom to comment.

**Comment by nguerrera** [comment] 2018-03-15 04:17
This is a duplicate of https://github.com/dotnet/sdk/issues/1748

It is now fixed. The fix will be in 2.1.102 which will ship very soon and be delivered with a VS 15.6.x update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lanayx** [comment] 2018-03-21 07:12
Tried the latest 15.6.3 update - the error is different:
```
Error writing code fragment: System.Exception: Language name must be F#
   at Microsoft.FSharp.Build.WriteCodeFragment.Microsoft-Build-Framework-ITask-Execute()
Build FAILED.
```
But the result is the same, it still doesn't work... Please reopen the issue.

**Comment by livarcocc** [comment] 2018-03-21 16:07
@nguerrera can you please take a look and if necessary re-activate the SDK issue?

**Comment by nguerrera** [comment] 2018-03-21 16:50
@brettfo It looks like F# is overriding the WriteCodeFragment task to only support F#. I think you either need to give your task another name or support a superset of built-in WriteCodeFragment (C#, VB).

 https://github.com/Microsoft/visualfsharp/blob/a44472c8d92652ee16e05a90a40fe0a7f41328c3/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L28

We always use csc to generate satellite assemblies regardless of code language. We therefore need to write the satellite assembly attributes in C# syntax.

**Comment by nguerrera** [comment] 2018-03-21 16:51
This issue was moved to Microsoft/visualfsharp#4591

**Closed by nguerrera** 2018-03-21 16:51 UTC
