### ISSUE TITLE
RC2 is much slower than RC1??

### ISSUE THREAD

**Issue by XiaoFaye** [dotnet/cli#2889] opened 2016-05-04 22:23 UTC
## Steps to reproduce

Any simple MVC projects using net core.

## Expected  behavior

similar speed when handling request

## Actual behavior

This ASP.NET 5 project was created using Visual Studio 2015, dnvm version 1.0.0-rc1-15540.
![speed1](https://cloud.githubusercontent.com/assets/6334728/15031160/ea4165c4-12aa-11e6-9b32-97bd25e8991c.png)

This project was created using dotnet new, cli version 1.0.0-rc2-002659
![speed2](https://cloud.githubusercontent.com/assets/6334728/15031175/ef0c3a0c-12aa-11e6-8e5b-67e28ce38034.png)

Both projects are only showing a simple page, You can see the time used to process request are huge difference.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002659)

Product Information:
 Version:     1.0.0-rc2-002659
 Commit Sha:  11a001706f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment] 2016-05-04 23:14
We are going to be making additional perf improvements after this milestone is over. This is a dupe of #2515

**Closed by piotrpMSFT** 2016-05-04 23:14 UTC
Labels: bug

**Comment by jeremymeng** [comment] 2016-05-05 03:38
@piotrpMSFT I think this bug is about runtime performance (coreclr/corefx/asp.net/etc.) while #2515 is about performance of dotnet/cli tooling. Or am I overlooking anything?

**Comment by tatalvit** [comment] 2016-05-17 14:07
I tested RC1 and today RC2. Basic hello world web app compiles in around 2.0 seconds and IIS Express shows the changes made to startup.cs file within 3-5 seconds in both RC1 and RC2. But, when I edit MVC controller class and then hit the refresh in browser there is a major difference: in RC1 it tooks 3-5 seconds but in RC2 around 9-12 seconds until IIS Express responds to request. This only applies if the URI executes MVC controller.

**Comment by pedrogaspar** [comment] 2016-06-09 21:24
Will this be fixed in time for rtm? 
Compilation in rc2 is a lot slower than it was in dnx.

**Comment by HydrateEfficiently** [comment] 2016-07-23 12:29
Hey guys, don't get me wrong, loving the new framework. It's my love that made me want to chime in and express that compile times are seriously slow. A project that I have been working on for 3 months (not THAT much code, relatively - ~5 separate project files) can often take more than a minute to compile. Before RTM (I went straight from RC1 to RTM) there was no noticeable lag, maybe 5 or 10 seconds. Obviously this is going to turn a lot of developers off using dotnet core.

**Comment by severisv** [comment] 2016-08-02 07:45
Is it possible to get any information regarding this? Developing with dnx was a pleasure, but after the move to dotnet cli it is a frustrating experience.

Why was dnx fast and why is dotnet cli slow? Will we ever see dotnet cli perform as well as dnx did? When?
