### ISSUE TITLE
dotnet-restore doesn't respect global.json

### ISSUE THREAD

**Issue by vors** [dotnet/cli#1137] opened 2016-01-30 02:14 UTC
Calling `dotnet restore` from a root folder with `global.json` does restore for all folders regardless are they listed in `projects` section of `global.json` or not.

**Comment by davidfowl** [comment] 2016-01-30 02:27
It never did. It looks recursively for project.json files

**Comment by blackdwarf** [comment] 2016-02-25 06:33
@vors seems like this is by design. I will close this, feel free to reopen if more info is needed.

**Closed by blackdwarf** 2016-02-25 06:33 UTC
Labels: question
