### ISSUE TITLE
Code Coverage does not work even after adding the code coverage nuget.

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/cli#1995] opened 2016-03-22 19:30 UTC
## Steps to reproduce

The attached project has a simple xunit test. There are two ways to repro this:

The more easier way of reproing this is : From a developer command prompt run vstest.console.exe project.json /useVsixExtensions:true /enableCodeCoverage

For the VS IDE repro you can use this:
1. Open it in VS.
2. Open Test Explorer.(Test -> Windows -> Test Explorer)
3. Build the solution to trigger discovery.
4. Right Click on the discovered test and "Analyze code coverage"

[Repro.zip](https://github.com/dotnet/cli/files/184801/Repro.zip)
## Expected  behavior

A code coverage file that covers the project under test with no errors.
## Actual behavior

The following error occurs:
Error: Unable to start C:\Program Files\dotnet\bin\dotnet.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

This scenario works if I manually drop the CodeCoverage.Shim dll that the nuget package contains under %ProgramFiles%/dotnet/bin. 
## Environment data

`dotnet --version` output:

**Comment by andriysavin** [comment] 2016-12-23 16:12
> This scenario works if I manually drop the CodeCoverage.Shim dll that the nuget package contains under %ProgramFiles%/dotnet/bin.
Even with this workaround code coverage seems to be working only for netstandard assemblies, but not for net4хх ones. In other words, in the VS's Code Coverage Results only netstandard assemblies are listed, though I know that net4xx assemblies were called by the tests.

**Comment by piotrpMSFT** [comment] 2017-01-19 00:05
@dotnet/vstest I'm going to close this issue on CLI, but getting Code Coverage as a feature in the near future will be great :D

**Closed by piotrpMSFT** 2017-01-19 00:05 UTC
Labels: blocking-release

**Comment by dandago** [comment] 2017-03-09 10:01
Why is this issue closed if the problem is not solved?

**Comment by Leonardo-Ferreira** [comment] 2017-09-25 13:47
Same for VS 2017...

**Comment by treenew** [comment] 2017-10-30 15:37
System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 

no work.......

**Comment by BlitzkriegSoftware** [comment] 2018-04-17 01:09
I have the same issue as of today. .NET Core 2.0 project XUNIT test project.

**Comment by AraHaan** [comment] 2018-09-19 19:31
same for me on my xUnit project on the .NET Standard style *.csproj files. .NET Framework old style *.csproj files like the ones here: https://github.com/Elskom/zlib.managed/ are not affected.
