### ISSUE TITLE
dotnet store has entries for artifact that aren't in store, causing runtime failure

### ISSUE THREAD

**Issue by rynowak** [dotnet/cli#6492] opened 2017-05-02 20:59 UTC
## Steps to reproduce
These repro steps are based on the instructions at https://github.com/aspnet/JitBench/blob/dev/README.md. This was working about a week ago, and regressed without any changes to JITBench

`git clone https://github.com/aspnet/JitBench.git`
`git checkout dev`

// This is needed to 'pin' the versions in `CreateStore.proj`
`$env:JITBENCH_ASPNET_VERSION = 2.0.0-preview2-24806`

`dotnet store --manifest .\CreateStore.proj -f netcoreapp20 -r win7-x64 --framework-version 2.0.0-preview2-002093-00 -w .\temp -o .\store`

This will create a store at `.store`. Later if you publish and run the app at `src/MusicStore` with this store you'll get an error like:
```
Error: assembly specified in the dependencies manifest was not found probably due to missing runtime store associated with artifact.xml -- package: 'Microsoft.Win32.Registry', version: '4.4.0-preview1-25229-02', path: 'runtimes/win/lib/netcoreapp2.0/Microsoft.Win32.Registry.dll'
```

## Actual behavior

Open `.store/x64/netcoreapp20/artifact.xml` - notice that there's an entry for `Microsoft.Win32.Registry`. Now go look at `.store/x64/netcoreapp20/` - there's no folder there for `microsoft.win32.registry`. 

The store claims to contain this package, but it doesn't.

## Expected  behavior

The store doesn't claim to contain packages it doesn't have. Publishing and running the application using these store can succeed.

## Environment data
.NET Command Line Tools (2.0.0-preview1-005899)

Product Information:
 Version:            2.0.0-preview1-005899
 Commit SHA-1 hash:  ea746bd0dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\rynowak\.dotnet\x64\sdk\2.0.0-preview1-005899\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

**Comment by eerhardt** [comment] 2017-05-03 04:39
Dupe of https://github.com/dotnet/sdk/issues/1162?

**Comment by rynowak** [comment] 2017-05-03 04:49
Yes, this appears to be the same issue. Note that this blocking `aspnet/JitBench` which a lot of runtime folks use for perf work.

**Comment by eerhardt** [comment] 2017-05-03 15:13
@rynowak - can you explain how it is blocking?  Why can't you just use versions that align with each other?

Basically, ensure that the version of `Microsoft.Win32.Registry` is the same version as the shared framework you are using.  Here you are mixing `preview1` and `preview2` assets:

`--framework-version 2.0.0-preview2-002093-00`
` -- package: 'Microsoft.Win32.Registry', version: '4.4.0-preview1-25229-02',`

**Comment by rynowak** [comment] 2017-05-03 19:48
I'm using preview2 builds of ASP.NET and preview2 builds of the shared framework. Are you saying that the bug is that one of the ASP.NET package is pulling in `'4.4.0-preview1-25229-02'`

**Comment by eerhardt** [comment] 2017-05-03 19:51
It appears someone is pulling in the `preview1` package.  You can check your `obj/project.assets.json` file to see how that package is getting pulled in.

**Comment by rynowak** [comment] 2017-05-06 00:36
We've identified where this is happening in ASP.NET, we're just focusing all of our energy right now on shipping preview-1. 

I was able to work around this in JitBench for now by hoisting these versions in the project file https://github.com/aspnet/JitBench/pull/41/files

**Comment by rynowak** [comment] 2017-05-18 21:26
I've gotten back to trying this again with preview2 builds and preview2 packages all around. My workaround no longer works. I now have bunch of packages like:

```
   <Package Id="Microsoft.Win32.Registry"  Version ="4.3.0"/>
...
   <Package Id="Microsoft.Win32.Registry"  Version ="4.4.0-preview2-25317-01"/>
```

There are two entries in artifact.xml but nothing actually in the store. So this is once again failing with:

Error: assembly specified in the dependencies manifest was not found probably due to missing ```runtime store associated with artifact.xml -- package: 'Microsoft.Win32.Registry', version: '4.4.0-preview2-25317-01', path: 'runtimes/win/lib/netcoreapp2.0/Microsoft.Win32.Registry.dll'
```

**Comment by livarcocc** [comment] 2017-05-31 00:55
@eerhardt @ramarag is this something you guys will still tackle for 2.0?

**Comment by ramarag** [comment] 2017-05-31 01:17
yes i am working on this as part of using sdk conflict resolution in store

**Comment by livarcocc** [comment] 2017-06-09 05:56
I believe this has been fixed now that we inserted an SDK with the fix. Please, re-activate if this is still happening.

**Closed by livarcocc** 2017-06-09 05:56 UTC
Labels: Store
