### ISSUE TITLE
MyGet packages should be updated before CLI installer

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#2608] opened 2016-04-20 19:15 UTC
At the time this issue was created (4/20/16 12:12PM), the version of "Windows x64 .NET Core SDK Installer" at https://github.com/dotnet/cli is 1.0.0-rc2-002439.  However, the newest version of Microsoft.NETCore.App at https://dotnet.myget.org/F/dotnet-core/api/v3/index.json is v1.0.0-rc2-3002426.  This means that `dotnet restore` after `dotnet new` will fail.

The fix is to update packages on MyGet *before* updating the CLI installer at https://github.com/dotnet/cli.

## Steps to reproduce
1. Download "Windows x64 .NET Core SDK Installer" from https://github.com/dotnet/cli.
2. Run `dotnet new`
3. Add NuGet.config per #2545.
4. Run `dotnet restore`

## Expected  behavior
Restore works.

## Actual behavior
error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002439)' for '.NETCoreApp,Version=v1.0'.

@piotrpMSFT

**Comment by kerryjiang** [comment] 2016-04-21 16:21
I met the same problem.
I waited the updated rc night build release for many days, but still got same errors.

Fortunately, there is a workaround for this problem mentioned in the other issue https://github.com/dotnet/cli/issues/2543.

**Comment by piotrpMSFT** [comment] 2016-04-21 23:41
This is a dupe of #2613

**Closed by piotrpMSFT** 2016-04-21 23:41 UTC
