### ISSUE TITLE
dotnet restore does not update lock file for tools when imports are modified

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2977] opened 2016-05-10 22:20 UTC
Restore caches the lock file and does not rebuild it if imports changes (which might cause the dependency graph to be rebuilt).

`dotnet --version`: `1.0.0-preview1-002700`

**Comment by livarcocc** [comment] 2016-05-10 23:03
@pranavkm This seems like a NuGet bug. Can you open a bug there and close this one in favor of it?

**Comment by brthor** [comment] 2016-05-10 23:03
@pranavkm Is it definitely the lock file and not deps file which is not being rebuilt?

**Comment by pranavkm** [comment] 2016-05-10 23:48
Sorry, I think it's the deps file. @pakrym might have more info on this.

**Comment by pakrym** [comment] 2016-05-11 00:16
`deps` file is not rebuild

**Comment by piotrpMSFT** [comment] 2016-05-11 23:52
This is then a dupe of #2978

**Closed by piotrpMSFT** 2016-05-11 23:52 UTC
Labels: bug
