### ISSUE TITLE
[Windows] Self-contained console app not really self contained.

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/cli#3969] opened 2016-07-31 18:17 UTC
## Steps to reproduce
My console app should be self-contained after 'dotnet publish'. However, the published console app is not able to run on a clean installed WinServer2012R2 Azure VM. It's complains about missing dependency.
I find the following log in event log.
```
Faulting application name: Agent.Listener.exe, version: 0.0.0.0, time stamp: 0x57461460
Faulting module name: i-ms-win-crt-runtime-l1-1-0.dll, version: 6.3.9600.18233, time stamp: 0x56bb4ebb
Exception code: 0xc0000135
Fault offset: 0x00000000000ecdd0
Faulting process id: 0xe18
Faulting application start time: 0x01d1e763e1b53193
Faulting application path: C:\WinCoreCLRAgent\bin\Agent.Listener.exe
Faulting module path: i-ms-win-crt-runtime-l1-1-0.dll
Report Id: 1f61bd6f-5357-11e6-80c4-000d3a7028e7
Faulting package full name: 
Faulting package-relative application ID:
```
The missing dll's name looks buggy. :)
After searching online, i installed https://support.microsoft.com/en-us/kb/2999226 which eventially unblock me.

Why the self-contained app need that dependency? My project.json has runtimes target to win7-x64.
BTW, I didn't find any official Doc talks about this requirement.

## Expected  behavior
My console app is able to run on any windows platform when my target runtimes has win7-x64
## Actual behavior
My app fail to launch on winserver 2012 r2

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003161)

Product Information:
 Version:            1.0.0-preview3-003161
 Commit SHA-1 hash:  63846c5751

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment] 2016-08-01 04:57
The pre-requisite for Windows platforms has been documented extensively on both the [pre-requsities](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md) page as well as on the https://dot.net/core getting started page. Also, the current documentation for self-contained applications notes that you need to install any native pre-requisites for .NET Core in order for the self-contained application to work.

Closing this as "by design".

**Closed by blackdwarf** 2016-08-01 04:57 UTC
