### ISSUE TITLE
Publish looks in wrong folder for dependency

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#9690] opened 2018-07-18 20:49 UTC
_From @ghosttie on July 18, 2018 0:0_

I have a project targeting .NET Core 2.1 that has a reference to a project targeting .NET Standard 2.0.

Everything compiles and runs fine, but when I try to publish, it fails with this error:

> Metadata file 'C:\projects\asp.net\Project Name\Project Name.BusinessLogic\bin\Release\netcoreapp2.1\Project Name.BusinessLogic.dll' could not be found

It appears to be looking for a nonexistent \netcoreapp2.1\ directory instead of \netstandard2.0\ where the dll actually is.

I think it might be using the referencing project's target rather than the referenced project's target to construct the path, but I could be wrong.

EDIT: on reflection, this might be the wrong project to report this to - can someone give me direction to the correct project?

_Copied from original issue: dotnet/coreclr#18974_

**Comment by ghosttie** [comment] 2018-07-18 22:17
The last time I published this was before upgrading from .NET Core 2.0, but I just tried reverting git back to that commit and it no longer works (same error), so I think the problem must be in the 2.1 SDK

Having said that, I created a new empty solution and tried to reproduce the problem but it published fine, so there must be something about my solution that it's interacting with, but I can't figure out what

**Comment by nguerrera** [comment] 2018-07-19 04:03
Can you share a binary log (.binlog)?

`dotnet publish /bl`

This will write msbuild.binlog to current directory.

**NOTE**: this will capture project file contents and other details about your projects. You may want to browse it yourself using http://msbuildlog.com before sharing.

**Comment by nguerrera** [comment] 2018-07-19 04:05
Also, how are you invoking publish? In VS? On the command line? What options do you choose for VS? What is the exact command line?

**Comment by nguerrera** [comment] 2018-07-20 18:41
@dsplaisted

**Comment by ghosttie** [comment] 2018-07-25 20:12
I downgraded to .NET Core 2.0 and it allowed me to publish

**Comment by nguerrera** [comment] 2018-07-25 20:30
cc @vijayrkn 

The command line publish succeeded so this seems isolated to the parameters used in VS publish. What version of Visual Studio are you using? I recall something like this being fixed before.

**Comment by ghosttie** [comment] 2018-07-25 20:33
Visual Studio Community 2017 v15.7.5 - I keep it on the latest version

**Comment by vijayrkn** [comment] 2018-07-25 20:54
Can you try running the following command and share the output?

`msbuild <projname>.csproj /p:DeployOnBuild=true /p:PublishProfile=<profilename> /bl `

**Comment by vijayrkn** [comment] 2018-07-25 21:52
From the log it shows 'Build succeeded'. Are you running into this issue only with Visual Studio?

**Comment by ghosttie** [comment] 2018-07-25 22:09
I only use Visual Studio, so yes I guess so

**Comment by vijayrkn** [comment] 2018-07-25 22:40
Can you set the msbuild file verbosity to Diagnostic (Tools -> Options -> Projects & Solutions -> Build and Run -> MSBuild Project build output verbosity to Diagnostic) & share the output log please?

**Comment by ghosttie** [comment] 2018-07-25 22:56
[output.zip](https://github.com/dotnet/cli/files/2229801/output.zip)

**Comment by vijayrkn** [comment] 2018-07-26 01:17
In the log, I can see the TargetFrameworkIdentifier for this project getting set to .NETCoreApp. Can you try removing the TargetFramework from the pubxml (Properties\PublishProfiles\<profile>.pubxml) & see if it makes any difference?

```
   TargetPathWithTargetPlatformMoniker=
        C:\Users\jmunro\Dropbox\Work\projects\asp.net\Child Cancer Foundation\Child Cancer Foundation.BusinessLogic\bin\Release\netcoreapp2.1\Child Cancer Foundation.BusinessLogic.dll
                CopyUpToDateMarker=C:\Users\jmunro\Dropbox\Work\projects\asp.net\Child Cancer Foundation\Child Cancer Foundation.BusinessLogic\obj\Release\netcoreapp2.1\Child Cancer Foundation.BusinessLogic.csproj.CopyComplete
                TargetFrameworkIdentifier=.NETCoreApp
                TargetFrameworkVersion=2.1
                TargetPlatformIdentifier=Windows
                TargetPlatformMoniker=Windows,Version=7.0
                Done building target "GetTargetPathWithTargetPlatformMoniker" in project "Child Cancer Foundation.BusinessLogic.csproj".
```

**Comment by ghosttie** [comment] 2018-07-26 14:22
That fixed it

**Comment by livarcocc** [comment] 2018-08-06 18:49
Closing as @vijayrkn's suggestion seems to have solved the problem.

**Closed by livarcocc** 2018-08-06 18:49 UTC

**Comment by ghosttie** [comment] 2018-08-06 19:06
I appreciate the workaround but isn't this something that needs to be fixed?

I don't think I did anything strange - I created a project in ASP.NET Core 1.0, upgraded to 2.0, upgraded to 2.1 and publishing stopped working.  I didn't add the TargetFramework element to the pubxml file - that happened automatically.

If it happened to me, won't it happen to other people?

**Comment by dsplaisted** [comment] 2018-08-15 20:16
@vijayrkn It sounds like publishing project with a pubxml will break if you retarget the project and don't know to update the pubxml.  Is there anything we can do about this?

**Comment by vijayrkn** [comment] 2018-08-15 20:27
We write the targetframework to the pubxml to handle the multi-targeting scenarios. For apps with a single 'targetframework', we can probably skip writing this info to the pubxml so that the targetframework from csproj will be used. I will create a work-item to track this.

**Comment by daniel-packard** [comment] 2019-08-23 17:33
@vijayrkn -- seems I have the same issue with visual studio 2019, netstandard 2.0, and netcoreapp2.2

Is it better to file as a new issue since this is already closed for some time?

**Comment by dsplaisted** [comment] 2019-08-23 20:20
@daniel-packard Yes, please file a new issue with details about your issue, and as much as possible in terms of repro steps.  Thanks!
