### ISSUE TITLE
"emitEntryPoint": true is not creating exe

### ISSUE THREAD

**Issue by cheers00** [dotnet/cli#2571] opened 2016-04-18 20:16 UTC
I'm using the latest CLI (`rc2-002418`) and both `build `and `publish `commands not creating exe file. Is there any other setting to build exe file?

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },
    "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-23931"
        },
        "NETStandard.Library": "1.0.0-rc2-*",
        "System.Xml.XmlDocument": "4.0.1-rc2-*",
        "System.Xml.ReaderWriter": "4.0.11-rc2-*",
        "System.Xml.XmlSerializer": "4.0.11-rc2-*",
        "System.Diagnostics.TraceSource": "4.0.0-rc2-*",
        "System.Diagnostics.Tracing": "4.1.0-rc2-*",
        "System.Collections": "4.0.11-rc2-*",
        "System.Collections.NonGeneric":"4.0.1-rc3-*"
    },
 "runtimeOptions": {
      "configProperties": {
      "System.GC.Server": true
     }
  },
  "frameworks": {
      "netcoreapp1.0": {}
  }
}

```

**Comment by piotrpMSFT** [comment] 2016-04-18 23:06
@cheers00 this is a documentation issue. The system is behaving as designed. @blackdwarf is working on updated docs, so assigning to him to make sure you get unblocked.

**Comment by blackdwarf** [comment] 2016-05-20 02:47
@cheers00 this document explains the types of portability that apps can have and what is the output of each: http://dotnet.github.io/docs/core-concepts/app-types.html. 

I will close this issue. If this explanation is not sufficient, please reopen this issue or file a new one under dotnet/core-docs.

**Closed by blackdwarf** 2016-05-20 02:47 UTC
Labels: question

**Comment by hassanselim0** [comment] 2016-05-21 23:31
It's still not clear how can I make it generate an exe file (the renamed corehost.exe file) in the case of a "Portable Application", and what exactly does the "emitEntryPoint" value do.

**Comment by blackdwarf** [comment] 2016-05-22 00:00
@hassanselim0 you don't. For portable apps, you use the runner. The "emitEntryPoint" creates an entry point which you need in your IL code.

**Comment by hassanselim0** [comment] 2016-05-22 12:41
I think the documentation needs to get better at specifying the difference between the following with regards to the output you get:
building a portable app
publishing a portable app
building a self-contained app
publishing a self-contained app

I don't quite yet understand the difference between building and publishing a portable app, but I think I understand the rest now.

**Comment by blackdwarf** [comment] 2016-05-22 16:59
@hassanselim0 OK, fair enough. I should probably update that document. 

The different between publishing a portable app an building it is where your dependencies that exist outside of .NET Core come from. In the first case, a built app, they come from your NuGet cache. In the second case, a published app, they are packaged with your application. 

Hope this makes it somewhat clearer.

**Comment by GuardRex** [comment] 2016-05-23 06:25
@hassanselim0 

@blackdwarf may have one on the way for the outputs of publishing, as well. That's currently listed for RTM: https://github.com/dotnet/cli/issues/937

I'm also fleshing out some details in an unofficial IIS helper doc in the Slack #iis channel ( http://tattoocoder.com/aspnet-slack-sign-up/ ) that has some info in these regards.

... and I think you probably got this from @blackdwarf's response, but you don't really "build a self-contained app," since using cached packages wouldn't result in something "self-contained" by definition. I'm very glad you asked about that tho ... I'd like to add something to the unofficial doc that pertains to these concepts, as well. :+1:
