### ISSUE TITLE
Could not read the incremental cache file

### ISSUE THREAD

**Issue by serdna27** [dotnet/cli#3187] opened 2016-05-22 17:17 UTC
## Steps to reproduce

Was working with Aspnet core rc2 with the new tooling. Made some changes to controllers, models among others changes using dotnet watch. After i finished editing an error was thrown in the console: "Could not read the incremental cache file". I stopped the watch re-run the project but the error keep showing.
## Environment data

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by peterblazejewicz** [comment] 2016-05-22 21:31
@serdna27 
I'm getting the same. Have you used `dotnet watch` tool by chance? I don't remember similar problem with `dotnet run`

**Comment by peterblazejewicz** [comment] 2016-05-22 21:33
@serdna27 
try: `rm -rf obj/ && dotnet watch` from the project root

**Comment by serdna27** [comment] 2016-05-23 23:55
Thanks your solution works.

**Comment by piotrpMSFT** [comment] 2016-05-26 06:33
@victorhurdugaci can you take a look? we shouldn't require deleting obj before running `dotnet watch`

**Comment by victorhurdugaci** [comment] 2016-05-26 16:17
Some people reported that on dotnet watch too: https://github.com/aspnet/dotnet-watch/issues/97

I'm not sure if this is a watcher issue. The watcher kills the process and then calls `dotnet run` (or `dotnet <whatever command you pass>`).

@serdna27 if you see that error again, can you please what dotnet processes are running and what arguments were used to start them?

**Comment by nbarbettini** [comment] 2016-05-27 16:53
I received this error, although I wasn't using ``dotnet watch``. I started a build, then canceled it before it finished. When I tried to build again, ``dotnet build`` threw this error.

**Comment by shanselman** [comment] 2016-06-17 19:34
I'm seeing this regularly when using `dotnet watch`.

**Comment by mclark1129** [comment] 2016-06-19 14:36
I'm writing a script to build and run all the projects and services needed in my current app.  I am able to reproduce this issue 100% of the time in my WebAPI project

```
dotnet restore
dotnet build **/project.json

start cmd /k "cd MyApp.Api && dotnet run"
start cmd /K "cd MyApp.Services.EventHandlerService && dotnet run"
```

Both .NET projects were generated using the ASP.NET core yeoman generator (WebAPI and ConsoleApplication, respectively)

They are both targeting net461, although they are built exclusively using dotnet CLI tooling.

My console app starts perfectly every time, the API project fails with the incremental cache error every time.  If I run `dotnet run` in the API window that was spawned, it works fine as well.  This only occurs for me when I try to launch the API project as a part of this script.

**Comment by julielerman** [comment] 2016-06-19 15:12
Also getting it with dotnet watch. Is there a workaround for now and will it be fixed by RTM? (My current concern is some upcoming conference demos and running them as efficiently as possible). I followed through the referenced issues and am not finding something that looks like a resolution on the way. Thanks

**Comment by victorhurdugaci** [comment] 2016-06-20 15:43
@piotrpMSFT this is a CLI issue. People are able to reproduce it without the watcher. It seems to happen when you run build multiple times (the watcher does that). Can you assign someone to investigate?

cc @cdmihai because he seems to be the author of the file from where the message comes from https://github.com/dotnet/cli/blob/18c8a2724ad066a6999540f5015e1a0ed89b94fc/src/dotnet/commands/dotnet-build/IncrementalCache.cs

**Comment by cdmihai** [comment] 2016-06-20 16:27
The cache file is written with FileShare.None and read with FileShare.Read to prevent reading it when it's in a bad state. If you call build on the same output directory in parallel, you might get a race. Does dotnet watch run builds in parallel, or does it try to serialize them?

@victorhurdugaci  Do you know the repro steps without dotnet watch?

**Comment by victorhurdugaci** [comment] 2016-06-20 16:32
I don't have a repro without the watcher but I have an idea: you run the watcher at the same time as VS; both call build; you end up with a race. You might try build from console instead of the watcher with VS open but simply running build from console will not trigger the race. You probably have to change a file so VS build is triggered too.

`dotnet watch` waits for the child `dotnet` process to end before restarting.

**Comment by cdmihai** [comment] 2016-06-20 17:49
If `dotnet watch` waits, I am curious what causes the race. Does `dotnet watch` respect project dependencies when it triggers builds? If not, it could race when it watches both a project and it's dependent projects. If A depends on B, and you have A and B under watch, triggering a parallel dotnet build call on A and B will result in trying to build B twice.

Related to #2616

**Comment by victorhurdugaci** [comment] 2016-06-20 17:52
`dotnet watch` calls `dotnet run` on the project being watched. It only calls it on one project (the top one being watched). My guess it that on the system there might be another dotnet running (like the one from VS) that causes the race.

@shanselman @julielerman @serdna27 @peterblazejewicz was VS/VSCode running while you hit this issues?

**Comment by julielerman** [comment] 2016-06-20 17:55
yes vscode was running for sure. I'm doing this while coding/debugging and most often using either the new built in terminal or popping out to a terminal window. This was not something that I triggered via VSCode's debug feature.

**Comment by peterblazejewicz** [comment] 2016-06-20 18:34
> @shanselman @julielerman @serdna27 @peterblazejewicz was VS/VSCode running while you hit this issues?

@victorhurdugaci OS X console (first class citizen, the next one is via VSCode - but it requires tasks). Thanks!

**Comment by shanselman** [comment] 2016-06-21 13:54
@victorhurdugaci Yes, I was running VS code and running within its terminal

**Comment by victorhurdugaci** [comment] 2016-06-22 18:41
@cdmihai were you able to reproduce this?

**Comment by cdmihai** [comment] 2016-06-23 18:33
I haven't tried, but it is a known issue with build: #2616
And it will be a known issue with MSBuild as well.

If we want to fix this, I'd vote for fixing it for MSBuild.

**Comment by sifeij** [comment] 2016-07-21 15:24
`rm -rf obj/ && dotnet watch` from the project root worked for me. Thank you.

**Comment by 0xdeafcafe** [comment] 2016-09-27 10:19
Was there any further updates on this? It's still happening, and it's incredibly frustrating - especially while developing many services simultaneously. Having to run `rm -r ./obj` every 15 minutes or so isn't really acceptable.

**Comment by piotrpMSFT** [comment] 2016-11-10 09:10
As @cdmihai mentioned, this will be fixed as Microsoft/MSBuild#2616. As of preview3, the CLI's incremental cache is gone.

**Closed by piotrpMSFT** 2016-11-10 09:10 UTC

**Comment by mcintyre321** [comment] 2016-11-25 10:21
I got this while using R#s continuous testing feature

**Comment by joelharkes** [comment] 2017-01-06 08:13
We are still running on the project.json version of the dotnet cli, and here we also constantly have the same issue.

**Comment by joelharkes** [comment] 2017-01-19 16:16
I even run into this if I manually create dependency tree with a nodjs app. And build dependencies in parallel with dotnet build --no-dependency I wonder if the dotnet build process quits before fileshare flags are set properly?
I'll try adding some hard delays inside my node script/cli tool, and see if this prevents it. 

(Had to build it because I want to build and run multiple startup projects)

It would be nice if dotnet run could be forced not to rebuild/check builds (with a CLI flag).
