### ISSUE TITLE
output parameter for command "dotnet publish" works wrong 

### ISSUE THREAD

**Issue by FinexTech** [dotnet/cli#12714] opened 2019-09-20 14:40 UTC
We use dotnet version '3.0.100-rc1-014190'.
Documentation for output parameter states: ' If the path is relative, the output directory generated is relative to the project file location, not to the current working directory.'
To publish application we use next command: 'dotnet publish -r linux-musl-x64 -c "Release" --self-contained=false -o "out"  PATH_TO_SOLUTION'
Publish result of all projects is copied into folder relative to the working directory.
Previous dotnet version creates out folders relative to project file locations.
Is it expected behavior?
Thanks.

**Comment by ericstj** [comment] 2019-09-25 20:09
@livarcocc @nguerrera i think this is CLI /SDK behavior.

**Comment by brunocampiol** [comment] 2019-09-25 23:58
I have same situation here. Previously it would push files into the specified folder. Now it is relative to the project, I think. Can someone look at this?

**Comment by mohag** [comment] 2019-09-26 07:33
#9892 seems to intentionally introduced the behaviour... (I'm not sure if it considered solutions instead of individual `.csproj` files though)

Also see #6700, #4765

**Comment by dasMulli** [comment] 2019-09-26 09:18
Yes, this was an intentional breaking change for 3.0.

This is the way the CLI originally worked in the 1.0-preview area for project.json / .NET Core 1.0 pre-VS-2017. When moving to msbuild, this behaviour changed and it got some negative feedback. Re-rooting relative arguments to CLI commands is something unnatural that no other tool does. I was too late trying to get the change into 2.0 so 3.0 it is (it is breaking after all).

**Comment by dasMulli** [comment] 2019-09-26 09:19
Btw it has been in every 3.0 preview so far..

**Comment by FinexTech** [comment] 2019-09-26 09:22
Is there any sense to publish 2+ projects into the same (single) folder? Here I am talking about publishing solution, not single project.

**Comment by dasMulli** [comment] 2019-09-26 09:25
https://github.com/dotnet/sdk/issues/3650

Calling `dotnet publish` on a sln file is gambling and I could sleep better at night if it just quit with an error.

**Comment by dasMulli** [comment] 2019-09-26 09:25
`dotnet publish some.sln -r some-RID` => leap of faith no less

**Comment by livarcocc** [comment] 2019-09-30 17:56
I agree with all the things @dasMulli has said above. We are looking to improve working with solutions in the 5.0 timeframe.

Meanwhile, the change as described by @dasMulli is by design for 3.0.

**Closed by livarcocc** 2019-09-30 17:56 UTC

**Comment by Indomitable** [comment] 2020-01-13 14:42
Hi, 
  is it possible to update docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish currently there is: 
```
If the path is relative, the output directory generated is relative to the project file location, not to the current working directory.
```
while on dotnet core 3+ it works the other way around.

**Comment by dasMulli** [comment] 2020-01-13 15:43
updating the docs is already filed at https://github.com/dotnet/docs/issues/12486
