### ISSUE TITLE
dotnet-install.cmd fails if install path contains a space

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/cli#11521] opened 2019-06-10 23:55 UTC
## Steps to reproduce
On Windows, run this:
```
dotnet-install.cmd -InstallDir "c:\Users\<user>\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode.sample-extension\.dotnet\2.2.0" -Runtime dotnet -Version 2.2.0
```

## Expected  behavior
Should install

## Actual behavior
Gives an error:
```
Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
```

The path is correctly interpreted by the batch file, but PowerShell is getting a corrupted value for the $Archtecture parameter (`"Insiders\User\globalStorage\ms-vscode.sample-extension\.dotnet\2.2.0"`)

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by StephenWeatherford** [comment] 2019-06-11 00:06
Note: Works if you use single quotes instead of double quotes in the call to dotnet-install.cmd

**Comment by johnbeisner** [comment] 2019-09-13 15:29
@StephenWeatherford 
I could not reproduce the failure. I used the following command:
`.\dotnet-install.ps1 -Version "2.1.701" -InstallDir "D:\G\Test - Folder" -Verbose "True"`

**Comment by johnbeisner** [comment] 2019-09-13 16:03
moving this issue to dotnet/arcade: https://github.com/dotnet/arcade/issues/3941

**Comment by johnbeisner** [comment] 2019-09-13 16:03
dotnet-install.cmd is supported by dotnet/arcade

**Closed by johnbeisner** 2019-09-13 16:03 UTC
Labels: Install-Script
