### ISSUE TITLE
Nuget cache is being corrupted after running build

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#2683] opened 2016-04-25 22:31 UTC
## Steps to reproduce
build.bat/build.sh

## Expected  behavior
Build should not be placing partial host nuget packages in the real cache as they are causing cross build/publish to not work after running build

## Actual behavior
It does happen

## Environment data
`dotnet --info` output: irrelevant

**Comment by brthor** [comment] 2016-04-26 17:38
Should do something like this
https://github.com/dotnet/cli/blob/rel/1.0.0/build.sh#L19

but all the time

**Comment by piotrpMSFT** [comment] 2016-04-27 23:25
#2405 is a duplicate of this issue.

**Comment by eerhardt** [comment] 2016-09-20 16:35
Since the host is now built out of the core-setup repo, the CLI no longer has this issue.  Closing.

**Closed by eerhardt** 2016-09-20 16:35 UTC
