### ISSUE TITLE
dotnet restore incompatibility (ubuntu.15.10-x64)

### ISSUE THREAD

**Issue by yigitgursoy** [dotnet/cli#1179] opened 2016-02-02 14:54 UTC
error: Microsoft.Win32.Primitives 4.0.1-rc3-23720 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Console 4.0.0-rc3-23720 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Debug 4.0.11-rc3-23720 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Process 4.1.0-rc3-23720 provides a compile-time reference assembly for System.Diagnostics.Process on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.IO.FileSystem 4.0.1-rc3-23720 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Primitives 4.0.11-rc3-23720 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Sockets 4.1.0-rc3-23720 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.Extensions 4.1.0-rc3-23720 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc3-23720 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading 4.0.11-rc3-23720 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.15.10-x64).
info : Committing restore...
info : Restore failed in 103472ms.

**Comment by brthor** [comment] 2016-02-02 21:56
Please share your project.json

**Comment by yigitgursoy** [comment] 2016-02-03 06:15
Project.json file:
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23727"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

**Comment by swgillespie** [comment] 2016-02-16 04:19
This happens to me as well when restoring the project created by `dotnet new`.

Version:
```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.10
 OS Platform: Linux
 Runtime Id:  ubuntu.15.10-x64
```

**Comment by blackdwarf** [comment] 2016-02-25 06:42
@yigitgursoy does this still repro with latest bits?

**Comment by yigitgursoy** [comment] 2016-02-25 07:06
I installed Ubuntu v14 instead. Maybe @swgillespie still has v15.

**Comment by tlycken** [comment] 2016-02-25 07:38
I have 15.10 and could reproduce the other day. Don't remember if it was a build from source or whatever I got from `apt-get`, but I can do some testing this weekend. (Possibly I'll need someone to guide me through building process etc...)

**Comment by swgillespie** [comment] 2016-02-25 18:00
@blackdwarf This still repros with the latest debian package:

```
[sean ~/Documents/workspace/csharp/stuff]
$ dotnet new
Created new C# project in /home/sean/Documents/workspace/csharp/stuff.
[sean ~/Documents/workspace/csharp/stuff]
$ dotnet restore
log  : Restoring packages for /home/sean/Documents/workspace/csharp/stuff/project.json...
error: Microsoft.Win32.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.AppContext 4.1.0-rc2-23811 provides a compile-time reference assembly for System.AppContext on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Collections 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Collections on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Console 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Tools 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tools on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Diagnostics.Tracing 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tracing on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Globalization 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Globalization on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Globalization.Calendars 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Globalization.Calendars on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.IO 4.1.0-rc2-23811 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.IO.FileSystem 4.0.1-rc2-23811 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Primitives 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Net.Sockets 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.Extensions 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Reflection.TypeExtensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection.TypeExtensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.Extensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.Handles 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Runtime.Handles on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.InteropServices 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Text.Encoding 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Text.Encoding.Extensions 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading.Tasks 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: System.Threading.Timer 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Threading.Timer on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.15.10-x64).
info : Committing restore...
log  : Restore failed in 769ms.
Errors in /home/sean/Documents/workspace/csharp/stuff/project.json
    Microsoft.Win32.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.AppContext 4.1.0-rc2-23811 provides a compile-time reference assembly for System.AppContext on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Collections 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Collections on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Console 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Debug 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Tools 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tools on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Diagnostics.Tracing 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tracing on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Globalization 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Globalization on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Globalization.Calendars 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Globalization.Calendars on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.IO 4.1.0-rc2-23811 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.IO.FileSystem 4.0.1-rc2-23811 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Net.Primitives 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Net.Sockets 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.Extensions 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Reflection.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Reflection.TypeExtensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Reflection.TypeExtensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.Extensions 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.Handles 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Runtime.Handles on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.InteropServices 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Text.Encoding 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Text.Encoding.Extensions 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Text.Encoding.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading.Tasks 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    System.Threading.Timer 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Threading.Timer on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
    Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.15.10-x64).
NuGet Config files used:
    /home/sean/Documents/workspace/csharp/stuff/NuGet.Config
    /home/sean/.nuget/NuGet/NuGet.Config
Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
[sean ~/Documents/workspace/csharp/stuff]
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001563)

Product Information:
 Version:     1.0.0-beta-001563
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.10
 OS Platform: Linux
 Runtime Id:  ubuntu.15.10-x64
```

**Comment by brthor** [comment] 2016-02-25 18:20
We don't currently do any testing on 15.10 and this looks like a rid issue in the packages.

I expect this to repro independently of being installed of the debian package.

**Comment by brthor** [comment] 2016-02-25 18:30
As a workaround, you may be able to try this:
`dotnet restore --runtime ubuntu.14.04-x64'

Can't guarantee what results you will get though.

**Comment by cpx** [comment] 2016-03-13 13:16
I can verify it works with restore and build, but not with run. It fails with "Can not find runtime target for framework 'DNXCore,Version=v5.0' and RID's 'ubuntu.15.10-x64'."

**Comment by myoung34** [comment] 2016-03-14 13:49
Installing `libicu52` manually resolves the compatibility issue.
As for support for 15.10 it looks like its scheduled for [march mileston](https://github.com/dotnet/cli/milestones/RTM-March).

You can trick restore to work by setting the runtime to `14.04` via ` dotnet restore --runtime ubuntu.14.04-x64` but that doesn't work for run.

I guess I'll just sit and hope the march milestone gets `15.10` support in.

**Comment by cpx** [comment] 2016-03-14 22:26
@myoung34 
> Installing libicu52 manually resolves the compatibility issue.
Only partially. It seems to resolve the issue when deps are initially pulled down, but as noted there are other issues when actually running the tools.

@brthor What is the motivation behind not testing on 15.10 to keep it compatible? It seems a bit inconsistent since both the corefx and the coreclr projects do it (albeit as I understand it primarly preparation for the 16.04LTS)

**Comment by tmds** [comment] 2016-03-15 05:48
@jasonwilliams200OK do you know how to handle this:?
```
xxx provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.15.10-x64.
```

Are these what the [net-platform-standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md calls) "Anchored Assemblys"?

**Comment by AndrewBarfield** [comment] 2016-03-30 11:03
Does anyone know when this will be resolved? Has anything happened in the past 15 days?

**Comment by tmds** [comment] 2016-03-31 06:21
There are a number of issues related to "Ubuntu 15.10" support and none of them are moving. Today it isn't well documented how to port to an unsupported flavor of linux (see https://github.com/dotnet/corefx/issues/6770). If this improves, dotnet will boldy go where it hasn't gone before.

> give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime

Probably the new Ubuntu LTS release (16.04), due in a few weeks, will be supported on the short term.

**Comment by atrauzzi** [comment] 2016-04-26 02:33
16.04 is out...still can't install.

**Comment by markrendle** [comment] 2016-04-26 14:06
I suspect (I may be wrong) that there is a push to address the urgent platform-independent issues (i.e. those that exist across all the currently-officially-supported platforms (i.e. Windows, Mac, Ubuntu 14, Debian 8.2 and RH7)) to get the Release Candidate out the door (in line with ASP.NET Core RC2, which has been greatly delayed by re-platforming).

Until the RC is out, adding more distros, or versions of distros, into the mix is just going to push it further away, and nobody wants that.

In the meantime, you could try using [docknet](https://blog.rendle.io/run-dotnet-cli-on-unsupported-linux-distros-with-docknet/), although I haven't tested it myself lately so it might not be working.

**Comment by myoung34** [comment] 2016-04-26 16:13
I think there was a real architectural snafu here by requiring versions to be whitelisted. 
The longer this goes unresolved the more frustrated people will become and stop using it.

**Comment by jasonwilliams200OK** [comment] 2016-04-26 16:29
Guys, Ubuntu 15 seems to be working for both CoreFX and CoreCLR:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu15.10_debug/lastBuild/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/debug_ubuntu15.10/lastBuild/

*[nit] @mmitche, can we have uniform URL slug in core[fx/clr] `ubuntu15.10_debug` vs. `debug_ubuntu15.10` :smile:*

---

CoreFX has even a issue tracking Ubuntu 16 CI https://github.com/dotnet/corefx/issues/7191.

As @brthor  said, this must be the RID issue in CLI and Ubuntu 15 is explicitly excluded for CLI in CoreCLR in https://github.com/dotnet/coreclr/pull/3577.

@ellismg, on this note, if CoreCLR is building fine and issues are sorted out, can this be addressed: https://github.com/dotnet/coreclr/issues/3271. There is a significant demand on Ubuntu 15 based on the feedback in CLI and CoreCLR repos. We certainly ack that you guys are super busy stabilizing the current platform set for RC2; meanwhile, is there anything we can do to resolve the next blockers for Ubuntu 15?

**Comment by mmitche** [comment] 2016-04-26 16:52
@jasonwilliams200OK Yeah, the job names can be changed pretty easily.  Which do you prefer?

**Comment by jasonwilliams200OK** [comment] 2016-04-26 16:56
@mmitche, thanks. I would say `{Platform}_{BuildConfiguration}` for two reasons:

* platform is more significant (but that's debatable)
* less replacements in CoreCLR's README :smile:

**Comment by fuszenecker** [comment] 2016-05-11 18:22
After having created a new project, I receive the following result:

```
fuszenecker@fuszenecker:~/nu$ rm -rf *
fuszenecker@fuszenecker:~/nu$ dotnet new
Created new C# project in /home/fuszenecker/nu.
fuszenecker@fuszenecker:~/nu$ dotnet restore
log  : Restoring packages for /home/fuszenecker/nu/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 478ms
error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002700)' for '.NETCoreApp,Version=v1.0'.
info : Committing restore...
log  : Writing lock file to disk. Path: /home/fuszenecker/nu/project.lock.json
log  : /home/fuszenecker/nu/project.json
log  : Restore failed in 1333ms.

Errors in /home/fuszenecker/nu/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002700)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    /home/fuszenecker/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
fuszenecker@fuszenecker:~/nu$
```

```dotnet --info``` says:
```
fuszenecker@fuszenecker:~$ dotnet --info
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
fuszenecker@fuszenecker:~$
```

Do you have any idea why it happens?
Thanks, Robert

**Comment by ellismg** [comment] 2016-05-11 18:25
@fuszenecker The packages have not been published to NuGet yet, so you need to add a NuGet config that tells NuGet to also look at MyGet:

Place a file called `NuGet.config` in your project folder

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

And try restore again.

This will be resolved in a few days when we publish the final packages to NuGet.

**Comment by fuszenecker** [comment] 2016-05-12 06:37
Many thanks, Ellismg, I'll check this nuget config this evening.

**Comment by fuszenecker** [comment] 2016-05-12 18:45
```
log  : Restore completed in 16610ms.

NuGet Config files used:
    /home/fuszenecker/.nuget/NuGet/NuGet.Config

Feeds used:
    https://www.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json

Installed:
    11 package(s) to /home/fuszenecker/nu/project.json
fuszenecker@fuszenecker:~/nu$
```

Works perfectly. Thanks Ellismg, again.

**Comment by piotrpMSFT** [comment] 2016-07-27 23:22
Sounds like this is resolved. Thanks all.

**Closed by piotrpMSFT** 2016-07-27 23:22 UTC
Labels: bug
