### ISSUE TITLE
dotnet run NRE

### ISSUE THREAD

**Issue by mausch** [dotnet/cli#3127] opened 2016-05-19 10:32 UTC
## Steps to reproduce

$ docker run --rm -it microsoft/dotnet-preview
$ dotnet run

## Expected  behavior

Show some meaningful error message.

## Actual behavior

Shows "Object reference not set to an instance of an object."

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

**Comment by dasMulli** [comment] 2016-05-19 11:13
Possible duplicate of https://github.com/dotnet/cli/issues/2965

**Comment by piotrpMSFT** [comment] 2016-05-26 08:06
Fixed by https://github.com/dotnet/cli/pull/2980

**Closed by piotrpMSFT** 2016-05-26 08:06 UTC
