### ISSUE TITLE
The executable generated from `dotnet publish -r ubuntu.16.04-x64` doesn't have "x" permission

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/cli#6286] opened 2017-04-10 21:32 UTC
`dotnet publish -r ubuntu.16.04-x64` generates an executable, however, the executable file doesn't have "x" permission.
This happens when building a stand-alone application targeting `netcoreapp2.0` with `dotnet-cli 2.0.0-preview1-005724`. It is a regression comparing to `dotnet sdk 1.0`.

## Steps to reproduce
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>ubuntu.16.04-x64</RuntimeIdentifier>
  </PropertyGroup>

</Project>

# dotnet restore
# dotnet publish -r ubuntu.16.04-x64
[/temp/console]
bash:96> bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
bash: bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console: Permission denied
[/temp/console]
bash:97> dir bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
-rw-rw-r-- 1 dongbo dongbo 66412 Apr 10 14:12 bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console
```

## Expected  behavior
The file `bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/console` is an executable and should have the "x" permission.

## Actual behavior
It doesn't have the "x" permission.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005724)

Product Information:
 Version:            2.0.0-preview1-005724
 Commit SHA-1 hash:  e391b5d5f3

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/dongbo/.dotnet/sdk/2.0.0-preview1-005724/
```

**Comment by kichalla** [comment] 2017-04-14 19:22
cc @Eilon

**Comment by livarcocc** [comment] 2017-04-14 19:57
@eerhardt @ramarag can we double check that apphost.exe is properly chmoded? I wonder if the change we made in the SDK for it broke this scenario.

**Comment by eerhardt** [comment] 2017-04-14 19:59
Duplicate of https://github.com/NuGet/Home/issues/4424

See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-2-self-contained

**Comment by livarcocc** [comment] 2017-04-14 20:07
@eerhardt Is this exe pulled out of the nuget cache or out of the CLI build location? Wondering if there is anything we can do to work around this problem during publish.

**Comment by eerhardt** [comment] 2017-04-14 20:09
It is pulled out of the nuget cache, like always.

> Wondering if there is anything we can do to work around this problem during publish.

We could, but that doesn't solve every other scenario that needs to get executables/scripts out of nuget packages.  I would rather we ask NuGet or corefx to fix this issue, so it gets solved for everyone.

**Comment by Eilon** [comment] 2017-04-17 22:28
CLI folks: Is this planned to be fixed for Preview1? I think this could be a ship-blocker, no?

cc @livarcocc

**Comment by muratg** [comment] 2017-04-24 19:58
*ping*

**Comment by eerhardt** [comment] 2017-04-24 19:59
@muratg - please ping @rrelyea.  This is a NuGet bug:  https://github.com/NuGet/Home/issues/4424

**Comment by tmds** [comment] 2017-04-27 11:59
@eerhardt Why is this a NuGet bug? How does NuGet affect the executable file generated by the `dotnet publish` command?

**Comment by dasMulli** [comment] 2017-04-27 12:07
> How does NuGet affect the executable file

I think the idea is that NuGet should create the files in the package cache with proper permissions and record permissions on `pack`.

I'd like to see a more comprehensive fix in the SDK that sets the proper permission on *nix machines, not assuming that the package cache can even have those flags (depending on file system, umask etc.)

**Comment by tmds** [comment] 2017-04-27 12:13
@dasMulli For pack, I understand the relationship. My question is how `publish` is related to NuGet.

**Comment by dasMulli** [comment] 2017-04-27 12:19
It just copies / renames the `dotnet` / `apphost` executable from the cache

**Comment by RheaAyase** [comment] 2017-04-27 12:29
Just for the sake of OCD, could we just remove the ubuntu refence from the tile of this issue and have it something like #6437 ?

**Comment by eerhardt** [comment] 2017-04-27 13:45
> My question is how publish is related to NuGet.

We don't create the `apphost` executable during "publish".  It is created when we build `dotnet/core-setup` and then put into a NuGet package.

"publish" takes assets and copies them to your publish folder.  It can't know what the permissions should be for all the assets that it copies.  Say a NuGet package has a `.sh` script in it and you need to invoke it in your app.  How is publish supposed to know to make that executable?

Or say (even more likely) a NuGet package has a `.sh` tool script in it, and it needs to be invoked during the build.  (or some other executable like `crossgen`)

The underlying issue here is that when I create a NuGet package, the .nupkg should retain the permissions at the time it was created.  Then when the .nupkg is restored, it should be restored with the same file permissions.

Can we work around this in publish just for the `apphost` executable?  Yes.  But then the next scenario comes along that needs to execute a file and is broken.  So why add all these little workarounds to every place that needs to execute a file, and instead fix the underlying issue.

**Comment by tmds** [comment] 2017-04-27 13:56
@dasMulli @eerhardt thanks, relationship is clear now.

**Comment by livarcocc** [comment] 2017-05-04 04:40
I agree with @eerhardt, we should not go around adding one workaround after another. I will close this issue and we will track this fix through NuGet/Home#4424.

**Closed by livarcocc** 2017-05-04 04:40 UTC

**Comment by muratg** [comment] 2017-05-04 06:00
@livarcocc FWIW https://github.com/NuGet/Home/issues/4424 is closed. Do we need another issue to track?

**Comment by eerhardt** [comment] 2017-05-05 19:07
When is a new drop of NuGet coming into the .NET Core SDK?
