### ISSUE TITLE
Microsoft.NETCore.App cannot be restored on projects with netstandard1.0, netstandard1.1, netstandard1.2, netstandard1.3, netstandard1.4.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2924] opened 2016-05-06 18:55 UTC
## Expectations
`Microsoft.NETCore.App` currently targets netstandard1.0 which lead me to believe it'd be possible (although not recommended) to use it in a >= netstandard1.0 project. However, it seems that the package is hand crafted and has dependencies that are inconsistent with its actual TFM.

## Steps to reproduce
- Create a project with the `project.json`:
```json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netstandard1.0": {
      "dependencies": {}
    }
  }
}
```
*You can can change the netstandard1.0 tfm to 1.1, 1.2, 1.3 or 1.4 and get the same behavior*
- Run dotnet restore

## Expected  behavior
- Restore completes successfully because `Microsoft.NETCore.App`'s nupkg says it targets `netstandard1.0`.

## Actual behavior
- Restore fails because `Microsoft.NETCore.App` actually targets packages that depend on `netstandard1.5`

Attached error log: [restoreerror.txt](https://github.com/dotnet/cli/files/252868/restoreerror.txt)

## Environment data
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:     1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

This seems like a blocker since the `Microsoft.NETCore.App` is the bread and butter to .NET core but I'll let the higher powers decide.

/cc @Eilon @DamianEdwards @davidfowl

**Comment by piotrpMSFT** [comment] 2016-05-06 19:16
@weshaggard can you take a look at this one?

**Comment by brthor** [comment] 2016-05-06 19:16
```
"Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
```

Has been intended to be used for runnable applications targeting netcoreapp1.0

When using netstandard tfms it is expected that you will use NETStandard.Library.

**Comment by NTaylorMullen** [comment] 2016-05-06 19:19
@brthor of course, but the package should reflect that (aka denoting where a package can be restored). It targeting `netstandard1.0` breaks the promise of a nupkg. My suggestion is to up `Microsoft.NETCore.App` to `netstandard1.3`.

**Comment by brthor** [comment] 2016-05-06 19:20
@NTaylorMullen deleted the comment right after I posted it, since I realized this issue was not about quite the same thing. 😄

**Comment by piotrpMSFT** [comment] 2016-05-06 19:21
The project.json for Microsoft.NetCore.App actually states netstandard1.5. However, I see we're using pkgproj for the creation of this package and its configuration is out of sync:
https://github.com/dotnet/cli/blob/rel/1.0.0/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj#L12

@weshaggard please take a look. This does seem rather bad.

**Comment by piotrpMSFT** [comment] 2016-05-08 20:21
I chatted briefly with @weshaggard about this on Friday and he seemed to feel that the current behavior is by-design. I'll leave it to @weshaggard to comment here and to close the bug if appropriate.

**Comment by NTaylorMullen** [comment] 2016-05-08 23:46
@weshaggard Why do we need to target netstandard1.0 for `Microsoft.NETCore.App`?

**Comment by davidfowl** [comment] 2016-05-08 23:47
@piotrpMSFT @weshaggard What's exactly is by design? Shouldn't it be targeting netcoreapp1.0? Seems pretty wrong that it doesn't.

**Comment by weshaggard** [comment] 2016-05-09 16:50
This is actually a bug.

@davidfowl would you suggest we just remove the TFM from the dependencies set which would give people the most flexibility in trying to use this meta-package or should we just bind it to netcoreapp1.0? 

cc @ericstj

**Comment by joganet** [comment] 2016-05-09 21:42
Hi Guys, I don't know if this applies for this same issue or I should raise a new one but looks pretty close to what I have been dealing with.

we have a core library targetting to netstandard1.5 framework and another project for unit test targetting "Microsoft.NETCore.App": {"version": "1.0.0-*", "type": "platform"}

the library restore, compile and pack pretty well. (this is the project.json)
{
  "version": "1.0.0-alpha-*",
  "description": "My .Net Core Class Library",

  "packOptions": {
    "content": "content/Readme.txt",
    "releaseNotes": "Review Readme.txt for details.",
    "requireLicenseAcceptance": true,
  },

  "buildOptions": {
    "define": [ "DNXCORE50" ],
    "warningsAsErrors": false,
    "embed": [ "Properties/ReservedWords.txt" ],
    "exclude": [ "Extensions/Net40/**/*.*" ],
    "copyToOutput": {
      "contentFiles": [ "NuGet.Config" ]
    }
  },


  "dependencies": {
    "NetStandard.Library": "1.5.0-rc2-24027",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "System.Collections.NonGeneric": "4.0.1-rc2-24027",
    "System.ComponentModel": "4.0.1-rc2-24027",
    "System.ComponentModel.Annotations": "4.1.0-rc2-24027",
    "System.ComponentModel.Primitives": "4.0.1-rc2-24027",
    "System.ComponentModel.TypeConverter": "4.0.1-rc2-24027",
    "System.Data.Common": "4.0.1-rc2-24027",
    "System.Data.SqlClient": "4.1.0-rc2-24027",
    "System.Diagnostics.Process": "4.1.0-rc2-24027",
    "System.Linq.Expressions": "4.0.11-rc2-24027",
    "System.Net.Security": "4.0.0-rc2-24027",
    "System.Text.Encoding.CodePages": "4.0.1-rc2-24027",
    "System.Threading.Timer": "4.0.1-rc2-24027",
    "System.Diagnostics.TextWriterTraceListener": "4.0.0-rc2-24027",
    "System.Net.Sockets": "4.1.0-rc2-24027",
    "System.Reflection": "4.1.0-rc2-24027",
    "System.IO.Compression": "4.1.0-rc2-24027",
    "System.Net.NameResolution": "4.0.0-rc2-24027",
    "System.Security.Principal.Windows": "4.0.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": { 
        "imports": "DNXCORE50" 
    }
  }
}

and this is project.json for the unit test
{
  "version": "1.0.0-alpha-*",
  "description": "My Test Class Library",
  "packOptions": {
    "requireLicenseAcceptance": true
  },

  "buildOptions": {
    "define": [ "DNXCORE50" ],
    "warningsAsErrors": false,
    "preserveCompilationContext": true,
    "copyToOutput": {
      "contentFiles": [ "appsettings.json", "NuGet.Config" ]
    }
  },

  "dependencies": {
    "MyLibrary": "1.0.0-alpha",
    "System.Data.Common": "4.0.1-rc2-24027",
    "dotnet-test-xunit": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*"
  },

  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}


for some reasons when I Add the dependency to MyLibrary the dotnet restore throw errors about incompatibilities from netstandard 1.5 with Net Core App 1.0

I attach the full output
[dotnet-restore.txt](https://github.com/dotnet/cli/files/255969/dotnet-restore.txt)


some one have a clue or is this a bug?


btw this is my dotnet cli info
.NET Command Line Tools (1.0.0-rc2-002677)

Product Information:
 Version:     1.0.0-rc2-002677
 Commit Sha:  d9d8bb2f03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64


Thanks in Advance

**Comment by brthor** [comment] 2016-05-09 21:48
@joganet I believe this is a separate issue but please share the project.json of the project referencing "MyLibrary"

**Comment by joganet** [comment] 2016-05-09 21:52
the project.json from MyLibrary is the first project json I paste, and the second project json is the one for the unitTest project
I will share again

MyLibrary project.json
{
 "version": "1.0.0-alpha-*",
 "description": "My .Net Core Class Library",

"packOptions": {
 "content": "content/Readme.txt",
 "releaseNotes": "Review Readme.txt for details.",
 "requireLicenseAcceptance": true,
 },

"buildOptions": {
 "define": [ "DNXCORE50" ],
 "warningsAsErrors": false,
 "embed": [ "Properties/ReservedWords.txt" ],
 "exclude": [ "Extensions/Net40/*/.*" ],
 "copyToOutput": {
 "contentFiles": [ "NuGet.Config" ]
 }
 },

"dependencies": {
 "NetStandard.Library": "1.5.0-rc2-24027",
 "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
 "System.Collections.NonGeneric": "4.0.1-rc2-24027",
 "System.ComponentModel": "4.0.1-rc2-24027",
 "System.ComponentModel.Annotations": "4.1.0-rc2-24027",
 "System.ComponentModel.Primitives": "4.0.1-rc2-24027",
 "System.ComponentModel.TypeConverter": "4.0.1-rc2-24027",
 "System.Data.Common": "4.0.1-rc2-24027",
 "System.Data.SqlClient": "4.1.0-rc2-24027",
 "System.Diagnostics.Process": "4.1.0-rc2-24027",
 "System.Linq.Expressions": "4.0.11-rc2-24027",
 "System.Net.Security": "4.0.0-rc2-24027",
 "System.Text.Encoding.CodePages": "4.0.1-rc2-24027",
 "System.Threading.Timer": "4.0.1-rc2-24027",
 "System.Diagnostics.TextWriterTraceListener": "4.0.0-rc2-24027",
 "System.Net.Sockets": "4.1.0-rc2-24027",
 "System.Reflection": "4.1.0-rc2-24027",
 "System.IO.Compression": "4.1.0-rc2-24027",
 "System.Net.NameResolution": "4.0.0-rc2-24027",
 "System.Security.Principal.Windows": "4.0.0-rc2-24027"
 },

"frameworks": {
 "netstandard1.5": { 
 "imports": "DNXCORE50" 
 }
 }
 }


unit Test project.json
{
 "version": "1.0.0-alpha-*",
 "description": "My Test Class Library",
 "packOptions": {
 "requireLicenseAcceptance": true
 },

"buildOptions": {
 "define": [ "DNXCORE50" ],
 "warningsAsErrors": false,
 "preserveCompilationContext": true,
 "copyToOutput": {
 "contentFiles": [ "appsettings.json", "NuGet.Config" ]
 }
 },

"dependencies": {
 "MyLibrary": "1.0.0-alpha",
 "System.Data.Common": "4.0.1-rc2-24027",
 "dotnet-test-xunit": "1.0.0-",
 "Microsoft.NETCore.Platforms": "1.0.1-"
 },

"testRunner": "xunit",
 "frameworks": {
 "netcoreapp1.0": {
 "imports": [
 "dnxcore50",
 "portable-net451+win8"
 ],
 "dependencies": {
 "Microsoft.NETCore.App": {
 "version": "1.0.0-*",
 "type": "platform"
 }
 }
 }
 }
 }

**Comment by GuardRex** [comment] 2016-05-09 23:04
@joganet You still have an rc1 package in there: `Microsoft.Extensions.Configuration.Json`. There is an rc2 package for that ... https://www.myget.org/gallery/aspnetcirelease

**Comment by joganet** [comment] 2016-05-10 16:16
Thanks GuardRex, I didn't have that feed, and last week we were told that an RC2 will be released shortly

just another question due to this update (besides the others about the project.json issue) I updated the dependendy to     "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-20852",
and now when I try to build throw two exceptions related to the object "Type" that doesn't have the method or the extension method for "GetField" and also for "GetProperties", where they did go?

I'm trying to see if there any dependency change but I need to test one by one.

**Comment by GuardRex** [comment] 2016-05-10 17:00
@joganet That package falls under Configuration. Try asking there, and they'll prob be able to help. https://github.com/aspnet/Configuration/issues

**Comment by joganet** [comment] 2016-05-10 17:13
Thanks GuardRex but actually I already resolved, it was the TypeExtensions dependency

Any clue why I can't do a restore in my test project.json? (the update o the dependency in rc1 will not fix the problem)

**Comment by GuardRex** [comment] 2016-05-10 17:27
@joganet If you're still getting the same conflicting requests on the same version as you showed in the TXT file of output above, no, I don't know the exact cause of that.

When I freeze package versions, what I usually do is float all of the versions first for both my NuGet package and my main app (e.g., wildcard `-*` versions on all packages and use the CI Release feed so that I only get RC2 packages across the board). I let `dotnet cli` evaluate the versions. When everything is happily restoring and compiling, I look inside the `project.lock.json` file and see what versions actually resolved ... then put those into the NuGet package dependencies and the app dependencies to freeze them both right there. In your case, I'd give that a shot: wildcard everything and stick with RC2 feeds, then see if you can get them restoring well ... then freeze the versions.

Side note: Lingering packages and SDK's can result in strange restore behavior. It's a good idea when running low on "good ideas" to refresh everything. See https://github.com/dotnet/cli/issues/2948 ... and clean your package cache out: `nuget locals all -clear` or navigate to `c:\Users\<USER>\.nuget\packages` and delete all of the cached packages.

**Comment by joganet** [comment] 2016-05-10 17:47
so there is no problem at all between netstandard.1.5 (library) and netcoreapp1.0 (unit test) is what you say?
we currently don't have yet the library in nuget or any internal nuget server, but I will try, I know the package has been detected because it detect the interntald ependencies and is when it says that it can't satisfy the cconflicting request (error: Unable to satisfy conflicting requests for 'System.Threading.Timer': System.Threading.Timer (>= 4.0.1-rc2-24027) (via project/MySql.Data.MySqlClient 1.0.0-alpha), System.Threading.Timer (>= 4.0.1-rc2-24027) (via package/NETStandard.Library 1.5.0-rc2-24027) <--- for example

I will wildcard and see what happens thanks

**Comment by GuardRex** [comment] 2016-05-10 17:53
@joganet That's correct. You do have the TFM's correct. My packages are `netstandard1.5`, and my apps are `netcoreapp1.0`. Yeah ... unfreeze and perhaps check for lingering old SDK's and `dotnet cli`'s in `Programs & Features`.

Worst case scenario is that you'll have to put up a repro so that a MS dev can pull it down and see what's what with the problem. They're monitoring our conversation :eyes:, and when they don't jump in quickly, it usually means that they are waiting to see if the ordinary troubleshooting advice works or fails. The next step will be 'please give us a GH repro ... a lib and an app that we can test.'

**Closed** 2016-05-27 19:37 UTC
Labels: question
