### ISSUE TITLE
F# classlib MissingMethodException in 2.0.0-preview2-006391

### ISSUE THREAD

**Issue by AnthonyLloyd** [dotnet/cli#6863] opened 2017-06-14 13:09 UTC
## Steps to reproduce

1. Create a F# classlib referenced by an F# console project
2. Code in the classlib builds fine but throws a MissingMethodException when run

An example I'm working on:
https://github.com/AnthonyLloyd/BenchmarksGame/tree/DotNetCore2preview2Bug

`dotnet build` succeeds
`dotnet run --project .\tester\tester.fsproj` fails

## Expected  behavior

The code builds so I wouldn't expect a missing method exception.

## Actual behavior

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Double FSharpOriginalNBody.test()'.                                      
   at Program.main@32-1.Invoke(Unit arg00@)                                                                                                     
   at Program.isFasterThan@26-1.Invoke(FSharpFunc`2 measurer) in C:\Users\Ant\src\BenchmarksGame\tester\Program.fs:line 26                      
   at Expecto.Performance.timeCompare[a](FSharpFunc`2 f1, FSharpFunc`2 f2) in C:\Users\Ant\src\BenchmarksGame\tester\Performance.fs:line 133    
   at Program.isFasterThanSub[a](FSharpFunc`2 f1, FSharpFunc`2 f2, String format) in C:\Users\Ant\src\BenchmarksGame\tester\Program.fs:line 10  
   at Program.isFasterThan[a](FSharpFunc`2 f1, FSharpFunc`2 f2, String message) in C:\Users\Ant\src\BenchmarksGame\tester\Program.fs:line 25    
   at Program.main(String[] argv) in C:\Users\Ant\src\BenchmarksGame\tester\Program.fs:line 32     
```                                             

I've checked that a mismatched function name causes a build error.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-006391)                      
                                                                     
Product Information:                                                 
 Version:            2.0.0-preview2-006391                           
 Commit SHA-1 hash:  ef5d4b47c3                                      
                                                                     
Runtime Environment:                                                 
 OS Name:     Windows                                                
 OS Version:  10.0.16215                                             
 OS Platform: Windows                                                
 RID:         win10-x64                                              
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006391\     
                                                                     
Microsoft .NET Core Shared Framework Host                            
                                                                     
  Version  : 2.0.0-preview2-25407-01                                 
  Build    : 40c565230930ead58a50719c0ec799df77bddee9                
```

**Comment by livarcocc** [comment] 2017-06-14 15:17
@KevinRansom @cartermp

**Comment by cartermp** [comment] 2017-06-14 15:59
cc @dsyme as well.  @KevinRansom is out this week, so he may not be able to take a look at this.

**Comment by enricosada** [comment] 2017-06-16 08:58
@livarcocc is possibile to add an `fsharp` label to these issues? i'd like to see what's missing/bugged in f# for `2.0.0`
Is a bit annoying to find these with search (github ignore the `#` pratically..)

**Comment by dsyme** [comment] 2017-06-16 16:05
@enricosada @cartermp (Though I do have ``tester.runtimeconfig.dev.json`` which indicates where fsharp.core lives, so that's probably a red herring)

**Comment by dsyme** [comment] 2017-06-16 16:07
@cartermp @KevinRansom @enricosada Ugh, I see this ``valuetype [netstandard]System.Double`` in the compiled binary - this looks wrong. 

```
.assembly extern netstandard
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 2:0:0:0
}
```
and
```
.method public static valuetype [netstandard]System.Double 
        test() cil managed
```

**Comment by dsyme** [comment] 2017-06-16 16:10
That is, I would expect simple "double" in these cases.  It looks at first sight like the F# compiler hasn't been correctly adjusted to emit primitive types correctly in the presence of the  "netstandard" library.  I don't know any of the details of this and I don't really understand what's going on

**Comment by dsyme** [comment] 2017-06-16 16:16
OK, so .NET Core 2.0 adds this new DLL ``netstandard.dll``

    packages\netstandard.library\2.0.0-preview2-2540101\build\netstandard2.0\ref\netstandard.dll

This seems to be yet another "mscorlib.dll" and "System.Runtime.dll" but I don't yet understand the rules concerning this.  I'm assuming the F# compiler just needs to be updated to understand this special DLL, though I'm unclear about if/how type forwarding works out to ensure these types all add up.

**Comment by dsyme** [comment] 2017-06-16 16:41
Here is the full command line being used:
```
         C:\Program Files\dotnet\sdk\2.0.0-preview2-006470\FSharp\RunFsc.cmd -o:obj\Debug\netstandard2.0\fsharp.dll
         -g
         --debug:portable
         --noframework
         --define:TRACE
         --define:DEBUG
         --define:NETSTANDARD2_0
         --optimize-
         --tailcalls-
         -r:C:\Users\dsyme\.nuget\packages\fsharp.core\4.2.1\lib\netstandard1.6\FSharp.Core.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\Microsoft.Win32.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\mscorlib.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\netstandard.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.AppContext.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Collections.Concurrent.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Collections.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Collections.NonGeneric.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Collections.Specialized.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ComponentModel.Composition.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ComponentModel.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ComponentModel.EventBasedAsync.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ComponentModel.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ComponentModel.TypeConverter.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Console.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Core.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Data.Common.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Data.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.Contracts.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.Debug.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.FileVersionInfo.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.Process.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.StackTrace.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.TextWriterTraceListener.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.Tools.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.TraceSource.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Diagnostics.Tracing.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Drawing.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Drawing.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Dynamic.Runtime.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Globalization.Calendars.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Globalization.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Globalization.Extensions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.Compression.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.Compression.FileSystem.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.Compression.ZipFile.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.FileSystem.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.FileSystem.DriveInfo.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.FileSystem.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.FileSystem.Watcher.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.IsolatedStorage.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.MemoryMappedFiles.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.Pipes.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.IO.UnmanagedMemoryStream.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Linq.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Linq.Expressions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Linq.Parallel.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Linq.Queryable.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Http.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.NameResolution.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.NetworkInformation.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Ping.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Requests.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Security.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.Sockets.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.WebHeaderCollection.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.WebSockets.Client.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Net.WebSockets.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Numerics.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ObjectModel.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Reflection.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Reflection.Extensions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Reflection.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Resources.Reader.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Resources.ResourceManager.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Resources.Writer.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.CompilerServices.VisualC.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Extensions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Handles.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.InteropServices.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.InteropServices.RuntimeInformation.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Numerics.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Serialization.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Serialization.Formatters.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Serialization.Json.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Serialization.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Runtime.Serialization.Xml.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Claims.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Cryptography.Algorithms.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Cryptography.Csp.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Cryptography.Encoding.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Cryptography.Primitives.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Cryptography.X509Certificates.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.Principal.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Security.SecureString.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ServiceModel.Web.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Text.Encoding.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Text.Encoding.Extensions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Text.RegularExpressions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.Overlapped.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.Tasks.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.Tasks.Parallel.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.Thread.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.ThreadPool.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Threading.Timer.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Transactions.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.ValueTuple.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Web.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Windows.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.Linq.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.ReaderWriter.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.Serialization.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.XDocument.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.XmlDocument.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.XmlSerializer.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.XPath.dll
         -r:C:\Users\dsyme\.nuget\packages\netstandard.library\2.0.0-preview2-25401-01\build\netstandard2.0\\ref\System.Xml.XPath.XDocument.dll
         --target:library
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         FSharpOriginalNBody.fs
         C:\Users\dsyme\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.fs
```

**Comment by enricosada** [comment] 2017-06-16 17:40
> that there is no FSharp.Core.dll in
> would have thought it would exist since FSharp.Core.dll is, I assume, added as a default dependency package of both the F# tester app and the F# library, as mentioned here

the `FSharp.Core` dll is never copied in output dir for build (works like that for all assemblies), that's why we pass `--nocopyfsharpcore` to fsc. List of assemblies is in the `.deps.json` file

the `FSharp.Core` is copied (again, with all deps) on `dotnet publish`

#### about this error

@dsyme i tried locally too, same repo. and i cannot repro the error.

**Comment by dsyme** [comment] 2017-06-16 17:41
@enricosada @cartermp Please review the linked PR

@enricosada I'm surprised the error doesn't repro - it sure did for me.  I reduced the 5000000 to 5000 to make it show quickly.  Note you have to switch the ``DotNetCore2preview2Bug`` branch of the repo

**Comment by dsyme** [comment] 2017-06-16 17:42
@enricosada Since this is high priority, to get correct codegen for .NET SDK 2.0 preview 2, could you possibly try the linked PR? I've got to go out now and haven't been able to try it manually as yet - I need to find the right way to use the freshly built bits

**Comment by enricosada** [comment] 2017-06-16 17:52
@dsyme i'll try tonight. 
btw i was in `master` branch, thx for hint.
but i cannot repro anyway, output is ok.

> Improved C# Mandelbrot faster than original. Expected function results to be the same ([|0uy; 63uy; 1uy; 0uy; 7uy; 191uy; ..

**Comment by enricosada** [comment] 2017-06-16 23:03
I cannot repro. 
i tried multiple cli versions, with and without `dotnet core` feed, in debug and release.

**Comment by enricosada** [comment] 2017-06-16 23:28
Ok, if i cannot repro locally, it should in CI.
Opening https://github.com/dotnet/cli/pull/6914 to add an F# end 2 test test (app with lib).

**Comment by AnthonyLloyd** [comment] 2017-06-17 06:23
@enricosada The branch has only NBody code not Mandelbrot.

**Comment by enricosada** [comment] 2017-06-17 13:49
@AnthonyLloyd thx! i was (another time 😭 ) in the wrong branch 
Now i can repro too

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Double FSharpOriginalNBody.test()'.
   at Program.main@32-1.Invoke(Unit arg00@)
   at Program.isFasterThan@26-1.Invoke(FSharpFunc`2 measurer) in e:\temp\BenchmarksGame\tester\Program.fs:line 26
   at Expecto.Performance.timeCompare[a](FSharpFunc`2 f1, FSharpFunc`2 f2) in e:\temp\BenchmarksGame\tester\Performance.fs:line 133
   at Program.isFasterThanSub[a](FSharpFunc`2 f1, FSharpFunc`2 f2, String format) in e:\temp\BenchmarksGame\tester\Program.fs:line 10
   at Program.isFasterThan[a](FSharpFunc`2 f1, FSharpFunc`2 f2, String message) in e:\temp\BenchmarksGame\tester\Program.fs:line 25
   at Program.main(String[] argv) in e:\temp\BenchmarksGame\tester\Program.fs:line 32
```

**Comment by livarcocc** [comment] 2017-06-20 21:46
@KevinRansom can you take a look at this?

**Comment by cartermp** [comment] 2017-06-20 21:58
Remaining work here is to get the updated compiler into the SDK/CLI, then we can close this.

**Comment by livarcocc** [comment] 2017-06-20 22:03
We got one in yesterday. Do we need another one?

**Comment by cartermp** [comment] 2017-06-20 22:09
I don't think so.  Looks like @ncave was no longer able to see the issue: https://github.com/dotnet/cli/issues/6912#issuecomment-309904692

@AnthonyLloyd, can you verify that the issue is resolved?

**Comment by AnthonyLloyd** [comment] 2017-06-21 08:08
@cartermp Having a problem building now. I just ran the latest installer and tried to build (dotnet restore & rebooted also). Is there another step?

`dotnet build` gives:

```
C:\Users\Ant\src\BenchmarksGame\csharp\csharp.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.0-preview3-25415-01)\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]       
C:\Users\Ant\src\BenchmarksGame\csharp\csharp.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-25301-01 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]           
C:\Users\Ant\src\BenchmarksGame\csharp\csharp.csproj : error NU1102:   - Found 3 version(s) in CliFallbackFolder [ Nearest version: 2.0.0-preview2-25401-01 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]   
C:\Users\Ant\src\BenchmarksGame\csharp\csharp.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]
C:\Users\Ant\src\BenchmarksGame\tester\tester.fsproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25415-01)\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]     
C:\Users\Ant\src\BenchmarksGame\tester\tester.fsproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-002111-00 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]         
C:\Users\Ant\src\BenchmarksGame\tester\tester.fsproj : error NU1102:   - Found 2 version(s) in CliFallbackFolder [ Nearest version: 2.0.0-preview2-25407-01 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]   
C:\Users\Ant\src\BenchmarksGame\tester\tester.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]                           
C:\Users\Ant\src\BenchmarksGame\fsharp\fsharp.fsproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.0-preview3-25415-01)\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]       
C:\Users\Ant\src\BenchmarksGame\fsharp\fsharp.fsproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-25301-01 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]           
C:\Users\Ant\src\BenchmarksGame\fsharp\fsharp.fsproj : error NU1102:   - Found 3 version(s) in CliFallbackFolder [ Nearest version: 2.0.0-preview2-25401-01 ]\r [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]   
C:\Users\Ant\src\BenchmarksGame\fsharp\fsharp.fsproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Users\Ant\src\BenchmarksGame\BenchmarksGame.sln]

```

`dotnet --info` gives

```
.NET Command Line Tools (2.1.0-preview1-006491)                  
                                                                 
Product Information:                                             
 Version:            2.1.0-preview1-006491                       
 Commit SHA-1 hash:  bd7bd69530                                  
                                                                 
Runtime Environment:                                             
 OS Name:     Windows                                            
 OS Version:  10.0.16215                                         
 OS Platform: Windows                                            
 RID:         win10-x64                                          
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006491\ 
                                                                 
Microsoft .NET Core Shared Framework Host                        
                                                                 
  Version  : 2.0.0-preview3-25415-01                             
  Build    : 0fb328316c72fef971a096d14f93b2474290210e            
```

**Comment by enricosada** [comment] 2017-06-21 08:15
use `release/2.0.0` branch, not `master`

**Comment by AnthonyLloyd** [comment] 2017-06-21 08:47
@enricosada Thanks. It works using `release/2.0.0-preview2` but not `release/2.0.0`. Happy for it to be closed if this in order. Many Thanks.

**Comment by cartermp** [comment] 2017-06-21 14:59
@livarcocc Is `release/2.0.0-preview2` the correct branch?  Seems correct to me, but this isn't a repo I work in.

**Comment by enricosada** [comment] 2017-06-21 22:02
PR with test https://github.com/dotnet/cli/pull/6975 for branch `release/2.0.0-preview2`

**Comment by cartermp** [comment] 2017-06-21 22:06
Thanks for the smoke test @enricosada.  Closing!

**Closed by cartermp** 2017-06-21 22:06 UTC
