### ISSUE TITLE
Can publish a framework-dependent application with application host but without RID

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/cli#10552] opened 2019-01-07 08:19 UTC
## Steps to reproduce
1.	Run `dotnet new console`.
2.	Run `dotnet publish -p:UseAppHost=true`.

## Expected  behavior
An error should be printed from the SDK informing you that a `RuntimeIdentifier` must be specified.

## Actual behavior
It runs successfully.

![cli](https://user-images.githubusercontent.com/46206739/50755362-bbb1e080-1293-11e9-8975-1f5bc2605c86.PNG)

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010006
 Commit:    166534d9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010006\

Host (useful for support):
  Version: 3.0.0-preview-27218-01
  Commit:  d40b87f29d

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010006 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18630-0234 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27218-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27220-11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2019-01-07 18:04
This is by design.

In 3.0, we changed the behavior of the CLI to always deploy an application host for framework dependent apps. When a rid is not specified, we will use the RID that the CLI itself targets for that.

cc @peterhuene to confirm and close.

**Comment by peterhuene** [comment] 2019-01-07 18:24
Hi @JiahongJin1.  Thanks for reporting this to us!

@livarcocc is correct.  The limitation that a RID must be specified to get the application host was removed in 3.0 because we now fallback to the RID of the SDK itself (i.e. the current platform RID).

This was to support building applications by default and getting an executable that can be used to run the application, which is especially important to GUI applications so that users can customize the executable icon and have a way to launch their application without resorting to a console.

Right now, publishing without a RID also includes the default application host in the publishing output.  Before 3.0 ships we may decide that it doesn't make sense to include the default platform apphost in the publishing output, but regardless of that decision, the expected error from this issue no longer exists in the SDK.  As such, I am closing this issue.  If you have any questions, please feel free to comment or reactivate the issue.  Thank you.

**Closed by peterhuene** 2019-01-07 18:24 UTC

**Comment by richaverma1** [comment] 2019-01-07 19:04
@peterhuene is this a test scenario that needs to be updated for the changed behavior?

**Comment by peterhuene** [comment] 2019-01-07 19:12
@richaverma1 It appears the 2.x test plan is out of date with respect to this feature.  I'll update now.

**Comment by richaverma1** [comment] 2019-01-07 19:14
Thank you @peterhuene :)
