### ISSUE TITLE
dotnet-test on solution

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5631] opened 2017-02-08 21:09 UTC
Being able to run "dotnet test" on a solution file would be awesome. It would make it really easy to test an entire project at once. At the moment, this is not possible. This means our build requires additional scripting to find test projects and execute dotnet-test on them.

**Suggestions**
Condition the VSTest target to skip projects that do not include Microsoft.NET.Sdk.Test.
Allow dotnet-test to also match \*.sln files

_For comparison_
dotnet-pack can be called on a solution. NuGet pack targets will skip producing nupkgs for projects where `<IsPackable>false</IsPackable>` is set.

**Comment by livarcocc** [comment] 2017-02-09 01:18
This is a duplicate of https://github.com/Microsoft/vstest/issues/411.

**Closed by livarcocc** 2017-02-09 01:18 UTC
