### ISSUE TITLE
dotnet build Command no longer calls Mono on Linux

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/cli#5988] opened 2017-03-10 00:53 UTC
## Steps to reproduce

Create a project on Linux targeting both `netcoreapp1.1.1` and `net451` (or some other version of the full .NET framework).  Install the `mono-complete` package

## Expected  behavior

In preview tooling, `dotnet build` would call into mono to build the `net451` package

## Actual behavior

Using `dotnet-dev-1.0.1`, building the `net451` build now fails with:

```
Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for 
framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or 
Targeting Pack for this framework version or retarget your application to a version of the framework for 
which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the 
Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your 
assembly may not be correctly targeted for the framework you intend.
```

Why does `dotnet build` no longer call into mono when targeting the full .NET framework on Linux?

## Environment data
```
dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by RehanSaeed** [comment] 2017-03-13 14:02
Duplicate of https://github.com/dotnet/cli/issues/5977

**Comment by dsplaisted** [comment] 2017-03-15 00:39
Closing this issue in favor of #5977

**Closed by dsplaisted** 2017-03-15 00:39 UTC
