### ISSUE TITLE
When attempting to display additional help for run command with `--help` flag, cli instead uses `--help` as name of build folder

### ISSUE THREAD

**Issue by mattmazzola** [dotnet/cli#3711] opened 2016-06-28 04:53 UTC
## Steps to reproduce
Create new app:
```
mkdir dotnetcore01
cd dotnetcore01
dotnet new
dotnet restore
```
Attempting to run with configuration:
```
dotnet run -c
```
Cli outputs:
```
Specify --help for a list of available options and commands.
Missing value for option 'configuration'
```
This suggests I can append `--help` onto the previous command to get help about what options are allowed for the `-c` flag; however, when you run:
```
dotnet run -c --help
```
It just uses `--help` as the name of containing folder for the app instead of displaying the help information and builds the app which is misleading.

## Expected  behavior
Whenever `-h` or `--help` is provided it should display help information for the current command not execute.
if it is decided `--help` is not compatible with the `-c` flag, then the error message for the `dotnet run -c` command should be more clear about what to type to get the proper help information.

## Actual behavior
`dotnet run -c --help` will use `--help` as the name of folder in the `bin` directory which contains build artifacts.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14366
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment] 2016-07-27 17:20
@mattmazzola this behavior is by design. The actual invocation you are describing is not something that we are looking for enabling at this time. 

The `--help` switch for a command (e.g. `dotnet run --help`) will give you all of the options that you need for running `dotnet run` and likewise for any other command. Closing this as "by design".

**Closed by blackdwarf** 2016-07-27 17:20 UTC
