### ISSUE TITLE
Build behavior change between 2.1.403 and 3.0.100-preview-010000

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/cli#10864] opened 2019-02-22 07:20 UTC
On version: 2.1.403

This project builds correctly:  https://github.com/Microsoft/visualfsharp/blob/master/src/buildtools/buildtools.proj

c:\kevinransom\visualfsharp\fcs>dotnet build ..\src\buildtools\buildtools.proj
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 19.05 ms for c:\kevinransom\visualfsharp\src\buildtools\fslex\fslex.fsproj.
  Restore completed in 1.76 ms for c:\kevinransom\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj.
  fslex -> c:\kevinransom\visualfsharp\artifacts\bin\fslex\Debug\netcoreapp2.0\fslex.dll
  fsyacc -> c:\kevinransom\visualfsharp\artifacts\bin\fsyacc\Debug\netcoreapp2.0\fsyacc.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.64

With version 3.0.100-preview-010000 installed the behavior has changed:

c:\kevinransom\visualfsharp\fcs>dotnet build ..\src\buildtools\buildtools.proj
Microsoft (R) Build Engine version 16.0.284-preview+g7905402dc6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for c:\kevinransom\visualfsharp\src\buildtools\fslex\fslex.fsproj...
  Generating MSBuild file c:\kevinransom\visualfsharp\artifacts\obj\fslex\fslex.fsproj.nuget.g.props.
  Restore completed in 125.12 ms for c:\kevinransom\visualfsharp\src\buildtools\fslex\fslex.fsproj.
  Restoring packages for c:\kevinransom\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj...
  Generating MSBuild file c:\kevinransom\visualfsharp\artifacts\obj\fsyacc\fsyacc.fsproj.nuget.g.props.
  Restore completed in 59.86 ms for c:\kevinransom\visualfsharp\src\buildtools\fsyacc\fsyacc.fsproj.
c:\kevinransom\visualfsharp\src\src\buildtools\buildtools.proj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'c:\kevinransom\visualfsharp\src\src\buildtools\buildtools.proj'.

Build FAILED.

c:\kevinransom\visualfsharp\src\src\buildtools\buildtools.proj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'c:\kevinransom\visualfsharp\src\src\buildtools\buildtools.proj'.
   0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.80

I assume this is a bug.

Kevin

**Comment by peterhuene** [comment] 2019-02-22 23:38
@rainersigwald is this the relative path regression in MSBuild?

**Comment by peterhuene** [comment] 2019-02-22 23:46
That is to say this issue: https://github.com/Microsoft/msbuild/pull/4039

**Comment by peterhuene** [comment] 2019-02-22 23:52
Looks like we took an insertion from MSBuild 8 days ago into release/3.0.1xx, so the fix may be in the preview 3 builds; there's an outstanding merge to master, so I'm not sure if the latest in master will contain the fix.

Judging from the repro and result, I think this is a dupe of dotnet/cli#10554.  I'm going to close it as such.  Please reopen if you disagree.  Thanks!

**Closed by peterhuene** 2019-02-22 23:52 UTC
