### ISSUE TITLE
Allow removal of Debug or Release build configurations

### ISSUE THREAD

**Issue by jez9999** [dotnet/cli#9610] opened 2018-07-04 10:07 UTC
On my current solution, I have a bunch of projects for which I have carefully setup several custom build configurations.  I have actually removed Release because I have several of my own custom configurations that replace it - I could imagine someone might want to do the same for Debug, too.

But when I added a .NET Core commandline project, I discovered that Debug and Release *always* appear in the Configuration dropdown for the project build options.  It seems that they are hard-coded into the .NET Core CLI!  No amount of editing the project file would get rid of them and let me replace them with my own custom build configs.

So I think you should add the option to remove Debug and Release, and replace them with other custom build configurations.

**Comment by peterhuene** [comment] 2018-07-06 17:28
Hi @jez9999.

Thank you for your feedback.  It sounds like you are referring to Visual Studio's configuration manager, which is not owned by the .NET Core CLI.

The .NET Core CLI does not control what solution or project configurations are shown in Visual Studio.   However, I'm unable to reproduce the behavior you're seeing as I can use Visual Studio's configuration manager to edit the project file's `Configurations` property (this may be set at the project level to override the configurations inherited from the default MSBuild targets) and remove both `Debug` and `Release`.

Because you did not fill out the suggested new issue template when filing this issue, I don't know what version of Visual Studio and .NET Core SDK you are using, nor do I have any repro steps to follow.

As such, I'm going to close this issue as "no repro".  If you are still able to reproduce, please follow the new issue template by providing the following information: steps to reproduce, expected behavior, actual behavior, and `dotnet --info` (and versions of Visual Studio). 

Thank you.

**Closed by peterhuene** 2018-07-06 17:28 UTC
