### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.

### ISSUE THREAD

**Issue by Ryther** [dotnet/cli#6277] opened 2017-04-08 20:00 UTC
New Ubuntu 16.10 installation, I've installed Net Core 1.1.1 and yeoman without errors. I've verified everything and cannot proceed further.

## Steps to reproduce
1. Install .NET Core 1.1.1
2. Install NPM
3. Install yo
4. Install generator-aspnet
5. Git clone 1.1.1 project / Create new yo aspnet project (empty/web)
6. dotnet restore -> build -> ef database update/run
7. Error

## Expected  behavior
1. Cloned git project works as in a Windows
2. New yo aspnet project works

## Actual behavior
`The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.1
  - Alternatively, install the framework version '1.0.4'.`

### `dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

### `npm doctor` output:
Check                               Value                        Recommendation
npm ping                            ok
npm -v                              v4.4.4
node -v                             v7.8.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Checksum cached files               ok

### `yo --version` output:
1.8.5

### `node --version` output:
v7.8.0

### `npm list -g generator-aspnet` output:
└── generator-aspnet@0.3.3

**Comment by livarcocc** [comment] 2017-04-09 03:15
I am not sure we have the yo generators updated or even how recent they are. @mlorbetske to answer that.

Can you use dotnet new mvc instead to create your project and try then.

You can actually run dotnet new -l to list all the templates you have available. If you want to work with React or angular, you can follow the steps here (https://www.hanselman.com/blog/dotnetNewAngularAndDotnetNewReact.aspx) to install the templates and create the projects.

**Comment by mlorbetske** [comment] 2017-04-09 08:52
I believe @peterblazejewicz & @sayedihashimi would have the most up to date information on the yo generators.

**Comment by peterblazejewicz** [comment] 2017-04-09 09:06
@Ryther 
The generators (at least `yo aspnet`) has been updated to Feb 1.0.4 release, but could be not aligned to latest bits of runtime itself (and yes, there could be bug). As suggested run `dotnet new mvc` scaffold tool and check if it works. The landing page for `dotnet/templating` tool has `mvc` template usage explained in details:
https://github.com/dotnet/templating

It could be issue with `dotnet/templating` or `omnisharp/generator-aspnet`, not `dotnet/cli`, so this thread should be moved to respective project when more details emerge.

**Comment by Ryther** [comment] 2017-04-09 10:40
I've just tried, `dotnet new mvc` works as intended.
On the last days of march I've used the same setup with `yo aspnet` on a windows machine and had no problems.
Will check at home with my Windows setup and report back. For the moment on my linux machine i will move to .NET Core 1.0.4

**Comment by livarcocc** [comment] 2017-04-10 03:57
The problem is that there is no 1.0.4 runtime for Ubuntu 16.10. That version of Ubuntu is only supported in 1.1.1.

Anyways, closing this, because if there is an issue it is with the yo generators and the issue should be filed in a separate repo.

**Closed by livarcocc** 2017-04-10 03:57 UTC
