### ISSUE TITLE
Setup Failed

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3410] opened 2016-06-06 21:43 UTC
I am trying to install: 1.0.0-preview2-002973 from https://github.com/dotnet/cli

![image](https://cloud.githubusercontent.com/assets/1438884/15838660/2527e016-2bf4-11e6-860e-dd6e66184ca9.png)

I think the issue is caused by VC redist. I did install a VS Update3 RC last week. Log file:

[Microsoft_.NET_Core_1.0.0_RC2_-_SDK_Preview_1_(x64)_20160606143541.log.txt](https://github.com/dotnet/cli/files/301391/Microsoft_.NET_Core_1.0.0_RC2_-_SDK_Preview_1_.x64._20160606143541.log.txt)

**Comment by piotrpMSFT** [comment] 2016-06-06 21:48
Dupe of https://github.com/dotnet/cli/issues/3371

**Closed by piotrpMSFT** 2016-06-06 21:48 UTC
