### ISSUE TITLE
dotnet cli 1.0.0-preview4-004233 fails to build a simple hello world program

### ISSUE THREAD

**Issue by 0xced** [dotnet/cli#5444] opened 2017-01-24 23:28 UTC
## Steps to reproduce

```
$ mkdir dotnet_helloworld
$ cd dotnet_helloworld/
$ dotnet new
Created new C# project in /Users/0xced/dotnet_helloworld.
$ ls -a
.                        ..                       Program.cs               dotnet_helloworld.csproj
$ cat Program.cs 
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}
$ cat dotnet_helloworld.csproj 
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
  </ItemGroup>

</Project>
```

## Expected  behavior

Running `dotnet build` succeeds.

## Actual behavior

Running `dotnet build` fails with the following error messages:
```
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(7,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,71): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,99): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,122): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(6,55): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(7,61): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(8,59): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(9,59): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(10,68): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(11,55): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(12,53): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(13,55): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(14,63): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
Program.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(2,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/var/folders/1l/rbhqr1jx4fdbgxmf58vwdw700000gq/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
obj/Debug/netcoreapp1.0/dotnet_helloworld.AssemblyInfo.cs(4,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
Program.cs(3,7): error CS0518: Predefined type 'System.Object' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
Program.cs(5,22): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
Program.cs(5,12): error CS0518: Predefined type 'System.Void' is not defined or imported [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
/usr/local/share/dotnet/sdk/1.0.0-preview4-004233/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(82,5): error : Assets file '/Users/0xced/dotnet_helloworld/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/Users/0xced/dotnet_helloworld/dotnet_helloworld.csproj]
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004233
```

**Comment by piotrpMSFT** [comment] 2017-01-25 02:42
@0xced please run `dotnet restore` before running `dotnet build`. #4730 tracks making this automatic.

**Comment by dasMulli** [comment] 2017-01-25 09:32
Just a simple idea: What about running restore after new/new3 automatically? Restoring before each build may be time-consuming, but running it after new should be what the user is supposed to do anyway..

**Comment by blackdwarf** [comment] 2017-01-26 02:18
@mlorbetske for the `new` suggestion.

**Comment by jpierson** [comment] 2017-02-01 04:14
I'm seeing a similar type of error specifically when using Windows Subsystem for Linux. Using Powershell for the same project seems to work fine.

# Steps to reproduce

Install Windows Subsystem for Linux on Windows 10.

Add the dotnet apt-get feed

```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
```

Install .NET Core SDK

```
sudo apt-get install dotnet-dev-1.0.0-preview4-004233
```

Install git

```
sudo apt-get install git
```

Clone _x-functional-helpers_ repo

```
git clone https://github.com/jpierson/x-functional-helpers
```

Attempt to build using `dotnet build`

```
cd x-functional-helpers/src
dotnet restore
dotnet build
```

# Expected behavior

Running `dotnet build` succeeds.

Actual behavior

Running `dotnet build` fails with the following error messages:

```
jeff@MYMACHINE:/mnt/c/Users/jeff/source/x-deleteme-test/src$ dotnet build
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(7,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(6,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(7,61): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(8,59): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(9,59): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(10,68): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(11,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(12,53): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(13,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(14,63): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(4,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(7,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(6,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(7,61): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(8,59): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(9,59): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(10,68): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(11,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(12,53): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(13,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(14,63): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
obj/Debug/netstandard1.4/FunctionalHelpers.AssemblyInfo.cs(4,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj]
/usr/share/dotnet/sdk/1.0.0-preview4-004233/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(82,5): error : Cannot find project info for '/mnt/c/Users/jeff/source/x-deleteme-test/src/FunctionalHelpers/FunctionalHelpers.csproj'. This can indicate a missing project reference. [/mnt/c/Users/jeff/source/x-deleteme-test/src/Tests/Tests.csproj]
```

# Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-preview4-004233
```

**Comment by blackdwarf** [comment] 2017-02-01 04:45
@jpierson the Windows subsystem for Linux is not an environment where we test and support the CLI at this point.

**Comment by dasMulli** [comment] 2017-02-01 05:51
@jpierson @blackdwarf out of interest, it tried it on WS with the current rc3-004530. It seems that somehow, the arguments to `RunCsc.sh` are not escaped:
```
/usr/share/dotnet/sdk/1.0.0-rc3-004530/Roslyn/RunCsc.sh … /define:TRACE;NETSTANDARD1_4;DEBUG … 
```
Which probably makes it break on the semicolon when executing. If I copy the command from the diagnostic log, add quotes and run it, runcsc succeeds.
Note that I get similar diagnostic logs on osx where it works. maybe this is a wsl difference or shell config?

**Comment by blackdwarf** [comment] 2017-02-01 06:04
@dasMulli you use bash on osx?

**Comment by dasMulli** [comment] 2017-02-01 06:11
default osx 10.12.2 bash:
```
MacBook-Pro:tmp martin$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

the ""windows"" one is:
```
martin@DW10MARTINHOME:/mnt/c/Windows$ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

I tried to match up the `shopt` options to see if there is a difference and also tried to activate compat flags on the windows one.
Maybe there is a difference in how the shell is invoked by msbuild.. Or it is a different problem after all.

**Comment by livarcocc** [comment] 2017-03-22 19:19
If this is a problem on how RunCsc is invoke, then this belongs in either msbuild or roslyn. @dasMulli  is that what you suspect the issue is here?

**Comment by dasMulli** [comment] 2017-03-23 08:22
@livarcocc i am no longer able to repro this on windows subsystem for linux with the latest windows + ubuntu updates and CLI 1.0.1.
If it occurs again, i suggest setting the `Define` and `NoWarn` properties to a value not containing `;`.
Since this has not been observed on any other platform, i suspect the issue is more related to how a command is executed on the linux subsystem.

**Comment by livarcocc** [comment] 2017-03-23 16:36
Thanks @dasMulli. Closing this for now then.

**Closed by livarcocc** 2017-03-23 16:36 UTC
