### ISSUE TITLE
Latest dotnet restore fails to resolve Microsoft.NETCore.App (>= 1.0.0-rc2-3002349)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2419] opened 2016-04-12 15:45 UTC
## Steps to reproduce
Mac OSX
dotnet new
dotnet restore

I uninstalled all the previous packages and I am starting from scratch:

xyz:hello-2016-04-12 xyz$ pkgutil --pkgs | grep dotnet
com.microsoft.dotnet.dev.1.0.0-rc2-002349.component.osx.x64
com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.1.0.0-rc2-3002349.component.osx.x64
com.microsoft.dotnet.sharedhost.1.0.0.component.osx.x64

xyz:hello-2016-04-12 xyz$ ls /usr/local/share/dotnet/shared/Microsoft.NETCore.App/
1.0.0-rc2-3002349

## Expected  behavior
Restore succeeds

## Actual behavior
Errors in /Users/xyz/Documents/Projects/hello-2016-04-12/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002349)' for '.NETCoreApp,Version=v1.0'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by jeffschwMSFT** [comment] 2016-04-12 15:51
Ok, it seems with the right nuget.config settings I am able to get restore working...

<add key="dotnet-cli" value="https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

**Comment by GuardRex** [comment] 2016-04-12 15:54
@jeffschwMSFT Same here. @moozzyk corrected my feeds to  ...
```xml
<add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
```
... to get me running as shown in the `Nuget.config` of the current `cli-samples`, which are very easy to overlook in the location that they appear in that repo.

**Comment by jeffschwMSFT** [comment] 2016-04-12 15:57
Building is then failing with the following...

/Users/xyz/Documents/Projects/matrix/d.app_f.app_shared/project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.Common 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.
/Users/xyz/Documents/Projects/matrix/d.app_f.app_shared/project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.CSharp 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.
/Users/xyz/Documents/Projects/matrix/d.app_f.app_shared/project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.VisualBasic 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.

**Comment by GuardRex** [comment] 2016-04-12 16:03
@jeffschwMSFT I'll see if I can confirm the same behavior on Windows.

**Comment by GuardRex** [comment] 2016-04-12 16:09
@@jeffschwMSFT They don't have the `dotnet new` project providing the `imports` statement on the TFM. Try it like this ...
```json
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net451+win8" ]
    }
}
```
... it won't run for me (yet) just because I don't have the shared framework installed locally (yet), but that's something I'll be getting to shortly. I've been very focused on the standalone model thus far, and this is a shared framework app that `dotnet new` creates.

**Comment by jeffschwMSFT** [comment] 2016-04-12 16:13
That did it... I suspect this is a point in time right before we ship RC2?

**Comment by GuardRex** [comment] 2016-04-12 16:17
@jeffschwMSFT Correct ... just waiting for packages to catch up so that the `imports` statement can be dropped. AFAICT this will be resolved by the time RC2 hits (guessing).

The only way to know if it can be dropped in a given project is to do a "poor man's test," by just removing the `imports` line and seeing if it will compile/run. I have some projects where I've been able to drop the line and others where it still chokes on a handful of packages.

**Comment by Petermarcu** [comment] 2016-04-12 16:22
@weshaggard , Can we put the netcoreapp metapackage on the dotnet-core myget feed?

**Comment by Petermarcu** [comment] 2016-04-12 16:24
@jeffschwMSFT , Are these the latest CodeAnalysis packages? We should see what it will take to get them to not require imports.

**Comment by GuardRex** [comment] 2016-04-12 16:26
@Petermarcu I noticed that `dotnet new` doesn't produce a `NuGet.config` file. idk if that was by-design. Seems wrong given the prevailing samples and issues where feeds are discussed.

**Comment by Petermarcu** [comment] 2016-04-12 16:28
We removed it because we will be pushing everything to NuGet and don't want people to have our dev feeds in their feed list. As soon as RC2 packages are on NuGet, all the feedback will go away, until then, folks need to add the dev feed to their NuGet.config to opt into the dev feed.

**Comment by weshaggard** [comment] 2016-04-12 16:30
Microsoft.NETCore.App meta-package is on the dotnet-core myget feed, in fact the exact version is there. The way publishing works however there is a little bit of a delay so it is possible that it wasn't there immediately if you picked up the cli build hot off the press. 

That said the dotnet-core feed doesn't have the latest Roslyn packages which would account for the Microsoft.CodeAnalysisissue that Jeff is seeing. I will add the latest version of those to the dotnet-core feed.

**Comment by Petermarcu** [comment] 2016-04-12 16:33
I'm going to close this issue for now, I believe so far everything is by design and there are a few follow ups.

**Closed by Petermarcu** 2016-04-12 16:33 UTC
