### ISSUE TITLE
dotnet list package fails on unreachable conditions

### ISSUE THREAD

**Issue by batzen** [dotnet/cli#12267] opened 2019-08-15 19:08 UTC
## Steps to reproduce
- dotnet new console
- add
```
  <ItemGroup Condition="'true' == 'false'">
    <PackageReference Condition="'asdf' >= '10'" Include="Newtonsoft.Json" />
  </ItemGroup>
```
to the project
- dotnet restore
- dotnet list package --outdated

## Expected  behavior
As `dotnet restore` and `dotnet build` work without any error i expect it to just output:
`The given project `xx` has no updates given the current sources.`

## Actual behavior
`error: A numeric comparison was attempted on "asdf" that evaluates to "asdf" instead of a number, in condition "'asdf' >= '10'". `

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  1.0.0 [c:\program files\dotnet\sdk]
  1.0.2 [c:\program files\dotnet\sdk]
  1.0.3 [c:\program files\dotnet\sdk]
  1.0.4 [c:\program files\dotnet\sdk]
  1.1.0 [c:\program files\dotnet\sdk]
  3.0.100-preview8-013656 [c:\program files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by peterhuene** [comment] 2019-08-15 19:26
@rainersigwald is this an artifact of how MSBuild works?

**Comment by rainersigwald** [comment] 2019-08-15 19:57
Yes. When you load a project "as if for edit", as NuGet does here, MSBuild goes through codepaths that ignore conditions. That enables, for instance, finding `PackageReference` elements that are conditioned to only certain `TargetFramework`s, or things that are conditioned on `Debug` and so on.

This is a surprising and confusing behavior in this circumstance, but I don't think that warrants trying to change anything, since I can't see a nice way to differentiate this situation (always unreachable) from the general one (condition currently evaluates to `false`).

cc @zivkan

**Comment by peterhuene** [comment] 2019-08-15 20:15
Thanks for the clarification.

@batzen given that this is by design, I am going to close this issue.  Please feel free to ask additional questions of myself or @rainersigwald.  Thanks!

**Closed by peterhuene** 2019-08-15 20:15 UTC

**Comment by zivkan** [comment] 2019-08-15 20:19
Relevant docs: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition

> You can use a condition to control whether a package is included, where conditions can use any MSBuild variable or a variable defined in the targets or props file. However, at presently, **only the TargetFramework variable is supported**.

emphasis mine.

From https://github.com/NuGet/Home/issues/5895, it may be possible to specify the property doing an msbuild restore `msbuild /t:restore /p:PropertyName=Value`. I'm not sure if `dotnet restore -p:PropertyName=Value` would work. Sometimes unknown arguments are passed to msbuild, but I'm not sure if `dotnet restore` is effectively an alias for `dotnet msbuild -t:restore` or if it calls something else.

Depending on the scenario, a work around is to use MSBuild's choose-when-otherwise syntax. This is one way to get different packages in Debug Configuration in VS, although I didn't test if it works when restoring or building from the command line.

**Comment by batzen** [comment] 2019-08-15 20:35
The code was just an example. The real issue is that code like that is part of the wpf sdk and not a part of user code. Essentially this behavior leads to being unable to call the command on a wpf project.
Do you suggest i create an issue at the wpf project? They would have to duplicate all checks done in an outer scope to several inner scope conditions then.

To be honest I don't think the current behavior (throwing an error for totally valid code) is correct and no other cli command seems to it that way.

**Comment by zivkan** [comment] 2019-08-15 20:52
If there's a problem with the way that NuGet and the WPF SDK work together, then our teams need to talk ASAP. However

```
dotnet new wpf
dotnet add package Dapper
dotnet restore
```
works fine for me, so I don't understand the scenario. As the NuGet docs say we only support the TargetFramework property in conditions at the moment, so to me it's working as designed.

**Comment by batzen** [comment] 2019-08-15 21:38
It only happens in wpf projects when using TargetFrameworks instead of TargetFramework. That's because TargetFrameworkWithoutV seems to resolve to an empty string at some stage. Can post a repro tomorrow.

**Comment by batzen** [comment] 2019-08-16 16:21
@peterhuene @zivkan 
Simple repro for wpf:
- dotnet new wpf
- Replace `TargetFramework` with `<TargetFrameworks>netcoreapp3.0;net45</TargetFrameworks>`
- dotnet restore
- dotnet list package
-> Results in an error being displayed
That's by design?

**Comment by zivkan** [comment] 2019-08-16 16:34
I should have said not a supported scenario, rather than by design.  I also missed that this was about `dotnet list package`, I thought it was a `dotnet restore ` error which would have been really scary.

I'll create an issue on NuGet, since we own `dotnet list package`, but it won't get done for .NET Core 3.0.

**Comment by batzen** [comment] 2019-08-16 16:39
So dotnet list package will be broken for multi targeted projects?
That's sad. Hope it gets fixed for core 3.1 ;-)

**Comment by rainersigwald** [comment] 2019-08-16 16:51
That's a very nice repo @batzen, thanks. Filed microsoft/msbuild#4622 (it _might_ be possible for MSBuild to be more forgiving at some point in the future) and https://github.com/dotnet/wpf/issues/1651 (a small change in the WPF SDK should be able to resolve this specific problem).

**Comment by zivkan** [comment] 2019-08-16 17:01
dotnet list package will work fine for multi targeting projects whose msbuild evaluations don't use conditions other than TargetFramework. Basically, any project type other than wpf or winforms.
