### ISSUE TITLE
Restore is too verbose

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3318] opened 2016-06-01 16:45 UTC
## Steps to reproduce
dotnet new
dotnet restore

## Expected  behavior
minimal output with only errors/warnings by default
optionally dial up the verbosity

## Actual behavior
lines upon lines of spew with errors and warnings hidden among the mess.  folks ignore warnings when often those point to issues.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-002882)

Product Information:
 Version:            1.0.0-preview2-002882
 Commit SHA-1 hash:  f46be283f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by mellinoe** [comment] 2016-06-01 17:19
Related: https://github.com/dotnet/cli/issues/2212, https://github.com/dotnet/cli/issues/1623

**Comment by ericstj** [comment] 2016-06-01 17:44
Feel free to dupe to #1623.  I looked but didn't see that.

**Comment by piotrpMSFT** [comment] 2016-06-07 01:30
@billwert already merged #3229 which was supposed to have dealt with this issue. Is there a regression?

**Comment by billwert** [comment] 2016-06-07 19:27
I didn't do anything about the copious downgrade warnings a person could see - suppressing warnings by default seemed very bad.

**Comment by blackdwarf** [comment] 2016-07-24 18:57
Closing this as a dupe of #1623.

**Closed by blackdwarf** 2016-07-24 18:57 UTC
