### ISSUE TITLE
Paths passed to scripts should be absolute 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3528] opened 2016-06-12 19:12 UTC
## Steps to reproduce

When invoking a tool in a script (e.g. publish-iis) the paths passed to the script should be absolute even if the path provided by the user was relative. This is because when running a tool as a script the current directory is apparently changed and as a result the tool resolves a different path than the global command if the global command is not run from the project folder (e.g. publish publishes application to one location but publish-iis wants to write web.config to a different location)

Reported on stackoverflow:
http://stackoverflow.com/questions/37773621/dotnet-publish-iis-looking-for-web-config-in-wrong-place?noredirect=1#comment63023314_37773621

**Comment by brthor** [comment] 2016-06-13 20:09
Do you mean the script variables should resolve to absolute paths.

ex `%publish:OutputPath%`

This seems like a good change.

**Comment by moozzyk** [comment] 2016-06-13 20:12
Yes - if a parameter is a path it should be resolved so that the script only gets an absolute path.

**Comment by blackdwarf** [comment] 2016-10-31 21:34
This issue is mitigated by MSBuild insofar as the tools that require access to output and/or project files should be rewritten as targets/tasks, rather than a tool 

However, strictly speaking, all output path properties that are available in MSBuild are relative, so in that sense the issue is not mitigated (passing in `$(OutputPath)` to an `<Exec>` target will pass in a relative path).

**Comment by blackdwarf** [comment] 2016-11-01 13:57
@livarcocc @piotrpMSFT thoughts on this?

**Comment by blackdwarf** [comment] 2016-11-02 18:01
Since this will require some more thinking, moving it to Preview 4.

**Comment by bytemaster-0xff** [comment] 2016-11-20 12:54
seems like same sort of situation is happening as part of the .NET Core build steps on VS Online where the end result is that the site can not be started since web.config is invalid

```
2016-11-19T00:13:35.2835544Z ##[section]Starting: dotnet publish
2016-11-19T00:13:35.2845543Z ==============================================================================
2016-11-19T00:13:35.2855548Z Task         : .NET Core (PREVIEW)
2016-11-19T00:13:35.2855548Z Description  : Build, test and publish using dotnet core command-line.
2016-11-19T00:13:35.2855548Z Version      : 0.1.0
2016-11-19T00:13:35.2855548Z Author       : Microsoft Corporation
2016-11-19T00:13:35.2855548Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2016-11-19T00:13:35.2855548Z ==============================================================================
2016-11-19T00:13:35.9475551Z [command]C:\Program Files\dotnet\dotnet.exe publish C:/a/1/s/Web/LagoVista.IoT.Web.Portal/project.json -c release --output Published\LagoVista.IoT.Web.Portal
2016-11-19T00:13:45.1044530Z Publishing LagoVista.IoT.Web.Portal for .NETFramework,Version=v4.6.1/win7-x64
2016-11-19T00:13:45.1044530Z Bundling with configuration from C:\a\1\s\Web\LagoVista.IoT.Web.Portal\bundleconfig.json
2016-11-19T00:13:45.1044530Z Processing wwwroot/css/site.min.css
2016-11-19T00:13:45.1044530Z   Bundled
2016-11-19T00:13:45.1044530Z   Minified
2016-11-19T00:13:45.1044530Z Processing wwwroot/js/site.min.js
2016-11-19T00:13:45.1054542Z Project LagoVista.Common (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.Common.UserManagement (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.Common.CloudStorage (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.Common.Web.Identity (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.Common.Net (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.Common.Security (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.IoT.DeviceLibrary (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.IoT.DeviceManagement.Repo (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.IoT.DeviceManagement.BusinessLogic (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Project LagoVista.IoT.Web.Portal (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
2016-11-19T00:13:45.1054542Z Configuring the following project for use with IIS: 'Published\LagoVista.IoT.Web.Portal'
2016-11-19T00:13:45.1054542Z No web.config found. Creating 'Published\LagoVista.IoT.Web.Portal\web.config'
2016-11-19T00:13:45.1064538Z System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\a\1\s\Web\LagoVista.IoT.Web.Portal\Published\LagoVista.IoT.Web.Portal\web.config'.
2016-11-19T00:13:45.1064538Z    at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-11-19T00:13:45.1064538Z    at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-11-19T00:13:45.1064538Z    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2016-11-19T00:13:45.1064538Z    at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
2016-11-19T00:13:45.1064538Z    at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
2016-11-19T00:13:45.1064538Z    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
2016-11-19T00:13:45.1064538Z    at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
2016-11-19T00:13:45.1064538Z publish: Published to Published\LagoVista.IoT.Web.Portal
2016-11-19T00:13:45.1064538Z Published 1/1 projects successfully
2016-11-19T00:13:45.1074546Z Could not find a part of the path 'C:\a\1\s\Web\LagoVista.IoT.Web.Portal\Published\LagoVista.IoT.Web.Portal\web.config'.
2016-11-19T00:13:49.8984140Z ##[section]Finishing: dotnet publish
```

**Comment by piotrpMSFT** [comment] 2016-12-05 19:47
PublishOutputPath becomes OutputDir in preview3+. OutputDir, like other directory paths in msbuild, are specified relative to the csproj file path. You can see the full mapping from Project.json to csproj here:

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigrateScriptsRule.cs#L143

**Closed by piotrpMSFT** 2016-12-05 19:47 UTC
Labels: bug, msbuild-mitigated
