### ISSUE TITLE
dotnet restore ignores the packages property from global.json

### ISSUE THREAD

**Issue by lucassp** [dotnet/cli#3816] opened 2016-07-08 13:55 UTC
## Steps to reproduce

1 Create a solution which has the following structure:

```
 -- MySolution
    -- global.json
    -- src
        -- project.json
            <project files>
    -- test
        -- project.json
           <project files>
```

2 Add the following to `global.json`:

```
{
    "projects": ["src", "test"],
    "sdk": {
        "version": "1.0.0-preview2-003121"
    },
    "packages": "packages"
}
```

3 Inside the solution root run `dotnet restore`.
## Expected  behavior

After `dotnet restore` finishes, a `packages` folder should be created inside the solution root containing the dependencies.
## Actual behavior

After `dotnet restore` finishes, the `packages` folder doesn't exist and the dependencies are installed globally.
## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:                           
 Version:            1.0.0-preview2-003121     
 Commit SHA-1 hash:  1e9d529bc5                

Runtime Environment:                           
 OS Name:     Windows                          
 OS Version:  10.0.10240                       
 OS Platform: Windows                          
 RID:         win10-x64                        
```

**Comment by pasisavolainen** [comment] 2016-10-07 15:07
This is even worse. The `packages` property in `global.json` stops dependencies from restoring at all.
Here is a minirepro: https://github.com/pasisavolainen/dotnet-restore-issue
If you rename `packages` to something else, the solution is buildable. With the property, it is not (need to reopen solution).

Also `dotnet restore` just doesn't work **at all**. You have to use `dotnet restore --packages packages` for it to do anything. Solution doesn't compile.

**Comment by piotrpMSFT** [comment] 2016-11-12 11:39
dupe of https://github.com/NuGet/Home/issues/3915

**Closed by piotrpMSFT** 2016-11-12 11:39 UTC
Labels: msbuild-notapplicable
