### ISSUE TITLE
Difference between 'dotnet build' and 'dotnet compile'

### ISSUE THREAD

**Issue by russellhadley** [dotnet/cli#1310] opened 2016-02-09 17:58 UTC
In a clean project for which 'emitEntryPoint' is true, if you issue a 'dotnet build' you end up with an executable in the bin dir.  If instead you do a 'dotnet compile' in the clean project you only get a dll (and pdb).  If you then follow with 'dotnet build' the compile step is omitted (message: "Project myproj (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.")

output for 'dotnet build':
hostpolicy.dll
myproj.deps
myproj.dll
myproj.exe
myproj.pdb

output for 'dotnet compile':
myproj.dll
myproj.pdb

**Comment by blackdwarf** [comment] 2016-02-23 15:35
@russellhadley you should always use `dotnet build`. `dotnet compile` gets called within the flow. 

@cdmihai about the error message, I seem to remember us having a discussion on it?

**Comment by aL3891** [comment] 2016-02-23 20:29
Isn't this the intended behavior though? dotnet-compile just invokes csc and produces a dll, dotnet-build also embeds that dll in a platform specific exe file. If the project is already built, dotnet-build skips the dotnet-compile.

**Comment by blackdwarf** [comment] 2016-02-23 21:22
@aL3891 I understood @russellhadley that the skip happens completely, that is, even though there is no executable dotnet build skips.

**Comment by davidfowl** [comment] 2016-02-23 21:24
Yes, don't use `dotnet compile`, maybe we should remove it from running as a top level command.

/cc @cdmihai @piotrpMSFT

**Comment by cdmihai** [comment] 2016-02-23 21:28
Build uses the output path calculator to get a list of output items. If the executable path is in that list but does not exist in the file system, build should rebuild. Could be a bug somewhere if build knows about the exe but does not rebuild when it's not there

**Comment by blackdwarf** [comment] 2016-03-02 15:38
@cdmihai do you want to take a look at this?

**Comment by cdmihai** [comment] 2016-03-03 17:47
OK

**Comment by cdmihai** [comment] 2016-03-04 05:35
While testing this out I found out that dotnet compile is no longer available as a command that can be called by the user. So if you update dotnet CLI, compile is no longer callable. Problem solved :)

I looked into the incremental issue (why a rebuild is not triggered if the .exe is missing). This is because, for .net core apps,  the exe is not a product of csc, but a product of the Mini Publish that happens after compilation (to make the compilation output executable). So, for .net core apps the exe should not be considered for the incrementality of the compile phase. Also, ideally, the mini publish should not happen in the Build command but in the Publish command (and then build could call publish to make the app executable). This would keep the 2 commands focused on only one thing. 

I would put off adding Publish output files to incremental checks for when we're ready to make Publish itself incremental.

**Comment by krwq** [comment] 2016-04-07 21:27
@cdmihai, is this getting fixed for rc2?

**Comment by cdmihai** [comment] 2016-04-07 23:13
Support for the runtime files got introduced by this commit: https://github.com/dotnet/cli/commit/9fb99526a15aa0ff0a3e65cc08a84e5b9611ec7b

I checked it and it works. Unfortunately this makes the boundary between compilation and mini-publish more ambiguous, but it solves the missing exe problem :)

Closing issue.

**Closed by cdmihai** 2016-04-07 23:13 UTC
Labels: bug
