### ISSUE TITLE
Add implicit design time facade expansion

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#164] opened 2015-11-07 01:23 UTC
As much as I hate it, we have to do it for existing PCLs.

**Comment by piotrpMSFT** [comment] 2015-11-23 22:00
David, can you provide more detail on this?

**Comment by bricelam** [comment] 2016-01-08 17:27
@davidfowl We either need to fix this or NuGet. What is happening for RC2?

**Comment by davidfowl** [comment] 2016-01-08 17:30
I rather fix NuGet but that might take a while... Is it ok to fix vs2015 first?

**Comment by bricelam** [comment] 2016-01-08 17:31
(See also #578 & #579)
EF's current workaround was to target `net451` without the facade framework references and `dnx451` with them, but `dnx451` is going away, isn't it?

**Comment by bricelam** [comment] 2016-01-08 17:33
So long as customers can use our package for `net451` projects on both MSBuild+NuGet and CLI...

cc @rowanmiller

**Comment by ericstj** [comment] 2016-01-21 16:25
Since the CLI is replacing MSBuild here and there is existing precedent for these projects that CLI aims to be compatible with I'd recommend we match the existing precedent.

That means on desktop it auto-refs all the facades whenever a system.runtime-based DLL is referenced.  It also means that for platforms like NETCore and NETPortable it auto-references the entire targeting pack.  If you don't do this existing packages will break in CLI or folks will build new packages that don't work in MSBuild.

**Comment by bricelam** [comment] 2016-02-10 21:26
The current implementation doesn't work for following packages:
* ~~Remotion.Linq~~ (fixed via package update)
* System.Diagnostics.DiagnosticSource
* xuint.assert
* xunit.extensibility.core

**Comment by davidfowl** [comment] 2016-02-16 04:19
Why are people putting portable dlls in net4x folders wtf....

/cc @bradwilson @jaredpar @vancem @ericstj

**Comment by jaredpar** [comment] 2016-02-16 06:39
CC @tmat as he made this change for the Roslyn assemblies.

**Comment by bradwilson** [comment] 2016-02-16 07:50
@davidfowl Can you be more specific?

**Comment by davidfowl** [comment] 2016-02-16 07:54
My assumption (and I haven't looked) but `xuint.assert` and `xunit.extensibility.core` put a PCL in a folder that isn't labeled portable-*

**Comment by bradwilson** [comment] 2016-02-16 10:25
We use PCL 259 and dotnet folders, which both seem appropriate for a PCL 259 library:

https://github.com/xunit/xunit/blob/master/src/xunit.assert.nuspec

```xml
<file src="xunit.assert\bin\Release\xunit.assert.dll" target="lib\portable-net45+win8+wp8+wpa81" />
...
<file src="xunit.assert\bin\Release\xunit.assert.dll" target="lib\dotnet\" />
```

https://github.com/xunit/xunit/blob/master/src/xunit.extensibility.core.nuspec

```xml
<file src="xunit.core\bin\Release\xunit.core.dll" target="lib\dotnet\" />
...
<file src="xunit.core\bin\Release\xunit.core.dll" target="lib\portable-net45+win8+wp8+wpa81\" />
```

**Comment by bricelam** [comment] 2016-02-16 17:10
@davidfowl @bradwilson The "issue" with the xUnit.net packages is that it puts the lib in `dotnet` which gets picked on `net45`, but declares an empty set of dependencies for `net45`.

**Comment by bradwilson** [comment] 2016-02-16 17:18
*shrug* This is what we (and anybody else who took this early, ill-advised journey with you guys) were told to do. Nothing we can or will do about this until you guys ship a stable version of .NET Core. /cc @onovotny

**Comment by bradwilson** [comment] 2016-02-16 17:20
By the way, when you find issues like this many months later... this is why we (the community at large, but me specifically) have zero faith that your current rushed-to-hit-"RC2" plan will actually be right. :(

**Comment by tmat** [comment] 2016-02-16 17:21
+1 for what @bradwilson says. NuGet hasn't had clearly defined and validated rules. It's surely getting better but until nuget pack reports an error for badly formed packages you won't be able to rely on the packages being well formed.

**Comment by davidfowl** [comment] 2016-02-16 17:24
Looks like we're going to have to walk the assembly dependency graph much like msbuild does to resolve this.

**Comment by onovotny** [comment] 2016-02-16 17:28
One of the main reason for putting the empty `net45` dependency groups was to prevent 15 nuget packages from being pulled down for every consumer of this when the dependencies are already "in-box". Not really a big deal for project.json projects, but can be painful for those using packages.config.

**Comment by tmat** [comment] 2016-02-16 17:29
@davidfowl If Roslyn packages are not well formed please file a bug explaining how should they look like.

**Comment by onovotny** [comment] 2016-02-16 17:30
Furthermore, it seems like the CoreFX will be generating empty dependency groups for the same reason. @ericstj pointed me at this: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs

I was going to do something similar for the NuSpec reference generator.

**Comment by bricelam** [comment] 2016-03-07 22:35
This is an extremely painful issue, and it isn't just happening for "existing PCLs". It's happening for new packages shipping as part of .NET Core. (E.g. `System.Buffers`)

@davidfowl should this issue be moved off of the backlog and addressed before RTM?

**Comment by davidfowl** [comment] 2016-03-10 19:41
Moved this back to RTM as it affects the class lib authoring experience.

**Comment by piotrpMSFT** [comment] 2016-12-07 21:27
@davidfowl is this still needed? Who can we talk to about the work required?

**Comment by onovotny** [comment] 2016-12-07 21:30
This seems to be needed...if I try to reference a PCL with by using the XML elements:
https://github.com/onovotny/Preview3-migrate-bug/blob/master/MegaLib.csproj#L11-L13

It still fails to compile unless I add in `<Reference>` elements for each façade assembly....that's bad.

**Comment by piotrpMSFT** [comment] 2016-12-07 22:25
@onovotny is this a migration issue in your mind?

**Comment by onovotny** [comment] 2016-12-07 22:33
Absolutely....cannot easily use project types that work correctly with project.json today.

**Comment by piotrpMSFT** [comment] 2016-12-10 07:17
@nguerrera does the SDK have any support here?

**Comment by blackdwarf** [comment] 2017-01-20 16:04
@piotrpMSFT @nguerrera what is the status of this?

**Comment by livarcocc** [comment] 2017-01-25 06:11
I am not sure what is needed here. What is expected of migration in this case and under which circumstances?

What is the list of reference facade assemblies that we need to add and when?

**Comment by ericstj** [comment] 2017-01-25 06:37
Looks like folks are talking about two things here.

1. Automatically adding facades in desktop projects.  That's done by this:
https://github.com/Microsoft/msbuild/blob/40cd4d090dfebddd5417bc4e976feebc081a02ed/src/XMakeTasks/Microsoft.NETFramework.CurrentVersion.targets#L91 from folder https://github.com/Microsoft/msbuild/blob/765376a043d081569629998867d03e4a5eb9a256/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L1138.  I suspect that's happening for free, but @dsplaisted / @cdmihai can confirm.

2. Automatically referencing everything in PCL projects.  This is what @onovotny is talking about here: https://github.com/dotnet/cli/issues/164#issuecomment-265579153
That was done by the PCL targets, specifically ImplicitlyExpandTargetFramework in Microsoft.Portable.Core.targets.  In @onovotny's sample this isn't happening because he's not importing the portable targets like a PCL project would, he's importing MS.CSharp.targets.  I suppose for the SDK we'd have to look at what it does for a profile-based-PCL TFM.

**Comment by onovotny** [comment] 2017-01-25 12:58
This might be addressed by fully implementing https://github.com/dotnet/sdk/issues/491. In that case, it'll set the language targets to the Portable targets so that the expansion happens there.

Not sure if those targets are included x-plat though, but it'd fix it for Desktop MSBuild.

**Closed** 2018-02-07 23:16 UTC
Labels: RC3 known issue, enhancement, migration
