### ISSUE TITLE
dotnet build on NFS: Access to the path '.SDKVersion' is denied.

### ISSUE THREAD

**Issue by couven92** [dotnet/cli#4227] opened 2016-09-22 09:46 UTC
# Problem

The following problem occurs when attempting to build a dotnet project in Ubuntu when the project to build is located on a network file system.

When I run `dotnet build -f netstandard1.6` on any project, `dotnet build` returns the following output:

```
Project projectname (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling projectname for .NETStandard,Version=v1.6
Access to the path '/mnt/users/username/Documents/Source/projectsolution/src/projectname/obj/Debug/netstandard1.6/.SDKVersion' is denied.
```

However, when I run `ls -lah` with the path shown above, it shows me that the file is accessible (at least for me):

```
-rwxr--r-- 1 username usergroup 0 sep.  22 11:31 /mnt/users/username/Documents/Source/projectsolution/src/projectname/obj/Debug/netstandard1.6/.SDKVersion*
```

I am also able to open, edit and delete the file in the file explorer, with `gedit`, with `vim` or other usual tools.

Running `chmod a+rwx` on the file, so that all access right are granted does also not solve the problem.

In this case the project files are located on a NFS file system that is mounted in ubuntu. Any other program like `vim` or `git` that create dotfiles (files that start with `.`) work fine.
# Workaround

If I supply a path in `/tmp` with the `-b` option, the build runs successfully.
# Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003555)

Product Information:
 Version:            1.0.0-preview3-003555
 Commit SHA-1 hash:  a2b861e4c8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by kosak** [comment] 2016-10-13 01:14
Me too: I'm having the same problem on Debian, though in my case the OP's workaround doesn't work for me (perhaps because I've got a two projects: an application linking to a class library?)

In any case,

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

**Comment by couven92** [comment] 2016-10-14 20:33
Is the CLI maybe using some unusual way to access files? If so, I'd love to go look where this issue comes from, but I have no idea where the CLI decides to create the `.SDKVersion` file...

**Comment by kosak** [comment] 2016-10-14 22:50
Aha! After looking at this, I believe the problem is that the code is calling `flock`, which evidently doesn't work right on NFS on Linux. The good news is that the similar call `lockf` *does* seem to work. I believe it should be "easy" to change the flock call to the corresponding lockf call. This might need to be compiled conditionally, in case the target operating system doesn't support lockf.

Details:

Running `strace dotnet build` yields an important clue: dotnet is apparently locking the file after creating it:

```
open("/mnt/nfs/git/life/tools/blah/obj/Debug/netstandard1.6/.SDKVersion", O_WRONLY|O\
_CREAT|O_TRUNC, 0766) = 73
fstat(73, {st_mode=S_IFREG|0744, st_size=0, ...}) = 0
flock(73, LOCK_SH|LOCK_NB)              = -1 EBADF (Bad file descriptor)
```

The Internet tells me that ```flock``` does not work on NFS on Linux, but ```lockf``` does. I've written a small program that confirms this behavior:

```
kosak@nfstest-1:~$ ./a.out localfile.txt
flock succeeded
lockf succeeded
kosak@nfstest-1:~$ ./a.out /mnt/nfs/remotefile.txt
flock failed, errno is 9
lockf succeeded
```

This is the program:

```
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <unistd.h>

int main(int argc, char **argv) {
  if (argc != 2) {
    printf("usage: %s filename\n", argv[0]);
    return;
  }
  int fd = open(argv[1], O_WRONLY|O_CREAT|O_TRUNC, 0766);
  if (fd < 0) {
    printf("open failed, errno is %d\n", errno);
    return;
  }

  int res = flock(fd, LOCK_SH | LOCK_NB);
  if (res < 0) {
    printf("flock failed, errno is %d\n", errno);
  } else {
    printf("flock succeeded\n");
  }

  res = lockf(fd, F_TLOCK, 0);
  if (res < 0) {
    printf("lockf failed, errno is %d\n", errno);
  } else {
    printf("lockf succeeded\n");
  }
}
```

**Comment by blackdwarf** [comment] 2017-01-12 05:38
So, based on the discussion, it seems that the problem is not in the CLI itself but either in corefx (since we use .net APIs to access files) and Linux not supporting the native call corefx uses. Would I be right in my assesment?

**Comment by couven92** [comment] 2017-01-12 10:12
Looks like it. I can reissue in a different repo if you like. Where?

**Comment by blackdwarf** [comment] 2017-01-12 15:07
@couven92 that would be splendid. dotnet/corefx is the right place, I think.

**Comment by couven92** [comment] 2017-01-12 18:02
@blackdwarf done! Do we leave this one open until https://github.com/dotnet/corefx/issues/15120 is resolved?

**Comment by blackdwarf** [comment] 2017-01-12 19:21
@couven92 thanks! We will close this one to not duplicate. :)

**Closed by blackdwarf** 2017-01-12 19:21 UTC
