### ISSUE TITLE
Collapse in-box commands in single process

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2483] opened 2016-04-13 23:09 UTC
CLI Version: 1.0.0-rc2-002357

When compiling a C# hello world app using the CLI, it takes 3 processes to perform the "dotnet build" step.

1. dotnet build
2. dotnet compile-csc [spawned dotnet build]
3. dotnet csc.dll [spawned by dotnet compile-csc]

Each of these comes with the overhead of starting a new process, booting the runtime, loading dependencies and JITTing some of them before work can proceed.  My understanding is that this due to the extensibility model, but I'd like to believe that for a target such as C# where everything is contained in the SDK and shared framework that we could get this down to one process and get rid of the overhead.

- [x] #2542 dotnet compile should invoke compile-csc in the same process
- [ ] compile-csc should invoke the actual C# compiler in the same process

**Comment by brianrob** [comment] 2016-04-13 23:09
@brthor, PTAL

**Comment by gkhanna79** [comment] 2016-04-14 00:22
CC @piotrpMSFT

**Comment by cdmihai** [comment] 2016-04-14 00:28
Please reference me in the PR when this is done.

**Comment by eerhardt** [comment] 2016-04-14 22:54
First round of investigation:

`dotnet build` calls `dotnet compile` inline without spinning a new process:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-build/CompileContext.cs#L387

However, `dotnet compile` does invoke `dotnet compile-csc` with a new process:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L184

Working on making that in-proc...

**Comment by eerhardt** [comment] 2016-04-14 22:57
Also, like stated orginally, `compile-csc` will spin a new process for `dotnet csc.dll`:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile-csc/Program.cs#L117

Making that one in-proc as well.

**Comment by eerhardt** [comment] 2016-04-14 23:25
> Also, like stated orginally, compile-csc will spin a new process for dotnet csc.dll

That one appears to be troublesome.  What is the best way to invoke the C# compiler in-proc?

/cc @jaredpar @Pilchie

**Comment by jaredpar** [comment] 2016-04-14 23:26
Given that you're converting from a `Process.Start` call the easiest way is to just pass the arguments to the `Main` method.  There are more correct ways of doing it but it involves more code.  If you'd like to take that route we can get you pointed in the right direction.

**Comment by eerhardt** [comment] 2016-04-14 23:31
Thanks, @jaredpar.  Looking more into it, I don't think I can get a reference to the csc.dll from my project.json.  It looks like we are taking the `csc.exe` that ships in the runtimes folder of `Microsoft.Net.Compilers.netcore` and copying it to `csc.dll`.  I don't think there is a NuGet package that can give me this reference.

So maybe the 2nd route would be the way to go.  Can you point me in the right direction?

**Comment by eerhardt** [comment] 2016-04-15 03:48
@jaredpar - I hacked around calling the `Main` method by using reflection.  However, in some cases, I am getting errors like:

```
System.InvalidOperationException: Binding model is already locked for the AppDomain and cannot be reset.
   at System.Runtime.Loader.AssemblyLoadContext.InitializeDefaultContext(AssemblyLoadContext context)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

Does this error make sense?  It would seem something is "locking the binding model" before Roslyn gets invoked, and thus Roslyn can't do it itself.

I kind of think this error is going to block dotnet/cli from invoking the csc compiler in-proc.

**Comment by jaredpar** [comment] 2016-04-15 16:35
Hmm, that last error is indicative of a larger problem. 

The error you are seeing here is related to how Roslyn loads analyzers.  Which analyzers we load are defined as command line arguments and we use an `AssemblyLoadContext` to get them into the process.  The `Main` method assumes it's run once per process and hence always calls `InitializeDefaultContext` which leads to the above error if you call `Main` twice.  

It's possible for us to fix that but it's pointing to a bigger issue that comes when you try and run Roslyn in proc.  What happens when there are conflicting analyzers?  Say for instance you have the following:

- CompilationA: requires Analyzer.dll version 1.0. 
- CompilationB: requires Analyzer.dll version 2.0.

The problem is more typically with analyzer dependencies but can happen at the top level as well.  Once we load a particular `Assembly` into the proc we can't load another into the same address space.  Ideally `AssembyLoadContext` was supposed to give us isolation here so that we could run multiple compilations with conflicting analyzers in proc but we punted on that until RTM (just don't know enough about `AssemblyLoadContext`.  

That puts us in a bit of a pickle.  There are a few options that I see:

1. Don't run csc in proc
2. Run csc in proc if there are no analyzers, if there are analyzers shell out.  This would still require us to change how you call CSC a bit but that's a known item. 
3. Change csc to use `AssemblyLoadContext` to provide the proper isolation.  

My preference is 1 or 2.  These are known quantities that we could do confidently.  The last one though has a bit more risk to it.

**Comment by eerhardt** [comment] 2016-04-15 17:03
Thanks for the detailed explanation, @jaredpar.

Even with the "more correct ways of doing it but it involves more code" that you mentioned yesterday, would we still have this conflicting analyzer version issue?

I agree with your assessment that changing any `AssemblyLoadContext` code isn't a good option right now.

**Comment by brianrob** [comment] 2016-04-15 18:18
@gkhanna79 and @jkotas can you help with expertise on AssemblyLoadContext?  I'm definitely of the opinion that choosing a well-understood solution for RC2 is the way to go.  Before we throw out the idea of doing something with AssemblyLoadContext, let's get some input from the experts.  I'd like to believe that we can know if there's something quick and relatively not-risky to be done here by EOD.

**Comment by jaredpar** [comment] 2016-04-15 18:22
@brianrob the core issue is that `AssemblyLoadContext` is lacking documentation.  The key issues we need to understand are:

1. What is the actual isolation boundary guaranteed by `AssemblyLoadContext`.  Does it isolate statics, assemblies, etc ...  
2. How does communication work between assemblies loaded in different `AssemblyLoadContext`?  

In `AppDomains` for example the answers were full isolation and use binary serialization / remoting.  

> I'd like to believe that we can know if there's something quick and relatively not-risky to be done here by EOD.

I don't think this is realistic.

**Comment by gkhanna79** [comment] 2016-04-15 18:47
I agree there is no formal documentation on the topic. However, https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Loader/tests is an example of how the feature gets used (similarly, ASP.NET uses it all across in their implementation as well).

For the specific questions:

1) Assemblies loaded in one context do not see assemblies in another context and cannot consume their functionality. Thus, you will need to build a custom communication channel between them if you wish to have them interact with one another.

2) Statics are still managed at AppDomain level.

3) LoadContext cannot be unloaded. Thus, it means that assemblies cannot be unloaded as well.

Does this help?

**Comment by jaredpar** [comment] 2016-04-15 18:52
Thanks for the info.  That helps a bit.  

How does the JIT work here?  If I load the same physical assembly into separate contexts do I get to re-use the JIT'd methods?  Or does everything get re-JIT'd.  

> Statics are still managed at AppDomain level.

No app domains here though so I don't know how this impact statics sharing. 

> Thus, it means that assemblies cannot be unloaded as well.

That's fine so long as different assemblies with the same identity can be loaded in different `AssemblyLoadContext` instances. 

> Thus, you will need to build a custom communication channel between them if you wish to have them interact with one another.

Any examples of this I can look at?  I can't even really figure out how to call the initial kick off method in a loaded assembly.  That may be a good starting point.

**Comment by piotrpMSFT** [comment] 2016-04-18 23:25
Moving to RTM. Roslyn's extensibility model does not make it a great candidate for running in-process with CLI. We may be able to find some wins by moving things like Roslyn analyzers out-of-process but this is not clearly the right thing to do and will not happen in RC2.

**Comment by gkhanna79** [comment] 2016-04-19 16:50
> How does the JIT work here? If I load the same physical assembly into separate contexts do I get to re-use the JIT'd methods?

Yes. I am not aware of anything in the design that prevents this.

> No app domains here though so I don't know how this impact statics sharing.

@jkotas Thoughts?

> Any examples of this I can look at?

The simplest way is to load an assembly in one LoadContext and return its reference for use in another LoadContext.

**Comment by jkotas** [comment] 2016-04-19 17:04
> If I load the same physical assembly into separate contexts do I get to re-use the JIT'd methods?

Same physical assembly loaded into separate contexts gets own copy of the JITed code, as well as its own copy of statics.

Assembly loaded in one context can have its dependencies satisfied by assemblies loaded into a different context. The typical usage pattern for extensions is:
- Framework and main app is loaded into the default context
- Extension is loaded into custom context
- Extension references framework and the main app extension points from the default context. It does not have its own copy.

> Any examples of this I can look at?

You have to use reflection to establish the initial link. If the assembly has main method, you can call Assembly.EntryPoint and invoke it. Roslyn has example as well - it is using it to load analyzers on CoreCLR.

**Comment by piotrpMSFT** [comment] 2016-04-19 17:50
@brianrob @eerhardt besides csc.exe, are there any other in-box commands that get invoked out-of-proc?

**Comment by eerhardt** [comment] 2016-04-19 18:19
Looking at `Command.CreateDotNet`, it gets called from 4 places:

1. https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-build/CompileContext.cs#L314
 - `private void CollectCheckPathProbingPreconditions(ProjectContext project, IncrementalPreconditions preconditions)` which doesn't look like it actually executes the commands
1. https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-repl/Program.cs#L83
 - Used for repl
1. https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-run/RunCommand.cs#L185
 - Used for "interactive" running
1. https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/DotNetCommandFactory.cs#L29
 - This is the place I just refactored to check for 'built-in' commands first, so this won't get invoked out-of-proc if it is built-in.

So I think we are OK here. There shouldn't be any more processes that need reducing.

NOTE: obviously `dotnet run` and `dotnet test` spin up new processes, but that is completely by design and desired.

**Comment by cdmihai** [comment] 2016-04-19 20:11
1) is used to check how the command gets loaded (Path is bad, other stuff is okay).

**Comment by livarcocc** [comment] 2016-05-10 23:18
@eerhardt What is the work left here?

**Comment by eerhardt** [comment] 2016-05-10 23:20
The unchecked box in the issue description:

- [ ] compile-csc should invoke the actual C# compiler in the same process

**Comment by livarcocc** [comment] 2016-05-10 23:25
@eerhardt I was under the impression from your comment 4 boxes above that we had found a way around that. A way that handled the problem and therefore we didn't need to invoke the C# compiler in-proc. I guess not.

**Comment by eerhardt** [comment] 2016-09-20 16:33
Closing.  Since we are moving to MSBuild, this will no longer be controlled by the CLI.  We will be shelling out to MSBuild to do the build, and separate processes will be spawned as necessary by MSBuild, not by the CLI.

**Closed by eerhardt** 2016-09-20 16:33 UTC
Labels: blocking-release
