### ISSUE TITLE
Version of Microsoft.NET.Sdk package used by "dotnet new" does not match the version in offline package installer

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4510] opened 2016-10-27 20:30 UTC
INSTALL STEPS
1. Run preinstall.cmd
2. Install Dev15 RC build d15rel.25827.01 (.NET Core workload)

REPRO STEPS
1. Run "dotnet new" from command-line

ACTUAL
Version of Microsoft.NET.Sdk package used by "dotnet new" does not match the version in offline package installer. Version used by "dotnet new" is 1.0.0-alpha-20161019-1 but the one from offline package installer is 1.0.0-alpha-20161027-2

I'd expect the versions to be in-sync. Impact is probably that if you do 'dotnet new' and then open the project in VS, then it's using an old package and things might not behave correctly.

![image](https://cloud.githubusercontent.com/assets/8246794/19783171/bddc1f72-9c45-11e6-9912-fa3c3cb3ba7a.png)

**Comment by piotrpMSFT** [comment] 2016-10-27 22:10
Templates in the CLI need to match the offline packages in the CLI installer. We will need to synchronize CLI and VS before shipping. This is a point-in-time thing as products lock down.

**Comment by jinujoseph** [comment] 2016-11-02 16:53
Can we close this after this is in sync ? 
I see this out of sync on todays build d15rel/15.0.25901.2
Microsoft.NET.Sdk package used by "dotnet new" is 1.0.0-alpha-20161029-1, which does not match the version in offline package 1.0.0-alpha-20161031-2

**Comment by MiaomiaoHuangfu** [comment] 2016-11-10 02:29
Testing on build d15rel/15.0.25909.0: 
Version of Microsoft.NET.Sdk package used by "dotnet new" is 1.0.0-alpha-20161104-2, which matched the version in offline package 1.0.0-alpha-20161104-2.
The issue is fixed.

**Closed** 2016-11-10 02:31 UTC
