### ISSUE TITLE
Error with Resharper build: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

### ISSUE THREAD

**Issue by rchrismon** [dotnet/cli#9087] opened 2018-04-17 20:13 UTC
## Steps to reproduce
Create ASP.NET Core Web Application, Web Application (Model-View-Controller)
Using MySQL database, imported MySQL Framework Core DLLs 
    MySql.Data 8.0.10-rc
    MySql.Data.Entity 7.0.7-m61
    MySql.Data.EntityFrameworkCore 8.0.10-rc
Other pretty much standard DLLs for building a .netcore 2.0 web-app.
Build solution

## Expected  behavior
Clean build

## Actual behavior
Error: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.200-preview-007517)

Product Information:

Output from dotnet --info:
 Version:            2.1.200-preview-007517
 Commit SHA-1 hash:  dc62e50c3a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200-preview-007517\
Microsoft .NET Core Shared Framework Host
Version  : 2.0.6
Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Versions:
VS 2017 15.6.6 and 15.7.0 preview 3

**Comment by livarcocc** [comment] 2018-04-17 20:15
Does this repro if you build through the command line using full framework msbuild? Just open a developer prompt and run msbuild on your solution.

@nguerrera since this seems like a resolver issue.

**Comment by nguerrera** [comment] 2018-04-17 20:26
The project opens in VS, but does not build? That is not the typical case for that error message.

**Comment by rchrismon** [comment] 2018-04-17 21:07
Yes, the project opens but does not build. In response to livarcocc, dotnet build completes successfully, but neither dotnet run, nor dotnet myProject.dll will instantiate our web-app landing page. Looks like a 404 error. 

Thanks.

**Comment by nguerrera** [comment] 2018-04-17 21:08
What do you get when you run `msbuild` instead of `dotnet build`?

**Comment by livarcocc** [comment] 2018-04-17 22:27
What are the contents of `c:\Program Files\dotnet\sdk\2.1.200-preview-007517\Sdks`? Do you have a Microsoft.NET.Sdk.Web folder there? And what are the contents of that folder?

**Comment by rchrismon** [comment] 2018-04-18 13:53
Need to find msbuild. It isn't in the path... msbuild.exe worked but there were 800+ warnings about dll conflicts, downgrades, and who knows what else. 

I figure it has to  be a configuration or resolver issue of some sort, but completely at sea with what or where.

Thanks.

**Comment by rchrismon** [comment] 2018-04-18 14:01
Results of dir > dotnet.lst:

[dotnet.zip](https://github.com/dotnet/cli/files/1924286/dotnet.zip)

Anybody want to see the csproj or sln files?

Thanks.

**Comment by rchrismon** [comment] 2018-04-18 16:04
Livarcocc, I'm not sure what you're asking. Under the "C:\Program Files\dotnet\" folder there is an sdk folder, and under that a 2.1.200-preview-007517 folder. In that folder there is another sdk folder containing the Microsoft.NET.Sdk.Web folder. (Should I keep going?). Next is another Sdk folder containing two files, Sdk.props, and Sdk.targets. 

So Program files => dotnet => sdk => 2.1.200-preview-007517 => Sdks => Microsoft.NET.Sdk.Web => Sdk, with files.

Does that help?

**Comment by nguerrera** [comment] 2018-04-18 16:15
Msbuild should be on your path if you launch "Visual Studio Developer Command Prompt" from start menu.

Run `msbuild /bl` and send the resulting msbuild.binlog. If you can share the solution as well that would be helpful. Note that binlog may also reveal details about your project. If you'd prefer to share over email rather than publicly here, you can reach me at nicholg at microsoft.com

**Comment by rchrismon** [comment] 2018-04-18 16:46
Output from msbuild /bl attached.
[BuildOutput.txt](https://github.com/dotnet/cli/files/1924955/BuildOutput.txt)

**Comment by nguerrera** [comment] 2018-04-18 17:13
Can you send the `msbuild.binlog` file that is dropped on disk from there? Again, feel free to email me (nicholg at microsoft.com) if there are concerns about anything confidential in the project being shared publicly.

The build is working fine via command line msbuild (those conflict messages aren't errors and I think they should be dropped in importance, but that's entirely separate).

It is very strange that VS can evaluate the projects, but cannot build them and msbuild.exe can build fine. I have not seen this combination before with respect to sdk resolution.

Given that, binlog files from VS builds would also be very useful. You can get those using: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools

**Comment by rchrismon** [comment] 2018-04-18 20:03
Well, this is interesting. Build Logging shows no output. So, either I'm using it incorrectly, or I'm going crazy. I shutdown VS, then clicked on the visx to install Build Logging. I then restarted VS, and opened the solution. Opening the Build logging view, I saw that there was a start button (triangle), so I clicked that on, then did a solution build (there's only one project in the solution). Build ended very quickly with the Build Results window showing the error. The Build Logging window, is empty. Should I be looking for an output file somewhere?

Interestingly, I did get the following last view lines in the Output window, showing output from Build:

CONSOLE: Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
CONSOLE: Copyright (C) Microsoft Corporation. All rights reserved.
CONSOLE: Build started 18-Apr-18 13:55:24.
0: ------- Project started: MySolution.Admin
0: ------- Project finished: MySolution.Admin. Succeeded: False. Errors: 0. Warnings: 0
Build completed in 00:00:00.764

I'm not sure what to make of Project finished.... Succeeded: False. Errors: 0. Warnings: 0. I'm guessing the false statement means the build failed. 

Thanks for all your help!

**Comment by nguerrera** [comment] 2018-04-18 20:18
You can save the logs from project system tools via right-click, save logs:

![image](https://user-images.githubusercontent.com/75470/38955803-90113e34-430a-11e8-946f-455a1a2a1b9c.png)

There is a built-in viewer (see explore logs, open logs) and also http://msbuildlog.com

**Comment by rchrismon** [comment] 2018-04-19 15:10
Well, as I said, there's no output from the System Tool. I can open the Save Logs menu item, as shown in your last post, but there's nothing to save. I tried to open logs, and also got nothing. As soon as my file manager stops looking for msbuild.binlog (mentioned in one of your earlier posts) I'll try to explore logs. 

It's not at all your problem, but I don't look forward to my meeting with the boss later this morning!

Thank you!

Randy

**Comment by rchrismon** [comment] 2018-04-19 15:14
Is there a debugger that I can run from the command line? Dotnet build, dotnet msbuild, and msbuild by itself all successfully build the app. However, I need to debug the app, but I can't launch it from within VS because of the alleged build error. 

Thanks, 

Randy

**Comment by rchrismon** [comment] 2018-04-19 16:16
I am so sorry!! I had a colleague look at my situation. He noticed that I was using JetBrains build instead of MSBuild. When I switched to MSBuild, the application built as expected. 

I apologize for wasting  your time.

Randy

**Comment by nguerrera** [comment] 2018-04-19 17:45
No time wasted! Glad to help! 

It is very good to know how this situation can occur. We had not observed a case before this where a project loads, but cannot find Sdk on build. I can happily work with JetBrains to help get this resolved. 

@AndreyAkinshin, How should we proceed? Is this a known issue on your side? Feel free to reach out to me by email me (nicholg at microsoft.com) to discuss further.

**Comment by livarcocc** [comment] 2018-05-11 23:01
@nguerrera did you and @AndreyAkinshin talk? Do you want to keep this issue open still or should we go ahead and close it?

**Comment by nguerrera** [comment] 2018-05-11 23:40
We haven't spoken. I think we can leave the issue open in the Discussion milestone.

**Comment by AndreyAkinshin** [comment] 2018-05-14 12:14
@livarcocc, @nguerrera, sorry for the late response. An answer from our QA team:
> We can't reproduce this issue on our side.
> It seems that you are using an old version of ReSharper.
> Could you please update ReSharper and VS?
> If you are able to reproduce this problem on the latest version of ReSharper,
> please, create an issue in our tracker: https://youtrack.jetbrains.com/issues/RSRP

**Comment by livarcocc** [comment] 2018-10-02 23:30
Closing based on the answer above that this could not be reproduced using the latest resharper.

**Closed by livarcocc** 2018-10-02 23:30 UTC
