### ISSUE TITLE
dotnet add package without version not updating packages

### ISSUE THREAD

**Issue by rlm95** [dotnet/cli#7937] opened 2017-10-30 19:58 UTC
## Steps to reproduce
inside a folder with a .csproj file run dotnet add package {packagename} on a package that is not currently up to date.

## Expected  behavior
Package should update to the latest version available

## Actual behavior
Package does not update

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment] 2017-10-30 20:26
I don't believe this ever happened with dotnet add package command.

There is an issue on Nuget tracking a dotnet update package command here: https://github.com/NuGet/Home/issues/6054.

Closing issue as a duplicate of that one.

**Closed by livarcocc** 2017-10-30 20:26 UTC

**Comment by rlm95** [comment] 2017-11-01 14:19
I know it definitely did happen with the dotnet add package command because I have used it before. It works on version 2.0.0. It looks like on the issue you linked it seems it was implemented by nuget.
