### ISSUE TITLE
dotnet publish on a default dotnetcore class lib fails

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#3764] opened 2016-07-01 22:54 UTC
## Steps to reproduce
1. Create a .Net Core class library in VS
2. Go to commandline 
3. dotnet restore
4. dotnet build
5. dotnet publish

## Expected  behavior
dotnet publish infers the runtime (in the default case)

## Actual behavior
Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.

## Environment data
`dotnet --info` output:
C:\git\ClassLibrary1\src\ClassLibrary1>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment] 2016-07-28 06:11
Closing this as "by design". The libraries cannot be published, they should be packed. The error from `dotnet publish` has the correct help text.

**Closed by blackdwarf** 2016-07-28 06:11 UTC
