### ISSUE TITLE
dotnet build fails if the directory name is new

### ISSUE THREAD

**Issue by amaldevv** [dotnet/cli#5920] opened 2017-03-04 21:19 UTC
## Steps to reproduce
1. Create a new directory `md new` and set it as current directory `cd new`
2. Create a new console project `dotnet new console`
3. Restore the packages `dotnet restore`
4. Compile it using `dotnet build`
## Expected  behavior
Should get successfully compiled message

## Actual behavior

Getting build errors 

> Program.cs(3,11): error CS1001: Identifier expected [E:\test\new\new.csproj]
Program.cs(3,11): error CS1514: { expected [E:\test\new\new.csproj]
Program.cs(3,11): error CS0116: A namespace cannot directly contain members such as fields or methods [E:\test\new\new.csproj]
Program.cs(4,1): error CS1022: Type or namespace definition, or end-of-file expected [E:\test\new\new.csproj]
>
>Build FAILED.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-rc4-004771)
>
>Product Information:
>Version:            1.0.0-rc4-004771
> Commit SHA-1 hash:  d881d45b75
>
>Runtime Environment:
> OS Name:     Windows
> OS Version:  10.0.14393
> OS Platform: Windows
> RID:         win10-x64
> Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by livarcocc** [comment] 2017-03-05 00:34
This is a duplicate of https://github.com/dotnet/templating/issues/381.

**Closed by livarcocc** 2017-03-05 00:34 UTC
