### ISSUE TITLE
XAML designer or application failed to launch : invalid runtime config.json

### ISSUE THREAD

**Issue by chabiss** [dotnet/cli#11709] opened 2019-07-02 19:12 UTC
## Steps to reproduce
Verified that the machine is on 
3.0.100-preview7-012601

Install Visual Studio 16.3 Preview 1
 
First project.
"\\scratch2\scratch\peterspa\MahAppsFail\MahApps.Metro.zip"
 
It restore and compile fine. But then we try to launch the designer, we have this error: 
 
This appears to be a bug with design time 
 
 
 
Below is a copy of the JSON file. 
\\scratch2\scratch\peterspa\MahAppsFail\WpfSurface.runtimeConfig.json
 
 
Second project: 
\\scratch2\scratch\chabiss\RuntimeConfig.zip
 
This one is the one I showed to Livar.  You can add the private feed (https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json ) to get around the fact that you can’t restore properly because of the package reference  
However, when you try to open Mainpage.xaml.  Same problem
 
 
 
Same problem: 
\\scratch2\scratch\chabiss\WpfSurface.runtimeConfig.json
 
I think this is blocking 16.3 Preview 1.   

## Expected  behavior
App running file and and Designer loading

## Environment data
`dotnet --info` output:

**Comment by nguerrera** [comment] 2019-07-03 14:17
The issue is caused by transitive framework references. It is getting Microsoft.WindowsDesktop.App transitively and directly, and then we put dupes of it in runtimeconfig. The issue is not limited to design time, the built app doesn’t start either.

If DisableTransitiveFrameworkReferences=true is used, then the designer and the app work.

cc @livarcocc @dsplaisted

**Comment by AlexanderTaeschner** [comment] 2019-07-08 11:42
Although there was a fix merged to dotnet/sdk, this fix seems to be not included in the latest SDK (3.0.100-preview8-012929) yet! The included Microsoft.NET.Build.Tasks.dll has the version 3.0.100-preview8.19354.2+adf76a594158a742e2c22b49b0fb4942cb53317d.

**Comment by nguerrera** [comment] 2019-07-08 17:52
@AlexanderTaeschner This can happen where a fix made in a release branch doesn't flow to master right away. Keep in mind that daily builds like the preview 8 build you're using are not official releases. The official preview 7 will have this fix as will the official preview 8. We don't generally make guarantees about when daily builds will have certain changes. That said, I will look at getting this fix flowing as soon as possible to master of dotnet/core-sdk.

**Closed** 2019-07-10 19:57 UTC
Labels: bug, release blocking
