### ISSUE TITLE
can use dotnet in command but cannot be located in vscode on mac os 

### ISSUE THREAD

**Issue by yuzd** [dotnet/cli#3858] opened 2016-07-13 23:18 UTC
#
![image](https://cloud.githubusercontent.com/assets/16083659/16822865/45e1204a-4992-11e6-9762-361a5c2f694a.png)

sorry my english is not good.so i upload a pic to show my probleam.
the point is .i update to the new .net core  sdk.
i add to the PATH .and  i can use 
dotnet new 
dotnet restore
dotnet run 
in the command.
but when i open the project in vscode.
the cli tools cannot be located error happen.

## Environment data
`dotnet --info` output:
bash-3.2$ dotnet --info
.NET Command Line Tools (1.0.0-preview3-003180)

Product Information:
 Version:            1.0.0-preview3-003180
 Commit SHA-1 hash:  d4193cd5c1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
bash-3.2$ dotnet run
Project hello (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hello World!

#Console
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.e.doShow @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88

I tried above .but not solved.
use command+P.and enter >Download .Net core Debugger
likes nothing hanppen . the console also have no error message. 

# Append
![image](https://cloud.githubusercontent.com/assets/16083659/16879082/95d1377a-4ae1-11e6-8a6d-6b66135258e6.png)
i can use dotnet restore in command.
but when i use Command+p and enter >dotnet restore
then "/bin/sh" 

![image](https://cloud.githubusercontent.com/assets/16083659/16881910/00d8535c-4aef-11e6-8fea-bf33c2e2f9d8.png)

![image](https://cloud.githubusercontent.com/assets/16083659/16882171/211224e4-4af0-11e6-9ac4-2ee3317cd118.png)

**Comment by tonyferreira** [comment] 2016-07-15 15:29
Try closing vscode completely and then restarting it.  If you updated the CLI tools while vscode was open, vscode likely _did not_ load the updated $PATH environment variable.

**Comment by yuzd** [comment] 2016-07-15 16:53
@tonyferreira i restart my pc. but /bin/sh:dotnet command not found error not solved.
and i upload another pic to show that.

**Comment by blackdwarf** [comment] 2016-07-18 23:51
@yuzd I just tried it but I exited VS Code with Cmd-Q (or Code -> Quit VS Code from the menu bar). After restarting VS Code it actually worked. Can you try that?

**Comment by yuzd** [comment] 2016-07-19 00:39
@blackdwarf 
thanks for comment。
I tried that.but failed.
my vs code can not use dotnet command.so i tried this:

➜  ~ which dotnet
/usr/local/bin/dotnet

i copy the dotnet file from  [/usr/local/bin/dotnet] to the project folder.
then debugger working.

![image](https://cloud.githubusercontent.com/assets/16083659/16934723/b01ff0c4-4d8b-11e6-9662-c143d77e9222.png)

but this was not expected.
i need help.

**Comment by blackdwarf** [comment] 2016-07-20 00:58
What is the version of the SDK you have installed? You can find this out by running `dotnet --version` from the terminal.

Thanks,
Z

Sent from my tricorder




On Mon, Jul 18, 2016 at 5:40 PM -0700, "鱼东东" <notifications@github.com<mailto:notifications@github.com>> wrote:


@blackdwarf<https://github.com/blackdwarf>
thanks for comment。
I tried that.but failed.
my vs code can not use dotnet command.so i tried this:

? ~ which dotnet
/usr/local/bin/dotnet

i copy the dotnet file from [/usr/local/bin/dotnet] to the project folder.
then debugger working.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f16083659%2f16934723%2fb01ff0c4-4d8b-11e6-9662-c143d77e9222.png&data=01%7c01%7cZlatko.Knezevic%40microsoft.com%7c2f28adb66a7b4d71ced708d3af6d36f1%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=a7MZfVayhoJv0KS3pnfVIc%2fUqS2ZmGjFLJSPI5X%2fIqU%3d>

but this was not expected.
i need help.

―

**Comment by yuzd** [comment] 2016-07-21 00:16
@blackdwarf 
➜  ~ which dotnet
/usr/local/bin/dotnet
➜  ~ dotnet --version
1.0.0-preview3-003180

Thanks for helping!

**Comment by leonplata** [comment] 2016-07-24 17:20
The same issue for me with 1.0.0-preview2-003121 on Mac OSX

I've installed [nvm](https://github.com/creationix/nvm) much earlier than dotnet

I read this [issue](https://github.com/OmniSharp/omnisharp-vscode/issues/555) from the OmniSharp repository, so I tried by removing the nvm related scripts from my profile (`~/.bash_profile`, `~/.zshrc`, `~/.profile`, or `~/.bashrc`), this workaround is working in my case

**Comment by piotrpMSFT** [comment] 2016-07-27 09:16
@DustinCampbell

**Comment by DustinCampbell** [comment] 2016-07-27 10:11
cc @gregg-miskelly as well

**Comment by blackdwarf** [comment] 2016-07-27 15:29
@Tobyee you have a very old version of the dotnet tools. Can you please install the latest and see if it repros again?

**Comment by yuzd** [comment] 2016-07-28 00:29
@leonplata 
thank you very mush.
I removed the nvm from the ~/.zshrc .
then sloved!

But i can not use node command .do you have any idea for that?

**Comment by Tobyee** [comment] 2016-07-28 07:07
@blackdwarf 
The problem solved, see

https://github.com/OmniSharp/omnisharp-vscode/issues/627#issuecomment-235816230

**Closed** 2016-08-01 00:39 UTC

**Comment by bandrei** [comment] 2018-07-09 07:12
This issue is still happening with the latest version of Visual Studio Code on macOS.

**Comment by gregg-miskelly** [comment] 2018-07-09 17:14
@bandrei If you are only seeing this problem in VS Code (not a terminal window), the problem is likely to be that you have something configured with your shell that break's VS Code's ability to scrape environment variables. There are troubleshooting steps in https://github.com/Microsoft/vscode/issues/21655 that you may find useful.

**Comment by bandrei** [comment] 2018-07-10 07:07
I would've thought that might be the case, however whenever I run `env` I do see the path to dotnet being set correctly to `/usr/local/share/dotnet`. I opened another issue with the Azure Functions Extension because I think that's where the problem is (i.e. it doesn't know where on the path to look for the SDK)

**Comment by bandrei** [comment] 2018-07-10 07:46
ok, so the omnisharp server is starting correctly after running `dotnet restore` from VSCode. I guess that's needed to install the project depdencies locally. However the missing .NET cli error is still there.

**Comment by bandrei** [comment] 2018-07-10 07:57
further tracked it down to

```
> Executing task: dotnet clean <

/bin/bash: dotnet: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

It does look like the task execution is not picking up the environemnt variables

**Comment by bandrei** [comment] 2018-07-10 07:59
Ok, I have absolutely no idea what happened (it might have been my empty dev.env) file that messed up the path after omnisharp started working, however I restarted and updated VSCode and things are working now.

**Comment by Miggleness** [comment] 2018-07-19 05:59
@bandrei check your ~/.bash_profile and comment out items one by one.  In my case, the problem was caused when I added `export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"`
