### ISSUE TITLE
Custom tool: No executable found matching command <mytool>

### ISSUE THREAD

**Issue by alderic** [dotnet/cli#3178] opened 2016-05-21 13:05 UTC
How can I create custom tool and run it for my project?

## Steps to reproduce
https://github.com/alderic/dotnet-tool

## Expected  behavior
"Hello dotnet tool."

## Actual behavior
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\username\.nuget\packages\.tools\dotnet-tool'.
or (if I do some change to project.json of sampleapp)
No executable found matching command "dotnet-tool"
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment] 2016-05-21 16:21
@alderic http://dotnet.github.io/docs/core-concepts/core-sdk/cli/extensibility.html has info on how to build a tool that `dotnet` can run. 

Based on the above in the issue I can suggest the following:

- Have you packaged the tool into a NuGet package using `dotnet pack`?
- After the above, have you restored the sample app?

**Comment by alderic** [comment] 2016-05-21 17:47
yes, restore sampleApp log part:

> log  : Restoring packages for tool 'dotnet-tool' in c:\Users\username\Documents\Visual Studio 2015\Projects\SampleAppWithTool\src\SampleAppWithTool\project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/dotnet-tool/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/dotnet-tool/index.json 576ms
error: Unable to resolve 'dotnet-tool (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

If I add in sampleApp directory "NuGet.Config" with "&lt;add key="Local" value="..\dotnet-tool\bin\Debug" />", then restore sampleapp - "dotnet tool" works well. But if I make changes to tool, after dotnet pack (tool) and dotnet restore sampleapp - tool not updated. I have to  manually remove tool info form "C:\Users\username\.nuget\packages\" and "C:\Users\username\.nuget\packages\.tools" and then restore sampleapp.

With dnx commands was easier.

**Comment by blackdwarf** [comment] 2016-05-21 18:03
@alderic pack in this case is an operation that is analog to `publish` for an app you want to run on your server, for instance. You have to repack the tool after changes and then do a restore again for your consuming project to get the changes. You should not have to clean out your cache, however. 

With this, it seems that the issue has been solved, since the system is behaving as designed. I will go ahead and close the issue. If you feel it should be reopened, please reopen it.

**Closed by blackdwarf** 2016-05-21 18:03 UTC
Labels: question
