### ISSUE TITLE
dotnet add package reference puts Version in an element

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#5630] opened 2017-02-08 20:41 UTC
## Steps to reproduce

```
dotnet new -t lib
dotnat add package Newtonsoft.json

```
## Expected  behavior

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1"/>
  </ItemGroup>
</Project>
```

## Actual behavior

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.1</Version>
    </PackageReference>
  </ItemGroup>
</Project>
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15025
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

```

**Comment by spboyer** [comment] 2017-02-08 22:33
VS 2107 NuGet Package Manager via GUI and Console adds correctly.

```
<PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
```

**Comment by spboyer** [comment] 2017-02-08 22:35
steps to produce should be 
```
dotnet new classlib 
```

option `-t` no longer valid in `1.0.0-rc4-004771`

**Comment by livarcocc** [comment] 2017-02-08 23:14
@rohit21agrawal I have seen this issue before. We may have it already.

**Comment by rohit21agrawal** [comment] 2017-02-08 23:27
@mishra14 can you link to existing issue?

**Comment by mishra14** [comment] 2017-02-09 01:06
dupe of: https://github.com/dotnet/cli/issues/5386 and https://github.com/NuGet/Home/issues/4325

**Comment by livarcocc** [comment] 2017-02-09 01:17
Closing this one since we already have two issues tracking this.

**Closed by livarcocc** 2017-02-09 01:17 UTC
