### ISSUE TITLE
Publish .NET Framework and PCL Reference assemblies

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#191] opened 2015-11-13 20:51 UTC
Goal: Build projects (e.g. project.json) that support net451 (or later) or PCL frameworks.

We need a way to acquire the reference assemblies on any/all OSes w/o installing anything special and certainly w/o requiring a VS install on Windows.

**Comment by weshaggard** [comment] 2015-11-18 16:43
@richlander I assume this is a duplicate of https://github.com/dotnet/corefx/issues/3934. Can you provide the exact list of profiles we need?

**Comment by piotrpMSFT** [comment] 2015-11-23 21:53
@richlander, can you add more detail here? It's not clear what work needs to be done here, nor by whom. Leaving in backlog for now.

**Comment by akoeplinger** [comment] 2015-11-25 01:28
@piotrpMSFT the corresponding corefx issue https://github.com/dotnet/corefx/issues/3934 is assigned to @ericstj and rtm milestone. maybe @davidfowl can provide more details as well.

**Comment by Petermarcu** [comment] 2015-11-25 01:35
The idea here is to enable building libraries targeting the varied .NET platforms from the cli. For example, if I build a set of libraries for one nuget package that have different implementations for .NET Framework, some PCL profile, netstandard, and uwp, you should be able to compile that anywhere the cli runs.

**Comment by weshaggard** [comment] 2015-11-25 16:29
I get the basic idea but which targets do we care about? This needs to be fully spec'ed out so we know which target frameworks to produce packages for.

**Comment by piotrpMSFT** [comment] 2015-12-01 09:17
This seems like it will primarily affect NuGet + Compilers + Fx package authoring. I get the value add. Do we want to use this issue to track dotnet/CoreFx#3934 along with other affected product issues?

**Comment by ericstj** [comment] 2015-12-01 16:47
We already have all the PCL profile assemblies for PCLs targeting net45/win8/win-phone-8 and higher so I think this is just about desktop, is that correct Rich or did you have something in mind around a meta-package for the PCL profiles?

**Comment by davidfowl** [comment] 2015-12-01 16:54
@ericstj Do the PCL profile folders contain reference assemblies or empty `_._` folders?

**Comment by ericstj** [comment] 2015-12-01 16:58
We don't explicitly list out the profiles, instead we have generational reference assemblies that can be used.

**Comment by piotrpMSFT** [comment] 2017-02-08 07:22
Closing in favor of the duplicates in corefx

**Closed by piotrpMSFT** 2017-02-08 07:22 UTC
Labels: enhancement
