### ISSUE TITLE
Installation error on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by escamoteur** [dotnet/cli#3855] opened 2016-07-13 17:04 UTC
Hi,

I tried to follow your installation instructions on https://www.microsoft.com/net/core#ubuntu

But I get the following error message:

sudo apt-get install dotnet-dev-1.0.0-preview3-003180
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 dotnet-dev-1.0.0-preview3-003180 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Any idea?
Best
Thomas

**Comment by brthor** [comment] 2016-07-15 17:57
Hi @escamoteur 

Have you previously installed any of these packages?

Can you try installing `dotnet-sharedframework-microsoft.netcore.app-1.0.0` directly?

**Comment by frogstack** [comment] 2016-07-20 20:09
When I try to install `dotnet-sharedframework-microsoft.netcore.app-1.0.0` directly, I get the following error:

```
 dotnet-sharedframework-microsoft.netcore.app-1.0.0 : Depends: libicu55 (>= 55.1-1~) but it is not installable
                                                      Depends: liblttng-ust0 (>= 2.5.0) but it is not going to be installed
                                                      Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
                                                      Depends: dotnet-hostfxr-1.0.1 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I've never installed any of these packages before. Attempting to install `libicu55` directly fails with the following:

```
Package libicu55 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu55' has no installation candidate
```

**Comment by brthor** [comment] 2016-07-20 20:42
Thanks @frogstack, I try to get a repro here. This looks like perhaps the ubuntu 16.04 packages are on the 14 feed or the wrong feed got added to the machine. 

Let me see what I find

**Comment by brthor** [comment] 2016-07-20 20:59
@frogstack @escamoteur 

I've just tried this out on ubuntu 14 and confirmed that it is working as expected. 

What's weird here is that the shared framework you are installing @frogstack depends on libicu55, which is a dependency only of the ubuntu 16.04 packages.

Can you show the output of `cat /etc/apt/sources.list.d/dotnetdev.list`

**Comment by frogstack** [comment] 2016-07-20 21:01
Sure, here it is:

```
> cat /etc/apt/sources.list.d/dotnetdev.list
deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main
> 
```

**Comment by brthor** [comment] 2016-07-20 21:04
Indeed it looks like you have the ubuntu 16 feed added 

Change
`deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main`

to 

`deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main`

do `apt-get update && apt-get purge dotnet-host dotnet-hostfxr-1.0.1 dotnet-sharedframework-microsoft.netcore.app-1.0.0`

Then `apt-get install dotnet-dev-1.0.0-preview2-003121`

And you should be good to go.

**Comment by frogstack** [comment] 2016-07-20 21:12
That looks like it's solved my problem! I must have copied the wrong set of commands accidentally. Thanks for your help!

**Comment by brthor** [comment] 2016-07-20 21:12
/cc @blackdwarf For the confusion on the site.

Going to close this out for now

**Closed by brthor** 2016-07-20 21:12 UTC

**Comment by kmute90** [comment] 2016-12-14 14:39
i have the same error, but suggested solution did not solved my problem :(

**Comment by blackdwarf** [comment] 2016-12-14 15:15
@kmute90 can you share what steps did you do and what version you are trying to install?

**Comment by lukespice** [comment] 2016-12-15 23:11
I am having the same problem today on Ubuntu Server 16.04. I was able to do a successful install yesterday on Ubuntu desktop 16.04

Fresh install of Ubuntu server 16.04 VM using VirtualBox
Followed the steps as outlined on https://www.microsoft.com/net/core#linuxubuntu
Got the following error message
```
The following packages have unmet dependencies:
 dotnet-dev-1.0.0-preview2-1-003177 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.0 but it is not going to be installed
```
So I tried
`sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.1.0`

```
The following packages have unmet dependencies:
 dotnet-sharedframework-microsoft.netcore.app-1.1.0 : Depends: libicu52 (>= 52~m1-1~) but it is not installable
```

Then I tried 
`sudo apt-get install libicu52`

```
Package libicu52 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

I also tried the fix outlined above but got the same result.

**Comment by lukespice** [comment] 2016-12-16 00:22
Ignore the above comment, I am a Linux rookie and I had enabled auto updates in my installation so I was actually running 16.10.

Thanks to http://shazwazza.com/post/installing-net-core-101-on-ubuntu-1610/ for pointing me in the right direction.
