### ISSUE TITLE
Run command does not fallback to build dependency, when project name is different than the containing directory name

### ISSUE THREAD

**Issue by am11** [dotnet/cli#3040] opened 2016-05-14 21:46 UTC
## Problem Intro.

Attachment: [Archive.zip](https://github.com/dotnet/cli/files/264700/Archive.zip)

There are two solution directories `test` and `test1` in the attachment.
In `test`, there are two projects `A` (lib) and `B` (app).
Then I made a copy of solution directory `test` namely `test1`, renamed project `test1/A` to `test1/A1` and added the following in `test1/A1/project.json`:

``` diff
+  "name": "A",
+  "buildOptions": {
+    "outputName": "A"
+  },
```

i.e. making the project name (`A`) same, while changing the containing directory name (`A1`).

and changed `test1/B/project.json` as:

``` diff
-    "A": "1.0.0-*"
+    "A1": "1.0.0-*"
```

If I do not make this change (i.e. match the project directory name in dependent's PJ, although `outputName` and `name` of project `A`'s PJ in directory `A1` are set to `A`), `dotnet restore` fails (which probably should not be the case in first place? #1794)
## Steps to reproduce
- Extract `Achieve.zip`.
- Restore the packages for solution `test`: `cd test && dotnet restore`
- Run app (`B`): `cd B && dotnet run`.

Compiles `A` and `B`, runs the app and displays "Hello World". ✅ 
- Restore the packages for solution `test1`: `cd test1 && dotnet restore`
- Run app (`B`): `cd B && dotnet -v run`.

Throws: ❎ 

``` sh
Adeels-MacBook-Pro:B adeel$ dotnet -v run
Telemetry is: Enabled
Project B (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
    /Users/adeel/test1/B/bin/Debug/netcoreapp1.0/B.dll
    /Users/adeel/test1/B/bin/Debug/netcoreapp1.0/B.pdb
    /Users/adeel/test1/B/bin/Debug/netcoreapp1.0/B.deps.json
    /Users/adeel/test1/B/bin/Debug/netcoreapp1.0/B.runtimeconfig.json
Compiling B for .NETCoreApp,Version=v1.0
Running /Users/adeel/GeoIP2-dotnet/.dotnetcli/dotnet /Users/adeel/GeoIP2-dotnet/.dotnetcli/sdk/1.0.0-preview2-002752/csc.dll -noconfig @/Users/adeel/test1/B/obj/Debug/netcoreapp1.0/dotnet-compile-csc.rsp
Process ID: 81697
/Users/adeel/GeoIP2-dotnet/.dotnetcli/dotnet compile-csc @/Users/adeel/test1/B/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
/Users/adeel/test1/B/error CS0006: Metadata file '/Users/adeel/test1/A1/bin/Debug/netstandard1.4/A.dll' could not be found

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.9101110
```

It recognized the dependency project correctly, but did not compile it.
## Temporary Workaround

Explicitly build `test1/A1` before `dotnet run`'ing the `test1/B`:

``` sh
cd test1/A1
dotnet build
cd ../B
dotnet run
# now it builds and run
```
## Expected  behavior

Executing `dotnet run` in `test1/B` directory should build `test1/A1`, without the workaround (explicitly building `test1/A1` first).
## Actual behavior

`dotnet run` does not build the dependency project, as the folder name is now different. The compilation fails with:

``` sh
test1/B/error CS0006: Metadata file '/Users/adeel/test1/A1/bin/Debug/netstandard1.4/A.dll' could not be found
```
## Environment data

`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview2-002752)
> 
> Product Information:
>  Version:            1.0.0-preview2-002752
>  Commit SHA-1 hash:  b23feed7c8
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.11
>  OS Platform: Darwin
>  RID:         osx.10.11-x64

**Comment by wmathes** [comment] 2016-05-23 07:39
I might add, that this is extremely cumbersome when developing tools. 

Is there a way of debugging a tool locally? I can just dotnet run it, but I want to access the assembly of the project using the tool. I realize the EF tools are doing that, but there are a lot of comments suggesting even their approach is quite hacky and i cant get it to run locally at all. It all only seems to work once packaged which isn't ideal for debugging. When renaming the project (or rather the output) is necessary for tools to work, but the project not resolving the dependency anymore once you do...

Is this the same bug? Or is it a feature i just don't understand fully?

**Comment by jorgebay** [comment] 2016-08-10 11:24
We are getting the same error from dotnet cli. Having a project name different from the package name is very common (in our case, its Cassandra and [CassandraCsharpDriver](https://www.nuget.org/packages/CassandraCSharpDriver)).

The steps to reproduce this issue are clear on the ticket description.

**Comment by piotrpMSFT** [comment] 2016-11-10 06:45
Starting with preview3 P2P references use relative paths, so this sort of failure due to implicit P2P reference no longer exists.

**Closed by piotrpMSFT** 2016-11-10 06:45 UTC
