### ISSUE TITLE
SDK 2.1.100 installed after updating VS 2017 15.6.1

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8757] opened 2018-03-09 16:20 UTC
@Vaiune commented on [Fri Mar 09 2018](https://github.com/dotnet/core/issues/1329)

I've updated visual studio 2017 to 15.6.1 this morning.
After that i got 
```
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Prior to update I had 2.1.4 and everything was fine. 
```dotnet new react``` scaffolds the old template that doesn't use create-react-app as it should.
If I create a global.json file indicating SDK 2.1.4 then it scaffolds the correct template with CRA.

https://www.microsoft.com/net/download/Windows/build shows 2.1.4 as the latest version.

Is this supposed to happen with the update VS 2017 15.6.1?

---

@Kritner commented on [Fri Mar 09 2018](https://github.com/dotnet/core/issues/1329#issuecomment-371859833)

Ok, so not just me!

I see that I do in fact have 2.1.4 in my sdks folder, but even at root, with no global.json config, `dotnet --version` shows 2.1.100.

I unfortunately cannot confirm that it said 2.1.4 prior to the VS update.

**Comment by livarcocc** [comment] 2018-03-09 17:32
2.1.100 is the correct next version of the .NET Core SDK that shipped with 15.6.

@vaiune, it is not clear to me if the problem you are reporting is a question regarding the SDK version or some issue with the templates. Can you clarify?

**Comment by Kritner** [comment] 2018-03-09 17:50
@livarcocc is `2.1.100` a more recent version in comparison to `2.1.4`?  I had assumed this was not the case.

**Comment by livarcocc** [comment] 2018-03-09 17:54
That's correct. 2.1.100 is the latest.

**Comment by Kritner** [comment] 2018-03-09 17:58
huh... maybe that's just my misunderstanding of versioning (is this semantec versioning?).  I was under the impression the trailing zeroes were ignored (similar to a decimal), but I can't actually find any information on it.

**Comment by Vaiune** [comment] 2018-03-09 18:15
@livarcocc I’m using ‘Microsoft.DotNet.Web.Spa.ProjectTemplates’ and with the new 2.1.100 sdk, I get the old react template which is discontinued. I was playing with SPA templates and prior to update with 2.1.4 sdk all I got were React and Angular that uses the new template package. I also did confirm that with the global.json points to 2.1.4. When issued command ‘dotnet new react’, the new template is used. Without the global.json and the new sdk, the exact command uses the old template that discontinued. 
I guess this is a issue for ‘templating’ or ‘javascriptservices’ repo.

**Comment by livarcocc** [comment] 2018-03-09 18:19
Yeah, this is a problem with templates.

cc @vijayrkn @mlorbetske to comment on the template version we have on CLI 2.1.100. Branch release/2.1.1xx. Can you guys double check we have the appropriate ones? Or is this an ASP.NET issue? cc @natemcmaster @JunTaoLuo to verify the appropriate ASP.NET templates are inserted as well.

**Comment by natemcmaster** [comment] 2018-03-09 18:23
There were no changes to the bundled aspnetcore templates between 2.1.4 and 2.1.100. The correct templates are listed here: https://github.com/dotnet/cli/blob/f02eef83f710762da0a1181dee18009adb6eccac/build/DependencyVersions.props#L63

**Comment by livarcocc** [comment] 2018-03-09 18:47
Do you mean the custom `Microsoft.DotNet.Web.Spa.ProjectTemplates` template? That's not carried natively by the CLI. If a different one is being picked up by `dotnet new` based on the version of the CLI you are using, I would definitely file an issue against dotnet/templating.

If that's the case, I will also close this issue. Since the right version of the CLI is being installed by VS and the template issue belongs in a separate repo.

**Comment by Vaiune** [comment] 2018-03-09 18:51
Fair enough, I also think it is a templating issue.

**Comment by natemcmaster** [comment] 2018-03-09 18:52
@SteveSandersonMS is the right person to comment on Microsoft.DotNet.Web.Spa.ProjectTemplates. If there are issues in the template itself, that should be opened on https://github.com/aspnet/templating

**Comment by kasper3** [comment] 2018-03-09 20:22
@Kritner, yes semantic versioning https://semver.org/. These are "non-negative integers" as the spec states. 100 > 4, same rules apply in npm, same in nuget and same everywhere else.

**Comment by SteveSandersonMS** [comment] 2018-03-09 21:00
> Do you mean the custom Microsoft.DotNet.Web.Spa.ProjectTemplates template? That's not carried natively by the CLI.

It is supposed to be carried natively by the CLI. If it isn't, that's a regression we should fix.

We did ship `Microsoft.DotNet.Web.Spa.ProjectTemplates` with the .NET Core 2.0.0 SDK and should continue shipping it with 2.1.

In case you're wondering, there also used to be a different SPA template package (`Microsoft.AspNetCore.SpaTemplates`) that did not ship in the SDK - maybe that's what you were thinking of. That package was deprecated ([announcement](https://github.com/aspnet/Announcements/issues/289)).

**Comment by livarcocc** [comment] 2018-03-09 22:33
@natemcmaster again on we having potentially regressed the Spa.ProjectTemplates package.

**Comment by livarcocc** [comment] 2018-03-09 22:35
I just confirmed, we are still carrying it with version 2.0.5.

**Comment by natemcmaster** [comment] 2018-03-09 22:44
TBH I'm not 100% clear what the issue is here. Can someone clarify what is going wrong?

**Comment by rgl** [comment] 2018-03-10 12:02
For me, the confusion is with the version of dotnet core sdk that is installed by Visual Studio 15.6.1. It installs 2.1.100 whereas the latest dotnet core sdk available from https://github.com/dotnet/cli/releases is 2.1.4. It seems that a proper dotnet core sdk release was not done before releasing VS 15.6.1.

**Comment by Kritner** [comment] 2018-03-10 12:13
@kasper3 thanks! TIL! :)

**Comment by dazinator** [comment] 2018-03-10 16:33
Erm.. I accidentally just uninstalled `2.1.100`.. How do I go about re-installing it as it's not on the SDK download page..

**Comment by livarcocc** [comment] 2018-03-11 18:25
cc @leecow for the missing release.

**Comment by Petermarcu** [comment] 2018-03-14 14:57
I don't see 2.1.100 but I see 2.1.101 https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.101

**Comment by leecow** [comment] 2018-03-15 19:37
@kasper3 and @Kritner - There is a bit of conflict in the semver.org spec. While it specifies non-negative integers in one section, it also defines precedence based on ASCII sort behavior, which we know will not give the "natural" order for numbers. 

>identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.

**Comment by BlaqCox** [comment] 2018-03-26 19:42
I'm not really following what happened here. 

My dotnet --version output is **2.1.102** and the [documentation](https://docs.microsoft.com/en-us/aspnet/core/spa/react?tabs=visual-studio) here indicates that if you're using Core 2.1, then the new templates should be included, but '**dotnet new react**' generates it with the 2.0 template.

Why is the global.json file necessary and why should an issue be opened up with the template team if the documentation states the templates are bundled with 2.1?

**Comment by livarcocc** [comment] 2018-03-26 20:36
SDK <b>2.1.102</b> does not include .NET Core 2.1. The earliest version available of teh .NET Core SDK that is compatible with .NET Core 2.1 is <b>2.1.300</b> which is available as preview1 at get.dot.net.

We have since then re-worked our versioning story to align the SDK version major.minor version numbers with the runtime major.minor version numbers, but until we are past 2.1, we will have this confusion point.

**Comment by BlaqCox** [comment] 2018-03-26 20:49
Man, that is confusing.

**Comment by DeckardCain2014** [comment] 2018-05-03 10:43
But where is actually the difference between dotnet-sdk-2.1.4 and dotnet-sdk-2.1.104 ? As they are both linked in different documentation pages...
Which version is the latest and do I have to install/uninstall other packages?

**Comment by livarcocc** [comment] 2018-05-04 16:41
2.1.104 is the higher version amongst the two you mentioned above. There is not need to uninstall anything, as the SDKs all work side by side. By default, it will use the highest one available in the box.

**Closed** 2018-05-09 16:58 UTC
