### ISSUE TITLE
Building release/2.1.4xx branch using 2.1.402 SDK fails due to NU5123

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#10052] opened 2018-09-26 19:14 UTC
This showed up in source-build, fixed by [a patch](https://github.com/dotnet/source-build/blob/8e382759a35a44cb18973c8af695a9ebef5db354/patches/cli/0002-Ignore-NU5123-build-failure-with-SDK-2.1.402.patch) for `2.1.5`/`2.1.403` (context: https://github.com/dotnet/source-build/pull/791):

## Steps to reproduce
1. Clone and checkout `04e15494b` (in `release/2.1.4xx`).
1. Modify `run-build.sh`:

   ```diff
   @@ -165,7 +165,7 @@ if [[ $archlower == 'arm'* ]]; then
    fi
   
    if [ "$STAGE0_SOURCE_DIR" == "" ]; then
   -    (set -x ; "$REPOROOT/scripts/obtain/dotnet-install.sh" --version "2.1.300" --install-dir "$DOTNET_INSTALL_DIR" --architecture "$INSTALL_ARCHITECTURE" $LINUX_PORTABLE_INSTALL_ARGS)
   +    (set -x ; "$REPOROOT/scripts/obtain/dotnet-install.sh" --version "2.1.402" --install-dir "$DOTNET_INSTALL_DIR" --architecture "$INSTALL_ARCHITECTURE" $LINUX_PORTABLE_INSTALL_ARGS)
    else
        echo "Copying bootstrap cli from $STAGE0_SOURCE_DIR"
        cp -r $STAGE0_SOURCE_DIR/* "$DOTNET_INSTALL_DIR"
   ```
1. Run `./build.sh '/p:CLITargets="Prepare;Compile;Package"'` (other build commands may repro as well)

## Expected  behavior
The build succeeds.

## Actual behavior
Build fails while packing symbols with errors like:

> /opt/code/src/cli/.dotnet_stage0/x64/sdk/2.1.402/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(199,5): **error NU5123: The file 'sdk/2.1.403/Microsoft/Microsoft.NET.Build.Extensions/tools/netcoreapp2.0/Microsoft.NET.Build.Extensions.Tasks.ni.{80ded9fa-7ed2-48f3-b255-e94eb1ee3ae0}.map' path, name, or both are too long.** Your package might not work without long file path support. Please shorten the file path or file name. [/opt/code/src/cli/build/package/Symbols.csproj] [/opt/code/src/cli/build.proj]

Adding a `NoWarn` on `NU5123` lets the build pass.

## Environment data
```
#> .dotnet_stage0/x64/dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     fedora
 OS Version:  28
 OS Platform: Linux
 RID:         fedora.28-x64
 Base Path:   /home/dagood/git/cli/.dotnet_stage0/x64/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/home/dagood/git/cli/.dotnet_stage0/x64/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/home/dagood/git/cli/.dotnet_stage0/x64/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/home/dagood/git/cli/.dotnet_stage0/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/home/dagood/git/cli/.dotnet_stage0/x64/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment] 2018-09-28 17:28
@nkolev92 is this a new warning added by NuGet for 15.8?

**Comment by nkolev92** [comment] 2018-09-28 17:32
Yes, it was added in https://github.com/NuGet/NuGet.Client/pull/2243.

**Comment by livarcocc** [comment] 2018-09-28 17:43
I am going to close this issue as this is a by design warning added by NuGet and we are not seeing this in our official builds.

**Comment by dagood** [comment] 2018-09-28 17:48
You should see the failure in CI/official once you update the stage 0 tooling from 2.1.300 to 2.1.402 (or later). My understanding is that this problem prevents CLI from being able to build itself with new tooling versions, which directly impacts source-build.

CLI goes from 1 patch to 2 patches on source-build `release/2.1` if this isn't fixed.

/cc @dleeapho @dseefeld

**Comment by livarcocc** [comment] 2018-09-28 17:49
Can we just added the warning above to the no-warn list then? Put it in the official source, instead of in a patch?

**Comment by dagood** [comment] 2018-09-28 17:50
Yep, that would work.

**Comment by rrelyea** [comment] 2018-09-28 17:55
wow. that is a crazy long filename. can you fix that instead?
otherwise, you may hit restore problems on some user machines.

**Comment by dagood** [comment] 2018-09-28 17:58
I'm pretty sure that package is a symbol package, never restored. `Microsoft.NET.Build.Extensions.Tasks.ni.{80ded9fa-7ed2-48f3-b255-e94eb1ee3ae0}.map` for example is symbol information generated during crossgen.

**Closed** 2018-10-05 23:15 UTC
Labels: Area-Infrastructure
