### ISSUE TITLE
Dotnet sln add fails to properly add F# project files on OSX

### ISSUE THREAD

**Issue by TOTBWF** [dotnet/cli#6909] opened 2017-06-16 17:13 UTC
## Steps to reproduce
```
mkdir src
cd src
dotnet new console -lang f#
cd ..
dotnet new sln
dotnet sln add src/<Projectname>.fsproj
dotnet restore && dotnet build
```

## Expected  behavior
The project would be restored and built

## Actual behavior
error MSB4025: The project file could not be loaded. Could not find file '<PathToProject>/src/<ProjectName>.fsproj.metaproj'

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)
```
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

## Workarounds
In the solution file, replace the all backslashes in the path to the project file with forward slashes

**Comment by enricosada** [comment] 2017-06-16 22:41
dupe of https://github.com/dotnet/cli/issues/6723

**Comment by livarcocc** [comment] 2017-06-20 22:54
Yep. Seems like it. Closing this one.

**Closed by livarcocc** 2017-06-20 22:54 UTC
