### ISSUE TITLE
dotnet build+publish and dotnet publish does not produce the same result - fails when running as unprivileged user in Docker container

### ISSUE THREAD

**Issue by Lybecker** [dotnet/cli#11701] opened 2019-07-02 10:49 UTC
When the Dockerfile has both the steps `dotnet build` and `dotnet publish`, then the error `realpath(): Permission denied` appears at runtime when running as unprivileged user

## Steps to reproduce

1. Create simple webapp with command 
`dotnet new webapp -o mywebapp --no-https` 
2. Use Dockerfile from here: 
https://github.com/Lybecker/dotnetclibug/blob/master/Dockerfile
3. Uncomment line 15
`RUN dotnet build "mywebapp.csproj" -c Release -o /app`
4. Build the container 
`docker build -t mywebapp:issue .`
5. Execute the container 
`docker run –rm mywebapp:issue`

The problem only appears, when uncomment line 15

The issue has been reproduced have reproduced the issue on Windows and Linux.

## Expected  behavior
The dotnet kestrel process starts without any errors.

## Actual behavior
`docker run --rm mywebapp:issue`
_realpath(): Permission denied
realpath(): Permission denied
realpath(): Permission denied_
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {ea673121-40e4-4712-9072-58e595942f1d} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:8080
Application started. Press Ctrl+C to shut down.

## Environment data
Reproduced on Linux and Windows:

**Linux**
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Windows**
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment] 2019-07-02 16:30
@peterhuene can you take a first look at this?

**Comment by peterhuene** [comment] 2019-07-02 19:08
I haven't looked at it yet, but I suspect the errors might be coming from the file system watcher (I see calls to `realpath` in the framework there) used by the ASP.NET application and thus not a CLI issue as the application started by `dotnet run`.  I'll move the issue if I can confirm my suspicion.

**Comment by peterhuene** [comment] 2019-07-02 22:13
So my hunch was wrong.  It's not coming from the framework but from [the host PAL](https://github.com/dotnet/core-setup/blob/832f8250b5986028594c0db47b4e1cb62915c15b/src/corehost/common/pal.unix.cpp#L733).

Looks like there's an [core-setup issue here](https://github.com/dotnet/core-setup/issues/4038) that hasn't received any attention lately.  I'm going to close this as a duplicate of the core-setup issue and try to get some traction going on that issue.

**Closed by peterhuene** 2019-07-02 22:13 UTC

**Comment by peterhuene** [comment] 2019-07-02 22:24
While it's the host that's the cause of the error, I want to explore why sharing the build and publish output would introduce the error.

Without the build step:

```
$ docker run -it --rm --entrypoint /bin/bash mywebapp:issue
app@78f5543f0087:/app$ ls -l
total 324
-rw-r--r-- 1 root root    146 Jul  2 22:00 appsettings.Development.json
-rw-r--r-- 1 root root    105 Jul  2 22:00 appsettings.json
-rw-r--r-- 1 root root  59904 Jul  2 22:16 mywebapp.Views.dll
-rw-r--r-- 1 root root   3908 Jul  2 22:16 mywebapp.Views.pdb
-rw-r--r-- 1 root root 228903 Jul  2 22:16 mywebapp.deps.json
-rw-r--r-- 1 root root   8704 Jul  2 22:16 mywebapp.dll
-rw-r--r-- 1 root root   1604 Jul  2 22:16 mywebapp.pdb
-rw-r--r-- 1 root root    213 Jul  2 22:16 mywebapp.runtimeconfig.json
-rw-r--r-- 1 root root    484 Jul  2 22:16 web.config
drwxr-xr-x 5 root root   4096 Jul  2 22:16 wwwroot
app@78f5543f0087:/app$ docker exec mywebapp.dll
bash: docker: command not found
app@78f5543f0087:/app$ dotnet exec mywebapp.dll
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {ed3b83f3-c60e-4ad0-8971-e435ea4dc2eb} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:8080
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
app@78f5543f0087:/app$ exit
```

With the build step:
```
$ docker run -it --rm --entrypoint /bin/bash mywebapp:issue
app@0b27c97e5f89:/app$ ls -l
total 328
-rw-r--r-- 1 root root    146 Jul  2 22:00 appsettings.Development.json
-rw-r--r-- 1 root root    105 Jul  2 22:00 appsettings.json
-rw-r--r-- 1 root root  59904 Jul  2 22:01 mywebapp.Views.dll
-rw-r--r-- 1 root root   3908 Jul  2 22:01 mywebapp.Views.pdb
-rw-r--r-- 1 root root 228903 Jul  2 22:01 mywebapp.deps.json
-rw-r--r-- 1 root root   8704 Jul  2 22:01 mywebapp.dll
-rw-r--r-- 1 root root   1604 Jul  2 22:01 mywebapp.pdb
-rw-r--r-- 1 root root    190 Jul  2 22:01 mywebapp.runtimeconfig.dev.json
-rw-r--r-- 1 root root    213 Jul  2 22:01 mywebapp.runtimeconfig.json
-rw-r--r-- 1 root root    484 Jul  2 22:01 web.config
drwxr-xr-x 5 root root   4096 Jul  2 22:01 wwwroot
app@0b27c97e5f89:/app$ dotnet exec mywebapp.dll
realpath(): Permission denied
realpath(): Permission denied
realpath(): Permission denied
: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {a83286df-40a5-433d-9bd5-b75e52fdc660} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:8080
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
app@0b27c97e5f89:/app$ exit
```

There must be something that the host is probing.  I'll see if I can strace it.

**Comment by peterhuene** [comment] 2019-07-02 22:32
I've figured it out.  It's the `mywebapp.runtimeconfig.json` that got generated from the build:

```
app@81f48bafa73d:/app$ cat mywebapp.runtimeconfig.dev.json
{
  "runtimeOptions": {
    "additionalProbingPaths": [
      "/root/.dotnet/store/|arch|/|tfm|",
      "/root/.nuget/packages",
      "/usr/share/dotnet/sdk/NuGetFallbackFolder"
    ]
  }
```

There are paths there that cause the host to probe locations it doesn't have permissions to when running as non-root.

As a workaround to the host emitting the error messages, I would add this as a post-publish step to your `Dockerfile`:

```
RUN rm /app/mywebapp.runtimeconfig.dev.json
```

**Comment by Lybecker** [comment] 2019-07-03 07:40
Thanks @peterhuene
