### ISSUE TITLE
Update dotnet new web to be the Empty web template from VS

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#3619] opened 2016-06-16 20:12 UTC
Currently the dotnet new web template is creating the `Individual Auth` version of the web template from One ASP.NET.

After discussing with @DamianEdwards we feel that it would be a better fit to have the Empty web template in dotnet new.

We are making some late changes in the Empty web template in aspnet/templates. Once we have the final content @mlorbetske or @phenning will reply back here with the final content. Hopefully that will happen today or early tomorrow.

cc @ajaybhargavb @DamianEdwards

**Comment by blackdwarf** [comment] 2016-07-28 06:32
Dupe of #3934

**Closed by blackdwarf** 2016-07-28 06:32 UTC
