### ISSUE TITLE
Ubuntu 14.04/Mint 17 Installation is failing

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/cli#5772] opened 2017-02-19 22:29 UTC
## Steps to reproduce
- Go to https://github.com/dotnet/cli#ubuntu-installers
- Install the installers in order on a clean Mint 17 installation
- Last installer fails to run because of missing dependency. 

## Expected  behavior
Should work and rc4 gets installed on Mint 17

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/568272/23107293/80a67020-f6c8-11e6-9903-6ac1a6f9a715.png)

## Environment data
`dotnet --info` output:
Doesn't run as SDK never gets installed. Only the 1.0.1 Shared Host gets run.

**Comment by shawnwildermuth** [comment] 2017-02-19 22:30
The 1.0.1 Shared Framework is installed by step 2, don't think 1.0.4 is available.

**Comment by gkhanna79** [comment] 2017-02-22 16:46
Isn't this because 1.0.4 has not been released and thus, its packages are not available?

CC @leecow

**Comment by leecow** [comment] 2017-02-22 18:57
Looks like the sharedframework installers at https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/ are all 1.0.3. https://github.com/dotnet/core-setup strongly suggests that daily builds of the sharedframework are being pushed to latest but this obviously isn't the case.

**Comment by gkhanna79** [comment] 2017-02-22 19:28
Daily build installers are at https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/.

1.0.4 installers are at https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.4/.

There are no daily builds of release branches.

**Comment by leecow** [comment] 2017-02-22 19:40
Alright - The release columns on https://github.com/dotnet/core-setup report 1.0.4 and 1.1.1 which haven't happened yet.

**Comment by gkhanna79** [comment] 2017-02-22 19:41
Yes, this is what we discussed when the table was being done - some of the release will show here _before_ they get released.

**Comment by shawnwildermuth** [comment] 2017-02-22 23:23
So I'm confused, is any of this a help on getting it running on Linux or is this just a discussion on how to handle releases long-term (with the core-setup discussion which seems to be about 2.0, not the 1.1 RC4 Updates.

**Comment by TrevorNewsome** [comment] 2017-03-18 11:18
Has this been resolve do you know?

**Comment by TrevorNewsome** [comment] 2017-03-18 12:00
Hi Guys, I found a solution to this, unfortunately not my solution, rather someone else's, but I have verified it as working and has solved my issue on Mint 18.

http://hudosvibe.net/post/install-.net-core-on-mint-18-or-elementary-os

Hope this helps.
Trev

**Comment by livarcocc** [comment] 2017-03-18 17:06
@gkhanna79 according to the link above the issue seems to be installing the shared framework. Can you take a look?

**Comment by gkhanna79** [comment] 2017-03-29 19:51
IIUC, It seems like Mint 17/18/Elementary have different dependencies than U14.04 (which is supported for 1.0.X). Once they are in place, installation works as expected. 

I think documenting these issues is the right step ahead - we cannot build 1.0.X with different dependencies than what we shipped for.

@leecow can you please capture this on dotnet/core?

**Comment by leecow** [comment] 2017-03-29 20:41
Interesting, I can run both SDK 1.0.0-preview2-003131 with SharedFX 1.0.4/1.1.1 and SDK 1.0.1 with SharedFX 1.0.1 without libicu52.

````
$apt list | grep libicu

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libicu-dev/xenial-updates,xenial-security 55.1-7ubuntu0.1 amd64
libicu4j-4.4-java/xenial,xenial 4.4.2.2-2 all
libicu4j-49-java/xenial,xenial 49.1-2 all
libicu4j-java/xenial,xenial 4.2.1.1-3 all
libicu55/xenial-updates,xenial-security 55.1-7ubuntu0.1 amd64 [upgradable from: 55.1-7]
libicu55-dbg/xenial-updates,xenial-security 55.1-7ubuntu0.1 amd64
```

Seems like there's something else going on in the failure cases.

**Comment by livarcocc** [comment] 2017-05-04 18:41
Moving this over to core-setup, since the issue is about the shared framework.

**Comment by livarcocc** [comment] 2017-05-04 18:41
This issue was moved to dotnet/core-setup#2284

**Closed by livarcocc** 2017-05-04 18:41 UTC
