### ISSUE TITLE
Passing parameters with semicolon in msbuild

### ISSUE THREAD

**Issue by iskiselev** [dotnet/cli#10282] opened 2018-11-06 05:12 UTC
There is no way to pass properties with semicolon inside msbuild using dotnet CLI.
Consider sample projectfile:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Main" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">    
  <PropertyGroup>
    <build_configurations>test1;test2;test3</build_configurations>
  </PropertyGroup>    
  <ItemGroup>
    <BuildConfigurations Include="$(build_configurations)" />
  </ItemGroup>    
  <Target Name="Main">    
    <Message Text="Running with args: %(BuildConfigurations.Identity)" Importance="High" />
  </Target>
</Project>
```
We can pass semicolon-separated properties using call directly to msbuild: `msbuild test.csproj /p:build_configurations="test5;test6;test7"`, but it is not possible with dotnet CLI.

## Steps to reproduce
1. Save sample project file as test.csproj
2. Run `dotnet msbuild test.csproj /p:build_configurations="test5;test6;test7"`

## Expected  behavior
Output:
  Running with args: test5
  Running with args: test6
  Running with args: test7

## Actual behavior
Output: 
MSBUILD : error MSB1006: Property is not valid.
Switch: test6

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

For reference:
https://stackoverflow.com/questions/6051054/how-do-i-pass-a-property-to-msbuild-via-command-line-that-could-be-parsed-into-a
Also, this issue may be a root cause for: NuGet/Home#7413

**Comment by livarcocc** [comment] 2018-11-08 17:36
@peterhuene can you take a look at this? Is this the same as https://github.com/dotnet/cli/issues/7791?

**Comment by peterhuene** [comment] 2018-11-08 18:42
Hi @iskiselev,

This is a duplicate of #7791.  To pass semicolons through to MSBuild, the property value needs to have quotes around it.  However, your shell will likely remove any quotes when passing the value through to `dotnet`, so they need to be escaped for `dotnet` to pass them to MSBuild, which ultimate is the  program responsible for parsing the property option.

See https://github.com/dotnet/cli/issues/7791#issuecomment-393756980 for instructions of how to escape the quotes for most Linux shells and Windows' command prompt.

Thank you.

**Closed by peterhuene** 2018-11-08 18:42 UTC
