### ISSUE TITLE
[dotnet pack] Packaging a standalone app does not include the runtimeconfig.json settings

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2432] opened 2016-04-12 18:27 UTC
## Steps to reproduce

dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002349"
    }
  },
  "runtimes" : {
     "osx.10.11-x64": {}
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
dotnet restore
dotnet pack
## Expected  behavior

The app.runtimeconfig.json file should be packaged in the nupkg package.  The contents of the runtimeconfig.json should be:
{
  "runtimeOptions": {}
}
## Actual behavior

Pack succeeds but only the app.dll is placed in the nupkg lib/netcoreapp.1.0/ directory.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
[project.json.txt](https://github.com/dotnet/cli/files/215664/project.json.txt)

**Comment by piotrpMSFT** [comment] 2016-11-10 05:08
dupe of https://github.com/NuGet/Home/issues/3878

**Closed by piotrpMSFT** 2016-11-10 05:08 UTC
Labels: nuget
