### ISSUE TITLE
dotnet publish selects rid'd assets when publishing for Desktop

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#3350] opened 2016-06-02 18:35 UTC
## Steps to reproduce

```
Do the following on Unix:

> git clone https://github.com/JunTaoLuo/RuntimeServiceOnMono
> dotnet restore
> dotnet publish -f net451
```
## Expected  behavior

The version of `System.Runtime.InteropServices.RuntimeInformation.dll` that is published is the net45 version from the project.json without a rid:

```
      "System.Runtime.InteropServices.RuntimeInformation/4.0.0-rc3-24202-00": {
        "type": "package",
        "compile": {
          "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll": {}
        },
        "runtime": {
          "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll": {}
        },
```
## Actual behavior

The asset selected is in unix one listed in the runtime targets section of the `project.lock.json` additionally, dotnet-restore spits the following message:

```
Publishing RuntimeServiceOnMono for .NETFramework,Version=v4.5.1/ubuntu.14.04-x64
```

Note the inclusion of a RID in the message.

@ericstj and I looked into this a little and it looks like one issue maybe the code [here](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L427) which forces a RID even if one was not specified which is not correct when targeting desktop. 
## Environment data

```
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by ellismg** [comment] 2016-06-02 18:36
@anurse, Eric and I really aren't sure where this goes, but he thought you might understand the context better.  This is blocking us from making progress on https://github.com/dotnet/corefx/issues/9012 since we could consider having the desktop asset do light up when on Mono, if it's not even getting deployed, we have a world of problems.

**Comment by anurse** [comment] 2016-06-02 19:00
We do always select a RID when publishing for desktop because desktop does not support fully portable apps (since we can't hook native asset resolution). So we always have to do "half-portable" apps where we select a specific set of native assets.

Is the issue that there is a `runtimes/[rid]/lib/netstandard/...` AND a `lib/net45/...` and we're picking the first one instead of the second one on `net45`? If so, that definitely sounds like a bug to be resolved.

**Comment by ellismg** [comment] 2016-06-02 19:09
Here's the relevant portion of the `project.lock.json`

```
  "targets": {
    ".NETFramework,Version=v4.5.1": {
      "Microsoft.NETCore.Platforms/1.0.1-rc3-24202-00": {
        "type": "package",
        "compile": {
          "lib/netstandard1.0/_._": {}
        },
        "runtime": {
          "lib/netstandard1.0/_._": {}
        }
      },
      "System.Runtime.InteropServices.RuntimeInformation/4.0.0-rc3-24202-00": {
        "type": "package",
        "compile": {
          "ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll": {}
        },
        "runtime": {
          "lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll": {}
        },
        "runtimeTargets": {
          "runtimes/unix/lib/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll": {
            "assetType": "runtime",
            "rid": "unix"
          },
          "runtimes/win/lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll": {
            "assetType": "runtime",
            "rid": "win"
          }
        }
      }
    }
  },
```

The asset that is being selected is `runtimes/unix/lib/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll`

**Comment by BrennanConroy** [comment] 2016-06-02 19:17
If it were to choose the net45 one then IsPlatform() would be wrong since it's hard coded to Windows

**Comment by ericstj** [comment] 2016-06-02 19:38
We're trying to get clarity on what the expected behavior is here so that we know what we'd need to do in the packages if we wanted to try to better suppport mono.  Today none of our packages expect to resolve a net* TFM with anything but a windows RID.  All packages today duplicate the net* assets in the runtimes/win/net* folder whenever any runtime specific asset is provided so that we guard against folks supplying a valid RID with a desktop project (for more details see https://github.com/dotnet/corefx/pull/8072).  If folks think that a desktop project and UNIX RID is a valid combination then we'll need to further guard against this by copying the net4x asset into all RID folders.  Lets call this issue A.  Now issue A will cause lots of problems with this scenario end-to-end because it means folks will be getting standalone implementations instead of facades and things like Type-not-equal-to-Type will ensue.

Now if we want to support mono in our desktop assemblies we'll still need to come up with some runtime-lightup solution that can do the right thing when running in mono.  Lets call this issue B.

No matter what we'd need to fix Issue B if we want to make RuntimeInformation work on mono.

We're trying to decide if Issue A should also be fixed, or is this a problem in the CLI?

**Comment by piotrpMSFT** [comment] 2016-06-14 17:19
Moving to preview3 so folks have time to identify the appropriate design.

**Comment by livarcocc** [comment] 2019-05-10 18:26
Closing as this is a really old issue and we have changed this space considerably. If this is still a problem, please file a new issue with new repro steps for us to investigate further.

**Closed by livarcocc** 2019-05-10 18:26 UTC
