### ISSUE TITLE
dotnet store fails with NRE when referencing Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#9121] opened 2018-04-23 16:40 UTC
## Steps to reproduce
1. 
```
cat .\rs.csproj

<Project Sdk="Microsoft.NET.Sdk"><ItemGroup>
<PackageReference Include="Microsoft.AspNetCore.AzureAppServices.HostingStartup" Version="2.1.0-preview1-final" />
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />
</ItemGroup></Project>
```
2.
```
dotnet store -f netcoreapp2.1 --manifest .\rs.csproj -r win7-x64 --skip-optimization

Microsoft (R) Build Engine version 15.7.145.53551 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for D:\temp\store2\rs.csproj...
  Restoring packages for D:\temp\store2\rs.csproj...
  Generating MSBuild file C:\Users\pakrymet\AppData\Local\Temp\jxnhscwe.2od\Microsoft.AspNetCore.AzureAppServices.HostingStartup_2.1.0-preview2-final\rs.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\pakrymet\AppData\Local\Temp\jxnhscwe.2od\Microsoft.AspNetCore.AzureAppServices.HostingStartup_2.1.0-preview2-final\rs.csproj.nuget.g.targets.
  Restore completed in 829.99 ms for D:\temp\store2\rs.csproj.
  Generating MSBuild file C:\Users\pakrymet\AppData\Local\Temp\jxnhscwe.2od\Microsoft.AspNetCore.App_2.1.0-preview2-final\rs.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\pakrymet\AppData\Local\Temp\jxnhscwe.2od\Microsoft.AspNetCore.App_2.1.0-preview2-final\rs.csproj.nuget.g.targets.
  Restore completed in 2.35 sec for D:\temp\store2\rs.csproj.
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: The "FilterResolvedFiles" task failed unexpectedly. [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTransitivePackagesList(LockFileTarget lockFileTarget, LockFileTargetLibrary package, IDictionary`2 libraryLookup) [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.GetTransitiveList(String package) [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FilterResolvedFiles.ExecuteCore() [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\temp\store2\rs.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(426,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\temp\store2\rs.csproj]
```

## Expected  behavior

Store is generated that excludes assets that exist in Microsoft.AspNetCore.app

## Actual behavior

Crashes with NRE

## Environment data
`dotnet --info` output:

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\

Host (useful for support):
  Version: 2.1.0-preview3-26413-05
  Commit:  967b9806b2

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.1-preview-007118 [C:\Program Files\dotnet\sdk]
  2.1.1 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4-preview-007237 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007328 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007480 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007517 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008367 [C:\Users\pakrymet\.dotnet\x64\sdk]
  2.1.300-preview2-008528 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-30331 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-30558 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview3-32251 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview1-34003 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-30331 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-30558 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview3-32251 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview1-34003 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.2-servicing-25728-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26313-01 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26404-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26413-05 [C:\Users\pakrymet\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26413-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2018-04-23 22:18
I believe this may have been fixed already by @nguerrera through https://github.com/dotnet/sdk/pull/2159. I will try it out in the next ProdCon build.

**Comment by livarcocc** [comment] 2018-04-24 18:54
This still reproes with the latest prodcon build.

**Comment by nguerrera** [comment] 2018-04-24 23:29
The problem is here:

https://github.com/dotnet/sdk/blob/cfe8ff3c4e51c473ae75ca32d1c7a62043e96990/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ComposeStore.targets#L455

`store` targets are assuming that the platform package will have IsImplicitlyDefined=true metadata, but this isn't true for Microsoft.AspNetCore.App.

Workaround: set IsImplicitlyDefined=true
```diff
-<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" =/>
+<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" IsImplicitlyDefined="true" />
```

It may also work to remove the Version and use Sdk="Microsoft.NET.Sdk.Web" to set it, but I haven't tried that.

**Comment by livarcocc** [comment] 2018-04-25 20:30
@nguerrera  is right. Following his sugestions, this project worked for me:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.AzureAppServices.HostingStartup" Version="2.1.0-preview1-final" />
        <PackageReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
```

I am going to close this issue. If using the web sdk, where the package is marked appropriately, is not possible, we can consider explicitly calling out the `Microsoft.AspNetCore.App` package as Implicitly defined, but I am not too keen on that approach.

**Closed by livarcocc** 2018-04-25 20:30 UTC
Labels: Blocking-RTM
