### ISSUE TITLE
`dotnet build /p:myproperty=value`  not always set property and no `dotnet run /p:property=value`

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#10480] opened 2018-12-17 05:23 UTC
## Steps to reproduce
1. create a console project 
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition=" '$(XXX)' == '1'">X1</DefineConstants>
    <DefineConstants Condition=" '$(XXX)' == '2'">X2</DefineConstants>
    <DefineConstants Condition=" '$(XXX)' == '3'">X3</DefineConstants>
  </PropertyGroup>
  <Target Name="LogMyX" BeforeTargets="Build">
    <Message Importance="high" Text="'MyLogX $(XXX)'" />
  </Target>
  <Target Name="LogMyXX" AfterTargets="Build">
    <Message Importance="high" Text="'MyLogX $(XXX)'" />
  </Target>
</Project>
```
2. create a .cs file 
```C#
class Program
    {
        static void Main(string[] args)
        {
#if X1 
            Console.WriteLine("Hello X1!");
#elif X2
            Console.WriteLine("Hello X2!");
#elif X3
            Console.WriteLine("Hello X3!");
#endif
        }
    }
```
## Expected  behavior
`dotnet build /p:xxx=1`  =>compile log:"MyLogX 1"=>(run)  => "Hello X1"
`dotnet build /p:xxx=2`  =>compile log:"MyLogX 2"=>(run)  => "Hello X2"
`dotnet build /p:xxx=3`  =>compile log:"MyLogX 3"=>(run)  => "Hello X3"

## Actual behavior
`dotnet build /p:xxx=1`  =>compile log:"MyLogX 1"=>(run)  => "Hello X1"
`dotnet build /p:xxx=2`  =>compile log:"MyLogX 2"=>(run)  => "Hello X1"
`dotnet build /p:xxx=3`  =>compile log:"MyLogX 3"=>(run)  => "Hello X1"

**I must use `dotnet clean` before `dotnet build`  or save the csproj file again**

and I can not use `dotnet run /p:xxx=1`

## Environment data
`dotnet --info` output:

```
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.502
 Commit:    c74ce8f29f

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment] 2018-12-17 16:34
I think we might have a bug already for these not affecting incremental builds.

@nguerrera @rainersigwald would you know?

**Comment by rainersigwald** [comment] 2018-12-17 16:40
There's no general solution to "property changes don't cause rebuilds" but this specific case should be fixed in MSBuild 16/.NET Core SDK 3.0 builds. https://github.com/Microsoft/msbuild/issues/3350 also has a workaround you could apply today if interested.

**Comment by rainersigwald** [comment] 2018-12-17 16:40
Duplicate of https://github.com/Microsoft/msbuild/issues/3350

**Closed by rainersigwald** 2018-12-17 16:40 UTC
