### ISSUE TITLE
dotnet publish is not copying files to the correct location

### ISSUE THREAD

**Issue by txchen** [dotnet/cli#5947] opened 2017-03-07 22:46 UTC
## Steps to reproduce

```
project structure:
root.sln
  |- src
       |- abc
             |- abc.csproj
```

run `dotnet publish src/abc/abc.csproj -o publish -c Release` under {projectRoot}

## Expected  behavior

the built files would be bin placed to {projectRoot}/publish/, just like previous dotnet cli versions' behavior (project.json, non-csproj). 

## Actual behavior

Files are placed to `{projectRoot}/src/abc/publish/`, and the cli is not printing this dir to stdout. 

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

```
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by livarcocc** [comment] 2017-03-08 09:27
@eerhardt I think I remember some discussion about this way back when. Do you recall or have the issue where we discussed this handy?

**Comment by eerhardt** [comment] 2017-03-08 16:31
Dupe of https://github.com/dotnet/cli/issues/4765

**Closed by eerhardt** 2017-03-08 16:31 UTC
