### ISSUE TITLE
Build with globbing should respect project dependencies

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#2639] opened 2016-04-22 15:21 UTC
## Steps to reproduce

Project layout:
```
global.json
src/project_a/project.json
src/project_a/ClassA.cs
src/project_b/project.json
src/project_b/ClassB.cs
```

Precondition:
Project A depends on Project B

Commands:
```
dotnet restore
dotnet build **/project.json
```

## Expected  behavior

Project build order:
* Project B
* Project A

## Actual behavior

Project build order:
* Project A
* Project B

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002457)

Product Information:
 Version:     1.0.0-rc2-002457
 Commit Sha:  d06418509d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by fubar-coder** [comment] 2016-04-25 14:46
This problem is related to issue #2677. My example is incomplete. The package name must be different from the package folder name, e.g. `test.project_a` for the project name, and `project_a` for the project folder name.

**Comment by piotrpMSFT** [comment] 2016-04-25 23:47
There is an incoming feature #2574 that will allow you to specify multiple project.json's for a single build operation. This is a dupe of that feature.

**Closed by piotrpMSFT** 2016-04-25 23:47 UTC

**Comment by chwarr** [comment] 2016-11-08 23:10
FWIW, I'm still seeing this behavior with a more recent `dotnet`:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

If I use a command line like the following, I can get it to work:

```
dotnet build src/firstdep/project.json src/seconddep/project.json **/project.json
```

I assume that no action will be taken so that time can be spent instead on the MSBuild work. That's OK with me for now.
