### ISSUE TITLE
Update MSBuild to latest 

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#5283] opened 2017-01-11 21:22 UTC
Update MSBuild to latest which does not reference 1.1 NetCore.App packages

@rainersigwald

**Comment by rainersigwald** [comment] 2017-01-11 21:24
Dupe of https://github.com/dotnet/cli/issues/5263#issuecomment-271958611 ? In any case, please use `15.1.0-preview-000517-01`

**Comment by piotrpMSFT** [comment] 2017-01-11 21:26
We merged #5263 last night with latest MSBuild that did not pull in 1.1 binaries. Let's use this to track the yet-newer msbuild :)

**Closed** 2017-01-18 08:04 UTC
