### ISSUE TITLE
dotnet restore with basic authentication failing

### ISSUE THREAD

**Issue by simon-hardy** [dotnet/cli#2510] opened 2016-04-14 22:02 UTC
## Steps to reproduce

Ubuntu 14.04 container running on docker in Digital Ocean

Followed https://dotnet.github.io/getting-started/

Nexus Nuget feed with Basic Authentication enabled

Added feeds to Nuget.config with nuget add source & nuget setapikey.
## Expected  behavior

Manually running nuget 3.3.0 authenticates correctly, but:
## Actual behavior

dotnet restore ./project.json

gives

log  : Response status code does not indicate success: 401 (Unauthorized).

Detailed trace:

error:   Response status code does not indicate success: 401 (Unauthorized).
trace: System.AggregateException: One or more errors occurred. (Failed to retrieve information from remote source 'http://subdomain.domain.com/repository/nuget.org-proxy/FindPackagesById()?id='MRAM.ServiceFramework''.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information from remote source 'http://subdomain.domain.com/repository/nuget.org-proxy/FindPackagesById()?id='MRAM.ServiceFramework''. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
trace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
trace:    at NuGet.Protocol.HttpSource.<GetAsync>d__16.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<FindPackagesByIdAsyncCore>d__23.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<FindPackagesByIdAsyncCore>d__23.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<GetAllVersionsAsync>d__19.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<>c__DisplayClass15_1.<<FindLibrary>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibrary>d__15.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryByVersion>d__14.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryMatch>d__11.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryEntry>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__19.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<TryRestore>d__14.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__11.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.Main(String[] args)
trace: ---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information from remote source 'http://subdomain.domain.com/repository/nuget.org-proxy/FindPackagesById()?id='MRAM.ServiceFramework''. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
trace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
trace:    at NuGet.Protocol.HttpSource.<GetAsync>d__16.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<FindPackagesByIdAsyncCore>d__23.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<FindPackagesByIdAsyncCore>d__23.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResource.<GetAllVersionsAsync>d__19.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<>c__DisplayClass15_1.<<FindLibrary>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibrary>d__15.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryByVersion>d__14.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryMatch>d__11.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryEntry>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__19.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<TryRestore>d__14.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__11.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()<---
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-001793)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package

**Comment by Petermarcu** [comment] 2016-04-14 23:12
@yishaigalatzer , Can you take a look at confirm what needs to happen here?

**Comment by yishaigalatzer** [comment] 2016-04-14 23:14
Yes, this was fixed already in 4.3.2, but wasn't merged yet into the CLI.

**Comment by blackdwarf** [comment] 2016-04-15 04:44
Should we close this?

**Comment by yishaigalatzer** [comment] 2016-04-15 04:51
After we merge

Sent from Outlook Mobile<https://aka.ms/xp9y6l>



On Thu, Apr 14, 2016 at 9:44 PM -0700, "Zlatko Knezevic" <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we close this?

-

**Comment by simon-hardy** [comment] 2016-04-15 06:53
@yishaigalatzer, any guidance on a likely time-frame for the merge to happen? or any workaround you know of in the meantime?

**Comment by eerhardt** [comment] 2016-04-15 15:17
We've taken NuGet v3.5.0-beta-1160 in the latest CLI (CLI version 1.0.0-rc2-002392).

The issue report was using .NET Command Line Tools (1.0.0-beta-001793), which was a while ago.

**Comment by blackdwarf** [comment] 2016-04-15 15:27
@simon-hardy can you try with latest and see if this still repros?

**Comment by simon-hardy** [comment] 2016-04-15 15:53
@blackdwarf @eerhardt still get a similar error:

error: Failed to retrieve information from remote source 'http://configmanagement.xxx.com:8081/repository/nuget.org-proxy/FindPackagesById()?id='System.Linq''.
error: Response status code does not indicate success: 401 (Unauthorized).

**Comment by yishaigalatzer** [comment] 2016-04-15 15:57
@simon-hardy yes because it wasn't integrated yet into the CLI and hence this bug should stay open until it does. You can use nuget.exe 3.4.2 in the meantime. The root cause is a bug in the nexus server that the new code doesn't have a hack to work around with.

**Comment by simon-hardy** [comment] 2016-04-15 16:00
@yishaigalatzer ok you guys need to get on the same page as @eerhardt is indicating the RC2 CLI has nuget.exe 3.5.0 integrated...

**Comment by eerhardt** [comment] 2016-04-15 16:10
@yishaigalatzer - can you elaborate on which "merge" needs to happen? The way I read your response is that the CLI needs to merge a new NuGet build. But we have the latest NuGet build.

**Comment by yishaigalatzer** [comment] 2016-04-15 16:23
@simon-hardy @eerhardt you are both correct 

@eerhardt is correct that he has the latest 3.5-Beta build in the CLI
The fixes are in 3.5-RC (or the nuget dev branch) and 3.4.3 branch that is ahead of 3.5-Beta as 3.5-Beta was frozen in escrow and 3.4.3 had patches applied.

We are working on approving a merge from 3.5-RC (basically renaming the branch to 3.5-Beta) where at that point there will be a newer build that the CLI can take.

Hopefully this clarifies the state of affairs.

**Comment by deathrowe** [comment] 2016-04-19 19:49
I'm still hitting this issue with version 1.0.0-rc2-002427. I have nuget version 3.3.0.212 as well. I also noticed that 'dotnet restore' will even try to hit my diabledPackageSources.

**Comment by rrelyea** [comment] 2016-04-19 20:26
Included with the .NET CLI binaries are some NuGet binaries...
The last build we integrated into .NET CLI was 3.5.0-beta-1178. 
That build of NuGet should contain all fixes from our public 3.4.2 release.
Please check your version of NuGet components in the CLI build you have.

**Comment by deathrowe** [comment] 2016-04-19 21:09
I'm assuming you're talking about any of the NuGet.*.dll files from the /sdk/1.0.0-rc2-002427/ directory? I tried looking at the info for a couple of the files and I don't see any versioning. Is there a command I can run? I'm running on the latest OS X if that makes a difference

**Comment by rrelyea** [comment] 2016-04-19 21:12
This may be able to tell you the version:
    corerun nuget.commandline.xplat.dll --version

**Comment by deathrowe** [comment] 2016-04-20 03:17
Unfortunately, that command does not work for me. I get: 'Could not get full path: No such file or directory'

**Comment by patrickjamesbarry** [comment] 2016-05-04 14:24
I am on a Mac, running .NET Command Line Tools (1.0.0-rc2-002659) and  NuGet Version: 3.4.3.855. I am running into same Unauthorized issue with **dotnet restore**.  **nuget restore** works just fine. Hopefully whatever merge needs to be approved, happens soon!

**Comment by patrickjamesbarry** [comment] 2016-05-10 16:35
On NET Command Line Tools (1.0.0-preview1-002700), and this is still an issue. Can we get an update on this issue?

**Comment by yishaigalatzer** [comment] 2016-05-10 16:45
Everything is already merged. So we will need more info from you, like a fiddler trace, exact version of Nexus and any particular instruction you can provide us to try and repro this in details.

CC @rrelyea

**Comment by patrickjamesbarry** [comment] 2016-05-10 18:23
Artifactory (Cloud subscription)
Mac 10.10.5
NET Command Line Tools (1.0.0-preview1-002700)
Mono JIT compiler version 4.2.3

I think I found the problem. The auth header is not getting set correctly. 
**Authorization: Basic Og==**

I have confirmed that my credentials are set correctly and even tried 2 different ways. Encrypted vs Clear text.  Everything works when I run nuget restore, which uses the same config file.

```
<packageSourceCredentials>    
<Artifactory>
      <add key="Username" value="<username> />
      <add key="Password" value="<encrypted-pwd" />
    </Artifactory>
  </packageSourceCredentials>
  <packageSourceCredentials>    
<Artifactory>
      <add key="Username" value="<username> />
      <add key="ClearTextPassword" value="<pwd" />
    </Artifactory>
  </packageSourceCredentials>
```

**Comment by alpaix** [comment] 2016-05-10 19:21
@patrickjamesbarry Encrypted passwords are not supported on CoreCLR due to missing System.Security.Cryptography assembly. Can you try with clear text password section only?

**Comment by patrickjamesbarry** [comment] 2016-05-10 19:27
I tried both (separately) with neither working.

**Comment by yishaigalatzer** [comment] 2016-05-10 23:45
We have a proper repro, thanks!

@spadapet and @alpaix are working on a fix.

CC @rrelyea

**Comment by mburumaxwell** [comment] 2016-06-25 12:31
I made a script as a workaround for automated builds in case anyone needs a quick workaround.
See https://maxwellweru.com/using-authenticated-nuget-feeds-with-dot-net-rc2-on-vsts/

**Comment by nwoolls** [comment] 2017-02-13 16:09
I hope this is the correct thread - there seem to be several threads / issues tracking this.

We are trying to automate builds for projects using the .NET Core tooling that is compatible with `project.json` and allows for private NuGet packages to be restored via `dotnet restore` using `nuget.config`. I am running into the same issue as this thread using `1.0.0-preview2-003156`. The command `nuget list` can read the packages just fine and I see:

```
Using credentials from config. UserName: XYZ
```

However, attempting to use `dotnet restore` results in the same 401 in this thread:

```
log  : Response status code does not indicate success: 401 (Unauthorized).
```

I see references to this being fixed and merged, but the fixed CLI tooling I have tried seems to only use the new `csproj` project format.

Thanks in advance for any direction on this. Note this is *not* using VSTS - just a private NuGet server.

**Comment by ericstj** [comment] 2017-02-14 01:00
I don't think this should have been closed.  GitHub closed it on my behalf when I merely forked NuGet.Client and merged its dev branch into my private fork...

**Comment by rrelyea** [comment] 2017-02-14 19:46
The nuget fix is not available for a dotnet.exe that supports xproj/project.json.
There is a workaround mentioned above if you need to stay with Project.json.

NuGet.exe v3.5.0 has this fix, but only runs on windows (and sometimes on mono).

NuGet v4.0.0-rc4 and VS 2017-rc is available today with this fix, but it requires you to migrate to msbuild/csproj from xproj/project.json.

**Comment by nwoolls** [comment] 2017-02-14 20:01
@rrelyea what workaround are you referring to? I only see workarounds specific to VSTS (using a token) but nothing for a private NuGet server.

Are folks using `project.json` dead in the water with private NuGet servers + auth?

**Comment by rrelyea** [comment] 2017-02-14 21:15
I was referring to workaround from @mburumaxwell where he started with: "I made a script as a workaround for automated builds in case anyone needs a quick workaround."
Perhaps it was not the right workaround.

Are you able to use NuGet.exe v3.5.0-rtm in your scenario?

**Comment by ferrancg** [comment] 2017-02-21 20:37
I am also experiencing a similar issue when using dotnet (1.0.0-preview2-003121) against VSTS Feeds, but only intermittently. After exploring a bit on this issue, here is what I found:

1. The error sometime is shown as 403, sometimes as " Password decryption is not supported on .NET Core for this platform."
2. The dotnet restore can actually access the VSTS Feed with the credential, because it works most of the time on both VSTS and local (I did clean the cache before the restore)
3. Not only dotnet restore, even Nuget.exe restore also experience the same error intermittently.
4. The issue does not occur when you use Nuget + Cred Provider (This is our workaround right now)

**Comment by blackdwarf** [comment] 2017-02-21 21:43
@rrelyea I guess that this issue should be moved to Nuget/home, right?

**Comment by gtokenThinhnguyen** [comment] 2017-02-22 03:50
I am also having same issues when I am using dotnet (1.0.0-rc4-004771) on ubuntu Ubuntu 16.04. 
I already set the api key in Nuget.Config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="private_nuget_source" value="http://nexus.<domain>/repository/nuget-hosted/" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <apikeys>
    <add key="http://nexus.<domain>/repository/nuget-hosted/" value="<private_key>" />
  </apikeys>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
</configuration>
```

```
dotnet restore --configfile=NuGet.config
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nexus.<domain>/repository/nuget-hosted/FindPackagesById()?id='AspNetCore.DataProtection.Aws.S3''.
Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by nwoolls** [comment] 2017-02-22 03:58
@gtokenThinhnguyen only options we found:

* Build on Windows using NuGet.exe 3.5 and `nuget restore`
* Or, build on *nix using Mono and NuGet 3.5 (`nuget update -self`) and `nuget restore`
* Or, put your private NuGet server inside a VPN (if under your control)
* Or, upgrade your project(s) to the recently released `csproj` based tooling

**Comment by gtokenThinhnguyen** [comment] 2017-02-22 04:10
Thank you @nwoolls for a quick response. I already upgraded my project using csproj and I can restore the packages if my nuget repository is set public (without authentication). I guess that "dotnet restore" cannot get the credentials from NuGet.Config.

**Comment by nwoolls** [comment] 2017-02-22 04:12
@gtokenThinhnguyen interesting (and unfortunate if true) - that last option was an assumption on my part based on the feedback of others. We have yet to do the upgrade from `project.json` for these particular projects.

**Comment by gtokenThinhnguyen** [comment] 2017-02-22 04:21
@nwoolls yah I am looking for why "dotnet restore" cannot retrieve my credentials from NuGet.config :(

**Comment by nwoolls** [comment] 2017-02-22 04:27
@gtokenThinhnguyen did you try the other options? Not sure if Mono is an option for you and your build tooling. But using Mono along with `nuget restore` - not `dotnet restore` worked for me as long as NuGet was updated using e.g. `nuget update -self`.

**Comment by piotrpMSFT** [comment] 2017-02-22 05:01
This issue was moved to NuGet/Home#4668

**Closed by piotrpMSFT** 2017-02-22 05:01 UTC
