### ISSUE TITLE
dotnet add package should prefer attribute form

### ISSUE THREAD

**Issue by sharwell** [dotnet/cli#11100] opened 2019-04-08 18:31 UTC
## Steps to reproduce

> dotnet add package coverlet.msbuild

## Expected  behavior

```xml
<PackageReference Include="coverlet.msbuild" Version="2.5.0"
  IncludeAssets="runtime; build; native; contentfiles; analyzers"
  PrivateAssets="all" />
```

## Actual behavior

```xml
<PackageReference Include="coverlet.msbuild" Version="2.5.0"> 
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets> 
  <PrivateAssets>all</PrivateAssets> 
</PackageReference> 
```

## Environment data

Unknown (filed in response to https://github.com/dotnet/winforms/pull/702#issuecomment-480903415)

**Comment by peterhuene** [comment] 2019-04-08 19:58
I moved #11101, which this seems to be a dupe of.  I'm closing this one.

**Closed by peterhuene** 2019-04-08 19:58 UTC
