### ISSUE TITLE
Build dotnet cli on FreeBSD

### ISSUE THREAD

**Issue by sec** [dotnet/cli#3720] opened 2016-06-28 22:21 UTC
What do I need to build dotnet CLI on FreeBSD?
build.sh fails to detect OS and download binaries - how can I build those myself?
Do I need corecli/corefx to build?
Can corecli be used to run .net core apps?

**Comment by josteink** [comment] 2016-07-07 09:27
Not having a FreeBSD dotnet cli available is a build-breaker for corefx, and a hinderance to providing better coreclr availability for FreeBSD users (as mentioned in the above linked issue).

It would be nice if someone could look into this.

**Comment by sec** [comment] 2016-07-07 09:39
@josteink I'm able to build corehost (dotnet cli) under FreeBSD, but don't know what to do next. core-setup won't build anyway.

**Comment by josteink** [comment] 2016-07-07 11:15
I'm assuming coreclr run will only invoke `corerun` from coreclr.

As such I'd start with building coreclr, and then corefx.

For coreclr, follow the instructions here: (Soon to be merged to coreclr master via PR): https://github.com/josteink/coreclr/blob/master/Documentation/building/freebsd-instructions.md

For corefx, there seems to be some issues, discussed further in this issue here: https://github.com/dotnet/coreclr/issues/6115

Good luck.

**Comment by sec** [comment] 2016-07-07 12:21
@josteink I have coreclr and corefx build for FreeBSD (managed part built under Windows) and corehost (dotnet cli) from core-setup. How to build SDK (packages, dll's) to run, for example asp.net app? Can't find any information for this.

**Comment by josteink** [comment] 2016-07-07 12:55
Oh okay. As far as dotnet cli goes, and the whole SDK thing, I honestly don't have the big picture and don't think I can help much. Hopefully someone else can help you out here.

**Comment by blackdwarf** [comment] 2016-07-27 17:13
Dupe of #3815 .

**Closed by blackdwarf** 2016-07-27 17:13 UTC
