### ISSUE TITLE
publish ignores folders with underscore in name

### ISSUE THREAD

**Issue by xandhen** [dotnet/cli#7592] opened 2017-09-05 19:26 UTC
## Steps to reproduce
Create folder in wwwroot directory with the name "jspm_packages" prior to running publish
Run dot net publish

## Expected  behavior
The wwwroot folder in the output directory should contain a folder named "jspm_packages"

## Actual behavior
The folder "jspm_packages" is missing from the wwwroot folder in the output directory.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment] 2017-09-05 23:48
@mlorbetske can you take a look at this?

**Comment by ibrahimbensalah** [comment] 2017-09-16 12:11
same issue here

**Comment by dasMulli** [comment] 2017-09-17 12:05
`jspm_packages` is explicitly excluded in the web sdk [here](https://github.com/aspnet/websdk/blob/c4d0ae7e2a897870c82b9ee289e2046fb0876fce/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L16), so the folder is likely missing due to being named `jspm_packages` and not just because of the underscore..

To include the folder, you can add this to the project file:
```xml
<ItemGroup>
    <Content Include="jspm_packages\**" CopyToPublishDirectory="PreserveNewest" />
</ItemGroup>
```

**Comment by nguerrera** [comment] 2017-10-08 05:20
Closing since the websdk behavior is by design. You can override it as @dasMulli has shown.

**Closed by nguerrera** 2017-10-08 05:20 UTC
