### ISSUE TITLE
New projects are not created referencing netcoreapp1.1

### ISSUE THREAD

**Issue by simonech** [dotnet/cli#4788] opened 2016-11-20 13:11 UTC
After installing SDK + Runtime 1.1 I would expect to have new projects created targeting netcoreapp1.1 as by what was written in the [blog announcing .NET Core 1.1](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/), but what I get is csproj file referencing netcoreapp1.0

> The dotnet new command creates new templates that reference the latest runtime on the machine. This may not be desired. If not, you can hand-edit the versions in the resulting project.json to earlier version numbers. Based on feedback, we will be changing this behavior in the new version of the tools, at the same time we release the final version of Visual Studio 2017. If you do not use dotnet new to create new projects, but rely on Visual Studio, then you are not affected.

I know I can just edit it manually but it's very confusing, especially given the explanation in the post that says the opposite should happen.

## Steps to reproduce
Install "current" version of [SDK 1.1](https://go.microsoft.com/fwlink/?LinkID=835014)
launch `dotnet new`

## Expected  behaviour
Given the description on the [blog announcing .NET Core 1.1](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/) I'expect the `project.csproj` file to reference netcoreapp1.1

```
<TargetFramework>netcoreapp1.1</TargetFramework>
...
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.1.0</Version>
    </PackageReference>
```
## Actual behaviour

I still get a reference to netcoreapp 1.0

```
<TargetFramework>netcoreapp1.0</TargetFramework>
...
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

I checked and 1.1.0 is installed 

```
 Directory of C:\Program Files\dotnet\shared\Microsoft.NETCore.App

19/11/2016  22:21    <DIR>          .
19/11/2016  22:21    <DIR>          ..
17/07/2016  16:06    <DIR>          1.0.0
19/05/2016  20:00    <DIR>          1.0.0-rc2-3002702
07/11/2016  21:05    <DIR>          1.0.1
20/11/2016  01:09    <DIR>          1.1.0
               0 File(s)              0 bytes
               6 Dir(s)   2,629,787,648 bytes free
```

**Comment by piotrpMSFT** [comment] 2016-11-20 17:34
This is an interesting issue caused by recent release mechanics.

The problem is that the product is evolving on two fronts: the framework moved to 1.1 and the tools moved to msbuild. Both of these releases occurred at nearly the same time and were intentionally kept separate. This, however, means that one of them had to win for the default experience...

What happened on your system is that you installed preview2.1 with runtime 1.1 support atop project.json. You also installed preview3 with 1.0 support atop msbuild. The preview3 tools are 'newer' from a tools perspective, though they use an older runtime. This needs to be solved more elegantly before we take off the 'preview' suffix :)

I'm glad you have the workaround of manually updating the project files. You can also force CLI to preview2.1 behavior by adding a global.json file to the folder and setting its sdk.version property to the preview2.1 version number... But that's pretty counterintuitive when you want to use a project template.

We will reconcile these issues soon.

**Comment by simonech** [comment] 2016-11-20 18:40
So if I want to have the msbuild project file I need the tools "preview3" but then I have 1.0 templates.
If I want to use the templates with 1.1 I just need to install the preview 2.1 and just the runtime 1.1 (not the SDK).
Is that correct?

**Comment by piotrpMSFT** [comment] 2016-11-22 08:11
preview 2.1 comes with runtime 1.1 so you would be good to go.

Personally, I'd install preview3, install 1.1, and manually bump the version number in the generated templates to 1.1. I don't see much benefit in using the project.json tooling if a project is being created from scratch.

**Comment by simonech** [comment] 2016-11-23 10:25
Shall I leave the Microsoft.NET.Sdk to 1.0.0-alpha-20161104-2?

**Comment by piotrpMSFT** [comment] 2016-11-24 07:19
yep, you can leave the SDK at that version.

**Comment by kurtdevocht** [comment] 2016-12-01 09:43
I have the same setup as @simonech describes in the first post. On top of that, I've also installed visual studio 2017 RC (Visualstudio/public.d15rel/15.0.25920.0).

When I manually update `<TargetFramework>netcoreapp1.0</TargetFramework>` to `<TargetFramework>netcoreapp1.1</TargetFramework>` in the .csproj file, Visual Studio is unable to open the project file (Error message: "Value cannot be null. Parameter name: key")

What should I do to build a csproj-based dotnet core 1.1 app in Visual Studio 2017?

**Comment by piotrpMSFT** [comment] 2016-12-01 18:13
@srivatsn @nguerrera @dsplaisted any ideas on this one?

**Comment by nguerrera** [comment] 2016-12-01 18:27
Does the project build fine on the command line?

**Comment by kurtdevocht** [comment] 2016-12-02 07:13
@nguerrera Yes, it does compile and run when built on the command line.

**Comment by nguerrera** [comment] 2016-12-02 17:02
@kurtdevocht Thanks for the report. I've filed https://github.com/dotnet/roslyn-project-system/issues/862 to look at this on the VS side.

**Comment by piotrpMSFT** [comment] 2016-12-04 10:02
Since the remaining issue is tracked by dotnet/roslyn-project-system#862, closing this one.

**Closed by piotrpMSFT** 2016-12-04 10:02 UTC
