### ISSUE TITLE
dotnet run fails silently on linux

### ISSUE THREAD

**Issue by arcooke** [dotnet/cli#12454] opened 2019-08-31 20:19 UTC
_I'm running an unsupported distro_ (Solus) using dotnet and vs code snaps, so there is no expectation of official support.  However, I don't think `dotnet run` should be failing silently under any circumstance, supported or not.  I am happy to to try to resolve my own issue, but I'm not getting any output from dotnet that I can use to debug.  `--verbosity` option makes no difference

I could use a hand here.  Screen recording:

![dotnet](https://user-images.githubusercontent.com/6278400/64068754-27b9ce00-cc02-11e9-8127-8ed3cdc401b0.gif)

## Steps to reproduce
`dotnet run` with any options and any verbosity level

## Expected  behavior
Project runs, or outputs error information

## Actual behavior
`dotnet run` fails silently

## Environment data
`.bashrc`

```
export MSBuildSDKsPath=/snap/dotnet-sdk/current/sdk/$(/snap/dotnet-sdk/current/dotnet --version)/Sdks
export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))
export PATH="$PATH:/home/adam/.dotnet/tools"
```

```
$ snap list
Name        Version                  Rev   Tracking  Publisher    Notes
code        f06011ac                 13    stable    vscode✓      classic
core        16-2.40                  7396  stable    canonical✓   core
core18      20190723                 1074  stable    canonical✓   base
dotnet-sdk  3.0.100-preview8-013656  45    beta      dotnetcore✓  classic
```

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     solus
 OS Version:  4.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/45/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [/snap/dotnet-sdk/45/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/snap/dotnet-sdk/45/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/snap/dotnet-sdk/45/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment] 2019-09-03 18:02
Hi @arcooke.

This is a known issue with snap installs preventing framework-dependent application via the apphost (the executable that gets built by default for your application). 

See https://github.com/dotnet/cli/issues/12269#issuecomment-521835506 for a workaround.

We're tracking the problem with https://github.com/dotnet/core-setup/issues/5186, which also links to a bug in snap.

I'm going to close this issue as a duplicate of those issues.  Thanks!

**Closed by peterhuene** 2019-09-03 18:02 UTC
