### ISSUE TITLE
Add `dotnet nuget` and `dotnet msbuild` to --help output

### ISSUE THREAD

**Issue by sjdweb** [dotnet/cli#4762] opened 2016-11-17 15:18 UTC
## Steps to reproduce
When using dotnet-cli on non-Windows machines, you are able to make use of `dotnet pack` to prepare your NuGet packages for publishing, but still need to use `nuget push` to finish the job. Unfortunately this relies on Mono which has issues with certain SSL ciphers and TLS 1.2. Which means you cannot publish NuGet packages and must use Windows. [Here](https://bugzilla.xamarin.com/show_bug.cgi?id=26658) is a Xamarin bug tracking one of these.

## Expected  behavior
`dotnet pack publish`

## Actual behavior
Need to use `nuget push` on Windows.

## Environment data
NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by dasMulli** [comment] 2016-11-17 16:36
You could use `dotnet nuget push`. However, `dotnet nuget` isn't shown in the help text, just like `dotnet msbuild`.

**Comment by svick** [comment] 2016-11-17 16:37
Preview 3 has [the `dotnet nuget push` command](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-nuget-push) for exactly this purpose.

**Comment by piotrpMSFT** [comment] 2016-11-17 18:15
Tracking updating help content with this issue, after changing title.

**Comment by blackdwarf** [comment] 2016-11-17 18:40
This is a dupe of #4700.

**Comment by piotrpMSFT** [comment] 2016-11-17 19:23
@blackdwarf I don't see `msbuild` in the updated help text in #4700.

**Comment by piotrpMSFT** [comment] 2016-11-17 19:23
nor `nuget`

**Comment by blackdwarf** [comment] 2016-11-17 21:01
@piotrpMSFT there is no updated text in #4700. :) The text there is actually the current situation. I will add it.

**Comment by sjdweb** [comment] 2016-11-17 21:40
Great to see this is in preview3 already! Awesome.

Would you like a pull request for the updated docs or do Microsoft devs usually handle that?

**Comment by svick** [comment] 2016-11-17 21:47
@sjdweb What docs are you specifically talking about? [There already is documentation for `dotnet nuget push` on docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-nuget-push) and `dotnet --help` is being updated by https://github.com/dotnet/cli/pull/4763.

**Comment by sjdweb** [comment] 2016-11-17 21:51
@svick I see. I meant the `dotnet --help` output. #4763 fixes it.

**Comment by piotrpMSFT** [comment] 2016-11-17 22:24
Cool. We'll close this once #4736 is merged.

**Comment by blackdwarf** [comment] 2016-11-17 23:12
@piotrpMSFT issue #4700 updated with the needed/updated text.

**Comment by livarcocc** [comment] 2016-12-05 20:23
They are showing up on help now.

**Closed by livarcocc** 2016-12-05 20:23 UTC
