### ISSUE TITLE
Adding a project reference under full framework breaks ‘dotnet restore’

### ISSUE THREAD

**Issue by gregkalapos** [dotnet/cli#4172] opened 2016-09-13 11:35 UTC
## Steps to reproduce

[Here](https://github.com/gregkalapos/CliRestoreProblemReproducer) is a very simple reproducer. `dotnet restore` does not work in it, although the app compiles.
- Create an application with project.json to target net462 (or any other Full framework version) e.g. by VS -> File -> New Project -> Web -> “ASP.NET Core Web Application (.NET Framework)”. (Btw. this can be any CLI based application targeting Full Framework) 
- Add an old, classical (e.g. .NET 2.0) class library to the solution. 
- Add a reference the .NET2.0 class library in the ASP.NET Core project
  This causes an entry in the project.json of the webapplication:

```
"net462": {
      "dependencies": {
        "ClassLibrary1": {
          "target": "project"
        }
      }
```

So, project structure:

Reproducer
----ClassLibrary1
----WebApplication1
## Expected  behavior

In Visual Studio everyting is fine and with `dotnet run` i'm also able to run it.
Since in CI we do a `dotnet restore` step I would expect that to work, but it does not. 
## Actual behavior

```

C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1>dotnet restore
log  : Restoring packages for C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1\project.json...
error: Unable to resolve 'ClassLibrary1' for '.NETFramework,Version=v4.6.2'.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1\project.json...
log  : Writing lock file to disk. Path: C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1\project.lock.json
log  : C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1\project.json
log  : Restore failed in 881ms.

Errors in C:\Users\Gergely.Kalapos\Documents\Visual Studio 2015\Projects\ClassLibrary1\WebApplication1\project.json
    Unable to resolve 'ClassLibrary1' for '.NETFramework,Version=v4.6.2'.

```

And this breaks our CI build.

(I did the `dotnet restore` step also in the root of the solution, it doesn't matter) 
## Environment data

dotnet --version
1.0.0-preview2-003121

Windows 10
Visual Studio Professional 2015 Update 3 (Version 14.0.25421.03)

**Comment by saigandhi** [comment] 2016-09-15 17:11
I have the same issue and it's a road block..

**Comment by nelsonmorais** [comment] 2016-11-09 12:05
Same problem here, any workarounds?

**Comment by kyschouv** [comment] 2016-11-09 19:17
One thing I found when looking at this (I forget where the issue is) is that if your class library produces an output with a different name, the project reference won't work. That's for the new project.json class libraries though - not sure about older ones.

**Comment by nelsonmorais** [comment] 2016-11-10 08:41
@kyschouv Not the case here, but thanks for your input.

**Comment by piotrpMSFT** [comment] 2016-11-11 22:58
Can someone add a code repro to this issue? either a link to a repo or just a zip file with src. I've not been successful at reproducing this behavior.

**Comment by blackdwarf** [comment] 2017-01-17 20:59
Due to lack of traffic on this issue and the fact that we cannot repro it, I will close it. If you can share a repro, please reopen, but do take into account that with the move to MSBuild this issue should go away.

**Closed by blackdwarf** 2017-01-17 20:59 UTC
