### ISSUE TITLE
Error on "dotnet restore restore.dg" for ASP.Net Core Project in VS 2015 Update 3 with latest Dotnet CLI.

### ISSUE THREAD

**Issue by DreamingDevs** [dotnet/cli#4248] opened 2016-09-26 08:26 UTC
Hi,
## Steps to Reproduce

Create a new ASP.Net Core application in Visual Studio Community 2015 Update 3 on Windows 10 with latest Dotnet CLI (preview3-003686) and VS Tooling (VS2015Tools.Preview2.0.2). Point nuget.config to aspnetcore-dev myget feed.
## Actual behavior

When ever I create a new ASP.Net Core Project in Visual Studio community 2015 update 3, the first package restore (which happens immediately after project creation) fails with following error. In fact the same error is coming even if we do restore packages (by right clicking references of the project).

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Users\ramiadmin\Desktop\SampleApp\.vs\restore.dg"
error: Error reading 'C:\Users\ramiadmin\Desktop\SampleApp\.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0. 
```

Interesting point it, if I dot `dotnet restore` from command line, it successfully restore all the packages. Also `dotnet run` from command line works absolutely fine.

I pointed my `nuget.config` to `aspnetcore-dev` myget feed - 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
</configuration>
```

Following is my global.json - 

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview3-003686"
  }
}
```

Following is my project.json - 

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-*",
    "Microsoft.AspNetCore.Mvc": "1.1.0-*",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-*",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-*",
    "Microsoft.Extensions.Logging": "1.1.0-*",
    "Microsoft.Extensions.Logging.Console": "1.1.0-*",
    "Microsoft.Extensions.Logging.Debug": "1.1.0-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0-*"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

```
## Expected  behavior

Either after the initial application creation or by selecting restore packages (by right clicking references in VS), Packages should be restored successfully with out errors.
## Environment data

> .NET Command Line Tools (1.0.0-preview3-003686)
> 
> Product Information:
>  Version:            1.0.0-preview3-003686
>  Commit SHA-1 hash:  038fb6fbae
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.10586
>  OS Platform: Windows
>  RID:         win10-x64

I used `Visual Studio Community 2015 Version 14.0.25425.01 Update 3`.

I have installed Visual Studio 2015 Tooling Preview 2 of version `DotNetCore.1.0.1 - VS2015Tools.Preview2.0.2` from [https://go.microsoft.com/fwlink/?LinkId=827546](https://go.microsoft.com/fwlink/?LinkId=827546)

OS - `Windows 10 Enterprise N`

**Comment by knilecrack** [comment] 2016-09-28 03:00
Same problem

**Comment by 18583690825** [comment] 2016-09-28 06:25
Same...

`
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\dotnet\dotnet.exe restore "D:\User\CoreProjects\Sample\.vs\restore.dg"
error: Error reading 'D:\User\CoreProjects\Sample\.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
`

**Comment by AlyceS** [comment] 2016-09-28 06:46
Same...

**Comment by EncoderPtd** [comment] 2016-09-28 10:01
Unfortunately, this was such a mistake, but it was resolved.
There shouldn't be any file using name that is not English...
Or it will cause this problem.
It means you should set all file names in ASCII characters.

**Comment by DreamingDevs** [comment] 2016-09-28 10:25
@EncoderPtd I am not sure if I got you correctly. How is it related to file name? I created a brand new application with latest dotnet cli. And my application name is `SampleApp`. So what should be changed?

Which file actually caused problem to you?

**Comment by EncoderPtd** [comment] 2016-09-28 11:00
@DreamingDevs 
I used to have a resource file with a GBK character name (CN you know..) witch caused the issue. And when using vs to compile the solution or even restore Nuget Packages, the Output window in VS told me the error that you said. And i think the restore.dg file is used to record relationships of each project(you can see in it), and when invoke dotnet restore or build, CLI will analyze projects' info into that file(maybe i guess).
Anyway i changed my file name into EN, then reboot VS, it worked. Also on CentOS7.

**Comment by EncoderPtd** [comment] 2016-09-28 11:04
By the way, i think all the path, directory or name in CN character could cause that. Anyhow, my VS, CLI command line(both on Win and CentOS) worked OK.

**Comment by DreamingDevs** [comment] 2016-09-28 11:35
@EncoderPtd My application was brand new, created with VS. I never changed a single file in it. Except I updated `global.json` with new sdk version and `project.json` with new versions (I am sure that these versions are available in MyGet). So I think my problem is completely different. Waiting for someone from Core team to reply.

**Comment by ignacy130** [comment] 2016-10-04 11:31
Same thing here :/ Happens during restoring nuget packages. This operation fails and `#: ` is being added at the beginning some lines in the `restore.dg` file.

It results in 'Package restore failed' error in Output:
`[file path] at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0.`

**Comment by pealmeid** [comment] 2016-10-08 13:51
I'm having the same problem. Package restore inside VS2015 fails with the message: 

    error: Error reading 'C:\Users\username\Documents\Projects\SampleApp\.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.

However, `dotnet restore` from command line completes without any problems.

Using latest version of `dotnet` (1.0.0-preview3-003786) and VS2015 Update 3.

**Comment by scy0846** [comment] 2016-10-11 14:57
I'm having the same issue. I'm following this thread.

**Comment by benaadams** [comment] 2016-10-13 05:29
Yep

**Comment by sigmondzavion** [comment] 2016-10-31 20:17
Same issue

**Comment by aling93** [comment] 2016-11-01 11:32
I'm also experiencing the same issue.

**Comment by cehager** [comment] 2016-11-02 14:52
Same issue with '#:'. But I can open powershell and run dotnet restore and all packages restore correctly. Beeezaaar!

**Comment by piotrpMSFT** [comment] 2016-11-03 07:16
Folks, when Preview3 ships it will not include project.json support. In fact, builds since 3393 have already moved all major verbs [new, restore, build, pack, publish, etc...] to work with .csproj files only. There is a new `dotnet migrate` verb in preview3 that will convert your project.json project into a csproj project. Of course, the preview tooling you have installed for project.json won't be able to deal with the csproj version yet, but you can get a feel for where things are headed.

When we shipped VS tools for project.json, the project templates included a global.json file that specified the preview2 version of the tools for any projects created in visual studio. You will want to be sure that your project.json solutions include a global.json with a sdk version so as to avoid problems in Visual Studio when you have a preview3 build installed. 

Specifically, in most projects you will want [I say most because you may have installed later preview2 builds. If you see problems, just match to the preview2 version you have been using]:

````
{
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
````

There may be a deeper issue here than folks using preview3 with project.json, so I'll leave the issue open for a while so we can discuss.

**Comment by cehager** [comment] 2016-11-03 16:21
I'm still on  "sdk": {
    "version": "1.0.0-preview2-003133"
  }

The restore process fails, but dotnet restore works. (restore.dg has #: as first chars)
Thanks for the info, looking forward to preview3. Cheers

**Comment by NickCraver** [comment] 2016-11-04 22:55
@piotrpMSFT Is there any chance this will change? The hard migration of projects, repositories, and IDEs all at once is a *huge* ask for any project. The current plan is a stop-the-world operation and a major pain for any team that has given a lot of time to come along on this journey and help improve things along the way. It's even worse for open source which has pull requests involved. 

I strongly urge Microsoft to reconsider this support split, unless we want quite a few projects to linger on project.json. I know I wouldn't migrate our projects (indefinitely) with the current roadmap; it's just too big of an ask if all we can do is a highly coordinated big bang changeover.

**Comment by benaadams** [comment] 2016-11-04 23:54
@NickCraver I assume its not by design as you can do a command line restore, then VS will happily build - it just has issues restoring due to the restore.dg file which the cli doesn't seem to use but VS does.

**Comment by NickCraver** [comment] 2016-11-04 23:58
@benaadams re-reading that I see I should have clarified: I was speaking specifically about supporting `project.json` in VS 2015 (14) *only* and  supporting the new `.csproj` in VS 15 *only*. That's an incredibly bad constraint and I'd even say feels like punishment for any early adopters, especially people multi-targeting in `project.json` today.

**Comment by piotrpMSFT** [comment] 2016-11-09 01:02
Folks, we just posted a nice writeup of options for working around this issue:
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md

I think that everyone can find an approach that works for them, whether wanting to work with project.json, csproj, or both. Please take a look and let us know if this gets you unblocked!

**Comment by piotrpMSFT** [comment] 2016-11-09 05:52
Folks, we got reports from a number of machines which still repro the issue after following the steps in the linked writeup. Unfortunately, we haven't been able to reproduce the issue and need some assistance to get this addressed.

If you followed the guidance in the writeup and still see an issue can you please share some state with us?
 - zip archives of both the `Program Files\dotnet` and `Program Files (x86)\dotnet` directories on your machine.
- contents of your PATH environment variable to a text file
- the `global.json` file for your solution

These should give us enough data to find out why some folks are still running into issues. You can put these all in an archive and send me a link at piotrp [at] microsoft [dot] com. I'd really like to get to the bottom of the remaining issue!

**Comment by piotrpMSFT** [comment] 2016-11-09 22:59
@cehager thanks for helping out with a repro!

Folks we were able to track down the cause of the .dg issue. As a workaround you can:
- Copy the full command line that is failing, something like `C:\Program Files\dotnet\dotnet.exe restore "C:\Users\ramiadmin\Desktop\SampleApp\.vs\restore.dg"`
- Open a command prompt and navigate to the project directory, e.g. `cd C:\Users\ramiadmin\Desktop\SampleApp\`
- Run the copied command from this directory
- Reload the project in Visual Studio

I've tested this locally and was able to F5 and debug. Keep in mind, the procedure will need to be repeated any time that a restore would be required, so on a new machine or when dependencies change.

**Comment by piotrpMSFT** [comment] 2016-11-11 10:47
Closing the issue since there is a workaround. Working on a better fix...

**Closed by piotrpMSFT** 2016-11-11 10:47 UTC
