### ISSUE TITLE
Running tools no longer works- returns Could not resolve coreclr path

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#2054] opened 2016-03-25 16:09 UTC
## Steps to reproduce
Installed 1.0.0.002019
```
1. dotnet new
2. add razor tooling to project.json
  },
  "tools": {
   "dotnet-razor-tooling": "1.0.0-rc2-20254"
  }
3. dotnet restore
4. dotnet razor-tooling

get the following error. I tried a number of different tools and they all fail the same way.
Could not resolve coreclr path
```

**Comment by brthor** [comment] 2016-03-25 17:03
Dupe of #2026

**Comment by piotrpMSFT** [comment] 2016-03-28 09:20
Closing. This is bug needs to be filed against the tools in question.

**Closed by piotrpMSFT** 2016-03-28 09:20 UTC
Labels: blocking-partner
