### ISSUE TITLE
dotnet build output directory on Linux is different for root vs non-root

### ISSUE THREAD

**Issue by ziffusion** [dotnet/cli#10659] opened 2019-01-26 18:42 UTC
(dotnet sdk 2.2)

For root user:

> ./bin/Debug/netcoreapp2.1/IEDSim.dll

For non-root user:

> ./bin/**LINUX**/Debug/netcoreapp2.1/IEDSim.dll

Why is this, and is there a way to make this conistant?

**Comment by livarcocc** [comment] 2019-01-26 22:20
We have not perceived this ourselves. Is there something else different that you are doing? Can you provide a repro repo on github that we could try using to reproduce the issue? Or can you provide a binlog for the case where LINUX is being added (it should not be, independently of root or not). I suspect your non-root user might have some environment variable set that is affect the Outputpath for the project.

**Comment by peterhuene** [comment] 2019-01-27 19:33
Hi @ziffusion.  I'm glad you figured out the cause.  Unfortunately, `Platform` is an MSBuild property that has been in use by Visual Studio for a very long time (16+ years) and is something the .NET Core SDK needs to support in various places.  MSBuild will source the values of properties from the environment (case-insensitive, as you've discovered) if they are not set in a project file or other MSBuild-related files.

I do not know of an MSBuild feature to prevent the sourcing of properties from the environment.  @rainersigwald do you know of one or is there something on the backlog?

I'm going to close this issue for now, but we can continue this discussion here or move the issue to MSBuild if we feel that there is a missing feature that needs to be implemented.

Thanks for taking the time to report this to us!

**Closed by peterhuene** 2019-01-27 19:33 UTC

**Comment by rainersigwald** [comment] 2019-02-05 23:37
Microsoft/msbuild#2713 is the long-term "how can we better deal with inadvertent environment->MSBuild property problems" issue.
