### ISSUE TITLE
F# application compiled every run, even if nothing was modified

### ISSUE THREAD

**Issue by svarogg** [dotnet/cli#3996] opened 2016-08-04 18:58 UTC
## Steps to reproduce

Follow the F# Getting Started tutorial below, up to and including "Writing a Console Application which Consumes the Class Library"
https://docs.microsoft.com/en-us/dotnet/articles/fsharp/getting-started-netcore

cd into App directory
type `dotnet run` twice
## Expected  behavior

On the first run it should compile the application and run.
On the second time it should run without compilation
## Actual behavior

The programs compiles every time you type dotnet run, although nothing changed in the sources.
Here's actual output:

```

Project Library (.NETStandard,Version=v1.6) will be compiled because inputs were modified
Compiling Library for .NETStandard,Version=v1.6

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.3504307
Project App (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling App for .NETCoreApp,Version=v1.0
/home/mike/dev/fsharp-test/src/App/project.lock.json(1,0): warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.6243024


Nice command line arguments!.  Here's what JSON.NET has to say about them:

```
## Environment data

`dotnet --info` output:

```

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

```

**Comment by cartermp** [comment] 2016-08-19 16:39
Yep, this is a known, reproducible issue.  However, I'm not familiar with how the semantics of "hooking into" the CLI are going to work for F# with the switch to being MSBuild-based.  Thus I can't really say what we should be doing here.

**Comment by psulek** [comment] 2016-08-25 14:28
Same issue for C# projects. So it should be fixed. Strange is output says `Project XYZ (.NETStandard,Version=v1.6) will be compiled because inputs were modified` for all projects under solution, even when you dont touch any of files.

**Comment by piotrpMSFT** [comment] 2016-11-12 10:07
This has been fixed for C# in preview3 and @enricosada is working on an update to F#.

**Closed by piotrpMSFT** 2016-11-12 10:07 UTC

**Comment by psulek** [comment] 2016-11-14 09:16
@piotrpMSFT Any ETA on C# preview3 ?

**Comment by piotrpMSFT** [comment] 2016-11-15 19:19
@psulek I can't comment on real dates, but we have forked a  preview3 branch at build 1.0.0-preview3-004056 and have rev'd the version number of `rel/1.0.0` to preview4...
