### ISSUE TITLE
Error installing SDK in Linux Mint 18.2

### ISSUE THREAD

**Issue by joel-g** [dotnet/cli#9778] opened 2018-08-01 22:25 UTC
## Steps to reproduce
Following installation instructions from: 
https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

```sudo apt-get install dotnet-sdk-2.1```
Causes error

## Expected  behavior

 Installation of dotnet SDK

## Actual behavior

This terminal output

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.2) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

## Environment data

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.2
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

I'm surprised I was able to actually run ```dotnet --info`` because of the previous reported error

**Comment by peterhuene** [comment] 2018-08-01 23:11
I've reproduced this with a stock Mint 18.2 VM.

The problem appears to be that `dotnet-runtime-deps-2.1` depends on `libicu60`, which is not available as a xenial package; only `libicu55` is.

Looking into this more.

**Comment by peterhuene** [comment] 2018-08-01 23:16
@leecow Are we seeing reports of being unable to install dotnet 2.1 on Ubuntu 16.x or Mint 18.x?  The runtime packages don't seem to have the correct dependencies.

**Comment by peterhuene** [comment] 2018-08-01 23:17
Looks like https://github.com/dotnet/core-setup/issues/4049 is related.

**Comment by peterhuene** [comment] 2018-08-01 23:25
@joel-g I can confirm the [workaround in this comment](https://github.com/dotnet/core-setup/issues/4247#issuecomment-409174218) (which is to install `libicu60` manually) does work for Mint 18.2

**Comment by leecow** [comment] 2018-08-01 23:30
If you want to set up a Xenial system them you should use the Xenial feed, not the Bionic feed. See https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current for config steps.

**Comment by peterhuene** [comment] 2018-08-01 23:32
Whoops, didn't even notice the original link above was for 18.04 when I ran through the repro.

Going to quickly confirm that's the issue.

**Comment by peterhuene** [comment] 2018-08-01 23:38
Thanks, @leecow for the sharper eyes.  @joel-g I've confirmed that using the Xenial feed @leecow linked to has no dependency issue.

To correct:

```
$ sudo apt-get remove packages-microsoft-prod
```

And then follow the instructions again at https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current.

Closing this issue as resolved.  Please reactivate if you're still unable to install the SDK.  Cheers!

**Closed by peterhuene** 2018-08-01 23:38 UTC

**Comment by joel-g** [comment] 2018-08-02 19:49
I followed your suggestion but get this now

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'dotnet-sdk-2.1.101' for regex 'dotnet-sdk-2.1'
Note, selecting 'dotnet-sdk-2.1.105' for regex 'dotnet-sdk-2.1'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.101 : Depends: aspnetcore-store-2.0.6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by peterhuene** [comment] 2018-08-02 20:08
Weird, it should select `2.1.302`, which is the latest 2.1 .NET Core SDK version I get if I follow those instructions.  I assume apt's cache is up-to-date?
