### ISSUE TITLE
dotnet build on a project that targets Full .Net Framework does not generate binding redirects for dependency tools

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#4666] opened 2016-11-09 21:30 UTC
## Steps to reproduce
In a project that targets `net4xx` add scaffolding design and tools package. 

```xml
  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0-msbuild1-final"/>
  <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild1-final"/>
```

Run `dotnet-build` on the project. 

## Expected  behavior
A config file is created in the bin folder next to the `dotnet-aspnet-codegenerator-design.exe` as `dotnet-aspnet-codegenerator-design.exe.config`
The contents are same as the config file generated for the project's output. 

This was the behavior with the CLI version `1.0.0-preview2-003131`

## Actual behavior
The config file is only generated for the project's output.
Invoking the dependency tool fails as the assemblies it needs do not load properly.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x86

cc @balachir, @mlorbetske

**Comment by prafullbhosale** [comment] 2016-11-09 21:31
cc @livarcocc

**Comment by piotrpMSFT** [comment] 2016-11-10 00:16
@krwq is working on this

**Comment by piotrpMSFT** [comment] 2016-11-10 00:39
This is also a duplicate of #4514

**Closed** 2016-11-10 00:39 UTC
Labels: 1 - Ready
