### ISSUE TITLE
Can't publish netcoreapp1.0 if .NET/Mono not installed

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3658] opened 2016-06-21 02:07 UTC
## Steps to reproduce

If a project.json contains both `netcoreapp1.0` and `netXXX` targets it is impossible to publish the netcoreapp1.0 target when .NET Framework/Mono is not installed on the machine. 

e.g. with project.json like this: 
https://github.com/aspnet/cli-samples/blob/098f56c4f677e64f0ffbeca3b1a8cde68787f499/HelloMvc/project.json#L22-L30

MacOS (I changed `net451` to `net461` because I have Mono already installed):

```
XXXX:HelloMvc Administrator$ dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
/Users/Administrator/source/cli-samples/HelloMvc/project.json(30,15): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6.1 in
```

Fedora:

```
[XXXX@localhost HelloMvc]$ dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
/home/moozzyk/source/cli-samples/HelloMvc/project.json(30,15): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
```

Windows (I changed `net451` to `net465` to get non-existing .NET Fx version - should it even restore?): 

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
C:\Source\cli-samples\HelloMvc\project.json(30,15): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6.5 in
```
## Expected  behavior

When publishing for a specific framework other frameworks should be ignored
## Actual behavior

Unable to publish
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     fedora
 OS Version:  23
 OS Platform: Linux
 RID:         fedora.23-x64
```

```
.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by mikeharder** [comment] 2016-06-23 21:18
I have the same issue on a machine with .NET 4.6, where the project.json targets both `net451` and `netcoreapp1.0`.  For `dotnet build`, it fails if I don't specify the target framework, but it works if I specify `-f netcoreapp1.0`.  However, 'dotnet publish` fails even if I specify `-f netcoreapp1.0`.

**Comment by muratg** [comment] 2016-06-24 20:41
:eyes:

**Comment by Inumedia** [comment] 2016-06-29 01:21
Same issue for me, though I'm a few builds back.

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003093)

Product Information:
 Version:            1.0.0-preview2-003093
 Commit SHA-1 hash:  f4a8df3a56

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

```
$ dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
/builds/.../.../project.json(24,14): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
/builds/.../.../project.json(24,14): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
/builds/.../.../project.json(24,14): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
/builds/.../.../project.json(24,14): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
```

Installing mono-complete not only ups my build time from an average of 2 minutes and 45 seconds to a whopping 10 minutes (which is absolutely unacceptable and out of the question), but it also fails for DOTNET1011.

```
$ dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
/builds/maplestory/MapleDotNetFM/project.json(24,14): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6 in 
/builds/maplestory/MapleDotNetFM/project.json(24,14): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6 in 
/builds/maplestory/MapleDotNetFM/project.json(24,14): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6 in 
/builds/maplestory/MapleDotNetFM/project.json(24,14): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6 in 
```

**Comment by jasonwilliams200OK** [comment] 2016-06-29 12:14
Having to install mono on every target unix is not an option.  There should at least be a test case to test this to prevent it from happening in future. These bugs are really ruining the entire ".NET Core" experience..

**Comment by jasonwilliams200OK** [comment] 2016-06-29 16:32
Unfortunately, @Inumedia's workaround of having `net45` TxM didn't work for us in nunit .NET Core test running (https://github.com/nunit/dotnet-test-nunit/pull/39) as we have a dependency on a project which supports net451 at the minimum, so I came up with another workaround to remove net451 for TravisCI build jobs (node.js based): https://github.com/nunit/dotnet-test-nunit/blob/4b3cd00/.travis.yml#L62-L110

**Comment by Inumedia** [comment] 2016-06-29 16:34
@jasonwilliams200OK If you're also on Ubuntu, you can try grabbing the latest mono instead of from the apt repository. I know when I tried on my desktop instance it worked fine but only failed in my automated builds which are built in a clean ubuntu docker image.

If that doesn't work you could try the development channels for mono.

**Comment by jasonwilliams200OK** [comment] 2016-06-29 16:42
@Inumedia thanks for the tip. Our aim is to make sure that we test our assemblies without mono PCL assemblies dependencies. In order to test it in CI, we use `language: generic` in Travis instead of `language: csharp` (where mono gets installed and there  is no way of opting out of it atm: https://github.com/travis-ci/travis-ci/issues/5189). Therefore that patch is only required for mono.

In future, if things don't change on Travis side, we will add `language: csharp` in a separate job of our `matrix.include` (https://github.com/nunit/dotnet-test-nunit/blob/4b3cd00/.travis.yml#L13-L28), where we need to explicitly test against mono runtime.

**Comment by jasonwilliams200OK** [comment] 2016-06-29 16:45
i.e. additional:

```yml
    - os: linux
      dist: trusty
      sudo: required
      language: csharp
      env: CONFIGURATION=Release FRAMEWORK=net451
    - os: osx
      osx_image: xcode7.2
      language: csharp
      env: CONFIGURATION=Release FRAMEWORK=net451
```

etc.

**Comment by piotrpMSFT** [comment] 2016-11-13 02:17
duplicate of #3636

**Closed by piotrpMSFT** 2016-11-13 02:17 UTC

**Comment by ddrinka** [comment] 2016-11-30 17:11
I've posted a workaround for this issue in the duplicate issue #3636 .
