### ISSUE TITLE
Keep as much out of msbuild's directory as possible

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#5012] opened 2016-12-13 22:27 UTC
See the following trail of how roslyn got moved out of msbuild.exe's directory on desktop:

https://github.com/Microsoft/msbuild/issues/1183
https://github.com/Microsoft/msbuild/pull/1339
https://github.com/dotnet/roslyn/issues/14660
https://github.com/dotnet/roslyn/pull/15222

The CLI will need to absorb that (if it hasn't already). This bug doesn't track that because things will break now if you don't move Roslyn.

But there are other things in the CLI's directory that cause the same sort of versioning problems.

The SDK has been broken a few times by Nuget.*.dll getting put in the CLI msbuild directory with breaking changes. Note that even when the nuget assemblies were versioned from 3.x to 4.x, the fact that they were in the msbuild directory meant that we still could not SxS load the version the SDK uses.

I filed https://github.com/dotnet/sdk/issues/488 for some of the build-to-build problems we've had with the SDK, but to fully resolve the issue for the closure of SDK dependencies, we also need to make sure that the msbuild folder is isolated from nuget and whatever other unnecessary managed code is sitting there now.

@piotrpMSFT I know we've talked about this a lot, but I couldn't find an existing issue.

**Comment by piotrpMSFT** [comment] 2016-12-14 02:33
Sounds like a great issue for @jonsequitur to drive!

**Comment by jonsequitur** [comment] 2016-12-22 19:24
This is a duplicate of #4214.

**Closed by jonsequitur** 2016-12-22 19:24 UTC
