### ISSUE TITLE
OSX package does not modify path or tell the user where files installed to

### ISSUE THREAD

**Issue by igilham** [dotnet/cli#2005] opened 2016-03-23 10:30 UTC
After installing the package linked from the website on OS X, `dotnet` is not on my PATH and there is no obvious location where it is installed. The CLI installer documentation says the PATH should be modified by the package.

## Steps to reproduce

Install the PKG on Mac OS X.

## Expected  behavior

`dotnet` CLI tool should be added to the PATH, or the user should be informed about where the tool has been installed to so they can modify the PATH manually.

## Actual behavior

The PATH has not been changed and there is no help message to suggest where to look.

## Environment data

Package version: dotnet-osx-x64.1.0.0.001598.pkg
OS X version: Yosemite 10.10.5

**Comment by mellinoe** [comment] 2016-03-23 18:11
We're only adding to the path for the cli SDK installer right now, we should either do it in both places or, perhaps better, just do it in the shared framework installer since that will (eventually) be a pre-requisite for the SDK installer.

See:
[SDK postinstall](https://github.com/dotnet/cli/blob/d5f118273b21a9ca70c9a2d0793be9c977f606a5/packaging/osx/clisdk/scripts/postinstall),
[Shared Framework postinstall](https://github.com/dotnet/cli/blob/d5f118273b21a9ca70c9a2d0793be9c977f606a5/packaging/osx/sharedframework/scripts/postinstall)

**Comment by piotrpMSFT** [comment] 2016-03-28 09:23
@Sridhar-MS the path should be set by the host package, right?

**Comment by Sridhar-MS** [comment] 2016-03-28 17:16
Yup. It is done in the host pkg - https://github.com/dotnet/cli/pull/2062/files.

@igilham @mellinoe Can you try the latest https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-osx-x64.latest.pkg ?

**Comment by anorborg** [comment] 2016-04-22 15:12
I just ran the latest sdk installer and while it appears to complete successfully, `dotnet` command not found. `bash_profile` has no reference to `dotnet`

**Comment by andela-tsolarin** [comment] 2016-05-01 16:09
@anorborg after some digging I was able to find that the PKG install files to `/usr/local/share/dotnet/bin`. Knowing this adding to PATH was no problem at all, I use zsh so a simple `export PATH=/usr/local/share/dotnet/bin:$PATH` did the trick. Hope this helps.

**Comment by andela-tsolarin** [comment] 2016-05-03 22:41
@anorborg @igilham after some digging I was able to find that the PKG installs files to /usr/local/share/dotnet/bin. Knowing this adding to PATH was no problem at all, I use zsh so a simple export PATH=/usr/local/share/dotnet/bin:$PATH should do the trick. Hope this helps.

**Comment by blackdwarf** [comment] 2016-07-21 14:50
We are not touching any user files or modifying the $PATH directly. We are using `path_helper` on macOS by placing a file in the `/etc/paths.d` which the `path_helper` then uses to dynamically construct the $PATH for each new terminal session.

If you are using `oh-my-zsh` and you are experiencing a problem with `dotnet` not being on the path, you may need to update your installation, as there was a known problem with the way `oh-my-zsh` constructed the path (more details in our [known issues guide](https://github.com/dotnet/core/blob/master/cli/known-issues.md#users-of-zsh-z-shell-dont-get-dotnet-on-the-path-after-install)). 

Will close this issue since it has been resolved. If it still persists and none of the workarounds are helping, please reopen and update.

**Closed by blackdwarf** 2016-07-21 14:50 UTC

**Comment by adelynx** [comment] 2016-10-23 20:28
I solved the issue by adding to PATH the following line:
PATH=/usr/local/share/dotnet/:$PATH

**Comment by amitsha** [comment] 2016-11-07 05:28
Interestingly, this path wasn't visible to the terminal /usr/local/share/dotnet/ without restarting it.

**Comment by sanjibahmad** [comment] 2017-04-12 03:34
Package: dotnet-dev-osx-x64.1.0.1.pkg
Confirmed, Terminal needed restart after installation for it to find the path.
