### ISSUE TITLE
Dotnet does not report error when there's a RuntimeFrameworkVersion mismatch between projects

### ISSUE THREAD

**Issue by kouvel** [dotnet/cli#8776] opened 2018-03-13 03:37 UTC
## Steps to reproduce
- Install dotnet sdk 2.1.4 (runtime 2.0.5) and uninstall any other installed runtime.
- In a console window, in a temp folder:

```bat
mkdir Cons
mkdir Lib
cd Cons
dotnet new console
notepad Cons.csproj
  Add the following, save, close:
  <ItemGroup>
    <ProjectReference Include="..\Lib\Lib.csproj"/>
  </ItemGroup>
cd ..\Lib
dotnet new classlib
notepad Lib.csproj
  Add the following in PropertyGroup section, save, close:
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
cd ..\Cons
dotnet publish --self-contained --runtime win10-x64
dir bin\Debug\netcoreapp2.0\win10-x64\publish\coreclr.dll
```

## Expected  behavior
- Error due to mismatched `RuntimeFrameworkVersion` between projects

## Actual behavior
- Examining coreclr.dll above, it is from runtime version 2.0.0, this is a silent failure as one of the projects intends to run against 2.0.5
- Similar silent failure when using `dotnet build` / `dotnet ...\Cons.dll`, which unexpectedly runs against the 2.0.0 runtime

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Initially reported by @BrendanGrant in https://github.com/dotnet/corefx/issues/27952#issuecomment-372521802

**Comment by dasMulli** [comment] 2018-03-13 08:33
Could you (@BrendanGrant ?) maybe upload a project reproducing this or create a binary log (`-bl` argument) from the publish command?

When I try to repro this, the correct assets are copied:

<img width="1174" alt="screen shot 2018-03-13 at 09 32 21" src="https://user-images.githubusercontent.com/6129250/37330514-9d4dfad6-26a1-11e8-911d-bc7dd951b05e.png">

**Comment by BrendanGrant** [comment] 2018-03-13 14:34
To which project did you add the RuntimeFrameworkVersion @dasMulli ? What date/version are you seeing in your publish folder?

My original discovery involved it not being applied to all executables in the solution, but @kouvel 's steps also cause it. Attached is a repro based on it. CD into cons and run the following:

```
dotnet publish --self-contained --runtime win10-x64
```
The result is coreclr.dll (amungst others) being the 2.0.0 version from back July: 

![image](https://user-images.githubusercontent.com/11591952/37348244-e14d6908-2690-11e8-8b15-18719cde2906.png)

[repro.zip](https://github.com/dotnet/cli/files/1807221/repro.zip)

**Comment by kouvel** [comment] 2018-03-13 16:16
Shared msbuild binary log here: https://1drv.ms/f/s!AvtRwG9CobRTpw3ddmmxZu_UIYmb

From text log:
```
         Copying file from "C:\Users\<user>\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\coreclr.dll" to "bin\Debug\netcoreapp2.0\win10-x64\publish\coreclr.dll".
...
                 bin\Debug\netcoreapp2.0\win10-x64\publish\coreclr.dll
                         AssetType=native
                         CopyToPublishDirectory=Always
                         DestinationSubPath=coreclr.dll
                         OriginalItemSpec=C:\Users\<user>\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\coreclr.dll
                         PackageName=runtime.win-x64.microsoft.netcore.app
                         PackageVersion=2.0.0
                         RelativePath=coreclr.dll
```

**Comment by livarcocc** [comment] 2018-03-13 17:09
`Microsoft.NetCore.App` is not an implicit package of a library, which is why setting `RuntimeFrameworkVersion` has not effect. NuGet does not unify that package between the console and the library.

Can you set this property in the Console app?

**Comment by kouvel** [comment] 2018-03-13 17:24
Setting the property in the console app causes it to run against the 2.0.5 runtime as expected. The issue though is when there is a difference in referenced runtime version. Since the published app can only run against one version of the runtime, the problem is not discoverable until a bug fixed in a more recent version of the runtime manifests, a build-time error would make it discoverable early.

**Comment by BrendanGrant** [comment] 2018-03-13 17:35
It's a hair more discoverable/obvious when you think of a multi executable setup, say:

App.Service & App.Web

You encounter some issue in App.Service which requires you to add the overrideand add the override, but because App.Web will be built afterwards (it seems alphabetical, but I've not verified) it will override the earlier override and return you to 2.0.0 in the publish folder.

**Comment by livarcocc** [comment] 2018-03-13 17:36
The thing here is that just setting RuntimeFrameworkVersion does not mean that you have a reference to Microsoft.NetCore.App. If your library were targeting netcoreapp as its TFM, then the appropriate unification would happen.

Maybe, what we could do here, is check when RuntimeFrameworkVersion is set if there is a reference to Microsoft.NetCore.App, though, not sure how easy/simple/performant this would be.

cc @dsplaisted @nguerrera to comment on how feasible this is.

**Comment by dsplaisted** [comment] 2018-03-13 18:20
To help clarify: Setting `RuntimeFrameworkVersion` has no effect if you are not targeting `netcoreapp`.  So by default it won't have an effect on a project created with `dotnet new library`.

It is possible to create a library targeting `netcoreapp`.  In this case, `RuntimeFrameworkVersion` will affect the version of .NET Core that the library is compiled against, but there isn't any validation that the patch version specified for a library is compatible with the patch version an app uses.

> It's a hair more discoverable/obvious when you think of a multi executable setup, say:
>
> App.Service & App.Web
>
> You encounter some issue in App.Service which requires you to add the override and add the override, but because App.Web will be built afterwards (it seems alphabetical, but I've not verified) it will override the earlier override and return you to 2.0.0 in the publish folder.

I'm not sure publishing two separate executables to the same folder is supported.  I think there's a lot of things that could go wrong there.

**Comment by dasMulli** [comment] 2018-03-13 18:27
> I think there's a lot of things that could go wrong there.

Yep, tried to do this for including multiple global tools in the same package in the same folder level, it went horribly wrong even though I did my best to match dependency versions.

**Comment by BrendanGrant** [comment] 2018-03-13 18:48
> I don't think publishing two separate executables to the same folder is supported.

Why?

Correct me if I am wrong... but while the line between framework-dependent deployments & self-contained deployments seems clear on a traditional Windows or Linux install... my experience building things on the Raspberry Pi suggests that it always spits out a full SCD.

Even the current 2.0 instructions on Pi hints at only doing SCD: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

> Yep, tried to do this for including multiple global tools in the same package in the same folder level, it went horribly wrong even though I did my best to match dependency versions.

Which I think is where the usefulness of an error comes in, as publish will happily keep building a project or solution & it's dependencies, and silently create this state.

If you've NuGet packages dependencies which vary in such a situation, you'll sometimes be told about it, but VS is pretty good at helping you manage dependencies at a solution wide level, which I'd argue is a common requirement if you've multiple projects (libs or bins) in a single solution... but no way to do the same for framework version.

A work-around is to throw /p:RuntimeFrameworkVersion=2.0.* on the end of the dotnet publish command line and forcibly override whatever is listed in existing project files. I've added that to the build instructions for my project, but that still leaves a smell.

**Comment by dsplaisted** [comment] 2018-03-13 18:58
Self-contained deployments are fine, but there's no guarantee that a self-contained deployment of two different apps to the same folder will work.  The second publish may overwrite files from the first publish with different versions, causing the first app to no longer work.

**Comment by kouvel** [comment] 2018-03-14 02:54
I don't see much difference between publishing "two apps" (exe + exe) vs publishing "two projects" (exe + dll) where one depends on another. In the latter case, the dependency implies requirement that they both run in the same process and hence on the same runtime, so I don't see how it is valid to say that it's not supported to publish them to the same folder - publishing to the same folder is effectively what happens when publishing Cons in the repro steps. Sure, two interdependent apps may run on different runtimes, but that's a minor difference and typically is not desired.

Aside from publishing / self-contained deployments, the issue still exists. Instead of `dotnet publish` above, from the Cons folder do:
- `dotnet build --runtime win10-x64`
- `dotnet bin\Debug\netcoreapp2.0\win10-x64\Cons.dll`

Even this silently runs against the 2.0.0 runtime (unless matching RuntimeFrameworkVersion is on all or the magic set of relevant projects). People may avoid `dotnet run` (which doesn't have this issue) in preference of `dotnet app.dll` for several reasons, but the latter runs against an unexpected and different runtime than the former (by default, which is understandable, but also as a silent failure in this case). As a user, I would expect both to be identical and for the latter to be typical.

**Comment by livarcocc** [comment] 2018-03-14 03:32
The fact that self-contained apps are running against the 2.0.0 runtime by default is an issue that we are looking into addressing and is being tracked in a separate issue. @dsplaisted may be able to find and point out to it.

As for an exe + lib having "different" runtimes, like I said, is expected. Libraries that target netstandard do not have a runtime. As netstandard is compatible with multiple runtimes. That's the reason why setting `RuntimeFrameworkVersion` for it does not work. The RuntimeFrameworkVersion is a property that lets you override and control the version of the Microsoft.NetCore.App package implicitly referenced by projects that target NetCoreApp. If you change your library to netcoreapp, then you will have the desired behavior. Otherwise, you should set that property directly in your exe.

**Comment by kouvel** [comment] 2018-04-01 18:53
I don't fully understand your perspective. I see that an executable should specify which runtime it intends to run on, and a library targeting netstandard can still target a runtime by specifying the `RuntimeFrameworkVersion` and yet there is no error indicating that this is not a valid request for the library. From a user's perspective, there is something worthy of error here. There may be good reasons why it works the way it does (as a result of design choices that may or may not make full sense to a user)  but when the user scenario doesn't make sense despite all of those decisions, something is still wrong. Do you believe that there is no reason for error in this scenario? Do you believe that users should not expect an error in this scenario, and if so, how should they be already aware of the relevant reasons?

**Comment by kouvel** [comment] 2018-04-01 19:01
Aside from publish / self-contained, I also mentioned above the following, which was not responded to:

> Aside from publishing / self-contained deployments, the issue still exists. Instead of `dotnet publish` above, from the Cons folder do:
> - `dotnet build --runtime win10-x64`
> - `dotnet bin\Debug\netcoreapp2.0\win10-x64\Cons.dll`
>
> Even this silently runs against the 2.0.0 runtime (unless matching RuntimeFrameworkVersion is on all or the magic set of relevant projects). People may avoid `dotnet run` (which doesn't have this issue) in preference of `dotnet app.dll` for several reasons, but the latter runs against an unexpected and different runtime than the former (by default, which is understandable, but also as a silent failure in this case). As a user, I would expect both to be identical and for the latter to be typical.

This definitely looks like a bug (from a user's perspective), as even without a publish / self-contained specification, it seems to behave similarly by using the 2.0.0 runtime. Could someone please explain this?

**Comment by nguerrera** [comment] 2018-04-02 19:51
That second issue should be addressed by @dsplaisted's latest changes. We will default to the latest patch for self-contained apps.

**Comment by dsplaisted** [comment] 2018-04-03 20:02
> Aside from publishing / self-contained deployments, the issue still exists. Instead of `dotnet publish` above, from the Cons folder do:
> - `dotnet build --runtime win10-x64`
> - `dotnet bin\Debug\netcoreapp2.0\win10-x64\Cons.dll`
>
> Even this silently runs against the 2.0.0 runtime (unless matching RuntimeFrameworkVersion is on all or the magic set of relevant projects). People may avoid `dotnet run` (which doesn't have this issue) in preference of `dotnet app.dll` for several reasons, but the latter runs against an unexpected and different runtime than the former (by default, which is understandable, but also as a silent failure in this case). As a user, I would expect both to be identical and for the latter to be typical.

@kouvel This should run against the latest 2.0.x shared framework installed on the machine.  Are you saying that this isn't what happens, or are you saying that you expect an error if only 2.0.0 is available because of the `RuntimeFrameworkVersion` set in the library?

As for why it works like this, generally we think that you should not need to specify the `RuntimeFrameworkVersion`.  A framework-dependent app should use the latest runtime on the machine, while a self-contained app should include the latest runtime when it is published.  Unfortunately we didn't have the second part of that working before (IE the [pull request](https://github.com/dotnet/sdk/pull/2085) was just merged last week), so it was necessary to specify the `RuntimeFrameworkVersion` for self-contained apps.

When we were designing how this worked we considered an alternative where instead of `RuntimeFrameworkVersion`, you would just use the `TargetFramework` to specify the patch.  If we had gone with that design, you could have set the `TargetFramework` to `netcoreapp2.0.5` in your library and you would have gotten an error if you tried to reference it from a project that just targeted `netcoreapp2.0`.  We decided that in most cases the patch version should be implicit/automatic, so we went with the other option.

**Comment by kouvel** [comment] 2018-04-04 02:47
I didn't realize that it was expected that providing --runtime switch to "dotnet build" implied publish. I typically specify --runtime but I don't intend to publish.

**Comment by kouvel** [comment] 2018-04-04 02:52
But in any case regarding the original issue about issuing errors where an unexpected runtime would be used, I think with the fix for defaults it would make it less of an issue. @BrendanGrant do you think this is reasonable enough to close on this issue?

**Closed** 2018-06-01 23:31 UTC
