### ISSUE TITLE
dotnet needs a command that works with project tools/commands

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2715] opened 2016-04-27 18:08 UTC
dotnet needs a command that allow list, install, remove tools from the project.

e.g. `dotnet tools list` would list all the tools installed into project.

**Comment by piotrpMSFT** [comment] 2016-04-27 22:54
@yishaigalatzer is this a capability that should be exposed through NuGet xplat?

**Comment by yishaigalatzer** [comment] 2016-04-27 22:58
I would think so

**Comment by svick** [comment] 2016-07-20 16:17
Is this a duplicate of #917?

**Comment by blackdwarf** [comment] 2016-08-07 15:03
@svick yes, it is. Closing as a dupe of #917.

**Closed by blackdwarf** 2016-08-07 15:03 UTC
