### ISSUE TITLE
dotnet migrate xproj files to csproj files succeed but .sln file does not update in sync

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#4701] opened 2016-11-14 03:35 UTC
Test the scenario on the build of d15rel/25909.2
Steps to reproduce:
• Copy this zip file from \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip, which contains a solution with .xproj files, to your machine and extract it;
• Open command prompt and navigate to the folder of your legacy project; 
• dotnet migrate 

Expected  behavior:
dotnet migrate succeeded and the .sln file update the ProjectReferences in sync. "dotnet restore" should be succeeded.

Actual behavior:
dotnet migrate succeeded replace the .xproj with .csproj, but the solution file still shows reference of .xproj file ;
1)If modifying the reference of .xsproj with .csproj in .sln files, save the file and restore succeeded from the solution level:
![dotnet_migrate_but slnfile_not_updated](https://cloud.githubusercontent.com/assets/22901391/20252301/e56bd086-aa5b-11e6-9eaa-04f0ffb22864.jpg)
2) From a solution level: dotnet build -->succeed
3) Even if modifying the .sln file, open the sln file still failed to download the files:
![failed_to_download_files](https://cloud.githubusercontent.com/assets/22901391/20252513/f4c1e654-aa5d-11e6-8bac-ee3c8e0754cb.jpg)

**Comment by jinujoseph** [comment] 2016-11-14 18:04
@piotrpMSFT is this dupe of #4632 ?

**Comment by piotrpMSFT** [comment] 2016-11-15 19:51
Yep, it's a dupe. Closing this one as the other is already assinged to a milestone.

**Closed by piotrpMSFT** 2016-11-15 19:51 UTC
