### ISSUE TITLE
.well-known folder not published by SDK 2.1.4

### ISSUE THREAD

**Issue by martincostello** [dotnet/cli#8483] opened 2018-01-26 14:14 UTC
## Steps to reproduce

Add a `.well-known` folder and files (such as `/.well-known/assetlinks.json`) file to the `wwwroot` of an ASP.NET Core project and publish it.

## Expected behavior

The `.well-known` folder is included in the `wwwroot` folder output from `dotnet publish`.

## Actual behavior

The `.well-known` folder is not included.

## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

This works in `2.0.3` but does not in `2.1.4`.

**Comment by dasMulli** [comment] 2018-01-26 14:38
Did you modify the csproj to include this file in any way? Or can you share a minimal project that reproduces this?
Tried to report on 2.0.0,2.0.3, 2.1.4 and a 2.1.100 preview and the file is never included by default when creating an empty web project.

That being said, there have been changes to how msbuild does globbing and exclude handling, but it's hard to tell what happened to your project without being able to reproduce it.

**Comment by martincostello** [comment] 2018-01-26 14:40
So this is the project I'm having trouble with:

https://github.com/martincostello/alexa-london-travel-site

It has this custom target to sort out the missing files, but it doesn't work anymore since since I updated from 2.0.3 to 2.1.4:

https://github.com/martincostello/alexa-london-travel-site/blob/d65fd2102deabfebb43713b1b539079dfd1182d2/src/LondonTravel.Site/LondonTravel.Site.csproj#L56-L60

**Comment by dasMulli** [comment] 2018-01-26 14:44
You could remove the `$(DefaultExcludesInProjectFolder)` from the include statement.

The SDK carries the following warning for it:
```xml
    <!-- WARNING: This pattern is there to ignore folders such as .git and .vs, but it will also match items included with a
         relative path outside the project folder (for example "..\Shared\Shared.cs").  So be sure only to apply it to items
         that are in the project folder. -->
    <DefaultExcludesInProjectFolder>$(DefaultItemExcludesInProjectFolder);**/.*/**</DefaultExcludesInProjectFolder>
```

However, the web SDK ignores it and applies it to all patterns.. 

@vijayrkn can the web SDK adding this exclude variable to patterns meant for non-project-root-content be considered a bug in the web SDK?

**Comment by stuart-lang** [comment] 2018-01-26 14:47
https://github.com/dotnet/sdk/commit/12bda7b843e6c9c5a3077c4068f720b9fb9551d3

^ here's the commit that introduced it, looks like it's by design

**Comment by martincostello** [comment] 2018-01-26 14:55
If this is an unintentional side-effect of something "that just worked" no longer working due to intended design changes, that's fine, but I'd like an "official won't-break-again" way to ensure my content is published if that is the case 😃

**Comment by stuart-lang** [comment] 2018-01-26 14:57
Nothing is future proof, but emptying that prop should fix it:
```xml
<PropertyGroup>
    <DefaultExcludesInProjectFolder></DefaultExcludesInProjectFolder>
</PropertyGroup>
```

**Comment by dasMulli** [comment] 2018-01-26 15:10
I wouldn’t do that (empty the prop) or you may end up with unexpected files.
Better remove the property from the include attribute.
Btw msbuild has a slightly different behavior in targets vs static items regarding include/exclude patterns. There was a change to them afaik (on mobile now)

**Comment by martincostello** [comment] 2018-01-26 16:21
I'll give that a try and report back.

**Comment by dasMulli** [comment] 2018-01-26 16:23
> I'd like an "official won't-break-again"

fyi I don't work for MS or .NET Foundation, so nothing I write is official.

My personal suggestion would be to add this in the csproj, without a target:

```xml
<ItemGroup>
  <Content Include="wwwroot\.well-known\**" CopyToPublishDirectory="PreserveNewest" Exclude="$(DefaultItemExcludes)" />
</ItemGroup>
```

**Comment by tannergooding** [comment] 2018-01-26 16:38
FYI. @dsplaisted

**Comment by martincostello** [comment] 2018-01-26 18:01
@dasMulli Thanks - that worked! 🎉

**Comment by livarcocc** [comment] 2018-02-14 18:48
I don't believe we have plans to change this again at the moment.

Also, given @dasMulli's workaround above, I am going to close this issue. If I got anything wrong, just comment and I can re-activate it.

**Closed by livarcocc** 2018-02-14 18:48 UTC
