### ISSUE TITLE
[DotNet.ProjectModel.Server] Get a global error and no other data if a lock file assembly no longer exists

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#1668] opened 2016-03-02 23:49 UTC
Create a new project in VS
close project after restore completes
rd  %userprofile%\.nuget
Open project

Get a global error about the missing dependency and we don't get normal pms messages like references and dependencies.

This error should only be included in the dependency diagnostics.

**Comment by troydai** [comment] 2016-03-09 08:32
@BillHiebert I'm not able to reproduce this issue with latest dotnet build 1672. Can you give it a try?

**Comment by troydai** [comment] 2016-03-17 17:53
Ping @BillHiebert

**Comment by troydai** [comment] 2016-03-22 23:12
@BillHiebert I'm going to close this one. Please reopen if you're able to repo.

**Closed by troydai** 2016-03-22 23:12 UTC
Labels: Investigate
