### ISSUE TITLE
Error message from dotnet.exe shows invalid characters "←[1m←[31m" on Windows Server 2012 R2

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#2609] opened 2016-04-20 19:39 UTC
## Steps to reproduce
1. Install "Windows x64 .NET Core SDK Installer" on Windows Server 2012 R2.
2. Run `dotnet foo`

## Expected  behavior
Error message printed in red text, like on Windows 10.

## Actual behavior
Error message starts and ends with invalid characters:
```
←[1m←[31mNo executable found matching command "dotnet-foo"←[39m←[22m
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002441)

Product Information:
 Version:     1.0.0-rc2-002441
 Commit Sha:  e8eaebdaeb

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by moozzyk** [comment] 2016-04-21 21:37
dupe of https://github.com/dotnet/cli/issues/2590 ?

**Closed** 2016-04-21 21:49 UTC
Labels: duplicate
