### ISSUE TITLE
req : target build to ARM32/64

### ISSUE THREAD

**Issue by ch0mik** [dotnet/cli#7625] opened 2017-09-10 19:51 UTC
## Steps to reproduce
none

## Expected  behavior
packages to deploy on ARM machines like RPi3/TegraK1 etc

## Actual behavior
none

## Environment data
`dotnet --info` output:

**Comment by wli3** [comment] 2017-09-13 20:25
Hi @ch0mik 

Could you give me more detail of the request? What is your scenario? To use CLI on arm or publish to arm and run it on? Or it is about nuget packages?

Core CLR does support arm https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

@KathleenDollard FYI

**Comment by livarcocc** [comment] 2017-09-25 21:31
I am marking this as a duplicate of https://github.com/dotnet/cli/issues/5289, which asks for support to running the SDK in ARM. Cross-compiling to ARM is already supported.

**Closed by livarcocc** 2017-09-25 21:31 UTC

**Comment by ch0mik** [comment] 2017-11-29 07:53
http://sq7mru.blogspot.com/2017/09/net-core-200-na-tegra-tk1.html - works ;)
