### ISSUE TITLE
Please provide symbols for .NET Core native modules.

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/cli#1218] opened 2016-02-04 03:39 UTC
At present there are no native symbols available for .NET Core native modules. Lack of symbols make it difficult in debugging .NET Core applications. 

The other option is to build .NET Core and use those symbols. However, that may not be feasible and  an option in most of the times.

**Comment by Raviuppa** [comment] 2016-02-04 03:41
@mikem8361, Can you please look into this request?

**Comment by blackdwarf** [comment] 2016-02-04 21:27
Hm, I'm wondering if this is something that should go against the coreclr repo?

**Comment by mikem8361** [comment] 2016-02-04 21:39
I'm trying to narrow down who/what/where the problem is.  When the release coreclr is built in the CI lab the binaries contains the symbols.  They seem to be stripped by the time they make it to the debian package.

**Comment by piotrpMSFT** [comment] 2016-02-05 19:14
Why are symbols for the CLI 'app' interesting? The CoreFx that ships in the Debian package is the 'dependencies' of the CLI itself. They are in no way used in conjunction with the end-user's applications. Are we wanting to debug the CLI itself?

**Comment by gkhanna79** [comment] 2016-04-01 06:41
I think it will be useful to get the symbols for all repos published. CLI's native pieces are the host components.

**Comment by markwilkie** [comment] 2016-05-10 21:52
@dagood is point person on this effort and has made excellent progress.

**Comment by dagood** [comment] 2016-05-11 17:01
From my point of view (not knowing much about native parts of CLI) this issue would be about CoreCLR, since I don't believe we strip out symbols from the CoreFX native libs right now.

In CoreCLR, release builds strip out symbols into a symbol package alongside the library package, but the TFS build ignores these packages and builds its own that doesn't include the symbols. The build pipeline will use the library and symbol packages built by the open CoreCLR build, so we'll naturally start delivering symbols when the build pipeline goes online.

I think I *could* get symbols published in TFS with a day or two of work, but I wonder if it's worth the effort when we're trying to switch to the build pipeline. @markwilkie Thoughts?

https://github.com/dotnet/coreclr/issues/1743 seems like a good place to track CoreCLR symbols. It's kind of specific to public MS Symbol Server, but availability through MyGet should at least unblock some people.

**Comment by mikem8361** [comment] 2016-05-11 17:03
@wtgodbe is working on exactly that: getting the coreclr switched to the new build pipeline and is making sure the symbol packages are being published.

**Comment by wtgodbe** [comment] 2016-05-11 17:08
Part of the build pipeline for CoreCLR includes publishing symbol packages to the Azure portal. You can see an example of that here - Check blob 20160510-01 or 20160510-02<https://ms.portal.azure.com/#blade/Microsoft_Azure_Storage/ContainersBlade/storageAccountId/%2Fsubscriptions%2F06962174-fd78-47a2-9cf5-96d1e3975117%2FresourceGroups%2Fdotnetbuild%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fdotnetbuildoutput>

-Will

On May 11, 2016, at 10:04 AM, Mike McLaughlin <notifications@github.com<mailto:notifications@github.com>> wrote:


@wtgodbe<https://github.com/wtgodbe> is working on exactly that: getting the coreclr switched to the new build pipeline and is making sure the symbol packages are being published.

-

**Comment by piotrpMSFT** [comment] 2016-12-07 22:36
@gkhanna79 since CoreFx is now packaged in core-setup repo, can you validate and close this? Otherwise, move to core-setup and close?

**Comment by gkhanna79** [comment] 2016-12-07 22:39
@Raviuppa Do you still have any outstanding questions since symbols for all native components for .NET Core are available in Azure blob and also available off Download center?

**Comment by Raviuppa** [comment] 2016-12-07 22:42
We are good Gaurav and can close this bug as resolved.

Thanks,
Ravi.

**Closed** 2016-12-07 22:42 UTC
Labels: build
