### ISSUE TITLE
linker error during dotnet compile --native

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#478] opened 2015-12-11 06:12 UTC
```
x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api>dotnet compile --native
Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe --native
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe --native
Process ID: 29540
Compiling dotnet-api for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.6712106

Input Assembly: x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\dotnet-api.dll
msvcrtd.lib(std_type_info_static.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
Linking of intermediate files failed.
< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe --native exited with 1 in 2555 ms.
```

**Comment by krwq** [comment] 2015-12-11 06:14
More verbose output:
```
x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api>dotnet-compile --native
Compiling dotnet-api for DNXCore,Version=v5.0
  Using Package dependency Microsoft.NETCore.Platforms 1.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\Microsoft.NETCore.Platforms\1.0.1-rc2-23608

  Using Package dependency Microsoft.NETCore.Targets 1.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\Microsoft.NETCore.Targets\1.0.1-rc2-23608

  Using Package dependency Microsoft.NETCore.Targets.DNXCore 5.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\Microsoft.NETCore.Targets.DNXCore\5.0.0-rc2-23608

  Using Package dependency Microsoft.Win32.Primitives 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\Microsoft.Win32.Primitives\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency NETStandard.Library 1.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\NETStandard.Library\1.0.0-rc2-23608

  Using Package dependency NETStandard.Platform 1.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\NETStandard.Platform\1.0.0-rc2-23608

  Using Package dependency Newtonsoft.Json 7.0.1
    Path: C:\Users\krwq\.dnx\packages\Newtonsoft.Json\7.0.1
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.AppContext 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.AppContext\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Collections 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Collections\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Collections.NonGeneric 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Collections.NonGeneric\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Collections.Specialized 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Collections.Specialized\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Console 4.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Console\4.0.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Diagnostics.Debug 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Diagnostics.Debug\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Diagnostics.Process 4.1.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Diagnostics.Process\4.1.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Diagnostics.Tools 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Diagnostics.Tools\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Diagnostics.Tracing 4.0.21-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Diagnostics.Tracing\4.0.21-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Dynamic.Runtime 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Dynamic.Runtime\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Globalization 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Globalization\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Globalization.Calendars 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Globalization.Calendars\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Globalization.Extensions 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Globalization.Extensions\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.IO 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.IO\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.IO.FileSystem 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.IO.FileSystem\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.IO.FileSystem.Primitives 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.IO.FileSystem.Primitives\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Linq 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Linq\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Linq.Expressions 4.0.10
    Path: C:\Users\krwq\.dnx\packages\System.Linq.Expressions\4.0.10
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Net.Primitives 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Net.Primitives\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Net.Requests 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Net.Requests\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Net.Sockets 4.1.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Net.Sockets\4.1.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Net.WebHeaderCollection 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Net.WebHeaderCollection\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.ObjectModel 4.0.10
    Path: C:\Users\krwq\.dnx\packages\System.ObjectModel\4.0.10
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Private.Uri 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Private.Uri\4.0.1-rc2-23608

  Using Package dependency System.Reflection 4.1.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Reflection\4.1.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Reflection.Emit 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Reflection.Emit\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Reflection.Emit.ILGeneration 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Reflection.Emit.ILGeneration\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Reflection.Extensions 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Reflection.Extensions\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Reflection.Primitives 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Reflection.Primitives\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Reflection.TypeExtensions 4.1.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Reflection.TypeExtensions\4.1.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Resources.ResourceManager 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Resources.ResourceManager\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime 4.0.21-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Runtime\4.0.21-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime.Extensions 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Runtime.Extensions\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime.Handles 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Runtime.Handles\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime.InteropServices 4.0.21-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Runtime.InteropServices\4.0.21-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Runtime.InteropServices.RuntimeInformation\4.0.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Runtime.Serialization.Primitives 4.0.0
    Path: C:\Users\krwq\.dnx\packages\System.Runtime.Serialization.Primitives\4.0.0
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Text.Encoding 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Text.Encoding\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Text.Encoding.Extensions 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Text.Encoding.Extensions\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Text.Encodings.Web 4.0.0-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Text.Encodings.Web\4.0.0-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Text.RegularExpressions 4.0.10
    Path: C:\Users\krwq\.dnx\packages\System.Text.RegularExpressions\4.0.10
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Threading 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Threading\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Threading.Tasks 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Threading.Tasks\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Threading.Timer 4.0.1-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Threading.Timer\4.0.1-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Xml.ReaderWriter 4.0.10
    Path: C:\Users\krwq\.dnx\packages\System.Xml.ReaderWriter\4.0.10
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

  Using Package dependency System.Xml.XDocument 4.0.11-rc2-23608
    Path: C:\Users\krwq\.dnx\packages\System.Xml.XDocument\4.0.11-rc2-23608
    Assembly: Microsoft.DotNet.ProjectModel.Compilation.LibraryAsset

Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-csc.exe @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile.dotnet-api.rsp"
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-csc.exe @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile.dotnet-api.rsp"
Process ID: 36168
Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\csc.exe -noconfig @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-csc.rsp"
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\csc.exe -noconfig @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-csc.rsp"
Process ID: 35636
< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\csc.exe -noconfig @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-csc.rsp" exited with 0 in 1342 ms.
< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-csc.exe @"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile.dotnet-api.rsp" exited with 0 in 1523 ms.

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.7648403

Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-native.exe --rsp "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-native.dotnet-api.rsp"
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-native.exe --rsp "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-native.dotnet-api.rsp"
Process ID: 35944
Input Assembly: x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\dotnet-api.dll
Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\corerun.exe "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\ilc.exe" "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\dotnet-api.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\System.Private.CoreLib.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\appdepsdk\*.dll" -out "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj"
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\corerun.exe "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\ilc.exe" "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\dotnet-api.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\System.Private.CoreLib.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\appdepsdk\*.dll" -out "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj"
Process ID: 36848
< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\corerun.exe "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\ilc.exe" "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\dotnet-api.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\System.Private.CoreLib.dll" -r "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\appdepsdk\*.dll" -out "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj" exited with 0 in 327 ms.
Running C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\bin\amd64\link.exe /NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /out:"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\native\dotnet-api.exe" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "X:\oss\cli-2\artifa
ts\win7-x64\stage2\bin\Runtime.lib" "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\bootstrapper.lib" "msvcrtd.lib" /MACHINE:x64 "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj"
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\bin\amd64\link.exe /NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /out:"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\native\dotnet-api.exe" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "X:\oss\cli-2\artifacts\wi
7-x64\stage2\bin\Runtime.lib" "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\bootstrapper.lib" "msvcrtd.lib" /MACHINE:x64 "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj"
Process ID: 36224
msvcrtd.lib(std_type_info_static.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
< C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\bin\amd64\link.exe /NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /out:"x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\bin\Debug\dnxcore50\native\dotnet-api.exe" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "X:\oss\cli-2\artifacts\wi
7-x64\stage2\bin\Runtime.lib" "X:\oss\cli-2\artifacts\win7-x64\stage2\bin\bootstrapper.lib" "msvcrtd.lib" /MACHINE:x64 "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-api.obj" exited with 1112 in 25 ms.
Linking of intermediate files failed.
< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile-native.exe --rsp "x:\oss\cli-2\test\Microsoft.DotNet.Tools.Api\obj\Debug\dnxcore50\dotnet-compile-native.dotnet-api.rsp" exited with 1 in 531 ms.
```

**Comment by krwq** [comment] 2015-12-11 08:58
related: https://github.com/dotnet/cli/pull/469

**Comment by brthor** [comment] 2015-12-11 18:53
@krwq See Here

https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-and-run-ilcompiler-in-console-shell-prompt.md

*Note: On Windows, please ensure you have VS 2015 installed to get the native toolset and work within a VS 2015 x64 Native Tools command prompt.*

#301 Is tracking the removal of this.

**Comment by piotrpMSFT** [comment] 2015-12-14 23:26
Looks like this is a duplicate of #301. Please reopen if this is wrong.

**Closed by piotrpMSFT** 2015-12-14 23:26 UTC
