### ISSUE TITLE
.NET Core SDK doesn't run in globalization invariant mode

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#8290] opened 2017-12-23 20:16 UTC
I wasn't able to get the .NET Core SDK to run in globalization invariant mode with Alpine.

See https://github.com/dotnet/dotnet-docker-nightly/pull/508

To repro, remove the last three lines of the Dockerfile.

Sample you can use for testing is at https://github.com/dotnet/dotnet-docker-samples/tree/alpine/dotnetapp-prod

**Comment by nguerrera** [comment] 2018-01-08 19:16
This is going to be fun to investigate.

**Comment by richlander** [comment] 2018-01-10 05:52
This issue may not be specific to Alpine. That may or may not be clear. Alpine is just the place I found it.

**Comment by nguerrera** [comment] 2019-07-24 01:11
Duplicate of https://github.com/dotnet/corefx/issues/28021

**Comment by nguerrera** [comment] 2019-07-24 01:12
This should be fixed now (see corefx duplicate).

**Closed by nguerrera** 2019-07-24 01:12 UTC
