### ISSUE TITLE
dotnet core on Bash on Unbuntu on Windows

### ISSUE THREAD

**Issue by rexebin** [dotnet/cli#3999] opened 2016-08-04 21:40 UTC
## Steps to reproduce

Install Bash on Ubuntu on Windows with the latest windows 10 1607

In Bash on Ubuntu on Windows:

```
dotnet new -t web
dotnet restore
dotnet run
```
## Expected  behavior

localhost:5000 should be up and I should be able to visit the template website in browser in windows with url: localhost:5000
## Actual behavior

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -98 EADDRINUSE address already in use) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -98 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
```
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

```
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by jasonwilliams200OK** [comment] 2016-08-04 23:30
Seems like port 5000 is already in use. If you change the port in `Properties/launchSettings.json` from 5000 to something else does it work? Try 5123 for example, then browse `http://localhost:5123`.

**Comment by rexebin** [comment] 2016-08-05 06:40
@jasonwilliams200OK I have tried that and no matter what port I use, always the same error.

**Comment by rexebin** [comment] 2016-08-05 06:47
It may be a bash bug.

**Comment by jasonwilliams200OK** [comment] 2016-08-06 07:43
@rexebin, seems like this is duplicate of https://github.com/Microsoft/BashOnWindows/issues/740, should be closed here and continue in BashOnWindows repo.

**Comment by cesarbs** [comment] 2016-08-08 17:39
Someone filed a similar issue on Kestrel: https://github.com/aspnet/KestrelHttpServer/issues/1035#issuecomment-238312039

I was able to start it by listening on `127.0.0.1` and `[::1]` instead of `localhost`.

**Comment by livarcocc** [comment] 2016-11-10 22:33
I don't believe this is a CLI issue.

**Closed by livarcocc** 2016-11-10 22:33 UTC
