### ISSUE TITLE
`dotnet.exe msbuild` exits code 1 even if MSBuild succeeds

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#9105] opened 2018-04-20 02:01 UTC
## Steps to reproduce
So far, this only reproduces on our Windows 2012 R2 machines, but **it is consistent**. I can get you access to a machine to investigate more.

We are trying to upgrade ASP.NET Core to build with the 2.1.300-preview3-008646 SDK. 
Previously we were building with 2.1.300-preview2-008530. https://github.com/aspnet/BuildTools/commit/ed5ca9de3c652347dbb0158a9a65eff3471d2114

## Expected  behavior

Exit code 0 when a build completes

## Actual behavior

dotnet.exe exits code 1, even though MSBuild succeeds.

```
[18:35:10]  EventNotification     | 
[18:35:10]  EventNotification     | Build succeeded.
[18:35:10]  EventNotification     |     0 Warning(s)
[18:35:10]  EventNotification     |     0 Error(s)
[18:35:10]  EventNotification     | 
[18:35:10]  EventNotification     | Time Elapsed 00:00:37.68
[18:35:11]  dotnet.exe failed with exit code: 1
[18:35:11]  At C:\b\w\6e78c7aba2f17cd5\.dotnet\buildtools\korebuild\2.1.0-rc1-15774\scripts
[18:35:11]  \common.psm1:11 char:9
[18:35:11]  +         throw "$cmdName failed with exit code: $exitCode"
[18:35:11]  +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[18:35:11]      + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit c 
[18:35:11]     ode: 1:String) [], RuntimeException
[18:35:11]      + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
```
![image](https://user-images.githubusercontent.com/2696087/39026843-fbb3a498-4403-11e8-99fd-38668d8285e4.png)

## Environment data
`dotnet --info` output:

2.1.300-preview3-008646

cc @muratg @pranavkm

**Comment by livarcocc** [comment] 2018-04-20 02:15
does this repro in older versions of the CLI? Like, 2.1.100 or 2.1.200?

also, cc @rainersigwald since the CLI is just surfacing the error code from MSBuild.

**Comment by natemcmaster** [comment] 2018-04-20 04:26
Hard to say. The repo in question uses netcoreapp2.1, which isn't supported in 2.1.200. The issue is definitely tied to updating from 2.1.300-preview2-008530 to 2.1.300-preview3-008646. I figured it's probably the underlying `dotnet MSBuild.dll` process actually returning non-zero, but figured I'd start this issue at the top of the stack in case there were changes to forwarding, telemetry, logging, etc that might affect this.

**Comment by muratg** [comment] 2018-04-20 04:52
Ugh. Is there even a workaround?

**Comment by natemcmaster** [comment] 2018-04-20 06:15
One clue: it appears to happen only when dotnet msbuild is launched as a child process of another dotnet msbuild process.

**Comment by kasper3** [comment] 2018-04-20 08:53
@natemcmaster, I have made smaller steps to repro, it seems like it is happening with CLI 2.1.10x as well as 2.1.300-preview3

Seems the behavior with `ContinueOnError = true` makes the difference.

parent.proj

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0" DefaultTargets="CallChild">
  <Target Name="CallChild">
    <MSBuild Projects="child.proj" ContinueOnError="false" />
  </Target>
</Project>
```

child.proj

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0" DefaultTargets="PrintError">
  <Target Name="PrintError">
    <Error Text="Error!" Condition="'$(CauseError)' == 'True'" />
  </Target>
</Project>
```

With `dotnet msbuild parent.proj /p:CauseError=true`, the process exits with non-zero code and with `dotnet msbuild parent.proj` (or `/p:CauseError=false`), it exists with code 0.

However, with `ContinueOnError="true"`, exit code is 0 regardless of the value of `/p:CauseError`.

Seems like this is by design; in real projects, the error will still show in red, but msbuild will keep going until the very end.

**Comment by rainersigwald** [comment] 2018-04-20 15:15
One possible change candidate: post-preview2, we turned on MSBuild node reuse on *nix by default, after fixing an issue with calling `dotnet msbuild` inside `dotnet msbuild`. That shouldn't have changed anything on Windows, but since the symptoms are so similar it's worth mentioning.

I'd be happy to take a look at the repro machine @natemcmaster. Would also be curious if setting `MSBUILDDISABLENODEREUSE=1` changes anything.

**Comment by livarcocc** [comment] 2018-04-23 20:32
Closing this one in favor of https://github.com/Microsoft/msbuild/pull/3215.

**Closed by livarcocc** 2018-04-23 20:32 UTC
