### ISSUE TITLE
Support for installing packages directly from the command line

### ISSUE THREAD

**Issue by odytrice** [dotnet/cli#4607] opened 2016-11-03 23:08 UTC
It would be nice to get the ability to do a `dotnet install Newtonsoft.Json` that would automatically add the reference to the project rather than having to crack open `project.json` or `csproj/fsproj`.

There'd probably be a switch to install tools like `dotnet install -t Microsoft.EntityFrameworkCore.Tools`

**Comment by svick** [comment] 2016-11-04 00:20
I think this is a duplicate of https://github.com/dotnet/cli/issues/4521 and https://github.com/dotnet/cli/issues/917.

**Comment by blackdwarf** [comment] 2016-11-09 12:40
@svick yes, it is. Closing as a dupe of #4521 . @odytrice as that issue suggest, we will be adding a command to add a reference to the project file.

**Closed by blackdwarf** 2016-11-09 12:40 UTC
