### ISSUE TITLE
dotnet user-secrets needs init, create or new command

### ISSUE THREAD

**Issue by spboyer** [dotnet/cli#9200] opened 2018-05-04 17:30 UTC
The `dotnet new` templates by default do not have the `<UserSecrets>` node in the ***.csproj** file. However when using Visual Studio and using the right-click -> Manage User Secrets 

![screen shot 2018-05-04 at 1 08 57 pm](https://user-images.githubusercontent.com/7681382/39641521-85d4a7b4-4f9c-11e8-9466-d1ff56db33cb.png)

The GUID is generated and the XML is inserted.

```xml
 <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>28fedc3d-d7e3-4a78-9328-b0740315fcdd</UserSecretsId>
  </PropertyGroup>
```

Using the CLI, there is not a way to do this easily. Furthermore, if the developer is brand new a goes looking for the documented folders where the `.microsoft/usersecrets/<guid>/secrets.json` might exists; they would not find it. It doesn't exist until first create leading to more confusion.

Using MacOS one might use the following command(s).

```bash
myid=$(uuidgen)     

# add password to secrets
dotnet user-secrets set "Kestrel:Certificates:Development:Password" "P@55w0rd" --id $myid

# get the id to add the csproj
echo $myid
```

Should add a **create** or **init** method which initializes the folder and inserts the XML. As a stretch goal would be nice to add **edit** to open in VS Code, vim etc 

## Current Version Info.

```bash
User Secrets Manager 2.1.0-preview2-30571

Options:
  -p|--project <PROJECT>              Path to project. Defaults to searching the current directory.
  --id                                The user secret ID to use.

Commands:
  clear   Deletes all the application secrets
  list    Lists all the application secrets
  remove  Removes the specified user secret
  set     Sets the user secret to the specified value
```
@natemcmaster @livarcocc

**Comment by natemcmaster** [comment] 2018-05-04 17:35
Dupe of https://github.com/aspnet/DotNetTools/issues/166

**Comment by livarcocc** [comment] 2018-05-04 17:35
thanks @natemcmaster I was actually looking for it under aspnet/home.

**Closed** 2018-05-04 17:35 UTC

**Comment by spboyer** [comment] 2018-05-04 17:42
Whoops. Such a nice write up too :-)
