### ISSUE TITLE
Resgen crashes

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#419] opened 2015-12-07 17:33 UTC
1. Clone [UserSecrets](https://github.com/aspnet/usersecrets)
2. `cd src\Microsoft.Extensions.Configuration.UserSecrets`
3. `dotnet compile`

Result:

```
PS E:\temp\usersecrets\src\Microsoft.Extensions.Configuration.UserSecrets> dotnet compile
Compiling Microsoft.Extensions.Configuration.UserSecrets for .NETFramework,Version=v4.5.1

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5
f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.DotNet.Tools.Resgen.Program.WriteResourcesFileIfNotEmpty(String resxFilePath, String outputFile)
   at Microsoft.DotNet.Tools.Resgen.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Resgen.Program.Main(String[] args)
Compiling Microsoft.Extensions.Configuration.UserSecrets for .NETPlatform,Version=v5.4
```

**Comment by piotrpMSFT** [comment] 2015-12-07 18:58
This is a duplicate of #408

**Closed by piotrpMSFT** 2015-12-07 18:58 UTC
