### ISSUE TITLE
restore3 doesn't handle multiple source options

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#4312] opened 2016-10-04 23:12 UTC
## Steps to reproduce
`dotnet restore3 -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -s https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json`

## Expected  behavior
Should use multiple sources.

## Actual behavior
```
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch: https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json

For switch syntax, type "MSBuild /help"
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003748)

Product Information:
 Version:            1.0.0-preview3-003748
 Commit SHA-1 hash:  7632cd3502

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment] 2016-10-05 01:34
@rrelyea @emgarten

**Comment by emgarten** [comment] 2016-10-05 18:02
Dupe of https://github.com/dotnet/cli/issues/4252

**Comment by livarcocc** [comment] 2016-10-08 22:22
Closing this one. Let's track it at #4252.

**Closed by livarcocc** 2016-10-08 22:22 UTC
