### ISSUE TITLE
beta-001672 fails to restore packages

### ISSUE THREAD

**Issue by mrmeek** [dotnet/cli#1770] opened 2016-03-09 17:05 UTC
## Steps to reproduce
Download and install latest beta (001672) (windows msi)
dotnet new
dotnew restore

## behavior
>log  : Restoring packages for C:\source\temp\DotNetCoreMvc03\project.json...
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='NETStandard.Library'
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23901) but ended up with NETStandard.Library 1.0.0-rc2-23907.
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Security.Cryptography.X509Certificates'
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Security.Cryptography.Cng'
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Security.Cryptography.Algorithms'
info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Security.Cryptography.Encoding'
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23901) but ended up with NETStandard.Library 1.0.0-rc2-23907.
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23901) but ended up with NETStandard.Library 1.0.0-rc2-23907.
error: Unable to resolve runtime.win7.System.Security.Cryptography.Algorithms (>= 4.0.0-rc2-23907) for .NETStandardApp,Version=v1.5 (win7-x64).
error: Unable to resolve runtime.win7.System.Security.Cryptography.Encoding (>= 4.0.0-rc2-23907) for .NETStandardApp,Version=v1.5 (win7-x64).
error: Unable to resolve runtime.win7.System.Security.Cryptography.Algorithms (>= 4.0.0-rc2-23907) for .NETStandardApp,Version=v1.5 (win7-x86).
error: Unable to resolve runtime.win7.System.Security.Cryptography.Encoding (>= 4.0.0-rc2-23907) for .NETStandardApp,Version=v1.5 (win7-x86).

## Environment data
`dotnet --version` output:
> .NET Command Line Tools (1.0.0-beta-001672)
>
Product Information:
 Version:     1.0.0-beta-001672
 Commit Sha:  12dd8d6112
>
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

**Comment by mrmeek** [comment] 2016-03-09 17:09
I also have another project that looks like this

nuget.config:
```xml
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
  </packageSources>
</configuration>
```

project.json:
```json
"dependencies": {
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-*",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
        "Microsoft.EntityFrameworkCore": "1.0.0-rc2-*",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-*",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-*"
    },

    "tools": {
        "dotnet-ef":  "1.0.0-rc2-*"
    },
    
    "frameworks": {
        "dotnet5.6": {
            "imports": [
                "portable-net451+win8"
            ],
            "dependencies": {
                "NETStandard.Library": "1.0.0-*"
            }
        }
    }
```

fails with
> error: Unable to resolve Microsoft.AspNetCore.Diagnostics (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.AspNetCore.Hosting (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.AspNetCore.IISPlatformHandler (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.AspNetCore.Mvc (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.Extensions.Logging.Console (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.Extensions.Logging.Debug (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.EntityFrameworkCore (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.EntityFrameworkCore.SqlServer (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve Microsoft.EntityFrameworkCore.SqlServer.Design (>= 1.0.0-rc2) for .NETPlatform,Version=v5.6.
error: Unable to resolve NETStandard.Library (>= 1.0.0) for .NETPlatform,Version=v5.6.

Seems to have begun occurring when I updated from yesterday's cli build to this morning's build. Could be coincidence, monikers changed? problems in latest packages on dotnet-core/aspnetcidev feeds?

**Comment by naamunds** [comment] 2016-03-10 22:00
I am hitting this issue on Ubuntu with beta-001695.  It looks like the issue may be that NuGet is not using the NuGet.config that's in the same directory as the app (the directory where `dotnet restore` is run from).  The end of the `dotnet restore` output shows:

```
NuGet Config files used:
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

Whereas on beta-001638, where it works, the end of the output shows:

```
NuGet Config files used:
    /hwapp/NuGet.Config
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
```

**Comment by mrmeek** [comment] 2016-03-10 22:30
I agree, @naamunds. I didn't post the whole output in my second example, but, looking back it appears it's only checking the default nuget feed and not the myget feeds I manually defined in nuget.config.

The issue also appears to exist in betas 0.1673 and 0.1694. I rolled back to 0.1665 which was the previous latest working build I had on hand.

**Comment by piotrpMSFT** [comment] 2016-03-10 22:51
@emgarten it looks like a regression in NuGet xplat. Can you please take a look?

**Comment by brthor** [comment] 2016-03-10 22:55
I hit the same issue on osx10.11 where it seemed the projectlocal / cwd nuget.config wasn't getting picked up.

**Comment by emgarten** [comment] 2016-03-10 23:09
This has been fixed in NuGet.
https://github.com/NuGet/Home/issues/2265

The work around is to copy the NuGet.Config in the project directory to the parent directory.

**Comment by piotrpMSFT** [comment] 2016-03-10 23:09
I also spoke with someone that is seeing this issue intermittently. Is everyone else getting a 100% repro?

**Comment by piotrpMSFT** [comment] 2016-03-10 23:09
thanks @emgarten is a build available for us to pick up?

**Comment by piotrpMSFT** [comment] 2016-03-10 23:10
leaving issue open until it's fixed in CLI repo :)

**Comment by MichaelSimons** [comment] 2016-03-11 17:23
@emgarten, @piotrpMSFT - Is there any discussion on what engineering changes (e.g. tests) could be made to ensure regressions like this don't happen in the future?  This seems like a pretty core scenario to break.

**Comment by emgarten** [comment] 2016-03-11 19:31
@MichaelSimons there are tests for this scenario in NuGet now.

**Comment by mrmeek** [comment] 2016-03-16 15:10
This appears to be working again in beta 0.1806, issue can probably be closed

**Closed** 2016-03-16 20:05 UTC
Labels: blocking-partner, blocking-release, bug
