### ISSUE TITLE
Cannot publish app when net461 libraries are used

### ISSUE THREAD

**Issue by DOMZE** [dotnet/cli#8477] opened 2018-01-25 21:28 UTC
## Steps to reproduce
Have a .NET Framework 4.6.1 library, call it LIBA, with Microsoft.Office.Interop.Excel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL

This library is referenced in another library (.NET Framework 4.6.1) call it LIBB.
Add LIBB as a reference to an ASP.NET Core 2.0 project.

## Expected  behavior
dotnet restore works
Build the project using MSBuild works
dotnet publish works

## Actual behavior
dotnet restore works
Build the project using MSBuild works
dotnet publish fails

C:\Program Files\dotnet\sdk\2.1.4\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Office.Interop.Excel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment] 2018-01-25 23:04
@nguerrera can you take a look at this issue and triage as appropriate?

**Comment by DOMZE** [comment] 2018-02-01 19:37
Any updates? @livarcocc @nguerrera

**Comment by nguerrera** [comment] 2019-07-24 00:56
.NET Core msbuild cannot resolve COMReference or resolve references from the GAC.

You will need to use the full framework version of MSBuild at this time. It is still possible to publish on the command line using msbuild.exe instead of msbuild.

Use `msbuild /restore /t:Publish` instead of `dotnet publish`.

**Comment by nguerrera** [comment] 2019-07-24 00:57
Duplicate of https://github.com/microsoft/msbuild/issues/3986

**Closed by nguerrera** 2019-07-24 00:57 UTC
