### ISSUE TITLE
Add dotnet-build to Debian package

### ISSUE THREAD

**Issue by KodrAus** [dotnet/cli#778] opened 2016-01-10 07:39 UTC
I'm not too sure what the cli is actually trying to do here, but if I try to run a command that doesn't exist on Ubuntu, like `dotnet build`, I get the following error:

```
dotnet build

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted (core dumped)
```

Which looks like a bug trying to format an actual error message?

**Comment by brthor** [comment] 2016-01-11 20:59
I think there's two bugs here:
1. `dotnet build` isn't present on Ubuntu (Did you install via apt-get)?
2. Duplicate of #118 (Which should be resolved as of today)

**Comment by shahid-pk** [comment] 2016-01-11 21:51
i installed it on ubuntu from .deb found  on the read me page of this repo a few days ago [when incremental compilaton prs were merged]. I also got exactly this , 'dotnet compile' however worked so i reverted back stable :smile: i mean the version that is going to be stable. 
Could it be that ci is not creating .deb packages and they are older ?

**Comment by KodrAus** [comment] 2016-01-11 22:19
Hadn't seen #118 I think that's the main issue I was having. I did install via apt-get, but wasn't actually expecting `dotnet build` to be there. I just typed it without thinking and was thrown by the exception I got back.

`dotnet build` works just fine.

**Comment by blackdwarf** [comment] 2016-01-11 23:43
Renaming and putting @brthor  on it.

**Closed** 2016-01-12 22:50 UTC
Labels: bug, in progress
