### ISSUE TITLE
Cannot complete first run when using small tmpfs for /tmp: "No space left on device" error

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#3623] opened 2016-06-17 00:05 UTC
## Steps to reproduce
1. Create a Fedora 23 machine with 1GB RAM. This, by default, creates /tmp using the in-memory tmpfs set to 500 MB.
2. Run `dotnet (anything)` to trigger first run nuget cache priming
## Expected  behavior

Prime nuget cache succeeds
## Actual behavior

This fills /tmp and crashes. There is no obvious way for user to opt-out of first run.

```
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2628 ms
Expanding 74%
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (No space left on device)) (One or more errors occurred. (No space left on device)) (No space left on device) (No space left on device) ---> System.IO.IOException: No space left on device
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream.WriteNative(Byte[] array, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.FlushWriteBuffer()
   at System.IO.UnixFileStream.Dispose(Boolean disposing)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Compression.ZipArchive.CloseStreams()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at System.IO.Compression.ZipArchive.Dispose()
   at Microsoft.DotNet.Archive.IndexedArchive.ZipOperation.Execute()
   at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
   at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

After run:

```
$ df -h 
Filesystem                                     Size  Used Avail Use% Mounted on
tmpfs                                          495M  495M  4.0K 100% /tmp
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     fedora
 OS Version:  23
 OS Platform: Linux
 RID:         fedora.23-x64
```
## Changes to consider
- Put the env variable in first run message so users more easily find out how to skip this
- Allow specifying which directory to use during extraction
- Cleanup tmp dir if extraction fails
- Run extraction into nuget cache directly instead of into tmp dir first.
## Workaround

Set environment variable DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true permanently (e.g. add to .bashrc or something).

**Comment by brthor** [comment] 2016-06-17 15:57
@livarcocc @ericstj 

I'm not sure what the better workaround is if tmp is too small for the unpacking. Maybe unpack somewhere under `~` and delete it later?

**Comment by livarcocc** [comment] 2016-06-17 20:26
you can use the DOTNET_SKIP_FIRST_TIME_EXPERIENCE env variable to not run the offline restore and unblock you for now. Though I am not sure what we can do automatically to get around this. Suggestions?

**Comment by ericstj** [comment] 2016-06-17 20:31
we use the disk for two things during extraction:
1. expanding lzma to archive
2. extracting archive to temporary feed

For 1 we could do it in memory instead.  I was doing that felt that it used too much memory which could cause OOMs.
For 2 we could skip the restore phase and just write directly to the packages folder (if we know what that is).  I believe we're not doing that today because @livarcocc didn't want this step digging into the NuGet APIs to get the package folder out.

Alternatively we could put our temp files somewhere in the packages directory which should have plenty of space, but if we're doing that I'd argue for just extracting there directly.

**Comment by ericstj** [comment] 2016-06-23 15:11
In addition to these suggestions we should just skip the priming and cleanup if we run out of space.  It's non-essential and better not to block progress.

**Comment by ericstj** [comment] 2016-06-23 19:07
Even better, predict when we'll run out of space so that we don't even get close.

**Comment by docesam** [comment] 2016-10-30 22:01
i was able to bypass this by issuing the command 
sudo umount /tmp/
it worked for now

**Comment by piotrpMSFT** [comment] 2016-11-15 19:47
I just linked #3995 which is another instance where first run might fail but should not be blocking. Let's track both here.

**Comment by binki** [comment] 2016-11-15 21:17
@piotrpMSFT Please reopen #3995 or explain how it is a dupe—I don’t think it’s a dupe. Thanks.

**Comment by piotrpMSFT** [comment] 2016-11-16 02:53
@binki just looked at that one and confirmed. That issue was also affected by this one, but also shows remaining symptoms.

**Comment by Leathal1** [comment] 2017-07-11 02:56
I just had the same happen to me.  I pasted below.  I tried to issue the command as sudo umount /tmp/ as @docesam says but it does nothing.

Could you elaborate on how I would "Set environment variable DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true permanently (e.g. add to .bashrc or something)." as @natemcmaster suggested?

```
Unhandled Exception: System.IO.IOException: No space left on device
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted
```

**Comment by omajid** [comment] 2017-08-15 21:10
> Could you elaborate on how I would "Set environment variable DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true permanently (e.g. add to .bashrc or something)."

This depends on what shell you are using. If you don't know, it is probably bash. For that, add the following line to your `~/.bashrc` file. This is a file named `.bashrc` in your home directory. If the file doesn't exist, create it.

    export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

Then log out and login again. You can verify that this worked by doing:

    env | grep DOTNET

You should see:

    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

When you run `dotnet` now, you shouldn't see the first run message or the error.

**Comment by livarcocc** [comment] 2018-09-22 04:57
We have removed the lzma cache expansion logic from the 3.0 CLI already. Closing this issue.

**Closed by livarcocc** 2018-09-22 04:57 UTC
Labels: bug
