### ISSUE TITLE
Visual Studio 2015 throws build error when configuration contains space

### ISSUE THREAD

**Issue by whymatter** [dotnet/cli#3607] opened 2016-06-16 10:44 UTC
## Steps to reproduce
- Create a new .NET Core ConsoleApplication (or asp.net 5 app doesn't matter)
- Create a new build configuration with a space character i.e. "Debug Test"
- Compile the project using visual studio 2015

## Expected  behavior
- build succeeds 

## Actual behavior
- build fails

The output window logs the following line:
`C:\Program Files\dotnet\dotnet.exe build "[pathToProject]" --configuration Debug Test --no-dependencies`

And the error message:
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Couldn't find 'project.json' in 'Test'`

The error is that is executes dotnet.exe using
`--configuration Debug Test` and not
`--configuration "Debug Test"`

if i execute the command manually with quotation marks then it workes.
I know this is more an issue of visual studio 2015 that corecli but I just don't know the right place for that.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

## Visual Studio data

```
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038
```
Installed products:

```
Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA943
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA943
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA943
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.209.60613.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft .NET Core Tools (Preview 1)

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

MySQL for Visual Studio   1.2.6
Data design and management tools for MySQL.  Copyright © 2007-2015 Oracle, Inc.

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Web Essentials 2015.2   2.0.214
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015


```

**Comment by blackdwarf** [comment] 2016-07-23 06:53
@whymatter does this repro with the latest version of tooling?

**Comment by whymatter** [comment] 2016-07-23 22:00
@blackdwarf i will test this tomorrow

**Comment by whymatter** [comment] 2016-07-25 20:54
I installed 1.0.0-preview3-003171 (Nightly - 6/17/16) and removed all previous versions but it hasn't fixed anything...

`D:\Program Files\dotnet\dotnet.exe build "<project-path>" --configuration Debug Test --no-dependencies`

It still executes --configuration Debug Test and not --configuration **"**Debug Test**"**

**Comment by blackdwarf** [comment] 2016-07-25 22:43
@whymatter what happens when you put the quotes on the `Debug Test` on the command line? Your command would then become `D:\Program Files\dotnet\dotnet.exe build "<project-path>" --configuration "Debug Test" --no-dependencies`

**Comment by whymatter** [comment] 2016-07-26 17:28
```
projectroot>"D:\Program Files\dotnet\dotnet.exe" build "." --configuration "Debug Test" --no-dependencies
Project CloudsWebApp (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling CloudsWebApp for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.3125477



projectroot>"D:\Program Files\dotnet\dotnet.exe" build "." --configuration Debug Test --no-dependencies
Couldn't find 'project.json' in 'Test'
```

**Comment by blackdwarf** [comment] 2016-07-27 03:40
@whymatter this is actually by design. What is happening is that `dotnet build` is considering `Test` to be a directory that it should search for `project.json` to build because there is a space there. In most shells, you will have to quote the spaces to make sure that they are interpreted as a single string (or use some other means of escaping the space character). This is why it is usually recommended to use single words for properties that you will be passing on the command line; either that or you quote the string. 

**Example:** Consider the following example in zsh on macOS where I want to create a directory named `new app`. The first command will give me 2 directories named `new` and `app` respectively. 

```console
~/Experiments/test ⌚ 20:34:50 $ mkdir new app
~/Experiments/test ⌚ 20:34:54 $ ls
rwxr-xr-x  2 root  staff    68B Jul 26 20:34 app/
drwxr-xr-x  2 root  staff    68B Jul 26 20:34 new/
```

If I quote the string, I get what I want:

```console
~/Experiments/test ⌚ 20:34:55 $ mkdir "new app"
~/Experiments/test ⌚ 20:35:51 $ ls

drwxr-xr-x  2 root  staff    68B Jul 26 20:34 app/
drwxr-xr-x  2 root  staff    68B Jul 26 20:34 new/
drwxr-xr-x  2 root  staff    68B Jul 26 20:35 new app/
```

This behavior is the same in PowerShell. 

I will close this issue as "by design".

**Closed by blackdwarf** 2016-07-27 03:40 UTC

**Comment by whymatter** [comment] 2016-07-27 17:19
And now a user is unable to use a configuration name without spaces, but visual studio allows it ...
And it just says build failed, no message telling the user to change the configuration name.

**Comment by blackdwarf** [comment] 2016-07-27 17:24
@whymatter I'm not sure I follow your last comment. Could you provide more details?

**Comment by whymatter** [comment] 2016-07-27 17:45
@blackdwarf I mean it's possible to create a configuration named Debug Test in Visual Studio. But it's not possible to build a project using this configuration. I believe this is very bad..

If an user is able to create the configuration Debug Test, then he should be able to build with this configuration. But what he get's is just a strange error message....
