### ISSUE TITLE
Build CLI on Ubuntu from a clean environment requires too many apt-get install

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1974] opened 2016-03-21 19:56 UTC
### Repo
1. Set up clean Ubuntu OS clone the CLI repo and run `./build.sh`
2. Over the course of the building, user is prompted to `sudo apt-get install` different packages. The prompts don't happen together. As a result the entire build process keeps being interrupted and new package needs to be installed to try again.

**Comment by brthor** [comment] 2016-03-21 20:34
What do you recommend?

Multiple tiers here, we have a prereq check in the pre-build scripts, in the install scripts, and in the build itself.

**Comment by troydai** [comment] 2016-03-21 21:11
A script for prerequisite check. List the missing packages.

**Comment by troydai** [comment] 2016-03-21 21:13
Is the prereq check executed? All the required packages check should happen together ahead of the build process. So user is interrupt once for all.

**Comment by brthor** [comment] 2016-03-21 21:14
I think the answer for this is in the install scripts cc @krwq 

Our build does a pre-req check but the issue is that the build itself needs some of the pre-reqs. The install script seems like the most obvious (and generally useful) place for this to happen.

**Comment by blackdwarf** [comment] 2016-07-29 15:05
Are we still going to do something about this? If not, I suggest we close the issue.

**Comment by brthor** [comment] 2016-08-01 17:45
This doesn't seem like a pressing issue. 

For a complete list of packages needed to run the build one could look at our dockerfiles
https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/docker/ubuntu.14.04/Dockerfile

or even use them to run their build.

**Comment by blackdwarf** [comment] 2016-08-01 17:49
Then closing it is. :)

**Closed by blackdwarf** 2016-08-01 17:49 UTC
