### ISSUE TITLE
Publish fails but reports success when NuGet retore fails on invalid package path

### ISSUE THREAD

**Issue by MV10** [dotnet/cli#9760] opened 2018-07-29 20:36 UTC
Publishing from Visual Studio (which I assume uses the cli under the hood). I had an extra NuGet target set up for some testing I was doing in a different solution, and I forgot to remove it when I was done and had deleted the other solution. When I published this other project, the Output window showed "Publish: 1 succeeded" immediately after the line reporting the NuGet restore failed against the missing path.

VS 2017 15.7.5, dotnet 2.1.302, Win 10.0.17134

**Comment by nguerrera** [comment] 2018-07-31 21:30
@vijayrkn @nkolev92

**Comment by vijayrkn** [comment] 2018-08-01 00:33
Can you please share the full output from output window?

**Comment by MV10** [comment] 2018-08-01 19:10
I can no longer reproduce this. After reporting it here, I removed the invalid package source. I pulled up the same solution just now and added a source pointing to an invalid path, but now the publish succeeds normally.

**Comment by nguerrera** [comment] 2018-08-01 23:45
OK. thanks @MV10. Since we don't have a repro, I'm closing this for now, but if you or anyone else hits this again and can provide steps to reproduce it, please let us know and we can reopen this.

**Closed by nguerrera** 2018-08-01 23:45 UTC
