### ISSUE TITLE
Framework imports in app have to match dependent libraries 

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2641] opened 2016-04-22 15:47 UTC
## Steps to reproduce
gunzip imports.tar.gz
tar -xf imports.tar

The scenario is the following... Project A is an App and has no additional imports declared for NetCoreApp1.0.  Project B is a library and includes "dnxcore50" in order to support its nuget dependencies.

When Project A takes a dependency on Project B, A's imports must also include "dnxcore50" in order to restore/build.  But why?  Is it not sufficient that Project B's framework dependency NetStandard1.5 not sufficient for Project A to pickup the dependency without having to make any additional project.json changes?

## Expected  behavior
Project A should be able to take a dependency on Project B without having to add "imports" : "dnxcore50".

## Actual behavior
Project A must include "imports": "dnxcore50"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
[imports.tar.gz](https://github.com/dotnet/cli/files/232139/imports.tar.gz)

**Comment by davidfowl** [comment] 2016-04-22 16:08
This is by design because we don't want to let imports flow transitively. The goal was to force people to feel enough pain to get package authors to support the right target frameworks in their packages.

**Comment by jeffschwMSFT** [comment] 2016-04-22 16:16
@davidfowl in this case it is the developer not package owner that is feeling the pain. :(

**Comment by piotrpMSFT** [comment] 2016-04-25 23:45
Since this is by-design, I'm closing the issue.

**Closed by piotrpMSFT** 2016-04-25 23:45 UTC

**Comment by jeffschwMSFT** [comment] 2016-04-26 16:40
To be honest, I do not fully understand the rationale.  However, I have found another case that is more mainline that feels just as broken in the same way.

In my case I have a NetCoreApp and a NetStandard.Library.  The NetStandardLibrary has a reference to System.Diagnostics.Process (which is part of NetCoreApp but not NetStandard.Library).  When the app depends on the library I get a restore error: unable to resolve System.Diagnostics.Process.  This feels like the same situation.

**Comment by Petermarcu** [comment] 2016-04-26 17:01
@jeffschwMSFT , I believe I've seen this before. You really shouldn't get a restore error just because you are referencing a library that is also in a metapackage you reference. Can you file that issue?
