### ISSUE TITLE
ProjectLoadContext isn't resolving for portable apps

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#2289] opened 2016-04-05 22:25 UTC
I'm working on the `dotnet-ef` tool, and using the `ProjectLoadContext` to load the project's assembly. See the code that [creates the ProjectContext](https://github.com/aspnet/EntityFramework/blob/dev/src/dotnet-ef/ReflectionOperationExecutor.cs#L238). Everything appears to be working fine when I use the tool with standalone app projects, but when I switch the projects to be portable apps, I start getting exceptions like the following.

* Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
* Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

The `Microsoft.Data.Sqlite` package should bring in `sqlite3.dll`. If run the portable app, everything works; it's just the `ProjectLoadContext` that seems to be having problems.

## Environment data

    .NET Command Line Tools (1.0.0-beta-002202)

    Product Information:
     Version:     1.0.0-beta-002202
     Commit Sha:  60b23d5115

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14295
     OS Platform: Windows
     RID:         win10-x64

**Comment by natemcmaster** [comment] 2016-04-06 20:02
See #2315 for more details on reproducing the error. This blocks Entity Framework design-time tools that need to connect to a database.

**Comment by natemcmaster** [comment] 2016-04-06 20:35
Source of the issue:
## Expected
`AssemblyLoadContext` should contain `sqlite3.dll` from Microsoft.Data.Sqlite's "win7-x64" native assets.
```
        "runtimeTargets": {
          "runtimes/win7-x64/native/sqlite3.dll": {
            "assetType": "native",
            "rid": "win7-x64"
          },
          "runtimes/win7-x86/native/sqlite3.dll": {
            "assetType": "native",
            "rid": "win7-x86"
          }
        }
```

`AssemblyLoadContext` should contain `Sqlite.Data.SqlClient` from System.Data.SqlClient "win7" runtime asset.
```
          "runtimes/win7/lib/netstandard1.3/System.Data.SqlClient.dll": {
            "assetType": "runtime",
            "rid": "win7"
          }
```
## Actual
Contains neither.

**Comment by natemcmaster** [comment] 2016-04-06 22:13
Discussed with @anurse. May be able to workaround using dependency context instead.

**Comment by anurse** [comment] 2016-04-06 22:25
Yeah, we'll need to convert ProjectContextLoader to be based off the DependencyContext, since that is what handles the loading of portable frameworks

**Comment by natemcmaster** [comment] 2016-04-06 23:42
Is deps.json supposed to have the RID fallback? In my samples of standalone and portable, deps.json has no runtimes section.

**Comment by natemcmaster** [comment] 2016-04-07 00:09
Complicated by https://github.com/dotnet/cli/issues/2327

**Comment by anurse** [comment] 2016-04-07 17:14
Libraries within the portable target for a `.deps.json` that have runtime-specific assets should have a `runtimeTargets` section. The `DependencyContext` should be abstracting all of that though.

**Comment by natemcmaster** [comment] 2016-04-07 17:28
> The RID fallback data is in the shared framework's deps file.

It is, but I've still been unable to actually get rid fallbacks from `DependencyContext`. For now, I'm working around by hard-coding well-know RID graphs and re-implementing `ProjectContext.CreateLoadContext()` to include native/runtime assets.

**Comment by anurse** [comment] 2016-04-07 17:45
You have to load the shared framework DependencyContext and merge it. I think the DependencyContextLoader does that for you, but if you're using the reader directly you don't get that behavior.

**Comment by natemcmaster** [comment] 2016-04-07 17:47
Yes, DependencyContextLoader.Default should, but at design time, it's not able to locate the shared framework (at least in 2202). This means I get `null` for DependencyContext. cc @pakrym is this a bug?

**Comment by natemcmaster** [comment] 2016-04-07 17:49
cc https://github.com/natemcmaster/EntityFramework/blob/f859b720bdec85a1c7cee30a1e76190af4b37787/src/dotnet-ef/LoaderProjectContextExtensions.cs

**Comment by anurse** [comment] 2016-04-07 18:25
Unfortunately, DependencyContext is only able to locate the shared framework for the application that is currently running (because the host fills in an AppDomain property with the path)... Not sure the best way to solve that...

**Comment by anurse** [comment] 2016-04-11 17:27
The changes in dotnet/cli have been merged. @natemcmaster : let me know if you need anything else from us to get things working.

**Comment by natemcmaster** [comment] 2016-04-11 17:36
Can we leave this open? I believe we still need to make changes to LoaderProjectContextExtensions to fully fix this. For now, EF will work around with these changes: https://github.com/aspnet/EntityFramework/pull/5002

**Comment by anurse** [comment] 2016-04-11 17:48
Ok, but those changes can be made post-RC2. I'll retarget the bug and reopen.

**Comment by natemcmaster** [comment] 2016-04-12 01:29
@anurse Found a new bug in ProjectLoadContext. `ProjectLoadContext._nativeLibraries` currently stores a dictionary of native libraries to the path. e.g. `{"sni", "C:\super\long\path\to\sni.dll" }`. But, when `ProjectLoadContext.LoadUnmanagedDll(string unmanagedDllName)` is called, `unmanagedDllName == "sni.dll"`. The dictionary `_nativeLibraries` doesn't strip of the ".dll" and accordingly can't load the user's native library.

Thanks to @schellap for helping us find this.

**Comment by anurse** [comment] 2016-04-12 16:53
Oof, good catch. For RC2 you're still using your own copy of the load context code, right?

**Comment by natemcmaster** [comment] 2016-04-12 16:55
Yes, for now I've implemented our own load context in EF.

**Comment by natemcmaster** [comment] 2016-04-12 18:59
Adding cref here to https://github.com/dotnet/corefx/issues/7683 to track potential changes.

**Comment by natemcmaster** [comment] 2016-05-20 23:19
@anurse have you had a chance to make any progress on this?

**Comment by anurse** [comment] 2016-05-24 15:35
No, I've been OOF for the past few days. I'm back in today though and will be starting to look at these remaining preview 2 issues.

**Closed** 2016-06-06 22:08 UTC
Labels: 2 - In Progress, aspnet, blocking-partner
