### ISSUE TITLE
dotnet watch test does not discover tests in new files

### ISSUE THREAD

**Issue by steveoh** [dotnet/cli#9886] opened 2018-08-23 21:32 UTC
## Steps to reproduce
1. create a file with tests
1. start dotnet watch test
1. add a new test to existing file
   - watch # of tests increase
1. add a new file with tests
   - the # of tests does not increase

## Expected behavior
new tests in files added to the project while watch is running should be discovered and executed

## Actual behavior
tests in new file are ignored

## Environment data
```.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

// https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/124#issuecomment-415571877

**Comment by livarcocc** [comment] 2018-08-23 21:45
@natemcmaster do you want to take this one? Should I move to aspnet/home?

**Comment by natemcmaster** [comment] 2018-08-23 22:32
Closing as a duplicate of https://github.com/aspnet/DotNetTools/issues/212. This is a known issue we've had for almost 2 years. We backlogged and eventually closed as low-priority because we had zero reports of this problem. So congrats @steveoh , you're the first :)

Generally, the workaround is to switch tabs to an existing file and CTRL+S to retrigger the watcher.

cc @muratg

**Closed by natemcmaster** 2018-08-23 22:32 UTC

**Comment by AnthonyMastrean** [comment] 2019-07-12 20:58
Hey. I just worked up a custom VS Code background watching task for mstest and found this issue 😬. It really kills the effectiveness of this task.

```json
        {
            "label": "format",
            "type": "process",
            "command": "dotnet",
            "args": ["watch", "--project", "${workspaceFolder}/SimpleNetQ.sln", "format"],
            "problemMatcher": [],
            "isBackground": true,
            "runOptions": {
                "runOn": "folderOpen"
            }
        },
        {
            "label": "test",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "command": "dotnet",
            "args": ["watch", "--project", "${workspaceFolder}/SimpleNetQ.sln", "test"],
            "isBackground": true,
            "runOptions": {
                "runOn": "folderOpen"
            },
            "problemMatcher": {
                "fileLocation": ["absolute"],
                "severity": "error",
                "pattern": {
                    "regexp": "^\\s+at\\s+(?<test>.*\\.(?<method>.*?)\\(\\))\\s+in\\s+(?<path>.*):line\\s+(?<line>\\d+)\\s*$",
                    "message": 2,
                    "file": 3,
                    "line": 4
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^Starting test execution, please wait...$",
                    "endsPattern": "^Total tests:.*$"
                }
            }
        }
```
