### ISSUE TITLE
Dotnet Cli does not display message in correct encoding

### ISSUE THREAD

**Issue by yangshengf** [dotnet/cli#8685] opened 2018-02-26 06:56 UTC
## Steps to reproduce
run `dotnet -h`. 

## Expected  behavior
A readable help message is displayed

## Actual behavior

```
Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help            Display help.
  --version         Display version.

path-to-application:
  The path to an application .dll file to execute.
PS C:\Source\vscodeprojects\sabs-service> dotnet -h
.NET ???? ??? ??? (2.1.4)
???: dotnet [runtime-options] [path-to-application]
???: dotnet [sdk-options] [command] [arguments] [command-options]

path-to-application:
  ???????????? .dll ?????????

SDK ????:
  new              .NET ??????????????
  restore          .NET ?????????????????????????
  run              .NET ????????????????????????
  build            .NET ?????????????
  publish          ???? .NET ???????????? (????????)?
  test             ????????????????? ??????????????????????
  pack             NuGet ????????????
  migrate          project.json ??????????? msbuild ?????????????????
  clean            ????????????
  sln              ??????? (SLN) ???????????
  add              ????????????????
  remove           ?????????????????
  list             ???????????????????
  nuget            ??? NuGet ???????????
  msbuild          Microsoft Build Engine (MSBuild) ???????
  vstest           Microsoft Test Execution Command Line Tool ???????

????????:
  -v|--verbosity        ???????????????????????: q[uiet]?m[inimal]?n[ormal]?d[etailed]?diag[nostic]?
  -h|--help             ??????????

??????????????????'dotnet COMMAND --help' ???????

sdk-options:
  --version        .NET Core SDK ????????????
  --info           .NET Core ?????????
  -d|--diagnostics ????????????

runtime-options:
  --additionalprobingpath <path>    ??????????????????????
  --fx-version <version>            ???????????????????????????? Shared Framework ???????
  --roll-forward-on-no-candidate-fx ????? Shared Framework ??????????????????
  --additional-deps <path>          ?? deps.json ?????????
```

## Environment data
`dotnet --info` output:

```
.NET ???? ??? ??? (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Primary display language is set to Japanese. English (United States) is the second on Language settings. Date format is also set to English (United States).

Note this is concerning the output of Cli tool. Not the application I am writing. This has the same behavior in both CMD and Powershell, as well as VSCode Terminal.

**Comment by livarcocc** [comment] 2018-02-26 21:34
This seems like a dup of https://github.com/dotnet/cli/issues/7913.

**Comment by livarcocc** [comment] 2018-02-26 21:34
cc @nguerrera

**Comment by livarcocc** [comment] 2018-02-28 19:39
@nguerrera

**Comment by nguerrera** [comment] 2018-02-28 21:02
@yangshengf See https://github.com/dotnet/cli/issues/7913#issuecomment-369381006 for how to reconfigure your system to avoid this issue.

Duplicate of #7913

**Comment by nguerrera** [comment] 2018-02-28 21:02
Duplicate of #7913

**Closed by nguerrera** 2018-02-28 21:02 UTC
