### ISSUE TITLE
CLI: namespace error on fresh VB project

### ISSUE THREAD

**Issue by jcouv** [dotnet/cli#7704] opened 2017-09-22 20:45 UTC
@jcouv commented on [Fri Sep 22 2017](https://github.com/dotnet/roslyn/issues/22292)

Repro:

1. `mkdir 22227-cli-vb`
2. `cd 22227-cli-vb`
3. `dotnet new console --language=vb`
4. `dotnet build` produces the namespace error below

```
> dotnet --version
2.0.2-vspre-006949
```

```
> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

vbc : error BC30113: '22227-cli-vb' is not a valid name and cannot be used as the root namespace name. [D:\issues\22227-cli-vb\22227-cli-vb.vbproj]

Build FAILED.

vbc : error BC30113: '22227-cli-vb' is not a valid name and cannot be used as the root namespace name. [D:\issues\22227-cli-vb\22227-cli-vb.vbproj]
    0 Warning(s)
    1 Error(s)
```

Relates to https://github.com/dotnet/roslyn/issues/22227

---

@am11 commented on [Fri Sep 22 2017](https://github.com/dotnet/roslyn/issues/22292#issuecomment-331551793)

Does vb.exe by design considers the directory name to be the root namespace unless we explicitly add normalized name in `<RootNamespace>_22227_cli_vb</RootNamespace>` in vbproj?

csc doesn't seem to rely on dirname, even when there is no namespace in the program.cs code, actual dirname has invalid (hyphen) character and `<RootNamespace>` is set to `22227-cli-vb` (with same invalid chars) in csproj.

If it's not a breaking change, would be cool if vb.exe and csc.exe behave the same way.

---

@jcouv commented on [Fri Sep 22 2017](https://github.com/dotnet/roslyn/issues/22292#issuecomment-331556102)

It looks like the problem is not with `vbc.exe`, but with the arguments it receives. If the `vbproj` file is named A, then there is a `/rootnamespace:A` command-line option.

I'll move the issue to the CLI repo.

**Comment by AnthonyDGreen** [comment] 2017-09-22 20:54
vbc does do this by design. C# doesn't have the feature of a root namespace so it's not really something that can be made consistent. That said, it is an issue that this doesn't work. We should discuss possible solutions.

**Comment by am11** [comment] 2017-09-22 21:36
> C# doesn't have the feature of a root namespace

That's right. One thing I noticed that if we do something like:

```powershell
dotnet new console -n 123-console
cat 123-console/Program.cs
```

It shows that namespace is set to sanitized dirname:

```c#
namespace _123_console
{
  .. ..
}
```

> possible solutions

Could the same normalization be reused for VB root NS when setting the compiler arg in CLI?

**Comment by livarcocc** [comment] 2017-09-22 22:50
@mlorbetske is this something that we could do in the templates?

**Comment by mlorbetske** [comment] 2017-09-22 22:55
It's certainly possible to have the template content for the vbproj include the rootnamespace property

cc @jmarolf

**Comment by AnthonyDGreen** [comment] 2017-09-22 23:23
That sounds perfect!

**Comment by jmarolf** [comment] 2017-09-22 23:39
@mlorbetske what are the rules for how text is replaced in the templating engine?  `Company.ConsoleApplication1` gets replaced in code files but what about the project file?  would the template below work?

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Company.ConsoleApplication1</RootNamespace>
    <TargetFramework Condition="'$(TargetFrameworkOverride)' == ''">netcoreapp2.1</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkOverride)' != ''">TargetFrameworkOverride</TargetFramework>
    <RuntimeFrameworkVersion Condition="'$(Framework)' == 'netcoreapp2.1'">2.1.0-preview2-25624-02</RuntimeFrameworkVersion>
    <NETStandardImplicitPackageVersion Condition="'$(Framework)' == 'netcoreapp2.1'">2.1.0-preview2-25624-02</NETStandardImplicitPackageVersion>
  </PropertyGroup>

</Project>
```

**Comment by jmarolf** [comment] 2017-09-22 23:42
@AnthonyDGreen  I assume that this is the project file we want to generate for the repro steps in this bug:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>_22227_cli_vb</RootNamespace>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

As VB devs don't like having namespaces encapsulate their classes or modules if they are in the default namespace.

**Comment by mlorbetske** [comment] 2017-09-22 23:42
@jmarolf I believe that would work (and the name would get replaced with the "safe namespace" flavor of the name). @seancpeters to confirm

**Comment by seancpeters** [comment] 2017-09-23 00:04
Confirming what @mlorbetske stated above - yes the "safe namespace" flavor would be used.

@jmarolf - regarding the rules for what gets replaced in which files - by default every file in the template will have the replacements applied. If there are file(s) that shouldn't have replacements applied, they need to be specified as CopyOnly under the "sources" section of the template config.

**Comment by jmarolf** [comment] 2017-09-23 00:07
@mlorbetske @seancpeters got it thanks guys!

**Comment by livarcocc** [comment] 2017-11-10 21:55
@jmarolf did you have a chance to take a look a this?

**Comment by jmarolf** [comment] 2017-11-14 03:26
fixed by https://github.com/dotnet/templating/pull/1337

**Closed by jmarolf** 2017-11-14 03:26 UTC
