### ISSUE TITLE
Letters missing intermittently - "ompilation succeeded."

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#738] opened 2016-01-07 00:06 UTC
Some letters seem to be sometimes disappear when running. I believe it might be related to our console forwarding piece of code. Look at the "ompilation succeeded." in the following:
```
Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.3566069Compiling Microsoft.DotNet.ProjectModel for DNXCore,Version=v5.0
The destination "E:\oss\cli\artifacts\win7-x64\stage2\bin" does not exist. This script is only designed to update a previous full build!
The destination "E:\oss\cli\artifacts\win7-x64\stage2\bin" does not exist. This script is only designed to update a previous full build!
E:\oss\cli\src\Microsoft.DotNet.ProjectModel\project.json(17,52): warning NU1007: Dependency specified was Microsoft.Extensions.FileSystemGlobbing >= 1.0.0-rc2-15882 but ended up with Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15887.
 ompilation succeeded.
    1 Warning(s)
    0 Error(s)

22m
Time elapsed 00:00:02.4347574Compiling Microsoft.DotNet.Cli.Utils for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)
```

While this particular issue is not a high priority right now something similar might be happening when you use dotnet run which could potentially strip some letters from user code which could potentially have some inadvert effect on their app or some build script.

**Comment by moozzyk** [comment] 2016-01-07 00:25
Can this also make the console go crazy with colors? I ran `dotnet build` and suddenly any new text on the console was in red (I did have build errors).

**Comment by krwq** [comment] 2016-01-07 01:12
I'm experiencing same colors issue even without build errors. It's totally possible it is the same thing :smiley:

**Comment by krwq** [comment] 2016-01-14 22:35
This might be a Windows console issue. I actually just saw letter 'r' missing when using 'git clone' ('eceiving objects'). (we need to consider this possibility when investigating this)

**Comment by dleeapho** [comment] 2016-03-08 22:44
Also seeing this running in a Docker container, dotnet run on dotnet new:
`root@17dbf38e77a7:/myapp# dotnet run
Compiling yappor
                 NXCore,Version=v5.0

ompilation succeeded.
 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3332161
`

**Comment by brthor** [comment] 2016-03-08 22:46
@dleeapho 

Please post output of `dotnet --version` is this the latest?

A fix for this should have gone in a while back.

**Comment by Peter-Schneider** [comment] 2016-03-08 23:14
@brthor: Its also happening on a Mac Terminal 

<img width="619" alt="missingcharacters" src="https://cloud.githubusercontent.com/assets/7537527/13619747/22746664-e58b-11e5-9ecf-393346ab6d80.png">

**Comment by dleeapho** [comment] 2016-03-10 20:23
@bthor `dotnet --version` yields:
`.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
`

**Comment by brthor** [comment] 2016-03-22 17:50
I am seeing this pretty heavily in docker in our build scripts which do not use the StreamForwarder.

Unlikely that is the root cause.

**Comment by piotrpMSFT** [comment] 2016-07-27 19:07
This has been addressed through output synchronization. Furthermore, as we transition to MSBuild we will take advantage of its output synchronization.

**Closed by piotrpMSFT** 2016-07-27 19:07 UTC
Labels: msbuild-mitigated
