### ISSUE TITLE
dotnet cli installation fails with download error

### ISSUE THREAD

**Issue by dsgouda** [dotnet/cli#3159] opened 2016-05-20 17:26 UTC
## Steps to reproduce
When trying to install dotnet cli using either of the scripts dotnet-install.sh and dotnet-install.ps1 for an older version (1.0.0-rc2-002520) the installation scripts don't seem to find the blob to download 
To install, we run the script as 
dotnet-install.ps1 -InstallDir <someDir> -Version "1.0.0-rc2-002520"
(similar args for the .sh script)

## Expected  behavior
dotnet cli should be successfully installed

## Actual behavior
Error message "Invoke-WebRequest : BlobNotFoundThe specified blob does not exist."

## Environment data
`dotnet --info` output:
N/A
Tagging @lt72

**Comment by brthor** [comment] 2016-05-20 17:26
cc @eerhardt

**Comment by eerhardt** [comment] 2016-05-20 17:42
dupe of #3152

**Closed by eerhardt** 2016-05-20 17:42 UTC
Labels: bug, windows-installer
