### ISSUE TITLE
dotnet restore does not work correctly from root

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#715] opened 2016-01-05 22:58 UTC
# Repro Steps (Ubuntu 14.04)

1. cd /
2. dotnet new
3. dotnet restore

## Result:
error: Could not find a part of the path '/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/root/proc/52/fd/97'.

#687 is related to these specific repro steps, however even if new requires a directory, there is nothing that would prevent an end user from manually creating or coping project artifacts to the root and then attempting to use `dotnet`.

**Comment by naamunds** [comment] 2016-06-24 21:54
Although running `dotnet restore` from the root still fails, it is now due to "access denied" errors, which actually seems to be the expected behavior.  See https://github.com/NuGet/Home/issues/3038.  Running `dotnet restore /project.json` works, so I think we can close this issue.

**Closed** 2016-07-22 15:36 UTC
Labels: bug
