### ISSUE TITLE
dotnet restore FileNotFoundException: System.Linq, Version=4.0.2.0

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1429] opened 2016-02-16 17:47 UTC
Running `dotnet restore` with latest `dotnet cli` (`1.0.0.1370 beta`) on a proj that was restoring fine a couple of days ago under the prior `dotnet cli` (`1.0.0.1306 beta`) ...
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 
'System.Linq, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its 
dependencies. The system cannot find the file specified.
   at Microsoft.DotNet.Cli.Utils.DebugHelper.HandleDebugSwitch(String[]& args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
Uninstalling `1.0.0.1370 beta` and going back to `1.0.0.1306 beta`, `dotnet restore` works again ...
```
log  : Committing restore...
log  : Restore completed in 376365ms.
```

**Comment by davidfowl** [comment] 2016-02-16 17:50
I don't quite understand how our CI is passing yet you hit something like this... Seems like we need to see if we're pushing what we think we're pushing.

/cc @piotrpMSFT

**Comment by PinpointTownes** [comment] 2016-02-16 22:09
Actually, it's not specific to the `restore` command:

![image](https://cloud.githubusercontent.com/assets/6998306/13092822/4b087c44-d502-11e5-8c1c-c9cc5d561d24.png)

**Comment by piotrpMSFT** [comment] 2016-02-16 22:34
are folks seeing this on Windows only?

**Comment by GuardRex** [comment] 2016-02-16 22:35
Win10 only here

**Comment by piotrpMSFT** [comment] 2016-02-16 22:38
do you have DOTNET_HOME set by chance? can you try deleting it? we recently removed the requirement but I worry that it's now overriding the default behavior...

**Comment by GuardRex** [comment] 2016-02-16 22:44
@piotrpMSFT

Yep, that licked it. I deleted the `DOTNET_HOME` env var and uninstalled. I rebooted and reinstalled `-1370`. It works. Thx. Go ahead and close when ready ... I'm good.

**Comment by piotrpMSFT** [comment] 2016-02-16 22:54
Assigning to @schellap. Can CoreHost provide some useful diagnostics output in cases like this?

The scenario is legitimate. Someone has a DOTNET_HOME set which they used to point to a runtime installation directory. Later they deleted the runtime but forgot to unset DOTNET_HOME. How do we get them back into a good state?

**Comment by schellap** [comment] 2016-02-16 23:53
@GuardRex could you turn on `export COREHOST_TRACE=1` and pastebin the output or relevant portion (search for coreclr)?

**Comment by GuardRex** [comment] 2016-02-16 23:54
@schellap Sure, I'll do it right after the Standup ends ... or when they get into the 4-hour Q&A part :smile:

**Comment by schellap** [comment] 2016-02-17 00:01
@piotrpMSFT how is the host copied to the `stage2\bin`? I have a weird feeling the CoreHost added to the publish graph is stomping on this host?

**Comment by piotrpMSFT** [comment] 2016-02-17 00:05
@schellap are you able to get a local repro? Point DOTNET_HOME to an empty directory?

**Comment by schellap** [comment] 2016-02-17 00:08
Tried, no local repro with: https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-win-x64.latest.zip

**Comment by GuardRex** [comment] 2016-02-17 00:09
@schellap I'll see if I can break it again for you (with trace) ... I'm really, really good at breaking stuff :monkey:

**Comment by schellap** [comment] 2016-02-17 00:30
https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.1370/dotnet-win-x64.1.0.0.1370.exe MSI install doesn't repro as well for me. Will wait for @GuardRex inputs.

**Comment by GuardRex** [comment] 2016-02-17 00:41
@schellap I'm going on it right now. I'll get back to you soon.

**Comment by GuardRex** [comment] 2016-02-17 00:51
@schellap Good ... yep ... I re-broke it.


[Microsoft_Dotnet_CLI_for_Windows_(1.0.0.1370_)_20160216164533_000_dotnet_win_x64.1.0.0.1370.msi.txt](https://github.com/dotnet/cli/files/133498/Microsoft_Dotnet_CLI_for_Windows_.1.0.0.1370_._20160216164533_000_dotnet_win_x64.1.0.0.1370.msi.txt)

**Comment by piotrpMSFT** [comment] 2016-02-17 00:52
@GuardRex strikes again!

**Comment by schellap** [comment] 2016-02-17 00:53
Can you `set COREHOST_TRACE=1` and give me the trace of the `dotnet restore`?

**Comment by GuardRex** [comment] 2016-02-17 00:53
oh, sure ... brb

**Comment by GuardRex** [comment] 2016-02-17 00:56
[trace.txt](https://github.com/dotnet/cli/files/133507/trace.txt)

now ... let's see what else I break today :skull:

**Comment by schellap** [comment] 2016-02-17 01:00
Do you have System.Linq app local?

**Comment by schellap** [comment] 2016-02-17 01:00
or in the deps file?

**Comment by GuardRex** [comment] 2016-02-17 01:02
no, but's pulled in by other packages. I'd have to dig into the lock file ... or do you want me to put it on gist (I mean the last good lock file that was produced by `dotnet cli` ver -1306, which is working)?

**Comment by GuardRex** [comment] 2016-02-17 01:03
I don't reference it myself in `project.json`

**Comment by GuardRex** [comment] 2016-02-17 01:05
it does get pulled in ... I see it in the lock file and I see it in published output

![capture](https://cloud.githubusercontent.com/assets/1622880/13096619/83964948-d4cf-11e5-8048-b3d0f40fcac3.PNG)

**Comment by GuardRex** [comment] 2016-02-17 01:07
the lock file has 45 mentions of `"System.Linq": "4.0.2-rc2-23805",`

**Comment by schellap** [comment] 2016-02-17 01:31
Sorry, I wanted to know if System.Linq is present along with dotnet.exe in your install base?

**Comment by GuardRex** [comment] 2016-02-17 01:33
MIA

![capture](https://cloud.githubusercontent.com/assets/1622880/13097123/65276f38-d4d3-11e5-816e-36b852796d58.PNG)

**Comment by schellap** [comment] 2016-02-17 01:33
In the host trace:

```
Adding System.IO.Pipes to local assembly set from C:\Program Files\dotnet\bin\System.IO.Pipes.dll
Adding System.IO.UnmanagedMemoryStream to local assembly set from C:\Program Files\dotnet\bin\System.IO.UnmanagedMemoryS
tream.dll
Adding System.Linq.Expressions to local assembly set from C:\Program Files\dotnet\bin\System.Linq.Expressions.dll
Adding System.Linq.Parallel to local assembly set from C:\Program Files\dotnet\bin\System.Linq.Parallel.dll
Adding System.Linq.Queryable to local assembly set from C:\Program Files\dotnet\bin\System.Linq.Queryable.dll
Adding System.Net.Http to local assembly set from C:\Program Files\dotnet\bin\System.Net.Http.dll
```

I don't see System.Linq.

**Comment by schellap** [comment] 2016-02-17 01:33
Boom @piotrpMSFT could you please take over?

**Comment by schellap** [comment] 2016-02-17 01:35
I am not sure why System.Linq is missing. Earlier you got lucky because DOTNET_HOME\runtime\ provided a fallback path for System.Linq. So dotnet is broken the moment System.Linq is not found in your case.

**Comment by piotrpMSFT** [comment] 2016-02-17 01:36
@GuardRex only became fixed when we removed DOTNET_HOME, not when we added it.

@GuardRex can you share your deps file and lock file?

**Comment by GuardRex** [comment] 2016-02-17 01:36
sure ... brb

**Comment by schellap** [comment] 2016-02-17 01:37
@piotrpMSFT that would be dotnet.deps which I don't think is present in the `stage2\bin`

**Comment by GuardRex** [comment] 2016-02-17 01:38
yeah ... I was about to ask ... on what path for these?

**Comment by piotrpMSFT** [comment] 2016-02-17 01:40
@GuardRex what is the full [minus PII] path for the directory that is missing System.Linq.dll?

**Comment by GuardRex** [comment] 2016-02-17 01:41
C:\Program Files\dotnet\bin

**Comment by piotrpMSFT** [comment] 2016-02-17 01:43
strange. Your MSI log seems to be implying that it is getting installed:

````
MSI (s) (10:B0) [16:45:42:322]: Executing op: ComponentRegister(ComponentId={89591D4D-F6D2-456F-8EE9-31E37D4FE920},KeyPath=C:\Program Files\dotnet\bin\System.Linq.dll,State=3,,Disk=1,SharedDllRefCount=2,BinaryType=1)
````

**Comment by piotrpMSFT** [comment] 2016-02-17 01:44
does deleting DOTNET_HOME still fix the problem? Or was that a red herring?

**Comment by GuardRex** [comment] 2016-02-17 01:46
I can try again ... What's the exact process that's best for this: Delete the env var, uninstall `dotnet cli`, re-install `dotnet cli` and see if gets put there. Then ... go back to the original break pattern: Remove the env var (if its there, which it shouldn't be), install -1306, install -1370 on-top ... that seems to repo the issue.

**Comment by GuardRex** [comment] 2016-02-17 01:47
Let me try those two procedures. Those two series of steps should narrow it down a little bit now that I know what to look for.

**Comment by piotrpMSFT** [comment] 2016-02-17 01:48
I wouldn't reinstall. What I thought had happened earlier was that you just deleted the Env Var... it sounds like there is more magic happening. What is the recipe for getting into a broken state?

**Comment by GuardRex** [comment] 2016-02-17 01:50
Start with -1306 installed and the env var present and then just install -1370 over the top on it. That should break it.

Earlier, I think I removed the env var, uninstalled -1370 (via Programs and Features), rebooted, installed -1370, then it worked.

**Comment by GuardRex** [comment] 2016-02-17 01:58
No, merely deleting the env var will not work even with a reboot.

You apparently cannot have the env var there when you do the install of -1370 in order for -1370 to work.

**Comment by piotrpMSFT** [comment] 2016-02-17 01:59
@robmen @Sridhar-MS any ideas?

**Comment by GuardRex** [comment] 2016-02-17 02:00
Confirmed: With the env var absent ... Programs and Features uninstall -1370 and immeditely re-install -1370 (no reboot needed) ... it :sparkles: works :sparkles:

**Comment by GuardRex** [comment] 2016-02-17 02:02
... `System.Linq` makes it into the `bin` folder as long as that env var is not present when you do the install of -1370.

![capture](https://cloud.githubusercontent.com/assets/1622880/13097619/772d25f2-d4d7-11e5-97ad-bac8ab72c0a3.PNG)

**Comment by davidfowl** [comment] 2016-02-17 04:02
@schellap Try the MSI

**Comment by schellap** [comment] 2016-02-17 04:03
@davidfowl I tried the MSI couple of times. Are you able to repro?

**Comment by schellap** [comment] 2016-02-17 04:14
@davidfowl I'm not sure I follow, System.Linq is missing app local and there is no deps file -- @GuardRex confirmed System.Linq is missing, you think that is because of some interaction between the MSI installer and the host?

**Comment by piotrpMSFT** [comment] 2016-02-17 04:15
@Sridhar-MS should take a look. It seems like the presence of DOTNET_HOME is somehow affecting the behavior of the MSI...

**Comment by robmen** [comment] 2016-02-17 06:28
Log files always go a long way in actually understanding what is going wrong.

**Comment by piotrpMSFT** [comment] 2016-02-17 06:30
The log was shared above. Look for Microsoft_Dotnet_CLI_for_Windows_(1.0.0.1370_)_20160216164533_000_dotnet_win_x64.1.0.0.1370.msi.txt.

**Comment by robmen** [comment] 2016-02-17 06:57
Thanks. Missed the log file in the long thread. Here is the problem:

    MSI (s) (10:B0) [16:45:38:193]: Disallowing installation of component: {1499AEB1-8270-42F0-9B79-A0747CAFFB9A} since the same component with higher versioned keyfile exists
    MSI (s) (10:B0) [16:45:38:408]: Disallowing installation of component: {89591D4D-F6D2-456F-8EE9-31E37D4FE920} since the same component with higher versioned keyfile exists

Those are the Component GUIDs for the two locations where System.Linq.dll get installed. The log file suggests a newer version of the file was already present.

Does it make sense that an older version of the file was installed by the newer package? Hopefully, that is a bug elsewhere in the build for System.Linq.dll. It is very hard to ship files going backwards in time.

The reason System.Linq.dll is being ripped off the machine is because unique Component GUIDs are generated with every run of `heat.exe` due to the `-gg` switch being used. Probably would be better served with the `-ag` switch to allow WiX to manage the GUIDs for you automatically.

**Comment by schellap** [comment] 2016-02-17 07:28
FYI, in a good install on my local machine, System.Linq build date was 02/08. Most of the remaining ones  were 02/10 but that wasn't enough for me to say anything... @robmen's analysis ties it together.

**Comment by Petermarcu** [comment] 2016-02-17 16:23
@robmen , will switching to -ag be a breaking change at all?

**Comment by robmen** [comment] 2016-02-17 17:21
To be clear, right now the Component Rules are being violated every build. So there would be one more violation then the GUIDs would be stable.

**Comment by Petermarcu** [comment] 2016-02-17 17:55
That's what I thought. Sounds like the right thing to do. I thought we were uninstalling before install on the upgrade. Do we know how this happened if that was the case?

**Comment by robmen** [comment] 2016-02-17 17:58
Major upgrade *is* scheduled early. However, if you attempt to downgrade files this way, the Windows Installer will end up taking the newer ones away and not putting the older ones on the machine. So you have to repair afterwards.

Basically, downgrading files while upgrading packages doesn't work out so well.

**Comment by Petermarcu** [comment] 2016-02-17 18:07
Yeah, @piotrpMSFT @Sridhar-MS , why are we downgrading files in newer builds? Did a regression come in that we had to back out or something?

**Comment by Sridhar-MS** [comment] 2016-02-17 18:11
@Petermarcu I need to check out the MSIs `1.0.0.1370 beta` and `1.0.0.1306 beta`. We may bumped corefx version between those builds. I will give an update shortly.

**Comment by Sridhar-MS** [comment] 2016-02-17 18:55
We somehow managed to downgrade `System.Linq` from `4.6.23811` to `4.6.23808`. I am looking into how that happened.

**Comment by Sridhar-MS** [comment] 2016-02-17 19:01
With the latest builds we are somehow back to `System.Linq 4.6.23811`.

**Comment by tushargupta51** [comment] 2016-02-18 22:23
Having same issue with `dotnet test` command complaining about `System.Runtime` not found.

Repo I am building: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet, KDev branch

dotnet version:
.NET Command Line Tools (1.0.0)
Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
Runtime Id: win10-x64

Error:
info: program: dotnet
info: commandline: test
info: workingdir: test\Microsoft.IdentityModel.Logging.Tests
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
fail: Exit code 255 from dotnet
fail: Stack trace:
at View8bfa37c6d03a44059cf257ce5dcec7ee.Dotnet(String command, String dotnetDir) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 1273
at View8bfa37c6d03a44059cf257ce5dcec7ee.DotnetTest(String projectFile, Boolean testParallel) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 1498
at View8bfa37c6d03a44059cf257ce5dcec7ee.b__d0(String projectFile) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 10648
at System.Collections.Generic.List1.ForEach(Action1 action)
at View8bfa37c6d03a44059cf257ce5dcec7ee.b__ce() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 10648
at Sake.Engine.Builder.BuilderBase1.CallTarget(String name) at Sake.Engine.Builder.BuilderBase1.StartingTarget(String name)
at View8bfa37c6d03a44059cf257ce5dcec7ee.StartingTarget(String name) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 3522
at View8bfa37c6d03a44059cf257ce5dcec7ee.b__74() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 4006
at Sake.Engine.Builder.BuilderBase1.CallTarget(String name) at View8bfa37c6d03a44059cf257ce5dcec7ee.<RenderViewLevel0>b__6c() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 3862 at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
at Sake.Engine.SakeEngine.Execute(Options options)
at Sake.Engine.SakeEngine.Execute(String[] args)
at Sake.Program.Main(String[] args)

**Comment by Sridhar-MS** [comment] 2016-05-10 23:58
We longer do any major upgrades and should not be facing this issue now.

**Closed by Sridhar-MS** 2016-05-10 23:58 UTC
Labels: bug
