### ISSUE TITLE
Bad build performance for highly modular designs

### ISSUE THREAD

**Issue by firelizzard18** [dotnet/cli#7482] opened 2017-08-20 04:55 UTC
## Summary
I have a project that is highly modular and consists of 20-30 or more libraries and a few applications. These all use relative project references. Building is quite slow. [Here](https://gist.github.com/firelizzard18/8727679e6d0f9c69d89f13b67053228c) is a performance log of an 'incremental' build - **not a single source file changed between the last build and this one** - *total build time was **over 30 seconds***.

## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by firelizzard18** [comment] 2017-08-20 04:57
There's a bunch of cross-referencing between these projects.

**Comment by RUSshy** [comment] 2017-08-22 18:28
This is known issue with 2.0 https://github.com/dotnet/cli/issues/5918

**Comment by firelizzard18** [comment] 2017-08-22 19:12
I saw that issue. I created this one because A) that issue seemed to be focusing somewhat on `ResolveAssemblyReferences`, which in my case is an order of magnitude less of a problem than `ResolveProjectReferences`, and B) because I thought my situation could be a valuable stress-test/real world situation.

**Comment by firelizzard18** [comment] 2017-10-19 20:17
I'm averaging over a second per dependency, so with 50+ dependencies, my top-level build is now exceeding a minute, even for single-character changes to the top-level project.

**Comment by davkean** [comment] 2017-10-19 22:00
@firelizzard18 Do you have source code that we can grab? I suspect your evaluation time is huge and want to see why. The issues listed here under evaluation improve a tonne of this: https://github.com/dotnet/project-system/issues/2789.

**Comment by firelizzard18** [comment] 2017-10-20 23:43
Unfortunately I do not (the project is work for hire). The best I can provide is logs.

I am excited to try out the new changes and will do so as soon as there's an installer.

**Comment by dasMulli** [comment] 2017-10-21 19:04
The problem is likely that the incremental build time gets worse with growing project and package dependency graphs. Not sure if this is directly evaluation-related.

I've created a small testbed to demonstrate the current build time pain points, based on 20 projects with dependencies (`lib1` <- `lib2` … <- `lib20`) referencing `Microsoft.AspNetCore.All`, which takes about 20 seconds to build on fullfx and about 40 on .NET Core, though I haven't tried with an Ngen'd msbuild master branch or 2.1.1 (15.5?) CLI. (Or maybe I will in 20 mins when the download from azure is complete..)

if I understand correctly, the problem with .net core is a missing / slow RAR cache..

[testbed.zip](https://github.com/dotnet/cli/files/1404393/testbed.zip)

**Comment by firelizzard18** [comment] 2017-10-22 22:20
My situation is probably falling prey to the same issues as @dasMulli's testbed, though my dependency graph is wider than it is deep (probably no more than 10 deep at the worst).

Nearly all of my libraries are targeting .NET Standard (the lowest version I can for each). My applications are targeting .NET Framework (4.6+). I'm building projects (no solutions) on Windows 10 via the CLI (2.? preview).

I'm trying to eliminate as many .NET Framework dependencies as possible. I'm stuck with EF6 until EF Core has the features I need (hence why my apps are targeting .NET Framework).

**Comment by livarcocc** [comment] 2018-04-03 16:46
I tested this with the 2.1.300-preview1 build currently available to the public and on OSX, the first build with restore too 35 seconds and subsequent incremental builds were coming to 25 seconds. This will be even faster with our preview2 build.

As such, I am going to close this issue.

**Closed by livarcocc** 2018-04-03 16:46 UTC
Labels: performance
