### ISSUE TITLE
Unable to build MusicStore sample

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#4688] opened 2016-11-11 12:06 UTC
## Steps to reproduce
dotnet migrate
dotnet restore
dotnet build

## Expected  behavior

no error

## Actual behavior

both 'dotnet restore' and 'dotnet build' report errors.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by svick** [comment] 2016-11-11 13:17
What errors are you getting?

**Comment by xatabhk** [comment] 2016-11-11 16:31
![music_error](https://cloud.githubusercontent.com/assets/6814395/20222163/33bfae22-a86f-11e6-9970-ce0e923ae6f4.png)

**Comment by svick** [comment] 2016-11-11 16:40
Packages for the msbuild-based SDK are not on NuGet yet, you need to get them from MyGet and to do that, you need to set up a NuGet.config like this: https://github.com/dotnet/sdk/issues/345#issuecomment-257624891.

**Comment by xatabhk** [comment] 2016-11-11 16:56
Actually I have been using MyGet all the time.

**Comment by livarcocc** [comment] 2016-11-11 18:02
This is because of a change in msbuild. In MSBuild, if you have a desktop TFM (like net45, net451, net46, etc), you need to set the RuntimeIdentifiers in your csproj as well.

We have a bug tracking doing that automatically doing migration, but you can try to work around this problem by add this to your csproj:

```
<RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
```

**Comment by piotrpMSFT** [comment] 2016-11-11 22:22
@xatabhk are you unblocked with this info?

@livarcocc can you link the bug that will fix the root cause so we can close this out without losing the ref count?

**Comment by xatabhk** [comment] 2016-11-12 01:06
I added <RuntimeIdentifiers> but still got the same error. Dotnet just ignored it.

Here is my project file:
  <PropertyGroup>
    <Description>Music store application on ASP.NET 5</Description>
    <VersionPrefix>1.1.0</VersionPrefix>
    <TargetFrameworks>net451;netcoreapp1.1</TargetFrameworks>
    <DefineConstants>$(DefineConstants);DEMO</DefineConstants>
    <WarningsAsErrors>true</WarningsAsErrors>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>MusicStore</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
  </PropertyGroup>


The same error message:
Build FAILED.

       "C:\temp\MusicStore-dev\samples\MusicStore\MusicStore.csproj" (Build target) (1) ->
       "C:\temp\MusicStore-dev\samples\MusicStore\MusicStore.csproj" (Build target) (1:2) ->
       (CheckRuntimeIdentifier target) ->
         C:\Users\zaxideler\.nuget\packages\microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.RuntimeIdentifierInference.targets(45,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [C:\temp\MusicStore-dev\samples\MusicStore\MusicStore.csproj]

    0 Warning(s)
    1 Error(s)

**Comment by piotrpMSFT** [comment] 2016-11-12 03:40
We're not currently inferring the runtime during run. We only gave you a partial solution, sorry about that :) Now that you have the identifiers make sure you restore and then invoke run with `dotnet run /p:RuntimeIdentifier=win10-x64`. Use the appropriate runtime identifier for your system.

 I updated the title to track adding back inference.

**Comment by xatabhk** [comment] 2016-11-12 07:12
As "dotnet build" does not work, I have not got the chance to try "dotnet run". It is "dotnet build" that complains about RuntimeIdentifier and ignores it.

**Comment by piotrpMSFT** [comment] 2016-11-12 08:14
Putting back the title. Passing the RuntimeIdentifier to Build only resulted in another failure. We will need to look deeper.

Thanks @xatabhk !

**Comment by wizarrc** [comment] 2016-12-01 02:32
@piotrpMSFT @xatabhk I found a workaround/fix in another repo. I believe the RuntimeIdentifiers needs to be singular, at least with preview4 tooling.

`<RuntimeIdentifier>win7-x86</RuntimeIdentifier>`

https://github.com/dotnet/cli/issues/4619#issuecomment-263067703.

I would imagine it's one of the many migration bugs. Hope that helps.

**Comment by jgoshi** [comment] 2017-01-23 23:14
This works properly on the latest (using rel/1.0.0 branch). I do:
dotnet migrate MusicStore.sln
dotnet restore MusicStore.sln
dotnet build MusicStore.sln

**Comment by livarcocc** [comment] 2017-01-24 03:01
@xatabhk This seems to be working now. If you are still having problems, please re-activate this issue and give us some detail about the issues that you are seeing.

**Closed by livarcocc** 2017-01-24 03:01 UTC
Labels: blocking-release, migration

**Comment by tdekoekkoek** [comment] 2017-01-26 16:16
@wizarrc Thank you!  I cannot believe they have that as plural!
