### ISSUE TITLE
Dotnet publish on project with 2 frameworks dumps both into same folder

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3427] opened 2016-06-07 22:40 UTC
## Steps to reproduce

dotnet new
replace project.json with this https://gist.github.com/ericstj/2670a1a41c1e76ae734a310030abe5cd
- or use something simpler, key is two different frameworks with different dependencies/assets + a RID
  dotnet restore
  dotnet publish -r win7-x64 -o .\x64
## Expected  behavior

any of the folowing
1. Error saying -f must be specified
2. Choose one framework and log what was chosen
3. Publish both in framework specific subfolders
## Actual behavior

Both frameworks are written to the same folder, overwriting.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-002990)

Product Information:
 Version:            1.0.0-preview2-002990
 Commit SHA-1 hash:  54cd31b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment] 2016-06-08 01:11
Thanks @ericstj. Since this has a simple workaround, bumping it out to preview3.

**Comment by blackdwarf** [comment] 2016-10-31 23:12
@ericstj `dotnet publish` in the MSBuild world will error out saying that `--framework` has to be specified. I believe this solves some part of the issue above. However, it will still not create the subdir. This is by design, since the users are redirecting the output path. 

We should think through whether creating the TFM subdirectory is warranted in this case. I will open a new issue to discuss that. Closing this as mitigated.

**Closed by blackdwarf** 2016-10-31 23:12 UTC
Labels: fit-n-finish, msbuild-mitigated

**Comment by ericstj** [comment] 2016-10-31 23:14
Yeah, I don't care about a subdirectory.  I just care about not doing wrong stuff by default.  Thanks for addressing this.
