### ISSUE TITLE
Error installing nuget package with "facade" framework assembly reference

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#579] opened 2015-12-18 16:25 UTC
_From @herecydev on June 8, 2015 12:47_

Given a `project.json` as follows:

![image](https://cloud.githubusercontent.com/assets/11328618/8034187/4512a3b0-0ddd-11e5-9dfb-2b68a66a96e1.png)

When packaged and installed into a net45 project. Throws the following exception:

![image](https://cloud.githubusercontent.com/assets/11328618/8034542/9109e9b0-0de0-11e5-9949-0f72c438e492.png)

This isn't present within an `.xproj`. The associated `.nuspec` seems to be correct:

![image](https://cloud.githubusercontent.com/assets/11328618/8034272/08c91b7c-0dde-11e5-8a85-e91b699c11be.png)

It could well be something I'm doing wrong but within the `.xproj` the reference is resolved from `...\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades`.
I suspect the issue is that the `.csproj` is not seeing this facades folder (and therefore the dlls that project.json was able to see) and throws at this point but I have very little experience on how this all works.

By including:
```c#
		"net45": {
			"frameworkAssemblies": {
				"System.Runtime": { "version": "4.0.0.0", "type": "build" },
				"System.Reflection": { "version": "4.0.0.0", "type": "build" }
```
The issue doesn't manifest itself anymore. Though I am uncertain if this is the correct fix, thoughts?

_Copied from original issue: aspnet/dnx#2029_

**Comment by piotrpMSFT** [comment] 2016-05-20 21:36
dupe of #164

**Closed by piotrpMSFT** 2016-05-20 21:36 UTC
Labels: Move to DotNet CLI
