### ISSUE TITLE
dotnet build --native should check the native binary to determine if build is needed

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#1190] opened 2016-02-02 21:32 UTC
This is the repro:

```console
dotnet new
dotnet restore
dotnet build
dotnet build --native
```

The second call fails because it skips compilation with the message of `Project new (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.`. It should work, since I'm not asking `dotnet build` for the same thing as the first time around and there is no native binary on disk at the time of second invocation.

**Comment by brthor** [comment] 2016-02-02 21:53
This is an incremental compilation bug. Can't find it at the moment but there is another thread tracking this.

**Comment by cdmihai** [comment] 2016-02-02 22:06
Duplicate of #1041

**Closed by cdmihai** 2016-02-02 22:06 UTC
Labels: bug
