### ISSUE TITLE
Absolute reference to project.assets.json prevents separating build and publish stages

### ISSUE THREAD

**Issue by desmondgc** [dotnet/cli#10584] opened 2019-01-10 12:44 UTC
The .csproj.nuget.g.props file contains an absolute reference to project.assets.json which prevents us from separating build and publish stages in our CI pipeline. The idea is to have a pipeline that first builds the project, then test and publish jobs can be run in parallel using the output from the build stage. (I want to use `dotnet test --no-build` and `dotnet publish --no-build` to ensure the same output is used for all future stages.)

The problematic behavior can be reproduced by building a project, renaming the root folder or moving it elsewhere, and then attempting to publish with `--no-build`. The real-world case is that our CI jobs may be run on different runners so the build job runs under `/builds/765eb435/...` and the publish job runs under `/builds/5951fa48/...` for example.

## Steps to reproduce

```
dotnet new console -o foo
dotnet build foo
mv foo bar
dotnet publish --no-build bar
```

## Expected  behavior

Project is published successfully.

## Actual behavior

```
/usr/share/dotnet/sdk/2.2.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file '/tmp/foo/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/tmp/bar/foo.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment] 2019-01-10 17:47
This is by design and actually just the first of many symptoms you would encounter by attempting something like this.

We do not have any current plans to add support for this scenario and as such I am going to close this issue.

**Closed by livarcocc** 2019-01-10 17:47 UTC
