### ISSUE TITLE
dotnet publish does not clean output directory

### ISSUE THREAD

**Issue by halter73** [dotnet/cli#3086] opened 2016-05-17 19:05 UTC
## Steps to reproduce

Run `dotnet publish` with `publishOptions` like the following:

    "publishOptions": {
      "include": [
        "wwwroot",
        "Views",
        "appsettings.json",
        "web.config"
      ]
    }

Then remove an included directory such as "wwwroot" and run `dotnet publish` again.

## Expected  behavior

The publish directory would be cleaned and "wwwroot" would not longer be in the output directory.

## Actual behavior

"wwwroot" remains in the output directory after the second run of `dotnet publish` without "wwwroot" included.

Arguably there should be another build step that cleans the output directory like you would do for "copyToOutput". I'm filing this issue to ensure that this is a conscious design decision. @glennc 

There doesn't currently appear to be any option that changes the publish behavior:
    > dotnet publish --help
    .NET Publisher

    Usage: dotnet publish [arguments] [options]

    Arguments:
      <PROJECT>  The project to publish, defaults to the current directory. Can be a path to a project.json or a project directory

    Options:
      -h|--help                           Show help information
      -f|--framework <FRAMEWORK>          Target framework to compile for
      -r|--runtime <RUNTIME_IDENTIFIER>   Target runtime to publish for
      -b|--build-base-path <OUTPUT_DIR>   Directory in which to place temporary outputs
      -o|--output <OUTPUT_PATH>           Path in which to publish the app
      --version-suffix <VERSION_SUFFIX>   Defines what `*` should be replaced with in version field in project.json
      -c|--configuration <CONFIGURATION>  Configuration under which to build
      --native-subdirectory               Temporary mechanism to include subdirectories from native assets of dependency packages in output
      --no-build                          Do not build projects before publishing

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by nil4** [comment] 2016-05-18 00:35
@halter73 reported as #2855

**Comment by piotrpMSFT** [comment] 2016-05-26 08:34
duplicate of #2855

**Closed by piotrpMSFT** 2016-05-26 08:34 UTC
