### ISSUE TITLE
Global.Microsoft.VisualBasic.MyServices.Internal.ContextValue is not defined in VB .NET core class library projects

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#12116] opened 2019-08-01 23:48 UTC
## Steps to reproduce
Open a command prompt with cli.
Create a new VB Class Library using .NET Core 3.0:
dotnet new classlib -f netcoreapp3.0 -lang vb -n test1
Build via: dotnet build

## Expected  behavior
Library builds correctly.

## Actual behavior
Library fails to build with the following error.
vbc : error BC30002: Type 'Global.Microsoft.VisualBasic.MyServices.Internal.ContextValue' is not defined.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013437
 Commit:    37fe062a9e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013437\

Host (useful for support):
  Version: 3.0.0-preview8-28373-17
  Commit:  5d8d5e8661

.NET Core SDKs installed:
  3.0.100-preview8-013437 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19374.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nguerrera** [comment] 2019-08-04 21:21
Duplicate of https://github.com/dotnet/corefx/issues/40012

**Comment by nguerrera** [comment] 2019-08-04 21:21
This came in first, but the fix would go in corefx or roslyn, and https://github.com/dotnet/corefx/issues/40012 is therefore a better place to track this.

**Closed by nguerrera** 2019-08-04 21:21 UTC
