### ISSUE TITLE
Why doesn't cli use the version of dotnet-install in repo?

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#5410] opened 2017-01-20 22:18 UTC
This is probably a stupid question, so apologies in advance.

Why does the cli grab the `dotnet-install.sh` script from github rather than using the copy at `scripts/obtain/dotnet-install.sh`?

To me, it seems like this approach makes it much harder to fix issues in `dotnet-install.sh` because the version available at github.com is being used and local changes to `dotnet-install.sh` are ignored.

**Comment by ellismg** [comment] 2017-01-20 22:19
/cc @piotrpMSFT 

This seems like a reasonable request to me, but I don't know the history behind why the choice was made.

**Comment by krwq** [comment] 2017-01-21 00:34
@omajid thanks for point this out!

I do not know the cause and I'm not sure if this is intentional or not but I know for a fact that at one point we wanted to make sure that one of the "stable" branches was picking up the script from the correct stable branch - this could be unintentional merge back to rel branch or some temporary fix (i.e. some transition) which we forgot to remove. Also we need one of the old builds for migration testing which might be causing the need to use the old script.

I believe we should be using local version of the script but there might be some background to it - @livarcocc or @piotrpMSFT might have some more context on this.

**Comment by omajid** [comment] 2017-02-10 22:40
Any ideas on how to fix this? I have been trying to build cli on RHEL 7.3. I created a fix for `dotnet-install.sh` that was pushed to `master` but because of how the version at `rel/1.0.0` branch is used instead, that fix isn't helping.

**Comment by piotrpMSFT** [comment] 2017-02-11 02:55
Actually, it looks like we're currently using the `build_tools` copy of the script. This is an easy change. In `run-build.sh` on ~line 141 we set the value for `dotnetInstallPath`. Just point that to the repo-local file. @omajid want to make a PR? Can you update the `run-build.ps1` file  to match?

**Comment by omajid** [comment] 2017-02-13 16:07
@piotrpMSFT In my tests, it doesn't look like the build scripts even gets to line 141. It fails a few lines earlier, because it calls out to `build_tools/bootstrap.sh`, which downloads and runs the copy at `build_tools/dotnet-install.sh`. `bootstrap.sh` accepts flags to fetch from another branch from github, so I can make it use `master` rather than `rel/1.0.0`, but it feels like a hack rather than a proper fix that uses the local copy of `dotnet-install.sh`.

**Comment by piotrpMSFT** [comment] 2017-02-14 07:34
@livarcocc @markwilkie this may be a great reason for CLI to stop using build_tools altogether...

**Comment by markwilkie** [comment] 2017-02-14 17:26
@crummel and @dleeapho who will be interested in the buildtools problem.

**Comment by crummel** [comment] 2017-02-16 21:06
@piotrpMSFT Do you mean CLI should stop using the BuildTools package or changing the way CLI puts it in the build_tools folder?

I think something that might be useful for all repos using bootstrap and BuildTools is something similar to the way you can use a locally built BuildTools package - you can set $BUILDTOOLS_SOURCE to a local folder and it'll be picked up from there instead.  As a long-term fix I think we should consider a $DOTNET_INSTALL_SOURCE or something similar, since I can see a scenario like: "I'm fixing a dotnet-install issue and want to test my changes in multiple repos".

**Comment by livarcocc** [comment] 2017-05-15 17:13
This has been changed already. CLI is using the dotnet-install script from the repo and we are no longer using build_tools.

**Closed by livarcocc** 2017-05-15 17:13 UTC
