### ISSUE TITLE
Enable CLI to support OneCore based SKUs (e.g. Nano server)

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1008] opened 2016-01-24 16:19 UTC
For CLI toolchain to run successfully on OneCore based SKUs, all native components in the toolchain and its dependencies (e.g. Roslyn, CoreCLR, ILC, Libuv, etc) need to be updated to build against OneCore libraries and CLI be updated to carry APISet forwarders so that it can then execute on downlevel OS (e.g. win7).

CC @anurse @schellap @jaredpar @davidfowl

**Comment by gkhanna79** [comment] 2016-01-24 16:22
Related discussion is https://github.com/dotnet/cli/issues/468

**Comment by gkhanna79** [comment] 2016-01-25 16:02
This shoudl also account for APISet packaging for CLI native components.

**Comment by GuardRex** [comment] 2016-01-26 07:47
Cross ref (`ViewBag` bug on Nano): https://github.com/aspnet/Mvc/issues/3991

**Comment by honestgrace** [comment] 2016-05-04 22:18
When I run musicstore.standalone.exe on the latest Nano server machine, I ran into this error.

.\MusicStore.Standalone.exe : Failed to load the dll from [D:\shared2\temp\AspnetCoreHandler_MusicStore\hostpolicy.dll], HRESULT: 0x8007007E
    + CategoryInfo          : NotSpecified: (Failed to load ...ULT: 0x8007007E:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
… 

One work-around way of the issue is to copy the following three files on the same directory of the MusicStore and try again. You will the error is gone and it works.

**Comment by piotrpMSFT** [comment] 2016-12-07 22:32
@gkhanna79 reading through the description here, it seems this should be a core-setup issue as there are no native bits in CLI anymore. Can you close this one? Or let us know what is needed?

**Closed** 2016-12-07 22:40 UTC
Labels: infrastructure
