### ISSUE TITLE
migration: use of versionprefix in multitargetting projects (which include netfx*) cause restore to fail

### ISSUE THREAD

**Issue by rrelyea** [dotnet/cli#5573] opened 2017-02-03 13:18 UTC
## Steps to reproduce
create a preview 2 based project that targets net45 and netstandard-whatever
migrate it using current bits

## Expected  behavior
it works in VS

## Actual behavior
restore fails because:
   cps/rps nominates the project and sends per tfm info about version to nuget restore manager.
   nuget can only write one version to the assets file so we check to ensure the version is the same for every tfm.
   since netfx likely doesn't have a:
`<Version` Condition="not set yet">$(VersionPrefix)...</Version> type property, the version for netfx ends up being different for netfx and netstandard -- and we cannot restore.

## Environment data
`dotnet --info` output: latest cli from VS build from 02/02 d15rel

More info in this NuGet issue: https://github.com/NuGet/Home/issues/4487

**Comment by livarcocc** [comment] 2017-02-03 19:02
What are the semantic differences between versionprefix and version? if I have version 1.0.0-* and pass --version-suffix to dotnet pack, will the right version be constructed.

We have versionprefix in migration because we must maintain the same semantics as the project.json version property.

Also, while everyone who migrates will hit this, fixing this in migration does not address the root cause of the problem? 

People who have multiTFM with netfx and netcore and add a versionprefix themselves will hit this. I don't believe this is a migration issue and this should be fixed somewhere else.

**Comment by srivatsn** [comment] 2017-02-03 21:49
Adding @dsplaisted @nguerrera @eerhardt as well for context about Version vs VersionPrefix

**Comment by rrelyea** [comment] 2017-02-03 22:08
setting blocking release so we can minimally discuss at 4:30

**Comment by eerhardt** [comment] 2017-02-03 22:17
`<Version>` is the final full version of the project.  `1.0.0-alpha-1234`.

`<VersionPrefix>` is the value normally hard-coded in project files, like it was in project.json.  `1.0.0-alpha`.

`<VersionSuffix>` is the property that is appended to the `<VersionPrefix>` to make up the `<Version>` property.  This is normally passed in at build time, when a build number is defined.  `1234`.

See the [OneNote](https://microsoft.sharepoint.com/teams/netfx/corefx/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2Fcorefx%2FDocuments%2FCoreFx%20Notes&wd=target%28Planning%2FMSBuild%20CLI%20integration.one%7C41D470DD-CF44-4595-8E05-0CE238864B55%2FVersions%7C72702C8D-C66A-4B39-8410-175F54316BD0%2F%29)

**Comment by livarcocc** [comment] 2017-02-03 22:18
@rrelyea I am closing this issue in favor of https://github.com/NuGet/Home/issues/4496.

**Closed by livarcocc** 2017-02-03 22:18 UTC
Labels: blocking-partner, blocking-release, migration

**Comment by rrelyea** [comment] 2017-02-03 23:20
think the fix is in the sdk or migrate ... but whatever. we'll discuss
