### ISSUE TITLE
F5 Debug issue: An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#8622] opened 2018-02-15 18:06 UTC
_From @LazerFX on February 15, 2018 10:32_

I have spent a few days trying to figure out why F5 debugging doesn't work.  I believe I have an idea, however I don't know how to fix it, hence posting here for assistance.

I have a .NET Core 2.0 application that has a UI project, a Service project and several DLL projects.  The UI project has been created by doing a `dotnet new aurelia`.  I'm using ReSharper, so have added the `JetBrains.Annotations` version 11.1.0 NuGet project to the package.

When I attempt to F5 run, I get the message:

```
IDAMock.UI> Error:
IDAMock.UI>   An assembly specified in the application dependencies manifest (IDAMock.UI.deps.json) was not found:
IDAMock.UI>     package: 'JetBrains.Annotations', version: '11.1.0'
IDAMock.UI>     path: 'lib/netstandard1.0/JetBrains.Annotations.dll'
IDAMock.UI>
```

I've tested, and this happens whether I am launching Project, IIS or IIS Express.  If I do a `dotnet run` from the command prompt, it launches `http://localhost:5000` and correctly runs.  If I publish to IIS, it runs.  It appears to be only the IIS Debugging handler that is triggering this issue.  Of course, if I remove the JetBrains.Annotations reference, then it works - but that's not a long term solution, as there will be other NuGet packages that I'll want to reference.

I've tried changing the value of `<PublishWithAspNetCoreTargetManifest>` in the .csproj, which doesn't appear to change the results.

I found that the DLL was being output to `./Debug/netcoreapp2.0/PubTmp/Out`, and copied from there to the `./bin/Debug/netcoreapp2.0` folder, which temporarily resolved the issue.

For now, I'm going to add a post-build task to do this copy manually, but this isn't a permanent solution.   How can I resolve this in a non-hacky manner?  It only affects debugging, not deployment, but it's proving quite debilitating.

_Copied from original issue: dotnet/coreclr#16397_

**Comment by jkotas** [comment] 2018-02-15 18:06
_From @LazerFX on February 15, 2018 11:38_

As an update, so far this is affecting:

- JetBrains.Annotations (11.1.0)
- - JetBrains.Annotations.dll
- Newtonsoft.Json (10.0.3)
- - NJSonSchema.dll
- - Newtonsoft.Json.dll
- NSwag.AspNetCore (11.13.3)
- - NSwag.Annotations.dll
- - NSwag.AspNetCore.dll
- - NSwag.AssemblyLoader.dll
- - NSwag.Core.dll
- - NSwag.SwaggerGeneration.dll
- - NSwag.SwaggerGeneration.AspNetCore.dll
- - NSwag.SwaggerGeneration.WebApi.dll

So far, the common theme I'm referencing is these are all debug- and compile-time DLLs, not normally deployed with the application (Although, the NSwag Swagger UI is deployed, I'm primarily using it to auto-generate TypeScript client classes).

**Comment by livarcocc** [comment] 2018-02-15 18:14
Given that this works in `dotnet run`, I don't believe this is a CLI issue.

@BillHiebert can you take a look? Is there a more appropriate repo for debug issues?

**Comment by LazerFX** [comment] 2018-02-15 21:28
Sorry for putting this in the wrong location, I saw similar issues referenced so assumed it was the right place.

**Comment by livarcocc** [comment] 2018-02-15 21:30
@LazerFX zero worries. We will sort it out.

**Comment by livarcocc** [comment] 2018-02-15 21:37
@nguerrera any chance this is another one of those issues due to the build/publish differences?

**Comment by livarcocc** [comment] 2018-02-15 21:38
@LazerFX can you share a repro repo with us? As in, can you cook up a repro on github and share the link with us? Makes it easier to debug.

**Comment by LazerFX** [comment] 2018-02-16 01:20
Will have a look tomorrow, when I'm at my PC. Will give full versions as well of software.

**Comment by LazerFX** [comment] 2018-02-16 11:58
I have created https://github.com/LazerFX/cliBug

I created this by:

`dotnet new aurelia`
`npm install`
`dotnet restore`

Open in Visual Studio 2017 (15.5.6)
Set hosting to be IIS
Add JetBrains.Annotations
Press F5

Chrome appears, then disappears, and when I check the 'Dot Net Webserver' output window, I see the above-mentioned errors.

Hope this is enough to reproduce!

**Comment by livarcocc** [comment] 2018-02-16 22:56
Trying it out.

**Comment by LazerFX** [comment] 2018-02-21 14:27
Could you also point me in the direction where to report that every time I modify the project properties, it overwrites the IIS bindings and removes the HTTPS certificate?  I'm not just testing this one project on my IIS box, so having it re-write and destroy my bindings is very inconvenient :D

**Comment by LazerFX** [comment] 2018-02-23 09:41
Can confirm that the issue still persists in Visual Studio 2017.5.7, which has the release note:

    Projects targeting .NET Core 2.1 or newer are not supported by Visual Studio 2017 version 15.5.

I still need to manually copy the requisite DLLs to the debug folder in order for the project to function in IIS.

**Comment by LazerFX** [comment] 2018-03-06 09:44
Sorry to 'bump' this, but is there anything I can do to assist?  Have you had chance to look at it?  Can I provide logs or more details?

**Comment by BillHiebert** [comment] 2018-03-08 23:29
I opened an TFS issue for this: https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=579096

**Comment by LazerFX** [comment] 2018-03-09 11:53
Thanks for the update.  I guess that's an internal Microsoft repository, as I have no access to it ;)  If there is anything I can assist in further identifying or tracing this, please let me know.

**Comment by LazerFX** [comment] 2018-03-16 13:51
Issue still occurs in 15.6.2

**Comment by abpiskunov** [comment] 2018-04-17 21:26
I tried the repro solution on 15.7 P3 and it was debugging fine with IIS and Chrome. I don't have Resharper though. Was anyone else able to repro it on and VS build?

**Comment by abpiskunov** [comment] 2018-04-17 22:40
@LazerFX could you confirm something: does it work if you run (not debug) the project via Ctrl+F5? Also, since it only reproed so far on your machine, could you try to get fusion log to see what exactly happens during Jetbrains.Annotation resolution? If it was restored and exists on disk, i don't see how it could not be found, unless some mismatching runtime subfolder is used form the package...

**Comment by LazerFX** [comment] 2018-04-23 12:32
Apologies for the delay in responding to your queries - I was recovering from Bacterial Tonsillitis (I don't recommend this!).

I've just upgraded to Visual Studio 15.6.6, cleared out the OBJ/BIN folders and re-run the project through IIS (Run as administrator, as always), and it has run without issue - it still doesn't include the DLLs, but it also doesn't fail asking for the DLLs.

It seems that the a version between 15.6.2 and 15.6.6 has resolved the issue; debugging and non-debugging function as expected (hit F5 / CTRL+F5 and It Just Runs™).  Thanks all for your assistance in this matter.

**Comment by abpiskunov** [comment] 2018-04-23 15:40
I see. Yes, it should not copy , it is expected. Good that it is working now. I will close this issue, please re-open if see it again in newer versions of VS and Sdk.

**Closed by abpiskunov** 2018-04-23 15:40 UTC
