### ISSUE TITLE
dotnet new sln overwrites itself

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#5652] opened 2017-02-10 01:24 UTC
## Steps to reproduce
dotnet new sln
dotnet new sln

## Expected  behavior
Error because sln exists

## Actual behavior
sln is overwritten

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\work\dotnets\1.0.0-rc4-004777\sdk\1.0.0-rc4-004777

**Comment by mlorbetske** [comment] 2017-02-10 04:08
This is actually an expected behavior for now - non-project (item) templates will overwrite content with the same name. I've filed https://github.com/dotnet/templating/issues/297 so that we can prompt & ask for confirmation in cases where we'd currently overwrite

**Comment by mlorbetske** [comment] 2017-02-10 04:10
Also filed https://github.com/dotnet/templating/issues/298 to do the actual prompting. We can track this on the templating repo unless we want to keep the issue here.

**Comment by livarcocc** [comment] 2017-02-10 04:38
Closing this issue since the relevant changes are in the dotnet/templating side of things.

**Closed by livarcocc** 2017-02-10 04:38 UTC
