### ISSUE TITLE
Offline does not respect global.json

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#3610] opened 2016-06-16 16:31 UTC
## Steps to reproduce

Set a global.json file which also sets a NuGet cache folder.
Run dotnet for the first time in a folder under the global.json
## Expected  behavior

We run the dotnet first run experience and we restore packages from the archive into the folder specified in the global.json file. We also right the sentinel to the folder in the global.json.
## Actual behavior

We will restore packages and write sentinel to the folder specified either in the NUGET_CACHE environment variable or in the user's HOME NuGet cache.

We are not honoring the settings from global.json.

For the sentinel, we don't pass it to the class that resolves the NuGet cache path.
For the restore, we do a dotnet new followed by a dotnet restore in a temp folder, which won't be under the folder containing the global.json. We need to either create a new global.json with the NuGet cache path set for the "fake" restore or maybe even copy the one we found.

cc @eerhardt @ericstj @brthor

**Comment by brthor** [comment] 2016-06-16 17:42
Or from the Nuget.config

The global.json setting was deprecated per @emgarten

**Comment by ericstj** [comment] 2016-06-16 18:05
I believe NuGet.config isn't honored at all by CLI: https://github.com/dotnet/cli/issues/2714.

**Comment by piotrpMSFT** [comment] 2016-11-13 02:41
This is a dupe of https://github.com/NuGet/Home/issues/3915

**Closed by piotrpMSFT** 2016-11-13 02:41 UTC

**Comment by MartinJohns** [comment] 2017-01-29 11:07
@brthor 

> The global.json setting was deprecated per @emgarten

Is there any news about the replacement? I always read about the changes to the `csproj` format, but no changes to the `sln` format. Also in this article (https://msdn.microsoft.com/en-us/magazine/mt791801.aspx) written on January 2017 by Mark Michaelis he mentions that `global.json` is still fully supported.
