### ISSUE TITLE
Folder permission is broken for Mac OS X.

### ISSUE THREAD

**Issue by Kimi-Arthur** [dotnet/cli#325] opened 2015-11-25 06:36 UTC
After installing dotnet-cli with the pkg file. The group / other 's "x" bit is not set for the folders including and under "/usr/local/share/dotnet/cli".
This makes the binary uncallable since the installation is using "root" user.

**Comment by blackdwarf** [comment] 2015-11-25 16:55
@Kimi-Arthur this sounds like a regression. Can you invoke `dotnet` from the shell or does that not work?

**Comment by brthor** [comment] 2015-11-25 18:54
+1 hit this issue and had to use `sudo dotnet` frequently

**Comment by Kimi-Arthur** [comment] 2015-11-25 18:57
To @brthor , one workaround is to add "x" bits for all folders under /usr/local/share/dotnet/cli"

**Comment by blackdwarf** [comment] 2015-11-25 18:57
@brthor @Kimi-Arthur the weird part is that it is not repro'd on my machine, so this is why I'm asking. Can you share a `ls -lhF` on the `/usr/local/share/dotnet/cli/bin` dir on your machines after installing latest?

**Comment by brthor** [comment] 2015-11-25 19:00
@blackdwarf Already adjusted my perms unfortunately. This should fix it though:

`sudo chmod -R +x /usr/local/share/dotnet/cli`

Obviously it's not optimal though since you are making everything executable.

**Comment by blackdwarf** [comment] 2015-11-25 19:30
@brthor I **really** dislike that approach. The `--ownership preserve` switch to `pkgbuild` should've kept the permisssions properly.

**Comment by brthor** [comment] 2015-11-25 20:13
@blackdwarf I am not familiar with that switch, but does it preserve permissions or ownership?

Permissions are the issue here, not necessarily ownership.

**Comment by muratg** [comment] 2015-11-25 20:45
@BrennanConroy recently fixed the same issue for `dnx` PKG.  Please feel free to ping with him as needed.

**Comment by Kimi-Arthur** [comment] 2015-11-26 01:56
The command failed with permission denied. Got:

> ls: /usr/local/share/dotnet/cli/bin: Permission denied

 And I try to do with `sudo`. It works. Please note that the user `pimix` is some other user on this machine.

total 226824
-rw-r--r--    1 pimix  staff   439K Nov 25 07:55 Microsoft.CSharp.dll
-rw-r--r--    1 pimix  staff    26K Nov 25 07:54 Microsoft.CodeAnalysis.CSharp.Scripting.dll
-rw-r--r--    1 pimix  staff   3.9M Nov 25 07:55 Microsoft.CodeAnalysis.CSharp.dll
-rw-r--r--    1 pimix  staff    17M Nov 25 07:56 Microsoft.CodeAnalysis.CSharp.ni.dll
-rw-r--r--    1 pimix  staff   113K Nov 25 07:54 Microsoft.CodeAnalysis.Scripting.dll
-rw-r--r--    1 pimix  staff   4.8M Nov 25 07:55 Microsoft.CodeAnalysis.VisualBasic.dll
-rw-r--r--    1 pimix  staff    20M Nov 25 07:56 Microsoft.CodeAnalysis.VisualBasic.ni.dll
-rw-r--r--    1 pimix  staff   1.9M Nov 25 07:55 Microsoft.CodeAnalysis.dll
-rw-r--r--    1 pimix  staff    15M Nov 25 07:56 Microsoft.CodeAnalysis.ni.dll
-rw-r--r--    1 pimix  staff   8.0K Nov 25 07:55 Microsoft.DotNet.Compiler.Common.dll
-rw-r--r--    1 pimix  staff   1.7K Nov 25 07:55 Microsoft.DotNet.Compiler.Common.pdb
-rw-r--r--    1 pimix  staff    95K Nov 25 07:55 Microsoft.DotNet.ProjectModel.dll
-rw-r--r--    1 pimix  staff    37K Nov 25 07:55 Microsoft.DotNet.ProjectModel.pdb
-rw-r--r--    1 pimix  staff   4.0K Nov 25 07:55 Microsoft.Extensions.CommandLineUtils.Sources.dll
-rw-r--r--    1 pimix  staff    25K Nov 25 07:55 Microsoft.Extensions.FileSystemGlobbing.dll
-rw-r--r--    1 pimix  staff   3.5K Nov 25 07:55 Microsoft.Extensions.HashCodeCombiner.Sources.dll
-rw-r--r--    1 pimix  staff   4.0K Nov 25 07:55 Microsoft.Extensions.JsonParser.Sources.dll
-rw-r--r--    1 pimix  staff   9.0K Nov 25 07:55 Microsoft.Win32.Primitives.dll
-rw-r--r--    1 pimix  staff    80K Nov 25 07:55 NuGet.Frameworks.dll
-rw-r--r--    1 pimix  staff    18K Nov 25 07:55 NuGet.Logging.dll
-rw-r--r--    1 pimix  staff    28K Nov 25 07:55 NuGet.Packaging.Core.Types.dll
-rw-r--r--    1 pimix  staff    28K Nov 25 07:55 NuGet.Packaging.Core.dll
-rw-r--r--    1 pimix  staff    81K Nov 25 07:55 NuGet.Packaging.dll
-rw-r--r--    1 pimix  staff    40K Nov 25 07:55 NuGet.Versioning.dll
-rw-r--r--    1 pimix  staff   1.6K Nov 25 07:55 README.md
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.AppContext.dll
-rw-r--r--    1 pimix  staff    91K Nov 25 07:55 System.Collections.Concurrent.dll
-rw-r--r--    1 pimix  staff   196K Nov 25 07:55 System.Collections.Immutable.dll
-rw-r--r--    1 pimix  staff   1.5M Nov 25 07:56 System.Collections.Immutable.ni.dll
-rw-r--r--    1 pimix  staff    87K Nov 25 07:55 System.Collections.NonGeneric.dll
-rw-r--r--    1 pimix  staff   102K Nov 25 07:55 System.Collections.dll
-rw-r--r--    1 pimix  staff    40K Nov 25 07:55 System.CommandLine.dll
-rw-r--r--    1 pimix  staff    31K Nov 25 07:55 System.ComponentModel.EventBasedAsync.dll
-rw-r--r--    1 pimix  staff    59K Nov 25 07:55 System.Console.dll
-rw-r--r--    1 pimix  staff    21K Nov 25 07:55 System.Diagnostics.Contracts.dll
-rw-r--r--    1 pimix  staff    23K Nov 25 07:55 System.Diagnostics.Debug.dll
-rw-r--r--    1 pimix  staff    12K Nov 25 07:55 System.Diagnostics.FileVersionInfo.dll
-rw-r--r--    1 pimix  staff    68K Nov 25 07:55 System.Diagnostics.Process.dll
-rw-r--r--    1 pimix  staff    22K Nov 25 07:55 System.Diagnostics.StackTrace.dll
-rw-r--r--    1 pimix  staff    22K Nov 25 07:55 System.Diagnostics.Tools.dll
-rw-r--r--    1 pimix  staff    36K Nov 25 07:55 System.Diagnostics.Tracing.dll
-rw-r--r--    1 pimix  staff   110K Nov 25 07:55 System.Dynamic.Runtime.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Globalization.Calendars.dll
-rwxr-xr-x    1 pimix  staff    48K Nov 25 07:55 System.Globalization.Native.dylib*
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Globalization.dll
-rw-r--r--    1 pimix  staff    28K Nov 25 07:54 System.IO.Compression.ZipFile.dll
-rw-r--r--    1 pimix  staff   101K Nov 25 07:55 System.IO.Compression.dll
-rw-r--r--    1 pimix  staff    22K Nov 25 07:55 System.IO.FileSystem.Primitives.dll
-rw-r--r--    1 pimix  staff    35K Nov 25 07:55 System.IO.FileSystem.Watcher.dll
-rw-r--r--    1 pimix  staff    77K Nov 25 07:55 System.IO.FileSystem.dll
-rw-r--r--    1 pimix  staff    49K Nov 25 07:55 System.IO.Pipes.dll
-rw-r--r--    1 pimix  staff    24K Nov 25 07:55 System.IO.dll
-rw-r--r--    1 pimix  staff   451K Nov 25 07:55 System.Linq.Expressions.dll
-rw-r--r--    1 pimix  staff   101K Nov 25 07:55 System.Linq.dll
-rwxr-xr-x    1 pimix  staff    46K Nov 25 07:55 System.Native.dylib*
-rwxr-xr-x    1 pimix  staff    15K Nov 25 07:55 System.Net.Http.Native.dylib*
-rw-r--r--    1 pimix  staff    55K Nov 25 07:55 System.Net.NameResolution.dll
-rw-r--r--    1 pimix  staff    21K Nov 25 07:55 System.Net.Primitives.dll
-rw-r--r--    1 pimix  staff   184K Nov 25 07:55 System.Net.Sockets.dll
-rw-r--r--    1 pimix  staff    49K Nov 25 07:55 System.ObjectModel.dll
-rw-r--r--    1 pimix  staff   657K Nov 25 07:55 System.Private.DataContractSerialization.dll
-rw-r--r--    1 pimix  staff   656K Nov 25 07:55 System.Private.Networking.dll
-rw-r--r--    1 pimix  staff   106K Nov 25 07:55 System.Private.Uri.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Reflection.Emit.ILGeneration.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Reflection.Emit.Lightweight.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Reflection.Emit.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Reflection.Extensions.dll
-rw-r--r--    1 pimix  staff   281K Nov 25 07:55 System.Reflection.Metadata.dll
-rw-r--r--    1 pimix  staff   1.7M Nov 25 07:56 System.Reflection.Metadata.ni.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Reflection.Primitives.dll
-rw-r--r--    1 pimix  staff    28K Nov 25 07:55 System.Reflection.TypeExtensions.dll
-rw-r--r--    1 pimix  staff    21K Nov 25 07:55 System.Reflection.dll
-rw-r--r--    1 pimix  staff    34K Nov 25 07:55 System.Resources.ReaderWriter.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Resources.ResourceManager.dll
-rw-r--r--    1 pimix  staff    56K Nov 25 07:55 System.Runtime.Extensions.dll
-rw-r--r--    1 pimix  staff    22K Nov 25 07:55 System.Runtime.Handles.dll
-rw-r--r--    1 pimix  staff   8.0K Nov 25 07:55 System.Runtime.InteropServices.RuntimeInformation.dll
-rw-r--r--    1 pimix  staff    33K Nov 25 07:55 System.Runtime.InteropServices.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Runtime.Loader.dll
-rw-r--r--    1 pimix  staff    70K Nov 25 07:55 System.Runtime.Numerics.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Runtime.Serialization.Json.dll
-rw-r--r--    1 pimix  staff    29K Nov 25 07:55 System.Runtime.Serialization.Primitives.dll
-rw-r--r--    1 pimix  staff    39K Nov 25 07:55 System.Runtime.dll
-rw-r--r--    1 pimix  staff    57K Nov 25 07:55 System.Security.Claims.dll
-rw-r--r--    1 pimix  staff    39K Nov 25 07:55 System.Security.Cryptography.Algorithms.dll
-rw-r--r--    1 pimix  staff    32K Nov 25 07:55 System.Security.Cryptography.Encoding.dll
-rw-r--r--    1 pimix  staff    23K Nov 25 07:55 System.Security.Cryptography.Hashing.Algorithms.dll
-rwxr-xr-x    1 pimix  staff    55K Nov 25 07:55 System.Security.Cryptography.Native.dylib*
-rw-r--r--    1 pimix  staff    29K Nov 25 07:55 System.Security.Cryptography.OpenSsl.dll
-rw-r--r--    1 pimix  staff    44K Nov 25 07:55 System.Security.Cryptography.Primitives.dll
-rw-r--r--    1 pimix  staff   126K Nov 25 07:55 System.Security.Cryptography.X509Certificates.dll
-rw-r--r--    1 pimix  staff    79K Nov 25 07:55 System.Security.Principal.Windows.dll
-rw-r--r--    1 pimix  staff    21K Nov 25 07:55 System.Security.Principal.dll
-rw-r--r--    1 pimix  staff   726K Nov 25 07:55 System.Text.Encoding.CodePages.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Text.Encoding.Extensions.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Text.Encoding.dll
-rw-r--r--    1 pimix  staff   111K Nov 25 07:55 System.Text.RegularExpressions.dll
-rw-r--r--    1 pimix  staff    29K Nov 25 07:55 System.Threading.Overlapped.dll
-rw-r--r--    1 pimix  staff    57K Nov 25 07:55 System.Threading.Tasks.Parallel.dll
-rw-r--r--    1 pimix  staff    26K Nov 25 07:55 System.Threading.Tasks.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Threading.Thread.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Threading.ThreadPool.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:55 System.Threading.Timer.dll
-rw-r--r--    1 pimix  staff    41K Nov 25 07:55 System.Threading.dll
-rw-r--r--    1 pimix  staff   590K Nov 25 07:55 System.Xml.ReaderWriter.dll
-rw-r--r--    1 pimix  staff   109K Nov 25 07:55 System.Xml.XDocument.dll
-rw-r--r--    1 pimix  staff    36K Nov 25 07:55 System.Xml.XPath.XDocument.dll
-rw-r--r--    1 pimix  staff   184K Nov 25 07:55 System.Xml.XPath.dll
-rw-r--r--    1 pimix  staff   135K Nov 25 07:55 System.Xml.XmlDocument.dll
-rw-r--r--    1 pimix  staff   313K Nov 25 07:55 System.Xml.XmlSerializer.dll
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 corehost*
-rwxr-xr-x    1 pimix  staff    22K Nov 25 07:55 corerun*
-rwxr-xr-x    1 pimix  staff   5.7M Nov 25 07:55 crossgen*
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 csc*
-rw-r--r--    1 pimix  staff    37K Nov 25 07:55 csc.dll
-rw-r--r--    1 pimix  staff   184K Nov 25 07:56 csc.ni.dll
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 csi*
-rw-r--r--    1 pimix  staff    12K Nov 25 07:54 csi.dll
drwxr-xr-x  119 pimix  staff   4.0K Nov 25 07:56 dnx/
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:53 dotnet*
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:53 dotnet-compile*
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:54 dotnet-compile-csc*
-rw-r--r--    1 pimix  staff    44K Nov 25 07:54 dotnet-compile-csc.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:54 dotnet-compile-csc.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 dotnet-compile-native*
-rw-r--r--    1 pimix  staff    60K Nov 25 07:55 dotnet-compile-native.dll
-rw-r--r--    1 pimix  staff    22K Nov 25 07:55 dotnet-compile-native.pdb
-rw-r--r--    1 pimix  staff    59K Nov 25 07:53 dotnet-compile.dll
-rw-r--r--    1 pimix  staff    20K Nov 25 07:53 dotnet-compile.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 dotnet-init*
-rw-r--r--    1 pimix  staff    42K Nov 25 07:55 dotnet-init.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:55 dotnet-init.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:54 dotnet-pack*
-rw-r--r--    1 pimix  staff    77K Nov 25 07:54 dotnet-pack.dll
-rw-r--r--    1 pimix  staff    24K Nov 25 07:54 dotnet-pack.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:54 dotnet-publish*
-rw-r--r--    1 pimix  staff    43K Nov 25 07:54 dotnet-publish.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:54 dotnet-publish.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:54 dotnet-repl*
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:54 dotnet-repl-csi*
-rw-r--r--    1 pimix  staff    40K Nov 25 07:54 dotnet-repl-csi.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:54 dotnet-repl-csi.pdb
-rw-r--r--    1 pimix  staff    40K Nov 25 07:54 dotnet-repl.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:54 dotnet-repl.pdb
-rwxr-xr-x    1 pimix  staff   877B Nov 25 07:56 dotnet-restore*
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 dotnet-run*
-rw-r--r--    1 pimix  staff    42K Nov 25 07:55 dotnet-run.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:55 dotnet-run.pdb
-rw-r--r--    1 pimix  staff    42K Nov 25 07:53 dotnet.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:53 dotnet.pdb
-rwxr-xr-x    1 pimix  staff   7.6M Nov 25 07:55 libcoreclr.dylib*
-rwxr-xr-x    1 pimix  staff   1.0M Nov 25 07:55 libdbgshim.dylib*
-rwxr-xr-x    1 pimix  staff   3.3M Nov 25 07:55 libmscordaccore.dylib*
-rwxr-xr-x    1 pimix  staff   2.1M Nov 25 07:55 libmscordbi.dylib*
-rwxr-xr-x    1 pimix  staff   2.4M Nov 25 07:55 libprotojit.dylib*
-rwxr-xr-x    1 pimix  staff   460K Nov 25 07:55 libsos.dylib*
-rw-r--r--    1 pimix  staff   2.1M Nov 25 07:55 mscorlib.dll
-rw-r--r--    1 pimix  staff   9.1M Nov 25 07:56 mscorlib.ni.dll
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 resgen*
-rw-r--r--    1 pimix  staff    41K Nov 25 07:55 resgen.dll
-rw-r--r--    1 pimix  staff    14K Nov 25 07:55 resgen.pdb
-rwxr-xr-x    1 pimix  staff    65K Nov 25 07:55 vbc*
-rw-r--r--    1 pimix  staff    37K Nov 25 07:55 vbc.dll
-rw-r--r--    1 pimix  staff   184K Nov 25 07:56 vbc.ni.dll


The key thing I believe is the folders (and parent folders) 's "x" bit.

See `ls -lhF /usr/local/share/dotnet`:

> total 0
> drwxr--r--  6 pimix  staff   204B Nov 26 09:48 cli/

I think since it's "readable", it probably should also be executable since it's a directory.

**Comment by blackdwarf** [comment] 2015-11-26 02:28
@Kimi-Arthur my installation looks the same and stuff works (dotnet can be invoked without sudo). Now, I thought that it is the artifact of me building the package locally, so that the --ownership switch actually preserves stuff properly. I've just installed the online PKG and I still cannot repro this, which is why I'm confused.

**Comment by Kimi-Arthur** [comment] 2015-11-26 02:33
So what is your permission for folders under `/usr/local/share/dotnet`? Is it 755 or 744?

**Comment by blackdwarf** [comment] 2015-11-26 02:43
@Kimi-Arthur below:
drwxr--r--  178 zlatkoknezevic  staff   5.9K Nov 25 13:55 bin/
drwxr--r--    3 zlatkoknezevic  staff   102B Nov 25 13:54 runtime/

Looks like 744?

**Comment by Kimi-Arthur** [comment] 2015-11-26 03:11
So the thing is. If the tool is installed by one user, it's not usable by another. (I'm not sure whether this behaviour is considered a bug?)

Because the symlink in /usr/local/bin points to some path under `/usr/local/share/dotnet`, it won't be able to get there because it cannot `execute` on the folders to reach the real binary. This is the problem.

Quoted from http://unix.stackexchange.com/questions/21251/how-do-directory-permissions-in-linux-work
> The execute bit allows the affected user to enter the directory, and access files and directories inside

To make the symlink find the real binary, the user must have permission to `execute` on all folders all the way to binary. That is the user needs to have `read` and `execute` permissions on the following items:

> /usr/local/share/dotnet/cli/bin/
> /usr/local/share/dotnet/cli/
> /usr/local/share/dotnet/
> /usr/local/share/
> /usr/local/
> /usr/
> /

P.S. It surely also needs "execute" permission on `/usr/local/share/dotnet/cli/bin/dotnet` to run.

**Comment by blackdwarf** [comment] 2015-11-26 05:50
@Kimi-Arthur ah, so...that's the deal. Nice piece of debugging. So the switch to pkgbuild works but not for multiuser scenarios. Can you try to install as your user and see if it repros? Or have you tried that already?

**Comment by Kimi-Arthur** [comment] 2015-11-26 05:58
I don't know why the user isn't myself. But `untar` the `tar` package will work (whose user is myself).
So, this should probably show the cause.

**Comment by blackdwarf** [comment] 2015-12-15 00:47
This is going to be tracked via #492, so closing this one out.

**Closed by blackdwarf** 2015-12-15 00:47 UTC
Labels: bug
