### ISSUE TITLE
Microsoft.Extensions.DependencyModel package has the dotnet5.4 binary under net451 directory

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#882] opened 2016-01-16 01:33 UTC
Seeing this with issue in the `1.0.0-dev-000973` build of the package. The `lib\net451\Microsoft.Extensions.DependencyModel.dll` binary has an `TargetFrameworkAttribute` that says '.NETPlatform,Version=v5.4` and is compiled against the 4.1.0.0 of System.Reflection which doesn't exist in net451.

**Comment by piotrpMSFT** [comment] 2016-01-16 06:02
#760 should be the root cause. @livarcocc

**Comment by davidfowl** [comment] 2016-01-16 06:04
Is that really the root cause?

**Comment by piotrpMSFT** [comment] 2016-01-16 22:12
We will find out. Given, however, that Publish stomps on its own output, it should be at least 'a' cause.

**Comment by davidfowl** [comment] 2016-01-18 10:43
This is blocking ASP.NET, marking it as such

**Comment by pranavkm** [comment] 2016-01-19 17:33
Is there some way to get to the net451 binaries? I'd be happy to workaround this issue locally until you're able to produce a package with the fix.

**Comment by piotrpMSFT** [comment] 2016-01-19 18:32
Yea, you should be able to manually publish into the right folder layout. @livarcocc or@davidfowl should know how to make this work.

**Comment by davidfowl** [comment] 2016-01-19 18:34
I'm not aware of what the actual bug is, who is working on this? It looks like the packages on the feed are bad..

**Comment by pranavkm** [comment] 2016-01-22 23:46
Any update on this? We're still blocked by this issue.

**Comment by livarcocc** [comment] 2016-01-22 23:52
I have #760 in the CI right now. Which might fix this, but CI is kind of nasty at the moment.

**Comment by piotrpMSFT** [comment] 2016-01-22 23:54
and I understand that @pranavkm is uploading logging 16011, so the circular dependency is complete!

**Comment by livarcocc** [comment] 2016-01-23 00:59
There is another change that I need to make to get the packs filled out correctly for each Tfm. It is in the works. I should have a PR for it soon.

**Comment by livarcocc** [comment] 2016-01-23 01:38
PR https://github.com/dotnet/cli/pull/989 will fix this. I checked and the generated nupkg has all current tfm inside of it.

**Closed** 2016-01-23 07:59 UTC
Labels: blocking-partner

**Comment by pranavkm** [comment] 2016-01-25 15:46
Yup, looks like it's fixed in build `001064`.
