### ISSUE TITLE
global.json sdk should not be a hint

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/cli#5165] opened 2016-12-28 14:23 UTC
Currently when the CLI version pinned in global.json is not found we fallback to the latest version:

![image](https://cloud.githubusercontent.com/assets/245275/21523757/3b6236a6-cd11-11e6-8b38-60d9cb0d0e6b.png)

(Note the change from `*121` to `*131` in the global.json sdk section)

This is super trappy, can we either:

- make all `dotnet` commands fail
- add a baked in `dotnet validate-sdk` command that I can use in my builds

**Comment by davidfowl** [comment] 2016-12-28 15:40
I'm surprised it doesn't fail. It does fail in visual studio....

**Comment by vcsjones** [comment] 2016-12-28 16:50
Dupe of #3662.

**Comment by livarcocc** [comment] 2016-12-28 18:19
this is a problem in the host. @vcsjones is pointing to the right issue. Closing this one.

**Closed by livarcocc** 2016-12-28 18:19 UTC
