### ISSUE TITLE
Migration: While migrating web projects, dotnet publish-iis needs to be removed from postpublishscripts section.

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#4731] opened 2016-11-15 22:11 UTC
## Steps to reproduce
Migrate an xproj webproject with reference to publish-iis

## Expected  behavior
No error during publish

## Actual behavior
dotnet publish-iis not found issue.

In the csproj, this section is added after migration, this should not be added during migration.

  <Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="dotnet publish-iis --publish-folder $(TargetDir) --framework $(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)" />
  </Target>

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment] 2016-11-15 22:13
Dupe of https://github.com/dotnet/cli/issues/4612.

**Closed by livarcocc** 2016-11-15 22:13 UTC
