### ISSUE TITLE
'Failed to initialize CoreCLR' on dotnet-watch

### ISSUE THREAD

**Issue by saurabsa** [dotnet/cli#2055] opened 2016-03-25 16:48 UTC
## Steps to reproduce
project.json:

_"tools": {
    "dotnet-publish-iis": "1.0.0-rc2-20094",
    "dotnet-razor-tooling": "1.0.0-rc2-20094",
    "dotnet-watch": "1.0.0-*"
  }_

`dotnet watch`

## Expected  behavior
I assume it should have worked.

## Actual behavior
**Failed to initialize CoreCLR, HRESULT: 0x80004005**

## Environment data
`dotnet --version` output:

> .NET Command Line Tools (1.0.0-dev-001698)
> 
> Product Information:
>  Version:     1.0.0-dev-001698
>  Commit Sha:  N/A
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  14.04
>  OS Platform: Linux
>  Runtime Id:  ubuntu.14.04-x64

**Comment by brthor** [comment] 2016-03-25 16:55
looking into this now, closing as a dupe of #2026

**Closed** 2016-03-25 18:00 UTC
